---
permalink: install-ip/concept_mediator_requirements.html 
sidebar: sidebar 
keywords: ontap, mediator, assist, metrocluster, ip, configuration, perform, automatic, unplan, switchover, physical, repository, status, information, configuring, configure, install, configuring, configure, mtu size, packet loss, bandwidth, firewall, rhel, centos, linux, revert, kernal, upgrade, latency 
summary: ONTAP 9.7 以降、ONTAP Mediator は、ステータス情報用の物理的に別のリポジトリを提供することで、MetroCluster IP 構成による計画外の自動スイッチオーバーの実行を支援できます。 
---
= MetroCluster IP構成にONTAP Mediatorをインストールする準備
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ご使用の環境が特定の要件を満たしている必要があり

1つのディザスタリカバリグループ（DRグループ）に次の要件が適用されます。の詳細を確認してください link:concept_parts_of_an_ip_mcc_configuration_mcc_ip.html#disaster-recovery-dr-groups["DR グループ"]。

* Linux バージョンを更新する予定がある場合は、最新バージョンの ONTAP Mediator をインストールする前に更新してください。
* ONTAP Mediator と MetroCluster Tiebreaker ソフトウェアの両方を同じ MetroCluster 構成で使用しないでください。
* ONTAP Mediator は、MetroCluster サイトとは別の場所にある Linux ホストにインストールする必要があります。
+
ONTAP メディエーターと各サイトの間の接続には、2つの異なる障害ドメインが必要です。

* ONTAP 9.7 以降では、自動計画外スイッチオーバーがサポートされます。
* ONTAP 9.18.1 およびONTAP Mediator 1.11 以降では、1 つのONTAP Mediator インスタンスで最大 10 個のMetroCluster構成を同時に管理できます。以前のリリースでは、 ONTAP Mediator は最大 5 つのMetroCluster構成を同時にサポートできました。
* ONTAP 9.18.1 以降では、 MetroCluster IP 構成のONTAP Mediator 1.11 以降で IPv6 がサポートされます。




== MetroCluster構成でONTAP Mediatorを使用するためのネットワーク要件

MetroCluster 構成に ONTAP Mediator をインストールするには、構成がいくつかのネットワーク要件を満たしていることを確認する必要があります。

* レイテンシ
+
最大レイテンシは75ms（RTT）未満

+
ジッターは5ミリ秒以下である必要があります。

* MTU
+
MTU サイズは 1400 以上にする必要があります。

* パケット損失
+
Internet Control Message Protocol（ICMP）とTCPトラフィックの両方で、パケット損失は0.01%未満でなければなりません。

* 帯域幅
+
ONTAP Mediator と 1 つの DR グループ間のリンクには、少なくとも 20 Mbps の帯域幅が必要です。

* 独立した接続性
+
各サイトとONTAP メディエーターは個別に接続する必要があります。一方のサイトで障害が発生しても、影響を受けない他の2つのサイト間のIP接続は中断しないでください。





== MetroCluster構成におけるONTAP Mediatorのホスト要件

構成が複数のホスト要件を満たしていることを確認する必要があります。

* ONTAP メディエーターは、2つのONTAP クラスタから物理的に分離された外部サイトにインストールする必要があります。
* ONTAP メディエーターでは、ホストオペレーティングシステムの最小要件であるCPUおよびメモリ（RAM）は必要ありません。
* ホストオペレーティングシステムの最小要件に加えて、使用可能なディスクスペースが少なくとも30GB必要です。
+
** 各DRグループには、最大200MBのディスクスペースが必要です。






== ONTAP メディエーターのファイアウォール要件

ONTAP メディエーターは、複数のポートを使用して特定のサービスと通信します。

サードパーティのファイアウォールを使用している場合は、次の手順を実行します。

* HTTPS アクセスが有効になっている必要があります。
* ポート 31784 および 3260 でアクセスを許可するように設定されている必要があります。
+
Red Hat または CentOS のデフォルトのファイアウォールを使用している場合は、メディエーターのインストール時に自動的に設定されます。



次の表に、ファイアウォールで許可する必要があるポートを示します。

[NOTE]
====
* iSCSIポートは、MetroCluster IP構成でのみ必要です。
* 22/TCPポートは通常の動作には必要ありませんが、メンテナンスのために一時的に有効にし、メンテナンスセッションの終了後に無効にすることができます。


====
|===


| ポート / サービス | ソース | 方向 | 宛先 | 目的 


 a| 
22 / TCP
 a| 
管理ホスト
 a| 
インバウンド
 a| 
ONTAPメディエーター
 a| 
SSH / ONTAPメディエーターの管理



 a| 
31784/TCP
 a| 
クラスタ管理およびノード管理LIF
 a| 
インバウンド
 a| 
ONTAP メディエーター Web サーバ
 a| 
REST API （ HTTPS ）



 a| 
3260 TCP
 a| 
ノード管理LIF
 a| 
双方向
 a| 
ONTAP メディエーターの iSCSI ターゲット
 a| 
メールボックス用の iSCSI データ接続

|===


== MetroCluster構成でONTAP Mediatorをアップグレードするためのガイドライン

ONTAP Mediator をアップグレードする場合は、Linux バージョンの要件を満たし、アップグレードのガイドラインに従う必要があります。

* ONTAP Mediator は、直前のバージョンから現在のバージョンにアップグレードできます。
* MetroCluster 9.7 以降を実行する ONTAP IP 構成では、すべてのメディエーターのバージョンがサポートされます。


link:https://docs.netapp.com/us-en/ontap/mediator/index.html["ONTAPメディエーターをインストールまたはアップグレードする"^]



== アップグレード後

メディエーターとオペレーティングシステム問題のアップグレードが完了したら、「 storage iscsi-initiator show 」コマンドを実行して、メディエーター接続が稼働していることを確認する必要があります。
