---
permalink: install-ip/concept-requirements-isls.html 
sidebar: sidebar 
keywords: isl, isls, layer 2, layer 3, shared switch 
summary: ここでは、すべてのMetroCluster IP構成およびネットワークトポロジでMetroClusterトラフィックを伝送するスイッチ間リンク（ISL）の要件について説明します。 
---
= ISL に関する考慮事項
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


すべてのMetroCluster IP構成およびネットワークトポロジでMetroClusterトラフィックを伝送するスイッチ間リンク（ISL）には、一定の要件があります。これらの要件は、お客様のスイッチ間でISLを直接接続するか共有するかに関係なく、MetroClusterトラフィックを伝送するすべてのISLに適用されます。



== MetroCluster ISLの一般的な要件

すべてのMetroCluster IP構成の次の環境ISL：

* ISLの数は両方のファブリックで同じである必要があります。
* 1つのファブリックのISLは、速度と長さがすべて同じである必要があります。
* ISLの速度と長さは、両方のファブリックで同じである必要があります。
* サポートされるファブリック1とファブリック2の距離の最大差は20km（0.2ms）です。
* ISLのトポロジは同じである必要があります。たとえば、すべてのリンクを直接リンクにするか、WDMを使用する場合はすべてのリンクでWDMを使用する必要があります。
* ISLの速度は10Gbps以上である必要があります。
* ファブリックごとに10Gbps ISLポートが少なくとも1つ必要です。




=== ISL のレイテンシとパケット損失の制限

安定した状態でのMetroCluster構成でのsite_Aとsite_BのMetroCluster IPスイッチ間の次の環境ラウンドトリップトラフィック。

* 2 つの MetroCluster サイト間の距離が長くなるとレイテンシが増加します。通常、ラウンドトリップ遅延時間は 100km （ 62 マイル）ごとに 1 ミリ秒程度です。レイテンシは、ネットワーク上のISLリンクの帯域幅、パケットドロップレート、およびジッタに関して、ネットワークのService Level Agreement（SLA；サービスレベルアグリーメント）にも左右されます。低帯域幅、高ジッタ、およびランダムなパケットドロップは、パケット配信を成功させるために、スイッチまたはコントローラモジュール上のTCPエンジンによって異なるリカバリメカニズムをもたらします。このようなリカバリメカニズムによって、全体的なレイテンシが増加することがあり構成のラウンドトリップレイテンシおよび最大距離の要件の詳細については、を参照してください link:https://hwu.netapp.com/["Hardware Universe の略。"^]
* レイテンシに影響するすべてのデバイスについて考慮する必要があります。
* 。 link:https://hwu.netapp.com/["Hardware Universe の略。"^] 距離（km）を提供します。100kmごとに1ミリ秒を割り当てる必要があります。最大距離は、最初に到達した距離によって定義されます。最大ラウンドトリップ時間（RTT）（ms）または距離（km）です。たとえば、–the _ listsの距離が300km（3ミリ秒）の場合、ISLは300km以下にすることができ、最大Hardware Universe時間は3ミリ秒のいずれか先に達した方を超えることはできません。
* パケット損失は0.01%以下でなければなりません。最大パケット損失は、MetroClusterノード間のパス上のすべてのリンクの損失と、ローカルMetroCluster IPインターフェイス上の損失の合計です。
* サポートされるジッタ値は、ラウンドトリップの場合は3ミリ秒（一方向の場合は1.5ミリ秒）です。
* ネットワークは、トラフィックのマイクロバーストや急増に関係なく、MetroClusterトラフィックに必要な帯域幅のSLAを割り当て、維持する必要があります。
* ONTAP 9.7以降を使用している場合は、2つのサイト間の中間ネットワークでMetroCluster IP構成用に4.5Gbps以上の帯域幅が確保されている必要があります。




== トランシーバとケーブルに関する考慮事項

MetroCluster ISL では、機器のベンダーがサポートしている SFP または QSFP がサポートされます。NetAppまたは機器ベンダーから提供されたSFPおよびQSFPが、スイッチおよびスイッチのファームウェアでサポートされている必要があります。

コントローラをスイッチおよびローカルクラスタのISLに接続するときは、NetAppとMetroClusterが提供するトランシーバとケーブルを使用する必要があります。



== xWDM、TDM、および外部暗号化デバイスの使用

MetroCluster IP構成でxWDM / TDMデバイスまたは暗号化を提供するデバイスを使用する場合は、次の要件を満たす必要があります。

* MetroCluster IPスイッチをxWDM / TDMに接続する場合は、スイッチとファームウェアについてベンダーが認定した外部暗号化デバイスまたはxWDM / TDM機器を使用する必要があります。動作モード（トランキングや暗号化など）に対応している必要があります。
* 暗号化を含むエンドツーエンドの全体的な遅延とジッタは、IMTおよびこのマニュアルに記載されている最大値を超えることはできません。




== サポートされるISL数とブレークアウトケーブル数

次の表に、リファレンス構成ファイル（RCF）構成を使用してMetroCluster IPスイッチに設定できる、サポートされるISLの最大数を示します。

|===


| MetroCluster IP スイッチのモデル | ポートタイプ | ISLの最大数 


 a| 
Broadcom 対応 BES-53248 スイッチ
 a| 
ネイティブポート
 a| 
ISL×4（10Gbpsまたは25Gbpsを使用）



 a| 
Broadcom 対応 BES-53248 スイッチ
 a| 
ネイティブポート（注1）
 a| 
ISL×2、40Gbpsまたは100Gbpsを使用



 a| 
Cisco 3132Q-V の設定
 a| 
ネイティブポート
 a| 
ISL×6、40Gbpsを使用



 a| 
Cisco 3132Q-V の設定
 a| 
ブレークアウトケーブル
 a| 
ISL×16（10Gbpsを使用）



 a| 
Cisco 3232C
 a| 
ネイティブポート
 a| 
ISL×6、40Gbpsまたは100Gbpsを使用



 a| 
Cisco 3232C
 a| 
ブレークアウトケーブル
 a| 
ISL×16（10Gbpsを使用）



 a| 
Cisco 9336C-FX2（NS224シェルフは接続しない）
 a| 
ネイティブポート
 a| 
ISL×6、40Gbpsまたは100Gbpsを使用



 a| 
Cisco 9336C-FX2（NS224シェルフは接続しない）
 a| 
ブレークアウトケーブル
 a| 
ISL×16（10を使用）



 a| 
Cisco 9336C-FX2（NS224シェルフの接続）
 a| 
ネイティブポート（注2）
 a| 
ISL×4、40Gbpsまたは100Gbpsを使用



 a| 
Cisco 9336C-FX2（NS224シェルフの接続）
 a| 
ブレークアウトケーブル（注2）
 a| 
ISL×16（10Gbpsを使用）



 a| 
NVIDIA SN2100
 a| 
ネイティブポート（注2）
 a| 
ISL×2、40Gbpsまたは100Gbpsを使用



 a| 
NVIDIA SN2100
 a| 
ブレークアウトケーブル（注2）
 a| 
ISL×8、10Gbpsまたは25Gbpsを使用

|===
*注1 *：BES-53248スイッチで40Gbpsまたは100GbpsのISLを使用するには、追加のライセンスが必要です。

*注2 *：同じポートがネイティブ速度とブレークアウトモードに使用されます。RCFファイルを作成するときは、ポートを標準の速度モードとブレークアウトモードのどちらで使用するかを選択する必要があります。

* 1つのMetroCluster IPスイッチのISLは、すべて同じ速度である必要があります。速度が異なるISLポートを同時に使用することはできません。
* 最適なパフォーマンスを実現するには、ネットワークごとに40GbpsのISLを少なくとも1つ使用する必要があります。FAS9000、AFF A700、またはその他の大容量プラットフォームでは、ネットワークごとに1つの10Gbps ISLを使用しないでください。



NOTE: NetAppでは、広帯域幅のISLを多数使用するのではなく、広帯域幅のISLを少数使用することを推奨しています。たとえば、4つの10Gbps ISLではなく、40Gbps ISLを1つ設定することを推奨します。複数のISLを使用する場合は、統計的なロードバランシングが最大スループットに影響する可能性があります。負荷分散が均等でないと、単一ISLのスループットまで低下する可能性があります。
