---
permalink: install-ip/concept-network-speeds-and-switchport-modes.html 
sidebar: sidebar 
keywords: metrocluster ip, metrocluster-compliant switches, metrocluster-compliant, compliant, network speed, switch port mode 
summary: MetroCluster準拠のスイッチを使用している場合は、プラットフォーム固有のネットワーク速度とスイッチポートモードの要件を確認しておく必要があります。 
---
= MetroCluster準拠スイッチのONTAPプラットフォーム固有のネットワーク速度とスイッチポートモード
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
MetroCluster準拠のスイッチを使用している場合は、プラットフォーム固有のネットワーク速度とスイッチポートモードの要件を確認しておく必要があります。

次の表に、MetroCluster準拠スイッチのネットワーク速度とスイッチポートモードをプラットフォーム別に示します。表に従ってスイッチポートモードを設定する必要があります。

[NOTE]
====
* 値がない場合は、プラットフォームをMetroCluster準拠のスイッチで使用できないことを示しています。
* AFF A30、AFF C30、AFF C60、およびFAS50システムでは、25Gbpsのネットワーク速度をサポートするために、コントローラ上のカードにQSFP-to-SFPアダプタが必要です。


====
[cols="1,2,2"]
|===
| プラットフォーム | ネットワーク速度（Gbps） | スイッチ ポート モード 


 a| 
FAS9500

AFF A900 の略

ASA A900
 a| 
100Gbpsを使用したチャンク アップロード署名要求がサポートされるようになりました。

FAS9000またはAFF A700からPCMをアップグレードする場合は40Gbps
 a| 
トランクモード



 a| 
AFF C800用

ASA C800

AFF A800

ASA A800
 a| 
40Gbpsまたは100Gbps
 a| 
アクセス モード



 a| 
FAS9000

AFF A700
 a| 
40Gbpsを使用したチャンク アップロード署名要求がサポートされるようになりました。
 a| 
アクセス モード



 a| 
FAS8300

AFF C400用

ASA C400

AFF A400

ASA A400
 a| 
40Gbpsまたは100Gbps
 a| 
トランクモード



 a| 
AFF A320
 a| 
40Gbpsまたは100Gbps
 a| 
アクセス モード



 a| 
FAS8200

AFF A300
 a| 
25Gbpsを使用したチャンク アップロード署名要求がサポートされるようになりました。
 a| 
アクセス モード



 a| 
FAS500f

AFF C250用

ASA C250

AFF A250

ASA A250
 a| 
-
 a| 
-



 a| 
FAS2750

AFF A220
 a| 
-
 a| 
-



 a| 
AFF A150

ASA A150
 a| 
-
 a| 
-



 a| 
AFF A20用
 a| 
25Gbpsを使用したチャンク アップロード署名要求がサポートされるようになりました。
 a| 
トランクモード



 a| 
AFF A30用
 a| 
25Gbpsまたは100Gbps
 a| 
トランクモード



 a| 
AFF C30
 a| 
25Gbpsまたは100Gbps
 a| 
トランクモード



 a| 
AFF C60
 a| 
25Gbpsまたは100Gbps
 a| 
トランクモード



 a| 
FAS50
 a| 
25Gbpsまたは100Gbps
 a| 
トランクモード



 a| 
AFF A50用
 a| 
100Gbpsを使用したチャンク アップロード署名要求がサポートされるようになりました。
 a| 
トランクモード



 a| 
AFF A70用
 a| 
100Gbpsを使用したチャンク アップロード署名要求がサポートされるようになりました。
 a| 
トランクモード



 a| 
AFF A90用
 a| 
100Gbpsを使用したチャンク アップロード署名要求がサポートされるようになりました。
 a| 
トランクモード



 a| 
AFF A1K用
 a| 
100Gbpsを使用したチャンク アップロード署名要求がサポートされるようになりました。
 a| 
トランクモード



 a| 
AFF C80用
 a| 
100Gbpsを使用したチャンク アップロード署名要求がサポートされるようになりました。
 a| 
トランクモード



 a| 
FAS70
 a| 
100Gbpsを使用したチャンク アップロード署名要求がサポートされるようになりました。
 a| 
トランクモード



 a| 
FAS90
 a| 
100Gbpsを使用したチャンク アップロード署名要求がサポートされるようになりました。
 a| 
トランクモード

|===