---
permalink: install-ip/concept_considerations_tdm_encryption.html 
sidebar: sidebar 
keywords: differences, eight-node, four-node, fabric-attached, stretch, metrocluster ip, storage, bridges, fc-to-sas, atto, fibrebridge, SAS, local HA, auso, automatic unplanned switchover, array luns, mediator, tiebreaker 
summary: MetroCluster IP 構成で多重化機器を使用する場合は、一定の考慮事項に注意する必要があります。 
---
= MetroCluster IP 構成で TDM / xWDM および暗号化機器を使用
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
MetroCluster IP 構成で多重化機器を使用する場合は、一定の考慮事項に注意する必要があります。

これらの考慮事項は、 MetroCluster の専用の直接のバックエンドリンクおよびスイッチにのみ適用され、 MetroCluster 以外のトラフィックと共有されるリンクには適用されません。

Hardware Universe ツールには、 MetroCluster IP 構成で TDM / xWDM 機器を使用する場合の要件について、いくつかの注意事項が記載されています。

https://["NetApp Hardware Universe の略"]



== WDM または外部暗号化デバイスでの暗号化の使用

MetroCluster IP 構成において WDM デバイスで暗号化を使用する場合は、次の要件を満たす必要があります。

* 該当するスイッチのベンダーの認定を受けた外部暗号化デバイスまたは DWDM 機器を使用する必要があります。
+
動作モード（トランキングや暗号化など）に対応した認定が必要です。

* 暗号化を含むエンドツーエンドの全体的なレイテンシおよびジッターが IMT または本ドキュメントに記載されている最大値以下である必要があります。




== SFP に関する考慮事項

MetroCluster ISL では、機器のベンダーがサポートしている SFP または QSFP がサポートされます。SFP と QSFP はネットアップまたは機器のベンダーから入手できます。



== ISL に関する考慮事項

ISL の速度と長さは、 1 つのファブリックのすべての ISL で同じである必要があります。

ISL のトポロジは、 1 つのファブリックのすべての ISL で同じである必要があります。たとえば、すべての ISL を直接リンクにするか、または WDM を使用する場合はすべての ISL で WDM を使用する必要があります。

ISL を MetroCluster 以外のネットワークと共有する場合は、のガイドラインに従う必要があります link:concept_considerations_layer_2.html["プライベートレイヤ 2 ネットワークの共有に関する考慮事項"]。

ファブリック 1 とファブリック 2 の距離の最大サポート距離は 20 km です
