---
permalink: install-ip/concept_considerations_isls.html 
sidebar: sidebar 
keywords: isl, isls, layer 2, layer 3, shared switch 
summary: 構成に応じた ISL の要件を確認しておく必要があります。 
---
= ISL に関する考慮事項
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


構成に応じた ISL の要件を確認しておく必要があります。



== MetroCluster ISL の基本要件

すべての MetroCluster IP 構成で ISL が次の要件を満たしている必要があります。

* ネイティブ速度の ISL スイッチポートは、ネイティブ速度の ISL スイッチポートに接続する必要があります。
+
たとえば、 40Gbps ポートは 40Gbps ポートに接続します。

* ブレークアウトケーブルを使用しないネイティブモードの 10Gbps ポートは、ネイティブモードの 10Gbps ポートに接続できます。
* MetroCluster IP スイッチとネットワークの間の ISL 、および中間スイッチ間の ISL は、速度に関して同じルールに従います。
* MetroCluster スイッチとネットワークスイッチの間と、ネットワークスイッチ間で、 ISL の数が一致している必要はありません。
+
たとえば、 MetroCluster スイッチは、 2 つの ISL を使用して中間スイッチに接続でき、 10 個の ISL を使用して中間スイッチどうしを接続できます。

* MetroCluster スイッチとネットワークスイッチの間と、ネットワークスイッチ間で、 ISL の速度が一致している必要はありません。
+
たとえば、 40Gbps の ISL を使用して MetroCluster スイッチを中間スイッチに接続し、 100Gbps の ISL を使用して中間スイッチをどうしを接続できます。

* 各 MetroCluster スイッチを中間スイッチに接続する ISL の数と速度は、両方の MetroCluster サイトで同じである必要があります。




== 共有レイヤ 2 ネットワークにおける ISL の要件

いつ link:../install-ip/concept_considerations_layer_2.html["共有ネットワークで ISL トラフィックを共有する"]をクリックし、十分な容量を確保し、 ISL のサイズを適切に設定する必要があります。MetroCluster サイト間でのデータのレプリケーションでは、レイテンシを低く抑えることが重要になります。これらの接続にレイテンシの問題があると、クライアント I/O に影響する可能性があります

以下のセクションを確認して、 ISL に必要なエンドツーエンドの容量を正しく計算してください。MetroCluster 構成では、不揮発性キャッシュとストレージのレプリケーションのレイテンシを継続的に低く抑えることが重要です。バックエンドネットワークのレイテンシは、クライアント IO のレイテンシとスループットに影響します。



=== ISL のレイテンシとパケット損失の制限

MetroCluster 構成の安定した運用状態を維持するには、 site_A と site_B の MetroCluster IP スイッチ間のラウンドトリップトラフィックについて次の要件を満たしている必要があります。

* 構成のラウンドトリップレイテンシおよび最大距離の要件の詳細については、を参照してください link:https://hwu.netapp.com/["Hardware Universe の略。"^]
+
2 つの MetroCluster サイト間の距離が長くなるとレイテンシが増加します。通常、ラウンドトリップ遅延時間は 100km （ 62 マイル）ごとに 1 ミリ秒程度です。このレイテンシは、ネットワークの ISL リンクの帯域幅、パケット破棄率、ジッターに関する Service Level Agreement （ SLA ；サービスレベル契約）にも左右されます。低帯域幅、高ジッター、ランダムなパケット破棄などが発生すると、パケットを適切に配信できるように、スイッチやコントローラモジュールの TCP エンジンによってさまざまなリカバリメカニズムが実施されます。このようなリカバリメカニズムによって、全体的なレイテンシが増加することがあり

+
レイテンシに影響するすべてのデバイスについて考慮する必要があります。

* パケット損失は 0.01% 以下である必要があります。
+
パケット損失には、物理的な損失や輻輳やオーバーサブスクリプションによる損失が含まれます。

+
パケットの破棄により、原因の再送信が発生し、輻輳ウィンドウが減少することがあります。

* サポートされるジッタ値は、往復で 3 ミリ秒（一方向で 1.5 ミリ秒）です。
* ネットワークの SLA については、トラフィックのマイクロバーストや急増も考慮して、 MetroCluster トラフィックに必要な帯域幅に対応する SLA を割り当てて維持する必要があります。
+
低帯域幅の場合、原因キューの遅延およびテールドロップがスイッチで発生する可能性があります。ONTAP 9.7 以降を使用している場合、 2 つのサイト間の中間ネットワークで、 MetroCluster 構成用に 4.5Gbps 以上の帯域幅を確保する必要があります。

* MetroCluster トラフィックは、完全な帯域幅を消費せず、 MetroCluster 以外のトラフィックにも悪影響を与えません。
* 共有ネットワークでネットワーク監視を設定し、 ISL の利用率、エラー（破棄、リンクフラップ、破損など）、障害を監視する必要があります。




=== お客様のスイッチの接続制限とトランキング

お客様側で用意する中間スイッチは、次の要件を満たしている必要があります。

* 中間スイッチの数に制限はなく、 MetroCluster IP スイッチ間で 3 つ以上のスイッチがサポートされます。
+
MetroCluster IP スイッチは、長距離リンクを提供する中間スイッチにできるだけ近い場所に配置する必要があります。ルート上のすべての ISL 接続が MetroCluster ISL のすべての要件を満たしている必要があります。

* 十分な帯域幅を確保し、配信順序が維持されるようにネットワークの ISL （お客様のスイッチ間の ISL ）を設定する必要があります。
+
そのためには、十分な数のリンクをトランキングし、ロードバランシングポリシーを適用して順序を維持します。





=== その他のネットワーク要件

お客様側で用意する中間スイッチは、次の要件を満たしている必要があります。

* RCF ファイルに設定されている MetroCluster VLAN に一致するサイト間で、お客様のネットワークが同じ VLAN を提供する必要があります。
+
MetroCluster VLAN ID と ID が一致するレイヤ 2 VLAN で共有ネットワークを構成する必要があります。

+
** ONTAP 9.7 以前では、 FAS2750 システムと AFF A220 システムで VLAN 10 および 20 が必要です。
** ONTAP 9.8 以降では、 FAS2750 、 AFF A220 、 FAS500f 、 AFF A250 、 FAS8300 、 AFF A400 、 FAS8700 の各システムは、デフォルトで VLAN 10 と 20 を使用します。インターフェイスの作成時に他の VLAN を設定できます。範囲は 101-4096 にする必要があります。前述したすべてのプラットフォームについて、 VLAN はインターフェイスの作成時にのみ指定できます。MetroCluster インターフェイスを作成したあとに VLAN ID を変更することはできません。前述していない他のすべてのプラットフォームでは、任意の VLAN を使用でき、これらのプラットフォーム用の VLAN ID はいつでも変更できますが、新しい RCF ファイルを作成して適用する必要があります。




--
[NOTE]
====
RcfFileGenerator では、プラットフォームでサポートされていない VLAN を使用して RCF ファイルを作成することはできません。

RcfFileGenerator では、特定の VLAN ID の使用が制限される場合があります（将来使用する場合など）。一般的に、予約済み VLAN は最大で 100 です。

====
--
* ネットワークのエンドツーエンドのすべてのデバイスについて、 MTU サイズを 9216 に設定する必要があります。
* 他のトラフィックに Class of Service （ COS ；サービスクラス） 5 よりも高い優先度を設定することはできません。
* エンドツーエンドのすべてのパスで Explicit Congestion Notification （ ECN ；明示的輻輳通知）を設定する必要があります。




=== 共有 ISL を使用する場合のケーブル接続要件

[role="lead"]
MetroCluster IP 構成で共有 ISL を使用する場合は、サイト A のコントローラポートからサイト B のコントローラポートまでのエンドツーエンドの MetroCluster ISL の要件を理解しておく必要があります


NOTE: 次の手順に従う必要があります  MetroCluster ISL requirements。



=== 共有ネットワーク内の ISL およびブレークアウトケーブルの数

MetroCluster IP スイッチを共有ネットワークに接続する ISL の数は、スイッチのモデルとポートタイプによって異なります。

|===


| MetroCluster IP スイッチのモデル | ポートタイプ | ISL 数 


 a| 
Broadcom 対応 BES-53248 スイッチ
 a| 
ネイティブポート
 a| 
ISL × 4 、 10Gbps または 25Gbps ポートを使用



 a| 
Cisco 3132Q-V の設定
 a| 
ネイティブポート
 a| 
ISL × 6 、 40Gbps ポートを使用



 a| 
Cisco 3132Q-V の設定
 a| 
ブレークアウトケーブル
 a| 
10 Gbps ISL × 16



 a| 
Cisco 3232C
 a| 
ネイティブポート
 a| 
ISL × 6 、 40Gbps または 100Gbps ポートを使用



 a| 
Cisco 3232C
 a| 
ブレークアウトケーブル
 a| 
10 Gbps ISL × 16



 a| 
Cisco 9336C-FX2（NS224シェルフは接続しない）
 a| 
ネイティブポート
 a| 
ISL×6、40Gbpsまたは100Gbpsを使用



 a| 
Cisco 9336C-FX2（NS224シェルフは接続しない）
 a| 
ブレークアウトケーブル
 a| 
ISL×16、10Gbpsを使用



 a| 
Cisco 9336C-FX2（NS224シェルフの接続）
 a| 
ネイティブポート（2）
 a| 
ISL×4、40Gbpsまたは100Gbpsを使用



 a| 
Cisco 9336C-FX2（NS224シェルフの接続）
 a| 
ブレークアウトケーブル（2）
 a| 
ISL×16、10Gbpsを使用

|===
* BES-53248スイッチで40個または100GbpsのISLポートを使用するには、追加のライセンスが必要です。
* Cisco 9336C-FX2（NS224シェルフを接続）用にRCFファイルを作成する場合は、ISLをネイティブ*または*ブレークアウトモードで設定するように選択する必要があります。
* Cisco スイッチでは、ブレークアウトケーブルの使用（ 1 つの物理ポートを 4 つの 10Gbps ポートとして使用）がサポートされます。
* IP スイッチの RCF ファイルでは、標準モードとブレークアウトモードのポートが設定されています。
+
標準ポート速度モードとブレークアウトモードの ISL ポートの混在はサポートされていません。同じネットワーク内で、 MetroCluster IP スイッチから中間スイッチへのすべての ISL で速度と長さが同じである必要があります。

* ラウンドトリップレイテンシが上記の要件の範囲内であれば、外部暗号化デバイス（外部リンクの暗号化や WDM デバイスによる暗号化など）の使用がサポートされます。


最適なパフォーマンスを実現するには、ネットワークごとに少なくとも 1 つの 40Gbps ISL か複数の 10Gbps ISL を使用します。AFF A800 システムでは、ネットワークごとに 1 つの 10Gbps ISL を使用することは推奨されません。

共有 ISL の理論上の最大スループット（たとえば 40Gbps ISL が 6 つであれば 240Gbps ）は、すべての条件が揃った場合の最大値です。複数の ISL を使用する場合は、統計上の負荷分散が最大スループットに影響することがあります。負荷が均一でなくなった場合、単一の ISL と同じレベルまでスループットが低下する可能性があります。

L2 VLAN を使用する構成の場合、これらの VLAN をサイトにネイティブにまたがって設定する必要があります。Virtual Extensible LAN （ VXLAN ）などの VLAN オーバーレイはサポートされていません。

MetroCluster トラフィックを伝送する ISL は、スイッチ間のネイティブリンクである必要があります。マルチプロトコルラベルスイッチング（ MPLS ）リンクなどのリンク共有サービスはサポートされません。



=== Broadcom BES-53248 スイッチでの WAN ISL のサポート

* ファブリックあたりの WAN ISL の最小数： 1 （ 10GbE 、 25GbE 、 40GbE 、または 100GbE ）
* ファブリックあたりの 10GbE WAN ISL の最大数： 4
* ファブリックあたりの最大 25GbE WAN ISL 数： 4
* ファブリックあたりの最大 40GbE WAN ISL 数： 2
* ファブリックあたりの最大 100GbE WAN ISL 数： 2


40GbE または 100GbE の WAN ISL には、 RCF ファイルのバージョンが 1.40 以降である必要があります。


NOTE: 追加のポートには追加のライセンスが必要です。
