---
permalink: install-ip/concept_mediator_requirements.html 
sidebar: sidebar 
keywords: ontap, mediator, assist, metrocluster, ip, configuration, perform, automatic, unplan, switchover, physical, repository, status, information, configuring, configure, install, configuring, configure, mtu size, packet loss, bandwidth, firewall, rhel, centos, linux, revert, kernal, upgrade, latency 
summary: ONTAP 9.7 以降、ONTAP Mediator は、ステータス情報用の物理的に別のリポジトリを提供することで、MetroCluster IP 構成による計画外の自動スイッチオーバーの実行を支援できます。 
---
= MetroCluster IP構成のONTAP Mediatorインストール要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ご使用の環境が特定の要件を満たしている必要があり

1つのディザスタリカバリグループ（DRグループ）に次の要件が適用されます。の詳細を確認してください link:concept_parts_of_an_ip_mcc_configuration_mcc_ip.html#disaster-recovery-dr-groups["DR グループ"]。

* Linux バージョンを更新する予定がある場合は、最新バージョンの ONTAP Mediator をインストールする前に更新してください。
* ONTAP Mediator と MetroCluster Tiebreaker ソフトウェアの両方を同じ MetroCluster 構成で使用しないでください。
* ONTAP Mediator は、MetroCluster サイトとは別の場所にある Linux ホストにインストールする必要があります。
+
ONTAP メディエーターと各サイトの間の接続には、2つの異なる障害ドメインが必要です。

* ONTAP 9.7 以降では、自動計画外スイッチオーバーがサポートされます。
* ONTAP 9.19.1およびONTAP Mediator 1.12以降では、iSCSIではなくHTTPSを使用して通信を行うONTAP Mediatorを設定できます。ONTAP MediatorがHTTPSで設定されている場合、ONTAP Mediatorインスタンスごとに1つのMetroCluster IP構成のみを監視できます。詳細については、<<ONTAP Mediatorの通信プロトコルを選択してください>>を参照してください。
* ONTAP 9.18.1およびONTAP Mediator 1.11以降では、iSCSIで構成された単一のONTAP Mediatorインスタンスで、最大10個のMetroCluster構成を同時に管理できます。ONTAP 9.17.1およびONTAP Mediator 1.10以前では、iSCSIで構成されたONTAP Mediatorは、最大5個のMetroCluster構成を同時にサポートできます。
* ONTAP 9.18.1 以降では、 MetroCluster IP 構成のONTAP Mediator 1.11 以降で IPv6 がサポートされます。




== MetroCluster構成でONTAP Mediatorを使用するためのネットワーク要件

MetroCluster 構成に ONTAP Mediator をインストールするには、構成がいくつかのネットワーク要件を満たしていることを確認する必要があります。

* レイテンシ
+
最大レイテンシは75ms（RTT）未満

+
ジッターは5ミリ秒以下である必要があります。

* MTU
+
MTU サイズは 1400 以上にする必要があります。

* パケット損失
+
Internet Control Message Protocol（ICMP）とTCPトラフィックの両方で、パケット損失は0.01%未満でなければなりません。

* 帯域幅
+
ONTAP Mediator と 1 つの DR グループ間のリンクには、少なくとも 20 Mbps の帯域幅が必要です。

* 独立した接続性
+
各サイトとONTAP メディエーターは個別に接続する必要があります。一方のサイトで障害が発生しても、影響を受けない他の2つのサイト間のIP接続は中断しないでください。





== MetroCluster構成におけるONTAP Mediatorのホスト要件

構成が複数のホスト要件を満たしていることを確認する必要があります。

* ONTAP メディエーターは、2つのONTAP クラスタから物理的に分離された外部サイトにインストールする必要があります。
* ONTAP メディエーターでは、ホストオペレーティングシステムの最小要件であるCPUおよびメモリ（RAM）は必要ありません。
* ホストオペレーティングシステムの最小要件に加えて、使用可能なディスクスペースが少なくとも30GB必要です。
+
** 各DRグループには、最大200MBのディスクスペースが必要です。






== ONTAP Mediatorの通信プロトコルを選択してください

デフォルトでは、MetroCluster IPノードはiSCSIセッションを使用してONTAP MediatorメールボックスLUNにアクセスします。ONTAP MediatorはSCSTパッケージを利用してiSCSIを提供します。iSCSIセッションは、難読化された機械生成の事前共有鍵を使用したチャレンジハンドシェイク認証プロトコル（CHAP）によって認証されますが、完全に暗号化されるわけではありません。

ONTAP 9.19.1およびONTAP Mediator 1.12以降では、iSCSIではなくHTTPSを使用して通信を行うONTAP Mediatorインスタンスを設定できます。HTTPSは、SSL/TLSを使用してセッション全体を暗号化する安全な通信プロトコルであり、iSCSIと比較してセキュリティが向上しています。

CLIを使用してHTTPSを使用するONTAP Mediatorのみを設定できます。System Managerはサポートされていません。

[CAUTION]
====
* HTTPS を使用して ONTAP Mediator を設定する場合、単一の ONTAP Mediator インスタンスで監視できる MetroCluster IP 設定は 1 つだけです。複数の MetroCluster IP 設定を同時に監視することはサポートされていません。
* 複数のMetroCluster IP構成を監視するためにHTTPSで構成されたONTAP Mediatorが必要な場合は、MetroCluster IP構成ごとに個別のONTAP Mediatorインスタンスを構成する必要があります。MetroCluster IPに対してHTTPSでONTAP Mediatorを構成することを選択する前に、MetroCluster IP環境の要件を慎重に評価する必要があります。
* 複数のMetroCluster IP構成を監視するために単一のONTAP Mediatorインスタンスを使用する場合は、HTTPSではなくiSCSIを使用してONTAP Mediatorを設定する必要があります。


====
詳細については、link:https://docs.netapp.com/us-en/ontap/mediator/index.html#https-iscsi-installation["ONTAP MediatorのHTTPSおよびiSCSIインストールオプション"^]を参照してください。



== MetroCluster構成でONTAP Mediatorをアップグレードするためのガイドライン

ONTAP Mediator をアップグレードする場合は、Linux バージョンの要件を満たし、アップグレードのガイドラインに従う必要があります。

* ONTAP Mediator は、直前のバージョンから現在のバージョンにアップグレードできます。
* MetroCluster 9.7 以降を実行する ONTAP IP 構成では、すべてのメディエーターのバージョンがサポートされます。


link:https://docs.netapp.com/us-en/ontap/mediator/index.html["ONTAPメディエーターをインストールまたはアップグレードする"^]



== アップグレード後

メディエーターとオペレーティングシステム問題のアップグレードが完了したら、「 storage iscsi-initiator show 」コマンドを実行して、メディエーター接続が稼働していることを確認する必要があります。
