---
permalink: install-ip/concept_considerations_unmirrored_aggrs.html 
sidebar: sidebar 
keywords: differences, eight-node, four-node, fabric-attached, stretch, metrocluster ip, storage, bridges, fc-to-sas, atto, fibrebridge, SAS, local HA, auso, automatic unplanned switchover, mediator, tiebreaker 
summary: ミラーされていないアグリゲートが構成に含まれている場合、スイッチオーバー処理後にアクセスに関する問題が発生する可能性があります。 
---
= MetroCluster IP構成におけるミラーリングされていないアグリゲートについて学習します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ミラーされていないアグリゲートが構成に含まれている場合、スイッチオーバー処理後にアクセスに関する問題が発生する可能性があります。



== ミラーリングされていない集約と階層型名前空間

階層状のネームスペースを使用している場合は、パス内のすべてのボリュームがミラーされたアグリゲートのみ、またはミラーされていないアグリゲートのみに配置されるようにジャンクションパスを設定する必要があります。ジャンクションパスにミラーされていないアグリゲートとミラーされたアグリゲートが混在していると、スイッチオーバー処理後にミラーされていないアグリゲートにアクセスできなくなる可能性があります。



== ミラーリングされていないアグリゲートと電源シャットダウンを必要とするメンテナンス

サイト全体の電源シャットダウンを必要とするメンテナンスのためにネゴシエート スイッチオーバーを実行する場合は、まず災害サイトが所有するミラーリングされていないアグリゲートを手動でオフラインにする必要があります。

ディザスタサイトが所有するミラーリングされていないアグリゲートをオフラインにしないと、マルチディスクパニックにより、サバイバルサイトのノードがダウンする可能性があります。これは、電源のシャットダウンやISLの損失により、スイッチオーバーされたミラーリングされていないアグリゲートがオフラインになったり、ディザスタサイトのストレージへの接続が失われたために欠落したりした場合に発生する可能性があります。



== ミラーリングされていないアグリゲート、CRSメタデータボリューム、およびデータSVMルートボリューム

構成レプリケーションサービス（CRS）メタデータボリュームとデータSVMルートボリュームは、ミラーリングされたアグリゲート上に配置する必要があります。ミラーリングこれらのボリュームをミラーされていないアグリゲートに移動することはできません。されていないアグリゲート上に配置されている場合、ネゴシエートされたスイッチオーバーおよびスイッチバック操作は拒否され、  `metrocluster check`コマンドは警告を返します。



== ミラーリングされていないアグリゲートとSVM

SVMは、ミラーリングされたアグリゲートのみ、またはミラーリングされていないアグリゲートのみに設定する必要があります。ミラーリングされていないアグリゲートとミラーリングされたアグリゲートの両方にSVMを設定すると、スイッチオーバー処理に120秒を超える時間がかかる場合があります。ミラーリングされていないアグリゲートがオンラインにならない場合、データ障害が発生する可能性があります。



== ミラーリングされていないアグリゲートとSAN

ONTAP 9.9.1より前のバージョンでは、LUNをミラーリングされていないアグリゲート上に配置しないでください。ミラーリングされていないアグリゲート上にLUNを設定すると、スイッチオーバー処理に120秒以上かかり、データが停止する可能性があります。



== ミラーリングされていないアグリゲート用のストレージシェルフを追加する

シェルフを追加し、 MetroCluster IP 構成内のミラーリングされていないアグリゲートに使用する場合は、次の手順を実行する必要があります。

. 手順を開始してシェルフを追加する前に、次のコマンドを問題に設定します。
+
MetroCluster modify -enable -ミラー されていない -aggr-deployment true

. ディスクの自動割り当てが無効になっていることを確認します。
+
「ディスクオプション表示」

. 手順の手順に従ってシェルフを追加します。
. 新しいシェルフのすべてのディスクを、ミラーされていないアグリゲートまたはアグリゲートを所有するノードに手動で割り当てます。
. アグリゲートを作成します。
+
「 storage aggregate create 」

. 手順が完了したら、次のコマンドを問題に設定します。
+
MetroCluster modify -enable -ミラー されていない -aggr-deployment false

. ディスクの自動割り当てが有効になっていることを確認します。
+
「ディスクオプション表示」


