---
permalink: install-ip/concept_configure_the_mcc_software_in_ontap.html 
sidebar: sidebar 
keywords: metrocluster, configuration, ontap, node-level, configuration, node, site, relationship, configuring, configure, 
summary: MetroCluster 構成の各ノードは、ノードレベルの設定や 2 つのサイトへのノードの設定を含めて、 ONTAP で設定する必要があります。また、 2 つのサイト間に MetroCluster 関係を実装する必要があります。 
---
= ONTAP で MetroCluster ソフトウェアを設定します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
MetroCluster 構成の各ノードは、ノードレベルの設定や 2 つのサイトへのノードの設定を含めて、 ONTAP で設定する必要があります。また、 2 つのサイト間に MetroCluster 関係を実装する必要があります。

設定中にコントローラモジュールに障害が発生した場合は、を参照してください link:../disaster-recovery/concept_choosing_the_correct_recovery_procedure_parent_concept.html#controller-module-failure-scenarios-during-metrocluster-installation["MetroCluster のインストール中のコントローラモジュールの障害のシナリオ"]。

image::../media/workflow_mcc_ip_high_level_node_and_cluster_configuration_software.svg[ワークフロー MCC IP ：ノードおよびクラスタ構成ソフトウェアの概要]



== 8ノードのMetroCluster IP構成を構成する

8ノードのMetroCluster構成は2つのDRグループで構成されます。最初のDRグループを設定するには、このセクションのタスクを完了してください。最初のDRグループを設定したら、以下の手順に従ってください。 link:../upgrade/task_expand_a_four_node_mcc_ip_configuration.html["4ノードのMetroCluster IP構成を8ノード構成に拡張する"] 。
