---
permalink: install-ip/concept_considerations_mediator.html 
sidebar: sidebar 
keywords: differences, eight-node, four-node, fabric-attached, stretch, metrocluster ip, storage, bridges, fc-to-sas, atto, fibrebridge, SAS, local HA, auso, automatic unplanned switchover, mediator, tiebreaker 
summary: MetroCluster 構成のタイプごとに、必要なコンポーネントが異なります。 
---
= ONTAP メディエーターと MetroCluster Tiebreaker の違い
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.7 以降では、 MetroCluster IP 構成で ONTAP Mediator-Assisted Automatic Unplanned Switchover （ MAUSO ；メディエーターアシスト自動計画外スイッチオーバー）を使用するか、 MetroCluster Tiebreaker ソフトウェアを使用できます。MAUSOまたはTiebreakerソフトウェアを使用する必要はありませんが、これらのサービスのどちらも使用しない場合は、 link:../disaster-recovery/concept_dr_workflow.html["手動リカバリの実行"] 災害が発生した場合。

MetroCluster 構成に応じて、異なる状況で自動スイッチオーバーが実行されます。

* * AUSO 機能を使用した MetroCluster FC 構成（ MetroCluster IP 構成には含まれません） *
+
これらの構成では、コントローラの障害が発生した場合にストレージ（および存在する場合はブリッジ）が動作していれば AUSO が開始されます。

* *ONTAP Mediator を使用した MetroCluster IP 構成 (ONTAP 9.7 以降)*
+
これらの構成では、前述の AUSO と同じ状況に加え、サイト全体（コントローラ、ストレージ、スイッチ）の障害が発生した場合に MAUSO が開始されます。

+
link:concept-ontap-mediator-supports-automatic-unplanned-switchover.html["ONTAPメディエーターでの自動計画外スイッチオーバーのサポート"]。

* * アクティブモードで Tiebreaker ソフトウェアを使用した MetroCluster IP または FC 構成 *
+
これらの構成では、サイト全体の障害が発生した場合に Tiebreaker で計画外スイッチオーバーが開始されます。

+
Tiebreaker ソフトウェアを使用する前に、を参照してください link:../tiebreaker/concept_overview_of_the_tiebreaker_software.html["MetroCluster Tiebreaker ソフトウェアのインストールおよび設定"]





== ONTAP メディエーターと他のアプリケーションおよびアプライアンスとの相互運用性

スイッチオーバーをトリガーできるサードパーティのアプリケーションやアプライアンスを ONTAP メディエーターと組み合わせて使用することはできません。また、 ONTAP メディエーターを使用した場合、 MetroCluster Tiebreaker ソフトウェアでの MetroCluster 構成の監視はサポートされません。
