---
permalink: install-ip/concept_mediator_requirements.html 
sidebar: sidebar 
keywords: ontap, mediator, service, assist, metrocluster, ip, configuration, perform, automatic, unplan, switchover, physical, repository, status, information, configuring, configure, install, configuring, configure, mtu size, packet loss, bandwidth, firewall, rhel, centos, linux, revert, kernal, upgrade, latency 
summary: ONTAP 9.7 以降では、 ONTAP メディエーターサービスを使用してステータス情報用のリポジトリを物理的に切り離すことで、 MetroCluster IP 構成で自動計画外スイッチオーバーを実行できます。 
---
= ONTAP メディエーターサービスをインストールする準備をします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
環境が次の要件を満たしている必要があります。

[NOTE]
====
* Linux のバージョンを更新する場合は、最新の ONTAP メディエーターサービスをインストールする前にアップグレードしてください。
* ONTAP メディエーターサービスと MetroCluster Tiebreaker ソフトウェアの両方を同じ MetroCluster 構成で使用することはできません。
* ONTAP メディエーターは、 MetroCluster サイトとは別の場所にある Linux ホストにインストールする必要があります。
* ONTAP メディエーターサービスでは、最大 5 つの MetroCluster 構成を同時にサポートできます。
* ONTAP 9.7 以降では、自動計画外スイッチオーバーがサポートされます。


====


== MetroCluster 構成でメディエーターを使用するためのネットワーク要件

ONTAP 構成で MetroCluster メディエーターサービスをインストールするには、いくつかのネットワーク要件を満たす必要があります。

* レイテンシ
+
ラウンドトリップレイテンシは75ミリ秒以下である必要があります。

+
ジッターは25ミリ秒以下である必要があります。

* MTU
+
MTU サイズは 1400 以上にする必要があります。

* パケット損失
+
パケット損失は 0.01% 以下である必要があります。

* 帯域幅
+
メディエーターサービスとMetroCluster 構成の間のリンクには、20MBps以上の帯域幅が必要です。





== ONTAP メディエーターのファイアウォール要件

ONTAP メディエーターは、複数のポートを使用して特定のサービスと通信します。

サードパーティのファイアウォールを使用している場合は、次の手順を実行します。

* HTTPS アクセスが有効になっている必要があります。
* ポート 31784 および 3260 でアクセスを許可するように設定されている必要があります。
+
Red Hat または CentOS のデフォルトのファイアウォールを使用している場合は、メディエーターのインストール時に自動的に設定されます。



次の表に、ファイアウォールで許可する必要があるポートを示します。

|===


| ポート / サービス | ソース | 宛先 | 目的 


 a| 
31784/TCP
 a| 
ONTAP クラスタ管理インターフェイス
 a| 
ONTAP メディエーター Web サーバ
 a| 
REST API （ HTTPS ）



 a| 
3260 TCP
 a| 
ONTAP クラスタ
 a| 
ONTAP メディエーターの iSCSI ターゲット
 a| 
メールボックス用の iSCSI データ接続

|===


== MetroCluster 構成での ONTAP メディエーターのアップグレードに関するガイドライン

ONTAP メディエーターをアップグレードする場合は、 Linux のバージョン要件を満たし、アップグレードのガイドラインに従う必要があります。

* メディエーターサービスは、以前のバージョンから現在のバージョンにアップグレードすることができます。
* MetroCluster 9.7 以降を実行する ONTAP IP 構成では、すべてのメディエーターのバージョンがサポートされます。


link:https://docs.netapp.com/us-en/ontap/mediator/index.html["ONTAP メディエーターサービスをインストールまたはアップグレードします"^]



== アップグレード後

メディエーターとオペレーティングシステム問題のアップグレードが完了したら、「 storage iscsi-initiator show 」コマンドを実行して、メディエーター接続が稼働していることを確認する必要があります。
