---
permalink: install-ip/concept_considerations_unmirrored_aggrs.html 
sidebar: sidebar 
keywords: differences, eight-node, four-node, fabric-attached, stretch, metrocluster ip, storage, bridges, fc-to-sas, atto, fibrebridge, SAS, local HA, auso, automatic unplanned switchover, array luns, mediator, tiebreaker 
summary: ミラーされていないアグリゲートが構成に含まれている場合、スイッチオーバー処理後にアクセスに関する問題が発生する可能性があります。 
---
= ミラーされていないアグリゲートを
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ミラーされていないアグリゲートが構成に含まれている場合、スイッチオーバー処理後にアクセスに関する問題が発生する可能性があります。



== ミラーされていないアグリゲートと階層状のネームスペースに関する考慮事項

階層状のネームスペースを使用している場合は、パス内のすべてのボリュームがミラーされたアグリゲートのみ、またはミラーされていないアグリゲートのみに配置されるようにジャンクションパスを設定する必要があります。ジャンクションパスにミラーされていないアグリゲートとミラーされたアグリゲートが混在していると、スイッチオーバー処理後にミラーされていないアグリゲートにアクセスできなくなる可能性があります。



== ミラーされていないアグリゲート、 CRS メタデータボリューム、およびデータ SVM ルートボリュームに関する考慮事項

設定レプリケーションサービス（ CRS ）メタデータボリュームとデータ SVM ルートボリュームは、ミラーされたアグリゲートに配置する必要があります。これらのボリュームをミラーされていないアグリゲートに移動することはできませミラーされていないアグリゲートにある場合、ネゴシエートスイッチオーバー処理とスイッチバック処理が拒否されます。MetroCluster チェックコマンドを使用すると、この場合に警告が表示されます。



== ミラーされていないアグリゲートと SVM に関する考慮事項

SVM は、ミラーされたアグリゲートでのみ、またはミラーされていないアグリゲートでのみ設定してください。ミラーされていないアグリゲートとミラーされたアグリゲートが混在しているとスイッチオーバー処理に 2 分以上かかり、ミラーされていないアグリゲートがオンラインにならない場合にデータを利用できなくなることがあります。



== ミラーされていないアグリゲートと SAN に関する考慮事項

ONTAP 9.4.1 より前のバージョンでは、 LUN をミラーされていないアグリゲートに配置しないでください。ミラーされていないアグリゲートに LUN を設定すると、スイッチオーバー処理が 120 秒を超え、データを利用できなくなる可能性があります。



== ミラーされていないアグリゲート用にストレージシェルフを追加する場合の考慮事項


NOTE: MetroCluster IP 構成でミラーされていないアグリゲートに使用するシェルフを追加する場合は、次の手順を実行する必要があります。

. 手順を開始してシェルフを追加する前に、次のコマンドを問題に設定します。
+
MetroCluster modify -enable -ミラー されていない -aggr-deployment true

. ディスクの自動割り当てが無効になっていることを確認します。
+
「ディスクオプション表示」

. 手順の手順に従ってシェルフを追加します。
. 新しいシェルフのすべてのディスクを、ミラーされていないアグリゲートまたはアグリゲートを所有するノードに手動で割り当てます。
. アグリゲートを作成します。
+
「 storage aggregate create 」

. 手順が完了したら、次のコマンドを問題に設定します。
+
MetroCluster modify -enable -ミラー されていない -aggr-deployment false

. ディスクの自動割り当てが有効になっていることを確認します。
+
「ディスクオプション表示」


