---
permalink: install-ip/concept_considerations_drive_assignment.html 
sidebar: sidebar 
keywords: drive auto-assignment, drive, adp, advanced disk partitioning, root disk, unmirrored root, data partition, root partition, shelf-by-shelf, AFF A320, AFF A220, AFF A250, C250, AFF A300, AFF A400, C400, AFF A700, AFF A800, FAS2750, FAS8200, FAS500f, FAS9000 
summary: ONTAP 9.4 以降の MetroCluster IP 構成では、 ADP （アドバンストドライブパーティショニング）を使用した AFF システムの新規設置がサポートされます。 
---
= ONTAP 9.4 以降での自動ドライブ割り当てと ADP システムに関する考慮事項
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.4以降では、MetroCluster IP構成でアドバンストドライブパーティショニング（ADP）を使用した新規インストールがサポートされます。ほとんどの構成では、パーティショニングとディスク割り当ては MetroCluster サイトの初期設定時に自動的に実行されます。

ONTAP 9.4以降では、ADPのサポートに次の変更が加えられています。

* プール 0 のディスクは出荷時点で割り当て済みです。
* ミラーされていないルートが工場出荷時に作成されています。
* データパーティションは、手順のセットアップ時にお客様のサイトで割り当てます。
* ほとんどの場合、ドライブの割り当てとパーティショニングはセットアップ時に自動的に実行されます。
* ディスクとそのすべてのパーティションは、同じハイアベイラビリティ（HA）ペアのノードが所有している必要があります。ローカルHAペアとディザスタリカバリ（DR）パートナーまたはDR補助パートナーと、1つのドライブ内でパーティションまたはドライブの所有権を混在させることはできません。
+
サポートされる構成の例：

+
|===


| ドライブ/パーティション | オーナー 


| ドライブ： | `ClusterA-Node01` 


| パーティション1： | `ClusterA-Node01` 


| パーティション2： | `ClusterA-Node02` 


| パーティション3： | `ClusterA-Node01` 
|===



NOTE: ONTAP 9.4 から 9.5 へのアップグレードでは、既存のディスク割り当てが認識されます。



== 自動パーティショニング

ADP は、プラットフォームの初期設定時に自動的に実行されます。


NOTE: ONTAP 9.5以降では、でディスクの自動割り当てを有効にする必要があります `storage disk option modify -autoassign on` コマンドを実行します

ha-config状態をに設定する必要があります `mccip` 自動プロビジョニングの前に、ルートボリュームのサイズが適切になるように正しいパーティションサイズが選択されていることを確認します。詳細については、を参照してください link:https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_sw_config_verify_haconfig.html["コンポーネントの ha-config 状態の確認"]。

インストール中に最大 96 本のドライブを自動的にパーティショニングできます。初期インストール後にドライブを追加することができます。



== シェルフ単位の自動割り当ての仕組み

各サイトに 4 台の外付けシェルフがある場合、次の例に示すように、各シェルフが異なるノードの異なるプールに割り当てられます。

* site_A-shelf_1 のすべてのディスクが node_A_1 のプール 0 に自動的に割り当てられます
* site_A-shelf_3 のすべてのディスクが node_A_1 のプール 0 に自動的に割り当てられます
* site_B-shelf_1 のすべてのディスクが node_B_1 のプール 0 に自動的に割り当てられます
* site_B-shelf_3 のすべてのディスクが node_B_2 のプール 0 に自動的に割り当てられます
* site_B-shelf_2 のすべてのディスクが node_A_1 のプール 1 に自動的に割り当てられます
* site_B-shelf_2 のすべてのディスクが node_B_2 のプール 1 に自動的に割り当てられます
* site_A-shelf_2 のすべてのディスクが node_B_1 のプール 1 に自動的に割り当てられます
* site_A-shelf_2 のすべてのディスクが node_B_2 のプール 1 に自動的に割り当てられます




== 部分的にフルになったシェルフの設置方法

シェルフに十分な空きドライブベイがない場合は、ディスク割り当てポリシーに応じて、シェルフ全体にドライブを均等に分散する必要があります。ディスク割り当てポリシーは、各 MetroCluster サイトにシェルフがいくつあるかによって異なります。

各サイトでシェルフが 1 台（または AFF A800 システムの内蔵シェルフのみ）を使用している場合は、クォータシェルフポリシーを使用してディスクが割り当てられます。シェルフに空きがない場合は、すべてのクォータにドライブを均等に取り付けます。

次の表は、 24 本のディスクを 48 本のドライブ内蔵シェルフに配置する方法の例を示しています。ドライブの所有権も表示されます。

|===


| 48 個のドライブベイが 4 つのクォータに分割されています。 | 各クォータの最初の 6 つのベイに 6 本のドライブを取り付け ... 


 a| 
第 1 クォータ：ベイ 0~11
 a| 
ベイ 0~5



 a| 
第 2 クォータ：ベイ 12~23
 a| 
ベイ 12~17



 a| 
第 3 四半期 : ベイ 24-35
 a| 
ベイ 24-29



 a| 
第 4 四半期：ベイ 36 ～ 48
 a| 
ベイ 36-41

|===
各サイトでシェルフを 2 台使用している場合は、ハーフシェルフポリシーを使用してディスクが割り当てられます。シェルフにフル装備されていない場合は、シェルフの両端からドライブを均等に取り付けます。

たとえば、 24 ドライブシェルフに 12 本のドライブを取り付ける場合は、ベイ 0~5 および 18~23 にドライブを取り付けます。



== ドライブの手動割り当て（ ONTAP 9.5 ）

ONTAP 9.5 では、次のシェルフ構成のシステムについては手動でドライブを割り当てる必要があります。

* 各サイトに外付けシェルフが 3 台ある構成。
+
2 台のシェルフはハーフシェルフの割り当てポリシーに従って自動的に割り当てられますが、 3 台目のシェルフは手動で割り当てる必要があります。

* 各サイトにシェルフが 5 台以上あり、外付けシェルフの総数が 4 の倍数でない構成。
+
4 の倍数を超えた分のシェルフは未割り当てとなり、ドライブを手動で割り当てる必要があります。たとえば、サイトに 5 台の外付けシェルフがある場合は、シェルフ 5 を手動で割り当てる必要があります。



未割り当てのシェルフのドライブは 1 本だけ手動で割り当てます。シェルフの残りのドライブは自動的に割り当てられます。



== ドライブの手動割り当て（ ONTAP 9.4 ）

ONTAP 9.4 では、次のシェルフ構成のシステムに対して手動でドライブを割り当てる必要があります。

* 各サイトに外付けシェルフが 3 台以下の構成。
+
ドライブを手動で割り当てる必要があります。各プールのドライブ数が同じになるようにドライブを対称的に割り当てます。

* 各サイトに外付けシェルフが 5 台以上あり、外付けシェルフの総数が 4 の倍数でない構成。
+
4 の倍数を超えた分のシェルフは未割り当てとなり、ドライブを手動で割り当てる必要があります。



ドライブを手動で割り当てるときは、各プールのドライブ数が同じになるようにディスクを対称的に割り当てる必要があります。たとえば、各サイトにストレージシェルフが 2 台ある構成では、 1 台のシェルフをローカル HA ペアに使用し、もう 1 台のシェルフをリモート HA ペアに使用します。

* site_A-shelf_1 の半分のディスクを node_A_1 のプール 0 に割り当てます。
* site_A-shelf_1 の半分のディスクを node_A_1 のプール 0 に割り当てます。
* site_A-shelf_2 の半分のディスクを node_B_1 のプール 1 に割り当てます。
* site_A-shelf_2 の半分のディスクを node_B_2 のプール 1 に割り当てます。
* site_B-shelf_1 の半分のディスクを node_B_1 のプール 0 に割り当てます。
* site_B-shelf_1 の半分のディスクを node_B_2 のプール 0 に割り当てます。
* site_B-shelf_2 の半分のディスクを node_A_1 のプール 1 に割り当てます。
* site_B-shelf_2 の半分のディスクを node_B_2 のプール 1 に割り当てます。




== 既存構成へのシェルフの追加

自動ドライブ割り当てでは、既存の構成にシェルフを対称的に追加できます。

新しいシェルフが追加されると、追加されたシェルフに同じ割り当てポリシーが適用されます。たとえば、各サイトにシェルフが 1 台ある構成でシェルフを追加した場合、新しいシェルフにはクォータシェルフの割り当てルールが適用されます。

.関連情報
link:concept_required_mcc_ip_components_and_naming_guidelines_mcc_ip.html["必要な MetroCluster IP コンポーネントと命名規則"]

https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-psmg/home.html["ディスクおよびアグリゲートの管理"^]



== MetroCluster IP 構成での ADP とディスク割り当てのシステム別の違い

MetroCluster IP 構成でのアドバンストドライブパーティショニング（ ADP ）と自動ディスク割り当ての動作は、システムモデルによって異なります。


NOTE: ADP を使用するシステムではパーティションを使用してアグリゲートが作成され、各ドライブがパーティション P1 、 P2 、 P3 に分割されます。ルートアグリゲートは P3 パーティションを使用して作成されます。

サポートされる最大ドライブ数やその他のガイドラインについては、 MetroCluster の制限を満たす必要があります。

https://hwu.netapp.com["NetApp Hardware Universe の略"]



=== AFF A320 システムでの ADP とディスクの割り当て

|===


| ガイドライン | サイトあたりのドライブ数 | ドライブ割り当てルール | ルートパーティションの ADP レイアウト 


 a| 
推奨される最小ドライブ数（サイトあたり）
 a| 
48 ドライブ
 a| 
各外付けシェルフのドライブが 2 つのグループに均等に分割されます（ハーフ）。シェルフの各ハーフが自動的に別々のプールに割り当てられます。
 a| 
1 台のシェルフはローカル HA ペアによって使用されます。2 番目のシェルフはリモート HA ペアによって使用されます。

各シェルフのパーティションは、ルートアグリゲートの作成に使用されます。ルートアグリゲートの 2 つのプレックスのそれぞれに、次のパーティションが含まれています::
+
--
* データ用パーティション × 8
* パリティパーティション × 2
* スペアパーティションが 2 つ必要です


--




 a| 
サポートされる最小ドライブ数（サイトあたり）
 a| 
24 本のドライブ
 a| 
ドライブは 4 つのグループに均等に分割されます各クォータシェルフは、自動的に別々のプールに割り当てられます。
 a| 
ルートアグリゲートの 2 つのプレックスのそれぞれに、次のパーティションが含まれます。

* データ用パーティション × 3
* パリティパーティション × 2
* スペアパーティション × 1


|===


=== AFF A150およびAFF A220システムでのADPとディスク割り当て

|===


| ガイドライン | サイトあたりのドライブ数 | ドライブ割り当てルール | ルートパーティションの ADP レイアウト 


 a| 
推奨される最小ドライブ数（サイトあたり）
 a| 
内蔵ドライブのみ
 a| 
内蔵ドライブは 4 つのグループに均等に分割されます各グループは自動的に別々のプールに割り当てられ、各プールは構成内の別々のコントローラに割り当てられます。


NOTE: 内蔵ドライブの半分は、 MetroCluster が設定される前に未割り当てのままです。
 a| 
2 つのクォータはローカル HA ペアに使用されます。残り 2 つのクォータはリモート HA ペアに使用されます。

ルートアグリゲートの各プレックスには、次のパーティションが含まれます。

* データ用パーティション × 3
* パリティパーティション × 2
* スペアパーティション × 1




 a| 
サポートされる最小ドライブ数（サイトあたり）
 a| 
16 本の内蔵ドライブ
 a| 
ドライブは 4 つのグループに均等に分割されます各クォータシェルフは、自動的に別々のプールに割り当てられます。

シェルフ上の 2 つのクォータに同じプールを割り当てることができます。プールは、そのクォータを所有するノードに基づいて選択されます。

* ローカルノードが所有している場合は、プール 0 が使用されます。
* リモートノードが所有している場合は、プール 1 が使用されます。


たとえば、 Q1~Q4 に 4 分割されたシェルフでは次のような割り当てが可能です。

* Q1 ： node_A_1 のプール 0
* Q2 ： node_A_1 のプール 0
* Q3 ： node_B_1 のプール 1
* Q4 ： node_B_2 のプール 1



NOTE: 内蔵ドライブの半分は、 MetroCluster が設定される前に未割り当てのままです。
 a| 
ルートアグリゲートの 2 つのプレックスのそれぞれに、次のパーティションが含まれます。

* データ用パーティション×2
* パリティパーティション × 2
* スペアなし


|===


=== AFF C250、AFF A250、およびFAS500fシステムでのADPとディスク割り当て

|===


| ガイドライン | サイトあたりのドライブ数 | ドライブ割り当てルール | ルートパーティションの ADP レイアウト 


 a| 
推奨される最小ドライブ数（サイトあたり）
 a| 
48 ドライブ
 a| 
各外付けシェルフのドライブが 2 つのグループに均等に分割されます（ハーフ）。シェルフの各ハーフが自動的に別々のプールに割り当てられます。
 a| 
1 台のシェルフはローカル HA ペアによって使用されます。2 番目のシェルフはリモート HA ペアによって使用されます。

各シェルフのパーティションは、ルートアグリゲートの作成に使用されます。ルートアグリゲートの各プレックスには、次のパーティションが含まれます。

* データ用パーティション × 8
* パリティパーティション × 2
* スペアパーティションが 2 つ必要です




 a| 
サポートされる最小ドライブ数（サイトあたり）
 a| 
16 本の内蔵ドライブ
 a| 
ドライブは 4 つのグループに均等に分割されます各クォータシェルフは、自動的に別々のプールに割り当てられます。
 a| 
ルートアグリゲートの 2 つのプレックスのそれぞれに、次のパーティションが含まれます。

* データ用パーティション×2
* パリティパーティション × 2
* スペアパーティションがありません


|===


=== AFF A300 システムでの ADP とディスク割り当て

|===


| ガイドライン | サイトあたりのドライブ数 | ドライブ割り当てルール | ルートパーティションの ADP レイアウト 


 a| 
推奨される最小ドライブ数（サイトあたり）
 a| 
48 ドライブ
 a| 
各外付けシェルフのドライブが 2 つのグループに均等に分割されます（ハーフ）。シェルフの各ハーフが自動的に別々のプールに割り当てられます。
 a| 
1 台のシェルフはローカル HA ペアによって使用されます。2 番目のシェルフはリモート HA ペアによって使用されます。

各シェルフのパーティションは、ルートアグリゲートの作成に使用されます。ルートアグリゲートの各プレックスには、次のパーティションが含まれます。

* データ用パーティション × 8
* パリティパーティション × 2
* スペアパーティションが 2 つ必要です




 a| 
サポートされる最小ドライブ数（サイトあたり）
 a| 
24 本のドライブ
 a| 
ドライブは 4 つのグループに均等に分割されます各クォータシェルフは、自動的に別々のプールに割り当てられます。
 a| 
ルートアグリゲートの 2 つのプレックスのそれぞれに、次のパーティションが含まれます。

* データ用パーティション × 3
* パリティパーティション × 2
* スペアパーティション × 1


|===


=== AFF C400およびAFF A400システムでのADPとディスク割り当て

|===


| ガイドライン | サイトあたりのドライブ数 | ドライブ割り当てルール | ルートパーティションの ADP レイアウト 


 a| 
推奨される最小ドライブ数（サイトあたり）
 a| 
96 本のドライブ
 a| 
ドライブはシェルフ単位で自動的に割り当てられます。
 a| 
ルートアグリゲートの 2 つのプレックスのそれぞれに、次のものが含まれます。

* データ用のパーティション × 20
* パリティパーティション × 2
* スペアパーティションが 2 つ必要です




 a| 
サポートされる最小ドライブ数（サイトあたり）
 a| 
24 本のドライブ
 a| 
ドライブが 4 つのグループ（クォータ）に均等に分割されます。各クォータシェルフは、自動的に別々のプールに割り当てられます。
 a| 
ルートアグリゲートの 2 つのプレックスのそれぞれに、次のものが含まれます。

* データ用パーティション × 3
* パリティパーティション × 2
* スペアパーティション × 1


|===


=== ADP とディスク割り当ては AFF A700 システムでサポートされます

|===


| ガイドライン | サイトあたりのドライブ数 | ドライブ割り当てルール | ルートパーティションの ADP レイアウト 


 a| 
推奨される最小ドライブ数（サイトあたり）
 a| 
96 本のドライブ
 a| 
ドライブはシェルフ単位で自動的に割り当てられます。
 a| 
ルートアグリゲートの 2 つのプレックスのそれぞれに、次のものが含まれます。

* データ用のパーティション × 20
* パリティパーティション × 2
* スペアパーティションが 2 つ必要です




 a| 
サポートされる最小ドライブ数（サイトあたり）
 a| 
24 本のドライブ
 a| 
ドライブが 4 つのグループ（クォータ）に均等に分割されます。各クォータシェルフは、自動的に別々のプールに割り当てられます。
 a| 
ルートアグリゲートの 2 つのプレックスのそれぞれに、次のものが含まれます。

* データ用パーティション × 3
* パリティパーティション × 2
* スペアパーティション × 1


|===


=== AFF C800およびAFF A800システムでのADPとディスク割り当て

|===


| ガイドライン | サイトあたりのドライブ数 | ドライブ割り当てルール | ルートアグリゲートの ADP レイアウト 


 a| 
推奨される最小ドライブ数（サイトあたり）
 a| 
内蔵ドライブと外付けドライブ 96 本
 a| 
内部パーティションは 4 つのグループ（クォータ）に均等に分割されます。各クォータが自動的に別々のプールに割り当てられます。外付けシェルフのドライブはシェルフ単位で自動的に割り当てられ、各シェルフのすべてのドライブが MetroCluster 構成の 4 つのノードのいずれかに割り当てられます。
 a| 
内蔵シェルフの 12 個のルートパーティションを使用してルートアグリゲートが作成されます。

ルートアグリゲートの 2 つのプレックスのそれぞれに、次のものが含まれます。

* データ用パーティション × 8
* パリティパーティション × 2
* スペアパーティションが 2 つ必要です




 a| 
サポートされる最小ドライブ数（サイトあたり）
 a| 
内蔵ドライブ24本
 a| 
内部パーティションは 4 つのグループ（クォータ）に均等に分割されます。各クォータが自動的に別々のプールに割り当てられます。
 a| 
内蔵シェルフの 12 個のルートパーティションを使用してルートアグリゲートが作成されます。

ルートアグリゲートの 2 つのプレックスのそれぞれに、次のものが含まれます。

* データ用パーティション × 3
* パリティパーティション × 2
* スペアパーティション × 1


|===


=== ADP とディスク割り当ては AFF A900 システムでサポートされます

|===


| ガイドライン | サイトあたりのシェルフ数 | ドライブ割り当てルール | ルートパーティションの ADP レイアウト 


 a| 
推奨される最小ドライブ数（サイトあたり）
 a| 
96 本のドライブ
 a| 
ドライブはシェルフ単位で自動的に割り当てられます。
 a| 
ルートアグリゲートの 2 つのプレックスのそれぞれに、次のものが含まれます。

* データ用のパーティション × 20
* パリティパーティション × 2
* スペアパーティションが 2 つ必要です




 a| 
サポートされる最小ドライブ数（サイトあたり）
 a| 
24 本のドライブ
 a| 
ドライブが 4 つのグループ（クォータ）に均等に分割されます。各クォータシェルフは、自動的に別々のプールに割り当てられます。
 a| 
ルートアグリゲートの 2 つのプレックスのそれぞれに、次のものが含まれます。

* データ用パーティション × 3
* パリティパーティション × 2
* スペアパーティション × 1


|===


=== FAS2750 システムでのディスク割り当て

|===


| ガイドライン | サイトあたりのドライブ数 | ドライブ割り当てルール | ルートパーティションの ADP レイアウト 


 a| 
推奨される最小ドライブ数（サイトあたり）
 a| 
内蔵ドライブ 24 本、外付けドライブ 24 本
 a| 
内蔵シェルフと外付けシェルフは、 2 つに均等に分割されます。各ハーフが自動的に別々のプールに割り当てられます
 a| 
該当なし



 a| 
サポートされる最小ドライブ数（サイトあたり）（アクティブ / パッシブ HA 構成）
 a| 
内蔵ドライブのみ
 a| 
手動で割り当てる必要があります
 a| 
該当なし

|===


=== FAS8200 システムでのディスク割り当て

|===


| ガイドライン | サイトあたりのドライブ数 | ドライブ割り当てルール | ルートパーティションの ADP レイアウト 


 a| 
推奨される最小ドライブ数（サイトあたり）
 a| 
48 ドライブ
 a| 
外付けシェルフのドライブが 2 つのグループ（ハーフ）に均等に分割されます。シェルフの各ハーフが自動的に別々のプールに割り当てられます。
 a| 
該当なし



 a| 
サポートされる最小ドライブ数（サイトあたり）（アクティブ / パッシブ HA 構成）
 a| 
24 本のドライブ
 a| 
手動で割り当てる必要があります。
 a| 
該当なし

|===


=== FAS500f システムでのディスク割り当て

AFF C250システムとAFF A250システムで同じディスク割り当てガイドラインとルールがFAS500fシステムにも適用されます。FAS500fシステムでのディスク割り当てについては、を参照してください。 <<ADP_FAS500f>> 表。



=== FAS9000 システムでのディスク割り当て

|===


| ガイドライン | サイトあたりのドライブ数 | ドライブ割り当てルール | ルートパーティションの ADP レイアウト 


 a| 
推奨される最小ドライブ数（サイトあたり）
 a| 
96 本のドライブ
 a| 
ドライブはシェルフ単位で自動的に割り当てられます。
 a| 
該当なし



 a| 
サポートされる最小ドライブ数（サイトあたり）
 a| 
48 ドライブ
 a| 
シェルフのドライブが 2 つのグループ（ハーフ）に均等に分割されます。シェルフの各ハーフが自動的に別々のプールに割り当てられます。
 a| 
サポートされる最小ドライブ数（サイトあたり）（アクティブ / パッシブ HA 構成）

|===


=== FAS9500システムでのディスク割り当て

|===


| ガイドライン | サイトあたりのシェルフ数 | ドライブ割り当てルール | ルートパーティションの ADP レイアウト 


 a| 
推奨される最小ドライブ数（サイトあたり）
 a| 
96 本のドライブ
 a| 
ドライブはシェルフ単位で自動的に割り当てられます。
 a| 
該当なし



 a| 
サポートされる最小ドライブ数（サイトあたり）
 a| 
24 本のドライブ
 a| 
ドライブが 4 つのグループ（クォータ）に均等に分割されます。各クォータシェルフは、自動的に別々のプールに割り当てられます。
 a| 
サポートされる最小ドライブ数（サイトあたり）（アクティブ / パッシブ HA 構成）

|===