---
permalink: install-ip/overview-isl-requirements.html 
sidebar: sidebar 
keywords: isls, ip, layer 2, layer 3, shared switch 
summary: MetroCluster構成とネットワークがISLのすべての要件を満たしていることを確認するために必要な情報について説明します。 
---
= ISLの要件の概要
:allow-uri-read: 


MetroCluster IP構成とネットワークがスイッチ間リンク（ISL）の要件をすべて満たしていることを確認する必要があります。一部の要件が該当しない構成もありますが、構成全体の理解を深めるためには、ISLのすべての要件を把握しておく必要があります。

次の表に、このセクションで説明するトピックの概要を示します。

[cols="25,75"]
|===
| タイトル | 説明 


| link:mcc-compliant-netapp-validated-switches.html["ネットアップが検証したMetroCluster準拠スイッチ"] | に、スイッチの要件を示します。

環境バックエンドスイッチを含む、MetroCluster構成で使用されるすべてのスイッチ。 


| link:concept-requirements-isls.html["ISL に関する考慮事項"] | に、ISLの要件を示します。

ネットワークトポロジ、およびネットアップ検証済みスイッチとMetroCluster準拠スイッチのどちらを使用しているかに関係なく、環境All MetroCluster構成。 


| link:concept-considerations-layer-2-layer-3.html["共有レイヤ2またはレイヤ3ネットワークにMetroClusterを導入する際の考慮事項"] | 共有レイヤ2またはレイヤ3ネットワークの要件について説明します。

環境：ネットアップ検証済みのスイッチを使用し、直接接続されたISLを使用するMetroCluster構成を除くすべての構成。 


| link:concept-requirement-and-limitations-mcc-compliant-switches.html["MetroCluster準拠スイッチを使用する場合の考慮事項"] | MetroCluster準拠スイッチの要件について説明します。

ネットアップ検証済みスイッチを使用していない環境All MetroCluster構成。 


| link:concept-example-network-topologies.html["MetroCluster ネットワークトポロジの例"] | に、さまざまなMetroClusterネットワークトポロジの例を示します。

環境All MetroCluster構成 
|===