---
permalink: install-ip/task_configuring_the_ontap_mediator_service_from_a_metrocluster_ip_configuration.html 
sidebar: sidebar 
keywords: metrocluster, mediator, configure 
summary: MetroCluster IP 構成で使用するには、ONTAP ノードで ONTAP Mediator を構成する必要があります。 
---
= MetroCluster IP構成用のONTAPメディエーターを設定する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
MetroCluster IP 構成で ONTAP Mediator を使用するには、 ONTAPノードでONTAP Mediator を構成する必要があります。

.作業を開始する前に
* ONTAP Mediator は、両方の MetroCluster サイトからアクセスできるネットワークの場所に正常にインストールされている必要があります。
+
link:https://docs.netapp.com/us-en/ontap/mediator/index.html["ONTAPメディエーターをインストールまたはアップグレードする"^]

* ONTAP Mediator を実行しているホストの IP アドレスが必要です。
* ONTAP Mediator のユーザー名とパスワードが必要です。
* MetroCluster IP 構成のすべてのノードがオンラインになっている必要があります。



CAUTION: ONTAP 9.12.1以降では、MetroCluster IP設定でMetroCluster 自動強制スイッチオーバー機能をイネーブルにできます。この機能は、メディエーターアシスト計画外スイッチオーバーの拡張機能です。この機能を有効にする前に、 link:concept-ontap-mediator-supports-automatic-unplanned-switchover.html#mauso-9-12-1["MetroCluster 自動強制スイッチオーバーを使用する場合のリスクと制限事項"]。

.このタスクについて
* このタスクでは、自動計画外スイッチオーバーをデフォルトで有効にします。
* このタスクは、MetroCluster IP構成内の任意のノードのONTAPインターフェースで実行できます。
* ONTAP 9.18.1およびONTAP Mediator 1.11以降では、iSCSIで構成された単一のONTAP Mediatorインスタンスで、最大10個のMetroCluster構成を同時に管理できます。ONTAP 9.17.1およびONTAP Mediator 1.10以前では、iSCSIで構成されたONTAP Mediatorは、最大5個のMetroCluster構成を同時にサポートできます。
* ONTAP 9.19.1およびONTAP Mediator 1.12以降では、iSCSIとHTTPSをサポートするONTAP Mediator、またはHTTPSのみをサポートするONTAP Mediatorをインストールできます。ONTAP MediatorをHTTPSのみでインストールした場合、iSCSIでMediatorを設定することはできません。
*  `-type`パラメータを `metrocluster configuration-settings mediator add`コマンドで指定しない場合、デフォルトのiSCSIプロトコルが使用されます。
* HTTPS を使用して ONTAP Mediator を設定する場合、単一の ONTAP Mediator インスタンスは 1 つの MetroCluster IP 設定のみを監視できます。ONTAP Mediator が HTTPS で設定されている場合、複数の MetroCluster IP 設定を同時に監視することはサポートされていません。
* 複数のMetroCluster IP構成を監視するためにHTTPSで構成されたONTAP Mediatorが必要な場合は、MetroCluster IP構成ごとに個別のONTAP Mediatorインスタンスを構成する必要があります。MetroCluster IPに対してHTTPSでONTAP Mediatorを構成することを選択する前に、MetroCluster IP環境の要件を慎重に評価する必要があります。
* 複数のMetroCluster IP構成を監視するために単一のONTAP Mediatorインスタンスを使用する場合は、HTTPSではなくiSCSIを使用してONTAP Mediatorを設定する必要があります。


[role="tabbed-block"]
====
.HTTPS を使用した ONTAP Mediator の設定
--
ONTAP 9.19.1 および ONTAP Mediator 1.12 以降では、MetroCluster IP 構成で HTTPS を使用して通信を行う ONTAP Mediator を設定できます。

.手順
. ONTAP Mediator Linux VM/ホストソフトウェアのインストール場所からONTAP Mediator CA証明書を見つけます：
+
`[root@ontap-mediator ~] cd /opt/netapp/lib/ontap_mediator/ontap_mediator/server_config`

+
次の例のような出力が表示されます。

+
[listing]
----
1-ontap-mediator.rules  intermediate.crt   make_self_signed_certs.sh      ontap_mediator_server_chain.crt  ontap_mediator.user_config.yaml  root_ca.crt
config_migration        intermediate.key   netapp_sudoers                 ontap_mediator_server.crt        openssl_ca.cnf                   root_ca.key
config.pyc              intermediate.srl   ontap_mediator.config.yaml     ontap_mediator_server.csr        openssl_intermediate.cnf
__init__.pyc            logging.conf.yaml  ontap_mediator.constants.yaml  ontap_mediator_server.key        openssl_server.cnf
----
. ルートCA証明書の内容を表示します：
+
`[root@ontap-mediator ~] cat root_ca.crt`

+
[listing]
----
-----BEGIN CERTIFICATE-----
<certificate_value>
-----END CERTIFICATE-----
----
. 中間CA証明書の内容を表示します：
+
`[root@ontap-mediator ~] cat intermediate.crt`

+
[listing]
----
-----BEGIN CERTIFICATE-----
<certificate_value>
-----END CERTIFICATE-----
----
. サイトAにルートCA証明書と中間CA証明書をインストールします：
+
.. ルートCA証明書をインストールします：
+
`security certificate install -type server-ca -vserver <vserver_name>`

+
プロンプトが表示されたら、次の例に示すように `root_ca.crt`を入力します。

+
[listing]
----
cluster_A::*> security certificate install -type server-ca -vserver cluster_A

Enter certificate: Press <Enter> when done

-----BEGIN CERTIFICATE-----
<certificate_value>
-----END CERTIFICATE-----

You should keep a copy of the CA-signed digital certificate for future
reference.

The installed certificate's CA and serial number for reference:
CA: ONTAP Mediator CA
serial: <serial_value>

The certificate's generated name for reference: ONTAPMediatorCA

cluster_A::*>

----


. 中間CA証明書をインストールします：
+
`security certificate install -type server-ca -vserver <vserver_name>`

+
プロンプトが表示されたら、次の例に示すように `intermediate.crt`を入力します。

+
[listing]
----
cluster_A::*> security certificate install -type server-ca -vserver cluster_A

Enter certificate: Press <Enter> when done

-----BEGIN CERTIFICATE-----
<certificate_value>
-----END CERTIFICATE-----

You should keep a copy of the CA-signed digital certificate for future
reference.

The installed certificate's CA and serial number for reference:
CA: ONTAP Mediator CA
serial: <serial_value>

The certificate's generated name for reference: ONTAPMediatorCA

cluster_A::*>

----
. 前の手順を繰り返して、サイトBにルートCA証明書と中間CA証明書をインストールします。
. 生成された証明書名を使用して、インストールされた自己署名CA証明書を表示します：
+
`security certificate show -common-name <common_name>`

+
次の例のような出力が表示されます。

+
[listing]
----
security certificate show -common-name ONTAPMediatorCA
Vserver    Serial Number      Certificate Name                     Type
---------- ---------------    ------------------------------------ ------------
cluster_A  <serial_value>     ONTAPMediatorCA                      server-ca
    Certificate Authority: ONTAP Mediator CA
          Expiration Date: Thu Nov 28 05:26:07 2030

cluster_A  <serial_value>    ONTAPMediatorCA                       server-ca
    Certificate Authority: ONTAP Mediator CA
          Expiration Date: Thu Nov 28 05:26:07 2030

2 entries were displayed.
----
. ONTAPにONTAP Mediator を追加します。手順は、IPv4 アドレスを使用するか、IPv6 アドレスを使用するかによって異なります。
+
[NOTE]
====
** IPv6 を使用するには、 ONTAP 9.18.1 以降およびONTAP Mediator 1.11 以降を実行している必要があります。
** クラスターで IPv6 を有効にすると、後で無効にすることはできません。


====
+
.. IPv6を使用する場合は、以下の手順を実行してください：
+
IPv4を使用するには、<<https_ipv4_step8b,IPv4ステップ>>にスキップします。

+
... 両方のクラスターで次のコマンドを実行します。
+
`network options ipv6 modify -enabled true`

... 4 つのノードすべてで、IPv6 アドレスを使用してノード管理 IP アドレスを設定します。
... ONTAPメディエーターを追加します。
+
`metrocluster configuration-settings mediator add -mediator-address <mediator_host_ipv6_ip_address> -type https-mediator`

+

NOTE: プロンプトが表示されたら、Mediator の管理者ユーザー名とパスワードを入力します。



.. [[https_ipv4_step8b]]IPv4を使用する場合は、次の手順を実行します：
+
... ONTAPメディエーターを追加します。
+
`metrocluster configuration-settings mediator add -mediator-address <mediator_host_ip_address> -type https-mediator`

+

NOTE: プロンプトが表示されたら、Mediator の管理者ユーザー名とパスワードを入力します。





. 接続ステータスとONTAP Mediatorタイプを確認します。
+
`metrocluster configuration-settings mediator show`

+
次の例のような出力が表示されます。

+
[listing]
----
cluster_A::*> metrocluster configuration-settings mediator show
        Mediator IP     Port    Type              Node                    Configuration Connection
                                                  Status                  Status
        --------------- ------- ----------------- ----------------------- ------------- -----------
        10.101.101.101
                        31784   https-mediator    cluster1_node_01        true          true
                                                  cluster1_node_02        true          true
                                                  cluster2_node_01        true          true
                                                  cluster2_node_02        true          true
----
+
.. 自動スイッチオーバー機能が有効になっていることを確認します。
+
「 MetroCluster show 」

.. メディエーターが実行されたことを確認します。
+
... メディエーターの仮想ディスクを表示します。
+
「 storage disk show -container-type mediator 」のように表示されます

+
....
 cluster_A::> storage disk show -container-type mediator
                        Usable           Disk    Container   Container
 Disk                   Size Shelf Bay Type    Type        Name      Owner
 ---------------- ---------- ----- --- ------- ----------- --------- --------
 NET-1.5                   -     -   - VMDISK  mediator    -         node_A_2
 NET-1.6                   -     -   - VMDISK  mediator    -         node_B_1
 NET-1.7                   -     -   - VMDISK  mediator    -         node_B_2
 NET-1.8                   -     -   - VMDISK  mediator    -         node_A_1
....
... Automatic Unplanned Switchover（AUSO；自動計画外スイッチオーバー）障害ドメインの状態を確認します。
+
「 MetroCluster show 」

+

NOTE: 次の例は、環境 ONTAP 9.13.1以降の出力を示しています。ONTAP 9.12.1以前では、AUSO障害ドメインの状態は `auso-on-cluster-disaster`。

+
[listing]
----
cluster_A::> metrocluster show
Cluster                   Entry Name          State
------------------------- ------------------- -----------
Local: cluster_A         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-dr-group-disaster
Remote: cluster_B         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-dr-group-disaster
----






--
.iSCSI を使用した ONTAP Mediator の設定
--
.手順
. ONTAPにONTAP Mediator を追加します。手順は、IPv4 アドレスを使用するか、IPv6 アドレスを使用するかによって異なります。
+
[NOTE]
====
** IPv6 を使用するには、 ONTAP 9.18.1 以降およびONTAP Mediator 1.11 以降を実行している必要があります。
** クラスターで IPv6 を有効にすると、後で無効にすることはできません。


====
+
.. IPv6を使用する場合は、以下の手順を実行してください：
+
IPv4を使用するには、<<iscsi_ipv4_step8b,IPv4ステップ>>にスキップします。

+
... 両方のクラスターで次のコマンドを実行します。
+
`network options ipv6 modify -enabled true`

... 4 つのノードすべてで、IPv6 アドレスを使用してノード管理 IP アドレスを設定します。
... ONTAPメディエーターを追加します。
+
`metrocluster configuration-settings mediator add -mediator-address <mediator_host_ipv6_ip_address> -type iscsi-mediator`

+

NOTE: プロンプトが表示されたら、Mediator の管理者ユーザー名とパスワードを入力します。



.. [[iscsi_ipv4_step8b]]IPv4を使用する場合は、次の手順を実行してください：
+
... ONTAPメディエーターを追加します。
+
`metrocluster configuration-settings mediator add -mediator-address <mediator_host_ip_address> -type iscsi-mediator`

+

NOTE: プロンプトが表示されたら、Mediator の管理者ユーザー名とパスワードを入力します。



.. 自動スイッチオーバー機能が有効になっていることを確認します。
+
「 MetroCluster show 」

.. メディエーターが実行されたことを確認します。
+
... メディエーターの仮想ディスクを表示します。
+
「 storage disk show -container-type mediator 」のように表示されます

+
....
 cluster_A::> storage disk show -container-type mediator
                        Usable           Disk    Container   Container
 Disk                   Size Shelf Bay Type    Type        Name      Owner
 ---------------- ---------- ----- --- ------- ----------- --------- --------
 NET-1.5                   -     -   - VMDISK  mediator    -         node_A_2
 NET-1.6                   -     -   - VMDISK  mediator    -         node_B_1
 NET-1.7                   -     -   - VMDISK  mediator    -         node_B_2
 NET-1.8                   -     -   - VMDISK  mediator    -         node_A_1
....
... 権限モードを advanced に設定します。
+
「高度」

+
....
 cluster_A::> set advanced
....
... mediator というラベルのイニシエータを表示します。
+
「 storage iscsi-initiator show -label mediator 」という名前のストレージがあります

+
....
 cluster_A::*> storage iscsi-initiator show -label mediator
   (storage iscsi-initiator show)
  +                                                                     Status
 Node Type Label    Target Portal      Target Name                      Admin/Op
 ---- ---- -------- ------------------ -------------------------------- --------
 node_A_1
      mailbox
           mediator 1.1.1.1       iqn.2012-05.local:mailbox.target.6616cd3f-9ef1-11e9-aada-00a098ccf5d8:a05e1ffb-9ef1-11e9-8f68- 00a098cbca9e:1 up/up
 node_A_2
      mailbox
           mediator 1.1.1.1       iqn.2012-05.local:mailbox.target.6616cd3f-9ef1-11e9-aada-00a098ccf5d8:a05e1ffb-9ef1-11e9-8f68-00a098cbca9e:1 up/up
....
... Automatic Unplanned Switchover（AUSO；自動計画外スイッチオーバー）障害ドメインの状態を確認します。
+
「 MetroCluster show 」

+

NOTE: 次の例は、環境 ONTAP 9.13.1以降の出力を示しています。ONTAP 9.12.1以前では、AUSO障害ドメインの状態は `auso-on-cluster-disaster`。

+
[listing]
----
cluster_A::> metrocluster show
Cluster                   Entry Name          State
------------------------- ------------------- -----------
Local: cluster_A         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-dr-group-disaster
Remote: cluster_B         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-dr-group-disaster
----






--
====