---
permalink: install-ip/task_switch_config_cisco_macsec.html 
sidebar: sidebar 
keywords: cisco, MACsec encryption 
summary: サイト間で実行される WAN ISL ポートにのみ MACsec 暗号化を設定する必要があります。正しい RCF ファイルを適用したあとに MACsec を設定する必要があります。 
---
= Cisco 9336C スイッチに MACsec 暗号化を設定します
:allow-uri-read: 


必要に応じて、サイト間で実行される WAN ISL ポートに MACsec 暗号化を設定できます。正しい RCF ファイルを適用したあとに MACsec を設定する必要があります。


NOTE: MACsec 暗号化は、 WAN ISL ポートにのみ適用できます。



== Cisco 9336C スイッチに MACsec 暗号化を設定します

サイト間で実行される WAN ISL ポートにのみ MACsec 暗号化を設定する必要があります。正しい RCF ファイルを適用したあとに MACsec を設定する必要があります。



=== MACsec のライセンス要件

MACsec にはセキュリティライセンスが必要です。Cisco NX-OS ライセンス方式の詳細およびライセンスの取得方法と適用方法については、を参照してください https://["『 Cisco NX-OS Licensing Guide 』"^]



=== MetroCluster IP構成でCisco MACsec暗号化WAN ISLを有効にします

MetroCluster IP 構成では、 WAN ISL 上の Cisco 9336C スイッチに対して MACsec 暗号化をイネーブルにできます。

.手順
. グローバルコンフィギュレーションモードを開始します。
+
「 configure terminal 」をクリックします

+
[listing]
----
IP_switch_A_1# configure terminal
IP_switch_A_1(config)#
----
. デバイスで MACsec と MKA を有効にします。
+
「 feature MACsec

+
[listing]
----
IP_switch_A_1(config)# feature macsec
----
. 実行コンフィギュレーションをスタートアップコンフィギュレーションにコピーします。
+
'copy running-config startup-config

+
[listing]
----
IP_switch_A_1(config)# copy running-config startup-config
----




=== MACsecキーチェーンとキーを設定します

MACsec キーチェーンまたはキーをコンフィギュレーションに作成できます。

* キーライフタイムと Hitless Key Rollover *

MACsec キーチェーンには、複数の Pre-Shared Key （ PSK; 事前共有キー）を設定できます。各 PSKs には、キー ID とオプションのライフタイムが設定されています。キーの有効期間は、キーがアクティブになって有効期限が切れるタイミングを指定します。ライフタイム設定がない場合、デフォルトのライフタイムは無制限です。ライフタイムが設定されている場合、ライフタイムが期限切れになると、 MKA はキーチェーン内で設定されている次の事前共有キーにロールオーバーします。キーのタイムゾーンは、 local または UTC です。デフォルトのタイムゾーンは UTC です。キーを同じキーチェーン内の 2 番目のキー（キーチェーン内）にロールオーバーして、最初のキーのライフタイムを設定することができます。最初のキーの有効期間が終了すると、自動的にリスト内の次のキーにロールオーバーされます。リンクの両側で同じキーが同時に設定されている場合、キーのロールオーバーはヒットレスになります（つまり、キーはトラフィックを中断することなくロールオーバーされます）。

.手順
. グローバルコンフィギュレーションモードを開始します。
+
「 configure terminal 」をクリックします

+
[listing]
----
IP_switch_A_1# configure terminal
IP_switch_A_1(config)#
----
. 暗号化されたキーオクテット文字列を非表示にするには、「 show running-config 」コマンドと「 show startup-config 」コマンドの出力で、文字列をワイルドカード文字に置き換えます。
+
[listing]
----
IP_switch_A_1(config)# key-chain macsec-psk no-show
----
+

NOTE: オクテット文字列は、コンフィギュレーションをファイルに保存するときにも非表示になります。

+
デフォルトでは、 PSK キーは暗号化形式で表示され、簡単に復号化できます。このコマンドは、 MACsec キーチェーンにのみ適用されます。

. MACsec キーチェーンを作成して一連の MACsec キーを保持し、 MACsec キーチェーンコンフィギュレーションモードを開始します。
+
キーチェーン名 MACsec

+
[listing]
----
IP_switch_A_1(config)# key chain 1 macsec
IP_switch_A_1(config-macseckeychain)#
----
. MACsec キーを作成し、 MACsec キーコンフィギュレーションモードを開始します。
+
「 key key-id 」

+
指定できる 16 進数のキー文字列の範囲は 1 ～ 32 で、最大サイズは 64 文字です。

+
[listing]
----
IP_switch_A_1 switch(config-macseckeychain)# key 1000
IP_switch_A_1 (config-macseckeychain-macseckey)#
----
. キーのオクテット文字列を設定します。
+
「 key-octet-string octet-string octet-string cryptographic-algorithm ae_128_CMAC | aes-256_CMAC 」という形式で指定します

+
[listing]
----
IP_switch_A_1(config-macseckeychain-macseckey)# key-octet-string abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789
cryptographic-algorithm AES_256_CMAC
----
+

NOTE: octet-string 引数には、最大 64 個の 16 進文字を含めることができます。オクテットキーは内部でエンコードされるため、クリアテキストのキーは、「 show running-config macsec 」コマンドの出力には表示されません。

. キーの送信ライフタイムを設定します（秒単位）。
+
「 send-lifetime start-time duration 」

+
[listing]
----
IP_switch_A_1(config-macseckeychain-macseckey)# send-lifetime 00:00:00 Oct 04 2020 duration 100000
----
+
デフォルトでは、デバイスは開始時間を UTC として処理します。start-time 引数には、キーがアクティブになる時刻と日付を指定します。duration 引数は、ライフタイムの秒単位の長さです。最大値は 2147483646 秒（約 68 年）です。

. 実行コンフィギュレーションをスタートアップコンフィギュレーションにコピーします。
+
'copy running-config startup-config

+
[listing]
----
IP_switch_A_1(config)# copy running-config startup-config
----
. キーチェーン設定を表示します。
+
「鍵チェーン名」

+
[listing]
----
IP_switch_A_1(config-macseckeychain-macseckey)# show key chain 1
----




=== MACsecポリシーを設定します

.手順
. グローバルコンフィギュレーションモードを開始します。
+
「 configure terminal 」をクリックします

+
[listing]
----
IP_switch_A_1# configure terminal
IP_switch_A_1(config)#
----
. MACsec ポリシーを作成します。
+
「 ACSEC ポリシー名」

+
[listing]
----
IP_switch_A_1(config)# macsec policy abc
IP_switch_A_1(config-macsec-policy)#
----
. 次のいずれかの暗号、 gcm-aes-128 、 gcm-aes-256 、 gcm-aes-xpN-128 、または gcm-aes-xpN-256 を設定します。
+
「 cipher-site name 」

+
[listing]
----
IP_switch_A_1(config-macsec-policy)# cipher-suite GCM-AES-256
----
. キー交換時にピア間の接続を解除するために、キーサーバの優先度を設定します。
+
「 key-server -priority number 」と入力します

+
[listing]
----
switch(config-macsec-policy)# key-server-priority 0
----
. データおよび制御パケットの処理を定義するセキュリティポリシーを設定します。
+
「セキュリティ・ポリシー・セキュリティ・ポリシー」を参照してください

+
次のオプションからセキュリティポリシーを選択します。

+
** must-secure -- MACsec ヘッダーを伝送していないパケットはドロップされます
** must-secure -- MACsec ヘッダーを伝送しないパケットは許可されます ( これがデフォルト値です ) 。


+
[listing]
----
IP_switch_A_1(config-macsec-policy)# security-policy should-secure
----
. リプレイ保護ウィンドウを設定して、セキュアインターフェイスが設定されたウィンドウサイズより小さいパケットを受け入れないようにします。「 window-size number 」
+

NOTE: リプレイ保護ウィンドウのサイズは、 MACsec が受信して破棄されない最大アウトオブシーケンスフレーム数を表します。指定できる範囲は 0 ～ 596000000 です。

+
[listing]
----
IP_switch_A_1(config-macsec-policy)# window-size 512
----
. SAK キーの再生成を強制する時間を秒単位で設定します。
+
「 SAK-expiry-date time 」

+
このコマンドを使用して、予測可能な時間間隔にセッションキーを変更できます。デフォルトは 0 です。

+
[listing]
----
IP_switch_A_1(config-macsec-policy)# sak-expiry-time 100
----
. 暗号化を開始するレイヤ 2 フレームで、次の機密性オフセットのいずれかを設定します。
+
「 conf-offsetconfidentiality offset 」を参照してください

+
次のいずれかのオプションを選択します。

+
** conf-offset-0 。
** conf-offset-30 。
** conf -offset-50 。
+
[listing]
----
IP_switch_A_1(config-macsec-policy)# conf-offset CONF-OFFSET-0
----
+

NOTE: このコマンドは、中間スイッチが MPLS タグのようなパケットヘッダー（ DMAC 、 smac 、 type ）を使用するために必要な場合があります。



. 実行コンフィギュレーションをスタートアップコンフィギュレーションにコピーします。
+
'copy running-config startup-config

+
[listing]
----
IP_switch_A_1(config)# copy running-config startup-config
----
. MACsec ポリシー設定を表示します。
+
「 MACsec ポリシー」

+
[listing]
----
IP_switch_A_1(config-macsec-policy)# show macsec policy
----




=== インターフェイス上でCisco MACsec暗号化をイネーブルにします

. グローバルコンフィギュレーションモードを開始します。
+
「 configure terminal 」をクリックします

+
[listing]
----
IP_switch_A_1# configure terminal
IP_switch_A_1(config)#
----
. MACsec暗号化で設定したインターフェイスを選択します。
+
インターフェイスのタイプと ID を指定できます。イーサネットポートの場合は、イーサネットスロット / ポートを使用します。

+
[listing]
----
IP_switch_A_1(config)# interface ethernet 1/15
switch(config-if)#
----
. インターフェイスに設定するキーチェーンとポリシーを追加して、MACsec設定を追加します。
+
「MACsec keychain -name policy policy-name」という名前のキーチェーンがあります

+
[listing]
----
IP_switch_A_1(config-if)# macsec keychain 1 policy abc
----
. MACsec暗号化を設定するすべてのインターフェイスで、ステップ1と2を繰り返します。
. 実行コンフィギュレーションをスタートアップコンフィギュレーションにコピーします。
+
'copy running-config startup-config

+
[listing]
----
IP_switch_A_1(config)# copy running-config startup-config
----




=== MetroCluster IP構成でCisco MACsec暗号化WAN ISLをディセーブルにします

MetroCluster IP 構成では、 WAN ISL 上の Cisco 9336C スイッチに対して MACsec 暗号化を無効にする必要がある場合があります。

.手順
. グローバルコンフィギュレーションモードを開始します。
+
「 configure terminal 」をクリックします

+
[listing]
----
IP_switch_A_1# configure terminal
IP_switch_A_1(config)#
----
. デバイスの MACsec 設定を無効にします。
+
「 ACSEC SHUTDOWN 」のようになります

+
[listing]
----
IP_switch_A_1(config)# macsec shutdown
----
+

NOTE: 「 no 」オプションを選択すると、 MACsec 機能が復元されます。

. MACsec で設定済みのインターフェイスを選択します。
+
インターフェイスのタイプと ID を指定できます。イーサネットポートの場合は、イーサネットスロット / ポートを使用します。

+
[listing]
----
IP_switch_A_1(config)# interface ethernet 1/15
switch(config-if)#
----
. インターフェイスに設定されているキーチェーンとポリシーを削除して、MACsec設定を削除します。
+
「no MACsec keychain keychain -name policy policy-name」

+
[listing]
----
IP_switch_A_1(config-if)# no macsec keychain 1 policy abc
----
. MACsec が設定されているすべてのインターフェイスで、ステップ 3 と 4 を繰り返します。
. 実行コンフィギュレーションをスタートアップコンフィギュレーションにコピーします。
+
'copy running-config startup-config

+
[listing]
----
IP_switch_A_1(config)# copy running-config startup-config
----




=== MACsec 構成の確認

.手順
. コンフィギュレーション内の 2 番目のスイッチで上記の手順 * すべて * を繰り返して、 MACsec セッションを確立します。
. 次のコマンドを実行して、両方のスイッチが正常に暗号化されたことを確認します。
+
.. 「 How MACsec mka summary 」を実行します
.. 実行 :'How MACsec mka session`
.. 実行： 'How MACsec mka statistics （ MACsec mka 統計情報）
+
MACsec 設定を確認するには、次のコマンドを使用します。

+
|===


| コマンドを実行します | 表示される情報 


 a| 
'How MACsec mka session interface types/port number
 a| 
特定のインターフェイスまたはすべてのインターフェイスの MACsec MKA セッション



 a| 
「鍵チェーン名」
 a| 
キーチェーン設定



 a| 
「 MACsec mka の概要」を参照してください
 a| 
MACsec MKA 設定



 a| 
'How MACsec policy policy-name' 」を参照してください
 a| 
特定の MACsec ポリシーまたはすべての MACsec ポリシーの設定

|===



