---
permalink: install-ip/task_configuring_the_ontap_mediator_service_from_a_metrocluster_ip_configuration.html 
sidebar: sidebar 
keywords: metrocluster, mediator, configure 
summary: MetroCluster IP 構成で ONTAP メディエーターサービスを使用するには、 ONTAP ノードで設定する必要があります。 
---
= MetroCluster IP 構成での ONTAP メディエーターサービスの設定
:icons: font
:imagesdir: ../media/


[role="lead"]
MetroCluster IP 構成で ONTAP メディエーターサービスを使用するには、 ONTAP ノードで設定する必要があります。

.作業を開始する前に
* 両方の MetroCluster サイトからアクセスできるネットワークの場所に ONTAP メディエーターがインストールされている必要があります。
* ONTAP メディエーターサービスを実行するホストの IP アドレスが必要です。
* ONTAP メディエーターサービスのユーザ名とパスワードが必要です。
* MetroCluster IP 構成のすべてのノードがオンラインになっている必要があります。


.このタスクについて
* このタスクでは、自動計画外スイッチオーバーをデフォルトで有効にします。
* このタスクは、 MetroCluster IP 構成の任意のノードの ONTAP インターフェイスで実行できます。
* ONTAP メディエーターサービスは、 1 つのインストールにつき最大 5 つの MetroCluster IP 構成で設定できます。


.手順
. 次のコマンドを使用して、 ONTAP メディエーターサービスを ONTAP に追加します。
+
MetroCluster の構成設定メディエーターの追加メディエーターのアドレス IP-addressof mediator-host`

+

NOTE: メディエーターの admin ユーザアカウントのユーザ名とパスワードを入力するように求められます。

. 自動スイッチオーバー機能が有効になっていることを確認します。
+
「 MetroCluster show 」

. メディエーターが実行されたことを確認します。
+
.. メディエーターの仮想ディスクを表示します。
+
「 storage disk show -container-type mediator 」のように表示されます

+
....
 cluster_A::> storage disk show -container-type mediator
                        Usable           Disk    Container   Container
 Disk                   Size Shelf Bay Type    Type        Name      Owner
 ---------------- ---------- ----- --- ------- ----------- --------- --------
 NET-1.5                   -     -   - VMDISK  mediator    -         node_A_2
 NET-1.6                   -     -   - VMDISK  mediator    -         node_B_1
 NET-1.7                   -     -   - VMDISK  mediator    -         node_B_2
 NET-1.8                   -     -   - VMDISK  mediator    -         node_A_1
....
.. 権限モードを advanced に設定します。
+
「高度」

+
....
 cluster_A::> set advanced
....
.. mediator というラベルのイニシエータを表示します。
+
「 storage iscsi-initiator show -label mediator 」という名前のストレージがあります

+
....
 cluster_A::*> storage iscsi-initiator show -label mediator
   (storage iscsi-initiator show)
  +                                                                     Status
 Node Type Label    Target Portal      Target Name                      Admin/Op
 ---- ---- -------- ------------------ -------------------------------- --------
 node_A_1
      mailbox
           mediator 1.1.1.1       iqn.2012-05.local:mailbox.target.6616cd3f-9ef1-11e9-aada-00a098ccf5d8:a05e1ffb-9ef1-11e9-8f68- 00a098cbca9e:1 up/up
 node_A_2
      mailbox
           mediator 1.1.1.1       iqn.2012-05.local:mailbox.target.6616cd3f-9ef1-11e9-aada-00a098ccf5d8:a05e1ffb-9ef1-11e9-8f68-00a098cbca9e:1 up/up
....



