---
permalink: install-ip/task_remove_unconfigure_mediator.html 
sidebar: sidebar 
keywords: ontap, mediator, assist, remove, unconfigure, requirements, mediator requirements 
summary: MetroCluster IP 構成から ONTAP メディエーターを削除できます。 
---
= MetroCluster IP構成からONTAPメディエーターを削除する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
MetroCluster IP 構成から ONTAP Mediator の構成を解除できます。

.作業を開始する前に
両方の MetroCluster サイトからアクセスできるネットワークの場所に ONTAP Mediator を正常にインストールして構成しておく必要があります。

.手順
. 次のコマンドを使用して、ONTAP Mediator の構成を解除します。
+
MetroCluster 構成設定のメディエーターが削除されました

+
ONTAPメディエーターの管理者ユーザアカウントのユーザ名とパスワードの入力を求められます。

+

NOTE: ONTAPメディエーターがダウンしている場合は、  `metrocluster configuration-settings mediator remove`コマンドを実行すると、引き続き ONTAP Mediator 管理者ユーザー アカウントのユーザー名とパスワードの入力が求められ、MetroCluster 構成から ONTAP Mediator が削除されます。

+
.. 次のコマンドを使用して、破損ディスクがないかどうかを確認します。
+
「disk show -broken」

+
* 例 *

+
....
There are no entries matching your query.
....


. HTTPS を使用して通信を行う ONTAP Mediator を使用している場合は、ONTAP Mediator を削除した後に CA 証明書を削除します：
+
.. インストールされているCA証明書を表示します：
+
`security certificate show -common-name ONTAPMediatorCA`

.. インストール済みのルート証明書と中間証明書を削除します：
+
`security certificate delete -vserver cluster-A -common-name ONTAPMediatorCA -cert-name <root_certificate_name> -type server-ca -ca "ONTAP Mediator CA"`

+
`security certificate delete -vserver cluster-A -common-name ONTAPMediatorCA -cert-name <intermediate_certificate_name> -type server-ca -ca "ONTAP Mediator CA"`



. 両方のクラスタで次のコマンドを実行して、ONTAP MediatorがMetroCluster構成から削除されたことを確認します：
+
.. `metrocluster configuration-settings mediator show`
+
* 例 *

+
[listing]
----
This table is currently empty.
----



