---
permalink: install-ip/task_configuring_the_ontap_mediator_service_from_a_metrocluster_ip_configuration.html 
sidebar: sidebar 
keywords: metrocluster, mediator, configure 
summary: MetroCluster IP 構成で使用するには、ONTAP ノードで ONTAP Mediator を構成する必要があります。 
---
= MetroCluster IP構成用のONTAPメディエーターを設定する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
MetroCluster IP 構成で使用するには、ONTAP ノードで ONTAP Mediator を構成する必要があります。

.作業を開始する前に
* ONTAP Mediator は、両方の MetroCluster サイトからアクセスできるネットワークの場所に正常にインストールされている必要があります。
+
link:https://docs.netapp.com/us-en/ontap/mediator/index.html["ONTAPメディエーターをインストールまたはアップグレードする"^]

* ONTAP Mediator を実行しているホストの IP アドレスが必要です。
* ONTAP Mediator のユーザー名とパスワードが必要です。
* MetroCluster IP 構成のすべてのノードがオンラインになっている必要があります。



CAUTION: ONTAP 9.12.1以降では、MetroCluster IP設定でMetroCluster 自動強制スイッチオーバー機能をイネーブルにできます。この機能は、メディエーターアシスト計画外スイッチオーバーの拡張機能です。この機能を有効にする前に、 link:concept-ontap-mediator-supports-automatic-unplanned-switchover.html#mauso-9-12-1["MetroCluster 自動強制スイッチオーバーを使用する場合のリスクと制限事項"]。

.このタスクについて
* このタスクでは、自動計画外スイッチオーバーをデフォルトで有効にします。
* このタスクは、 MetroCluster IP 構成の任意のノードの ONTAP インターフェイスで実行できます。
* ONTAP Mediator の 1 つのインストールで、最大 5 つの MetroCluster IP 構成を設定できます。


.手順
. ONTAP に ONTAP Mediator を追加します。
+
MetroCluster の構成設定メディエーターの追加 mediator-address_ip-address-bmediator-host_`

+

NOTE: メディエーターの admin ユーザアカウントのユーザ名とパスワードを入力するように求められます。

. 自動スイッチオーバー機能が有効になっていることを確認します。
+
「 MetroCluster show 」

. メディエーターが実行されたことを確認します。
+
.. メディエーターの仮想ディスクを表示します。
+
「 storage disk show -container-type mediator 」のように表示されます

+
....
 cluster_A::> storage disk show -container-type mediator
                        Usable           Disk    Container   Container
 Disk                   Size Shelf Bay Type    Type        Name      Owner
 ---------------- ---------- ----- --- ------- ----------- --------- --------
 NET-1.5                   -     -   - VMDISK  mediator    -         node_A_2
 NET-1.6                   -     -   - VMDISK  mediator    -         node_B_1
 NET-1.7                   -     -   - VMDISK  mediator    -         node_B_2
 NET-1.8                   -     -   - VMDISK  mediator    -         node_A_1
....
.. 権限モードを advanced に設定します。
+
「高度」

+
....
 cluster_A::> set advanced
....
.. mediator というラベルのイニシエータを表示します。
+
「 storage iscsi-initiator show -label mediator 」という名前のストレージがあります

+
....
 cluster_A::*> storage iscsi-initiator show -label mediator
   (storage iscsi-initiator show)
  +                                                                     Status
 Node Type Label    Target Portal      Target Name                      Admin/Op
 ---- ---- -------- ------------------ -------------------------------- --------
 node_A_1
      mailbox
           mediator 1.1.1.1       iqn.2012-05.local:mailbox.target.6616cd3f-9ef1-11e9-aada-00a098ccf5d8:a05e1ffb-9ef1-11e9-8f68- 00a098cbca9e:1 up/up
 node_A_2
      mailbox
           mediator 1.1.1.1       iqn.2012-05.local:mailbox.target.6616cd3f-9ef1-11e9-aada-00a098ccf5d8:a05e1ffb-9ef1-11e9-8f68-00a098cbca9e:1 up/up
....
.. Automatic Unplanned Switchover（AUSO；自動計画外スイッチオーバー）障害ドメインの状態を確認します。
+
「 MetroCluster show 」

+

NOTE: 次の例は、環境 ONTAP 9.13.1以降の出力を示しています。ONTAP 9.12.1以前では、AUSO障害ドメインの状態は `auso-on-cluster-disaster`。

+
[listing]
----
cluster_A::> metrocluster show
Cluster                   Entry Name          State
------------------------- ------------------- -----------
Local: cluster_A         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-dr-group-disaster
Remote: cluster_B         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-dr-group-disaster
----


. 必要に応じて、MetroClusterの自動強制スイッチオーバーを設定します。
+
次のコマンドはadvanced権限レベルでのみ使用できます。

+

IMPORTANT: このコマンドを使用する前に、 link:concept-ontap-mediator-supports-automatic-unplanned-switchover.html#mauso-9-12-1["MetroCluster 自動強制スイッチオーバーを使用する場合のリスクと制限事項"]。

+
`metrocluster modify -allow-auto-forced-switchover true`

+
....
cluster_A::*> metrocluster modify -allow-auto-forced-switchover true
....

