---
permalink: install-ip/task_remove_unconfigure_mediator.html 
sidebar: sidebar 
keywords: ontap, mediator, assist, remove, unconfigure, requirements, mediator requirements 
summary: MetroCluster IP 構成から ONTAP メディエーターを削除できます。 
---
= MetroCluster IP構成からONTAPメディエーターを削除する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
MetroCluster IP 構成から ONTAP Mediator の構成を解除できます。

.作業を開始する前に
両方の MetroCluster サイトからアクセスできるネットワークの場所に ONTAP Mediator を正常にインストールして構成しておく必要があります。

.手順
. 次のコマンドを使用して、ONTAP Mediator の構成を解除します。
+
MetroCluster 構成設定のメディエーターが削除されました

+
ONTAPメディエーターの管理者ユーザアカウントのユーザ名とパスワードの入力を求められます。

+

NOTE: ONTAPメディエーターがダウンしている場合は、  `metrocluster configuration-settings mediator remove`コマンドを実行すると、引き続き ONTAP Mediator 管理者ユーザー アカウントのユーザー名とパスワードの入力が求められ、MetroCluster 構成から ONTAP Mediator が削除されます。

+
.. 次のコマンドを使用して、破損ディスクがないかどうかを確認します。
+
「disk show -broken」

+
* 例 *

+
....
There are no entries matching your query.
....


. 両方のクラスタで次のコマンドを実行して、ONTAP Mediator が MetroCluster 構成から削除されていることを確認します。
+
.. `metrocluster configuration-settings mediator show`
+
* 例 *

+
[listing]
----
This table is currently empty.
----
.. 「 storage iscsi-initiator show -label mediator 」という名前のストレージがあります
+
* 例 *

+
[listing]
----
There are no entries matching your query.
----



