---
permalink: install-ip/task_changing_mediator_password.html 
sidebar: sidebar 
keywords: mediator, password, change 
summary: ONTAP メディエーターサービスをインストールしたあと、必要に応じてパスワードを変更できます。パスワードは 2 つの方法で変更できます。 
---
= ONTAP メディエーターのパスワードを変更しています
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP メディエーターサービスをインストールしたあと、必要に応じてパスワードを変更できます。パスワードは 2 つの方法で変更できます。

このタスクは、 ONTAP メディエーターサービスがインストールされた Linux ホストで実行します。

このコマンドを実行できない場合は、次の例のように完全パスを使用してコマンドを実行する必要があります。

`/usr/local/bin/mediator_change_password`

次のいずれかを実行してパスワードを変更します。

* 「 mediator_change_password 」コマンドを実行し、次の例に示すようにプロンプトに応答します。
+
....
 [root@mediator-host ~]# mediator_change_password
 Change the Mediator API password by entering the following values:
    Mediator API User Name: mediatoradmin
              Old Password:
              New Password:
          Confirm Password:
 The password has been updated successfully.
 [root@mediator-host ~]#
....
* 次のコマンドを実行します。
+
`m EDIATOR_USERNAME=mediatoradmin mediator_password=mediator1 mediator1 mediator_new_password=mediator2 mediator2 mediator_change_password'

+
この例では、パスワードが「 mediator1 」から「 mediator2 」に変更されています。

+
....
 [root@mediator-host ~]# MEDIATOR_USERNAME=mediatoradmin MEDIATOR_PASSWORD=mediator1 MEDIATOR_NEW_PASSWORD=mediator2 mediator_change_password
 The password has been updated successfully.
 [root@mediator-host ~]#
....

