---
permalink: install-ip/task_switch_config_broadcom.html 
sidebar: sidebar 
keywords: ip, switch, connection, configuring, configure, broadcom, factory defaults 
summary: クラスタインターコネクトおよびバックエンド MetroCluster IP 接続用に Broadcom IP スイッチを設定する必要があります。 
---
= Broadcom IP スイッチの設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クラスタインターコネクトおよびバックエンド MetroCluster IP 接続用に Broadcom IP スイッチを設定する必要があります。


NOTE: 次のような場合は、構成に追加のライセンス（100Gbポートライセンス×6）が必要になります。

* ポート53および54を40Gbpsまたは100GbpsのMetroCluster ISLとして使用します。
* ローカルクラスタインターフェイスとMetroCluster インターフェイスをポート49-52に接続するプラットフォームを使用します。




== Broadcom IP スイッチを工場出荷時のデフォルトにリセット

新しいバージョンのスイッチソフトウェアと RCF をインストールする前に、 Broadcom スイッチの設定を消去し、基本的な設定を完了する必要があります。

.このタスクについて
* この手順は、 MetroCluster IP 構成の各 IP スイッチで実行する必要があります。
* シリアルコンソールを使用してスイッチに接続する必要があります。
* このタスクでは、管理ネットワークの設定をリセットします。


.手順
. 昇格されたコマンドプロンプト (`#`):'enable' に変更します
+
[listing]
----
(IP_switch_A_1)> enable
(IP_switch_A_1) #
----
. スタートアップコンフィギュレーションを消去し、バナーを削除します
+
.. スタートアップ設定を消去します。
+
*`erase startup-config *

+
[listing]
----
(IP_switch_A_1) #erase startup-config

Are you sure you want to clear the configuration? (y/n) y

(IP_switch_A_1) #
----
+
このコマンドでは、バナーは消去されません。

.. バナーを削除します。
+
*`no set clibanner`*

+
[listing]
----
(IP_switch_A_1) #configure
(IP_switch_A_1)(Config) # no set clibanner
(IP_switch_A_1)(Config) #
----


. スイッチを再起動します *`(IP_switch_A_1 )#reload *`
+
[listing]
----
Are you sure you would like to reset the system? (y/n) y
----
+

NOTE: スイッチをリロードする前に、未保存または変更された設定を保存するかどうかを確認するメッセージが表示された場合は、 *No* を選択します。

. スイッチがリロードされるまで待ってから、スイッチにログインします。
+
デフォルトのユーザは「 admin 」で、パスワードは設定されていません。次のようなプロンプトが表示されます。

+
[listing]
----
(Routing)>
----
. 管理者特権のコマンドプロンプトに切り替えます。
+
「 enable 」を選択します

+
[listing]
----
Routing)> enable
(Routing) #
----
. サービスポートプロトコルを「 none 」に設定します。
+
「サービスポートプロトコルなし」

+
[listing]
----
(Routing) #serviceport protocol none
Changing protocol mode will reset ip configuration.
Are you sure you want to continue? (y/n) y

(Routing) #
----
. サービスポートに IP アドレスを割り当てます。
+
'erviceport IP_address__netmask__ gateway_

+
次の例では、サービスポートに IP アドレス「 10.10.10.10 」が割り当てられています。サブネットは「 255.255.255.0 」、ゲートウェイは「 10.10.10.1 」です。

+
[listing]
----
(Routing) #serviceport ip 10.10.10.10 255.255.255.0 10.10.10.1
----
. サービスポートが正しく設定されていることを確認します。
+
'How serviceport

+
次の例は、ポートが稼働しており、正しいアドレスが割り当てられていることを示しています。

+
[listing]
----
(Routing) #show serviceport

Interface Status............................... Up
IP Address..................................... 10.10.10.10
Subnet Mask.................................... 255.255.255.0
Default Gateway................................ 10.10.10.1
IPv6 Administrative Mode....................... Enabled
IPv6 Prefix is ................................ fe80::dac4:97ff:fe56:87d7/64
IPv6 Default Router............................ fe80::222:bdff:fef8:19ff
Configured IPv4 Protocol....................... None
Configured IPv6 Protocol....................... None
IPv6 AutoConfig Mode........................... Disabled
Burned In MAC Address.......................... D8:C4:97:56:87:D7

(Routing) #
----
. 必要に応じて、 SSH サーバを設定します。
+

NOTE: RCF ファイルで Telnet プロトコルが無効になります。SSH サーバを設定しない場合は、シリアルポート接続を使用してブリッジにアクセスする必要があります。

+
.. RSA キーを生成します。
+
[listing]
----
(Routing) #configure
(Routing) (Config)#crypto key generate rsa
----
.. DSA キーの生成（オプション）
+
[listing]
----
(Routing) #configure
(Routing) (Config)#crypto key generate dsa
----
.. FIPS 準拠バージョンの EFOS を使用している場合は、 ECDSA キーを生成します。次の例では、長さ 256 のキーを作成します。有効な値は、 256 、 384 、または 521 です。
+
[listing]
----
(Routing) #configure
(Routing) (Config)#crypto key generate ecdsa 256
----
.. SSH サーバを有効にします。
+
必要に応じて、設定コンテキストを終了します。

+
[listing]
----
(Routing) (Config)#end
(Routing) #ip ssh server enable
----
+

NOTE: キーがすでに存在する場合は、それらを上書きするように求められることがあります。



. 必要に応じて、ドメインとネームサーバを設定します。
+
「 configure 」を実行します

+
次に 'ip domain' コマンドと 'ip name server' コマンドの例を示します

+
[listing]
----
(Routing) # configure
(Routing) (Config)#ip domain name lab.netapp.com
(Routing) (Config)#ip name server 10.99.99.1 10.99.99.2
(Routing) (Config)#exit
(Routing) (Config)#
----
. 必要に応じて、タイムゾーンと時刻の同期（ SNTP ）を設定します。
+
次に 'ntp' コマンドの例を示しますこの例では 'sntp サーバの IP アドレスと相対タイム・ゾーンを指定します

+
[listing]
----
(Routing) #
(Routing) (Config)#sntp client mode unicast
(Routing) (Config)#sntp server 10.99.99.5
(Routing) (Config)#clock timezone -7
(Routing) (Config)#exit
(Routing) (Config)#
----
. スイッチ名を設定します。
+
'hostname ip_switch_a_1'

+
スイッチのプロンプトに新しい名前が表示されます。

+
[listing]
----
(Routing) # hostname IP_switch_A_1

(IP_switch_A_1) #
----
. 設定を保存します。
+
「メモリの書き込み」

+
次の例のようなプロンプトと出力が表示されます。

+
[listing]
----
(IP_switch_A_1) #write memory

This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y

Config file 'startup-config' created successfully .


Configuration Saved!

(IP_switch_A_1) #
----
. MetroCluster IP 構成の他の 3 つのスイッチについて、上記の手順を繰り返します。




== Broadcom スイッチの EFOS ソフトウェアのダウンロードとインストール

MetroCluster IP 構成の各スイッチにスイッチのオペレーティングシステムファイルと RCF ファイルをダウンロードする必要があります。

このタスクは、 MetroCluster IP 構成内のスイッチごとに実行する必要があります。

====
* 次の点に注意してください。 *

* EFOS 3.x.x から EFOS 3.x.x 以降にアップグレードするときは、スイッチが EFOS 3.4.4.6 （または 3.4.x.x 以降のリリース）を実行している必要があります。それよりも前のリリースを実行している場合は、まずスイッチを EFOS 3.4.4.6 （または 3.4.x.x 以降のリリース）にアップグレードしてから、スイッチを EFOS 3.x.x 以降にアップグレードします。
* EFOS 3.x.x と 3.7.x.x 以降の設定は異なります。EFOS バージョンを 3.4.x.x から 3.7.x.x 以降、またはその逆に変更する場合は、スイッチを工場出荷時のデフォルトにリセットする必要があり、対応する EFOS バージョンの RCF ファイルが適用される（再適用される）必要があります。この手順には、シリアルコンソールポート経由でアクセスする必要があります。
* EFOS バージョン 3.7.x.x 以降では、 FIPS に準拠していないバージョンと FIPS に準拠したバージョンが提供されています。FIPS に準拠していないバージョンから FIPS に準拠したバージョンに移行する場合とその逆に移行する場合は、さまざまな手順があります。EFOS を FIPS 非準拠バージョンから FIPS 準拠バージョンに変更するか、その逆に変更すると、スイッチが工場出荷時のデフォルトにリセットされます。この手順には、シリアルコンソールポート経由でアクセスする必要があります。


====
.手順
. 「show fips status」コマンドを使用して、EFOSのバージョンがFIPSに準拠しているか、FIPSに準拠していないかを確認します。次の例では'ip_switch_a_1'はFIPS準拠のEFOSを使用しており'ip_switch_a_2'はFIPS非準拠のEFOSを使用しています
+
*例1 *

+
[listing]
----
IP_switch_A_1 #show fips status

System running in FIPS mode

IP_switch_A_1 #
----
+
*例2 *

+
[listing]
----
IP_switch_A_2 #show fips status
                     ^
% Invalid input detected at `^` marker.

IP_switch_A_2 #
----
. 次の表を参照して、実行する必要がある方法を確認してください。
+
|===


| * 手順 * | * 現在の EFOS バージョン * | * 新しい EFOS バージョン * | * 高レベルステップ * 


 a| 
FIPS に準拠している 2 つのバージョン間で EFOS をアップグレードする手順
 a| 
3.4.x.x
 a| 
3.4.x.x
 a| 
方法 1 ）設定とライセンスの情報は保持されています



 a| 
3.4.4.6 （または 3.4.x.x 以降）
 a| 
3.7.x.x 以降の非 FIPS 準拠
 a| 
方法 1 を使用して EFOS をアップグレードします。スイッチを工場出荷時のデフォルトにリセットして、 EFOS 3.x.x 以降の RCF ファイルを適用します



.2+| 3.7.x.x 以降の非 FIPS 準拠  a| 
3.4.4.6 （または 3.4.x.x 以降）
 a| 
方法 1 を使用して EFOS をダウングレードします。スイッチを工場出荷時のデフォルトにリセットして、 EFOS 3.x.x の RCF ファイルを適用します



 a| 
3.7.x.x 以降の非 FIPS 準拠
 a| 
方法 1 を使用して新しい EFOS イメージをインストールします。構成とライセンスの情報は保持されます



 a| 
3.7.x.x 以降の FIPS に準拠しています
 a| 
3.7.x.x 以降の FIPS に準拠しています
 a| 
方法 1 を使用して新しい EFOS イメージをインストールします。構成とライセンスの情報は保持されます



 a| 
FIPS 準拠の EFOS バージョンへのアップグレード手順
 a| 
FIPS に準拠していません
 a| 
FIPS に準拠している
 a| 
方法 2 を使用した EFOS イメージのインストールスイッチの設定とライセンス情報が失われます。



 a| 
FIPS に準拠している
 a| 
FIPS に準拠していません

|===
+
** 方法 1 ：  to upgrade EFOS with downloading the software image to the backup boot partition
** 方法 2 ：  to upgrade EFOS using the ONIE OS installation






=== ソフトウェアイメージをバックアップブートパーティションにダウンロードして EFOS をアップグレードする手順

次の手順を実行できるのは、両方の EFOS バージョンが FIPS 非準拠であるか、両方の EFOS バージョンが FIPS 準拠である場合のみです。


NOTE: FIPS に準拠したバージョンで、もう一方のバージョンが FIPS に準拠していない場合は、次の手順を使用しないでください。

.手順
. スイッチソフトウェアをスイッチにコピーします :+copy sftp://user@50.50.50.50 /switchsoftware/efos-3.4.6.stk backup+`
+
この例では、 efos-3.4.6.stk オペレーティングシステムファイルが SFTP サーバ（ 50.50.50 ）からバックアップパーティションにコピーされています。使用する TFTP / SFTP サーバの IP アドレスを指定し、インストールする必要がある RCF ファイルのファイル名を指定する必要があります。

+
[listing]
----
(IP_switch_A_1) #copy sftp://user@50.50.50.50/switchsoftware/efos-3.4.4.6.stk backup
Remote Password:*************

Mode........................................... SFTP
Set Server IP.................................. 50.50.50.50
Path........................................... /switchsoftware/
Filename....................................... efos-3.4.4.6.stk
Data Type...................................... Code
Destination Filename........................... backup

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) y

File transfer in progress. Management access will be blocked for the duration of the transfer. Please wait...
SFTP Code transfer starting...


File transfer operation completed successfully.

(IP_switch_A_1) #
----
. 次回リブート時にスイッチをバックアップパーティションからブートするように設定します。
+
「ブート・システム・バックアップ」を参照してください

+
[listing]
----
(IP_switch_A_1) #boot system backup
Activating image backup ..

(IP_switch_A_1) #
----
. 次回ブート時に新しいブートイメージがアクティブになることを確認します。
+
'How bootvar'

+
[listing]
----
(IP_switch_A_1) #show bootvar

Image Descriptions

 active :
 backup :


 Images currently available on Flash

 ----  -----------  --------  ---------------  ------------
 unit       active    backup   current-active   next-active
 ----  -----------  --------  ---------------  ------------

	1       3.4.4.2    3.4.4.6      3.4.4.2        3.4.4.6

(IP_switch_A_1) #
----
. 設定を保存します。
+
「メモリの書き込み」

+
[listing]
----
(IP_switch_A_1) #write memory

This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y


Configuration Saved!

(IP_switch_A_1) #
----
. スイッチをリブートします。
+
「再ロード」

+
[listing]
----
(IP_switch_A_1) #reload

Are you sure you would like to reset the system? (y/n) y
----
. スイッチがリブートするまで待ちます。
+

NOTE: まれに、スイッチが起動しないことがあります。に従ってください  to upgrade EFOS using the ONIE OS installation 新しいイメージをインストールします。

. スイッチを EFOS 3.x.x から EFOS 3.x.x に変更した場合、またはその逆の場合は、次の 2 つの手順に従って正しい設定（ RCF ）を適用します。
+
..  the Broadcom IP switch to factory defaults
..  and installing the Broadcom RCF files


. MetroCluster IP 構成の残りの 3 つの IP スイッチについて、上記の手順を繰り返します。




=== ONIE OS インストールを使用して EFOS をアップグレードする手順

一方の EFOS バージョンが FIPS に準拠していて、もう一方の EFOS バージョンが FIPS に準拠していない場合は、次の手順を実行できます。次の手順は、スイッチがブートに失敗した場合に、 ONIE から FIPS 非準拠または FIPS 準拠の EFOS 3.x.x イメージをインストールするために使用できます。

.手順
. スイッチを ONIE インストールモードで起動します。
+
起動中に、次の画面が表示されたら ONIE を選択します。

+
[listing]
----
 +--------------------------------------------------------------------+
 |EFOS                                                                |
 |*ONIE                                                               |
 |                                                                    |
 |                                                                    |
 |                                                                    |
 |                                                                    |
 |                                                                    |
 |                                                                    |
 |                                                                    |
 |                                                                    |
 |                                                                    |
 |                                                                    |
 +--------------------------------------------------------------------+

----
+
「 ONIE 」を選択すると、スイッチがロードされ、次の選択肢が表示されます。

+
[listing]
----
 +--------------------------------------------------------------------+
 |*ONIE: Install OS                                                   |
 | ONIE: Rescue                                                       |
 | ONIE: Uninstall OS                                                 |
 | ONIE: Update ONIE                                                  |
 | ONIE: Embed ONIE                                                   |
 | DIAG: Diagnostic Mode                                              |
 | DIAG: Burn-In Mode                                                 |
 |                                                                    |
 |                                                                    |
 |                                                                    |
 |                                                                    |
 |                                                                    |
 +--------------------------------------------------------------------+

----
+
スイッチが ONIE インストールモードで起動します。

. ONIE の検出を停止し、イーサネットインターフェイスを設定します
+
次のメッセージが表示されたら、 <ENTER> を押して ONIE コンソールを起動します。

+
[listing]
----
 Please press Enter to activate this console. Info: eth0:  Checking link... up.
 ONIE:/ #
----
+

NOTE: ONIE の検出は続行され、メッセージがコンソールに出力されます。

+
[listing]
----
Stop the ONIE discovery
ONIE:/ # onie-discovery-stop
discover: installer mode detected.
Stopping: discover... done.
ONIE:/ #
----
. イーサネットインターフェイスを設定し、「 ifconfig eth0 <ipAddress> netmask <netmask> up 」および「 route add default gw <gatewayAddress> 」を使用してルートを追加します
+
[listing]
----
ONIE:/ # ifconfig eth0 10.10.10.10 netmask 255.255.255.0 up
ONIE:/ # route add default gw 10.10.10.1
----
. ONIE インストールファイルをホストしているサーバにアクセスできることを確認します。
+
[listing]
----
ONIE:/ # ping 50.50.50.50
PING 50.50.50.50 (50.50.50.50): 56 data bytes
64 bytes from 50.50.50.50: seq=0 ttl=255 time=0.429 ms
64 bytes from 50.50.50.50: seq=1 ttl=255 time=0.595 ms
64 bytes from 50.50.50.50: seq=2 ttl=255 time=0.369 ms
^C
--- 50.50.50.50 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.369/0.464/0.595 ms
ONIE:/ #
----
. 新しいスイッチソフトウェアをインストールします
+
[listing]
----

ONIE:/ # onie-nos-install http:// 50.50.50.50/Software/onie-installer-x86_64
discover: installer mode detected.
Stopping: discover... done.
Info: Fetching http:// 50.50.50.50/Software/onie-installer-3.7.0.4 ...
Connecting to 50.50.50.50 (50.50.50.50:80)
installer            100% |*******************************| 48841k  0:00:00 ETA
ONIE: Executing installer: http:// 50.50.50.50/Software/onie-installer-3.7.0.4
Verifying image checksum ... OK.
Preparing image archive ... OK.
----
+
ソフトウェアがスイッチをインストールし、リブートします。スイッチを通常どおりにリブートして新しい EFOS バージョンにします。

. 新しいスイッチソフトウェアがインストールされていることを確認します
+
*'How bootvar'*

+
[listing]
----

(Routing) #show bootvar
Image Descriptions
active :
backup :
Images currently available on Flash
---- 	----------- -------- --------------- ------------
unit 	active 	   backup   current-active  next-active
---- 	----------- -------- --------------- ------------
1 	3.7.0.4     3.7.0.4  3.7.0.4         3.7.0.4
(Routing) #
----
. インストールを完了します
+
設定を適用せずにスイッチがリブートし、工場出荷時のデフォルトにリセットされます。2 つの手順に従ってスイッチの基本設定を行い、次の 2 つのドキュメントに記載されているように RCF ファイルを適用します。

+
.. スイッチの基本設定を行います。手順 4 以降を実行します。  the Broadcom IP switch to factory defaults
.. の説明に従って、 RCF ファイルを作成して適用します  and installing the Broadcom RCF files






== Broadcom の RCF ファイルのダウンロードとインストール

MetroCluster IP 構成の各スイッチにスイッチの RCF ファイルをダウンロードしてインストールする必要があります。

この作業には、 FTP 、 TFTP 、 SFTP 、 SCP などのファイル転送ソフトウェアが必要です。 ファイルをスイッチにコピーします。

この手順は、 MetroCluster IP 構成の各 IP スイッチで実行する必要があります。

RCF ファイルは 4 つあり、それぞれが MetroCluster IP 構成の 4 つの各スイッチに対応しています。使用するスイッチのモデルに対応した正しい RCF ファイルを使用する必要があります。

|===


| スイッチ | RCF ファイル 


 a| 
IP_switch_A_1
 a| 
v1.32_Switch-A1.txt



 a| 
IP_switch_a_2
 a| 
v1.32_Switch-A2.txt



 a| 
IP_switch_B_1
 a| 
v1.32_Switch-B1.txt



 a| 
IP_switch_B_2
 a| 
v1.32_Switch-B2.txt

|===

NOTE: EFOS バージョン 3.4.4.6 以降の 3.4.x.x の RCF ファイルリリースと EFOS バージョン 3.7.0.4 は異なります。スイッチが実行されている EFOS バージョンの正しい RCF ファイルを作成したことを確認する必要があります。

|===


| EFOS バージョン | RCF ファイルのバージョン 


| 3.4.x.x | V1.3 倍、 V1.4 倍 


| 3.7.x.x | v2.x 
|===
.手順
. MetroCluster IP 用の Broadcom RCF ファイルを生成します。
+
.. をダウンロードします https://mysupport.netapp.com/site/tools/tool-eula/rcffilegenerator["MetroCluster IP 用の RcfFileGenerator"]
.. RcfFileGenerator for MetroCluster IPを使用して、設定用のRCFファイルを生成します。
+

NOTE: ダウンロード後にRCFファイルを変更することはできません。



. RCF ファイルをスイッチにコピーします。
+
.. RCFファイルを最初のスイッチにコピーします。'copy sftp://user@ftp-server-ip-address/RcfFiles/switch-specific -RCF / BES-53248_v1.32_Switch-A1.txt nvram：script BES-53248 v1.32_Switch-A1.SCR
+
この例では、「 BES-53248_v1.32_Switch-A1.txt 」 RCF ファイルを、 SFTP サーバの「 0.50.50.50 」からローカルブートフラッシュにコピーしています。使用する TFTP / SFTP サーバの IP アドレスを指定し、インストールする必要がある RCF ファイルのファイル名を指定する必要があります。

+
[listing]
----
(IP_switch_A_1) #copy sftp://user@50.50.50.50/RcfFiles/BES-53248_v1.32_Switch-A1.txt nvram:script BES-53248_v1.32_Switch-A1.scr

Remote Password:*************

Mode........................................... SFTP
Set Server IP.................................. 50.50.50.50
Path........................................... /RcfFiles/
Filename....................................... BES-53248_v1.32_Switch-A1.txt
Data Type...................................... Config Script
Destination Filename........................... BES-53248_v1.32_Switch-A1.scr

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) y

File transfer in progress. Management access will be blocked for the duration of the transfer. Please wait...
File transfer operation completed successfully.


Validating configuration script...

config

set clibanner "***************************************************************************

* NetApp Reference Configuration File (RCF)

*

* Switch    : BES-53248


...
The downloaded RCF is validated. Some output is being logged here.
...


Configuration script validated.
File transfer operation completed successfully.

(IP_switch_A_1) #
----
.. RCF ファイルがスクリプトとして保存されたことを確認します。
+
「原稿リスト」

+
[listing]
----
(IP_switch_A_1) #script list

Configuration Script Name        Size(Bytes)  Date of Modification
-------------------------------  -----------  --------------------
BES-53248_v1.32_Switch-A1.scr             852   2019 01 29 18:41:25

1 configuration script(s) found.
2046 Kbytes free.
(IP_switch_A_1) #
----
.. RCF スクリプトを適用します。
+
「 script apply BES-53248 v1.32_Switch-A1.scr 」を参照してください

+
[listing]
----
(IP_switch_A_1) #script apply BES-53248_v1.32_Switch-A1.scr

Are you sure you want to apply the configuration script? (y/n) y


config

set clibanner "********************************************************************************

* NetApp Reference Configuration File (RCF)

*

* Switch    : BES-53248

...
The downloaded RCF is validated. Some output is being logged here.
...

Configuration script 'BES-53248_v1.32_Switch-A1.scr' applied.

(IP_switch_A_1) #
----
.. 設定を保存します。
+
「メモリの書き込み」

+
[listing]
----
(IP_switch_A_1) #write memory

This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y


Configuration Saved!

(IP_switch_A_1) #
----
.. スイッチをリブートします。
+
「再ロード」

+
[listing]
----
(IP_switch_A_1) #reload

Are you sure you would like to reset the system? (y/n) y
----
.. 残りの 3 つのスイッチのそれぞれについて、同じ手順を繰り返します。それぞれのスイッチに対応する RCF ファイルをコピーするように注意してください。


. スイッチをリロードします。
+
「再ロード」

+
[listing]
----
IP_switch_A_1# reload
----
. MetroCluster IP 構成の他の 3 つのスイッチについて、上記の手順を繰り返します。

