---
permalink: install-ip/task_remove_unconfigure_mediator.html 
sidebar: sidebar 
keywords: ontap, mediator, service, assist, remove, unconfigure, requirements, mediator requirements 
summary: MetroCluster IP構成からONTAP メディエーターサービスを削除できます。 
---
= MetroCluster IP設定からONTAP メディエーターサービスの設定を解除します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP メディエーターサービスの設定をMetroCluster IP設定から解除できます。

.作業を開始する前に
両方のMetroCluster サイトからアクセスできるネットワークの場所にONTAP メディエーターがインストールされて設定されている必要があります。

.手順
. 次のコマンドを使用して、ONTAP メディエーターサービスの設定を解除します。
+
MetroCluster 構成設定のメディエーターが削除されました

+
ONTAPメディエーターの管理者ユーザアカウントのユーザ名とパスワードの入力を求められます。

+

NOTE: ONTAPメディエーターが停止している場合は、 `metrocluster configuration-settings mediator remove` ONTAPメディエーターの管理者ユーザアカウントのユーザ名とパスワードの入力を求めるプロンプトが引き続き表示され、ONTAPメディエーターサービスがMetroCluster構成から削除されます。

+
.. 次のコマンドを使用して、破損ディスクがないかどうかを確認します。
+
「disk show -broken」

+
* 例 *

+
....
There are no entries matching your query.
....


. 両方のクラスタで次のコマンドを実行して、ONTAP メディエーターサービスがMetroCluster 構成から削除されたことを確認します。
+
.. `metrocluster configuration-settings mediator show`
+
* 例 *

+
[listing]
----
This table is currently empty.
----
.. 「 storage iscsi-initiator show -label mediator 」という名前のストレージがあります
+
* 例 *

+
[listing]
----
There are no entries matching your query.
----



