---
permalink: install-ip/task_switch_config_nvidia.html 
sidebar: sidebar 
keywords: ip, switch, connection, configuring, configure, NVIDIA, factory defaults, MSN2100, SN2100 
summary: クラスタインターコネクトおよびバックエンドMetroCluster のIP接続用にNVIDIA IPスイッチを設定する必要があります。 
---
= NVIDIA IP SN2100スイッチを設定します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クラスタインターコネクトおよびバックエンドMetroCluster IP接続用にNVIDIA SN2100 IPスイッチを設定する必要があります。



== [[Reset-The switch]] NVIDIA IP SN2100スイッチを工場出荷時のデフォルトにリセットします

スイッチを工場出荷時のデフォルト設定にリセットするには、次のいずれかの方法を選択します。

* <<RCF-file-option,RCFファイルオプションを使用してスイッチをリセットします>>
* <<Cumulus-install-option,Cumulusインストールオプションを使用して、スイッチをリセットします>>




=== [RCFファイルオプション]] RCFファイルオプションを使用してスイッチをリセットします

新しいRCF設定をインストールする前に、NVIDIAスイッチ設定をリバートする必要があります。

.このタスクについて
スイッチをデフォルト設定に戻すには、「restoreDefaults」オプションを指定してRCFファイルを実行します。このオプションを選択すると、元のバックアップファイルが元の場所にコピーされ、スイッチがリブートされます。リブート後、スイッチを設定するためにRCFファイルを最初に実行したときに使用していた元の設定がスイッチにオンラインになります。

次の設定の詳細はリセットされません。

* ユーザおよびクレデンシャルの設定
* 管理ネットワークポートeth0の設定



NOTE: RCFファイルの適用中に発生するその他の設定変更は、すべて元の設定にリバートされます。

.作業を開始する前に
* に従ってスイッチを設定する必要があります <<Download-and-install,NVIDIAのRCFファイルをダウンロードしてインストールします>>。この方法で設定していない場合やRCFファイルを実行する前に追加機能を設定している場合は、この手順 を使用できません。
* この手順は、 MetroCluster IP 構成の各 IP スイッチで実行する必要があります。
* シリアルコンソール接続を使用してスイッチに接続する必要があります。
* このタスクでは、管理ネットワークの設定をリセットします。


.手順
. 同じバージョンまたは互換性のあるRCFファイルを使用してRCF設定が正常に適用され、バックアップファイルが存在することを確認します。
+

NOTE: 出力には、バックアップファイル、保持されたファイル、またはその両方が表示されます。バックアップファイルまたは保存されたファイルが出力に表示されない場合は、この手順 を使用できません。

+
[listing, subs="+quotes"]
----
cumulus@IP_switch_A_1:mgmt:~$ sudo python3 SN2100_v2.0.0_IP_switch_A_1.py
[sudo] password for cumulus:
>>> Opened RcfApplyLog
*A RCF configuration has been successfully applied.*
  *Backup files exist.*
    *Preserved files exist.*
    Listing completion of the steps:
        Success: Step: 1: Performing Backup and Restore
        Success: Step: 2: updating MOTD file
        Success: Step: 3: Disabling apt-get
        Success: Step: 4: Disabling cdp
        Success: Step: 5: Adding lldp config
        Success: Step: 6: Creating interfaces
        Success: Step: 7: Configuring switch basic settings: Hostname, SNMP
        Success: Step: 8: Configuring switch basic settings: bandwidth allocation
        Success: Step: 9: Configuring switch basic settings: ecn
        Success: Step: 10: Configuring switch basic settings: cos and dscp remark
        Success: Step: 11: Configuring switch basic settings: generic egress cos mappings
        Success: Step: 12: Configuring switch basic settings: traffic classification
        Success: Step: 13: Configuring LAG load balancing policies
        Success: Step: 14: Configuring the VLAN bridge
        Success: Step: 15: Configuring local cluster ISL ports
        Success: Step: 16: Configuring MetroCluster ISL ports
        Success: Step: 17: Configuring ports for MetroCluster-1, local cluster and MetroCluster interfaces
        Success: Step: 18: Configuring ports for MetroCluster-2, local cluster and MetroCluster interfaces
        Success: Step: 19: Configuring ports for MetroCluster-3, local cluster and MetroCluster interfaces
        Success: Step: 20: Configuring L2FC for MetroCluster interfaces
        Success: Step: 21: Configuring the interface to UP
        Success: Step: 22: Final commit
        Success: Step: 23: Final reboot of the switch
    Exiting ...
<<< Closing RcfApplyLog
cumulus@IP_switch_A_1:mgmt:~$

----
. デフォルトに戻すオプションを指定してRCFファイルを実行します。'restoreDefaults'
+
[listing]
----
cumulus@IP_switch_A_1:mgmt:~$ sudo python3 SN2100_v2.0.0_IP_switch_A_2.py restoreDefaults
[sudo] password for cumulus:
>>> Opened RcfApplyLog
Can restore from backup directory. Continuing.
This will reboot the switch !!!
Enter yes or no: yes
----
. プロンプトに「yes」と入力します。スイッチが元の設定に戻り、リブートします。
. スイッチがリブートするまで待ちます。
+
スイッチがリセットされ、RCFファイルを適用する前の既存の管理ネットワーク設定や現在のクレデンシャルなどの初期設定が保持されます。リブート後、同じバージョンまたは別のバージョンのRCFファイルを使用して新しい設定を適用できます。





=== [[Cumulus-install-option]] Cumulusソフトウェアのダウンロードとインストール

.このタスクについて
Cumulus画像を適用してスイッチを完全にリセットするには、次の手順を実行します。

.作業を開始する前に
* シリアルコンソール接続を使用してスイッチに接続する必要があります。
* Cumulusスイッチソフトウェアイメージには、HTTP経由でアクセスできます。
+

NOTE: Cumulus Linuxのインストールの詳細については、を参照してください。 link:https://docs.netapp.com/us-en/ontap-systems-switches/switch-nvidia-sn2100/configure-overview-sn2100-cluster.html#initial-configuration-overview["NVIDIA SN2100スイッチのインストールと設定の概要"^]

* コマンドへの「sudo」アクセス用のrootパスワードが必要です。


.手順
. Cumulusコンソールから、スイッチ・ソフトウェアのインストールを「ONIE-install-A-i」コマンドに続けてスイッチ・ソフトウェアへのファイル・パスを指定して、ダウンロードしてキューに入れます。
+
この例では、ファームウェアファイル `cumulus-linux-4.4.3-mlx-amd64.bin` HTTPサーバ「50.50.50.50」からローカルスイッチにコピーされます。

+
[listing]
----
cumulus@IP_switch_A_1:mgmt:~$ sudo onie-install -a -i http://50.50.50.50/switchsoftware/cumulus-linux-4.4.3-mlx-amd64.bin
Fetching installer: http://50.50.50.50/switchsoftware/cumulus-linux-4.4.3-mlx-amd64.bin
Downloading URL: http://50.50.50.50/switchsoftware/cumulus-linux-4.4.3-mlx-amd64.bin
######################################################################### 100.0%
Success: HTTP download complete.
tar: ./sysroot.tar: time stamp 2021-01-30 17:00:58 is 53895092.604407122 s in the future
tar: ./kernel: time stamp 2021-01-30 17:00:58 is 53895092.582826352 s in the future
tar: ./initrd: time stamp 2021-01-30 17:00:58 is 53895092.509682557 s in the future
tar: ./embedded-installer/bootloader/grub: time stamp 2020-12-10 15:25:16 is 49482950.509433937 s in the future
tar: ./embedded-installer/bootloader/init: time stamp 2020-12-10 15:25:16 is 49482950.509336507 s in the future
tar: ./embedded-installer/bootloader/uboot: time stamp 2020-12-10 15:25:16 is 49482950.509213637 s in the future
tar: ./embedded-installer/bootloader: time stamp 2020-12-10 15:25:16 is 49482950.509153787 s in the future
tar: ./embedded-installer/lib/init: time stamp 2020-12-10 15:25:16 is 49482950.509064547 s in the future
tar: ./embedded-installer/lib/logging: time stamp 2020-12-10 15:25:16 is 49482950.508997777 s in the future
tar: ./embedded-installer/lib/platform: time stamp 2020-12-10 15:25:16 is 49482950.508913317 s in the future
tar: ./embedded-installer/lib/utility: time stamp 2020-12-10 15:25:16 is 49482950.508847367 s in the future
tar: ./embedded-installer/lib/check-onie: time stamp 2020-12-10 15:25:16 is 49482950.508761477 s in the future
tar: ./embedded-installer/lib: time stamp 2020-12-10 15:25:47 is 49482981.508710647 s in the future
tar: ./embedded-installer/storage/blk: time stamp 2020-12-10 15:25:16 is 49482950.508631277 s in the future
tar: ./embedded-installer/storage/gpt: time stamp 2020-12-10 15:25:16 is 49482950.508523097 s in the future
tar: ./embedded-installer/storage/init: time stamp 2020-12-10 15:25:16 is 49482950.508437507 s in the future
tar: ./embedded-installer/storage/mbr: time stamp 2020-12-10 15:25:16 is 49482950.508371177 s in the future
tar: ./embedded-installer/storage/mtd: time stamp 2020-12-10 15:25:16 is 49482950.508293856 s in the future
tar: ./embedded-installer/storage: time stamp 2020-12-10 15:25:16 is 49482950.508243666 s in the future
tar: ./embedded-installer/platforms.db: time stamp 2020-12-10 15:25:16 is 49482950.508179456 s in the future
tar: ./embedded-installer/install: time stamp 2020-12-10 15:25:47 is 49482981.508094606 s in the future
tar: ./embedded-installer: time stamp 2020-12-10 15:25:47 is 49482981.508044066 s in the future
tar: ./control: time stamp 2021-01-30 17:00:58 is 53895092.507984316 s in the future
tar: .: time stamp 2021-01-30 17:00:58 is 53895092.507920196 s in the future
Staging installer image...done.
WARNING:
WARNING: Activating staged installer requested.
WARNING: This action will wipe out all system data.
WARNING: Make sure to back up your data.
WARNING:
Are you sure (y/N)? y
Activating staged installer...done.
Reboot required to take effect.
cumulus@IP_switch_A_1:mgmt:~$
----
. イメージのダウンロードおよび確認時に'プロンプトにyと応答してインストールを確認します
. 新しいソフトウェア「sudo reboot」をインストールするには、スイッチを再起動します
+
[listing]
----
cumulus@IP_switch_A_1:mgmt:~$ sudo reboot
----
+

NOTE: スイッチがリブートし、スイッチソフトウェアのインストールが開始されます。この処理にはしばらく時間がかかります。インストールが完了すると、スイッチがリブートし、「log-in」プロンプトが表示されたままになります。

. スイッチの基本設定を行います
+
.. スイッチがブートされ、ログインプロンプトでログインし、パスワードを変更します。
+

NOTE: ユーザ名は「cumulus」で、デフォルトのパスワードは「cumulus」です。



+
[listing]
----
Debian GNU/Linux 10 cumulus ttyS0

cumulus login: cumulus
Password:
You are required to change your password immediately (administrator enforced)
Changing password for cumulus.
Current password:
New password:
Retype new password:
Linux cumulus 4.19.0-cl-1-amd64 #1 SMP Cumulus 4.19.206-1+cl4.4.3u1 (2021-12-18) x86_64

Welcome to NVIDIA Cumulus (R) Linux (R)

For support and online technical documentation, visit
http://www.cumulusnetworks.com/support

The registered trademark Linux (R) is used pursuant to a sublicense from LMI,
the exclusive licensee of Linus Torvalds, owner of the mark on a world-wide
basis.

cumulus@cumulus:mgmt:~$
----
. 管理ネットワークインターフェイスを設定
+
使用するコマンドは、実行しているスイッチファームウェアのバージョンによって異なります。

+

NOTE: 次に、ホスト名をIP_switch_A_1、IPアドレスを10.10.10.10、ネットマスクを255.255.255.0（24）、ゲートウェイアドレスを10.10.10.1に設定する例を示します。

+
[role="tabbed-block"]
====
.クムルス4.4.x
--
次に、Cumulus 4.4.xを実行しているスイッチにホスト名、IPアドレス、ネットマスク、およびゲートウェイを設定する例を示します。

[listing]
----
cumulus@cumulus:mgmt:~$ net add hostname IP_switch_A_1
cumulus@cumulus:mgmt:~$ net add interface eth0 ip address 10.0.10.10/24
cumulus@cumulus:mgmt:~$ net add interface eth0 ip gateway 10.10.10.1
cumulus@cumulus:mgmt:~$ net pending

.
.
.


cumulus@cumulus:mgmt:~$ net commit

.
.
.


net add/del commands since the last "net commit"


User Timestamp Command

cumulus 2021-05-17 22:21:57.437099 net add hostname Switch-A-1
cumulus 2021-05-17 22:21:57.538639 net add interface eth0 ip address 10.10.10.10/24
cumulus 2021-05-17 22:21:57.635729 net add interface eth0 ip gateway 10.10.10.1

cumulus@cumulus:mgmt:~$
----
--
.Cumulus 5.4.x以降
--
次に、Cumulus 5.4.xを実行しているスイッチにホスト名、IPアドレス、ネットマスク、およびゲートウェイを設定する例を示します。以降が必要です。

[listing]
----
cumulus@cumulus:mgmt:~$ nv set system hostname IP_switch_A_1
cumulus@cumulus:mgmt:~$ nv set interface eth0 ip address 10.0.10.10/24 cumulus@cumulus:mgmt:~$ nv set interface eth0 ip gateway 10.10.10.1 cumulus@cumulus:mgmt:~$ nv config apply
cumulus@cumulus:mgmt:~$ nv config save
----
--
====
. sudo rebootコマンドを使用してスイッチをリブートします。
+
[listing]
----
cumulus@cumulus:~$ sudo reboot
----
+
スイッチがリブートしたら、の手順に従って新しい設定を適用できます <<Download-and-install,NVIDIAのRCFファイルをダウンロードしてインストールします>>。





== [[Download-And-install]] NVIDIA RCFファイルをダウンロードしてインストールします

MetroCluster IP 構成の各スイッチにスイッチの RCF ファイルをダウンロードしてインストールする必要があります。

.作業を開始する前に
* コマンドへの「sudo」アクセス用のrootパスワードが必要です。
* スイッチソフトウェアがインストールされ、管理ネットワークが設定されている。
* 方法1または方法2のいずれかを使用して、スイッチを最初に設置する手順を実行しました。
* 初期インストール後に追加の設定を適用しなかった場合。
+

NOTE: RCFファイルを適用する前にスイッチをリセットしたあとに以降の設定を実行する場合は、この手順 を使用できません。



.このタスクについて
この手順は、MetroCluster IP構成（新規の設置）または交換用スイッチ（スイッチの交換）の各IPスイッチで実行する必要があります。

.手順
. MetroCluster IP用のNVIDIA RCFファイルを生成します。
+
.. をダウンロードします https://mysupport.netapp.com/site/tools/tool-eula/rcffilegenerator["MetroCluster IP 用の RcfFileGenerator"^]。
.. RcfFileGenerator for MetroCluster IPを使用して、設定用のRCFファイルを生成します。
.. ホームディレクトリに移動します。「cumulus」として記録されている場合、ファイルパスは「/home/cumulus」です。
+
[listing]
----
cumulus@IP_switch_A_1:mgmt:~$ cd ~
cumulus@IP_switch_A_1:mgmt:~$ pwd
/home/cumulus
cumulus@IP_switch_A_1:mgmt:~$
----
.. このディレクトリにRCFファイルをダウンロードします。
次に、SCPを使用してファイルをダウンロードする例を示します。 `SN2100_v2.0.0_IP_switch_A_1.txt` サーバ「50.50.50.50」からホームディレクトリに保存します。 `SN2100_v2.0.0_IP_switch_A_1.py`：
+
[listing]
----
cumulus@Switch-A-1:mgmt:~$ scp username@50.50.50.50:/RcfFiles/SN2100_v2.0.0_IP_switch_A_1.txt ./SN2100_v2.0.0_IP_switch-A1.py
The authenticity of host '50.50.50.50 (50.50.50.50)' can't be established.
RSA key fingerprint is SHA256:B5gBtOmNZvdKiY+dPhh8=ZK9DaKG7g6sv+2gFlGVF8E.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '50.50.50.50' (RSA) to the list of known hosts.
***********************************************************************
Banner of the SCP server
***********************************************************************
username@50.50.50.50's password:
SN2100_v2.0.0_IP_switch_A1.txt 100% 55KB 1.4MB/s 00:00
cumulus@IP_switch_A_1:mgmt:~$
----


. RCFファイルを実行します。RCFファイルでは、1つ以上の手順を適用するためのオプションが必要です。テクニカルサポートから指示がないかぎり、コマンドラインオプションを指定せずにRCFファイルを実行します。RCFファイルのさまざまな手順の完了ステータスを確認するには、オプション「-1」または「all」を使用してすべての（保留中の）手順を適用します。
+
[listing]
----

cumulus@IP_switch_A_1:mgmt:~$ sudo python3 SN2100_v2.0.0_IP_switch_A_1.py
all
[sudo] password for cumulus:
The switch will be rebooted after the step(s) have been run.
Enter yes or no: yes



... the steps will apply - this is generating a lot of output ...



Running Step 24: Final reboot of the switch



... The switch will reboot if all steps applied successfully ...
----
. 構成でDACケーブルを使用する場合は、スイッチポートでDACオプションを有効にします。
+
[listing]
----
cumulus@IP_switch_A_1:mgmt:~$ sudo python3 SN2100_v2.0.0-X10_Switch-A1.py runCmd <switchport> DacOption [enable | disable]
----
+
次に、ポートのDACオプションをイネーブルにする例を示します。 `swp7`：

+
[listing]
----
cumulus@IP_switch_A_1:mgmt:~$ sudo python3 SN2100_v2.00_Switch-A1.py runCmd swp7 DacOption enable
    Running cumulus version  : 5.4.0
    Running RCF file version : v2.00
    Running command: Enabling the DacOption for port swp7
    runCmd: 'nv set interface swp7 link fast-linkup on', ret: 0
    runCmd: committed, ret: 0
    Completion: SUCCESS
cumulus@IP_switch_A_1:mgmt:~$
----
. スイッチポートでDACオプションを有効にしたら、スイッチをリブートします。
+
`sudo reboot`

+

NOTE: 複数のスイッチポートにDACオプションを設定する場合は、スイッチをリブートするだけで済みます。





== 未使用のISLポートとポートチャネルを無効にする

NetAppでは、不要なヘルスアラートを回避するために、未使用のISLポートとポートチャネルを無効にすることを推奨します

. RCFファイルのバナーを使用して、未使用のISLポートとポートチャネルを特定します。
+

NOTE: ポートがブレークアウトモードの場合は、コマンドで指定するポート名がRCFバナーに表示される名前と異なることがあります。RCFケーブル接続ファイルを使用してポート名を検索することもできます。

+
`net show interface`

. RCFファイルを使用して、未使用のISLポートとポートチャネルを無効にします。
+
[listing]
----
cumulus@mcc1-integrity-a1:mgmt:~$ sudo python3 SN2100_v2.0_IP_Switch-A1.py runCmd
[sudo] password for cumulus:
    Running cumulus version  : 5.4.0
    Running RCF file version : v2.0
Help for runCmd:
    To run a command execute the RCF script as follows:
    sudo python3 <script> runCmd <option-1> <option-2> <option-x>
    Depending on the command more or less options are required. Example to 'up' port 'swp1'
        sudo python3 SN2100_v2.0_IP_Switch-A1.py runCmd swp1 up
    Available commands:
        UP / DOWN the switchport
            sudo python3 SN2100_v2.0_IP_Switch-A1.py runCmd <switchport> state <up | down>
        Set the switch port speed
            sudo python3 SN2100_v2.0_Switch-A1.py runCmd <switchport> speed <10 | 25 | 40 | 100 | AN>
        Set the fec mode on the switch port
            sudo python3 SN2100_v2.0_Switch-A1.py runCmd <switchport> fec <default | auto | rs | baser | off>
        Set the [localISL | remoteISL] to 'UP' or 'DOWN' state
            sudo python3 SN2100_v2.0_Switch-A1.py runCmd [localISL | remoteISL] state [up | down]
        Set the option on the port to support DAC cables. This option does not support port ranges.
            You must reload the switch after changing this option for the required ports. This will disrupt traffic.
            This setting requires Cumulus 5.4 or a later 5.x release.
            sudo python3 SN2100_v2.0_Switch-A1.py runCmd <switchport> DacOption [enable | disable]
cumulus@mcc1-integrity-a1:mgmt:~$
----
+
次の例では、ポート「swp14」を無効にします。

+
`sudo python3 SN2100_v2.0_Switch-A1.py runCmd swp14 state down`

+
特定された未使用のポートまたはポートチャネルごとに、この手順を繰り返します。


