---
permalink: install-ip/task_cable_other_connections.html 
sidebar: sidebar 
keywords: cabling, cable, component, peering, management, network, hardware, component, switch, cluster, connection, management, data, configuring, configure 
summary: クラスタピアリング、管理、データ接続に使用するコントローラモジュールのポートをケーブル接続する必要があります。 
---
= MetroCluster IP構成でONTAPコントローラモジュールポートをケーブル接続する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クラスタピアリング、管理、データ接続に使用するコントローラモジュールのポートをケーブル接続する必要があります。

このタスクは、 MetroCluster 構成の各コントローラモジュールで実行する必要があります。

クラスタピアリングには、各コントローラモジュールの少なくとも 2 つのポートを使用します。

ポートおよびネットワーク接続の推奨される最小帯域幅は 1GbE です。

. クラスタピアリングに使用する少なくとも 2 つのポートを特定してケーブル接続し、そのポートがパートナークラスタとネットワーク接続されていることを確認します。
+
クラスタピアリングには、専用のポートとデータポートのどちらも使用できます。専用のポートを使用すると、クラスタピアリングトラフィックのスループットが向上します。

+
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-clus-peer/home.html["クラスタと SVM のピアリングの簡単な設定"]

. コントローラの管理ポートとデータポートを、ローカルサイトの管理ネットワークとデータネットワークにケーブル接続します。
+
使用しているプラットフォームに対応したインストール手順をで使用します https://docs.netapp.com/us-en/ontap-systems/["ONTAPハードウェアシステムのドキュメント"^]。

+

NOTE: MetroCluster IPシステムには、専用のハイアベイラビリティ（HA）ポートはありません。プラットフォームに応じて、HAトラフィックはMetroClusterインターフェイス、ローカルクラスタインターフェイス、または共有クラスタ/ MetroClusterインターフェイスを使用して処理されます。ONTAPハードウェアシステムのドキュメント_を使用してプラットフォームを設置する場合は、手順に従ってクラスタポートとHAポートをケーブル接続しないでください。


