---
permalink: install-ip/task_rack_hw_components.html 
sidebar: sidebar 
keywords: metrocluster ip, rack hardware, components, racking 
summary: 納入された機器がキャビネットに設置されていない場合は、コンポーネントをラックに配置する必要があります。 
---
= ラックにハードウェアコンポーネントを配置
:icons: font
:imagesdir: ../media/


[role="lead"]
納入された機器がキャビネットに設置されていない場合は、コンポーネントをラックに配置する必要があります。

このタスクは両方の MetroCluster サイトで実行する必要があります。

.手順
. MetroCluster コンポーネントの配置を計画します。
+
ラックスペースは、コントローラモジュールのプラットフォームモデル、スイッチのタイプ、構成内のディスクシェルフスタック数によって異なります。

. 自身の適切な接地対策を行います


. コントローラモジュールをラックまたはキャビネットに設置します。
+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2842666["AFF A220 / FAS2700 システムの設置とセットアップの手順"^]

+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2870798["AFF A250 システムのインストールとセットアップの手順"^]

+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2469722["AFF A300 システム『 Installation and Setup Instructions 』"^]

+
https://docs.netapp.com/platstor/topic/com.netapp.doc.hw-a320-install-setup/home.html["AFF A320 システム：設置とセットアップ"^]

+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2858854["AFF A400 システムの設置とセットアップの手順を参照してください"^]

+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2873445["AFF A700 システムの設置とセットアップの手順"^]

+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2842668["AFF A800 システムの設置とセットアップの手順"^]

+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2872833["FAS500f システム『 Installation and Setup Instructions 』"^]

+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2316769["FAS8200 システム設置とセットアップの手順"^]

+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2858856["FAS8300 および FAS8700 システム設置とセットアップの手順"^]

+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2874463["FAS9000 システム『 Installation and Setup Instructions 』"^]



. IP スイッチをラックまたはキャビネットに設置します。
. ディスクシェルフを設置し、電源を投入して、シェルフ ID を設定します。
+
** 各ディスクシェルフの電源を再投入する必要があります。
** トラブルシューティングに役立てるため、各 MetroCluster DR グループ内の各 SAS ディスクシェルフには、シェルフ ID を一意にすることを強く推奨します。


+

IMPORTANT: ミラーされていないアグリゲートが含まれるディスクシェルフは、この時点ではケーブル接続しないでください。MetroCluster 構成が完了するまで、ミラーされていないアグリゲート用のシェルフを配置し、「 MetroCluster modify -enable -munSHELVed-aggr-deployment true 」コマンドを使用した後にのみ配置する必要があります。


