---
permalink: install-ip/task_sw_config_configure_mediator.html 
sidebar: sidebar 
keywords: metrocluster ip, ontap, mediator, tiebreaker 
summary: MetroCluster Tiebreaker ソフトウェアまたは ONTAP 9.7 以降の ONTAP メディエーターは、第 3 のサイトにダウンロードしてインストールできます。 
---
= MetroCluster IP構成用にMetroCluster TiebreakerまたはONTAP Mediatorを設定する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
MetroCluster Tiebreaker ソフトウェアまたは ONTAP 9.7 以降の ONTAP メディエーターは、第 3 のサイトにダウンロードしてインストールできます。

.作業を開始する前に
MetroCluster 構成の両方のクラスタにネットワークで接続された Linux ホストが必要です。具体的な要件については、 MetroCluster Tiebreaker または ONTAP メディエーターのドキュメントを参照してください。

既存の Tiebreaker または ONTAP Mediator インスタンスに接続する場合は、Tiebreaker または Mediator のユーザー名、パスワード、および IP アドレスが必要です。

ONTAP メディエーターの新しいインスタンスをインストールする必要がある場合は、指示に従ってソフトウェアをインストールおよび設定します。

link:concept_mediator_requirements.html["計画外の自動スイッチオーバー用に ONTAP Mediator を構成する"]

Tiebreaker ソフトウェアの新しいインスタンスをインストールする必要がある場合は、に従います link:../tiebreaker/concept_overview_of_the_tiebreaker_software.html["ソフトウェアのインストールと設定の手順"]。

.このタスクについて
MetroCluster Tiebreaker ソフトウェアと ONTAP メディエーターの両方を同じ MetroCluster 構成で使用することはできません。

link:../install-ip/concept_considerations_mediator.html["ONTAP メディエーターまたは MetroCluster Tiebreaker を使用する場合の考慮事項"]

.ステップ
. ONTAP Mediator または Tiebreaker ソフトウェアを構成します。
+
** ONTAP Mediator の既存のインスタンスを使用している場合は、ONTAP Mediator を ONTAP に追加します。
+
MetroCluster の構成設定メディエーターの追加メディエーターのアドレス IP-addressof mediator-host`

** Tiebreaker ソフトウェアを使用している場合は、を参照してください link:../tiebreaker/concept_overview_of_the_tiebreaker_software.html["Tiebreaker のドキュメント"]。



