---
permalink: install-ip/task_config_switch_health.html 
sidebar: sidebar 
keywords: ip, switch, connection, configuring, configure, broadcom, snmp, health, monitoring 
summary: ヘルス監視にSNMPv3を使用するようにIPスイッチを設定できます。 
---
= 健全性監視用のMetroCluster IPスイッチの設定
:allow-uri-read: 


[role="lead"]
MetroCluster IP構成では、IPスイッチのヘルスを監視するようにSNMPv3を設定できます。



== 手順1：MetroCluster IPスイッチでSNMPv3ユーザを設定する

次の手順に従って、MetroCluster IPスイッチでSNMPv3ユーザを設定します。


IMPORTANT: コマンドでは、認証プロトコルとプライバシープロトコルの両方を使用する必要があります。プライバシーなしの認証の使用はサポートされていません。

[role="tabbed-block"]
====
.BroadcomIPスイツチ
--
.手順
. 「network-admin」ユーザグループが存在しない場合は、作成します。
+
`(IP_switch_1) (Config)# snmp-server group network-admin v3 auth read "Default"`

. 「network-admin」グループが作成されたことを確認します。
+
`(IP_switch_1) (Config)# show snmp group`

. Broadcom IPスイッチでSNMPv3ユーザを設定します。
+
[listing]
----
(IP_switch_1)# config
(IP_switch_1) (Config)# snmp-server user <user_name> network-admin auth-sha priv-aes128
----
+
プロンプトが表示されたら、認証パスワードを入力します。

+
[listing]
----
#snmp-server user admin1 network-admin auth-sha priv-aes128

Enter Authentication Password:
----


--
.Cisco IPスイッチ
--
.手順
. 次のコマンドを実行して、Cisco IPスイッチでSNMPv3ユーザを設定します。
+
[listing]
----
IP_switch_A_1 # configure terminal
IP_switch_A_1 (config) # snmp-server user <user_name>  auth [md5/sha/sha-256] <auth_password> priv (aes-128) <priv_password>
----
. スイッチにSNMPv3ユーザが設定されていることを確認します。
+
`IP_switch_A_1(config) # show snmp user <user_name>`

+
次の出力例は、ユーザが `admin` SNMPv3用に設定されています。

+
[listing]
----
IP_switch_A_1(config)# show snmp user admin
User                Auth      Priv(enforce) Groups              acl_filter

____                ____      _____________ ______              __________

admin               md5       aes-128(no)   network-admin
----


--
====


== 手順2：ONTAPでSNMPv3ユーザを設定する

次の手順に従って、ONTAPでSNMPv3ユーザを設定します。

. ONTAPでSNMPv3ユーザを設定します。
+
`security login create -user-or-group-name <user_name> -application snmp -authentication-method usm -remote-switch-ipaddress <ip_address>`

. 新しいSNMPv3ユーザを使用してスイッチを監視するようにスイッチヘルスモニタを設定します。
+
`system switch ethernet modify -device <device_id> -snmp-version SNMPv3 -community-or-username <user_name>`

. 新しく作成したSNMPv3ユーザで監視するデバイスのシリアル番号が正しいことを確認します。
+
.. スイッチヘルスモニタのポーリング期間を表示します。
+
`system switch ethernet polling-interval show`

.. ポーリング期間が経過したら、次のコマンドを実行します。
+
`system switch ethernet show-all -instance -device <device_serial_number>`




