---
permalink: install-ip/task_rack_hw_components.html 
sidebar: sidebar 
keywords: metrocluster ip, rack hardware, components, racking 
summary: 納入された機器がキャビネットに設置されていない場合は、コンポーネントをラックに配置する必要があります。 
---
= ラックにハードウェアコンポーネントを配置
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
納入された機器がキャビネットに設置されていない場合は、コンポーネントをラックに配置する必要があります。

.このタスクについて
このタスクは両方の MetroCluster サイトで実行する必要があります。

.手順
. MetroCluster コンポーネントの配置を計画します。
+
ラックスペースは、コントローラモジュールのプラットフォームモデル、スイッチのタイプ、構成内のディスクシェルフスタック数によって異なります。

. 自身の適切な接地対策を行います
. コントローラモジュールをラックまたはキャビネットに設置します。
+
https://["AFF A220 / FAS2700 システムの設置とセットアップの手順"^]

+
https://["AFF A250 システムのインストールとセットアップの手順"^]

+
https://["AFF A300 システム『 Installation and Setup Instructions 』"^]

+
https://["AFF A320 システム：設置とセットアップ"^]

+
https://["AFF A400 システムの設置とセットアップの手順を参照してください"^]

+
https://["AFF A700 システムの設置とセットアップの手順"^]

+
https://["AFF A800 システムの設置とセットアップの手順"^]

+
https://["FAS500f システム『 Installation and Setup Instructions 』"^]

+
https://["FAS8200 システム設置とセットアップの手順"^]

+
https://["FAS8300 および FAS8700 システム設置とセットアップの手順"^]

+
https://["FAS9000 システム『 Installation and Setup Instructions 』"^]



. IP スイッチをラックまたはキャビネットに設置します。
. ディスクシェルフを設置し、電源を投入して、シェルフ ID を設定します。
+
** 各ディスクシェルフの電源を再投入する必要があります。
** トラブルシューティングに役立てるため、各 MetroCluster DR グループ内の各 SAS ディスクシェルフには、シェルフ ID を一意にすることを強く推奨します。


+

IMPORTANT: ミラーされていないアグリゲートが含まれるディスクシェルフは、この時点ではケーブル接続しないでください。MetroCluster 構成が完了するまで、ミラーされていないアグリゲート用のシェルフを配置し、「 MetroCluster modify -enable -munSHELVed-aggr-deployment true 」コマンドを使用した後にのみ配置する必要があります。


