---
permalink: install-ip/using_rcf_generator.html 
sidebar: sidebar 
keywords: cabling, cable, component, link, site, management, network, hardware, component, switch, cluster, connection, management, data, configuring, configure, rcf, file, generator, RcfFileGenerator 
summary: RCF ファイルを正しく生成するためには、ポートテーブル内の情報の使用方法を理解しておく必要があります。 
---
= 複数のMetroCluster IP構成でポートテーブルを使用する方法
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
RCF ファイルを正しく生成するためには、ポートテーブル内の情報の使用方法を理解しておく必要があります。

.作業を開始する前に
表を使用する前に、次の考慮事項を確認してください。

* 次の表は、サイト A で使用するポートを示していますサイト B でも同じケーブル接続が使用されます
* 異なる速度のポート (たとえば、100 Gbps ポートと 40 Gbps ポートの混在) を持つスイッチを構成することはできません。
* MetroClusterポートグループ（MetroCluster 1、MetroCluster 2など）を記録しておいてください。この設定手順の後半で説明するRcfFileGeneratorツールを使用する際に、この情報が必要になります。
* すべてのノードを同じ方法でケーブル接続する必要があります。ノードのケーブル接続に使用できるポートの組み合わせオプションが異なる場合は、すべてのノードで同じポートの組み合わせを使用する必要があります。たとえば、node1のe1aとnode2のe1aを1つのスイッチに接続する必要があります。同様に、両方のノードの2番目のポートを2番目のスイッチに接続する必要があります。
*  https://mysupport.netapp.com/site/tools/tool-eula/rcffilegenerator["MetroCluster IP 用の RcfFileGenerator"^]また、各スイッチのポート単位のケーブル接続の概要についても説明しています。ケーブル接続の概要を使用して、ケーブル接続を確認します。




== 2 つの MetroCluster 構成とスイッチのケーブル接続

複数のMetroCluster構成をスイッチにケーブル接続する場合は、各MetroClusterを適切な表に従ってケーブル接続します。例えば、FAS2750とAFF A700を同じスイッチにケーブル接続する場合、FAS2750は表1の「MetroCluster 1」に従ってケーブル接続し、AFF A700は表2の「MetroCluster 2」または「MetroCluster 3」に従ってケーブル接続します。FAS2750とAFF A700の両方を「MetroCluster 1」として物理的にケーブル接続することはできません。



== 8 ノード MetroCluster 構成のケーブル接続

ONTAP 9.8 以前を実行している MetroCluster 構成でアップグレードを移行する場合、一時的な 8 ノード構成にするには、 2 つ目の 4 ノード DR グループを構成に追加する必要があります。  ONTAP 9.9.1以降では、永続的な8ノードMetroCluster構成がサポートされます。

.このタスクについて
8ノード構成の場合も、上記と同じ方法を使用します。2つ目のMetroClusterの代わりに、追加の4ノードDRグループをケーブル接続します。

たとえば、次のような構成になります。

* Cisco 3132Q-V スイッチ
* MetroCluster 1 ： FAS2750 プラットフォーム
* MetroCluster 2 ： AFF A700 プラットフォーム（これらのプラットフォームは 2 つ目の 4 ノード DR グループとして追加）


.手順
. MetroCluster 1 では、 FAS2750 プラットフォームの表と MetroCluster 1 インターフェイスの行を使用して、 Cisco 3132Q-V スイッチをケーブル接続します。
. MetroCluster 2 （ 2 つ目の DR グループ）の場合は、 AFF A700 プラットフォームの表と MetroCluster 2 インターフェイスの行を使用して、 Cisco 3132Q-V スイッチをケーブル接続します。

