---
permalink: disaster-recovery/task_power_on_mcfc.html 
sidebar: sidebar 
keywords: power, sas, storage, direct, attached, configuration, fabric 
summary: スイッチバックの準備が整ったら、ディザスタサイトで MetroCluster コンポーネントの電源をオンにする必要があります。 
---
= ディザスタサイトの機器の電源投入
:icons: font
:imagesdir: ../media/


[role="lead"]
スイッチバックの準備が整ったら、ディザスタサイトで MetroCluster コンポーネントの電源をオンにする必要があります。また、直接接続型の MetroCluster 構成で SAS ストレージ接続のケーブル接続をやり直し、ファブリック接続型の MetroCluster 構成でスイッチ間以外のリンクポートを有効にする必要があります。

MetroCluster コンポーネントを交換し、交換前とまったく同じ状態にケーブル接続しておく必要があります。

link:../install-fc/index.html["ファブリック接続 MetroCluster のインストールと設定"]

link:../install-stretch/index.html["ストレッチ MetroCluster のインストールと設定"]

この手順の例では、次のことを想定しています。

* サイト A はディザスタサイト
+
** FC_switch_A_1 は交換済み
** FC_switch_A_2 は交換済み


* サイト B はサバイバーサイトです。
+
** FC_switch_B_1 は正常
** FC_switch_B_2 は正常




FC スイッチは、ファブリック接続 MetroCluster 構成にのみ存在します。

.手順
. SAS ケーブルを使用する（ FC スイッチファブリックや FC-to-SAS ブリッジは使用しない）ストレッチ MetroCluster 構成で、両方のサイトのすべてのストレージ（リモートストレージを含む）を接続します。
+
ディザスタサイトのコントローラで、電源をオフのままにするか、 LOADER プロンプトを表示する必要があります。

. サバイバーサイトで、ディスクの自動割り当てを無効にします。
+
「 storage disk option modify -autoassign off * 」を参照してください

+
[listing]
----
cluster_B::> storage disk option modify -autoassign off *
2 entries were modified.
----
. サバイバーサイトで、ディスクの自動割り当てが無効になっていることを確認します。
+
「 storage disk option show 」をクリックします

+
[listing]
----
cluster_B::> storage disk option show
Node     BKg. FW. Upd.  Auto Copy   Auto Assign  Auto Assign Policy
--------  -------------  -----------  -----------  ------------------
node_B_1       on            on          off             default
node_B_2       on            on          off             default
2 entries were displayed.

 cluster_B::>
----
. ディザスタサイトのディスクシェルフの電源をオンにし、すべてのディスクが実行されていることを確認します。
. ブリッジ接続型またはファブリック接続型の MetroCluster 構成で、ディザスタサイトのすべての FC-to-SAS ブリッジの電源をオンにします。
. 交換したディスクがある場合は、コントローラの電源をオフのままにするか、 LOADER プロンプトを表示します。
. ファブリック接続 MetroCluster 構成で、 FC スイッチの非 ISL ポートを有効にします。
+
[cols="25,75"]
|===
| スイッチベンダー | ポートを有効化する手順 


 a| 
Brocade
 a| 
.. FC-to-SAS ブリッジに接続されているポートを永続的に有効にします :portpersistentenable port-number
+
次の例では、ポート 6 とポート 7 を有効にします。

+
[listing]
----
FC_switch_A_1:admin> portpersistentenable 6
FC_switch_A_1:admin> portpersistentenable 7

FC_switch_A_1:admin>
----
.. HBA および FC-VI アダプタに接続されているポート portpersistentenable port-number を永続的に有効にします
+
次の例では、ポート 6 とポート 7 を有効にします。

+
[listing]
----
FC_switch_A_1:admin> portpersistentenable 1
FC_switch_A_1:admin> portpersistentenable 2
FC_switch_A_1:admin> portpersistentenable 4
FC_switch_A_1:admin> portpersistentenable 5
FC_switch_A_1:admin>
----
+

NOTE: AFF A700 システムと FAS9000 システムでは、 switchcfgpersistentenable コマンドを使用して、 4 つの FC-VI ポートをすべて永続的に有効にする必要があります。

.. サバイバーサイトの 2 つ目の FC スイッチに対して手順 a と b を繰り返します。




 a| 
シスコ
 a| 
.. インターフェイスの構成モードを開始し、 no shut コマンドを使用してポートを有効化します。
+
次の例では、ポート fc1/36 が無効化されます。

+
[listing]
----
FC_switch_A_1# conf t
FC_switch_A_1(config)# interface fc1/36
FC_switch_A_1(config)# no shut
FC_switch_A_1(config-if)# end
FC_switch_A_1# copy running-config startup-config
----
.. スイッチポートが有効になっていることを確認します。「 show interface brief 」
.. FC-to-SAS ブリッジ、 HBA 、および FC-VI アダプタに接続されている他のポートに対して手順 a と b を繰り返します。
.. サバイバーサイトの 2 つ目の FC スイッチに対して手順 a 、 b 、 c を繰り返します。


|===

