---
permalink: disaster-recovery/task_config_switches_mcip.html 
sidebar: sidebar 
keywords: metrocluster, ip, configuration, switchback, operation 
summary: 交換した IP スイッチを設定する必要があります。 
---
= IP スイッチの設定（ MetroCluster IP 構成）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
交換した IP スイッチを設定する必要があります。

.このタスクについて
このタスクは、環境 MetroCluster IP 構成のみで実行します。

両方のスイッチで実行する必要があります。最初のスイッチの設定後に、サバイバーサイトでのストレージアクセスに影響がないことを確認します。


NOTE: サバイバーサイトでのストレージアクセスに影響がある場合は、 2 つ目のスイッチの設定に進まないでください。

.手順
. を参照してください link:../install-ip/concept_considerations_differences.html["MetroCluster IP のインストールと設定： ONTAP MetroCluster 構成の違い"] 交換用スイッチのケーブル接続と設定の手順については、を参照してください。
+
次のセクションの手順を使用できます。

+
** IP スイッチのケーブル接続
** IP スイッチを設定しています


. サバイバーサイトで ISL が無効になっている場合は、 ISL を有効にして、 ISL がオンラインであることを確認します。
+
.. 1 つ目のスイッチで ISL インターフェイスを有効にします。
+
「シャットダウンなし」

+
次の例は、 Broadcom IP スイッチまたは Cisco IP スイッチ用のコマンドを示しています。

+
|===


| スイッチベンダー | コマンド 


 a| 
Broadcom
 a| 
[listing]
----
(IP_Switch_A_1)> enable
(IP_switch_A_1)# configure
(IP_switch_A_1)(Config)# interface 0/13-0/16
(IP_switch_A_1)(Interface 0/13-0/16 )# no shutdown
(IP_switch_A_1)(Interface 0/13-0/16 )# exit
(IP_switch_A_1)(Config)# exit
----


 a| 
シスコ
 a| 
[listing]
----
IP_switch_A_1# conf t
IP_switch_A_1(config)# int eth1/15-eth1/20
IP_switch_A_1(config)# no shutdown
IP_switch_A_1(config)# copy running startup
IP_switch_A_1(config)# show interface brief
----
|===
.. パートナースイッチで ISL インターフェイスを有効にします。
+
「シャットダウンなし」

+
次の例は、 Broadcom IP スイッチまたは Cisco IP スイッチ用のコマンドを示しています。

+
|===


| スイッチベンダー | コマンド 


 a| 
Broadcom
 a| 
[listing]
----
(IP_Switch_A_2)> enable
(IP_switch_A_2)# configure
(IP_switch_A_2)(Config)# interface 0/13-0/16
(IP_switch_A_2)(Interface 0/13-0/16 )# no shutdown
(IP_switch_A_2)(Interface 0/13-0/16 )# exit
(IP_switch_A_2)(Config)# exit
----


 a| 
シスコ
 a| 
[listing]
----
IP_switch_A_2# conf t
IP_switch_A_2(config)# int eth1/15-eth1/20
IP_switch_A_2(config)# no shutdown
IP_switch_A_2(config)# copy running startup
IP_switch_A_2(config)# show interface brief
----
|===
.. インターフェイスが有効になっていることを確認します。
+
「インターフェイスの概要」

+
次の例は、 Cisco スイッチの出力例を示しています。

+
[listing]
----
IP_switch_A_2(config)# show interface brief

--------------------------------------------------------
Port VRF Status IP Address Speed MTU
--------------------------------------------------------
mt0 -- up 10.10.99.10 100 1500
--------------------------------------------------------
Ethernet    VLAN Type Mode    Status Reason Speed   Port
Interface                                           Ch
#
--------------------------------------------------------
.
.
.
Eth1/15    10   eth   access  up     none   40G(D)  --
Eth1/16    10   eth   access  up     none   40G(D)  --
Eth1/17    10   eth   access  down   none   auto(D) --
Eth1/18    10   eth   access  down   none   auto(D) --
Eth1/19    10   eth   access  down   none   auto(D) --
Eth1/20    10   eth   access  down   none   auto(D) --
.
.
.
IP_switch_A_2#
----



