---
permalink: disaster-recovery/task_complete_recovery.html 
sidebar: sidebar 
keywords: object, fabricpool, mirror, co-located, metrocluster, disaster, site, destroy, reestablish, store, reestablish, store, configuration, verify, license, replace, node, perform, switchback, successful, root, aggregates, replacement, health, reconfiguring, reconfigure, ontap, mediator, service, ip, configuration 
summary: FabricPool ミラーのオブジェクトストアの 1 つが MetroCluster ディザスタサイトと同じ場所にあり破損した場合は、そのオブジェクトストアと FabricPool ミラーを再確立する必要があります。 
---
= リカバリを完了しています
:allow-uri-read: 
:icons: font
:imagesdir: ../media/




== FabricPool 構成のオブジェクトストアの再確立

FabricPool ミラーのオブジェクトストアの 1 つが MetroCluster ディザスタサイトと同じ場所にあり破損した場合は、そのオブジェクトストアと FabricPool ミラーを再確立する必要があります。

.このタスクについて
* オブジェクトストアがリモートにある場合に MetroCluster サイトが破損しても、オブジェクトストアを再構築する必要はなく、オブジェクトストアの元の設定とコールドデータの内容は保持されます。
* FabricPool 構成の詳細については、を参照してください link:https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-psmg/home.html["ディスクとアグリゲートの管理"^]。


.ステップ
. の手順「 Replacing a FabricPool mirror on a MetroCluster configuration 」に従います link:https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-psmg/home.html["ディスクとアグリゲートの管理"^]。




== 交換したノードのライセンスを確認しています

障害ノードが標準（ノードロック）ライセンスを必要とする ONTAP 機能を使用していた場合は、交換ノード用の新しいライセンスをインストールする必要があります。標準ライセンスを使用する機能では、クラスタ内の各ノードにその機能用のキーが必要です。

.このタスクについて
ライセンスキーをインストールするまでの間も、標準ライセンスを必要とする機能を交換用ノードで引き続き使用できます。ただし、該当する機能のライセンスがクラスタ内でその障害ノードにしかなかった場合、機能の設定を変更することはできません。また、ライセンスされていない機能をノードで使用するとライセンス契約に違反する可能性があるため、できるだけ早く交換用ノードにライセンスキーをインストールする必要があります。

ライセンスキーは 28 文字の形式です。

ライセンスキーは 90 日間の猶予期間中にインストールする必要があります。この猶予期間を過ぎると、古いライセンスはすべて無効になります。有効なライセンスキーをインストールしたら、 24 時間以内にすべてのキーをインストールする必要があります。


NOTE: サイトのすべてのノード（ 2 ノード MetroCluster 構成の場合は 1 つのノード）を交換した場合は、スイッチバックの前にライセンスキーを交換用ノードにインストールする必要があります。

.手順
. ノードのライセンスを特定します。
+
「 license show 」を参照してください

+
次の例は、システム内のライセンスに関する情報を表示します。

+
[listing]
----
cluster_B::>  license show
         (system license show)

Serial Number: 1-80-00050
Owner: site1-01
Package           Type       Description             Expiration
-------          -------     -------------           -----------
Base             license     Cluster Base License        -
NFS              site        NFS License                 -
CIFS             site        CIFS License                -
iSCSI            site        iSCSI License               -
FCP              site        FCP License                 -
FlexClone        site        FlexClone License           -

6 entries were displayed.
----
. スイッチバック後のノードのライセンスに問題がないことを確認します。
+
「 MetroCluster check license show 」を参照してください

+
次の例は、ノードのライセンスに問題がないことを表示します。

+
[listing]
----
cluster_B::> metrocluster check license show

Cluster           Check                             Result
-------           -------                           -------------
Cluster_B         negotiated-switchover-ready       not-applicable
NFS               switchback-ready                  not-applicable
CIFS              job-schedules                     ok
iSCSI             licenses                          ok
FCP               periodic-check-enabled            ok
----
. 新しいライセンスキーが必要な場合は、ネットアップサポートサイトの「ソフトウェアライセンス」の下の「サポート」セクションで交換用ライセンスキーを入手します。
+

NOTE: 必要な新しいライセンスキーが自動的に生成され、 E メールで送信されます。30日以内にライセンスキーが記載された電子メールを受信できない場合は、Knowledge Baseの記事の_「ライセンスに問題がある場合は、誰に連絡すればよいですか？」_セクションを参照してください link:https://kb.netapp.com/Advice_and_Troubleshooting/Flash_Storage/AFF_Series/Post_Motherboard_Replacement_Process_to_update_Licensing_on_a_AFF_FAS_system["マザーボードの交換後プロセスを実行して、AFF / FASシステムのライセンスを更新"^]

. 各ライセンスキーをインストールします。
+
'system license add - license-code license-key'license-key...+' を選択します

. 必要に応じて、古いライセンスを削除します。
+
.. 使用されていないライセンスがないかどうか
+
「 license clean-up-unused - simulate 」を入力します

.. リストに間違いがなければ、未使用のライセンスを削除します。
+
「 license clean-up -unused 」のようになります







== キー管理をリストアしています

データボリュームが暗号化されている場合は、キー管理をリストアする必要があります。ルートボリュームが暗号化されている場合は、キー管理をリカバリする必要があります。

.手順
. データボリュームが暗号化されている場合は、キー管理設定に対応したコマンドを使用してキーをリストアします。
+
[cols="1,2"]
|===


| 使用するポート | 使用するコマンド 


 a| 
* オンボードキー管理 *
 a| 
「セキュリティキーマネージャオンボード同期」

詳細については、を参照してください https://["オンボードキー管理の暗号化キーのリストア"^]。



 a| 
* 外部キー管理 *
 a| 
'security key-manager key query -node node-name

詳細については、を参照してください https://["外部キー管理の暗号化キーのリストア"^]。

|===
. ルートボリュームが暗号化されている場合は、の手順を使用します link:../transition/task_connect_the_mcc_ip_controller_modules_2n_mcc_transition_supertask.html#recovering-key-management-if-the-root-volume-is-encrypted["ルートボリュームが暗号化されている場合のキー管理のリカバリ"]。




== スイッチバックを実行しています

MetroCluster 構成の修復が完了したら、 MetroCluster のスイッチバック処理を実行できます。MetroCluster のスイッチバック処理を実行すると、構成が通常の動作状態に戻ります。ディザスタサイトにある同期元の Storage Virtual Machine （ SVM ）がアクティブになり、ローカルディスクプールからデータを提供します。

.作業を開始する前に
* ディザスタクラスタからサバイバークラスタへのスイッチオーバーが正常に完了している必要があります。
* データアグリゲートとルートアグリゲートに対して修復が実行されている必要があります。
* サバイバークラスタノードが HA フェイルオーバー状態ではない（各 HA ペアのすべてのノードが稼働中である）必要があります。
* ディザスタサイトのコントローラモジュールが完全にブートしていること、および HA テイクオーバーモードでないことが必要です。
* ルートアグリゲートがミラーされている必要があります。
* スイッチ間リンク（ ISL ）がオンラインになっている必要があります。
* 必要なライセンスがシステムにインストールされている必要があります。


.手順
. すべてのノードの状態が enabled であることを確認します。
+
MetroCluster node show

+
次の例は、ノードが有効な状態であることを表示します。

+
[listing]
----
cluster_B::>  metrocluster node show

DR                        Configuration  DR
Group Cluster Node        State          Mirroring Mode
----- ------- ----------- -------------- --------- --------------------
1     cluster_A
              node_A_1    configured     enabled   heal roots completed
              node_A_2    configured     enabled   heal roots completed
      cluster_B
              node_B_1    configured     enabled   waiting for switchback recovery
              node_B_2    configured     enabled   waiting for switchback recovery
4 entries were displayed.
----
. すべての SVM で再同期が完了したことを確認します。
+
MetroCluster vserver show

. 修復処理で実行される LIF の自動移行が完了していることを確認します。
+
MetroCluster check lif show

. サバイバークラスタ内の任意のノードから MetroCluster switchback コマンドを実行して、スイッチバックを実行します。
. スイッチバック処理の進捗を確認します。
+
「 MetroCluster show 」

+
出力に「 waiting - for-switchback 」と表示されている場合は、スイッチバック処理をまだ実行中です。

+
[listing]
----
cluster_B::> metrocluster show
Cluster                   Entry Name          State
------------------------- ------------------- -----------
 Local: cluster_B         Configuration state configured
                          Mode                switchover
                          AUSO Failure Domain -
Remote: cluster_A         Configuration state configured
                          Mode                waiting-for-switchback
                          AUSO Failure Domain -
----
+
出力に「 normal 」と表示された場合、スイッチバック処理は完了しています。

+
[listing]
----
cluster_B::> metrocluster show
Cluster                   Entry Name          State
------------------------- ------------------- -----------
 Local: cluster_B         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain -
Remote: cluster_A         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain -
----
+
スイッチバックの完了に時間がかかる場合は、 advanced 権限レベルで次のコマンドを使用して、進行中のベースライン転送のステータスを確認できます。

+
「 MetroCluster config-replication resync-status show 」を参照してください

. SnapMirror 構成または SnapVault 構成があれば、再確立します。
+
ONTAP 8.3 では、失われた SnapMirror 構成を MetroCluster スイッチバック処理のあとに手動で再確立する必要があります。ONTAP 9.0 以降では、関係が自動的に再確立されます。





== スイッチバックが成功したことを確認する

スイッチバックの実行後に、すべてのアグリゲートと Storage Virtual Machine （ SVM ）がスイッチバックされてオンラインになっていることを確認します。

.手順
. スイッチオーバーされたデータアグリゲートがスイッチバックされたことを確認します。
+
「 storage aggregate show

+
次の例では、ノード B2 の aggr_b2 がスイッチバックされています。

+
[listing]
----
node_B_1::> storage aggregate show
Aggregate     Size Available Used% State   #Vols  Nodes            RAID Status
--------- -------- --------- ----- ------- ------ ---------------- ------------
...
aggr_b2    227.1GB   227.1GB    0% online       0 node_B_2   raid_dp,
                                                                   mirrored,
                                                                   normal

node_A_1::> aggr show
Aggregate     Size Available Used% State   #Vols  Nodes            RAID Status
--------- -------- --------- ----- ------- ------ ---------------- ------------
...
aggr_b2          -         -     - unknown      - node_A_1
----
+
ディザスタサイトにミラーされていないアグリゲートが含まれていて、ミラーされていないアグリゲートが存在しない場合、 storage aggregate show コマンドの出力に「 unknown 」という状態が表示されることがあります。ミラーされていないアグリゲートの古いエントリを削除する方法については、テクニカルサポートにお問い合わせください。サポート技術情報アーティクルを参照してください link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/MetroCluster/How_to_remove_stale_unmirrored_aggregate_entries_in_a_MetroCluster_following_disaster_where_storage_was_lost["ストレージが失われた場合にMetroCluster でミラーされていない古いアグリゲートエントリを削除する方法"^]

. サバイバークラスタにあるすべての同期先 SVM が休止状態（ Admin State が「 stopped 」と表示されている）であり、ディザスタクラスタにある同期元 SVM が稼働していることを確認します。
+
「 vserver show -subtype sync-source 」のようになります

+
[listing]
----
node_B_1::> vserver show -subtype sync-source
                               Admin      Root                       Name    Name
Vserver     Type    Subtype    State      Volume     Aggregate       Service Mapping
----------- ------- ---------- ---------- ---------- ----------      ------- -------
...
vs1a        data    sync-source
                               running    vs1a_vol   node_B_2        file    file
                                                                     aggr_b2

node_A_1::> vserver show -subtype sync-destination
                               Admin      Root                         Name    Name
Vserver            Type    Subtype    State      Volume     Aggregate  Service Mapping
-----------        ------- ---------- ---------- ---------- ---------- ------- -------
...
cluster_A-vs1a-mc  data    sync-destination
                                      stopped    vs1a_vol   sosb_      file    file
                                                                       aggr_b2
----
+
MetroCluster 構成の同期先アグリゲートの名前には、識別しやすいようにサフィックス「 -mc 」が自動的に付加されます。

. MetroCluster operation show コマンドを使用して、スイッチバック操作が成功したことを確認します。
+
|===


| 出力内容 | 作業 


 a| 
スイッチバック処理の状態が「 successful 」である
 a| 
スイッチバックプロセスは完了しており、システムの処理を続行できます。



 a| 
スイッチバック処理またはスイッチバック継続エージェントの処理が「 partially successful 」である
 a| 
MetroCluster operation show コマンドの出力に記載されている推奨修正を実行します。

|===


.完了後
上記の手順を繰り返して、逆方向へのスイッチバックを実行する必要があります。site_A が site_B のスイッチオーバーを行った場合は、 site_B で site_A のスイッチオーバーを行います



== 交換用ノードのルートアグリゲートをミラーリング

ディスクを交換した場合は、ディザスタサイトで新しいノードのルートアグリゲートをミラーする必要があります。

.手順
. ディザスタサイトで、ミラーリングされていないアグリゲートを特定します。
+
「 storage aggregate show

+
[listing]
----
cluster_A::> storage aggregate show

Aggregate     Size Available Used% State   #Vols  Nodes            RAID Status
--------- -------- --------- ----- ------- ------ ---------------- ------------
node_A_1_aggr0
            1.49TB   74.12GB   95% online       1 node_A_1         raid4,
                                                                   normal
node_A_2_aggr0
            1.49TB   74.12GB   95% online       1 node_A_2         raid4,
                                                                   normal
node_A_1_aggr1
            1.49TB   74.12GB   95% online       1 node_A_1         raid 4, normal
                                                                   mirrored
node_A_2_aggr1
            1.49TB   74.12GB   95% online       1 node_A_2         raid 4, normal
                                                                   mirrored
4 entries were displayed.

cluster_A::>
----
. 1 つのルートアグリゲートをミラーします。
+
「 storage aggregate mirror -aggregate root-aggregate 」のように表示されます

+
次の例は、アグリゲートをミラーするコマンドでディスクを選択し、確認を求めるプロンプトを表示する方法を示しています。

+
[listing]
----
cluster_A::> storage aggregate mirror -aggregate node_A_2_aggr0

Info: Disks would be added to aggregate "node_A_2_aggr0" on node "node_A_2" in
      the following manner:

      Second Plex

        RAID Group rg0, 3 disks (block checksum, raid4)
          Position   Disk                      Type                  Size
          ---------- ------------------------- ---------- ---------------
          parity     2.10.0                    SSD                      -
          data       1.11.19                   SSD                894.0GB
          data       2.10.2                    SSD                894.0GB

      Aggregate capacity available for volume use would be 1.49TB.

Do you want to continue? {y|n}: y

cluster_A::>
----
. ルートアグリゲートのミラーリングが完了したことを確認します。
+
「 storage aggregate show

+
次の例は、ルートアグリゲートがミラーされたことを示しています。

+
[listing]
----
cluster_A::> storage aggregate show

Aggregate     Size Available Used% State   #Vols  Nodes       RAID Status
--------- -------- --------- ----- ------- ------ ----------- ------------
node_A_1_aggr0
            1.49TB   74.12GB   95% online       1 node_A_1    raid4,
                                                              mirrored,
                                                              normal
node_A_2_aggr0
            2.24TB   838.5GB   63% online       1 node_A_2    raid4,
                                                              mirrored,
                                                              normal
node_A_1_aggr1
            1.49TB   74.12GB   95% online       1 node_A_1    raid4,
                                                              mirrored,
                                                              normal
node_A_2_aggr1
            1.49TB   74.12GB   95% online       1 node_A_2    raid4
                                                              mirrored,
                                                              normal
4 entries were displayed.

cluster_A::>
----
. 他のルートアグリゲートについても、上記の手順を繰り返します。
+
ステータスがミラーリングされていないルートアグリゲートはミラーリングする必要があります。





== ONTAP メディエーターサービスの再設定（ MetroCluster IP 構成）

ONTAP メディエーターサービスが設定された MetroCluster IP 構成がある場合は、メディエーターとの関連付けを削除して再設定する必要があります。

.作業を開始する前に
* ONTAP メディエーターサービスの IP アドレスとユーザ名およびパスワードが必要です。
* ONTAP メディエーターサービスが Linux ホストで設定されて動作している必要があります。


.手順
. 既存の ONTAP メディエーター設定を削除します。
+
MetroCluster 構成設定のメディエーターが削除されました

. ONTAP メディエーター設定を再設定します。
+
MetroCluster 構成設定メディエーターの追加メディエーターのアドレスメディエータの IP アドレス





== MetroCluster 構成の健全性の確認

MetroCluster 構成の健全性をチェックして、正常に動作することを確認する必要があります。

.手順
. 各クラスタで MetroCluster が設定されており、通常モードであることを確認します。
+
「 MetroCluster show 」

+
[listing]
----
cluster_A::> metrocluster show
Cluster                   Entry Name          State
------------------------- ------------------- -----------
 Local: cluster_A         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-cluster-disaster
Remote: cluster_B         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-cluster-disaster
----
. 各ノードでミラーリングが有効であることを確認します。
+
MetroCluster node show

+
[listing]
----
cluster_A::> metrocluster node show
DR                           Configuration  DR
Group Cluster Node           State          Mirroring Mode
----- ------- -------------- -------------- --------- --------------------
1     cluster_A
              node_A_1       configured     enabled   normal
      cluster_B
              node_B_1       configured     enabled   normal
2 entries were displayed.
----
. MetroCluster コンポーネントが正常であることを確認します。
+
「 MetroCluster check run 」のようになります

+
[listing]
----
cluster_A::> metrocluster check run

Last Checked On: 10/1/2014 16:03:37

Component           Result
------------------- ---------
nodes               ok
lifs                ok
config-replication  ok
aggregates          ok
4 entries were displayed.

Command completed. Use the `metrocluster check show -instance` command or sub-commands in `metrocluster check` directory for detailed results.
To check if the nodes are ready to do a switchover or switchback operation, run `metrocluster switchover -simulate` or `metrocluster switchback -simulate`, respectively.
----
. ヘルスアラートがないことを確認します。
+
「 system health alert show 」というメッセージが表示されます

. スイッチオーバー処理をシミュレートします。
+
.. いずれかのノードのプロンプトで、 advanced 権限レベルに切り替えます。
+
「 advanced 」の権限が必要です

+
advanced モードで続けるかどうかを尋ねられたら、「 y 」と入力して応答する必要があります。 advanced モードのプロンプトが表示されます（ * > ）。

.. 「 -simulate 」パラメータを指定して、スイッチオーバー操作を実行します。
+
MetroCluster switchover -simulate

.. admin 権限レベルに戻ります。
+
「特権管理者」



. ONTAP メディエーターサービスを使用した MetroCluster IP 構成の場合は、メディエーターサービスが稼働していることを確認します。
+
.. メディエーターディスクがシステムから認識されていることを確認します。
+
「 storage failover mailbox-disk show 」をクリックします

+
次の例は、メールボックスディスクが認識されていることを示しています。

+
[listing]
----
node_A_1::*> storage failover mailbox-disk show
                 Mailbox
Node             Owner     Disk    Name        Disk UUID
-------------     ------   -----   -----        ----------------
sti113-vsim-ucs626g
.
.
     local     0m.i2.3L26      7BBA77C9:AD702D14:831B3E7E:0B0730EE:00000000:00000000:00000000:00000000:00000000:00000000
     local     0m.i2.3L27      928F79AE:631EA9F9:4DCB5DE6:3402AC48:00000000:00000000:00000000:00000000:00000000:00000000
     local     0m.i1.0L60      B7BCDB3C:297A4459:318C2748:181565A3:00000000:00000000:00000000:00000000:00000000:00000000
.
.
.
     partner   0m.i1.0L14      EA71F260:D4DD5F22:E3422387:61D475B2:00000000:00000000:00000000:00000000:00000000:00000000
     partner   0m.i2.3L64      4460F436:AAE5AB9E:D1ED414E:ABF811F7:00000000:00000000:00000000:00000000:00000000:00000000
28 entries were displayed.
----
.. advanced 権限レベルに切り替えます。
+
「 advanced 」の権限が必要です

.. メールボックス LUN がシステムから認識されていることを確認します。
+
「 storage iscsi-initiator show 」のように表示されます

+
メールボックス LUN があることを示す出力が表示されます。

+
[listing]
----

Node    Type       Label      Target Portal     Target Name                                 Admin/Op
----    ----       --------   ---------    --------- --------------------------------       --------
.
.
.
.node_A_1
               mailbox
                     mediator 172.16.254.1    iqn.2012-05.local:mailbox.target.db5f02d6-e3d3    up/up
.
.
.
17 entries were displayed.
----
.. admin 権限レベルに戻ります。
+
「特権管理者」




