---
permalink: disaster-recovery/task_reassign_roots_mcfc.html 
sidebar: sidebar 
keywords: reassign, ownership, nvram, system, id, replaced 
summary: ディザスタサイトのどちらかまたは両方のコントローラモジュールか NVRAM カードを交換した場合は、ルートアグリゲートに属するディスクを交換用コントローラモジュールに再割り当てする必要があります。 
---
= 交換用コントローラモジュールへのルートアグリゲートのディスク所有権の再割り当て（ MetroCluster FC 構成）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ディザスタサイトのどちらかまたは両方のコントローラモジュールか NVRAM カードを交換した場合、システム ID が変わっているため、ルートアグリゲートに属するディスクを交換用コントローラモジュールに再割り当てする必要があります。

.このタスクについて
ノードがスイッチオーバーモードで、修復が完了しているため、このセクションでは、ディザスタサイトのプール 1 のルートアグリゲートを含むディスクのみを再割り当てします。この時点で古いシステム ID に所有されているのはこれらのディスクだけです。

ここでは、 2 ノードと 4 ノードの構成の例を示します。2 ノード構成の場合、各サイトの 2 つ目のノードに関する説明は無視してください。8 ノード構成の場合は、 2 つ目の DR グループの追加のノードを考慮する必要があります。この例で想定している状況は次のとおりです。

* サイト A はディザスタサイト
+
** node_A_1 は交換済み
** Node_a_2 は交換済み
+
4 ノード MetroCluster 構成にのみ存在します。



* サイト B はサバイバーサイトです。
+
** node_B_1 は健全
** node_B_2 は正常
+
4 ノード MetroCluster 構成にのみ存在します。





古いシステムIDと新しいシステムIDについては、を参照して link:task_replace_hardware_and_boot_new_controllers.html["ハードウェアを交換し、新しいコントローラをブート"]ください。

この手順の例では、次のシステム ID を持つコントローラを使用します。

|===


| ノードの数 | ノード | 元のシステム ID | 新しいシステム ID 


.4+| 4.  a| 
node_A_1
 a| 
4068741258
 a| 
1574774970



 a| 
Node_a_2
 a| 
4068741260
 a| 
157477991



 a| 
node_B_1
 a| 
4068741254
 a| 
変更なし



 a| 
node_B_2
 a| 
4068741256
 a| 
変更なし



 a| 
2 つ
 a| 
node_A_1
 a| 
4068741258
 a| 
1574774970

|===
.手順
. メンテナンスモードの交換用ノードで、ルートアグリゲートディスクを再割り当てします。
+
「ディスクの再割り当て - s old-system-ID -d new-system-ID 」

+
[listing]
----
*> disk reassign -s 4068741258 -d 1574774970
----
. ディスクを表示して、ディザスタサイトの pool1 のルートアグリゲートディスクの所有権が、交換用ノードに変わったことを確認します。
+
「ディスクショー」

+
出力に表示されるディスク数は、ルートアグリゲート内のディスク数と、そのうち障害が発生して交換したディスクが何本あるかによって変わってきます。ディスクが交換された場合、プール 0 のディスクは出力に表示されません。

+
ディザスタサイトのプール 1 のルートアグリゲートディスクが交換用ノードに割り当てられます。

+
[listing]
----
*> disk show
Local System ID: 1574774970

  DISK             OWNER                POOL   SERIAL NUMBER   HOME                DR HOME
------------       -------------        -----  -------------   -------------       -------------
sw_A_1:6.126L19    node_A_1(1574774970) Pool0  serial-number   node_A_1(1574774970)
sw_A_1:6.126L3     node_A_1(1574774970) Pool0  serial-number   node_A_1(1574774970)
sw_A_1:6.126L7     node_A_1(1574774970) Pool0  serial-number   node_A_1(1574774970)
sw_B_1:6.126L8     node_A_1(1574774970) Pool1  serial-number   node_A_1(1574774970)
sw_B_1:6.126L24    node_A_1(1574774970) Pool1  serial-number   node_A_1(1574774970)
sw_B_1:6.126L2     node_A_1(1574774970) Pool1  serial-number   node_A_1(1574774970)

*> aggr status
         Aggr State           Status
 node_A_1_root online          raid_dp, aggr
                               mirror degraded
                               64-bit
*>
----
. アグリゲートのステータスを表示します。
+
「 aggr status 」を入力します

+
出力に表示されるディスク数は、ルートアグリゲート内のディスク数と、そのうち障害が発生して交換したディスクが何本あるかによって変わってきます。ディスクが交換された場合、プール 0 のディスクは出力に表示されません。

+
[listing]
----
*> aggr status
          Aggr State           Status
  node_A_1_root online          raid_dp, aggr
                                mirror degraded
                                64-bit
*>
----
. メールボックスディスクの内容を削除します。
+
「マイボックス破壊ローカル」

. アグリゲートがオンラインになっていない場合は、オンラインにします。
+
「 aggr online aggr_name 」のようになります

. ノードを停止して LOADER プロンプトを表示します。
+
「 halt 」


