---
permalink: disaster-recovery/task_boot_new_mcfc.html 
sidebar: sidebar 
keywords: boot, controller, modules, fc 
summary: データアグリゲートとルートアグリゲート両方の修復が完了したら、ディザスタサイトのノードをブートする必要があります。 
---
= 新しいコントローラモジュールのブート（ MetroCluster FC 構成）
:icons: font
:imagesdir: ../media/


[role="lead"]
データアグリゲートとルートアグリゲート両方の修復が完了したら、ディザスタサイトのノードをブートする必要があります。

このタスクは、 LOADER プロンプトが表示されたノードから開始します。

.手順
. ブートメニューを表示します。
+
「 boot_ontap menu

. [step2 、 Step 2] ブートメニューからオプション 6 、 * バックアップ設定からフラッシュを更新 * を選択します。
. 次のプロンプトに「 y 」と入力します。
+
これは ' オール・フラッシュ・ベースの構成をディスクへの最後のバックアップに置き換えます続行してもよろしいですか ?:y`

+
システムが 2 回ブートし、 2 回目に新しい設定がロードされます。

+

NOTE: 使用した交換用コントローラの NVRAM の内容を消去しなかった場合は、パニック状態が発生して「 PANIC ： NVRAM contents are invalid... 」というメッセージが表示されることがあります この場合は、を繰り返します <<step2>> システムをブートして ONTAP プロンプトを表示します。その後、ルートリカバリを実行する必要があります。詳しくはテクニカルサポートにお問い合わせください。

. プレックス 0 でルートアグリゲートをミラーします。
+
.. 3 本の pool0 ディスクを新しいコントローラモジュールに割り当てます。
.. ルートアグリゲートの pool1 プレックスをミラーします。
+
「 aggr mirror root-aggr-name 」のようになります

.. 未割り当てディスクをローカルノードのプール 0 に割り当てます


. MetroCluster 構成を更新します。
+
.. advanced 権限モードに切り替えます。
+
「 advanced 」の権限が必要です

.. 構成を更新します。
+
MetroCluster configure -refresh true

.. admin 権限モードに戻ります。
+
「特権管理者」



. 4 ノード構成の場合は、ディザスタサイトのもう一方のノードで上記の手順を繰り返します。


に進みます link:../disaster-recovery/task_complete_recovery.html["ディザスタリカバリプロセスを完了する"]。
