---
permalink: disaster-recovery/task_reassign_pool1_disastersite_mcip.html 
sidebar: sidebar 
keywords: metrocluster, disaster, site, replacement, controller, module, reassign, ownership 
summary: ディザスタサイトでコントローラモジュールまたは NVRAM カードを交換した場合は、ルートアグリゲートに属するディスクを交換用コントローラモジュールに再割り当てする必要があります。 
---
= ディザスタサイトのプール 1 ディスクのディスク所有権の再割り当て（ MetroCluster IP 構成）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ディザスタサイトのどちらかまたは両方のコントローラモジュールか NVRAM カードを交換した場合、システム ID が変わっているため、ルートアグリゲートに属するディスクを交換用コントローラモジュールに再割り当てする必要があります。

.このタスクについて
ノードがスイッチオーバーモードであるため、このタスクでは、ディザスタサイトのプール 1 のルートアグリゲートを含むディスクのみを再割り当てします。この時点で古いシステム ID に所有されているのはこれらのディスクだけです。

このタスクはディザスタサイトの交換用ノードで実行します。

このタスクはメンテナンスモードで実行します。

この例で想定している状況は次のとおりです。

* サイト A はディザスタサイト
* node_A_1 は交換済み
* Node_a_2 は交換済み
* サイト B はサバイバーサイトです。
* node_B_1 は健全
* node_B_2 は正常


古いシステム ID と新しいシステム ID は、で特定されています link:../disaster-recovery/task_replace_hardware_and_boot_new_controllers.html#determining-the-system-ids-of-the-replacement-controller-modules["交換用コントローラモジュールの新しいシステム ID の確認"]。

この手順の例では、次のシステム ID を持つコントローラを使用します。

|===


| ノード | 元のシステム ID | 新しいシステム ID 


 a| 
node_A_1
 a| 
4068741258
 a| 
1574774970



 a| 
Node_a_2
 a| 
4068741260
 a| 
157477991



 a| 
node_B_1
 a| 
4068741254
 a| 
変更なし



 a| 
node_B_2
 a| 
4068741256
 a| 
変更なし

|===
.手順
. メンテナンスモードの交換用ノードで、システムに ADP と ONTAP のバージョンが設定されているかどうかに応じて、適切なコマンドを使用してルートアグリゲートディスクを再割り当てします。
+
プロンプトが表示されたら、再割り当てを続行できます。

+
|===


| システムでの ADP の使用の有無 | ディスクの再割り当てに使用するコマンド 


 a| 
○（ ONTAP 9.8 ）
 a| 
「ディスクの再割り当て」 - 「 old-system-ID -d new-system-ID -r dr-partner -system-ID 」



 a| 
○（ ONTAP 9.7.x 以前）
 a| 
「ディスクの再割り当て」 - 「 old-system-ID -d new-system-ID -p old-partner -system-ID 」



 a| 
いいえ
 a| 
「ディスクの再割り当て - s old-system-ID -d new-system-ID 」

|===
+
次の例は、 ADP 以外のシステムでのドライブの再割り当てを示しています。

+
[listing]
----
*> disk reassign -s 4068741256 -d 1574774970
Partner node must not be in Takeover mode during disk reassignment from maintenance mode.
Serious problems could result!!
Do not proceed with reassignment if the partner is in takeover mode. Abort reassignment (y/n)? n

After the node becomes operational, you must perform a takeover and giveback of the HA partner node to ensure disk reassignment is successful.
Do you want to continue (y/n)? y
Disk ownership will be updated on all disks previously belonging to Filer with sysid 537037643.
Do you want to continue (y/n)? y
disk reassign parameters: new_home_owner_id 537070473 , new_home_owner_name
Disk 0m.i0.3L14 will be reassigned.
Disk 0m.i0.1L6 will be reassigned.
Disk 0m.i0.1L8 will be reassigned.
Number of disks to be reassigned: 3
----
. メールボックスディスクの内容を破棄します。
+
「マイボックス破壊ローカル」

+
プロンプトが表示されたら、破棄処理を続行できます。

+
次の例は、 mailbox destroy local コマンドの出力を示しています。

+
[listing]
----
*> mailbox destroy local
Destroying mailboxes forces a node to create new empty mailboxes,
which clears any takeover state, removes all knowledge
of out-of-date plexes of mirrored volumes, and will prevent
management services from going online in 2-node cluster
HA configurations.
Are you sure you want to destroy the local mailboxes? y
...............Mailboxes destroyed.
*>
----
. ディスクを交換した場合は、障害が発生したローカルプレックスを削除する必要があります。
+
.. アグリゲートのステータスを表示します。
+
「 aggr status 」を入力します

+
次の例では、プレックス node_A_1_aggr0/plex0 で障害が発生しています。

+
[listing]
----
*> aggr status
Aug 18 15:00:07 [node_B_1:raid.vol.mirror.degraded:ALERT]: Aggregate node_A_1_aggr0 is
   mirrored and one plex has failed. It is no longer protected by mirroring.
Aug 18 15:00:07 [node_B_1:raid.debug:info]: Mirrored aggregate node_A_1_aggr0 has plex0
   clean(-1), online(0)
Aug 18 15:00:07 [node_B_1:raid.debug:info]: Mirrored aggregate node_A_1_aggr0 has plex2
   clean(0), online(1)
Aug 18 15:00:07 [node_B_1:raid.mirror.vote.noRecord1Plex:error]: WARNING: Only one plex
   in aggregate node_A_1_aggr0 is available. Aggregate might contain stale data.
Aug 18 15:00:07 [node_B_1:raid.debug:info]: volobj_mark_sb_recovery_aggrs: tree:
   node_A_1_aggr0 vol_state:1 mcc_dr_opstate: unknown
Aug 18 15:00:07 [node_B_1:raid.fsm.commitStateTransit:debug]: /node_A_1_aggr0 (VOL):
   raid state change UNINITD -> NORMAL
Aug 18 15:00:07 [node_B_1:raid.fsm.commitStateTransit:debug]: /node_A_1_aggr0 (MIRROR):
   raid state change UNINITD -> DEGRADED
Aug 18 15:00:07 [node_B_1:raid.fsm.commitStateTransit:debug]: /node_A_1_aggr0/plex0
   (PLEX): raid state change UNINITD -> FAILED
Aug 18 15:00:07 [node_B_1:raid.fsm.commitStateTransit:debug]: /node_A_1_aggr0/plex2
   (PLEX): raid state change UNINITD -> NORMAL
Aug 18 15:00:07 [node_B_1:raid.fsm.commitStateTransit:debug]: /node_A_1_aggr0/plex2/rg0
   (GROUP): raid state change UNINITD -> NORMAL
Aug 18 15:00:07 [node_B_1:raid.debug:info]: Topology updated for aggregate node_A_1_aggr0
   to plex plex2
*>
----
.. 障害が発生したプレックスを削除します。
+
「 aggr destroy plex-id 」

+
[listing]
----
*> aggr destroy node_A_1_aggr0/plex0
----


. ノードを停止して LOADER プロンプトを表示します。
+
「 halt 」

. ディザスタサイトのもう一方のノードで、上記の手順を繰り返します。

