---
settings:
  name: ONTAP MetroCluster
  platform: ''
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
    langs: ja-jp,us-en,zh-cn
  langs: ja-jp,us-en,zh-cn
sidebar:
  entries:
  - title: MetroCluster
    url: "/index.html"
  - title: リリースノート
    url: "/releasenotes.html"
  - section: install-fc
  - section: install-ip
  - section: install-stretch
  - section: tiebreaker
  - title: MetroCluster のデータ保護とディザスタリカバリを理解する
    entries:
    - title: MetroCluster がデータを保護し、ディザスタリカバリを実現する仕組み
      url: "/manage/concept_understanding_mcc_data_protection_and_disaster_recovery.html"
  - section: manage
  - section: maintain
  - section: transition
  - section: upgrade
  - section: disaster-recovery
  - title: 法的通知
    url: "/reference_legal_notices.html"
homepage:
  tiles:
  - title: はじめに
    links:
    - title: MetroCluster IP をインストールします
      summary: MetroCluster IP 構成をインストール
    - title: ファブリック接続 MetroCluster をインストールします
      summary: ファブリック接続 MetroCluster 構成をインストール
    - title: Stretch MetroCluster をインストールします
      summary: ストレッチ MetroCluster 構成をインストール
    - title: Tiebreaker をインストールします
      summary: MetroCluster Tiebreaker ソフトウェアを 3 番目の場所にインストールして、 MetroCluster サイトを監視します。
      url: "/tiebreaker/concept_overview_of_the_tiebreaker_software.html"
    - title: メディエーターのインストール（ MetroCluster IP のみ）
      summary: MetroCluster メディエーターソフトウェアを 3 つ目の場所にインストールして ONTAP IP サイトを監視します。
      url: "/install-ip/concept_configure_the_ontap_mediator_for_unplanned_automatic_switchover.html"
  - title: メンテナンス
    links:
    - title: FC スイッチ
      summary: MetroCluster FC 構成での FC スイッチの保守と交換
      url: "/maintain/task_upgrade_or_downgrad_the_firmware_on_a_brocade_fc_switch_mcc.html"
    - title: IP スイッチ
      summary: MetroCluster IP 構成で IP スイッチの保守と交換を行います。
      url: "/maintain/task_replace_an_ip_switch.html"
    - title: ATTO ブリッジ
      summary: MetroCluster FC 構成で ATTO FC-to-SAS ブリッジをメンテナンスし、交換します。
      url: "/maintain/concept_using_fibrebridge_7600n_bridges_in_mcc_configurations.html"
    - title: ドライブシェルフ
      summary: ドライブシェルフ MetroCluster FC 構成のホットアドおよび無停止での交換
      url: "/maintain/index.html"
  - title: RCF ファイル
    links:
    - title: MetroCluster RCF ファイル
      summary: MetroCluster スイッチ用の RCF ファイルを生成またはダウンロードします。
      url: https://mysupport.netapp.com/site/products/all/details/metrocluster-rcf/docsandkb-tab
  - title: 詳細はこちら。
    links:
    - title: NetApp MetroCluster 解決策のアーキテクチャと設計 | TR-4705
      summary: MetroCluster FC 解決策を理解する
      url: https://www.netapp.com/pdf.html?item=/media/13480-tr4705.pdf
    - title: MetroCluster IP 解決策のアーキテクチャと設計 | TR-4689
      summary: MetroCluster IP 解決策を理解する。
      url: https://www.netapp.com/pdf.html?item=/media/13481-tr4689.pdf
  - title: アップグレード、拡張、変換
    links:
    - title: ハードウェアのアップグレードと更新
      summary: MetroCluster 構成のコントローラをアップグレードします。
      url: "/upgrade/index.html"
    - title: を展開します
      summary: MetroCluster 構成にコントローラを追加して、 4 ノードまたは 8 ノード構成を作成します。
      url: "/upgrade/index.html"
    - title: MetroCluster FC を MetroCluster IP に変換
      summary: 既存の MetroCluster IP 構成を MetroCluster IP 構成に移行する。
      url: "/transition/index.html"
    - title: MetroCluster IP RCF ファイルをアップグレードします
      summary: MetroCluster IP 構成のスイッチ RCF ファイルをアップグレードします。
      url: "/maintain/task_upgrade_rcf_files_on_mcc_ip_switches.html"
  - title: ATTO ブリッジファームウェア
    links:
    - title: FibreBridge 7600N
      summary: 7600 ブリッジのファームウェアをダウンロードします。
      url: https://mysupport.netapp.com/NOW/cgi-bin/software/?product=Protocol+Bridge&platform=ATTO+FibreBridge+7600N
    - title: FibreBridge 7500N
      summary: 7500 ブリッジのファームウェアをダウンロードします。
      url: https://mysupport.netapp.com/NOW/cgi-bin/software/?product=Protocol+Bridge&platform=ATTO+FibreBridge+7500N
    - title: FibreBridge 6500N
      summary: 6500 ブリッジのファームウェアをダウンロードします。
      url: https://mysupport.netapp.com/NOW/cgi-bin/software/?product=Protocol+Bridge&platform=ATTO+FibreBridge+6500N
  - title: リソースの追加
    links:
    - title: NetApp Config Advisor の略
      summary: 構成とケーブル接続を検証
      url: https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor
    - title: NetApp Hardware Universe の略
      summary: ハードウェアがサポートされていることを確認します。
      url: https://hwu.netapp.com/
    - title: ネットアップのサポートナレッジベース
      summary: サポートに関する質問の回答を検索します。
      url: https://kb.netapp.com/
