---
settings:
  name: ONTAP MetroCluster
  harmony_integration: maestro
  platform: ''
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: ja-jp,us-en,de-de,es-es,fr-fr,it-it,pt-br,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: MetroCluster のドキュメント
    url: "/index.html"
  - section: releasenotes
  - section: install-fc
  - section: install-ip
  - section: install-stretch
  - section: tiebreaker
  - title: MetroCluster のデータ保護とディザスタリカバリを理解する
    entries:
    - title: MetroCluster がデータを保護し、ディザスタリカバリを実現する仕組み
      url: "/manage/concept_understanding_mcc_data_protection_and_disaster_recovery.html"
  - section: manage
  - section: maintain
  - section: transition
  - section: upgrade
  - section: disaster-recovery
  - title: 法的通知
    url: "/legal-notices.html"
product-family:
  name: ONTAP
  repo: ontap-family
