---
permalink: transition/concept_requirements_for_fc_to_ip_transition_mcc.html 
sidebar: sidebar 
keywords: start, transition, process, configuration, requirement, nondisruptive, fc-to-ip 
summary: 移行プロセスを開始する前に、構成が要件を満たしていることを確認する必要があります。 
---
= FC から IP への無停止での移行に関する要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
移行プロセスを開始する前に、構成が要件を満たしていることを確認します。

FCからIPへの移行は、次の要件を満たしている構成であれば、無停止で実行できます。

* 8ノード構成の場合は、すべてのノードでONTAP 9.13.1以降が実行されています。
* 4ノード構成の場合は、すべてのノードでONTAP 9.8以降が実行されています。
* 既存のプラットフォームと新しいプラットフォームの組み合わせが移行対象としてサポートされます。
+
link:concept_choosing_your_transition_procedure_mcc_transition.html["無停止移行でサポートされるプラットフォーム"]

* ご使用の構成では、スイッチクラスタ構成がサポートされます。
+
https://hwu.netapp.com["Hardware Universe"^]



[CAUTION]
====
共有ストレージMetroClusterスイッチを使用している場合は、4ノードのMetroCluster IP構成にのみ移行できます。共有ストレージMetroClusterスイッチを使用した8ノードMetroCluster IP構成への移行はサポートされていません。4ノードMetroCluster IP構成への移行が完了したら、移行link:../upgrade/task_expand_a_four_node_mcc_ip_configuration.html["8ノードMetroCluster IP構成に拡張"]を実行できます。

====
* ご使用の構成はすべての要件を満たしており、次の_ MetroClusterインストールおよび構成手順の説明に従ってケーブル接続されています。
+
link:../install-fc/index.html["ファブリック接続 MetroCluster のインストールと設定"]

+
link:../install-stretch/concept_considerations_differences.html["ストレッチ MetroCluster のインストールと設定"]


