---
permalink: transition/concept_nondisruptively_transitioning_from_a_four_node_mcc_fc_to_a_mcc_ip_configuration.html 
sidebar: sidebar 
keywords: nondisruptive, transition, fc, ip 
summary: ONTAP 9.13.1以降では、既存の8ノードMetroCluster FC構成から新しいMetroCluster IP構成に、ワークロードとデータを無停止で移行できます。 
---
= MetroCluster FC から MetroCluster IP 構成への無停止での移行（ ONTAP 9.8 以降）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
既存のMetroCluster FC構成から新しいMetroCluster IP構成へ、ワークロードやデータを無停止で移行できます。

ONTAP 9.13.1以降では、MetroClusterとドライブシェルフが同じIPスイッチに接続されたMetroCluster IP構成（共有ストレージスイッチ構成）でこの手順がサポートされます。

ONTAP 9.13.1 以降では、既存の 8 ノードMetroCluster FC 構成から新しい 8 ノードMetroCluster IP 構成へのワークロードとデータの無停止移行を実行できます。この手順を使用して、1 つの 4 ノード FC DR グループを移行し、空の FC DR グループを削除してから、2 番目の FC DR グループに対して手順を繰り返します。 

ONTAP 9.8 以降では、既存の 4 ノードMetroCluster FC 構成から新しい 4 ノードMetroCluster IP 構成へのワークロードとデータの無停止移行を実行できます。移行が完了したら、必要に応じて 8 ノードのMetroCluster IP 構成に拡張できます。見るlink:../upgrade/task_expand_a_four_node_mcc_ip_configuration.html["MetroCluster IP設定を展開します"]。

* この手順は無停止で実行されます。
+
MetroCluster 構成では、処理中もデータの提供を継続できます。

* この手順 は、4ノードおよび8ノードのMetroCluster FC構成にのみ適用されます。
+
2 ノード MetroCluster FC 構成の場合は、を参照してください link:concept_choosing_your_transition_procedure_mcc_transition.html["移行する手順を選択します"]。

* この手順 では、1つの4ノードFC DRグループを移行するために必要な手順について説明します。8ノード構成（2つのFC DRグループ）の場合は、FC DRグループごとに手順 全体を繰り返す必要があります。
+

NOTE: この手順の一環として DR グループを追加または削除する場合は、別の DR グループを追加または削除する前に、DR グループの削除または追加が成功したことを確認する必要があります。

* すべての要件を満たし、手順のすべての手順に従う必要があります。


.古いプラットフォームモデルを追加する場合の重要な情報
次のガイダンスは、新しいプラットフォーム モデル ( ONTAP 9.15.1 以降でリリースされたプラットフォーム) を含む既存のMetroCluster構成に古いプラットフォーム モデル ( ONTAP 9.15.1 より前にリリースされたプラットフォーム) を追加する必要がある、まれなシナリオを対象としています。  8 ノードの FC から IP への移行では、最初の FC DR グループをON​​ONTAP 9.15.1 以降で導入されたプラットフォーム モデルに移行し、2 番目の DR グループをON​​ONTAP 9.15.1 より前に導入されたプラットフォームに移行する予定の場合、このガイダンスが適用されます。

既存のMetroCluster構成に、*共有クラスタ/HA ポート* を使用するプラットフォーム ( ONTAP 9.15.1 以降でリリースされたプラットフォーム) が含まれている場合、構成内のすべてのノードをONTAP 9.15.1P11 またはONTAP 9.16.1P4 以降にアップグレードせずに、*共有MetroCluster/HA ポート* を使用するプラットフォーム ( ONTAP 9.15.1 より前にリリースされたプラットフォーム) を追加することはできません。

[CAUTION]
====
*共有/ MetroCluster HA ポート* を使用する古いプラットフォーム モデルを、*共有クラスタ/HA ポート* を使用する新しいプラットフォーム モデルを含むMetroClusterに追加することはまれなシナリオであり、ほとんどの組み合わせは影響を受けません。

====
次の表を使用して、組み合わせが影響を受けるかどうかを確認してください。既存のプラットフォームが最初の列にリストされ、構成に追加するプラットフォームが 2 番目の列にリストされている場合、新しい DR グループを追加するには、構成内のすべてのノードでONTAP 9.15.1P11 またはONTAP 9.16.1P4 以降が実行されている必要があります。

[cols="20,20,20,20,20"]
|===
2+| 既存の MetroCluster に以下が含まれている場合... 2+| 追加するプラットフォームは... | 作業 


 a| 
*共有クラスター/HA ポート* を使用する AFF システム:

* AFF A20用
* AFF A30用
* AFF C30
* AFF A50用
* AFF C60
* AFF C80用
* AFF A70用
* AFF A90用
* AFF A1K用

 a| 
*共有クラスター/HA ポート* を使用する FAS システム:

* FAS50
* FAS70
* FAS90

 a| 
*共有 MetroCluster/HA ポート* を使用する AFF システム:

* AFF A150、ASA A150向け
* AFF A220
* AFF C250、ASA C250向け
* AFF A250、ASA A250向け
* AFF A300
* AFF A320
* AFF C400、ASA C400向け
* AFF A400、ASA A400向け
* AFF A700
* AFF C800、ASA C800向け
* AFF A800、ASA A800向け
* AFF A900、ASA A900向け

 a| 
*共有 MetroCluster/HA ポート* を使用する FAS システム:

* FAS2750
* FAS500f
* FAS8200
* FAS8300
* FAS8700 の場合
* FAS9000
* FAS9500

| 既存の MetroCluster 構成に新しいプラットフォームを追加する前に、既存および新しい構成内のすべてのノードを ONTAP 9.15.1P11 または ONTAP 9.16.1P4 以降にアップグレードします。 
|===