---
permalink: transition/task_apply_rcfs.html 
sidebar: sidebar 
keywords: Generating and applying RCFs to the new IP switches, review, requirement, preparing, prepare, transition, perform, procedure, order, completing, complete, step, task, moving, move, controller, storage, shelves, shelf, exist, configuration, direct, metrocluster, fc, ip, verify, health, removing, remove, tiebreaker, monitor, software, generating, generate, apply, rcf, switch, controller, configure, prepare, preparing 
summary: MetroCluster IP 設定に新しい IP スイッチを使用する場合は、カスタム RCF ファイルでスイッチを設定する必要があります。 
---
= 新しい IP スイッチへの RCF の生成と適用
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
MetroCluster IP 設定に新しい IP スイッチを使用する場合は、カスタム RCF ファイルでスイッチを設定する必要があります。

このタスクは、新しいスイッチを使用する場合に必要です。

既存のスイッチを使用している場合は、に進みます link:task_move_cluster_connections.html["ローカルクラスタ接続を移動しています"]。

. 新しい IP スイッチを設置してラックに設置します。
. 新しい RCF ファイルを適用するための IP スイッチを準備します。
+
スイッチベンダーに対応するセクションを参照してください。

+
** link:../install-ip/task_switch_config_broadcom.html#resetting-the-broadcom-ip-switch-to-factory-defaults["Broadcom IP スイッチを工場出荷時のデフォルトにリセットします"]
** link:../install-ip/task_switch_config_cisco.html#resetting-the-cisco-ip-switch-to-factory-defaults["Cisco IPスイッチを工場出荷時のデフォルトにリセットする"]
** link:../install-ip/task_switch_config_nvidia.html#reset-the-nvidia-ip-sn2100-switch-to-factory-defaults["NVIDIA IP SN2100スイッチを工場出荷時のデフォルトにリセット"]


. 必要に応じて、スイッチのファームウェアをサポートされているバージョンにアップデートします。
. RCF ジェネレータツールを使用してスイッチベンダーとプラットフォームモデルに応じた RCF ファイルを作成し、その後ファイルでスイッチを更新します。
+
スイッチベンダーに対応するセクションを参照してください。

+
** link:../install-ip/task_switch_config_broadcom.html["Broadcom IPのRCFファイルをダウンロードしてインストールする"]
** link:../install-ip/task_switch_config_cisco.html["Cisco IP RCFファイルのダウンロードとインストール"]
** link:../install-ip/task_switch_config_nvidia.html#download-and-install-the-cumulus-software["NVIDIA RCFファイルをダウンロードしてインストールする"]



