---
permalink: transition/task_move_data_to_new_drive_shelves.html 
sidebar: sidebar 
keywords: Generating and applying RCFs to the new IP switches, review, requirement, preparing, prepare, transition, perform, procedure, order, completing, complete, step, task, moving, move, controller, storage, shelves, shelf, exist, configuration, direct, metrocluster, fc, ip, verify, health, removing, remove, tiebreaker, monitor, software, generating, generate, apply, rcf, switch, controller, configure, prepare, preparing 
summary: 移行時に、 MetroCluster FC 構成のドライブシェルフから新しい MetroCluster IP 構成へデータを移動します。 
---
= 新しいドライブシェルフへのデータの移動
:allow-uri-read: 


[role="lead"]
移行時に、 MetroCluster FC 構成のドライブシェルフから新しい MetroCluster IP 構成へデータを移動します。

.作業を開始する前に
新しいアグリゲートにボリュームを移動する前に、デスティネーションノードまたはIPノードに新しいSAN LIFを作成し、ホストを接続する必要があります。

. サポートケースの自動生成を再開するには、メンテナンスが完了したことを示す AutoSupport メッセージを送信します。
+
.. 問題次のコマンドを実行します。「 system node AutoSupport invoke -node * -type all -message MAINT=end 」
.. パートナークラスタに対してこのコマンドを繰り返します。


. 新しいコントローラ上のアグリゲートに、一度に 1 つのボリュームずつデータボリュームを移動します。
+
の手順を使用します http://docs.netapp.com/platstor/topic/com.netapp.doc.hw-upgrade-controller/GUID-AFE432F6-60AD-4A79-86C0-C7D12957FA63.html["アグリゲートの作成と新しいノードへのボリュームの移動"]。

. 追加したノードに SAN LIF を作成します。
+
の次の手順を使用します http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-expand/GUID-E3BB89AF-6251-4210-A979-130E845BC9A1.html["新しいノードの LUN パスを更新しています"^]。

. FC ノードにノードロックライセンスがあるかどうかを確認します。ある場合は、新しく追加したノードに追加する必要があります。
+
の次の手順を使用します http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-expand/GUID-487FAC36-3C5C-4314-B4BD-4253CB67ABE8.html["ノードロックライセンスを追加しています"^]。

. データ LIF を移行
+
の手順を使用します  http://docs.netapp.com/platstor/topic/com.netapp.doc.hw-upgrade-controller/GUID-95CA9262-327D-431D-81AA-C73DEFF3DEE2.html["SAN 以外のデータ LIF とクラスタ管理 LIF を新しいノードに移動する"^] クラスタ管理 LIF を移行する手順は、 do * not * ：最後の 2 つの手順で行ってください。



[NOTE]
====
* VMware vStorage APIs for Array Integration （ VAAI ）でコピーオフロード処理に使用されている LIF を移行することはできません。
* MetroCluster ノードのFCからIPへの移行が完了したあと、iSCSIホスト接続を新しいノードに移動しなければならない場合があります。を参照してください link:task_move_linux_iscsi_hosts_from_mcc_fc_to_mcc_ip_nodes.html["Linux iSCSIホストをMetroCluster FCノードからMetroCluster IPノードに移動しています。"]


====