---
permalink: transition/task_configure_the_new_nodes_and_complete_transition.html 
sidebar: sidebar 
keywords: node, complete, transition, configure, metrocluster, ip, node, configuring, disabling, disable, data, set, up, lif, bring, svm, moving, move, system, volume 
summary: 新しいノードを追加したら、移行手順を完了して、 MetroCluster IP ノードを設定する必要があります。 
---
= 新しいノードの設定と移行の完了
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
新しいノードを追加したら、移行手順を完了して、 MetroCluster IP ノードを設定する必要があります。



== MetroCluster IP ノードを設定し、移行を無効にします

MetroCluster IP 接続を実装し、 MetroCluster 構成を更新し、移行モードを無効にする必要があります。

.手順
. コントローラ node_A_1 の IP から次のコマンドを実行して、新しいノードを DR グループに形成します。
+
`metrocluster configuration-settings dr-group create -partner-cluster <peer_cluster_name> -local-node <local_controller_name> -remote-node <remote_controller_name>`

+
「 MetroCluster configurion-settings dr-group show 」を参照してください

. MetroCluster IP インターフェイスを作成します（ node_A_1 の IP 、 node_B_2 の IP 、 node_B_1 の IP 、 node_B_2 の IP 、 node_B_2 の IP ） - コントローラごとに 2 つのインターフェイスを作成します。合計 8 つのインターフェイスが必要です。
+
`metrocluster configuration-settings interface create -cluster-name <cluster_name> -home-node <controller_name> -home-port <port_name> -address <ip_address> -netmask <netmask_address> -vlan-id <vlan_id>`

+
「 MetroCluster configurion-settings interface show 」を参照してください

+
特定のプラットフォームでは、MetroCluster IPインターフェイスにVLANが使用されます。デフォルトでは、 2 つのポートでそれぞれ 10 と 20 の異なる VLAN が使用されます。

+
サポートされている場合は、コマンドのパラメータを使用して、100より大きい別の（デフォルト以外の）VLAN（101 ~ 4095）を指定することもできます `-vlan-id` `metrocluster configuration-settings interface create` 。

+
次のプラットフォームでは、パラメーターは*サポートされていません* `-vlan-id` 。

+
** FAS8200 と AFF A300
** AFF A320
** FAS9000およびAFF A700
** AFF C800、ASA C800、AFF A800、およびASA A800
+
他のすべてのプラットフォームでは、パラメータがサポートされ `-vlan-id` ます。

+
デフォルトおよび有効なVLAN割り当ては、プラットフォームがパラメータをサポートしているかどうかによって異なり `-vlan-id` ます。

+
[role="tabbed-block"]
====
.vlan-vlan-id </code>をサポートするプラットフォーム<code>
--
デフォルトVLAN：

*** パラメータを指定しない場合、 `-vlan-id` インターフェイスは「A」ポートにVLAN 10、「B」ポートにVLAN 20で作成されます。
*** 指定するVLANは、RCFで選択したVLANと一致する必要があります。


有効なVLAN範囲：

*** デフォルトVLAN 10および20
*** VLAN 101以上（101～4095）


--
.vlan-vlan-id </code>をサポートしないプラットフォーム<code>
--
デフォルトVLAN：

*** 該当なし。このインターフェイスでは、MetroClusterインターフェイスでVLANを指定する必要はありません。スイッチポートによって、使用されるVLANが定義されます。


有効なVLAN範囲：

*** RCFの生成時にすべてのVLANが明示的に除外されていない。VLANが無効な場合は、RCFから警告が表示されます。


--
====




. コントローラ node_A_1 の IP から MetroCluster 接続処理を実行して MetroCluster サイトを接続 - この処理には数分かかることがあります。
+
MetroCluster 構成設定接続接続

. リモートクラスタのディスクが、 iSCSI 接続を介して各コントローラから認識されていることを確認します。
+
「ディスクショー」

+
構成内の他のノードに属するリモートディスクが表示されます。

. node_A_1 の IP と node_B_1 の IP のルートアグリゲートをミラーします。
+
「 aggregate mirror -aggregate root-aggr 」のように指定します

. node_B_2 の IP と node_B_2 の IP のディスクを割り当て
+
ブートメニューで boot_after_MCC_transtion コマンドを実行した場合に、 node_A_1 と node_B_1 に対してすでに作成されているプール 1 のディスク割り当て

+
.. 問題： node_A_1 の IP に対して次のコマンドを実行します。
+
disk assign disk1disk2disk3... diskn-sysid node_B_2-ip-control-sysid-pool 1-force

.. 問題 node_B_2 IP で次のコマンドを実行します。
+
disk assign disk1disk2disk3... diskn -sysid node-a _2 -ip-controller-sysid -pool 1 -force



. リモートディスクの所有権が更新されたことを確認します。
+
「ディスクショー」

. 必要に応じて、次のコマンドを使用して所有権情報を更新します。
+
.. advanced 権限モードに切り替えて、続行するかどうかを尋ねられたら「 y 」と入力します。
+
'set priv advanced'

.. ディスク所有権を更新します。
+
「 disk refresh-ownership controller-name 」と入力します

.. admin モードに戻ります。
+
'set priv admin' のように設定します



. node_B_2 の IP と node_B_2 の IP のルートアグリゲートをミラーリングします。
+
「 aggregate mirror -aggregate root-aggr 」のように指定します

. ルートアグリゲートとデータアグリゲートの再同期が完了したことを確認します。
+
aggr show `aggr plex show`

+
再同期には時間がかかることがありますが、完了してから次の手順に進んでください。

. MetroCluster 構成を更新して新しいノードを組み込みます。
+
.. advanced 権限モードに切り替えて、続行するかどうかを尋ねられたら「 y 」と入力します。
+
'set priv advanced'

.. 構成を更新します。
+
|===


| 設定内容 | 問題コマンド 


 a| 
各クラスタにアグリゲートが 1 つあります。
 a| 
「 MetroCluster configure -refresh true -allow-with-one-aggregate true 」



 a| 
各クラスタに複数のアグリゲートがあります
 a| 
MetroCluster configure -refresh true

|===
.. admin モードに戻ります。
+
'set priv admin' のように設定します



. MetroCluster 移行モードを無効にします。
+
.. advanced 権限モードに切り替え、続行するかどうかを尋ねられたら「 y 」と入力します。
+
'set priv advanced'

.. 移行モードを無効にします。
+
MetroCluster transition disable`

.. admin モードに戻ります。
+
'set priv admin' のように設定します







== 新しいノードにデータ LIF をセットアップ

新しいノード、 node_B_2 の IP および node_B_2 の IP にデータ LIF を設定する必要があります。

新しいコントローラで使用可能な新しいポートがブロードキャストドメインに割り当てられていない場合は、そのドメインに追加する必要があります。必要に応じて、新しいポートに VLAN またはインターフェイスグループを作成します。を参照してください link:https://docs.netapp.com/us-en/ontap/network-management/index.html["Network Management の略"^]

. 現在のポートの使用状況とブロードキャストドメインを特定します。
+
network port show ` network port broadcast-domain show 」

. 必要に応じて、ブロードキャストドメインと VLAN にポートを追加します。
+
.. IP スペースを表示します。
+
network ipspace show

.. IP スペースを作成し、必要に応じてデータポートを割り当てます。
+
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-nmg/GUID-69120CF0-F188-434F-913E-33ACB8751A5D.html["IPspace の設定（クラスタ管理者のみ）"^]

.. ブロードキャストドメインを表示します。
+
「 network port broadcast-domain show 」

.. 必要に応じて、ブロードキャストドメインにデータポートを追加します。
+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-nmg/GUID-003BDFCD-58A3-46C9-BF0C-BA1D1D1475F9.html["ブロードキャストドメインのポートの追加と削除"^]

.. 必要に応じて、 VLAN とインターフェイスグループを再作成します。
+
VLAN およびインターフェイスグループのメンバーシップは、古いノードと異なる場合があります。

+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-nmg/GUID-8929FCE2-5888-4051-B8C0-E27CAF3F2A63.html["VLAN を作成する"^]

+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-nmg/GUID-DBC9DEE2-EAB7-430A-A773-4E3420EE2AA1.html["物理ポートを組み合わせたインターフェイスグループの作成"^]



. 必要に応じて、 MetroCluster IP ノード（ -mc を備えた SVM を含む）の適切なノードとポートで LIF がホストされていることを確認します。
+
で収集した情報を参照してください link:task_connect_the_mcc_ip_controller_modules_2n_mcc_transition_supertask.html["ネットワーク設定を作成しています"]。

+
.. LIF のホームポートを確認します。
+
「 network interface show - field home-port 」のように表示されます

.. 必要に応じて、 LIF の設定を変更します。
+
`vserver config override -command "network interface modify -vserver <svm_name> -home-port <active_port_after_upgrade> -lif <lif_name> -home-node <new_node_name>`

.. LIF をそれぞれのホームポートにリバートします。
+
`network interface revert * -vserver <svm_name>`







== SVM を起動する

LIF の設定が変更されたため、新しいノードで SVM を再起動する必要があります。

.手順
. SVM の状態を確認します。
+
MetroCluster vserver show

. サフィックスが「 -mc 」のない cluster_A 上の SVM を再起動します。
+
`vserver start -vserver <svm_name> -force true`

. パートナークラスタで上記の手順を繰り返します。
. すべての SVM が健全な状態であることを確認します。
+
MetroCluster vserver show

. すべてのデータ LIF がオンラインであることを確認します。
+
「 network interface show 」を参照してください





== 新しいノードへのシステムボリュームの移動

耐障害性を高めるには、システムボリュームを controller_A_1 から IP コントローラ node_A_1 に、さらに node_B_1 から node_B_2 の IP に移動する必要があります。システムボリュームのデスティネーションノードにミラーされたアグリゲートを作成する必要があります。

.このタスクについて
システムボリュームの名前の形式は「 MDV \\_crs_*\\_a' 」または「 MDV_CRS_*\\_b` 」です。 このセクションで使用されている site_A および site_B の参照とは関係がありません。たとえば、 MDV_CRS_*_A は site_A と関連付けられていません

.手順
. 必要に応じて、コントローラ node_A_1 の IP および node_B_2 の IP に少なくとも 3 本のプール 0 と 3 本のプール 1 ディスクを割り当てます。
. ディスクの自動割り当てを有効にします。
. site_A から次の手順を実行して、 _B システムボリュームを node_A_1 の IP から node_B_2 の IP に移動します
+
.. システムボリュームを格納するために、コントローラ node_A_1 にミラーアグリゲートを作成します。
+
`aggr create -aggregate new_node_A_2-IP_aggr -diskcount 10 -mirror true -node node_A_2-IP`

+
「 aggr show 」と入力します

+
ミラーされたアグリゲートには、 5 つのプール 0 と 5 つのプール 1 スペアディスクが必要です。これらのディスクはコントローラ node_A_1 のコントローラ node_A_1 の IP で所有されます。

+
ディスクが不足している場合は ' アドバンス・オプションの -force-small-aggregate true を使用すると ' ディスクの使用を 3 プール 0 および 3 プール 1 のディスクに制限できます

.. 管理 SVM に関連付けられているシステムボリュームの一覧を表示します。
+
「 vserver show 」

+
`volume show -vserver <admin_svm_name>`

+
site_A が所有するアグリゲートに含まれているボリュームを特定しますsite_B のシステムボリュームも表示されます。



. site_A 用の MDV_CRS_*_B システムボリュームを、コントローラ node_A_1 で作成されたミラーアグリゲートに移動します
+
.. 可能なデスティネーションアグリゲートがないかどうかを確認します
+
`volume move target-aggr show -vserver <admin_svm_name> -volume MDV_CRS_*_B`

+
node_A_1 に作成されたアグリゲートが表示されます。

.. node_A_1 に作成した新しいアグリゲートにボリュームを移動します。
+
「高度」

+
`volume move start -vserver <admin_svm_name> -volume MDV_CRS_*_B -destination-aggregate new_node_A_2-IP_aggr -cutover-window 40`

.. 移動処理のステータスを確認します。
+
`volume move show -vserver <admin_svm_name> -volume MDV_CRS_*_B`

.. 移動処理が完了したら、 MDV_CRS_*_B システムが node_A_1 の新しいアグリゲートに含まれていることを確認します。
+
「管理者」

+
`volume show -vserver <admin_svm_name>`



. site_B （ node_B_1 - IP と node_B_2 - IP ）で上記の手順を繰り返します。

