---
permalink: upgrade/concept_choosing_an_upgrade_method_mcc.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, choose, upgrade, refresh, method 
summary: 使用するアップグレードまたは更新手順は、プラットフォームモデル、アップグレードの範囲、および MetroCluster 構成の種類によって異なります。 
---
= はじめに：コントローラのアップグレード、システムの更新、拡張のいずれかを選択してください
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
機器のアップグレードの範囲に応じて、コントローラのアップグレード手順 、システムの更新手順 、または拡張手順 を選択します。

* コントローラのアップグレード手順は、コントローラモジュールにのみ適用されます。コントローラが新しいコントローラモデルに置き換えられます。
+
ストレージシェルフモデルはアップグレードされません。

+
** スイッチオーバーとスイッチバックの手順では、パートナークラスタのコントローラモジュールをアップグレードしている間、 MetroCluster スイッチオーバー処理を使用してクライアントに無停止のサービスが提供されます。
** ARL ベースコントローラのアップグレード手順では、アグリゲートの再配置処理を使用して、古い構成からアップグレード後の新しい構成へ、データを無停止で移動します。


* 更新手順は、コントローラとストレージシェルフに適用されます。
+
更新手順では、新しいコントローラとシェルフを MetroCluster 構成に追加して 2 つ目の DR グループを作成すると、データが新しいノードに無停止で移行されます。

+
その後、元のコントローラが撤去されます。

* 拡張手順によって、MetroCluster 構成にコントローラとシェルフが追加されるだけで、取り外しは不要になります。
+
使用する手順 は、MetroCluster のタイプと既存のコントローラの数によって異なります。




CAUTION: SVMの移行が実行中の場合は、すべての移行プロセスが完了するまで待ってから、コントローラのアップグレード手順またはシステムの更新手順を開始します。アップグレードまたは更新のプロセス中は、新しいSVM移行処理を開始しないでください。

[cols="2,5"]
|===


| アップグレードの種類 | 手順 


 a| 
コントローラのアップグレード
 a| 
link:../upgrade/concept_choosing_controller_upgrade_mcc.html["コントローラのアップグレード手順 を選択します"]



 a| 
システムの更新
 a| 
link:../upgrade/concept_choosing_tech_refresh_mcc.html["システム更新手順 を選択します"]



 a| 
拡張
 a| 
* link:../upgrade/task_expand_a_two_node_mcc_fc_configuration_to_a_four_node_fc_configuration_supertask.html["2ノードMetroCluster から4ノード"]
* link:../upgrade/task_expand_a_four_node_mcc_fc_configuration_to_an_eight_node_configuration.html["4ノードMetroCluster FCから8ノード"]
* link:../upgrade/task_expand_a_four_node_mcc_ip_configuration.html["4ノードMetroCluster のIPアドレスを8に設定します"]


|===