---
permalink: upgrade/task_prepare_for_the_upgrade_add_2nd_controller_to_create_ha_pair.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, prepare, upgrade 
summary: HA ペアにアップグレードする前に、システムがすべての要件を満たしていること、および必要な情報がすべて揃っていることを確認する必要があります。 
---
= アップグレードの準備を行います
:icons: font
:imagesdir: ../media/


[role="lead"]
HA ペアにアップグレードする前に、システムがすべての要件を満たしていること、および必要な情報がすべて揃っていることを確認する必要があります。

.手順
. 新しいコントローラモジュールに割り当てることができる未割り当てのディスクまたはスペアディスクを特定する必要があります。
+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2427462["物理ストレージ管理"^]

+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-psmg/home.html["ディスクおよびアグリゲートの管理"^]

. 前の手順の結果に基づいて、次のいずれかを実行します。
+
[cols="1,3"]
|===


| 結果 | 作業 


 a| 
ルート / データパーティショニングを使用しないシステムに、新しいコントローラモジュール用の十分な数のスペアディスクがありません
 a| 
詳細については、テクニカルサポートにお問い合わせください。



 a| 
その他の結果
 a| 
次の手順を実行します。

.. 既存のノードのアグリゲートが配置されている場所を特定します。
+
「 storage aggregate show

.. ディスク所有権の自動割り当てを有効にしている場合は無効にします。
+
「 storage disk option modify -node node_name -autoassign off

.. アグリゲートのないディスクの所有権を削除します。
+
「 storage disk removeowner _disk_name _ 」を選択します

.. 新しいノードに必要な数のディスクについて、前の手順を繰り返します。


|===
. 次の接続用のケーブルがあることを確認します。
+
** クラスタ接続
+
2 ノードスイッチレスクラスタを作成する場合は、コントローラモジュールを接続するために 2 本のケーブルが必要です。それ以外の場合は、クラスタネットワークスイッチへのコントローラモジュール接続ごとに 2 本、合計 4 本以上のケーブルが必要です。その他のシステム（ 80xx シリーズなど）では、デフォルトで 4 つまたは 6 つのクラスタ接続が設定されています。

** デュアルシャーシの HA ペアのシステムの場合、 HA インターコネクト接続を確立します


. コントローラモジュールに使用できるシリアルポートコンソールがあることを確認します。
. 環境がサイトとシステムの要件を満たしていることを確認します。
+
https://hwu.netapp.com["NetApp Hardware Universe の略"^]

. 新しいコントローラモジュールの IP アドレスとその他のネットワークパラメータをすべて収集します。

