---
permalink: upgrade/task_shut_down_the_exist_controller_when_add_a_2nd_controller_in_c_mode.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, shut, down, existing, controller, module 
summary: 既存のコントローラモジュールのクリーンシャットダウンを実行して、すべてのデータがディスクに書き込まれたことを確認する必要があります。また、電源装置の接続を解除する必要があります。 
---
= 既存のコントローラモジュールをシャットダウンしています
:icons: font
:imagesdir: ../media/


[role="lead"]
既存のコントローラモジュールのクリーンシャットダウンを実行して、すべてのデータがディスクに書き込まれたことを確認する必要があります。また、電源装置の接続を解除する必要があります。

. 既存のコントローラモジュールプロンプトからノードを停止します。「 * halt local-inhibit-takeover true *
+
手順の停止を続行するかどうかを確認するメッセージが表示されたら、「 y 」と入力し、システムが LOADER プロンプトで停止するまで待ちます。

+

IMPORTANT: システムコンポーネントを交換する前にシステムのクリーンシャットダウンを実行し、 NVRAM または NVMEM 内の書き込み前のデータが失われないようにする必要があります。

+
** 80xx システムでは NVMEM の LED はコントローラモジュールのネットワークポートの右側にあり、電池のマークが付いています。NVRAM 内に書き込み前のデータがある場合、この LED が点滅します。この LED が halt コマンドの実行後も黄色く点滅する場合は、システムをリブートし、もう一度 halt を実行する必要があります。


. 接地対策がまだの場合は、自身で適切に実施します。
. システムと電源装置タイプに適した方法で、電源装置の電源を切り、電源を切断します。
+
|===
| システムの用途 | 作業 


 a| 
AC 電源装置
 a| 
電源から電源コードを抜き、電源コードを取り外します。



 a| 
DC 電源装置
 a| 
DC 電源の電源を切り、必要に応じて DC ケーブルを取り外します。

|===

