---
permalink: upgrade/task_configure_the_fc_to_sas_bridges_for_health_monitor.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, configure, fc, sas, bridges, health, monitoring 
summary: FibreBridge ブリッジでは、サードパーティ製の SNMP 監視ツールはサポートされません。ONTAP 9.8 以降では、デフォルトで FC-to-SAS ブリッジがインバンド接続で監視されるため、追加の設定は必要ありません。 
---
= 健常性監視用の FC-to-SAS ブリッジの設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
健全性監視用にFC-to-SASブリッジを設定する方法について説明します。

.このタスクについて
* FibreBridge ブリッジでは、サードパーティ製の SNMP 監視ツールはサポートされません。
* ONTAP 9.8 以降では、デフォルトで FC-to-SAS ブリッジがインバンド接続で監視されるため、追加の設定は必要ありません。



NOTE: ONTAP 9.8 以降では 'storage bridge コマンドは 'system bridge コマンドに置き換えられました次の手順は「 storage bridge 」コマンドを示していますが、 ONTAP 9.8 以降を実行している場合は「 system bridge 」コマンドが優先されます。

.ステップ
. ONTAP クラスタのプロンプトで、ブリッジをヘルスモニタの対象に追加します。
+
.. 使用している ONTAP のバージョンに対応したコマンドを使用して、ブリッジを追加します。
+
|===


| ONTAP バージョン | コマンドを実行します 


 a| 
9.5 以降
 a| 
「 storage bridge add -address 0.0.0.0 -managed-by in-band-name_bridge-name_`



 a| 
9.4 以前
 a| 
「 storage bridge add -address_bridge-ip-address_-name_bridge-name_` 」

|===
.. ブリッジが追加され、正しく設定されていることを確認します。
+
「 storage bridge show 」

+
ポーリング間隔に応じて、すべてのデータが反映されるまで 15 分程度かかる場合があります。「 Status 」列の値が「 ok 」で、 World Wide Name （ WWN ；ワールドワイド名）などのその他の情報が表示されていれば、 ONTAP ヘルスモニタでブリッジに接続して監視できます。

+
次の例は、 FC-to-SAS ブリッジが設定されていることを示しています。

+
[listing]
----
controller_A_1::> storage bridge show

Bridge              Symbolic Name Is Monitored  Monitor Status  Vendor Model                Bridge WWN
------------------  ------------- ------------  --------------  ------ -----------------    ----------
ATTO_10.10.20.10  atto01        true          ok              Atto   FibreBridge 7500N   	20000010867038c0
ATTO_10.10.20.11  atto02        true          ok              Atto   FibreBridge 7500N   	20000010867033c0
ATTO_10.10.20.12  atto03        true          ok              Atto   FibreBridge 7500N   	20000010867030c0
ATTO_10.10.20.13  atto04        true          ok              Atto   FibreBridge 7500N   	2000001086703b80

4 entries were displayed

 controller_A_1::>
----



