---
permalink: upgrade/task_apply_the_rcf_files_and_recable_the_switches.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, apply, rcf, files, recable, switches 
summary: RCF ファイルを適用して、新しいノードに対応するようにゾーニングを再設定する必要があります。 
---
= RCF ファイルの適用およびスイッチの再接続
:icons: font
:imagesdir: ../media/


[role="lead"]
RCF ファイルを適用して、新しいノードに対応するようにゾーニングを再設定する必要があります。

.手順
. 使用している構成用の RCF ファイルを探します。
+
使用しているスイッチモデルに対応した 8 ノード構成用の RCF ファイルを使用する必要があります。

. ダウンロードページの指示に従って RCF ファイルを適用し、必要に応じて ISL 設定を調整します。
. スイッチの設定が保存されていることを確認します。
. FC スイッチをリブートします。
. 作成したケーブルレイアウトを使用して、既存の FC-to-SAS ブリッジと新しい FC-to-SAS ブリッジの両方を FC スイッチにケーブル接続します。
+
リファレンス構成ファイル（ RCF ）を使用できるようにするためには、 FC スイッチポートの用途が、 _ ファブリック接続 MetroCluster インストールおよび設定ガイド _ に記載されている MetroCluster 8 ノードの用途と同じである必要があります。

+
link:../install-fc/index.html["ファブリック接続 MetroCluster のインストールと設定"]

+

NOTE: RCF ファイルを使用できるようにケーブル接続できない場合は、テクニカルサポートにお問い合わせください。RCF ファイルを使用できないケーブル接続の場合は、この手順を使用しないでください。

. スイッチに対応したコマンドを使用して、ポートがオンラインであることを確認します。
+
|===


| スイッチベンダー | コマンドを実行します 


 a| 
Brocade
 a| 
SwitchShow



 a| 
シスコ
 a| 
インターフェイスの概要を表示します

|===
. 作成したケーブルレイアウトを使用して、既存のコントローラの FC-VI ポートを新しいコントローラにケーブル接続します。
+
link:../install-fc/index.html["ファブリック接続 MetroCluster のインストールと設定"]

+
リファレンス構成ファイル（ RCF ）を使用できるようにするためには、 FC スイッチポートの用途が、 _ ファブリック接続 MetroCluster インストールおよび設定ガイド _ に記載されている MetroCluster 8 ノードの用途と同じである必要があります。

+

NOTE: RCF ファイルを使用できるようにケーブル接続できない場合は、テクニカルサポートにお問い合わせください。RCF ファイルを使用できないケーブル接続の場合は、この手順を使用しないでください。

. 既存のノードから、 FC-VI ポートがオンラインであることを確認します。
+
MetroCluster インターコネクト・アダプタ・ショー

+
MetroCluster interconnect mirror show

. 現在のコントローラの HBA ポートを新しいコントローラにケーブル接続します。
. 既存のコントローラモジュールで、メンテナンス中のスイッチファブリックに接続されているポートを有効にします。
+
「 storage port enable -NODE-NODE-NAME_-PORT_PORT_ID_` 」

. 新しいコントローラを起動し、メンテナンスモードでブートします。
+
「 boot_ontap maint 」を使用してください

. 新しい DR グループが使用するストレージのみが新しいコントローラモジュールに認識されることを確認します。
+
他の DR グループが使用するストレージが認識されないようにしてください。

. このプロセスの最初に戻り、 2 つ目のスイッチファブリックを再ケーブル接続します。

