---
permalink: upgrade/task_upgrade_controllers_system_control_commands_in_a_four_node_mcc_ip.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, controllers, switchover, switchback, ip, configuration, net, boot, root, aggregate, system, commands, mcc 
summary: このガイド付きの自動MetroCluster スイッチオーバー処理を使用すると、4ノードMetroCluster IP構成のコントローラの無停止アップグレードを実行できます。 
---
= 「system controller replace」コマンドを使用したスイッチオーバーとスイッチバックを使用した4ノードMetroCluster IP構成のコントローラのアップグレード（ONTAP 9.13.1以降）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
このガイド付きの自動MetroCluster スイッチオーバー処理を使用すると、4ノードMetroCluster IP構成でコントローラの無停止アップグレードを実行できます。この手順の一部として他のコンポーネント（ストレージシェルフやスイッチなど）をアップグレードすることはできません。



== サポートされるプラットフォームの組み合わせ

この手順 では、AFF A300からAFF A900へのコントローラのアップグレードのみがサポートされます。

プラットフォームのアップグレードの組み合わせの詳細については、のMetroCluster IPアップグレードの表を参照してください link:concept_choosing_controller_upgrade_mcc.html#supported-metrocluster-ip-controller-upgrades["コントローラのアップグレード手順 を選択します"]。

を参照してください https://["アップグレードまたは更新方法を選択します"] を参照してください。



== このタスクについて

* この手順は、コントローラのアップグレードにのみ使用できます。
+
ストレージシェルフやスイッチなど、構成内の他のコンポーネントは同時にアップグレードできません。

* ONTAP 9.13.1以降を実行している4ノードMetroCluster IP構成のこの 手順 環境 コントローラモジュール。
+
https://["NetApp Hardware Universe の略"^]

* MetroCluster システムで両方のサイトで同じバージョンのONTAP が実行されている必要があります。
* この手順 を使用して、NSOベースの自動スイッチオーバーとスイッチバックを使用して4ノードMetroCluster IP構成のコントローラをアップグレードできます。
+

NOTE: 4ノードMetroCluster IP構成では、「systems controller replace」コマンドを使用したアグリゲートの再配置（ARL）を使用したアップグレードはサポートされていません。

* NSOコントローラの自動アップグレード手順 を使用して、両方のサイトのコントローラを順番にアップグレードする必要があります。
* この NSO ベースのコントローラの自動アップグレード手順を使用すると、 MetroCluster ディザスタリカバリ（ DR ）サイトでコントローラの交換を開始できます。コントローラの交換は一度に 1 つのサイトでしか開始できません。
* サイト A でコントローラの交換を開始するには、サイト B からコントローラの交換開始コマンドを実行する必要があります交換処理ガイドは、サイト A の両方のノードのコントローラのみを交換する場合に使用します。サイト B のコントローラを交換するには、サイト A からコントローラ交換の開始コマンドを実行する必要がありますコントローラを交換するサイトを示すメッセージが表示されます。


この手順では、次の名前が使用されています。

* site_A
+
** アップグレード前：
+
*** node_A_1 - 古い
*** Node_a_2-old


** アップグレード後：
+
*** node_A_1 - 新規
*** Node_a_2 - 新規




* site_B
+
** アップグレード前：
+
*** node_B_1 - 古い
*** node_B_2 - 古い


** アップグレード後：
+
*** node_B_1 - 新規
*** node_B_2 - 新規








== アップグレードを準備

コントローラのアップグレードを準備するには、システムの事前確認を実行し、構成情報を収集する必要があります。

ONTAP メディエーターがインストールされている場合は、事前確認の開始前に自動的に検出されて削除されます。削除を確認するには、ユーザ名とパスワードの入力を求められます。アップグレードが完了したとき、または事前確認が失敗した場合、またはアップグレードの続行を中止した場合は、を実行する必要があります <<man_reconfig_mediator,ONTAP メディエーターを手動で再設定します>>。

アップグレードのどの段階でも、サイト A から「 system controller replace show 」または「 system controller replace show -details 」コマンドを実行してステータスを確認できます。コマンドから何も出力されない場合は、数分待ってからコマンドを再実行してください。

.手順
. サイト A からコントローラの自動交換用手順を開始して、サイト B のコントローラを交換します。
+
`system controller replace start -nso true`

+
自動処理によって事前確認が実行されます。問題が見つからなかった場合は処理が一時停止するため、構成に関連する情報を手動で収集できます。

+
[NOTE]
====
** を実行しない場合 `system controller replace start -nso true` コマンドを実行すると、コントローラのアップグレード手順 では、MetroCluster IPシステムのデフォルト手順 としてNSOベースの自動スイッチオーバーとスイッチバックが選択されます。
** 現在のソースシステムと互換性のあるすべてのターゲットシステムが表示されます。ソースコントローラを、異なるバージョンの ONTAP または互換性のないプラットフォームのコントローラと交換した場合、自動処理が停止し、新しいノードがブートされたあとにエラーが報告されます。クラスタを正常な状態に戻すには、手動のリカバリ手順に従う必要があります。
+
「 system controller replace start 」コマンドで、次の事前確認エラーが報告されることがあります。

+
[listing]
----
Cluster-A::*>system controller replace show
Node        Status         Error-Action
----------- -------------- ------------------------------------
Node-A-1    Failed         MetroCluster check failed. Reason : MCC check showed errors in component aggregates
----
+
アグリゲートのミラーされていないか、別のアグリゲート問題が原因で、このエラーが発生していないかどうかを確認してくださいすべてのミラーアグリゲートが正常で、デグレードまたはミラーデグレードでないことを確認します。このエラーの原因がミラーされていないアグリゲートのみである場合は、「 system controller replace start 」コマンドで「 -skip-metrocluster-check true 」オプションを選択することで、このエラーを無視できます。リモートストレージにアクセスできる場合、ミラーされていないアグリゲートはスイッチオーバー後にオンラインになります。リモートストレージリンクに障害が発生すると、ミラーされていないアグリゲートがオンラインになりません。



====
. サイト B にログインし、「 system controller replace show 」または「 system controller replace show -details 」コマンドのコンソールメッセージに表示されるコマンドに従って、設定情報を手動で収集します。




=== アップグレード前に情報を収集

アップグレードの実行前にルートボリュームが暗号化されている場合は、暗号化された古いルートボリュームを含む新しいコントローラをブートするために、バックアップキーとその他の情報を収集する必要があります。

.このタスクについて
このタスクは、既存のMetroCluster IP設定で実行します。

.手順
. 既存のコントローラのケーブルにラベルを付けておくと、新しいコントローラをセットアップするときに識別しやすくなります。
. バックアップキーやその他の情報を取得するコマンドを表示します。
+
「 system controller replace show 」と表示されます

+
パートナークラスタから 'how コマンドの下に一覧表示されているコマンドを実行します

+
。 `show` コマンド出力には、MetroCluster インターフェイスIP、システムID、およびシステムUUIDを含む3つのテーブルが表示されます。この情報は、手順 の後半の工程で新しいノードのブート時にbootargを設定する際に必要になります。

. MetroCluster 構成内のノードのシステム ID を収集します。
+
--
MetroCluster node show -fields node-systemid 、 dr-partner-systemid'

交換用手順では、これらのシステム ID を新しいコントローラモジュールのシステム ID に置き換えます。

この4ノードMetroCluster IP構成の例では、次の古いシステムIDが取得されます。

** node_A_1 - 古い： 4068741258
** node_A_2 - 古い： 4068741260
** node_B_1 - 古い： 4068741254
** node_B_2 - 古い： 4068741256


[listing]
----
metrocluster-siteA::> metrocluster node show -fields node-systemid,ha-partner-systemid,dr-partner-systemid,dr-auxiliary-systemid
dr-group-id        cluster           node            node-systemid     ha-partner-systemid     dr-partner-systemid    dr-auxiliary-systemid
-----------        ---------------   ----------      -------------     -------------------     -------------------    ---------------------
1                    Cluster_A       Node_A_1-old    4068741258        4068741260              4068741256             4068741256
1                    Cluster_A       Node_A_2-old    4068741260        4068741258              4068741254             4068741254
1                    Cluster_B       Node_B_1-old    4068741254        4068741256              4068741258             4068741260
1                    Cluster_B       Node_B_2-old    4068741256        4068741254              4068741260             4068741258
4 entries were displayed.
----
この2ノードMetroCluster IP構成の例では、次の古いシステムIDが取得されます。

** node_A_1 ： 4068741258
** node_B_1 ： 4068741254


[listing]
----
metrocluster node show -fields node-systemid,dr-partner-systemid

dr-group-id cluster    node          node-systemid dr-partner-systemid
----------- ---------- --------      ------------- ------------
1           Cluster_A  Node_A_1-old  4068741258    4068741254
1           Cluster_B  node_B_1-old  -             -
2 entries were displayed.
----
--
. 各ノードのポートと LIF の情報を収集
+
ノードごとに次のコマンドの出力を収集する必要があります。

+
** 'network interface show -role cluster, node-mgmt
** 'network port show -node node_name -type physical ’
** 'network port vlan show -node -node-name _`
** 「 network port ifgrp show -node node_name 」 - instance 」を指定します
** 「 network port broadcast-domain show 」
** 「 network port reachability show-detail` 」と表示されます
** network ipspace show
** volume show
** 「 storage aggregate show
** 「 system node run -node _node-name_sysconfig -a 」のように入力します


. MetroCluster ノードが SAN 構成になっている場合は、関連情報を収集します。
+
次のコマンドの出力を収集する必要があります。

+
** 「 fcp adapter show -instance 」のように表示されます
** 「 fcp interface show -instance 」の略
** 「 iscsi interface show 」と表示されます
** ucadmin show


. ルートボリュームが暗号化されている場合は、 key-manager に使用するパスフレーズを収集して保存します。
+
「 securitykey-manager backup show 」を参照してください

. MetroCluster ノードがボリュームまたはアグリゲートに暗号化を使用している場合は、キーとパスフレーズに関する情報をコピーします。
+
追加情報の場合は、を参照してください https://["オンボードキー管理情報の手動でのバックアップ"^]。

+
.. オンボードキーマネージャが設定されている場合：
+
「 securitykey manager onboard show-backup 」を参照してください

+
パスフレーズは、あとでアップグレード手順で必要になります。

.. Enterprise Key Management （ KMIP ）が設定されている場合は、次のコマンドを問題で実行します。
+
「 securitykey-manager external show -instance 」

+
「セキュリティキーマネージャのキークエリ」



. 設定情報の収集が完了したら、処理を再開します。
+
「システムコントローラの交換が再開」





=== Tiebreaker またはその他の監視ソフトウェアから既存の設定を削除します

スイッチオーバーを開始できる MetroCluster Tiebreaker 構成またはその他のサードパーティアプリケーション（たとえば、 ClusterLion ）で既存の構成を監視している場合は、古いコントローラを交換する前に、 Tiebreaker またはその他のソフトウェアから MetroCluster 構成を削除する必要があります。

.手順
. http://["既存の MetroCluster 設定を削除します"^] Tiebreaker ソフトウェアから。
. スイッチオーバーを開始できるサードパーティ製アプリケーションから既存の MetroCluster 構成を削除します。
+
アプリケーションのマニュアルを参照してください。





== 古いコントローラの交換と新しいコントローラのブート

情報を収集して処理を再開すると、スイッチオーバー処理が自動化されます。

.このタスクについて
自動化処理によってスイッチオーバー処理が開始されます。これらの処理が完了すると、処理は* paused for user intervention *で一時停止します。これにより、を使用して、コントローラをラックに設置し、パートナーコントローラをブートし、ルートアグリゲートディスクをフラッシュバックアップから新しいコントローラモジュールに再割り当てできます `sysids` さっき集まった。

.作業を開始する前に
スイッチオーバーを開始する前に自動化処理が一時停止するため、サイト B のすべての LIF が「稼働」していることを手動で確認できます必要に応じて 'down' の LIF を up にし 'system controller replace resume' コマンドを使用して自動化処理を再開します



=== 古いコントローラのネットワーク構成を準備しています

新しいコントローラでネットワークが正常に再開されるようにするには、 LIF を共通ポートに移動して、古いコントローラのネットワーク設定を削除する必要があります。

.このタスクについて
* このタスクは、古いノードごとに実行する必要があります。
* で収集した情報を使用します <<アップグレードを準備>>。


.手順
. 古いノードをブートし、ノードにログインします。
+
「 boot_ontap 」

. 古いコントローラのすべてのデータ LIF のホームポートを、新旧両方のコントローラモジュールで同じ共通ポートに割り当てます。
+
.. LIF を表示します。
+
「 network interface show 」を参照してください

+
SAN と NAS を含むすべてのデータ LIF は ' スイッチオーバーサイト（ cluster_A ）で稼働しているため ' 管理上の "" および運用上の "" ダウン "" になります

.. の出力を確認して、クラスタポートとして使用されていない新旧両方のコントローラで同じ共通の物理ネットワークポートを特定します。
+
たとえば、「 e0d 」は古いコントローラ上の物理ポートであり、新しいコントローラ上にも存在します。「 e0d 」は、クラスタポートとしても、新しいコントローラ上でも使用されません。

+
プラットフォームモデルのポートの用途については、を参照してください https://["NetApp Hardware Universe の略"^]

.. すべてのデータ LIF で共通ポートをホームポートとして使用するように変更します。
+
「 network interface modify -vserver _svm -name _ -lif data -lif lif _ -home-port_port -id_ 」と入力します

+
次の例では、これは「 e0d 」です。

+
例：

+
[listing]
----
network interface modify -vserver vs0 -lif datalif1 -home-port e0d
----


. ブロードキャストドメインを変更して、削除する必要がある VLAN と物理ポートを削除します。
+
「 broadcast-domain remove-ports -broadcast-domain_domain-name-name_ports_node-name ： port-id_` 」

+
すべての VLAN ポートと物理ポートについて、この手順を繰り返します。

. クラスタポートをメンバーポートとして使用し、インターフェイスグループをメンバーポートとして使用している VLAN ポートをすべて削除します。
+
.. VLAN ポートを削除します。
+
「 network port vlan delete -node-node-name-vlan-name_portid -vlandid_ 」のように指定します

+
例：

+
[listing]
----
network port vlan delete -node node1 -vlan-name e1c-80
----
.. インターフェイスグループから物理ポートを削除します。
+
「 network port ifgrp remove-port -node-node_name -ifgrp_interface-group-name __ port_portid_ 」の形式で指定します

+
例：

+
[listing]
----
network port ifgrp remove-port -node node1 -ifgrp a1a -port e0d
----
.. ブロードキャストドメインから VLAN ポートとインターフェイスグループポートを削除します。
+
'network port broadcast-domain remove-ports -ipspace_ipspace -broadcast-domain_domain-name_ports_nodename ： portname 、 nodename ： portname _ 、

.. 必要に応じて、他の物理ポートをメンバーとして使用するようにインターフェイスグループポートを変更します。
+
ifgrp add-port -node node_name -ifgrp _interface -group-name_port_port-id_`



. ノードを停止します。
+
halt -inhibit-takeover true -node node_name `

+
この手順は両方のノードで実行する必要があります。





=== 新しいコントローラをセットアップする

新しいコントローラをラックに設置してケーブルを接続する必要があります。

.手順
. 必要に応じて、新しいコントローラモジュールとストレージシェルフの配置を計画します。
+
ラックスペースは、コントローラモジュールのプラットフォームモデル、スイッチのタイプ、構成内のストレージシェルフ数によって異なります。

. 自身の適切な接地対策を行います
. コントローラモジュールをラックまたはキャビネットに設置します。
+
https://["AFF と FAS ドキュメントセンター"^]

. 新しいコントローラモジュールに固有の FC-VI カードがない場合、および古いコントローラの FC-VI カードに新しいコントローラの互換性がある場合は、 FC-VI カードを交換し、正しいスロットに取り付けます。
+
を参照してください link:https://hwu.netapp.com["NetApp Hardware Universe の略"^] を参照してください。

. コントローラの電源、シリアルコンソール、および管理接続を、 MetroCluster インストールおよび設定ガイド _ の説明に従ってケーブル接続します。
+
この時点で古いコントローラから切断されていた他のケーブルは接続しないでください。

+
https://["AFF と FAS ドキュメントセンター"^]

. 新しいノードに電源を投入し、 LOADER プロンプトを表示するよう求められたら Ctrl+C キーを押します。




=== 新しいコントローラのネットブート

新しいノードを設置したら、ネットブートを実行して、新しいノードが元のノードと同じバージョンの ONTAP を実行するようにする必要があります。ネットブートという用語は、リモート・サーバに保存された ONTAP イメージからブートすることを意味します。ネットブートの準備を行うときは、システムがアクセスできる Web サーバに、 ONTAP 9 ブート・イメージのコピーを配置する必要があります。

このタスクは、新しい各コントローラモジュールで実行します。

.手順
. にアクセスします https://["ネットアップサポートサイト"^] システムのネットブートの実行に使用するファイルをダウンロードするには、次の手順を実行します。
. ネットアップサポートサイトのソフトウェアダウンロードセクションから該当する ONTAP ソフトウェアをダウンロードし、 Web にアクセスできるディレクトリに image.tgz ファイルを保存します。
. Web にアクセスできるディレクトリに移動し、必要なファイルが利用可能であることを確認します。
+
ディレクトリの一覧に、カーネルファイル ONTAP-version image.tgz のネットブートフォルダが含まれている必要があります

+
image.tgz ファイルを展開する必要はありません。

. LOADER プロンプトで、管理 LIF のネットブート接続を設定します。
+
** IP アドレスが DHCP の場合は、自動接続を設定します。
+
ifconfig e0M -auto

** IP アドレスが静的な場合は、手動接続を設定します。
+
ifconfig e0M -addr= ip_addr-mask= netmask `-gw= gateway `



. ネットブートを実行します。
+
** プラットフォームが 80xx シリーズシステムの場合は、次のコマンドを使用します。
+
netboot\http://web_server_ip/path_to_web-accessible_directory/netboot/kernel`

** プラットフォームが他のシステムの場合は、次のコマンドを使用します。
+
netboot\http://web_server_ip/path_to_web-accessible_directory/ontap-version_image.tgz`



. ブートメニューからオプション * （ 7 ） Install new software first * を選択し、新しいソフトウェアイメージをダウンロードしてブートデバイスにインストールします。
+
 Disregard the following message: "This procedure is not supported for Non-Disruptive Upgrade on an HA pair". It applies to nondisruptive upgrades of software, not to upgrades of controllers.
. 手順を続行するかどうかを確認するメッセージが表示されたら、「 y 」と入力し、パッケージの入力を求められたらイメージファイルの URL 「 ¥ http://web_server_ip/path_to_web-accessible_directory/ontap-version_image.tgz` 」を入力します
+
....
Enter username/password if applicable, or press Enter to continue.
....
. 次のようなプロンプトが表示されたら 'n' を入力してバックアップ・リカバリをスキップしてください
+
....
Do you want to restore the backup configuration now? {y|n}
....
. 次のようなプロンプトが表示されたら 'y' と入力して再起動します
+
....
The node must be rebooted to start using the newly installed software. Do you want to reboot now? {y|n}
....




=== コントローラモジュールでの設定の消去

[role="lead"]
MetroCluster 構成で新しいコントローラモジュールを使用する前に、既存の構成をクリアする必要があります。

.手順
. 必要に応じて、ノードを停止して LOADER プロンプトを表示します。
+
「 halt 」

. LOADER プロンプトで、環境変数をデフォルト値に設定します。
+
「デフォルト設定」

. 環境を保存します。
+
'aveenv

. LOADER プロンプトで、ブートメニューを起動します。
+
「 boot_ontap menu

. ブートメニューのプロンプトで、設定を消去します。
+
wipeconfig

+
確認プロンプトに「 yes 」と応答します。

+
ノードがリブートし、もう一度ブートメニューが表示されます。

. ブートメニューでオプション * 5 * を選択し、システムをメンテナンスモードでブートします。
+
確認プロンプトに「 yes 」と応答します。





=== HBA 構成をリストアしています

コントローラモジュールに HBA カードが搭載されているかどうかや設定によっては、サイトで使用するために正しく設定する必要があります。

.手順
. メンテナンスモードで、システム内の HBA の設定を行います。
+
.. ucadmin show と入力し、各ポートの現在の設定を確認します
.. 必要に応じてポートの設定を更新します。


+
|===


| HBA のタイプと目的のモード | 使用するコマンド 


 a| 
CNA FC
 a| 
ucadmin modify -m fc -t initiator_adapter-name _ `



 a| 
CNA イーサネット
 a| 
ucadmin modify -mode cna_adapter-name_`



 a| 
FC ターゲット
 a| 
fcadmin config -t target_adapter-name_`



 a| 
FC イニシエータ
 a| 
fcadmin config -t initiator_adapter-name_`

|===
. メンテナンスモードを終了します。
+
「 halt 」

+
コマンドの実行後、ノードが LOADER プロンプトで停止するまで待ちます。

. ノードをブートしてメンテナンスモードに戻り、設定の変更が反映されるようにします。
+
「 boot_ontap maint 」を使用してください

. 変更内容を確認します。
+
|===


| HBA のタイプ | 使用するコマンド 


 a| 
CNA
 a| 
ucadmin show



 a| 
FC
 a| 
fcadmin show`

|===




=== 新しいコントローラとシャーシで HA 状態を設定

コントローラとシャーシの HA 状態を確認し、必要に応じてシステム構成に合わせて更新する必要があります。

.手順
. メンテナンスモードで、コントローラモジュールとシャーシの HA 状態を表示します。
+
「 ha-config show 」

+
すべてのコンポーネントの HA 状態は「 mccip 」である必要があります。

. 表示されたコントローラまたはシャーシのシステム状態が正しくない場合は、 HA 状態を設定します。
+
「 ha-config modify controller mccip 」を参照してください

+
「 ha-config modify chassis mccip 」を参照してください

. ノードを停止します
+
ノードは 'loader>` プロンプトで停止する必要があります

. 各ノードで、システムの日付、時刻、およびタイムゾーンを確認します。「 show date 」
. 必要に応じて 'UTC または GMT:'set date <mm/dd/yyyy>' で日付を設定します
. ブート環境プロンプトで次のコマンドを使用して ' 時刻を確認します
. 必要に応じて、時刻を UTC または GMT:' 設定時刻 <:hh:mm:ss>` で設定します
. 設定を保存します： saveenv
. 環境変数 :printenv' を収集します




=== 新しいプラットフォームに対応できるようにスイッチの RCF ファイルを更新します

スイッチは、新しいプラットフォームモデルをサポートする構成に更新する必要があります。

.このタスクについて
このタスクは、現在アップグレード中のコントローラを含むサイトで実行します。この手順の例では、まず site_B をアップグレードします。

site_A のコントローラをアップグレードすると、 site_A のスイッチがアップグレードされます。

.手順
. 新しい RCF ファイルを適用するための IP スイッチを準備します。
+
MetroCluster IP のインストールと設定セクションに記載されているスイッチベンダーの手順に従ってください。

+
link:../install-ip/index.html["MetroCluster IP のインストールと設定"]

+
** link:../install-ip/task_switch_config_broadcom.html#resetting-the-broadcom-ip-switch-to-factory-defaults["Broadcom IP スイッチを工場出荷時のデフォルトにリセット"]
** link:../install-ip/task_switch_config_broadcom.html#resetting-the-cisco-ip-switch-to-factory-defaults["Cisco IP スイッチを工場出荷時のデフォルトにリセットする"]


. RCF ファイルをダウンロードしてインストールします。
+
使用しているスイッチベンダーに対応する手順については、を参照してください link:../install-ip/index.html["MetroCluster IP のインストールと設定"]。

+
** link:../install-ip/task_switch_config_broadcom.html#downloading-and-installing-the-broadcom-rcf-files["Broadcom の RCF ファイルのダウンロードとインストール"]
** link:../install-ip/task_switch_config_broadcom.html#downloading-and-installing-the-cisco-ip-rcf-files["Cisco IP RCF ファイルのダウンロードとインストール"]






=== MetroCluster の bootarg IP 変数を設定します

新しいコントローラモジュールには特定の MetroCluster IP bootarg 値を設定する必要があります。これらの値は、古いコントローラモジュールに設定されている値と一致する必要があります。

.このタスクについて
このタスクでは、のアップグレード手順で前述した UUID とシステム ID を使用します link:task_upgrade_controllers_in_a_four_node_ip_mcc_us_switchover_and_switchback_mcc_ip.html#gathering-information-before-the-upgrade["アップグレード前に情報を収集"]。

.手順
. 「 LOADER> 」プロンプトで、 site_B の新しいノードで次のブート引数を設定します。
+
'etenvarge.MCC.port_a_ip_config_local-ip-address/local-ip-mask'0 、 ha-partner-ip-address 、 dr-partner-ip-address 、 dr-aux-partnerip-address 、 vlan-id_`

+
「 etenvarge.MCC.port_b_ip_config_local-ip-address/local-ip-mask, 0,ha-partner-ip-address 、 dr-partner-ip-address 、 dr-aux-partnerip-address 、 vlan-id_` 」を指定します

+
次の例は、1つ目のネットワークにVLAN 120、2つ目のネットワークにVLAN 130を使用して、node_B_1の値を設定します。

+
[listing]
----
setenv bootarg.mcc.port_a_ip_config 172.17.26.10/23,0,172.17.26.11,172.17.26.13,172.17.26.12,120
setenv bootarg.mcc.port_b_ip_config 172.17.27.10/23,0,172.17.27.11,172.17.27.13,172.17.27.12,130
----
+
次の例は、1つ目のネットワークにVLAN 120、2つ目のネットワークにVLAN 130を使用してnode_B_2の値を設定します。

+
[listing]
----
setenv bootarg.mcc.port_a_ip_config 172.17.26.11/23,0,172.17.26.10,172.17.26.12,172.17.26.13,120
setenv bootarg.mcc.port_b_ip_config 172.17.27.11/23,0,172.17.27.10,172.17.27.12,172.17.27.13,130
----
. 新しいノードの LOADER プロンプトで ' UUID を設定します
+
「 etenv bootarg.mgwd.partner_uuid_partner -cluster-UUID_` 」と入力します

+
「 etenv bootarg.mgwd.cluster_ue_local-cluster-UUID_` 」と入力します

+
「 etenv bootarge.MCC.pri_partner_uuid_dr-partner -node-UUID_` 」と入力します

+
'etenv bootarg.mcc.aux_partner_uuid _dr-au-partner -UUID_`

+
「 etenv bootarg.mcc_iscsi.node_uuid _local-node-UUID_` 」と入力します

+
.. node_B_1のUUIDを設定します。
+
次の例は、node_B_1のUUIDを設定するコマンドを示しています。

+
[listing]
----
setenv bootarg.mgwd.cluster_uuid ee7db9d5-9a82-11e7-b68b-00a098908039
setenv bootarg.mgwd.partner_cluster_uuid 07958819-9ac6-11e7-9b42-00a098c9e55d
setenv bootarg.mcc.pri_partner_uuid f37b240b-9ac1-11e7-9b42-00a098c9e55d
setenv bootarg.mcc.aux_partner_uuid bf8e3f8f-9ac4-11e7-bd4e-00a098ca379f
setenv bootarg.mcc_iscsi.node_uuid f03cb63c-9a7e-11e7-b68b-00a098908039
----
.. node_B_2のUUIDを設定します。
+
次の例は、node_B_2のUUIDを設定するコマンドを示しています。

+
[listing]
----
setenv bootarg.mgwd.cluster_uuid ee7db9d5-9a82-11e7-b68b-00a098908039
setenv bootarg.mgwd.partner_cluster_uuid 07958819-9ac6-11e7-9b42-00a098c9e55d
setenv bootarg.mcc.pri_partner_uuid bf8e3f8f-9ac4-11e7-bd4e-00a098ca379f
setenv bootarg.mcc.aux_partner_uuid f37b240b-9ac1-11e7-9b42-00a098c9e55d
setenv bootarg.mcc_iscsi.node_uuid aa9a7a7a-9a81-11e7-a4e9-00a098908c35
----


. 元のシステムが ADP 用に設定されていた場合は、交換用ノードの LOADER プロンプトで ADP を有効にします。
+
'etenv bootarg.me.adp_enabled true

. 次の変数を設定します。
+
「 etenv bootarg.me.local_config_id_original-sys-sys-id_` 」を返します

+
「 etenv bootarge.MCC.DR_PARTNER_DR-partner -sys-id_` 」を選択します

+

NOTE: 。 `setenv bootarg.mcc.local_config_id` 変数には、*元の*コントローラモジュールnode_B_1のシステムIDを設定する必要があります。

+
.. node_B_1の変数を設定します。
+
次の例は、node_B_1の値を設定するコマンドを示しています。

+
[listing]
----
setenv bootarg.mcc.local_config_id 537403322
setenv bootarg.mcc.dr_partner 537403324
----
.. node_B_2の変数を設定します。
+
次の例は、node_B_2の値を設定するコマンドを示しています。

+
[listing]
----
setenv bootarg.mcc.local_config_id 537403321
setenv bootarg.mcc.dr_partner 537403323
----


. 外部キー管理ツールで暗号化を使用する場合は、必要な bootargs を設定します。
+
「 etenv bootarg.kmip.init.ipaddr` 」を参照してください

+
「 etenv bootarg.kmip.kmip.init.netmask` 」を参照してください

+
「 etenv bootarg.kmip.kmip.init.gateway` 」を参照してください

+
「 etenv bootarg.kmip.kmip.init.interface` 」を参照してください





=== ルートアグリゲートディスクの再割り当て中です

前の手順で確認した「 sysconfig 」を使用して、ルートアグリゲートディスクを新しいコントローラモジュールに再割り当てします

.このタスクについて
このタスクはメンテナンスモードで実行します。

古いシステム ID は、で識別されています link:task_upgrade_controllers_system_control_commands_in_a_four_node_mcc_ip.html#gathering-information-before-the-upgrade["アップグレード前に情報を収集"]。

この手順の例では、次のシステム ID を持つコントローラを使用します。

|===


| ノード | 古いシステム ID | 新しいシステム ID 


 a| 
node_B_1
 a| 
4068741254
 a| 
1574774970

|===
.手順
. 他のすべての接続を新しいコントローラモジュール（ FC-VI 、ストレージ、クラスタインターコネクトなど）にケーブル接続します。
. システムを停止し、 LOADER プロンプトからメンテナンスモードでブートします。
+
「 boot_ontap maint 」を使用してください

. node_B_1 古いが所有するディスクを表示します。
+
「ディスクショー - A` 」

+
コマンド出力に、新しいコントローラモジュール（ 1574774970 ）のシステム ID が表示されます。ただし、ルートアグリゲートディスクは古いシステム ID （ 4068741254 ）で所有されます。この例で表示されているのは、 MetroCluster 構成の他のノードが所有するドライブではありません。

+
[listing]
----
*> disk show -a
Local System ID: 1574774970

  DISK         OWNER                     POOL   SERIAL NUMBER    HOME                      DR HOME
------------   -------------             -----  -------------    -------------             -------------
...
rr18:9.126L44 node_B_1-old(4068741254)   Pool1  PZHYN0MD         node_B_1-old(4068741254)  node_B_1-old(4068741254)
rr18:9.126L49 node_B_1-old(4068741254)   Pool1  PPG3J5HA         node_B_1-old(4068741254)  node_B_1-old(4068741254)
rr18:8.126L21 node_B_1-old(4068741254)   Pool1  PZHTDSZD         node_B_1-old(4068741254)  node_B_1-old(4068741254)
rr18:8.126L2  node_B_1-old(4068741254)   Pool0  S0M1J2CF         node_B_1-old(4068741254)  node_B_1-old(4068741254)
rr18:8.126L3  node_B_1-old(4068741254)   Pool0  S0M0CQM5         node_B_1-old(4068741254)  node_B_1-old(4068741254)
rr18:9.126L27 node_B_1-old(4068741254)   Pool0  S0M1PSDW         node_B_1-old(4068741254)  node_B_1-old(4068741254)
...
----
. ドライブシェルフのルートアグリゲートディスクを新しいコントローラに再割り当てします。
+
「ディスクの再割り当て -s _old-sysid_-d_new-sysid_`

+

NOTE: MetroCluster IPシステムにアドバンストディスクパーティショニングが設定されている場合は、を実行してDRパートナーシステムIDを含める必要があります `disk reassign -s old-sysid -d new-sysid -r dr-partner-sysid` コマンドを実行します

+
次の例は、ドライブの再割り当てを示しています。

+
[listing]
----
*> disk reassign -s 4068741254 -d 1574774970
Partner node must not be in Takeover mode during disk reassignment from maintenance mode.
Serious problems could result!!
Do not proceed with reassignment if the partner is in takeover mode. Abort reassignment (y/n)? n

After the node becomes operational, you must perform a takeover and giveback of the HA partner node to ensure disk reassignment is successful.
Do you want to continue (y/n)? Jul 14 19:23:49 [localhost:config.bridge.extra.port:error]: Both FC ports of FC-to-SAS bridge rtp-fc02-41-rr18:9.126L0 S/N [FB7500N107692] are attached to this controller.
y
Disk ownership will be updated on all disks previously belonging to Filer with sysid 4068741254.
Do you want to continue (y/n)? y
----
. すべてのディスクが想定どおりに再割り当てされていることを確認します。
+
「ディスクショー」

+
[listing]
----
*> disk show
Local System ID: 1574774970

  DISK        OWNER                      POOL   SERIAL NUMBER   HOME                      DR HOME
------------  -------------              -----  -------------   -------------             -------------
rr18:8.126L18 node_B_1-new(1574774970)   Pool1  PZHYN0MD        node_B_1-new(1574774970)  node_B_1-new(1574774970)
rr18:9.126L49 node_B_1-new(1574774970)   Pool1  PPG3J5HA        node_B_1-new(1574774970)  node_B_1-new(1574774970)
rr18:8.126L21 node_B_1-new(1574774970)   Pool1  PZHTDSZD        node_B_1-new(1574774970)  node_B_1-new(1574774970)
rr18:8.126L2  node_B_1-new(1574774970)   Pool0  S0M1J2CF        node_B_1-new(1574774970)  node_B_1-new(1574774970)
rr18:9.126L29 node_B_1-new(1574774970)   Pool0  S0M0CQM5        node_B_1-new(1574774970)  node_B_1-new(1574774970)
rr18:8.126L1  node_B_1-new(1574774970)   Pool0  S0M1PSDW        node_B_1-new(1574774970)  node_B_1-new(1574774970)
*>
----
. アグリゲートのステータスを表示します。
+
「 aggr status 」を入力します

+
[listing]
----
*> aggr status
           Aggr            State       Status           Options
aggr0_node_b_1-root        online      raid_dp, aggr    root, nosnap=on,
                           mirrored                     mirror_resync_priority=high(fixed)
                           fast zeroed
                           64-bit
----
. パートナーノードで上記の手順を繰り返します（ node_B_2 - 新規）。




=== 新しいコントローラのブート

コントローラのフラッシュイメージを更新するには、ブートメニューからコントローラをリブートする必要があります。暗号化が設定されている場合は、追加の手順が必要です。

VLAN とインターフェイスグループを再設定できます。必要に応じて、「 system controller replace resume 」コマンドを使用して処理を再開する前に、クラスタ LIF とブロードキャストドメインのポートを手動で変更します。

.このタスクについて
このタスクはすべての新しいコントローラで実行する必要があります。

.手順
. ノードを停止します。
+
「 halt 」

. 外部キー管理ツールが設定されている場合は、関連する bootargs を設定します。
+
'setenv bootarg.kmip.init.ipaddr _ip-address_'

+
'setenv bootarg.kmip.init.netmask _netmask_`

+
'setenv bootarg.kmip.init.gateway _gateway-address_

+
'setenv bootarg.kmip.init.interface _interface-id_

. ブートメニューを表示します。
+
「 boot_ontap menu

. ルート暗号化を使用する場合は、キー管理設定のブートメニューオプションを選択します。
+
|===


| 使用するポート | 選択するブートメニューオプション 


 a| 
オンボードキー管理
 a| 
オプション "10 `"

プロンプトに従って、キー管理ツールの構成をリカバリおよびリストアするために必要な入力を指定します。



 a| 
外部キー管理
 a| 
オプション "11`"

プロンプトに従って、キー管理ツールの構成をリカバリおよびリストアするために必要な入力を指定します。

|===
. ブートメニューからオプション "6`" を実行します
+

NOTE: オプション "6`" を選択すると ' 完了前にノードが 2 回再起動されます

+
システム ID 変更プロンプトに「 y 」と入力します。2 回目のリブートメッセージが表示されるまで待ちます。

+
[listing]
----
Successfully restored env file from boot media...

Rebooting to load the restored env file...
----
+
オプション"`6`"の後のいずれかの再起動中に、確認プロンプトが表示されます `Override system ID? {y|n}` 表示されます。入力するコマンド `y`。

. ルート暗号化を使用する場合は、キー管理設定のブートメニューオプションを再度選択します。
+
|===


| 使用するポート | 選択するブートメニューオプション 


 a| 
オンボードキー管理
 a| 
オプション "10 `"

プロンプトに従って、キー管理ツールの構成をリカバリおよびリストアするために必要な入力を指定します。



 a| 
外部キー管理
 a| 
オプション "11`"

プロンプトに従って、キー管理ツールの構成をリカバリおよびリストアするために必要な入力を指定します。

|===
+
キー・マネージャの設定に応じて '10 またはオプション 11 を選択し ' 最初のブート・メニュー・プロンプトでオプション 6 を選択して 'recovery 手順を実行しますノードを完全にブートするには ' オプション "1" によって続行されるリカバリ手順 ( 通常のブート ) を繰り返す必要がある場合があります

. ノードをブートします。
+
「 boot_ontap 」

. 交換したノードがブートするまで待ちます。
+
いずれかのノードがテイクオーバーモードの場合は、「 storage failover giveback 」コマンドを使用してギブバックを実行します。

. すべてのポートがブロードキャストドメインに属していることを確認します。
+
.. ブロードキャストドメインを表示します。
+
「 network port broadcast-domain show 」

.. 必要に応じて、ブロードキャストドメインにポートを追加します。
+
https://["ブロードキャストドメインのポートの追加と削除"^]

.. インタークラスタLIFをホストする物理ポートを対応するブロードキャストドメインに追加します。
.. 新しい物理ポートをホームポートとして使用するようにクラスタ間 LIF を変更します。
.. クラスタ間 LIF が起動したら、クラスタピアのステータスを確認し、必要に応じてクラスタピアリングを再確立します。
+
クラスタピアリングの再設定が必要になる場合があります。

+
link:../install-ip/task_sw_config_configure_clusters.html#peering-the-clusters["クラスタピア関係を作成"]

.. 必要に応じて、 VLAN とインターフェイスグループを再作成します。
+
VLAN およびインターフェイスグループのメンバーシップは、古いノードと異なる場合があります。

+
https://["VLAN を作成する"^]

+
https://["物理ポートを組み合わせたインターフェイスグループの作成"^]

.. パートナークラスタが到達可能であり、パートナークラスタで設定が再同期されたことを確認します。
+
`metrocluster switchback -simulate true`



. 暗号化を使用する場合は、キー管理設定に対応したコマンドを使用してキーをリストアします。
+
|===


| 使用するポート | 使用するコマンド 


 a| 
オンボードキー管理
 a| 
「セキュリティキーマネージャオンボード同期」

詳細については、を参照してください https://["オンボードキー管理の暗号化キーのリストア"^]。



 a| 
外部キー管理
 a| 
「 securitykey manager external restore -vserver _svm_-node __ key -server_host_name | ip_address ： port_-key-id key_id -key tag key_tag_node-name_ 」

詳細については、を参照してください https://["外部キー管理の暗号化キーのリストア"^]。

|===
. 処理を再開する前に、 MetroCluster が正しく設定されていることを確認してください。ノードのステータスを確認します。
+
MetroCluster node show

+
新しいノード（ site_B ）の状態が「 Waiting for switchback state * from site_A 」であることを確認します

. 処理を再開します。
+
「システムコントローラの交換が再開」





== アップグレードを完了します

自動処理では、検証システムのチェックが実行されたあと一時停止するため、ネットワークの到達可能性を確認できます。検証が完了すると、リソースの再取得フェーズが開始され、自動化処理によってサイト A でスイッチバックが実行され、アップグレード後のチェックで一時停止されます。自動処理を再開すると、アップグレード後のチェックが実行され、エラーが検出されない場合はアップグレードが完了としてマークされます。

.手順
. コンソールメッセージに従って、ネットワークの到達可能性を確認します。
. 検証が完了したら、処理を再開します。
+
「システムコントローラの交換が再開」

. 自動化処理が実行されます `heal-aggregate`、 `heal-root-aggregate`、サイトAでのスイッチバック処理、およびアップグレード後のチェックが実行されます。処理が一時停止した場合は、コンソールメッセージに従って SAN LIF のステータスを手動で確認し、ネットワーク設定を確認します。
. 検証が完了したら、処理を再開します。
+
「システムコントローラの交換が再開」

. アップグレード後チェックのステータスを確認します。
+
「 system controller replace show 」と表示されます

+
アップグレード後のチェックでエラーが報告されなかった場合、アップグレードは完了です。

. コントローラのアップグレードが完了したら、サイト B でログインし、交換したコントローラが正しく設定されていることを確認します。




=== ONTAP メディエーターを再設定します

アップグレードを開始する前に自動的に削除されたONTAP メディエーターを手動で設定します。

. の手順を使用します link:../install-ip/task_configuring_the_ontap_mediator_service_from_a_metrocluster_ip_configuration.html["MetroCluster IP 構成から ONTAP メディエーターサービスを設定します"]。




=== Tiebreaker 監視をリストアしています

MetroCluster 構成が Tiebreaker ソフトウェアで監視するように設定されている場合は、 Tiebreaker 接続をリストアできます。

. の手順を使用します http://["MetroCluster 構成を追加しています"]。

