---
permalink: upgrade/task-expand-four-to-eight-mcc-fc.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, create, mirrored, data, aggregate, node 
summary: DR グループの各ノードに、ミラーされたデータアグリゲートを 1 つ作成する必要があります。 
---
= 各MetroCluster FCノードでミラーリングされたデータ アグリゲートを作成します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
DR グループの各ノードに、ミラーされたデータアグリゲートを 1 つ作成する必要があります。

.このタスクについて
* 新しいアグリゲートで使用するドライブを把握しておく必要があります。
* システムに複数のドライブ タイプがある場合（異機種混在ストレージ）、正しいドライブ タイプが選択されていることを確認する方法を理解しておく必要があります。
* ドライブは特定のノードによって所有されます。アグリゲートを作成する場合、アグリゲート内のすべてのドライブは同じノードによって所有される必要があります。そのノードが、作成するアグリゲートのホームノードになります。
+
ADP を使用するシステムではパーティションを使用してアグリゲートが作成され、各ドライブがパーティション P1 、 P2 、 P3 に分割されます。

* アグリゲート名は、 MetroCluster 構成を計画する際に決定した命名規則に従う必要があります。
+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-psmg/home.html["ディスクおよびアグリゲートの管理"]

* アグリゲート名は、MetroClusterサイト全体で一意である必要があります。つまり、サイト A とサイト B に同じ名前を持つ 2 つの異なるデータ アグリゲートを持つことはできません。



NOTE: 最適なストレージ パフォーマンスと可用性を確保するには、ミラー化されたアグリゲートに少なくとも 20% の空き領域を確保することをお勧めします。ミラーリングされていないアグリゲートの場合、推奨値は 10% ですが、追加の 10% のスペースは、増分変更を吸収するためにファイル システムによって使用できます。増分変更により、ONTAPのcopy-on-write Snapshotベースのアーキテクチャにより、ミラー化されたアグリゲートのスペース使用率が増加します。これらのベスト プラクティスに従わないと、パフォーマンスに悪影響が出る可能性があります。

.手順
. 使用可能なスペアのリストを表示します。
+
`storage disk show -spare -owner <node_name>`

. アグリゲートを作成します。
+
「 storage aggregate create -mirror true 」のようになります

+
クラスタ管理インターフェイスでクラスタにログインしている場合は、クラスタ内の任意のノードにアグリゲートを作成できます。特定のノードにアグリゲートが作成されていることを確認するには、 `-node`パラメータを使用するか、そのノードが所有するドライブを指定します。

+
次のオプションを指定できます。

+
** アグリゲートのホームノード（通常運用時にアグリゲートを所有するノード）
** アグリゲートに追加するドライブのリスト
** 追加するドライブ数
+

NOTE: 使用できるドライブ数が限られている最小サポート構成では、 force-small-aggregate オプションを使用して、 3 ディスクの RAID-DP アグリゲートを作成できるように設定する必要があります。

** アグリゲートに使用するチェックサム形式
** 使用するドライブのタイプ
** 使用するドライブのサイズ
** 使用するドライブの速度
** アグリゲート上の RAID グループの RAID タイプ
** RAID グループに含めることができるドライブの最大数
** RPM の異なるドライブが許可されるかどうか
+
これらのオプションの詳細については 'storage aggregate create のマニュアルページを参照してください

+
次のコマンドでは、 10 本のディスクを含むミラーアグリゲートが作成されます。

+
[listing]
----
cluster_A::> storage aggregate create aggr1_node_A_1 -diskcount 10 -node node_A_1 -mirror true
[Job 15] Job is queued: Create aggr1_node_A_1.
[Job 15] The job is starting.
[Job 15] Job succeeded: DONE
----


. 新しいアグリゲートの RAID グループとドライブを確認します。
+
`storage aggregate show-status -aggregate <aggregate-name>`


