---
permalink: upgrade/task_change_the_ha_config_setts_mcc_add_a_2nd_controller.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, change, ha, config, sett, existing, new, controller, modules 
summary: MetroCluster 構成を拡張する場合は、既存のコントローラモジュールと新しいコントローラモジュールの ha-config 設定を更新する必要があります。また、新しいコントローラモジュールのシステム ID も確認する必要があります。 
---
= 既存および新規のコントローラモジュールの ha-config 設定を変更します
:icons: font
:imagesdir: ../media/


[role="lead"]
MetroCluster 構成を拡張する場合は、既存のコントローラモジュールと新しいコントローラモジュールの ha-config 設定を更新する必要があります。また、新しいコントローラモジュールのシステム ID も確認する必要があります。

このタスクは、既存および新規の両方のコントローラモジュールでメンテナンスモードで実行します。

.手順
. 既存のコントローラモジュールの ha-config 設定を変更します。
+
.. 既存のコントローラモジュールとシャーシの ha-config 設定を表示します。
+
「 ha-config show 」

+
コントローラモジュールが 2 ノード MetroCluster 構成であったため、すべてのコンポーネントの ha-config 設定は「 m cc-2n 」です。

.. 既存のコントローラモジュールの ha-config 設定を「 `m cc`:+`ha-config modify controller mcc` 」に変更します
.. 既存のシャーシの ha-config 設定を「 mcc 」に変更します。
+
「 ha-config modify chassis mcc 」

.. 既存のコントローラモジュールのシステム ID を取得します。
+
「 sysconfig 」を使用できます

+
システム ID をメモします。新しいコントローラモジュールでパートナー ID を設定するときに必要になります。

.. メンテナンスモードを終了して LOADER プロンプトに戻ります。
+
「 halt 」



. ha-config 設定を変更し、新しいコントローラモジュールのシステム ID を取得します。
+
.. 新しいコントローラモジュールがまだメンテナンスモードになっていない場合は、メンテナンスモードでブートします。
+
「 boot_ontap maint 」を使用してください

.. 新しいコントローラモジュールの ha-config 設定を「 `m cc` 」に変更します。
+
「 ha-config modify controller mcc 」

.. 新しいシャーシの ha-config 設定を mcc に変更します。
+
「 ha-config modify chassis mcc 」

.. 新しいコントローラモジュールのシステム ID を取得します。
+
「 sysconfig 」を使用できます

+
システム ID をメモします。パートナー ID を設定し、新しいコントローラモジュールにディスクを割り当てる際に必要になります。

.. メンテナンスモードを終了して LOADER プロンプトに戻ります。
+
「 halt 」




