---
permalink: upgrade/task_verify_the_health_of_the_mcc_configuration.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, health, verify, conofiguration 
summary: MetroCluster 構成の健全性をチェックして、正常に動作することを確認する必要があります。 
---
= MetroCluster 構成の健全性の確認
:icons: font
:imagesdir: ../media/


[role="lead"]
MetroCluster 構成の健全性をチェックして、正常に動作することを確認する必要があります。

.手順
. 各クラスタで MetroCluster が設定されており、通常モードであることを確認します。
+
「 * MetroCluster show * 」と入力します

+
[listing]
----
cluster_A::> metrocluster show
Cluster                   Entry Name          State
------------------------- ------------------- -----------
 Local: cluster_A         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-cluster-disaster
Remote: cluster_B         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-cluster-disaster
----
. 各ノードでミラーリングが有効であることを確認します。
+
'*MetroCluster node show*

+
[listing]
----
cluster_A::> metrocluster node show
DR                           Configuration  DR
Group Cluster Node           State          Mirroring Mode
----- ------- -------------- -------------- --------- --------------------
1     cluster_A
              node_A_1       configured     enabled   normal
      cluster_B
              node_B_1       configured     enabled   normal
2 entries were displayed.
----
. MetroCluster コンポーネントが正常であることを確認します。
+
「 * MetroCluster check run * 」のようになります

+
[listing]
----
cluster_A::> metrocluster check run

Last Checked On: 10/1/2014 16:03:37

Component           Result
------------------- ---------
nodes               ok
lifs                ok
config-replication  ok
aggregates          ok
4 entries were displayed.

Command completed. Use the "metrocluster check show -instance" command or sub-commands in "metrocluster check" directory for detailed results.
To check if the nodes are ready to do a switchover or switchback operation, run "metrocluster switchover -simulate" or "metrocluster switchback -simulate", respectively.
----
. ヘルスアラートがないことを確認します。
+
「 * system health alert show * 」というメッセージが表示されます

. スイッチオーバー処理をシミュレートします。
+
.. いずれかのノードのプロンプトで、 advanced 権限レベルに切り替えます。 +`* set -privilege advanced *`
+
advanced モードで続けるかどうかを尋ねられたら、「 * y * 」と入力して応答する必要があります。 advanced モードのプロンプトが表示されます（ * > ）。

.. simulate パラメータを指定して、スイッチオーバー操作を実行します。 +`* MetroCluster switchover -simulate *`
.. admin 特権レベルに戻ります :+`*set -privilege admin*`



