---
permalink: upgrade/task_power_up_both_controller_modules_and_display_the_loader_prompt_2_node_mcc_expansion.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, power, up, controller. modules, display, loader, prompt 
summary: 既存のコントローラモジュールと新しいコントローラモジュールの電源をオンにして LOADER プロンプトを表示します。 
---
= 両方のコントローラモジュールの電源投入と LOADER プロンプトの表示
:icons: font
:imagesdir: ../media/


[role="lead"]
既存のコントローラモジュールと新しいコントローラモジュールの電源をオンにして LOADER プロンプトを表示します。

構成に対応した手順で、コントローラモジュールの電源をオンにしてブートプロセスを中断します。

[cols="25,75"]
|===


| コントローラモジュールの場所 | 作業 


 a| 
同じシャーシ内
 a| 
. 新しいコントローラモジュールがベイに * 完全に挿入されていない * ことを確認します。
+
既存のコントローラモジュールはシャーシから取り外されていないため、ベイに完全に挿入する必要がありますが、新しいコントローラモジュールは完全に挿入しないでください。

. 電源を接続し、電源装置をオンにして、既存のコントローラモジュールに電力を供給します。
. Ctrl+C を押して、既存のコントローラモジュールのブートプロセスを中断します
. 新しいコントローラモジュールをベイにしっかりと押し込みます。
+
新しいコントローラモジュールが完全に収まると、電力が供給されて自動的にブートします。

. Ctrl+C を押してブートプロセスを中断します
. カムハンドルの取り付けネジがある場合は、締めます。
. ケーブルマネジメントデバイスがある場合は、取り付けます。
. ケーブルマネジメントデバイスに接続されているケーブルをフックとループストラップでまとめます。




 a| 
別のシャーシに搭載
 a| 
. 既存のコントローラモジュールの電源装置をオンにします。
. Ctrl+C を押してブートプロセスを中断します
. 新しいコントローラモジュールについて、上記の手順を繰り返します


|===
各コントローラモジュールには、 LOADER プロンプト（「 LOADER>` 」、「 LOADER-A> 」、または「 LOADER-B>` ）が表示されます。


NOTE: LOADER プロンプトが表示されない場合は、エラーメッセージをメモし、テクニカルサポートに連絡してください。システムにブートメニューが表示された場合は、リブートし、もう一度ブートプロセスを中断します。
