---
permalink: upgrade/task_assign_disk_ownership_in_aff_systems_mcc.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, assign, disk, ownership, aff, systems 
summary: アグリゲートがミラーされた AFF システムを使用する構成で、ノードにディスク（ SSD ）が正しく割り当てられていない場合は、各シェルフの半分のディスクを 1 つのローカルノードに割り当て、残りの半分を対応する HA パートナーノードに割り当てる必要があります。構成内の各ノードのローカルディスクプールとリモートディスクプールでディスク数が同じになるように設定する必要があります。 
---
= AFF システムでディスク所有権を割り当てます
:icons: font
:imagesdir: ../media/


[role="lead"]
アグリゲートがミラーされた AFF システムを使用する構成で、ノードにディスク（ SSD ）が正しく割り当てられていない場合は、各シェルフの半分のディスクを 1 つのローカルノードに割り当て、残りの半分を対応する HA パートナーノードに割り当てる必要があります。構成内の各ノードのローカルディスクプールとリモートディスクプールでディスク数が同じになるように設定する必要があります。

ストレージコントローラがメンテナンスモードになっている必要があります。

これは、アグリゲートがミラーされていない構成、アクティブ / パッシブ構成、ローカルプールとリモートプールのディスク数が異なる構成には該当しません。

このタスクは、工場出荷時にディスクが正しく割り当てられている場合は必要ありません。


NOTE: プール 0 にはディスクを所有するストレージシステムと同じサイトにあるディスクを割り当て、プール 1 にはディスクを所有するストレージシステムに対してリモートなディスクを割り当てます。

.手順
. システムをブートしていない場合は、メンテナンスモードでブートします。
. 最初のサイト（サイト A ）にあるノードにディスクを割り当てます。
+
各プールに同じ数のディスクを割り当てる必要があります。

+
.. 最初のノードで、各シェルフの半分のディスクをプール 0 に、残りの半分を HA パートナーのプール 0 に割り当てます。 +`* disk assign -disk disk_name _p_pool_-n _number -of disks _*`
+
ストレージコントローラ Controller_A_1 にシェルフが 4 台あり、各シェルフに SSD が 8 本ある場合は、次のコマンドを問題に設定します。

+
[listing]
----
*> disk assign -shelf FC_switch_A_1:1-4.shelf1 -p 0 -n 4
*> disk assign -shelf FC_switch_A_1:1-4.shelf2 -p 0 -n 4

*> disk assign -shelf FC_switch_B_1:1-4.shelf1 -p 1 -n 4
*> disk assign -shelf FC_switch_B_1:1-4.shelf2 -p 1 -n 4
----
.. ローカルサイトの 2 番目のノードに対して処理を繰り返し、各シェルフの半分のディスクをプール 1 に、残りの半分を HA パートナーのプール 1 に割り当てます。 +`* disk assign -disk disk_name _p_pool_*`
+
ストレージコントローラ Controller_A_1 にシェルフが 4 台あり、各シェルフに SSD が 8 本ある場合は、次のコマンドを問題に設定します。

+
[listing]
----
*> disk assign -shelf FC_switch_A_1:1-4.shelf3 -p 0 -n 4
*> disk assign -shelf FC_switch_B_1:1-4.shelf4 -p 1 -n 4

*> disk assign -shelf FC_switch_A_1:1-4.shelf3 -p 0 -n 4
*> disk assign -shelf FC_switch_B_1:1-4.shelf4 -p 1 -n 4
----


. 2 番目のサイト（サイト B ）にあるノードにディスクを割り当てます。
+
各プールに同じ数のディスクを割り当てる必要があります。

+
.. リモートサイトの最初のノードで、各シェルフの半分のディスクをプール 0 に、残りの半分を HA パートナーのプール 0 に割り当てます。 +`* disk assign -disk disk_name _p_pool_*`
+
ストレージコントローラ Controller_B_1 にシェルフが 4 台あり、各シェルフに SSD が 8 本ある場合は、次のコマンドを問題で実行します。

+
[listing]
----
*> disk assign -shelf FC_switch_B_1:1-5.shelf1 -p 0 -n 4
*> disk assign -shelf FC_switch_B_1:1-5.shelf2 -p 0 -n 4

*> disk assign -shelf FC_switch_A_1:1-5.shelf1 -p 1 -n 4
*> disk assign -shelf FC_switch_A_1:1-5.shelf2 -p 1 -n 4
----
.. リモートサイトの 2 番目のノードに対して処理を繰り返し、各シェルフの半分のディスクをプール 1 に、残りの半分を HA パートナーのプール 1 に割り当てます。 +`* disk assign -disk disk_name _p_pool_*`
+
ストレージコントローラ Controller_B_2 にシェルフが 4 台あり、各シェルフに SSD が 8 本ある場合は、次のコマンドを問題に設定します。

+
[listing]
----
*> disk assign -shelf FC_switch_B_1:1-5.shelf3 -p 0 -n 4
*> disk assign -shelf FC_switch_B_1:1-5.shelf4 -p 0 -n 4

*> disk assign -shelf FC_switch_A_1:1-5.shelf3 -p 1 -n 4
*> disk assign -shelf FC_switch_A_1:1-5.shelf4 -p 1 -n 4
----


. ディスクの割り当てを確認します。
+
'*storage show disk *

. メンテナンスモードを終了します。
+
*halt *`

. ブートメニューを表示します。
+
「 * boot_ontap menu * 」のようになります

. 各ノードで、オプション * 4 * を選択してすべてのディスクを初期化します。

