---
permalink: upgrade/upgrade-mcc-ip-system-controller-replace-boot-new-controllers.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, controllers, switchover, switchback, ip, configuration, net, boot, root, aggregate, system, commands, mcc 
summary: ブートメニューからコントローラをリブートして、コントローラのフラッシュイメージを更新します。暗号化が設定されている場合は、追加の手順が必要です。 
---
= 新しいMetroCluster IPコントローラのブートとLIF設定のリストア
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
コマンドを使用して新しいコントローラをブートし、LIFが適切なノードとポートでホストされていることを確認してから、処理を再開し `system controller replace resume`ます。



== 新しいコントローラのブート

新しいコントローラをブートし、bootarg変数が正しいことを確認し、必要に応じて暗号化のリカバリ手順を実行します。

.このタスクについて
このタスクはすべての新しいコントローラで実行する必要があります。

.手順
. ノードを停止します。
+
「 halt 」

. 外部キー管理ツールが設定されている場合は、関連する bootargs を設定します。
+
`setenv bootarg.kmip.init.ipaddr <ip-address>`

+
`setenv bootarg.kmip.init.netmask <netmask>`

+
`setenv bootarg.kmip.init.gateway <gateway-address>`

+
`setenv bootarg.kmip.init.interface <interface-id>`

. ブートメニューを表示します。
+
「 boot_ontap menu

. ルート暗号化を使用する場合は、キー管理設定のブートメニューオプションを選択します。
+
|===


| 使用するポート | 選択するブートメニューオプション 


 a| 
オンボードキー管理
 a| 
オプション "10 `"

プロンプトに従って、キー管理ツールの構成をリカバリおよびリストアするために必要な入力を指定します。



 a| 
外部キー管理
 a| 
オプション "11`"

プロンプトに従って、キー管理ツールの構成をリカバリおよびリストアするために必要な入力を指定します。

|===
. ブートメニューからオプション "6`" を実行します
+

NOTE: オプション「6」は、プロセスが完了する前にノードを2回リブートします。

+
システムIDの変更プロンプトに「y」と入力します。2回目のリブートメッセージが表示されるまで待ちます。

+
[listing]
----
Successfully restored env file from boot media...

Rebooting to load the restored env file...
----
+
オプション"`6`"の後のいずれかの再起動中に、確認プロンプトが表示されます `Override system ID? {y|n}` 表示されます。入力するコマンド `y`。

. ルート暗号化を使用する場合は、キー管理設定のブートメニューオプションを再度選択します。
+
|===


| 使用するポート | 選択するブートメニューオプション 


 a| 
オンボードキー管理
 a| 
オプション "10 `"

プロンプトに従って、キー管理ツールの構成をリカバリおよびリストアするために必要な入力を指定します。



 a| 
外部キー管理
 a| 
オプション "11`"

プロンプトに従って、キー管理ツールの構成をリカバリおよびリストアするために必要な入力を指定します。

|===
+
キー・マネージャの設定に応じて '10 またはオプション 11 を選択し ' 最初のブート・メニュー・プロンプトでオプション 6 を選択して 'recovery 手順を実行しますノードを完全にブートするには ' オプション "1" によって続行されるリカバリ手順 ( 通常のブート ) を繰り返す必要がある場合があります

. ノードをブートします。
+
「 boot_ontap 」

. 交換したノードがブートするまで待ちます。
+
いずれかのノードがテイクオーバーモードの場合は、「 storage failover giveback 」コマンドを使用してギブバックを実行します。

. すべてのポートがブロードキャストドメインに属していることを確認します。
+
.. ブロードキャストドメインを表示します。
+
「 network port broadcast-domain show 」

.. 新しくアップグレードしたコントローラのデータポート用に新しいブロードキャストドメインを作成する場合は、そのブロードキャストドメインを削除します。
+

NOTE: 新しいブロードキャストドメインだけを削除します。アップグレードを開始する前に存在していたブロードキャストドメインは削除しないでください。

+
`broadcast-domain delete -broadcast-domain <broadcast_domain_name>`

.. 必要に応じて、ブロードキャストドメインにポートを追加します。
+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-nmg/GUID-003BDFCD-58A3-46C9-BF0C-BA1D1D1475F9.html["ブロードキャストドメインのポートを追加または削除します"^]

.. インタークラスタLIFをホストする物理ポートを対応するブロードキャストドメインに追加します。
.. 新しい物理ポートをホームポートとして使用するようにクラスタ間 LIF を変更します。
.. クラスタ間 LIF が起動したら、クラスタピアのステータスを確認し、必要に応じてクラスタピアリングを再確立します。
+
クラスタピアリングの再設定が必要になる場合があります。

+
link:../install-ip/task_sw_config_configure_clusters.html#peering-the-clusters["クラスタピア関係を作成します。"]

.. 必要に応じて、 VLAN とインターフェイスグループを再作成します。
+
VLAN およびインターフェイスグループのメンバーシップは、古いノードと異なる場合があります。

+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-nmg/GUID-8929FCE2-5888-4051-B8C0-E27CAF3F2A63.html["VLANを作成します。"^]

+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-nmg/GUID-DBC9DEE2-EAB7-430A-A773-4E3420EE2AA1.html["物理ポートを組み合わせてインターフェイスグループを作成"^]

.. パートナークラスタが到達可能であり、パートナークラスタで設定が再同期されたことを確認します。
+
`metrocluster switchback -simulate true`



. 暗号化を使用する場合は、キー管理設定に対応したコマンドを使用してキーをリストアします。
+
|===


| 使用するポート | 使用するコマンド 


 a| 
オンボードキー管理
 a| 
「セキュリティキーマネージャオンボード同期」

詳細については、を参照してください https://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-nve/GUID-E4AB2ED4-9227-4974-A311-13036EB43A3D.html["オンボードキー管理暗号化キーのリストア"^]。



 a| 
外部キー管理
 a| 
`security key-manager external restore -vserver <svm-name> -node <node-name> -key-server <host_name|IP_address:port> -key-id <key_id> -key-tag key_tag <node-name>`

詳細については、を参照してください https://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-nve/GUID-32DA96C3-9B04-4401-92B8-EAF323C3C863.html["外部キー管理の暗号化キーのリストア"^]。

|===
. MetroClusterが正しく設定されていることを確認します。ノードのステータスを確認します。
+
MetroCluster node show

+
新しいノード（ site_B ）の状態が「 Waiting for switchback state * from site_A 」であることを確認します





== LIF の設定を確認してリストア

自動スイッチバック処理を開始する前に、LIFが適切なノードでホストされていることを確認してください。

.このタスクについて
* このタスクは site_B で実行します



CAUTION: スイッチバックを実行する前に、新しいノードでデータLIFの場所が正しいことを確認する必要があります。構成をスイッチバックすると、ONTAPはLIFで使用されているホームポートでトラフィックの再開を試みます。スイッチポートおよびVLANへのホームポート接続が正しくないと、I/O障害が発生する可能性があります。

.手順
. スイッチバックの前に、LIFが適切なノードとポートでホストされていることを確認します。
+
.. advanced 権限レベルに切り替えます。
+
「 advanced 」の権限が必要です

.. LIFを表示し、各データLIFが正しいホームポートを使用していることを確認します。
+
「 network interface show 」を参照してください

.. 正しいホームポートを使用していないLIFを変更します。
+
`network interface modify -vserver <svm-name> -lif <data-lif> -home-port <port-id>`

+
コマンドからエラーが返された場合は、ポート設定を上書きできます。

+
`vserver config override -command "network interface modify -vserver <svm-name> -home-port <active_port_after_upgrade> -lif <lif_name> -home-node <new_node_name>"`

+
vserver config override コマンドで network interface modify コマンドを入力した場合は、 tab autoccomplete 機能を使用することはできません。autoccomplete を使用してネットワーク 'interface modify' を作成してから 'vserver config override' コマンドで囲むことができます

.. すべてのデータLIFが正しいホームポートにあることを確認します。
+
「 network interface show 」を参照してください

.. admin 権限レベルに戻ります。
+
「特権管理者」



. インターフェイスをホームノードにリバートします。
+
`network interface revert * -vserver <svm-name>`

+
必要に応じて、すべての SVM でこの手順を実行します。

. 処理を再開します。
+
「システムコントローラの交換が再開」



.次の手順
link:upgrade-mcc-ip-system-controller-replace-complete-upgrade.html["コントローラのアップグレードの完了"]です。
