---
permalink: upgrade/upgrade-mcc-ip-manual-set-bootarg.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, controllers, switchover, switchback, ip, configuration, net, boot, root, aggregate, system, commands, mcc, bootarg 
summary: ONTAP 9.15.1以降で導入されたシステムをアップグレードする場合は、コントローラのアップグレードに進む前にbootargを設定する必要があります。 
---
= 必要なbootargの設定（ONTAP 9.15.1以降で導入されたシステムへのMetroCluster IPのアップグレードの場合）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.15.1 以降で導入されたシステムにアップグレードする場合は、通常、アップグレードを開始する前に、古いコントローラで bootarg を設定する必要があります。


NOTE: アップグレードの組み合わせが影響を受ける場合、アップグレードを成功させるには、すべての古いコントローラーで bootarg を設定する必要があります。このセクションの情報を注意深く確認して、アップグレードの組み合わせで bootarg を設定する必要があるかどうか、また組み合わせに対して正しい bootarg を設定する方法を確認してください。



== ステップ1: 古いコントローラにbootargを設定する必要があるかどうかを確認します

アップグレードを開始する前に、必要な bootarg を設定する必要があるかどうかを確認するには、次の情報を参照してください。

* 特に明記されていない限り、以下のシステムへのサポートされているアップグレードでは、古いコントローラに bootarg を設定する必要があります。
+
** AFF A70、AFF A90、AFF A1K
** FAS70、FAS90
** AFF C80用
** AFF A50、AFF A20、AFF A30
** AFF C30、AFF C60
** FAS50


* アップグレードが次のいずれかの組み合わせである場合、古いコントローラーで bootarg を設定する必要はありません。
+
** AFF A70システムからAFF A90システムへ
** FAS70システムからFAS90システムへ





CAUTION: アップグレードでbootargを設定する必要がない場合は、このタスクをスキップして直接link:upgrade-mcc-ip-prepare-system.html["システムのアップグレードを準備"]。



== ステップ2: 古いコントローラに設定するbootargを決定する

影響を受けるアップグレードのほとんどは、 `hw.cxgbe.toe_keepalive_disable`古いコントローラ上の bootarg。ただし、特定のアップグレードパスでは、 `bootarg.siw.interop_enabled`代わりに bootarg を使用してください。

次の表を参照して、それぞれのアップグレードの組み合わせに設定する必要があるbootargを特定してください。

[cols="2*"]
|===
| アップグレード対象 | bootargの設定 


| AFF A250からAFF A30へ | `bootarg.siw.interop_enabled` 


| AFF C250からAFF C30へ | `bootarg.siw.interop_enabled` 


| AFF A150からAFF A20へ | `bootarg.siw.interop_enabled` 


| AFF A220からAFF A20へ | `bootarg.siw.interop_enabled` 


 a| 
AFF A70、 AFF A90、 AFF A1K、FAS70、FAS90、 AFF C80、 AFF A50、 AFF A30、 AFF C30、 AFF C60、またはFAS50システムへのその他のすべてのアップグレード

*注:* AFF A70システムからAFF A90システム、または FAS70 システムから FAS90 システムへのアップグレードの場合は、bootarg を設定する必要はありません。
| `hw.cxgbe.toe_keepalive_disable` 
|===


== ステップ3: 古いコントローラに必要なbootargを設定する

アップグレードの組み合わせに必要な bootarg を決定したら、手順に従って古いコントローラーで bootarg を設定します。このタスクは、影響を受けるアップグレードに対してのみ必要です。


NOTE: アップグレードを開始する前に、両方のサイトのすべての古いノードで bootarg を設定する必要があります。

.手順
. 両方のサイトで一方のノードを停止し、そのHAパートナーでノードのストレージテイクオーバーを実行できるようにします。
+
`halt  -node <node_name>`

. アップグレードの組み合わせに必要なbootargを設定します。の表を使用して、設定する必要があるbootargを決めておき<<upgrade_paths_bootarg_manual,設定が必要なbootargを特定する>>ます。
+
[role="tabbed-block"]
====
.hw.cxgbe.toe_keepalive_disable
--
..  `LOADER`停止したノードのプロンプトで、次のように入力します。
+
`setenv hw.cxgbe.toe_keepalive_disable 1`

+
'aveenv

+
`printenv hw.cxgbe.toe_keepalive_disable`



--
.bootarg.siw.interop_enabled
--
..  `LOADER`停止したノードのプロンプトで、次のように入力します。
+
`setenv bootarg.siw.interop_enabled 1`

+
'aveenv

+
`printenv bootarg.siw.interop_enabled`



--
====
. ノードをブートします。
+
「 boot_ontap 」

. ノードがブートしたら、プロンプトでノードのギブバックを実行します。
+
`storage failover giveback -ofnode <node_name>`

. アップグレードするDRグループまたはDRグループ内のすべてのノードで、この手順を繰り返します。


.次の手順
link:upgrade-mcc-ip-prepare-system.html["システムのアップグレードを準備"]です。
