---
permalink: upgrade/upgrade-mcc-ip-manual-boot-new-controllers.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, controllers, switchover, switchback, ip, configuration, net, boot, root, aggregate, system, commands, mcc 
summary: 新しいコントローラをブートし、LIFが適切なノードとポートでホストされていることを確認します。 
---
= 新しいMetroCluster IPコントローラのブートとLIF設定のリストア
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
新しいコントローラをブートし、LIFが適切なノードとポートでホストされていることを確認します。



== 新しいコントローラのブート

新しいコントローラをブートする必要があります。 bootarg 変数が正しいことを確認し、必要に応じて暗号化のリカバリ手順を実行するように注意してください。

.手順
. 新しいノードを停止します。
+
「 halt 」

. 外部キー管理ツールが設定されている場合は、関連する bootargs を設定します。
+
`setenv bootarg.kmip.init.ipaddr <ip-address>`

+
`setenv bootarg.kmip.init.netmask <netmask>`

+
`setenv bootarg.kmip.init.gateway <gateway-addres>`

+
`setenv bootarg.kmip.init.interface <interface-id>`

. partner-sysid が現在のものかどうかを確認します。
+
printenv partner-sysid

+
partner-sysid が正しくない場合は、次のように設定します。

+
`setenv partner-sysid <partner-sysID>`

. ONTAP ブートメニューを表示します。
+
「 boot_ontap menu

. ルート暗号化を使用する場合は、キー管理設定のブートメニューオプションを選択します。
+
|===


| 使用するポート | 選択するブートメニューオプション 


 a| 
オンボードキー管理
 a| 
オプション 10

プロンプトに従って、キー管理ツールの構成をリカバリおよびリストアするために必要な入力を指定します。



 a| 
外部キー管理
 a| 
オプションは 11 です

プロンプトに従って、キー管理ツールの構成をリカバリおよびリストアするために必要な入力を指定します。

|===
. 起動メニューから「 (6) Update flash from backup config 」を選択します。
+

NOTE: オプション6では、プロセスが完了する前にノードが2回リブートされます。

+
システムIDの変更プロンプトに「y」と入力します。2回目のリブートメッセージが表示されるまで待ちます。

+
[listing]
----
Successfully restored env file from boot media...

Rebooting to load the restored env file...
----
.  `LOADER`プロンプトで、bootargの値を確認し、必要に応じて値を更新します。
+
の手順を使用しますlink:upgrade-mcc-ip-manual-apply-rcf-set-bootarg.html#set-the-metrocluster-ip-bootarg-variables["MetroCluster の bootarg IP 変数を設定します"]。

. パートナーシステムIDが正しいことを確認します。
+
printenv partner-sysid

+
partner-sysid が正しくない場合は、次のように設定します。

+
`setenv partner-sysid <partner-sysID>`

. ルート暗号化を使用する場合は、キー管理設定のブートメニューオプションを再度選択します。
+
|===


| 使用するポート | 選択するブートメニューオプション 


 a| 
オンボードキー管理
 a| 
オプション 10

プロンプトに従って、キー管理ツールの構成をリカバリおよびリストアするために必要な入力を指定します。



 a| 
外部キー管理
 a| 
オプション "11`"

プロンプトに従って、キー管理ツールの構成をリカバリおよびリストアするために必要な入力を指定します。

|===
+
キー・マネージャの設定に応じて '10 またはオプション 11 を選択し ' 最初のブート・メニュー・プロンプトでオプション 6 を選択して 'Recovery 手順を実行しますノードを完全にブートするには ' オプション "1" によって続行されるリカバリ手順 ( 通常のブート ) を繰り返す必要がある場合があります

. 交換したノードがブートするまで待ちます。
+
いずれかのノードがテイクオーバーモードの場合は、「 storage failover giveback 」コマンドを使用してギブバックを実行します。

. 暗号化を使用する場合は、キー管理設定に対応したコマンドを使用してキーをリストアします。
+
|===


| 使用するポート | 使用するコマンド 


 a| 
オンボードキー管理
 a| 
「セキュリティキーマネージャオンボード同期」

詳細については、を参照してください https://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-nve/GUID-E4AB2ED4-9227-4974-A311-13036EB43A3D.html["オンボードキー管理暗号化キーのリストア"^]。



 a| 
外部キー管理
 a| 
`security key-manager external restore -vserver <SVM> -node <node> -key-server <host_name|IP_address:port> -key-id key_id -key-tag key_tag <node_name>`

詳細については、を参照してください https://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-nve/GUID-32DA96C3-9B04-4401-92B8-EAF323C3C863.html["外部キー管理の暗号化キーのリストア"^]。

|===
. すべてのポートがブロードキャストドメインに属していることを確認します。
+
.. ブロードキャストドメインを表示します。
+
「 network port broadcast-domain show 」

.. 新しくアップグレードしたコントローラのデータポート用に新しいブロードキャストドメインを作成する場合は、そのブロードキャストドメインを削除します。
+

NOTE: 新しいブロードキャストドメインだけを削除します。アップグレードの開始前に存在していたブロードキャストドメインは削除しないでください。

+
`broadcast-domain delete -broadcast-domain <broadcast_domain_name>`

.. 必要に応じてブロードキャストドメインにポートを追加します。
+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-nmg/GUID-003BDFCD-58A3-46C9-BF0C-BA1D1D1475F9.html["ブロードキャストドメインのポートを追加または削除します"^]

.. 必要に応じて、 VLAN とインターフェイスグループを再作成します。
+
VLANおよびインターフェイスグループのメンバーシップは、古いノードと異なる場合があります。

+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-nmg/GUID-8929FCE2-5888-4051-B8C0-E27CAF3F2A63.html["VLANを作成します。"^]

+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-nmg/GUID-DBC9DEE2-EAB7-430A-A773-4E3420EE2AA1.html["物理ポートを組み合わせてインターフェイスグループを作成"^]







== LIF の設定を確認してリストア

アップグレード手順の開始時にマッピングされた適切なノードとポートで LIF がホストされていることを確認します。

.このタスクについて
* このタスクは site_B で実行します
* で作成したポートマッピング計画を確認しますlink:upgrade-mcc-ip-prepare-system.html#map-ports-from-the-old-nodes-to-the-new-nodes["古いノードから新しいノードへのポートのマッピング"]。



CAUTION: スイッチバックを実行する前に、新しいノードでデータLIFの場所が正しいことを確認する必要があります。構成をスイッチバックすると、ONTAPはLIFで使用されているホームポートでトラフィックの再開を試みます。スイッチポートおよびVLANへのホームポート接続が正しくないと、I/O障害が発生する可能性があります。

.手順
. スイッチバックの前に、LIFが適切なノードとポートでホストされていることを確認します。
+
.. advanced 権限レベルに切り替えます。
+
「 advanced 」の権限が必要です

.. LIFを表示し、各データLIFが正しいホームポートを使用していることを確認します。
+
「 network interface show 」を参照してください

.. 正しいホームポートを使用していないLIFを変更します。
+
`network interface modify -vserver <svm-name> -lif <data-lif> -home-port <port-id>`

+
コマンドからエラーが返された場合は、ポート設定を上書きできます。

+
`vserver config override -command "network interface modify -vserver <svm-name> -home-port <active_port_after_upgrade> -lif <lif_name> -home-node <new_node_name>"`

+
vserver config override コマンドで network interface modify コマンドを入力した場合は、 tab autoccomplete 機能を使用することはできません。autoccomplete を使用してネットワーク 'interface modify' を作成してから 'vserver config override' コマンドで囲むことができます

.. すべてのデータLIFが正しいホームポートにあることを確認します。
+
「 network interface show 」を参照してください

.. admin 権限レベルに戻ります。
+
「特権管理者」



. インターフェイスをホームノードにリバートします。
+
`network interface revert * -vserver <svm-name>`

+
必要に応じて、すべての SVM でこの手順を実行します。



.次の手順
link:upgrade-mcc-ip-manual-switchback.html["MetroCluster構成のスイッチバック"]です。
