---
permalink: tiebreaker/concept_configuring_the_tiebreaker_software.html 
sidebar: sidebar 
keywords: installation, tiebreaker, software, add, modify, metrocluster, configuration, remove, configuring, configure, launch, cli, add, command, modify, removing 
summary: Tiebreaker ソフトウェアをインストールしたら、 MetroCluster 構成を追加または変更したり、 Tiebreaker ソフトウェアから削除したりできます。 
---
= MetroCluster Tiebreakerソフトウェアを構成する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Tiebreaker ソフトウェアをインストールしたら、 MetroCluster 構成を追加または変更したり、 Tiebreaker ソフトウェアから削除したりできます。



== TiebreakerソフトウェアCLIを起動する

Tiebreakerソフトウェアをインストールしたら、CLIを起動してソフトウェアを設定する必要があります。

. ソフトウェアをインストールしたホストのプロンプトから CLI を起動します。
+
NetApp-metrocluster-Tiebreaker software-cli

. インストール後および最初の起動時に、データベースにアクセスするためのTiebreakerユーザのパスワードを入力します。これは、インストール時にデータベースユーザに指定したパスワードです。




== MetroCluster 構成を追加

NetApp MetroCluster Tiebreaker ソフトウェアをインストールしたら、 MetroCluster 構成を 1 つずつ追加できます。

.このタスクについて
* ONTAP 環境に MetroCluster 構成をインストールし、ソフトウェアで設定を有効にしておく必要があります。
* 手順と予想されるコマンド出力は、実行している Tiebreaker のバージョンによって異なります。


[role="tabbed-block"]
====
.タイブレーカー 1.5 以前
--
.手順
. Tiebreaker コマンドラインインターフェイス（ CLI ）の monitor add コマンドを使用して、 MetroCluster の設定を追加します。
+
ホスト名を使用する場合は、完全修飾ドメイン名（ FQDN ）を指定する必要があります。

+
次の例は、 cluster_A の構成を示しています。

+
.例
[%collapsible]
=====
[listing]
----

NetApp MetroCluster Tiebreaker :> monitor add wizard
Enter monitor Name: <monitor_name>
Enter Cluster IP Address: <cluster_ip_value>
Enter Cluster Username: admin
Enter Cluster Password:
Enter Cluster IP Address: <peer_cluster_ip_value>
Enter Peer Cluster Username: admin
Enter Peer Cluster Password:
Successfully added monitor to NetApp MetroCluster Tiebreaker software.
----
=====
. Tiebreaker CLI の monitor show-status コマンドを使用して、 MetroCluster 構成が正しく追加されたことを確認します。
+
[listing]
----

NetApp MetroCluster Tiebreaker :> monitor show -status
----
. Tiebreaker ソフトウェアのオブザーバーモードを無効にして、サイト障害を検出したあとにスイッチオーバーを自動的に開始するようにします。
+
`monitor modify -monitor-name <monitor_name> -observer-mode false`

+
[listing]
----
NetApp MetroCluster Tiebreaker :> monitor modify -monitor-name 8pack -observer-mode false
Warning: If you are turning observer-mode to false, make sure to review the 'risks and limitations'
as described in the MetroCluster Tiebreaker installation and configuration.
Are you sure you want to enable automatic switchover capability for monitor "8pack"? [Y/N]: y
----


--
.Tiebreaker 1.6以降
--
.手順
. Tiebreaker コマンドラインインターフェイス（ CLI ）の monitor add コマンドを使用して、 MetroCluster の設定を追加します。
+
ホスト名を使用する場合は、完全修飾ドメイン名（ FQDN ）を指定する必要があります。

+
次の例は、 cluster_A の構成を示しています。

+
.例
[%collapsible]
=====
[listing]
----
NetApp MetroCluster Tiebreaker :> monitor add wizard
Enter Monitor Name: cluster_A
Enter Cluster IP Address: <cluster_ip_value>
Enter Cluster Username: admin
Enter Cluster Password:
Enter Peer Cluster IP Address: <peer_cluster_ip_value>
Enter Peer Cluster Username: admin
Enter Peer Cluster Password:

 NOTE: Before enabling automatic switchover capability, make sure to review the 'risks and limitations' as described in the MetroCluster Tiebreaker Installation and Configuration Guide.

Do you want to enable automatic switchover capability for monitor(Y/N): y
Successfully added monitor to NetApp MetroCluster Tiebreaker software.
Verifying SSL certificate chain from cluster_A...

===============================================
Warning missing SSL certificates
===============================================

Cluster: cluster_A

IP Address: <cluster_ip_value>

Result:

The MetroCluster Tiebreaker is unable to verify the SSL certificate chain.

Recommended Actions:

Run the following command to identify missing certificates:

monitor switchover-simulate

Import any missing certificates as indicated by the command output.

For detailed instructions, please refer to the MetroCluster Tiebreaker documentation, or contact NetApp Support for assistance.

Note:

Missing certificates will prevent the MetroCluster Tiebreaker from issuing a switchover request in the event of a site failure.

================================================================================================================================
Verifying SSL certificate chain from cluster_B...

SSL certificate chain is valid
----
=====
. Tiebreaker CLI の monitor show-status コマンドを使用して、 MetroCluster 構成が正しく追加されたことを確認します。
+
[listing]
----

NetApp MetroCluster Tiebreaker :> monitor show -status
----
. 不足している証明書を、Tiebreakerのバージョンに応じた手順でインポートします。<<import-certificates-tb17,証明書をインポートする>> 。


--
====
.関連情報
link:concept_risks_and_limitation_of_using_mcc_tiebreaker_in_active_mode.html["MetroCluster Tiebreaker をアクティブモードで使用する場合のリスクと制限事項"]



== 証明書をインポートする

Tiebreaker 1.6 以降でシームレスな監視を有効にするには、サーバの Secure Sockets Layer (SSL) 証明書、中間証明書 (存在する場合)、およびルート証明書をONTAPから Java 仮想マシン (JVM) のキー ストアにインポートする必要があります。

.このタスクについて
* このタスクは、Tiebreaker 1.6 以降で必須です。
* このタスクは、 MetroCluster構成を Tiebreaker に正常に追加した後、または証明書の有効期限が切れた後に実行します。
* Tiebreaker 1.7 以降では、スイッチオーバー シミュレーションを実行して、証明書をインポートする必要があるかどうかを確認できます。スイッチオーバー シミュレーションが失敗した場合は、 ONTAPから Java 仮想マシン (JVM) のキー ストアに証明書をインポートする必要があります。


[role="tabbed-block"]
====
.タイブレーカー 1.7 以降
--
.手順
. 切り替えシミュレーションを実行して、証明書をインポートする必要があるかどうかを確認します。
+
.. タイブレーカーの監視ステータスを確認します。
`monitor show -status`
+
.例
[%collapsible]
=====
[listing]
----
NetApp MetroCluster Tiebreaker :> monitor show -status
MetroCluster: A700
    Disaster: false
    Monitor State: Normal
    Observer Mode: false
    Silent Period: 5
    Override Vetoes: false
    Cluster: ClusterA_siteA(UUID:713e5ab2-b4e8-11f0-91aa-00a098ef36a2)
        Reachable: true
        Intersite Connectivity Available: true
            Node: node_A1(UUID:9f6cecbf-b4e4-11f0-9d0f-00a098ef36a2)
                Reachable: true
                Intersite Connectivity Available: true
                State: normal
            Node: node_A2(UUID:2719bb56-b4e7-11f0-996c-00a09897caa3)
                Reachable: true
                Intersite Connectivity Available: true
                State: normal
    Cluster: ClusterB_siteB(UUID:72839591-b4e8-11f0-b688-00a09897cb73)
        Reachable: true
        Intersite Connectivity Available: true
            Node: node_B1(UUID:abfeab89-b4e4-11f0-a077-00a09897cb73)
                Reachable: true
                Intersite Connectivity Available: true
                State: normal
            Node: node_B2(UUID:31e395bf-b4e7-11f0-bf99-00a09897cb2f)
                Reachable: true
                Intersite Connectivity Available: true
                State: normal
----
=====
.. 切り替えシミュレーションをトリガーします。
+
`monitor switchover-simulate -monitor-name <monitor_name> -cluster <cluster_name>`

+
JVM に証明書をインポートする必要がある場合、コマンドは次の出力を返します。

+
[listing]
----
Failed to trigger Switchover Simulation. Please check Metrocluster Tiebreaker logs for further information or contact NetApp support.
----


. インポートする必要がある証明書 (SSL サーバー、中間、またはルート) ごとに次のコマンドを実行します。
+
`/opt/netapp/java/bin/keytool -import -trustcacerts -file <certificate_file_name> -keystore "/opt/netapp/java/lib/security/cacerts" -alias <certificate>`

+
** その `<certificate_file_name>` 値には、インポートする証明書のファイル名を指定します。
** その `-alias <certificate>` 値は、証明書を JVM にインポートした後に証明書を保存する名前を指定します。
+
次の例は、ファイル名のルート証明書をインポートする方法を示しています。 `root.crt` ファイル名のSSLサーバー証明書 `ssl_cert.crt`:

+
[listing]
----
/opt/netapp/java/bin/keytool -import -trustcacerts -file root.crt -keystore "/opt/netapp/java/lib/security/cacerts" -alias root

/opt/netapp/java/bin/keytool -import -trustcacerts -file ssl_cert.crt -keystore "/opt/netapp/java/lib/security/cacerts" -alias ssl_cert
----


. Tiebreaker ソフトウェアを再起動します。
+
`systemctl restart netapp-metrocluster-tiebreaker-software`

. 切り替えシミュレーション チェックを再度実行します。
+
.. タイブレーカーの監視ステータスを確認します。
`monitor show -status`
+
.例
[%collapsible]
=====
[listing]
----
NetApp MetroCluster Tiebreaker :> monitor show -status
MetroCluster: A700
    Disaster: false
    Monitor State: Normal
    Observer Mode: false
    Silent Period: 5
    Override Vetoes: false
    Cluster: ClusterA_siteA(UUID:713e5ab2-b4e8-11f0-91aa-00a098ef36a2)
        Reachable: true
        Intersite Connectivity Available: true
            Node: node_A1(UUID:9f6cecbf-b4e4-11f0-9d0f-00a098ef36a2)
                Reachable: true
                Intersite Connectivity Available: true
                State: normal
            Node: node_A2(UUID:2719bb56-b4e7-11f0-996c-00a09897caa3)
                Reachable: true
                Intersite Connectivity Available: true
                State: normal
    Cluster: ClusterB_siteB(UUID:72839591-b4e8-11f0-b688-00a09897cb73)
        Reachable: true
        Intersite Connectivity Available: true
            Node: node_B1(UUID:abfeab89-b4e4-11f0-a077-00a09897cb73)
                Reachable: true
                Intersite Connectivity Available: true
                State: normal
            Node: node_B2(UUID:31e395bf-b4e7-11f0-bf99-00a09897cb2f)
                Reachable: true
                Intersite Connectivity Available: true
                State: normal
----
=====
.. 切り替えシミュレーションをトリガーします。
+
`monitor switchover-simulate -monitor-name <monitor_name> -cluster <cluster_name>`

+
[listing]
----
Successfully triggered Switchover Simulation. Please check the status of the Switchover Simulation on the ONTAP cluster using command "metrocluster operation history show"
----




--
.タイブレーカー 1.6 または 1.6P1
--
.手順
. ONTAPからすべての証明書をインポートします。インポートする必要がある証明書 (SSL サーバー、中間、またはルート) ごとに次のコマンドを実行します。
+
`/opt/netapp/java/bin/keytool -import -trustcacerts -file <certificate_file_name> -keystore "/opt/netapp/java/lib/security/cacerts" -alias <certificate>`

+
** その `<certificate_file_name>` 値には、インポートする証明書のファイル名を指定します。
** その `-alias <certificate>` 値は、証明書を JVM にインポートした後に証明書を保存する名前を指定します。
+
次の例は、ファイル名のルート証明書をインポートする方法を示しています。 `root.crt` ファイル名のSSLサーバー証明書 `ssl_cert.crt`:

+
[listing]
----
/opt/netapp/java/bin/keytool -import -trustcacerts -file root.crt -keystore "/opt/netapp/java/lib/security/cacerts" -alias root

/opt/netapp/java/bin/keytool -import -trustcacerts -file ssl_cert.crt -keystore "/opt/netapp/java/lib/security/cacerts" -alias ssl_cert
----


. Tiebreaker ソフトウェアを再起動します。
+
`systemctl restart netapp-metrocluster-tiebreaker-software`



--
====


== MetroCluster Tiebreaker 構成を変更するためのコマンド

MetroCluster 設定は、必要に応じていつでも変更できます。

Tiebreaker CLI の monitor modify コマンドは、次のいずれかのオプションで使用できます。変更を確認するには、 monitor show-status コマンドを使用します。

[cols="30,70"]
|===


| オプション | 説明 


 a| 
-monitor-name を指定します
 a| 
MetroCluster 設定の名前



 a| 
-enable-monitor
 a| 
MetroCluster 設定の監視を有効または無効にします



 a| 
- サイレント - 期間
 a| 
MetroCluster Tiebreaker ソフトウェアが検出後にサイト障害の確認を待機する秒数



 a| 
- オブザーバーモード
 a| 
オブザーバーモード（ true ）は監視するだけで、サイト障害が発生してもスイッチオーバーをトリガーしません。オンラインモード（ false ）は、サイト障害が発生した場合にスイッチオーバーをトリガーします。

* link:concept_overview_of_the_tiebreaker_software.html["Tiebreaker ソフトウェアでサイト障害を検出する方法"]
* link:concept_risks_and_limitation_of_using_mcc_tiebreaker_in_active_mode.html["MetroCluster Tiebreaker をアクティブモードで使用する場合のリスクと制限事項"]


|===
次の例は、構成のサイレント期間を変更します。

[listing]
----

NetApp MetroCluster Tiebreaker :> monitor modify -monitor-name cluster_A -silent-period 15
Successfully modified monitor in NetApp MetroCluster Tiebreaker
software.
----
Tiebreaker CLI の debug コマンドを使用して、ロギングモードを変更できます。

[cols="30,70"]
|===


| コマンドを実行します | 説明 


 a| 
デバッグステータス
 a| 
デバッグモードのステータスを表示します



 a| 
デバッグイネーブル
 a| 
ロギングのデバッグモードをイネーブルにします



 a| 
デバッグを無効にします
 a| 
ロギングのデバッグモードをディセーブルにします

|===
Tiebreaker 1.4以前を実行しているシステムではTiebreaker CLIです `update-mcctb-password` コマンドを使用すると、ユーザパスワードを更新できます。このコマンドはTiebreaker 1.5以降では廃止されています。

[cols="30,70"]
|===


| コマンドを実行します | 説明 


 a| 
update-mccb-password
 a| 
ユーザパスワードが更新されました

|===


== MetroCluster 構成を削除

MetroCluster 構成を監視する必要がなくなった場合は、 Tiebreaker ソフトウェアで監視している MetroCluster 設定を削除できます。

. MetroCluster 構成を削除するには 'Tiebreaker CLI の monitor remove コマンドを使用します
+
次の例では ' "cluster_a" がソフトウェアから削除されています

+
[listing]
----

NetApp MetroCluster Tiebreaker :> monitor remove -monitor-name cluster_A
Successfully removed monitor from NetApp MetroCluster Tiebreaker
software.
----
. Tiebreaker CLI の「 monitor show-status 」コマンドを使用して、 MetroCluster 設定が正しく削除されたことを確認します。
+
[listing]
----

NetApp MetroCluster Tiebreaker :> monitor show -status
----

