---
permalink: tiebreaker/reference_where_to_find_additional_information_tb_icg.html 
sidebar: sidebar 
keywords: metrocluster, configuration, operation, netapp, documentation, additional, information, miscellaneous, guide 
summary: MetroCluster の設定と処理の詳細については、を参照してください。 
---
= 追加情報の参照先
:icons: font
:imagesdir: ../media/


[role="lead"]
MetroCluster の設定と処理の詳細については、を参照してください。



== MetroCluster およびその他の情報

|===


| 情報 | 件名 


 a| 
link:../index.html["MetroCluster のドキュメント"]
 a| 
* すべての MetroCluster 情報




 a| 
http://www.netapp.com/us/media/tr-4375.pdf["ネットアップテクニカルレポート 4375 ：『 NetApp MetroCluster for ONTAP 9.3 』"^]
 a| 
* MetroCluster の設定と運用の技術概要
* MetroCluster 構成のベストプラクティス




 a| 
https://docs.netapp.com/us-en/ontap-metrocluster/install-fc/index.html["ファブリック接続 MetroCluster のインストールと設定"]
 a| 
* ファブリック接続 MetroCluster アーキテクチャ
* 構成のケーブル接続
* FC-to-SAS ブリッジの設定
* FC スイッチを設定します
* ONTAP で MetroCluster を設定します




 a| 
https://docs.netapp.com/us-en/ontap-metrocluster/install-stretch/concept_considerations_differences.html["ストレッチ MetroCluster のインストールと設定"]
 a| 
* ストレッチ MetroCluster アーキテクチャ
* 構成のケーブル接続
* FC-to-SAS ブリッジの設定
* ONTAP で MetroCluster を設定します




 a| 
https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_considerations_differences.html["MetroCluster IP のインストールと設定"]
 a| 
* MetroCluster IP アーキテクチャ
* MetroCluster IP 構成のケーブル接続
* ONTAP で MetroCluster を設定します




 a| 
https://docs.netapp.com/us-en/ontap-metrocluster/maintain/index.html["MetroCluster のコンポーネントをメンテナンスします"]
 a| 
* MetroCluster 構成のメンテナンスガイドライン
* FC-to-SAS ブリッジおよび FC スイッチのハードウェア交換 / アップグレードおよびファームウェアアップグレード手順
* ファブリック接続またはストレッチ MetroCluster 構成でのディスクシェルフのホットアド
* ファブリック接続またはストレッチ MetroCluster 構成でのディスクシェルフのホットリムーブ
* ファブリック接続またはストレッチ MetroCluster 構成のディザスタサイトでのハードウェア交換
* 2 ノードのファブリック接続またはストレッチ MetroCluster 構成の 4 ノード MetroCluster 構成への拡張
* 4 ノードのファブリック接続またはストレッチ MetroCluster 構成の 8 ノード MetroCluster 構成への拡張




 a| 
Active IQ Unified Manager のドキュメント

https://docs.netapp.com["ネットアップのマニュアル：製品ガイドとリソース"^]
 a| 
* MetroCluster の設定とパフォーマンスを監視する




 a| 
https://docs.netapp.com/us-en/ontap-7mode-transition/copy-based/index.html["コピーベースの移行"]
 a| 
* 7-Mode ストレージシステムから clustered Data ONTAP ストレージシステムへデータを移行する


|===