---
permalink: tiebreaker/task_configure_snmp_setts_for_tiebreaker_software.html 
sidebar: sidebar 
keywords: snmp, tiebreaker, software, configure, setting 
summary: Tiebreaker ソフトウェアで SNMP を使用するには、 SNMP を設定する必要があります。 
---
= Tiebreaker ソフトウェアの SNMP 設定
:icons: font
:imagesdir: ../media/


[role="lead"]
Tiebreaker ソフトウェアで SNMP を使用するには、 SNMP を設定する必要があります。

. Tiebreaker CLI の SNMP 設定ウィザードのコマンドを使用して、 MetroCluster 設定を追加します。
+

NOTE: 現在サポートされている SNMP トラップホストは 1 つだけです。

+
次の例は、 IP アドレスが 10.222.210.234 、トラップメッセージ用のポート番号が 162 、コミュニティストリングが public に設定された SNMP V1 をサポートする SNMP レシーバの構成を示しています。

+
....

NetApp MetroCluster Tiebreaker :> snmp config wizard
Enter SNMP Version [V1/V3]: V1
Enter SNMP Host: 10.222.210.234
Enter SNMP Port: 162
Enter SNMP V1 Community: public
Successfully added SNMP properties to NetApp MetroCluster Tiebreaker software.
NetApp MetroCluster Tiebreaker :>
....
+
これで、 Tiebreaker ソフトウェアは、指定した SNMP レシーバにトラップを送信することができます。

. SNMP が設定されたことを確認します。
+
「 snmp config test 」

+
次の例は、 Tiebreaker ソフトウェアがイベント test_snmp_config の SNMP トラップを送信できることを示しています。

+
....

NetApp MetroCluster Tiebreaker :> snmp config test
Sending SNMP trap to localhost. Version : V1.
Successfully sent SNMP trap for event TEST_SNMP_CONFIG
NetApp MetroCluster Tiebreaker :>
....

