---
permalink: install-fc/concept_port_assignments_for_systems_using_two_initiator_ports.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, port, assignments, systems, two, initiator, ports 
summary: FAS8020 、 AFF8020 、 FAS8200 、および AFF A300 システムは、ファブリックごとに 1 つのイニシエータポートとコントローラごとに 2 つのイニシエータポートを使用して設定できます。 
---
= 2 つのイニシエータポートを使用するシステムのポート割り当て
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FAS8020 、 AFF8020 、 FAS8200 、および AFF A300 システムは、ファブリックごとに 1 つのイニシエータポートとコントローラごとに 2 つのイニシエータポートを使用して設定できます。

FibreBridge 7500N / 7600Nブリッジのケーブル接続には、1つのFCポート（FC1またはFC2）のみを使用します。4 つのイニシエータのうち 2 つだけを接続し、スイッチポートに接続されている他の 2 つのイニシエータは空にしておきます。

ゾーニングを手動で実行する場合は、1つのFCポート（FC1またはFC2）を使用するFibreBridge 7500N / 7600Nブリッジのゾーニングに従います。このシナリオでは、各ファブリックのゾーンメンバーごとに 2 つではなく 1 つのイニシエータポートが追加されます。

の手順を使用して、ゾーニングを変更したり、FibreBridge 6500NからFibreBridge 7500Nへのアップグレードを実行したりできます。 link:../maintain/task_replace_a_sle_fc_to_sas_bridge.html#hot_swap_6500n["FibreBridge 6500N ブリッジと FibreBridge 7600N / 7500N ブリッジのホットスワップ"]。

次の表に、 ONTAP 9.1 以降を使用している場合の FC スイッチのポート割り当てを示します。

|===


4+| 1つのFCポート（FC1またはFC2）のみを使用するFibreBridge 7500N / 7600Nを使用する構成 


4+| * MetroCluster 1 または DR グループ 1 * 


.2+| * コンポーネント * .2+| * ポート * 2+| * Brocade スイッチモデル 6505 、 6510 、 6520 、 7840 、 G620 、 G610 、 DCX 8510-8 * 


| * FC スイッチに接続 * | * スイッチポートに接続 ... * 


.8+| controller_x_1  a| 
FC-VI ポート a
 a| 
1.
 a| 
0



 a| 
FC-VI ポート b
 a| 
2.
 a| 
0



 a| 
FC-VI ポート c
 a| 
1.
 a| 
1.



 a| 
FC-VI ポート d
 a| 
2.
 a| 
1.



 a| 
HBA ポート A
 a| 
1.
 a| 
2.



 a| 
HBA ポート b
 a| 
2.
 a| 
2.



 a| 
HBA ポート c
 a| 
-
 a| 
-



 a| 
HBA ポート d
 a| 
-
 a| 
-



 a| 
スタック 1
 a| 
bridge_x_1a
 a| 
1.
 a| 
8.



 a| 
bridge_x_1b
 a| 
2.
 a| 
8.



 a| 
スタック y
 a| 
bridge_x_ya
 a| 
1.
 a| 
11.



 a| 
bridge_x_YB
 a| 
2.
 a| 
11.

|===
次の表に、 ONTAP 9.0 を使用している場合の FC スイッチのポート割り当てを示します。

|===


4+| * MetroCluster 2 ノード構成 * 


.2+| * コンポーネント * .2+| * ポート * 2+| * Brocade 6505 、 6510 、または DCX 8510-8 * 


| * FC_switch_x_1 * | * FC_switch_x_2 * 


 a| 
controller_x_1
 a| 
FC-VI ポート a
 a| 
0
 a| 
-



 a| 
FC-VI ポート b
 a| 
-
 a| 
0



 a| 
HBA ポート A
 a| 
1.
 a| 
-



 a| 
HBA ポート b
 a| 
-
 a| 
1.



 a| 
HBA ポート c
 a| 
2.
 a| 
-



 a| 
HBA ポート d
 a| 
-
 a| 
2.

|===