---
permalink: install-fc/concept_AFF_A900_port_assign_fc_switches_ontap_9_1.html 
sidebar: sidebar 
keywords: AFF, A900, ONTAP, FAS, FC, Brocade, ISL, Cisco, metrocluster 
summary: ONTAP 9.1 以降を使用している場合、 FC スイッチをケーブル接続するときは、指定のポート割り当てを使用していることを確認する必要があります。 
---
= AFF A900またはFAS9500システムを使用する場合のFCスイッチのポート割り当て
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.10.1 以降を使用している場合に FC スイッチをケーブル接続するときは、指定のポート割り当てを使用していることを確認する必要があります。

イニシエータポート、 FC-VI ポート、または ISL の接続に使用しないポートは、ストレージポートとして機能するように再設定できます。ただし、サポートされている RCF を使用している場合は、それに応じてゾーニングを変更する必要があります。

サポートされている RCF を使用している場合、 ISL ポートの接続先が表示されるポートとは異なることがあり、手動での再設定が必要になることがあります。

ONTAP 9 のポート割り当てを使用してスイッチを設定した場合は、引き続き古い割り当てを使用できます。ただし、 ONTAP 9.1 以降のリリースを実行する新しい構成では、ここに示すポート割り当てを使用する必要があります。



== ケーブル接続の全体的なガイドライン

ケーブル接続の表を使用する際は、次の点に注意してください。

* AFF A900またはFAS9500ストレージシステムでは、FC-VIポートが8つ必要です。AFF A900またはFAS9500を使用している場合は、8つのポート構成を使用する必要があります。構成に他のストレージシステムモデルが含まれている場合は、表に示されているケーブル接続を使用し、不要な FC-VI ポートのケーブル接続は無視してください。
* 2 つの MetroCluster 構成で ISL を共有する場合は、 8 ノード MetroCluster のケーブル接続と同じポート割り当てを使用します。
* ケーブル接続する ISL の数は、サイトの要件によって異なります。
* ISL に関する考慮事項についてのセクションを参照してください。
+
link:concept_considerations_isls_mcfc.html["ISL に関する考慮事項"]


