---
permalink: install-fc/concept_required_mcc_components_and_naming_conventions_fabric_mcc.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, required, fc, components, naming, conventions 
summary: MetroCluster FC 構成を計画する際には、サポート対象の必要なハードウェアコンポーネントとソフトウェアコンポーネントを把握しておく必要があります。また、内容を正しく理解するためには、このドキュメントで使用しているコンポーネントの命名規則も確認しておく必要があります。たとえば、一方のサイトをサイト A と呼び、もう一方のサイトをサイト B と呼びます 
---
= 必要な MetroCluster FC コンポーネントと命名規則
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
MetroCluster FC 構成を計画する際には、サポート対象の必要なハードウェアコンポーネントとソフトウェアコンポーネントを把握しておく必要があります。また、内容を正しく理解するためには、このドキュメントで使用しているコンポーネントの命名規則も確認しておく必要があります。たとえば、一方のサイトをサイト A と呼び、もう一方のサイトをサイト B と呼びます



== サポートされているソフトウェアおよびハードウェア

ハードウェアとソフトウェアは、 MetroCluster FC 構成でサポートされている必要があります。

https://hwu.netapp.com["NetApp Hardware Universe の略"]

AFF システムを使用する場合は、 MetroCluster 構成内のすべてのコントローラモジュールを AFF システムとして構成する必要があります。


NOTE: MetroCluster ストレージスイッチでは長波 SFP がサポートされません。サポートされる SPF については、 MetroCluster テクニカルレポートを参照してください。



== MetroCluster FC 構成でのハードウェアの冗長性

MetroCluster FC 構成ではハードウェアの冗長性が確保されるため、サイトには各コンポーネントが 2 つずつあります。コンポーネントの名前には、サイトを表す A または B 、および 2 つあるコンポーネントのうちどちらかを表す番号として 1 または 2 を使用します。



== ONTAP クラスタ × 2

ファブリック接続 MetroCluster FC 構成には、 MetroCluster サイトごとに 1 つ、計 2 つの ONTAP クラスタが必要です。

名前は MetroCluster 構成内で一意である必要があります。

名前の例：

* サイト A ： cluster_A
* サイト B ： cluster_B




== FC スイッチ × 4

ファブリック接続 MetroCluster FC 構成には、 FC スイッチ（サポートされている Brocade または Cisco モデル）が 4 つ必要です。

4 つのスイッチが 2 つのスイッチストレージファブリックを形成し、 MetroCluster FC 構成の各クラスタ間の ISL を提供します。

名前は MetroCluster 構成内で一意である必要があります。



== コントローラモジュール × 2 、 4 、または 8

ファブリック接続 MetroCluster FC 構成には、コントローラモジュールが 2 つ、 4 つ、または 8 つ必要です。

4 ノードまたは 8 ノードの MetroCluster 構成では、各サイトのコントローラモジュールが 1 つまたは 2 つの HA ペアを形成します。各コントローラモジュールには、もう一方のサイトに DR パートナーがあります。

コントローラモジュールの要件は次のとおりです。

* 名前は MetroCluster 構成内で一意である必要があります。
* MetroCluster 構成のすべてのコントローラモジュールで同じバージョンの ONTAP が実行されている必要があります。
* 1 つの DR グループ内のすべてのコントローラモジュールのモデルが同じであることが必要です。
+
ただし、 2 つの DR グループ構成にする場合は、 DR グループごとに異なるモデルのコントローラモジュールで構成してもかまいません。

* 1 つの DR グループのすべてのコントローラモジュールで同じ FC-VI 構成を使用する必要があります。
+
一部のコントローラモジュールは、次の 2 つのオプションに対応しています。

+
** オンボードの FC-VI ポート
** スロット 1 の FC-VI カードオンボードの FC-VI ポートを使用するコントローラモジュールとアドオンの FC-VI カードを使用するコントローラモジュールが混在している場合は、サポートされません。たとえば、あるノードでオンボードの FC-VI 構成を使用する場合は、 DR グループの他のすべてのノードでもオンボードの FC-VI 構成を使用する必要があります。




名前の例：

* サイト A ： controller_A_1
* サイト B ： controller_B_1




== クラスタインターコネクトスイッチ × 4

ファブリック接続 MetroCluster FC 構成には、クラスタインターコネクトスイッチが 4 つ必要です（ 2 ノードスイッチレスクラスタを使用している場合は除く）。

これらのスイッチは、各クラスタのコントローラモジュール間のクラスタ通信を提供します。各サイトのコントローラモジュールが 2 ノードスイッチレスクラスタとして設定されている場合、これらのスイッチは必要ありません。



== FC-to-SAS ブリッジの要件

ファブリック接続 MetroCluster FC 構成には、 SAS シェルフのスタックグループごとに FC-to-SAS ブリッジのペアが 1 組必要です。


NOTE: ONTAP 9.8 以降を実行している構成では、 FibreBridge 6500N ブリッジはサポートされません。

* FibreBridge 7600N / 7500N ブリッジでは、最大 4 つの SAS スタックがサポートされます。
* 各スタックで異なる IOM のモデルを使用できます。
* 名前は MetroCluster 構成内で一意である必要があります。


このドキュメントで例として使用されている推奨名には、次のようにブリッジの接続先のコントローラモジュールとスタックが含まれています。



== プールとドライブの要件（最小サポート）

シェルフ単位でディスク所有権を割り当てられるようにするために、 SAS ディスクシェルフを 8 台（各サイトに 4 台）配置することを推奨します。

MetroCluster 構成では、各サイトに最小構成が必要です。

* 各ノードのサイトに少なくとも 1 つのローカルプールと 1 つのリモートプールがあります。
+
たとえば、各サイトにノードが 2 つある 4 ノード MetroCluster 構成では、各サイトにプールが 4 つ必要です。

* 各プールに少なくとも 7 本のドライブ。
+
各ノードにミラーされたデータアグリゲートが 1 つある 4 ノード MetroCluster 構成では、最小構成として 24 本のディスクがサイトに必要です。



サポートされる最小構成では、各プールのドライブレイアウトは次のようになります。

* ルートドライブ × 3 本
* 3 本のデータドライブ
* スペアドライブ x 1 本


サポートされる最小構成では、各サイトに少なくとも 1 台のシェルフが必要です。

MetroCluster 構成では、 RAID-DP と RAID 4 がサポートされます。



== 空きのあるシェルフでのドライブの配置場所に関する考慮事項

収容数が半分（ 24 ドライブシェルフに 12 本のドライブ）のシェルフを使用している場合にドライブの自動割り当てを正しく行うには、スロット 0~5 および 18~23 にドライブを配置する必要があります。

シェルフに空きがある構成では、シェルフの 4 つの部分にドライブを均等に配置する必要があります。



== ブリッジの命名規則

ブリッジでは、次のような命名規則を使用します。

ペア内の 'bridge_site_stack グループ・ロケーション

|===


| 名前の各部分 | 特定のインターフェイス | 有効な値 


 a| 
サイト
 a| 
ブリッジペアが物理的に配置されているサイト。
 a| 
A または B



 a| 
スタックグループ
 a| 
ブリッジペアが接続されているスタックグループの番号。

FibreBridge 7600N / 7500N ブリッジでは、スタックグループで最大 4 個のスタックがサポートされます。

スタックグループに含めることができるストレージシェルフは 10 個までです。
 a| 
1 、 2 など



 a| 
ペア内の場所
 a| 
ブリッジペア内のブリッジ。ブリッジのペアは、特定のスタックグループに接続します。
 a| 
a または b

|===
各サイトの 1 つのスタックグループのブリッジ名の例：

* bridge_A_1a
* bridge_A_1b
* bridge_B_1a
* bridge_B_1b

