---
permalink: install-fc/concept_port_assignments_for_systems_using_two_initiator_ports.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, port, assignments, systems, two, initiator, ports 
summary: FAS8020 、 AFF8020 、 FAS8200 、および AFF A300 システムは、ファブリックごとに 1 つのイニシエータポートとコントローラごとに 2 つのイニシエータポートを使用して設定できます。 
---
= 2 つのイニシエータポートを使用するシステムのポート割り当て
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
各ファブリックに 1 つのイニシエーター ポート、各コントローラーに 2 つのイニシエーター ポートを使用して、 FAS8200およびAFF A300システムを構成できます。

1 つの FC ポート (FC1 または FC2) のみを使用して、FibreBridge 7600N ブリッジのケーブル接続を実行できます。4つのあるイニシエータのうち2つだけを接続し、スイッチ ポートに接続されている他の2つのイニシエータは空にしておきます。

ゾーニングを手動で実行する場合は、1 つの FC ポート (FC1 または FC2) を使用する FibreBridge 7600N ブリッジに使用されるゾーニングに従います。この場合は、各ファブリックのゾーン メンバーごとに2つではなく1つのイニシエータ ポートが追加されます。

の手順を使用して、ゾーニングを変更したり、FibreBridge 6500NからFibreBridge 7500Nへのアップグレードを実行したりできます。 link:../maintain/task_replace_a_sle_fc_to_sas_bridge.html#hot_swap_6500n["FibreBridge 6500N ブリッジと FibreBridge 7600N / 7500N ブリッジのホットスワップ"]。

次の表は、ファブリックごとに 1 つのイニシエーター ポートを使用し、コントローラごとに 2 つのイニシエーター ポートを使用する場合のBrocade FC スイッチのポートの割り当てを示しています。

[cols="2a,2a,2a,2a"]
|===
4+| 1つのFCポート（FC1またはFC2）のみを使用するFibreBridge 7500N / 7600Nを使用する構成 


 a| 
* MetroCluster 1 または DR グループ 1 *



 a| 
* コンポーネント *
 a| 
* ポート *
 a| 
*6505、6510、6520、7840、G620、G630、G610、G710、G720、G730、DCX 8510-8*



 a| 
* FC スイッチに接続 *
 a| 
* スイッチポートに接続 ... *



 a| 
controller_x_1
 a| 
FC-VI ポート a
 a| 
1.
 a| 
0



 a| 
FC-VI ポート b
 a| 
2.
 a| 
0



 a| 
FC-VI ポート c
 a| 
1.
 a| 
1.



 a| 
FC-VI ポート d
 a| 
2.
 a| 
1.



 a| 
HBA ポート A
 a| 
1.
 a| 
2.



 a| 
HBA ポート b
 a| 
2.
 a| 
2.



 a| 
HBA ポート c
 a| 
-
 a| 
-



 a| 
HBA ポート d
 a| 
-
 a| 
-



 a| 
スタック 1
 a| 
bridge_x_1a
 a| 
1.
 a| 
8.



 a| 
bridge_x_1b
 a| 
2.
 a| 
8.



 a| 
スタック y
 a| 
bridge_x_ya
 a| 
1.
 a| 
11.



 a| 
bridge_x_YB
 a| 
2.
 a| 
11.

|===