---
permalink: install-fc/concept_considerations_for_implementing_a_mcc_configuration_with_disks_and_array_luns.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, considerations, configuration, disks, array, luns 
summary: ディスクとアレイ LUN を使用する MetroCluster 構成を計画するときは、ストレージへのアクセスのセットアップ順序、ルートアグリゲートの場所、 FC イニシエータポート、スイッチ、 FC-to-SAS ブリッジの使用など、さまざまな要素を考慮する必要があります。 
---
= ディスクとアレイ LUN を使用する MetroCluster 構成を実装する際の考慮事項
:icons: font
:imagesdir: ../media/


[role="lead"]
ディスクとアレイ LUN を使用する MetroCluster 構成を計画するときは、ストレージへのアクセスのセットアップ順序、ルートアグリゲートの場所、 FC イニシエータポート、スイッチ、 FC-to-SAS ブリッジの使用など、さまざまな要素を考慮する必要があります。

構成を計画するときは、次の表に示す情報を考慮してください。

|===
| 考慮事項 | ガイドライン 


 a| 
ストレージへのアクセスのセットアップ順序
 a| 
ディスクとアレイ LUN へのアクセスはどちらから先にセットアップしてもかまいません。一方のタイプのストレージのセットアップをすべて完了し、正しくセットアップされたことを確認してから、もう一方のタイプのストレージをセットアップする必要があります。



 a| 
ルートアグリゲートの場所
 a| 
* ディスクとアレイ LUN の両方を使用する _new_MetroCluster 環境をセットアップする場合は、ネイティブディスクにルートアグリゲートを作成する必要があります。
+
その場合は、各サイトに少なくとも 1 台のディスクシェルフ（ 24 本のディスクドライブを搭載）がセットアップされていることを確認してください。

* アレイ LUN を使用する既存の MetroCluster 構成にネイティブディスクを追加する場合は、ルートアグリゲートをアレイ LUN に配置したままでもかまいません。




 a| 
スイッチおよび FC-to-SAS ブリッジを使用
 a| 
4 ノード構成および 2 ノードファブリック接続構成で ONTAP システムをスイッチ経由でディスクシェルフと接続するには、 FC-to-SAS ブリッジが必要です。

ストレージアレイへの接続と FC-to-SAS ブリッジへの接続に同じスイッチを使用する必要があります。



 a| 
FC イニシエータポートを使用する
 a| 
FC-to-SAS ブリッジへの接続に使用されるイニシエータポートは、ストレージアレイに接続するスイッチへの接続に使用されるポートとは別でなければなりません。ONTAP システムをディスクとアレイ LUN の両方に接続するには、最低でも 8 つのイニシエータポートが必要です。

|===
* 関連情報 *

link:task_fcsw_configure_the_cisco_or_brocade_fc_switches_manually.html["Cisco または Brocade FC スイッチを手動で設定する"]

link:concept_example_of_switch_zoning_in_a_four_node_mcc_configuration_with_array_luns.html["アレイ LUN を使用する 4 ノード MetroCluster 構成におけるスイッチゾーニングの例"]

link:concept_example_of_switch_zoning_in_an_eight_node_mcc_configuration_with_array_luns.html["アレイ LUN を使用する 8 ノード MetroCluster 構成におけるスイッチゾーニング例"]

link:task_fb_new_install.html["FC-to-SAS ブリッジおよび SAS ディスクシェルフの設置"]

https://hwu.netapp.com["NetApp Hardware Universe の略"]
