---
permalink: install-fc/concept_implementing_a_mcc_configuration_with_both_disks_and_array_luns.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, implement, configuration, disks, array, luns 
summary: ネイティブディスクとアレイ LUN を使用する MetroCluster 構成を実装するには、使用する ONTAP システムをストレージアレイに接続できるように構成する必要があります。 
---
= ディスクとアレイ LUN の両方を含む MetroCluster 構成の実装
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ネイティブディスクとアレイ LUN を使用する MetroCluster 構成を実装するには、使用する ONTAP システムをストレージアレイに接続できるように構成する必要があります。

ディスクとアレイ LUN を使用する MetroCluster 構成は、 4 ノードまたは 2 ノードのどちらかで構成できます。4 ノードの MetroCluster 構成はファブリック接続にする必要がありますが、 2 ノードの構成はストレッチまたはファブリック接続のどちらでも構成できます。

を参照してください https://mysupport.netapp.com/matrix["ネットアップの Interoperability Matrix Tool （ IMT ）"]では、 Storage 解決策フィールドを使用して MetroCluster 解決策を選択できます。検索を絞り込むには、 * 構成部品エクスプローラ * を使用して構成部品と ONTAP バージョンを選択します。[ 結果の表示（ Show Results ） ] をクリックすると、条件に一致するサポートされている構成のリストを表示できます。

ネイティブディスクおよびアレイ LUN を使用する 2 ノードファブリック接続 MetroCluster 構成または 4 ノード MetroCluster 構成では、 FC-to-SAS ブリッジを使用して ONTAP システムとディスクシェルフを FC スイッチ経由で接続する必要があります。アレイ LUN は FC スイッチ経由で ONTAP システムに接続できます。

link:reference_example_of_a_two_node_fabric_attached_mcc_configuration_with_disks_and_array_luns.html["ディスクとアレイ LUN を使用する 2 ノードファブリック接続 MetroCluster 構成の例"]

link:concept_example_of_a_four_node_mcc_configuration_with_disks_and_array_luns.html["ディスクとアレイ LUN を使用する 4 ノード MetroCluster 構成の例"]
