---
permalink: install-fc/fc-switch-port-assignment-overview.html 
sidebar: sidebar 
keywords: ONTAP, FAS, FC, Brocade, ISL, Cisco, metrocluster, switch, cabling, port, assignment 
summary: FCスイッチをケーブル接続するときは、指定のポート割り当てを使用していることを確認する必要があります。 
---
= MetroCluster FCスイッチのポート割り当て
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FCスイッチをケーブル接続するときは、指定のポート割り当てを使用していることを確認する必要があります。

イニシエータポート、FC-VIポート、またはISLの接続に使用されていないポートを、ストレージポートとして再構成できます。ただし、サポートされているRCFを使用している場合は、それに応じてゾーニングを変更する必要があります。

サポートされている RCF を使用する場合、ISL ポートは表示されているポートと同じポートに接続されない可能性があり、手動で再構成する必要がある場合があります。

ONTAP 9のポート割り当てを使用してスイッチが設定されている場合は、引き続き古い割り当てを使用できます。ただし、 ONTAP 9.1 以降を実行する新しい構成では、ここに示すポート割り当てを使用する必要があります。



== ケーブル接続の全体的なガイドライン

ケーブル接続の表を使用する際は、次の点に注意してください。

* Brocade スイッチと Cisco スイッチでは、ポート番号の付け方が異なります。
+
** Brocade スイッチでは、ポート番号は 0 から始まります。
** Cisco スイッチでは、ポート番号は 1 から始まります。


* ケーブル接続は、スイッチファブリックの各 FC スイッチで同じです。
* AFF A300およびFAS8200ストレージシステムでは、発注時にFC-VI接続のオプションとして次のいずれかを選択できます。
+
** FC-VI モードで設定されたオンボードポート 0e および 0f 。
** スロット 1 の FC-VI カードのポート 1a および 1b 。


* AFF A700 および FAS9000 ストレージシステムの場合、 FC-VI ポートが 4 つ必要です。次の表に、 Cisco 9250i スイッチを除く各コントローラに FC-VI ポートが 4 つある FC スイッチのケーブル接続を示します。
+
他のストレージシステムの場合、表にあるケーブル接続を使用し、 FC-VI ポート c および d については無視してください

+
これらのポートは空にしておくことができます。

* AFF A400 および FAS8300 ストレージシステムは、 FC-VI 接続にポート 2a と 2b を使用します。
* 2 つの MetroCluster 構成で ISL を共有する場合は、 8 ノード MetroCluster のケーブル接続と同じポート割り当てを使用します。
* ケーブル接続する ISL の数は、サイトの要件に応じて異なります。
* ISL に関する考慮事項についてのセクションを参照してください。
+
link:concept_considerations_isls_mcfc.html["ISL に関する考慮事項"]





== AFF A900およびFAS9500の配線ガイドライン

* AFF A900またはFAS9500ストレージシステムでは、FC-VIポートが8つ必要です。AFF A900またはFAS9500を使用している場合は、8つのポート構成を使用する必要があります。構成に他のストレージシステムモデルが含まれている場合は、表に示されているケーブル接続を使用し、不要な FC-VI ポートのケーブル接続は無視してください。

