---
permalink: install-fc/reference_requirements_for_a_mcc_configuration_with_array_luns_reference.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, requirements, array, luns, mcc 
summary: MetroCluster 構成で使用する ONTAP システム、ストレージアレイ、および FC スイッチには、それらの構成の種類に固有の要件があります。また、アレイ LUN を使用する MetroCluster 構成に対する SyncMirror の要件も考慮する必要があります。 
---
= アレイ LUN を使用する MetroCluster 構成の要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
MetroCluster 構成で使用する ONTAP システム、ストレージアレイ、および FC スイッチには、それらの構成の種類に固有の要件があります。また、アレイ LUN を使用する MetroCluster 構成に対する SyncMirror の要件も考慮する必要があります。



== ONTAP システムの要件

* ONTAP システムが MetroCluster 構成でサポートされていることを確認しておく必要があります。
+
を参照してください https://mysupport.netapp.com/matrix["ネットアップの Interoperability Matrix Tool （ IMT ）"]では、 Storage 解決策フィールドを使用して MetroCluster 解決策を選択できます。検索を絞り込むには、 * 構成部品エクスプローラ * を使用して構成部品と ONTAP バージョンを選択します。[ 結果の表示（ Show Results ） ] をクリックすると、条件に一致するサポートされている構成のリストを表示できます。

+

NOTE: Interoperability Matrix で選択した構成に関連するアラートの詳細を参照する必要があります。

* MetroCluster 構成内のすべての ONTAP システムが同じモデルである必要があります。
* 各 ONTAP システムで、モデルに応じた適切なスロットに FC-VI アダプタが挿入されている必要があります。
+
https://hwu.netapp.com["NetApp Hardware Universe の略"]





== ストレージアレイの要件

* ストレージアレイが MetroCluster 構成でサポートされていることを確認しておく必要があります。
+
https://mysupport.netapp.com/matrix["NetApp Interoperability Matrix Tool で確認できます"]

* MetroCluster 構成内のストレージアレイは対称に配置する必要があります。
+
** 2 つのストレージアレイは、サポートされている同じベンダーファミリーに属し、同じバージョンのファームウェアがインストールされている必要があります。
+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.vs-ig-es/home.html["NetApp E シリーズストレージ向けの FlexArray 仮想化の実装"]

+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.vs-ig-third/home.html["サードパーティ製ストレージ向けの FlexArray 仮想化の実装"]

** ミラーされたストレージに使用するディスクタイプ（ SATA 、 SSD 、 SAS など）は、両方のストレージアレイで同じである必要があります。
** RAID タイプや階層化など、ストレージアレイを設定するパラメータは、両方のサイトで同じである必要があります。






== FC スイッチの要件

* スイッチとスイッチファームウェアが MetroCluster 構成でサポートされていることを確認しておく必要があります。
+
https://mysupport.netapp.com/matrix["NetApp Interoperability Matrix Tool で確認できます"]

* ファブリックごとに 2 つの FC スイッチが必要です。
* デバイスやパスに障害が発生した場合でも冗長性を確保できるように、各 ONTAP システムを冗長コンポーネントを使用してストレージに接続する必要があります。
* AFF A900 および FAS9000 ストレージシステムでは、ファブリックあたり最大 8 つの ISL がサポートされます。それ以外のストレージシステムモデルでは、ファブリックごとに最大 4 つの ISL がサポートされます。


各スイッチで、 MetroCluster の基本的なスイッチ設定、 ISL 設定、および FC-VI 構成を使用する必要があります。

link:task_fcsw_configure_the_cisco_or_brocade_fc_switches_manually.html["Cisco または Brocade FC スイッチを手動で設定する"]



== SyncMirror の要件

* MetroCluster 構成には SyncMirror が必要です。
* ミラーリングされたストレージには、各サイトに 1 つずつ、合計 2 つのストレージアレイが必要です。
* アレイ LUN が 2 セット必要です。
+
1 つ目はローカルストレージアレイ上のアグリゲート（ pool0 ）用、もう 1 つはアグリゲートのミラー（アグリゲートのもう 1 つのプレックス、 pool1 ）用にリモートストレージアレイに配置します。

+
アグリゲートをミラーするには、アレイ LUN が同じサイズである必要があります。

* MetroCluster 構成ではミラーされていないアグリゲートもサポートされます。
+
サイトで障害が発生しても保護されるわけではありません。


