---
permalink: install-fc/reference_where_to_find_additional_information_icg.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, additional, information 
summary: MetroCluster の設定と運用の詳細については、ネットアップのドキュメントを参照してください。 
---
= 追加情報の参照先
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
MetroCluster の設定と処理の詳細については、を参照してください。



== MetroCluster およびその他の情報

|===


| 情報 | 件名 


 a| 
https://docs.netapp.com/us-en/ontap/index.html["ONTAP 9 のドキュメント"^]
 a| 
* すべての MetroCluster 情報




| https://www.netapp.com/pdf.html?item=/media/13480-tr4705.pdf["NetApp MetroCluster 解決策のアーキテクチャと設計、 TR-4705"^]  a| 
* MetroCluster FC の構成と運用の技術概要
* MetroCluster FC 構成のベストプラクティス




| https://www.netapp.com/pdf.html?item=/media/13481-tr4689.pdf["MetroCluster IP 解決策のアーキテクチャおよび設計、 TR-4689"^]  a| 
* MetroCluster IP の構成と運用の技術概要
* MetroCluster IP 構成のベストプラクティス




 a| 
https://docs.netapp.com/us-en/ontap-metrocluster/install-stretch/concept_considerations_differences.html["ストレッチ MetroCluster のインストールと設定"]
 a| 
* ストレッチ MetroCluster アーキテクチャ
* 構成のケーブル接続
* FC-to-SAS ブリッジの設定
* ONTAP で MetroCluster を設定します




 a| 
https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_considerations_differences.html["MetroCluster IP のインストールと設定： ONTAP MetroCluster 構成の違い"]
 a| 
* MetroCluster IP アーキテクチャ
* 構成のケーブル接続
* ONTAP で MetroCluster を設定します




 a| 
https://docs.netapp.com/us-en/ontap-metrocluster/manage/index.html["MetroCluster の管理とディザスタリカバリ"]
 a| 
* MetroCluster 構成について
* スイッチオーバー、修復、スイッチバック
* ディザスタリカバリ




 a| 
https://docs.netapp.com/us-en/ontap-metrocluster/maintain/index.html["MetroCluster のコンポーネントをメンテナンスします"]
 a| 
* MetroCluster FC 構成のメンテナンスガイドライン
* FC-to-SAS ブリッジおよび FC スイッチのハードウェア交換 / アップグレードおよびファームウェアアップグレード手順
* ファブリック接続またはストレッチ MetroCluster FC 構成でのディスクシェルフのホットアド
* ファブリック接続またはストレッチ MetroCluster FC 構成でのディスクシェルフのホットリムーブ
* ファブリック接続またはストレッチ MetroCluster FC 構成のディザスタサイトでのハードウェア交換
* 2 ノードのファブリック接続またはストレッチ MetroCluster FC 構成の 4 ノード MetroCluster 構成への拡張
* 4 ノードのファブリック接続またはストレッチ MetroCluster FC 構成の 8 ノード MetroCluster FC 構成への拡張




 a| 
https://docs.netapp.com/us-en/ontap-metrocluster/transition/concept_choosing_your_transition_procedure_mcc_transition.html["MetroCluster FC から MetroCluster IP に移行します"]

https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/concept_choosing_an_upgrade_method_mcc.html["MetroCluster アップグレードおよび拡張ガイド"]
 a| 
* MetroCluster 設定をアップグレードまたは更新する
* MetroCluster FC 構成から MetroCluster IP 構成への移行
* ノードの追加による MetroCluster 構成の拡張




 a| 
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.hw-metrocluster-tiebreaker/home.html["MetroCluster Tiebreaker ソフトウェアのインストールおよび設定"]
 a| 
* MetroCluster Tiebreaker ソフトウェアを使用して MetroCluster 構成を監視する




 a| 
Active IQ デジタルアドバイザのドキュメント

https://www.netapp.com/support-and-training/documentation/["ネットアップのマニュアル：製品ガイドとリソース"^]
 a| 
* MetroCluster の設定とパフォーマンスを監視する




 a| 
https://docs.netapp.com/us-en/ontap-7mode-transition/copy-based/index.html["コピーベースの移行"^]
 a| 
* 7-Mode ストレージシステムから clustered Data ONTAP ストレージシステムへデータを移行する




 a| 
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-concepts/home.html["ONTAP の概念"^]
 a| 
* ミラーされたアグリゲートの機能


|===