---
permalink: install-fc/task_fcsw_brocade_configure_the_brocade_fc_switches_supertask.html 
sidebar: sidebar 
keywords: MetroCluster configurations 
summary: MetroCluster 構成内の各 Brocade スイッチファブリックを設定する必要があります。 
---
= Brocade FC スイッチを手動で設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
MetroCluster 構成内の各 Brocade スイッチファブリックを設定する必要があります。

.作業を開始する前に
* Telnet または Secure Shell （ SSH ）を使用して FC スイッチにアクセス可能な PC または UNIX ワークステーションが必要です。
* 同じバージョンとライセンスの Brocade Fabric Operating System （ FOS ）を実行している、同じモデルの Brocade スイッチ（サポートされるもの）を 4 つ使用している必要があります。
+
https://mysupport.netapp.com/matrix["NetApp Interoperability Matrix Tool で確認できます"]

+
IMT では、 Storage 解決策フィールドを使用して MetroCluster 解決策を選択できます。検索を絞り込むには、 * 構成部品エクスプローラ * を使用して構成部品と ONTAP バージョンを選択します。[ 結果の表示（ Show Results ） ] をクリックすると、条件に一致するサポートされている構成のリストを表示できます。

* サポートされる 4 つの Brocade スイッチがそれぞれ 2 つのスイッチで構成される 2 つのファブリックに接続されます。各ファブリックが両方のサイトにまたがっている必要があります。
* 各ストレージコントローラに、スイッチファブリックに接続可能なイニシエータポートが 4 つ必要です。各ストレージコントローラの 2 つのイニシエータポートを各ファブリックに接続する必要があります。
+

NOTE: FAS8020 、 AFF8020 、 FAS8200 、および AFF A300 のシステムでは、次のすべての条件に該当する場合、コントローラあたりのイニシエータポートを 2 ポート（各ファブリックに 1 つのイニシエータポートを接続）にすることができます。

+
** ディスクストレージの接続に使用できる FC イニシエータポートが 3 つ以下で、それ以外に FC イニシエータとして設定できるポートがない。
** すべてのスロットが使用中で、 FC イニシエータカードを追加できません。




.このタスクについて
* スイッチ間リンク（ ISL ）トランキングがリンクでサポートされている場合、これを有効にする必要があります。
+
link:concept_tdm_wdm.html["ファブリック接続 MetroCluster 構成で TDM / WDM 機器を使用する場合の考慮事項"]

* 1 つのファブリック内のすべての ISL の長さと速度が同じである必要があります。
+
ISL の長さはファブリックが異なる場合は同じである必要はありませんが、速度はすべてのファブリックで同じである必要があります。

* Metro-E および TDM （ SONET / SDH ）はサポートされず、 FC 以外のネイティブのフレーミングやシグナリングはサポートされていません。
+
Metro-E とは、長距離（メトロ距離）間でネイティブに、または何らかの時分割多重化（ TDM ）、 Multiprotocol Label Switching （ MPLS ）、波長分割多重化（ WDM ）経由で行われるイーサネットフレーミングまたはシグナリングを意味します。

* TDM 、 FCR （ネイティブの FC ルーティング）、または FCIP の拡張機能は、 MetroCluster FC スイッチファブリックではサポートされていません。
* MetroCluster FC スイッチファブリック内の一部のスイッチでは、暗号化または圧縮、あるいはその両方がサポートされます。
+
https://mysupport.netapp.com/matrix["ネットアップの Interoperability Matrix Tool （ IMT ）"]

+
IMT では、 Storage 解決策フィールドを使用して MetroCluster 解決策を選択できます。検索を絞り込むには、 * 構成部品エクスプローラ * を使用して構成部品と ONTAP バージョンを選択します。[ 結果の表示（ Show Results ） ] をクリックすると、条件に一致するサポートされている構成のリストを表示できます。

* Brocade Virtual Fabric （ VF ）機能はサポートされていません。
* ドメインポートに基づく FC ゾーニングはサポートされていますが、ワールドワイド名（ WWN ）に基づくゾーニングはサポートされていません。




== Brocade ライセンス要件の確認

MetroCluster 構成内のスイッチには所定のライセンスが必要です。これらのライセンスは 4 つのスイッチすべてにインストールする必要があります。

.このタスクについて
MetroCluster 構成での Brocade ライセンス要件は次のとおりです。

* 推奨される複数の ISL を使用するシステムのトランキングライセンスです。
* Extended Fabric ライセンス（ ISL の距離が 6km を超える場合）
* ISL の距離が 6km を超えるサイト用の Enterprise ライセンスです
+
Enterprise ライセンスには、 Brocade Network Advisor と、追加のポートライセンスを除くすべてのライセンスが含まれます。



.ステップ
. ライセンスがインストールされていることを確認します。
+
「 licenseshow` 」

+
これらのライセンスをお持ちでない場合は、作業を進める前に営業担当者までお問い合わせください。





== Brocade FC スイッチの値を工場出荷時のデフォルトに設定

設定を適切に行うには、スイッチを工場出荷時のデフォルトに設定する必要があります。また、各スイッチに一意な名前を割り当てる必要があります。

.このタスクについて
この手順の例では、ファブリックは BrocadeSwitchA と BrocadeSwitchB で構成されています。

.手順
. コンソールに接続し、 1 つのファブリック内の両方のスイッチにログインします。
. スイッチを永続的に無効にします。
+
'witchcfgpersistentdisable

+
これにより、リブート後や高速ブート後もスイッチが無効なままになります。このコマンドが使用できない場合は、「 witchDisable 」コマンドを使用します。

+
次の例は、 BrocadeSwitchA に対するコマンドを示しています。

+
[listing]
----
BrocadeSwitchA:admin> switchcfgpersistentdisable
----
+
次の例は、 BrocadeSwitchB に対するコマンドを示しています。

+
[listing]
----
BrocadeSwitchB:admin> switchcfgpersistentdisable
----
. スイッチ名を設定します。
+
'witchname switch_name

+
スイッチの名前はそれぞれ一意である必要があります。名前を設定すると、プロンプトがそれに応じて変わります。

+
次の例は、 BrocadeSwitchA に対するコマンドを示しています。

+
[listing]
----
BrocadeSwitchA:admin> switchname "FC_switch_A_1"
FC_switch_A_1:admin>
----
+
次の例は、 BrocadeSwitchB に対するコマンドを示しています。

+
[listing]
----
BrocadeSwitchB:admin> switchname "FC_Switch_B_1"
FC_switch_B_1:admin>
----
. すべてのポートをデフォルト値に設定します。
+
portcfgdefault

+
スイッチ上のすべてのポートに対して実行する必要があります。

+
次の例は、 FC_switch_A_1 に対するコマンドを示しています。

+
[listing]
----
FC_switch_A_1:admin> portcfgdefault 0
FC_switch_A_1:admin> portcfgdefault 1
...
FC_switch_A_1:admin> portcfgdefault 39
----
+
次の例は、 FC_switch_B_1 に対するコマンドを示しています。

+
[listing]
----
FC_switch_B_1:admin> portcfgdefault 0
FC_switch_B_1:admin> portcfgdefault 1
...
FC_switch_B_1:admin> portcfgdefault 39
----
. ゾーニング情報を消去します。
+
cfgdisable

+
cfgclear

+
cfgsave

+
次の例は、 FC_switch_A_1 に対するコマンドを示しています。

+
[listing]
----
FC_switch_A_1:admin> cfgdisable
FC_switch_A_1:admin> cfgclear
FC_switch_A_1:admin> cfgsave
----
+
次の例は、 FC_switch_B_1 に対するコマンドを示しています。

+
[listing]
----
FC_switch_B_1:admin> cfgdisable
FC_switch_B_1:admin> cfgclear
FC_switch_B_1:admin> cfgsave
----
. スイッチの一般的な設定をデフォルトに設定します。
+
「 configdefault 」

+
次の例は、 FC_switch_A_1 に対するコマンドを示しています。

+
[listing]
----
FC_switch_A_1:admin> configdefault
----
+
次の例は、 FC_switch_B_1 に対するコマンドを示しています。

+
[listing]
----
FC_switch_B_1:admin> configdefault
----
. すべてのポートを非トランキングモードに設定します。
+
'witchcfgtrunk 0`

+
次の例は、 FC_switch_A_1 に対するコマンドを示しています。

+
[listing]
----
FC_switch_A_1:admin> switchcfgtrunk 0
----
+
次の例は、 FC_switch_B_1 に対するコマンドを示しています。

+
[listing]
----
FC_switch_B_1:admin> switchcfgtrunk 0
----
. Brocade 6510 スイッチで、 Brocade Virtual Fabric （ VF ）機能を無効にします。
+
「 fosconfig options 」を参照してください

+
次の例は、 FC_switch_A_1 に対するコマンドを示しています。

+
[listing]
----
FC_switch_A_1:admin> fosconfig --disable vf
----
+
次の例は、 FC_switch_B_1 に対するコマンドを示しています。

+
[listing]
----
FC_switch_B_1:admin> fosconfig --disable vf
----
. Administrative Domain （ AD ）設定をクリアします。
+
「広告オプション」

+
次の例は、 FC_switch_A_1 に対するコマンドを示しています。

+
[listing]
----
FC_switch_A_1:admin> switch:admin> ad --select AD0
FC_switch_A_1:> defzone --noaccess
FC_switch_A_1:> cfgsave
FC_switch_A_1:> exit
FC_switch_A_1:admin> ad --clear -f
FC_switch_A_1:admin> ad --apply
FC_switch_A_1:admin> ad --save
FC_switch_A_1:admin> exit
----
+
次の例は、 FC_switch_B_1 に対するコマンドを示しています。

+
[listing]
----
FC_switch_B_1:admin> switch:admin> ad --select AD0
FC_switch_A_1:> defzone --noaccess
FC_switch_A_1:> cfgsave
FC_switch_A_1:> exit
FC_switch_B_1:admin> ad --clear -f
FC_switch_B_1:admin> ad --apply
FC_switch_B_1:admin> ad --save
FC_switch_B_1:admin> exit
----
. スイッチをリブートします。
+
「再起動」

+
次の例は、 FC_switch_A_1 に対するコマンドを示しています。

+
[listing]
----
FC_switch_A_1:admin> reboot
----
+
次の例は、 FC_switch_B_1 に対するコマンドを示しています。

+
[listing]
----
FC_switch_B_1:admin> reboot
----




== スイッチの基本設定を行います

Brocade スイッチに対して、ドメイン ID を含む基本的なグローバル設定を行う必要があります。

.このタスクについて
このタスクには、両方の MetroCluster サイトの各スイッチで実行する必要のある手順が含まれています。

この手順では、次の例に示すように、スイッチごとに一意のドメイン ID を設定します。この例では、ドメイン ID 5 と 7 が fabric_1 を形成し、ドメイン ID 6 と 8 が fabric_2 を形成します。

* FC_switch_A_1 をドメイン ID 5 に割り当てます
* FC_switch_A_2 はドメイン ID 6 に割り当てられています
* FC_switch_B_1 をドメイン ID 7 に割り当てます
* FC_switch_B_2 をドメイン ID 8 に割り当て


.手順
. コンフィギュレーションモードを開始します。
+
「 configure 」を実行します

. プロンプトに従って次の手順に進みます。
+
.. スイッチのドメイン ID を設定します。
.. 「 RDP Polling Cycle 」というプロンプトが表示されるまで *Enter を押し、その値を「 0 」に設定してポーリングを無効にします。
.. スイッチのプロンプトに戻るまで * Enter キーを押します。
+
[listing]
----
FC_switch_A_1:admin> configure
Fabric parameters = y
Domain_id = 5
.
.

RSCN Transmission Mode [yes, y, no, no: [no] y

End-device RSCN Transmission Mode
 (0 = RSCN with single PID, 1 = RSCN with multiple PIDs, 2 = Fabric RSCN): (0..2) [1]
Domain RSCN To End-device for switch IP address or name change
 (0 = disabled, 1 = enabled): (0..1) [0] 1

.
.
RDP Polling Cycle(hours)[0 = Disable Polling]: (0..24) [1] 0
----


. ファブリックごとに 2 つ以上の ISL を使用している場合は、フレームの配信順序として In-Order Delivery （ IOD ；インオーダー配信）または Out-of-Order Delivery （ OOD ；アウトオブオーダー配信）のいずれかを設定できます。
+

NOTE: 標準の IOD 設定を推奨します。OOD を設定するのは必要な場合だけにしてください。

+
link:concept_prepare_for_the_mcc_installation.html["ファブリック接続 MetroCluster 構成で TDM / WDM 機器を使用する場合の考慮事項"]

+
.. フレームの IOD を設定するには、各スイッチファブリックで次の手順を実行する必要があります。
+
... IOD を有効にします。
+
「 iodset 」

... Advanced Performance Tuning （ APT ；高度なパフォーマンスチューニング）ポリシーを 1 に設定します。
+
「 aptpolicy 1 」

... 動的負荷共有（ DLS ）を無効にします。
+
「 lsreset 」と表示されます

... iodshow 、 aptpolicy 、および `d lsshow の各コマンドを使用して IOD 設定を検証します。
+
たとえば、 FC_switch_A_1 で次のコマンドを問題に実行します。

+
[listing]
----
FC_switch_A_1:admin> iodshow
    IOD is set

    FC_switch_A_1:admin> aptpolicy
    Current Policy: 1 0(ap)

    3 0(ap) : Default Policy
    1: Port Based Routing Policy
    3: Exchange Based Routing Policy
         0: AP Shared Link Policy
         1: AP Dedicated Link Policy
    command aptpolicy completed

    FC_switch_A_1:admin> dlsshow
    DLS is not set
----
... 2 つ目のスイッチファブリックで、上記の手順を繰り返します。


.. フレームの OOD を設定するには、各スイッチファブリックで次の手順を実行する必要があります。
+
... OOD を有効にします。
+
「 iodreset 」

... Advanced Performance Tuning （ APT ；高度なパフォーマンスチューニング）ポリシーを 3 に設定します。
+
「 aptpolicy 3 」

... 動的負荷共有（ DLS ）を無効にします。
+
「 lsreset 」と表示されます

... OOD 設定を確認します。
+
「 iodshow 」

+
「 aptpolicy 」と入力します

+
「 llsshow 」

+
たとえば、 FC_switch_A_1 で次のコマンドを問題に実行します。

+
[listing]
----
FC_switch_A_1:admin> iodshow
    IOD is not set

    FC_switch_A_1:admin> aptpolicy
    Current Policy: 3 0(ap)
    3 0(ap) : Default Policy
    1: Port Based Routing Policy
    3: Exchange Based Routing Policy
    0: AP Shared Link Policy
    1: AP Dedicated Link Policy
    command aptpolicy completed


    FC_switch_A_1:admin> dlsshow
    DLS is set by default with current routing policy
----
... 2 つ目のスイッチファブリックで、上記の手順を繰り返します。
+

NOTE: コントローラモジュールに ONTAP を設定する場合は、 MetroCluster 構成の各コントローラモジュールで OOD を明示的に設定する必要があります。

+
https://docs.netapp.com/us-en/ontap-metrocluster/install-fc/concept_configure_the_mcc_software_in_ontap.html#configuring-in-order-delivery-or-out-of-order-delivery-of-frames-on-ontap-software["ONTAP ソフトウェアでのフレームのインオーダー配信またはアウトオブオーダー配信の設定"]





. スイッチが動的ポートライセンス方式を使用していることを確認します。
+
.. ライセンスコマンドを実行します。
+
--
「 licensePort -- show 」を入力します

[listing]
----
FC_switch_A_1:admin> licenseport -show
24 ports are available in this switch
Full POD license is installed
Dynamic POD method is in use
----

NOTE: バージョン 8.0 より前の Brocade FabricOS では、次のコマンドを admin として実行し、バージョン 8.0 以降では root として実行します。

--
.. root ユーザを有効にします。
+
Brocade によって root ユーザがすでに無効にされている場合は、次の例に示すように root ユーザを有効にします。

+
[listing]
----
FC_switch_A_1:admin> userconfig --change root -e yes
FC_switch_A_1:admin> rootaccess --set consoleonly
----
.. ライセンスコマンドを実行します。
+
「 licensePort -- show 」を入力します

+
[listing]
----
FC_switch_A_1:root> licenseport -show
24 ports are available in this switch
Full POD license is installed
Dynamic POD method is in use
----
.. ライセンス方式を動的な方式に変更します。
+
licenseport -- メソッドの動的

+

NOTE: 動的ライセンス方式が使用されていない場合（静的な方式の場合）は、ライセンス方式を動的な方式に変更する必要があります。動的ライセンス方式を使用している場合は、この手順を省略します。

+
[listing]
----
FC_switch_A_1:admin> licenseport --method dynamic
The POD method has been changed to dynamic.
Please reboot the switch now for this change to take effect
----


. ONTAP でスイッチの健常性を監視できるように、 T11-FC-ZONE-SERVER-MIB のトラップを有効にします。
+
.. T11-FC-ZONE-SERVER-MIB を有効にします。
+
'mpconfig -- set mibCapability-mib_name T11-FC-ZONE-SERVER-MIB-Bitz-0x3f

.. T11-FC-ZONE-SERVER-MIB トラップを有効にします。
+
「 mpconfig 」 -- mibcapability を有効にする - mib_name sw-mib-trap_name swZoneConfigChangeTrap 」

.. 2 つ目のスイッチファブリックで、ここまでの手順を繰り返します。


. * オプション * ：コミュニティストリングを「 public 」以外の値に設定した場合は、指定したコミュニティストリングを使用して ONTAP ヘルスモニタを設定する必要があります。
+
.. 既存のコミュニティストリングを変更します。
+
'mpconfig -- set snmpv1'

.. 「 Community (ro): [public] 」というテキストが表示されるまで * Enter キーを押します。
.. 目的のコミュニティストリングを入力します。
+
FC_switch_A_1 では、次のコマンドを実行します。

+
[listing]
----
FC_switch_A_1:admin> snmpconfig --set snmpv1
SNMP community and trap recipient configuration:
Community (rw): [Secret C0de]
Trap Recipient's IP address : [0.0.0.0]
Community (rw): [OrigEquipMfr]
Trap Recipient's IP address : [0.0.0.0]
Community (rw): [private]
Trap Recipient's IP address : [0.0.0.0]
Community (ro): [public] mcchm     <<<<<< change the community string to the desired value,
Trap Recipient's IP address : [0.0.0.0]    in this example it is set to "mcchm"
Community (ro): [common]
Trap Recipient's IP address : [0.0.0.0]
Community (ro): [FibreChannel]
Trap Recipient's IP address : [0.0.0.0]
Committing configuration.....done.
FC_switch_A_1:admin>
----
+
FC_switch_B_1 では、次のコマンドを実行します。

+
[listing]
----
FC_switch_B_1:admin> snmpconfig --set snmpv1
SNMP community and trap recipient configuration:
Community (rw): [Secret C0de]
Trap Recipient's IP address : [0.0.0.0]
Community (rw): [OrigEquipMfr]
Trap Recipient's IP address : [0.0.0.0]
Community (rw): [private]
Trap Recipient's IP address : [0.0.0.0]
Community (ro): [public] mcchm      <<<<<< change the community string to the desired value,
Trap Recipient's IP address : [0.0.0.0]     in this example it is set to "mcchm"
Community (ro): [common]
Trap Recipient's IP address : [0.0.0.0]
Community (ro): [FibreChannel]
Trap Recipient's IP address : [0.0.0.0]
Committing configuration.....done.
FC_switch_B_1:admin>
----


. スイッチをリブートします。
+
「再起動」

+
FC_switch_A_1 では、次のコマンドを実行します。

+
[listing]
----
FC_switch_A_1:admin> reboot
----
+
FC_switch_B_1 では、次のコマンドを実行します。

+
[listing]
----
FC_switch_B_1:admin> reboot
----
. スイッチを永続的に有効にします。
+
'witchcfgpersistentenable

+
FC_switch_A_1 では、次のコマンドを実行します。

+
[listing]
----
FC_switch_A_1:admin> switchcfgpersistentenable
----
+
FC_switch_B_1 では、次のコマンドを実行します。

+
[listing]
----
FC_switch_B_1:admin> switchcfgpersistentenable
----




== Brocade DCX 8510-8 スイッチの基本設定

Brocade スイッチに対して、ドメイン ID を含む基本的なグローバル設定を行う必要があります。

.このタスクについて
この手順は、両方の MetroCluster サイトの各スイッチで実行する必要があります。この手順では、次の例に示すように、各スイッチのドメイン ID を設定します。

* FC_switch_A_1 をドメイン ID 5 に割り当てます
* FC_switch_A_2 はドメイン ID 6 に割り当てられています
* FC_switch_B_1 をドメイン ID 7 に割り当てます
* FC_switch_B_2 をドメイン ID 8 に割り当て


この例では、ドメイン ID 5 と 7 が fabric_1 を形成し、ドメイン ID 6 と 8 が fabric_2 を形成します。


NOTE: 各サイトで DCX 8510-8 スイッチを 1 つだけ使用する場合も、この手順を使用してスイッチを設定できます。

この手順を使用して、各 Brocade DCX 8510-8 スイッチに 2 つの論理スイッチを作成する必要があります。両方の Brocade DCX8510-8 スイッチに作成された 2 つの論理スイッチは、次の例に示すように 2 つの論理ファブリックを形成します。

* 論理ファブリック 1 ：スイッチ 1 のブレード 1 とスイッチ 2 のブレード 1
* 論理ファブリック 2 ：スイッチ 2 のブレード 2 とスイッチ 2 のブレード 2


.手順
. コマンドモードを開始します。
+
「 configure 」を実行します

. プロンプトに従って次の手順に進みます。
+
.. スイッチのドメイン ID を設定します。
.. 「 RDP Polling Cycle 」というプロンプトが表示されるまで *Enter を押し続け、値を「 0 」に設定してポーリングを無効にします。
.. スイッチのプロンプトに戻るまで *Enter を押します。
+
[listing]
----
FC_switch_A_1:admin> configure
Fabric parameters = y
Domain_id = `5


RDP Polling Cycle(hours)[0 = Disable Polling]: (0..24) [1] 0
`
----


. fabric_1 と fabric_2 のすべてのスイッチについて、同じ手順を繰り返します。
. 仮想ファブリックを設定します。
+
.. スイッチで仮想ファブリックを有効にします。
+
fosconfig -- 有効な evf`

.. すべての論理スイッチで同じ基本設定を使用するようにシステムを設定します。
+
「シャーシの設定」を参照してください

+
次に 'configurechassis コマンドの出力例を示します

+
[listing]
----
System (yes, y, no, n): [no] n
cfgload attributes (yes, y, no, n): [no] n
Custom attributes (yes, y, no, n): [no] y
Config Index (0 to ignore): (0..1000) [3]:
----


. 論理スイッチを作成して設定します。
+
'cfg -- fabricID' を作成します

. ブレードのすべてのポートを仮想ファブリックに追加します。
+
lscfg --config fabricID-slot スロットポート lowest-port-fest-port

+

NOTE: 論理ファブリックを形成するブレード（例 スイッチ 1 のブレード 1 とスイッチ 3 のブレード 1 ）のファブリック ID が同じである必要があります。

+
[listing]
----
setcontext fabricid
switchdisable
configure
<configure the switch per the above settings>
switchname unique switch name
switchenable
----


.関連情報
link:concept_prepare_for_the_mcc_installation.html["Brocade DCX 8510-8 スイッチを使用するための要件"]



== FC ポートを使用した Brocade FC スイッチでの E ポートの設定

FC ポートを使用してスイッチ間リンク（ ISL ）が設定された Brocade スイッチの場合、 ISL を接続する各スイッチファブリックのスイッチポートを設定する必要があります。これらの ISL ポートは E ポートとも呼ばれます。

.作業を開始する前に
* FC スイッチファブリック内のすべての ISL を、同じ速度、同じ距離で設定する必要があります。
* この速度をサポートするスイッチポートと Small Form-factor Pluggable （ SFP ）の組み合わせを使用する必要があります。
* サポートされる ISL の距離は FC スイッチのモデルによって異なります。
+
https://mysupport.netapp.com/matrix["NetApp Interoperability Matrix Tool で確認できます"]

+
IMT では、 Storage 解決策フィールドを使用して MetroCluster 解決策を選択できます。検索を絞り込むには、 * 構成部品エクスプローラ * を使用して構成部品と ONTAP バージョンを選択します。[ 結果の表示（ Show Results ） ] をクリックすると、条件に一致するサポートされている構成のリストを表示できます。

* ISL リンクには専用のラムダが必要であり、 Brocade によって距離、スイッチタイプ、および Fabric Operating System （ FOS ）がサポートされている必要があります。


.このタスクについて
portCfgLongDistance コマンドを実行する際、 L0 設定は使用しないでください。代わりに LE または LS 設定を使用し、 Brocade スイッチで LE の距離レベルを最小値とする距離を設定します。

xWDM/TDM 機器で作業をする場合は 'portCfgLongDistance コマンドを実行する際に LD 設定は使用しないでください代わりに LE または LS 設定を使用し、 Brocade スイッチで距離を設定します。

このタスクは FC スイッチファブリックごとに行う必要があります。

以下の表は、 ONTAP 9.1 または 9.2 を実行している構成の各種スイッチと ISL 数に対応する ISL ポートを示しています。このセクションでは、 Brocade 6505 スイッチの例を示しています。スイッチタイプに応じて、該当するポートを使用するように変更してください。

ONTAP 9.0 以前を実行している構成の場合は、を参照してください link:concept_port_assignments_for_fc_switches_when_using_ontap_9_0.html["ONTAP 9.0 を使用している場合の FC スイッチのポート割り当て"]。

構成に応じて必要な数の ISL を使用する必要があります。

|===


| スイッチモデル | ISL ポート | スイッチポート 


.4+| Brocade 6520 | ISL 、ポート 1 | 23 


| ISL 、ポート 2 | 47 


| ISL 、ポート 3 | 71. 


| ISL 、ポート 4 | 95 


.4+| Brocade 6505 | ISL 、ポート 1 | 20 


| ISL 、ポート 2 | 21 


| ISL 、ポート 3 | 22 


| ISL 、ポート 4 | 23 


.8+| Brocade 6510 および Brocade DCX 8510-8 | ISL 、ポート 1 | 40 


| ISL 、ポート 2 | 41. 


| ISL 、ポート 3 | 42 


| ISL 、ポート 4 | 43 


| ISL 、ポート 5 | 44 


| ISL 、ポート 6 | 45 


| ISL 、ポート 7 | 46 


| ISL ポート 8 | 47 


.6+| Brocade 7810  a| 
ISL 、ポート 1
 a| 
GE2 （ 10Gbps ）



 a| 
ISL 、ポート 2
 a| 
GE3 （ 10Gbps ）



 a| 
ISL 、ポート 3
 a| 
GE4 （ 10Gbps ）



 a| 
ISL 、ポート 4
 a| 
GE5 （ 10Gbps ）



 a| 
ISL 、ポート 5
 a| 
ge6 （ 10Gbps ）



 a| 
ISL 、ポート 6
 a| 
ge7 （ 10Gbps ）



.4+| Brocade 7840 * 注： Brocade 7840 スイッチでは、 FCIP ISL を作成するために、スイッチあたり 2 つの 40Gbps VE ポートまたは最大 4 つの 10Gbps VE ポートがサポートされます。  a| 
ISL 、ポート 1
 a| 
ge0 （ 40Gbps ）または ge2 （ 10Gbps ）



 a| 
ISL 、ポート 2
 a| 
GE1 （ 40Gbps ）または ge3 （ 10Gbps ）



 a| 
ISL 、ポート 3
 a| 
ge10 （ 10Gbps ）



 a| 
ISL 、ポート 4
 a| 
ge11 （ 10Gbps ）



.4+| Brocade G610  a| 
ISL 、ポート 1
 a| 
20



 a| 
ISL 、ポート 2
 a| 
21



 a| 
ISL 、ポート 3
 a| 
22



 a| 
ISL 、ポート 4
 a| 
23



.7+| Brocade G620 、 G620 -1 、 G630 、 G630-1 、 G720  a| 
ISL 、ポート 1
 a| 
40



 a| 
ISL 、ポート 2
 a| 
41.



 a| 
ISL 、ポート 3
 a| 
42



 a| 
ISL 、ポート 4
 a| 
43



 a| 
ISL 、ポート 5
 a| 
44



 a| 
ISL 、ポート 6
 a| 
45



 a| 
ISL 、ポート 7
 a| 
46

|===
.手順
. [[step1_brocade_config]] ポート速度を設定します。
+
portcfgspeed port-number speed

+
パス内のすべてのコンポーネントでサポートされている最高速度を使用する必要があります。

+
次の例では、各ファブリックに ISL が 2 つあります。

+
[listing]
----
FC_switch_A_1:admin> portcfgspeed 20 16
FC_switch_A_1:admin> portcfgspeed 21 16

FC_switch_B_1:admin> portcfgspeed 20 16
FC_switch_B_1:admin> portcfgspeed 21 16
----
. ISL ごとにトランキングモードを設定します。
+
'portcfgtrunkport port-number

+
** ISL でトランキングを設定する場合（ IOD の場合）は、 portcfgtrunk port-number port-number port-number port-number を 1 に設定します。次に例を示します。
+
[listing]
----
FC_switch_A_1:admin> portcfgtrunkport 20 1
FC_switch_A_1:admin> portcfgtrunkport 21 1
FC_switch_B_1:admin> portcfgtrunkport 20 1
FC_switch_B_1:admin> portcfgtrunkport 21 1
----
** ISL でトランキングを設定しない場合（ OOD の場合）は、 portcfgtrunkport-number を 0 に設定します。次に例を示します。
+
[listing]
----
FC_switch_A_1:admin> portcfgtrunkport 20 0
FC_switch_A_1:admin> portcfgtrunkport 21 0
FC_switch_B_1:admin> portcfgtrunkport 20 0
FC_switch_B_1:admin> portcfgtrunkport 21 0
----


. ISL ポートごとに QoS トラフィックを有効にします。
+
portcfgqos --enable port-number

+
次の例では、各スイッチファブリックに ISL が 2 つあります。

+
[listing]
----
FC_switch_A_1:admin> portcfgqos --enable 20
FC_switch_A_1:admin> portcfgqos --enable 21

FC_switch_B_1:admin> portcfgqos --enable 20
FC_switch_B_1:admin> portcfgqos --enable 21
----
. 設定を確認します。
+
portCfgShow コマンド

+
次の例は、 2 つの ISL がポート 20 とポート 21 にケーブル接続されている構成の出力を示しています。Trunk Port の設定は、 IOD の場合は ON 、 OOD の場合は OFF になります。

+
[listing]
----

Ports of Slot 0   12  13   14 15    16  17  18  19   20  21 22  23    24  25  26  27
----------------+---+---+---+---+-----+---+---+---+----+---+---+---+-----+---+---+---
Speed             AN  AN  AN  AN    AN  AN  8G  AN   AN  AN  16G  16G    AN  AN  AN  AN
Fill Word         0   0   0   0     0   0   3   0    0   0   3   3     3   0   0   0
AL_PA Offset 13   ..  ..  ..  ..    ..  ..  ..  ..   ..  ..  ..  ..    ..  ..  ..  ..
Trunk Port        ..  ..  ..  ..    ..  ..  ..  ..   ON  ON  ..  ..    ..  ..  ..  ..
Long Distance     ..  ..  ..  ..    ..  ..  ..  ..   ..  ..  ..  ..    ..  ..  ..  ..
VC Link Init      ..  ..  ..  ..    ..  ..  ..  ..   ..  ..  ..  ..    ..  ..  ..  ..
Locked L_Port     ..  ..  ..  ..    ..  ..  ..  ..   ..  ..  ..  ..    ..  ..  ..  ..
Locked G_Port     ..  ..  ..  ..    ..  ..  ..  ..   ..  ..  ..  ..    ..  ..  ..  ..
Disabled E_Port   ..  ..  ..  ..    ..  ..  ..  ..   ..  ..  ..  ..    ..  ..  ..  ..
Locked E_Port     ..  ..  ..  ..    ..  ..  ..  ..   ..  ..  ..  ..    ..  ..  ..  ..
ISL R_RDY Mode    ..  ..  ..  ..    ..  ..  ..  ..   ..  ..  ..  ..    ..  ..  ..  ..
RSCN Suppressed   ..  ..  ..  ..    ..  ..  ..  ..   ..  ..  ..  ..    ..  ..  ..  ..
Persistent Disable..  ..  ..  ..    ..  ..  ..  ..   ..  ..  ..  ..    ..  ..  ..  ..
LOS TOV enable    ..  ..  ..  ..    ..  ..  ..  ..   ..  ..  ..  ..    ..  ..  ..  ..
NPIV capability   ON  ON  ON  ON    ON  ON  ON  ON   ON  ON  ON  ON    ON  ON  ON  ON
NPIV PP Limit    126 126 126 126   126 126 126 126  126 126 126 126   126 126 126 126
QOS E_Port        AE  AE  AE  AE    AE  AE  AE  AE   AE  AE  AE  AE    AE  AE  AE  AE
Mirror Port       ..  ..  ..  ..    ..  ..  ..  ..   ..  ..  ..  ..    ..  ..  ..  ..
Rate Limit        ..  ..  ..  ..    ..  ..  ..  ..   ..  ..  ..  ..    ..  ..  ..  ..
Credit Recovery   ON  ON  ON  ON    ON  ON  ON  ON   ON  ON  ON  ON    ON  ON  ON  ON
Fport Buffers     ..  ..  ..  ..    ..  ..  ..  ..   ..  ..  ..  ..    ..  ..  ..  ..
Port Auto Disable ..  ..  ..  ..    ..  ..  ..  ..   ..  ..  ..  ..    ..  ..  ..  ..
CSCTL mode        ..  ..  ..  ..    ..  ..  ..  ..   ..  ..  ..  ..    ..  ..  ..  ..

Fault Delay       0  0  0  0    0  0  0  0   0  0  0  0    0  0  0  0
----
. ISL の距離を計算します。
+
FC-VI の動作により、この距離は、 10km （ LE の距離レベルを使用）を最小値として、実際の距離の 1.5 倍に設定する必要があります。

+
ISL の距離は次のように計算され、 km 単位に切り上げられます。

+
実際の距離 × 1.5

+
距離が 3km の場合は、 3km × 1.5 = 4.5km となりますこの場合、 10km より短いため、 ISL は LE の距離レベルに設定する必要があります。

+
距離が 20km の場合は、 1.5 × 20 km = 30 km となりますISL は 30km に設定し、 LS の距離レベルを使用する必要があります。

. ISL ポートごとに距離を設定します。
+
`longdistance_portdistance-level_vc_link_init_ddistance

+
'vc_link_init' の値が '1' の場合は 'ARB フィルワード ( デフォルト ) が使用されます値「 0 」は IDLE を使用します。必要な値は、使用されているリンクによって異なる場合があります。コマンドは ISL ポートごとに繰り返し実行する必要があります。

+
前の手順の例で ISL の距離が 3km であるとすると、設定は 4.5km で、デフォルトの「 vc_link_init 」の値は「 1 」です。設定が 4.5km で 10km より短いため、ポートを LE の距離レベルに設定する必要があります。

+
[listing]
----
FC_switch_A_1:admin> portcfglongdistance 20 LE 1

FC_switch_B_1:admin> portcfglongdistance 20 LE 1
----
+
前の手順の例で ISL の距離が 20km であるとすると、設定は 30km で、 vc_link_init はデフォルト値の「 1' 」です。

+
[listing]
----
FC_switch_A_1:admin> portcfglongdistance 20 LS 1 -distance 30

FC_switch_B_1:admin> portcfglongdistance 20 LS 1 -distance 30
----
. 距離設定を確認します。
+
portbuffershow

+
LE の距離レベルは 10 km と表示されます

+
次の例は、ポート 20 とポート 21 上の ISL を使用する構成の出力です。

+
[listing]
----
FC_switch_A_1:admin> portbuffershow

User  Port     Lx      Max/Resv    Buffer Needed    Link      Remaining
Port  Type    Mode     Buffers     Usage  Buffers   Distance  Buffers
----  ----    ----     -------     ------ -------   --------- ---------
...
 20     E      -          8         67      67       30km
 21     E      -          8         67      67       30km
...
 23            -          8          0      -        -        466
----
. 両方のスイッチが 1 つのファブリックを形成することを確認します。
+
'witchshow'

+
次の例は、ポート 20 とポート 21 上の ISL を使用する構成の出力です。

+
[listing]
----
FC_switch_A_1:admin> switchshow
switchName: FC_switch_A_1
switchType: 109.1
switchState:Online
switchMode: Native
switchRole: Subordinate
switchDomain:       5
switchId:   fffc01
switchWwn:  10:00:00:05:33:86:89:cb
zoning:             OFF
switchBeacon:       OFF

Index Port Address Media Speed State  Proto
===========================================
...
20   20  010C00   id    16G  Online FC  LE E-Port  10:00:00:05:33:8c:2e:9a "FC_switch_B_1" (downstream)(trunk master)
21   21  010D00   id    16G  Online FC  LE E-Port  (Trunk port, master is Port 20)
...

FC_switch_B_1:admin> switchshow
switchName: FC_switch_B_1
switchType: 109.1
switchState:Online
switchMode: Native
switchRole: Principal
switchDomain:       7
switchId:   fffc03
switchWwn:  10:00:00:05:33:8c:2e:9a
zoning:             OFF
switchBeacon:       OFF

Index Port Address Media Speed State Proto
==============================================
...
20   20  030C00   id    16G  Online  FC  LE E-Port  10:00:00:05:33:86:89:cb "FC_switch_A_1" (downstream)(Trunk master)
21   21  030D00   id    16G  Online  FC  LE E-Port  (Trunk port, master is Port 20)
...
----
. ファブリックの設定を確認します。
+
「 fabricshow` 」

+
[listing]
----
FC_switch_A_1:admin> fabricshow
   Switch ID   Worldwide Name      Enet IP Addr FC IP Addr Name
-----------------------------------------------------------------
1: fffc01 10:00:00:05:33:86:89:cb 10.10.10.55  0.0.0.0    "FC_switch_A_1"
3: fffc03 10:00:00:05:33:8c:2e:9a 10.10.10.65  0.0.0.0   >"FC_switch_B_1"
----
+
[listing]
----
FC_switch_B_1:admin> fabricshow
   Switch ID   Worldwide Name     Enet IP Addr FC IP Addr   Name
----------------------------------------------------------------
1: fffc01 10:00:00:05:33:86:89:cb 10.10.10.55  0.0.0.0     "FC_switch_A_1"

3: fffc03 10:00:00:05:33:8c:2e:9a 10.10.10.65  0.0.0.0    >"FC_switch_B_1
----
. [step10_brocade_config]] ISL のトランキングを確認します。
+
「 trunkshow 」

+
** ISL でトランキングを設定する場合（ IOD の場合）は、次のような出力が表示されます。
+
[listing]
----
FC_switch_A_1:admin> trunkshow
 1: 20-> 20 10:00:00:05:33:ac:2b:13 3 deskew 15 MASTER
    21-> 21 10:00:00:05:33:8c:2e:9a 3 deskew 16
 FC_switch_B_1:admin> trunkshow
 1: 20-> 20 10:00:00:05:33:86:89:cb 3 deskew 15 MASTER
    21-> 21 10:00:00:05:33:86:89:cb 3 deskew 16
----
** ISL でトランキングを設定しない場合（ OOD の場合）は、次のような出力が表示されます。
+
[listing]
----
FC_switch_A_1:admin> trunkshow
 1: 20-> 20 10:00:00:05:33:ac:2b:13 3 deskew 15 MASTER
 2: 21-> 21 10:00:00:05:33:8c:2e:9a 3 deskew 16 MASTER
FC_switch_B_1:admin> trunkshow
 1: 20-> 20 10:00:00:05:33:86:89:cb 3 deskew 15 MASTER
 2: 21-> 21 10:00:00:05:33:86:89:cb 3 deskew 16 MASTER
----


. 繰り返します <<step1_brocade_config,手順 1.>> から <<step10_brocade_config,手順 10>> 2 つ目の FC スイッチファブリック。


.関連情報
link:concept_port_assignments_for_fc_switches_when_using_ontap_9_1_and_later.html["ONTAP 9.1 以降を使用している場合の FC スイッチのポート割り当て"]



== Brocade FC 7840 スイッチでの 10Gbps VE ポートの設定

ISL に 10Gbps VE ポート（ FCIP を使用）を使用する場合は、各ポートに IP インターフェイスを作成し、 FCIP トンネルと各トンネルの回線を設定する必要があります。

.このタスクについて
この手順は、 MetroCluster 構成の各スイッチファブリックで実行する必要があります。

この手順の例では、 2 つの Brocade 7840 スイッチの IP アドレスを次のように想定しています。

* ローカルが FC_switch_A_1 。
* リモートが FC_switch_B_1 。


.手順
. ファブリック内の両方のスイッチに 10Gbps ポートの IP インターフェイス（ ipif ）アドレスを作成します。
+
'portcfg ipif FC_switch1_namefirst_port_name create FC_switch1_ip_address netmask netmask_number vlan 2 mtu auto

+
次のコマンドは、 FC_switch_A_1 のポート GE2.dp0 および ge3.dp0 に ipif アドレスを作成します。

+
[listing]
----
portcfg ipif  ge2.dp0 create  10.10.20.71 netmask 255.255.0.0 vlan 2 mtu auto
portcfg ipif  ge3.dp0 create  10.10.21.71 netmask 255.255.0.0 vlan 2 mtu auto
----
+
次のコマンドは、 FC_switch_B_1 のポート GE2.dp0 および ge3.dp0 に ipif アドレスを作成します。

+
[listing]
----
portcfg ipif  ge2.dp0 create  10.10.20.72 netmask 255.255.0.0 vlan 2 mtu auto
portcfg ipif  ge3.dp0 create  10.10.21.72 netmask 255.255.0.0 vlan 2 mtu auto
----
. 両方のスイッチに ipif アドレスが作成されたことを確認します。
+
"portShow ipif all`

+
次のコマンドは、スイッチ FC_switch_A_1 の ipif アドレスを表示します。

+
[listing]
----
FC_switch_A_1:root> portshow ipif all

 Port         IP Address                     / Pfx  MTU   VLAN  Flags
--------------------------------------------------------------------------------
 ge2.dp0      10.10.20.71                    / 24   AUTO  2     U R M I
 ge3.dp0      10.10.21.71                    / 20   AUTO  2     U R M I
--------------------------------------------------------------------------------
Flags: U=Up B=Broadcast D=Debug L=Loopback P=Point2Point R=Running I=InUse
       N=NoArp PR=Promisc M=Multicast S=StaticArp LU=LinkUp X=Crossport
----
+
次のコマンドは、スイッチ FC_switch_B_1 の ipif アドレスを表示します。

+
[listing]
----
FC_switch_B_1:root> portshow ipif all

 Port         IP Address                     / Pfx  MTU   VLAN  Flags
--------------------------------------------------------------------------------
 ge2.dp0      10.10.20.72                    / 24   AUTO  2     U R M I
 ge3.dp0      10.10.21.72                    / 20   AUTO  2     U R M I
--------------------------------------------------------------------------------
Flags: U=Up B=Broadcast D=Debug L=Loopback P=Point2Point R=Running I=InUse
       N=NoArp PR=Promisc M=Multicast S=StaticArp LU=LinkUp X=Crossport
----
. dp0 のポートを使用して、 2 つの FCIP トンネルのうちの 1 つ目のトンネルを作成します。
+
"portcfg fciptunnel

+
このコマンドは、単一回線のトンネルを作成します。

+
次のコマンドは、スイッチ FC_switch_A_1 にトンネルを作成します。

+
[listing]
----
portcfg fciptunnel 24 create -S 10.10.20.71  -D 10.10.20.72 -b 10000000 -B 10000000
----
+
次のコマンドは、スイッチ FC_switch_B_1 にトンネルを作成します。

+
[listing]
----
portcfg fciptunnel 24 create -S 10.10.20.72  -D 10.10.20.71 -b 10000000 -B 10000000
----
. FCIP トンネルが作成されたことを確認します。
+
'portShow fciptunnel all

+
次の例は、トンネルが作成され、回線が稼働していることを示しています。

+
[listing]
----
FC_switch_B_1:root>

 Tunnel Circuit  OpStatus  Flags    Uptime  TxMBps  RxMBps ConnCnt CommRt Met/G
--------------------------------------------------------------------------------
 24    -         Up      ---------     2d8m    0.05    0.41   3      -       -
--------------------------------------------------------------------------------
 Flags (tunnel): i=IPSec f=Fastwrite T=TapePipelining F=FICON r=ReservedBW
                 a=FastDeflate d=Deflate D=AggrDeflate P=Protocol
                 I=IP-Ext
----
. DP0 の追加の回線を作成します。
+
次のコマンドは、スイッチ FC_switch_A_1 に dp0 の回線を作成します。

+
[listing]
----
portcfg fcipcircuit 24 create 1 -S 10.10.21.71 -D 10.10.21.72  --min-comm-rate 5000000 --max-comm-rate 5000000
----
+
次のコマンドは、スイッチ FC_switch_A_1 に dp0 の回線を作成します。

+
[listing]
----
portcfg fcipcircuit 24 create 1 -S 10.10.21.72 -D 10.10.21.71  --min-comm-rate 5000000 --max-comm-rate 5000000
----
. すべての回線が正常に作成されたことを確認します。
+
'portShow fcipcircuit all

+
次のコマンドは、回線とそのステータスを表示します。

+
[listing]
----
FC_switch_A_1:root> portshow fcipcircuit all

 Tunnel Circuit  OpStatus  Flags    Uptime  TxMBps  RxMBps ConnCnt CommRt Met/G
--------------------------------------------------------------------------------
 24    0 ge2     Up      ---va---4    2d12m    0.02    0.03   3 10000/10000 0/-
 24    1 ge3     Up      ---va---4    2d12m    0.02    0.04   3 10000/10000 0/-
--------------------------------------------------------------------------------
 Flags (circuit): h=HA-Configured v=VLAN-Tagged p=PMTU i=IPSec 4=IPv4 6=IPv6
                 ARL a=Auto r=Reset s=StepDown t=TimedStepDown  S=SLA
----




== Brocade 7810 および 7840 FC スイッチでの 40Gbps VE ポートの設定

ISL に 2 つの 40GbE VE ポート（ FCIP を使用）を使用する場合は、各ポートに IP インターフェイスを作成し、 FCIP トンネルと各トンネルの回線を設定する必要があります。

.このタスクについて
この手順は、 MetroCluster 構成の各スイッチファブリックで実行する必要があります。

この手順の例では、次の 2 つのスイッチを使用します。

* ローカルが FC_switch_A_1 。
* リモートが FC_switch_B_1 。


.手順
. ファブリック内の両方のスイッチに 40Gbps ポートの IP インターフェイス（ ipif ）アドレスを作成します。
+
'portcfg ipif FC_switch_nameefirst_port_name create FC_switch_ip_address netmask netmask_number VLAN 2 mtu auto`

+
次のコマンドは、 FC_switch_A_1 のポート ge0.dp0 および ge1.dp0 に ipif アドレスを作成します。

+
[listing]
----
portcfg ipif  ge0.dp0 create  10.10.82.10 netmask 255.255.0.0 vlan 2 mtu auto
portcfg ipif  ge1.dp0 create  10.10.82.11 netmask 255.255.0.0 vlan 2 mtu auto
----
+
次のコマンドは、 FC_switch_B_1 のポート ge0.dp0 および ge1.dp0 に ipif アドレスを作成します。

+
[listing]
----
portcfg ipif  ge0.dp0 create  10.10.83.10 netmask 255.255.0.0 vlan 2 mtu auto
portcfg ipif  ge1.dp0 create  10.10.83.11 netmask 255.255.0.0 vlan 2 mtu auto
----
. 両方のスイッチに ipif アドレスが作成されたことを確認します。
+
"portShow ipif all`

+
次の例は、 FC_switch_A_1 の IP インターフェイスを示しています。

+
[listing]
----
Port         IP Address                     / Pfx  MTU   VLAN  Flags
---------------------------------------------------------------------------
-----
 ge0.dp0      10.10.82.10                    / 16   AUTO  2     U R M
 ge1.dp0      10.10.82.11                    / 16   AUTO  2     U R M
--------------------------------------------------------------------------------
Flags: U=Up B=Broadcast D=Debug L=Loopback P=Point2Point R=Running I=InUse
       N=NoArp PR=Promisc M=Multicast S=StaticArp LU=LinkUp X=Crossport
----
+
次の例は、 FC_switch_B_1 の IP インターフェイスを示しています。

+
[listing]
----
Port         IP Address                     / Pfx  MTU   VLAN  Flags
--------------------------------------------------------------------------------
 ge0.dp0      10.10.83.10                    / 16   AUTO  2     U R M
 ge1.dp0      10.10.83.11                    / 16   AUTO  2     U R M
--------------------------------------------------------------------------------
Flags: U=Up B=Broadcast D=Debug L=Loopback P=Point2Point R=Running I=InUse
       N=NoArp PR=Promisc M=Multicast S=StaticArp LU=LinkUp X=Crossport
----
. 両方のスイッチに FCIP トンネルを作成します。
+
「 portconfig fciptunnel 」のように入力します

+
次のコマンドは、 FC_switch_A_1 にトンネルを作成します。

+
[listing]
----
portcfg fciptunnel 24 create -S 10.10.82.10  -D 10.10.83.10 -b 10000000 -B 10000000
----
+
次のコマンドは、 FC_switch_B_1 にトンネルを作成します。

+
[listing]
----
portcfg fciptunnel 24 create -S 10.10.83.10  -D 10.10.82.10 -b 10000000 -B 10000000
----
. FCIP トンネルが作成されたことを確認します。
+
'portShow fciptunnel all

+
次の例は、トンネルが作成され、回線が稼働していることを示しています。

+
[listing]
----
FC_switch_A_1:root>

 Tunnel Circuit  OpStatus  Flags    Uptime  TxMBps  RxMBps ConnCnt CommRt Met/G
--------------------------------------------------------------------------------
 24    -         Up      ---------     2d8m    0.05    0.41   3      -       -
 --------------------------------------------------------------------------------
 Flags (tunnel): i=IPSec f=Fastwrite T=TapePipelining F=FICON r=ReservedBW
                 a=FastDeflate d=Deflate D=AggrDeflate P=Protocol
                 I=IP-Ext
----
. 各スイッチに追加の回線を作成します。
+
'portcfg fcipcircuit 24 create 1-S source-ip-address -D destination-ip-address --min-comm-rate 10000000 --max-comm-rate 10000000

+
次のコマンドは、スイッチ FC_switch_A_1 に dp0 の回線を作成します。

+
[listing]
----
portcfg fcipcircuit 24  create 1 -S 10.10.82.11 -D 10.10.83.11  --min-comm-rate 10000000 --max-comm-rate 10000000
----
+
次のコマンドは、スイッチ FC_switch_A_1 に DP1 の回線を作成します。

+
[listing]
----
portcfg fcipcircuit 24 create 1  -S 10.10.83.11 -D 10.10.82.11  --min-comm-rate 10000000 --max-comm-rate 10000000
----
. すべての回線が正常に作成されたことを確認します。
+
'portShow fcipcircuit all

+
次の例は、回線をリストしたもので、それぞれの OpStatus が Up であることを示しています。

+
[listing]
----
FC_switch_A_1:root> portshow fcipcircuit all

 Tunnel Circuit  OpStatus  Flags    Uptime  TxMBps  RxMBps ConnCnt CommRt Met/G
--------------------------------------------------------------------------------
 24    0 ge0     Up      ---va---4    2d12m    0.02    0.03   3 10000/10000 0/-
 24    1 ge1     Up      ---va---4    2d12m    0.02    0.04   3 10000/10000 0/-
 --------------------------------------------------------------------------------
 Flags (circuit): h=HA-Configured v=VLAN-Tagged p=PMTU i=IPSec 4=IPv4 6=IPv6
                 ARL a=Auto r=Reset s=StepDown t=TimedStepDown  S=SLA
----




== Brocade スイッチでの非 E ポートの設定

FC スイッチ上の非 E ポートを設定する必要があります。MetroCluster 構成では、これらのポートによって、スイッチと HBA イニシエータ、 FC-VI インターコネクト、および FC-to-SAS ブリッジが接続されます。この手順はポートごとに実行する必要があります。

.このタスクについて
次の例では、ポートを FC-to-SAS ブリッジに接続します。

--
* Site_A の FC_FC_switch_A_1 のポート 6
* Site_B の FC_FC_switch_B_1 のポート 6


--
.手順
. 非 E ポートの速度を設定します。
+
portcfgspeed portSpeed

+
データパス内のすべてのコンポーネント（ SFP 、 SFP が設置されているスイッチポート、 HBA 、ブリッジなどの接続デバイス）でサポートされている最高速度を使用する必要があります。

+
たとえば、各コンポーネントで次の速度がサポートされているとします。

+
** SFP は 4GB 、 8GB 、 16GB に対応
** スイッチポートは 4GB 、 8GB 、 16GB に対応
** 接続されている HBA の最高速度は 16GBこの場合の共通最高速度は 16GB であるため、ポート速度は 16GB に設定する必要があります。
+
[listing]
----
FC_switch_A_1:admin> portcfgspeed 6 16

FC_switch_B_1:admin> portcfgspeed 6 16
----


. 設定を確認します。
+
portcfgshow

+
[listing]
----
FC_switch_A_1:admin> portcfgshow

FC_switch_B_1:admin> portcfgshow
----
+
この出力例では、ポート 6 に次の設定があり、速度は 16G に設定されています。

+
[listing]
----
Ports of Slot 0                     0   1   2   3   4   5   6   7   8
-------------------------------------+---+---+---+--+---+---+---+---+--
Speed                               16G 16G 16G 16G 16G 16G 16G 16G 16G
AL_PA Offset 13                     ..  ..  ..  ..  ..  ..  ..  ..  ..
Trunk Port                          ..  ..  ..  ..  ..  ..  ..  ..  ..
Long Distance                       ..  ..  ..  ..  ..  ..  ..  ..  ..
VC Link Init                        ..  ..  ..  ..  ..  ..  ..  ..  ..
Locked L_Port                       -   -   -   -   -  -   -   -   -
Locked G_Port                       ..  ..  ..  ..  ..  ..  ..  ..  ..
Disabled E_Port                     ..  ..  ..  ..  ..  ..  ..  ..  ..
Locked E_Port                       ..  ..  ..  ..  ..  ..  ..  ..  ..
ISL R_RDY Mode                      ..  ..  ..  ..  ..  ..  ..  .. ..
RSCN Suppressed                     ..  ..  ..  ..  ..  ..  ..  .. ..
Persistent Disable                  ..  ..  ..  ..  ..  ..  ..  .. ..
LOS TOV enable                      ..  ..  ..  ..  ..  ..  ..  .. ..
NPIV capability                     ON  ON  ON  ON  ON  ON  ON  ON  ON
NPIV PP Limit                       126 126 126 126 126 126 126 126 126
QOS Port                            AE  AE  AE  AE  AE  AE  AE  AE  ON
EX Port                             ..  ..  ..  ..  ..  ..  ..  ..  ..
Mirror Port                         ..  ..  ..  ..  ..  ..  ..  ..  ..
Rate Limit                          ..  ..  ..  ..  ..  ..  ..  ..  ..
Credit Recovery                     ON  ON  ON  ON  ON  ON  ON  ON  ON
Fport Buffers                       ..  ..  ..  ..  ..  ..  ..  ..  ..
Eport Credits                       ..  ..  ..  ..  ..  ..  ..  ..  ..
Port Auto Disable                   ..  ..  ..  ..  ..  ..  ..  ..  ..
CSCTL mode                          ..  ..  ..  ..  ..  ..  ..  ..  ..
D-Port mode                         ..  ..  ..  ..  ..  ..  ..  ..  ..
D-Port over DWDM                    ..  ..  ..  ..  ..  ..  ..  ..  ..
FEC                                 ON  ON  ON  ON  ON  ON  ON  ON  ON
Fault Delay                         0   0   0   0   0   0   0   0   0
Non-DFE                             ..  ..  ..  ..  ..  ..  ..  ..  ..
----




== Brocade G620 スイッチの ISL ポートで圧縮を設定します

Brocade G620 スイッチを使用している場合に ISL で圧縮を有効にするには、スイッチの各 E ポートで圧縮を設定する必要があります。

.このタスクについて
このタスクは、 ISL を使用する両方のスイッチの ISL ポートで実行する必要があります。

.手順
. 圧縮を設定するポートを無効にします。
+
portdisable port-id`

. ポートで圧縮を有効にします。
+
portCfgCompress -- ポート ID を有効にします

. ポートを有効にして圧縮の設定をアクティブにします。
+
portEnable port-id`

. 設定が変更されたことを確認します。
+
portcfgshow port-id`



次の例は、ポート 0 で圧縮を有効にします。

[listing]
----
FC_switch_A_1:admin> portdisable 0
FC_switch_A_1:admin> portcfgcompress --enable 0
FC_switch_A_1:admin> portenable 0
FC_switch_A_1:admin> portcfgshow 0
Area Number: 0
Octet Speed Combo: 3(16G,10G)
(output truncated)
D-Port mode: OFF
D-Port over DWDM ..
Compression: ON
Encryption: ON
----
islShow コマンドを使用すると、暗号化または圧縮が設定され、アクティブになった状態で E_port がオンラインになったことを確認できます。

[listing]
----
FC_switch_A_1:admin> islshow
  1: 0-> 0 10:00:c4:f5:7c:8b:29:86   5 FC_switch_B_1
sp: 16.000G bw: 16.000G TRUNK QOS CR_RECOV ENCRYPTION COMPRESSION
----
portEncCompShow コマンドを使用すると、アクティブなポートを確認できます。この例では、ポート 0 で暗号化と圧縮が設定され、アクティブになっています。

[listing]
----
FC_switch_A_1:admin> portenccompshow
User	  Encryption		           Compression	         Config
Port   Configured    Active   Configured   Active  Speed
----   ----------    -------  ----------   ------  -----
  0	   Yes	          Yes	     Yes	         Yes	    16G
----


== Brocade FC スイッチでゾーニングを設定します

スイッチポートを別々のゾーンに割り当てて、コントローラとストレージのトラフィックを分離する必要があります。手順は、 FibreBridge 7500N ブリッジと FibreBridge 6500N ブリッジのどちらを使用しているかによって異なります。



=== FC-VI ポートのゾーニング

MetroCluster の DR グループごとに、コントローラ間のトラフィックに使用する FC-VI 接続のゾーンを 2 つ設定する必要があります。これらのゾーンには、コントローラモジュールの FC-VI ポートに接続する FC スイッチポートが含まれます。これらのゾーンは、 Quality of Service （ QoS ；サービス品質）ゾーンです。

QoS ゾーンには、通常のゾーンと区別するために、プレフィックス QOSHid_ から始まる名前を使用します。これらの QoS ゾーンは、使用する FibreBridge ブリッジのモデルに関係なく同じです。

各ゾーンには、各コントローラの FC-VI ケーブルごとに 1 つ、すべての FC-VI ポートが含まれます。これらのゾーンには高い優先度が設定されています。

次の表に、 2 つの DR グループの FC-VI ゾーンを示します。

* DR グループ 1 ： FC-VI ポート a / c * の QOSH1 FC-VI ゾーン

|===
| FC スイッチ | サイト | スイッチドメイン | 6505 / 6510 ポート | 6520 ポート | G620 ポート | 接続先 


| FC_switch_A_1 を使用します | A | 5. | 0 | 0 | 0 | controller_A_1 のポート FC-VI a 


| FC_switch_A_1 を使用します | A | 5. | 1. | 1. | 1. | controller_A_1 のポート FC-VI c 


| FC_switch_A_1 を使用します | A | 5. | 4. | 4. | 4. | controller_A_2 、 FC-VI a 


| FC_switch_A_1 を使用します | A | 5. | 5. | 5. | 5. | controller_A_2 、 FC-VI c ポート 


| FC_switch_B_1 | B | 7. | 0 | 0 | 0 | controller_B_1 、ポート FC-VI a 


| FC_switch_B_1 | B | 7. | 1. | 1. | 1. | controller_B_1 、ポート FC-VI c 


| FC_switch_B_1 | B | 7. | 4. | 4. | 4. | controller_B_2 、ポート FC-VI a 


| FC_switch_B_1 | B | 7. | 5. | 5. | 5. | controller_B_2 、ポート FC-VI c 
|===
|===


| Fabric_1 のゾーン | メンバーポート 


| QOSH1_MC1_FAB_1_FCVI | 5 、 0 ； 5 、 1 ； 5 、 4 ； 5 、 5 ； 7 、 0 ； 7 、 1 ； 7 、 4 ； 7 、 5 
|===
* DR グループ 1 ： FC-VI ポート b / d * の QOSH1 FC-VI ゾーン

|===
| FC スイッチ | サイト | スイッチドメイン | 6505 / 6510 ポート | 6520 ポート | G620 ポート | 接続先 


| FC_switch_A_2 | A | 6. | 0 | 0 | 0 | controller_A_1 のポート FC-VI b 


|  |  |  | 1. | 1. | 1. | controller_A_1 のポート FC-VI d 


|  |  |  | 4. | 4. | 4. | controller_A_2 、 FC-VI b ポート 


|  |  |  | 5. | 5. | 5. | controller_A_2 、 FC-VI d ポート 


| FC_switch_B_2 | B | 8. | 0 | 0 | 0 | controller_B_1 、ポート FC-VI b 


|  |  |  | 1. | 1. | 1. | controller_B_1 、ポート FC-VI d 


|  |  |  | 4. | 4. | 4. | controller_B_2 、ポート FC-VI b 


|  |  |  | 5. | 5. | 5. | controller_B_2 、ポート FC-VI d 
|===
|===


| Fabric_1 のゾーン | メンバーポート 


| QOSH1_MC1_FAB_2_FCVI | 6 、 0 ； 6 、 1 ； 6 、 4 ； 6 、 5 ； 8 、 0 ； 8 、 1 ； 8 、 4 ； 8 、 5 
|===
* DR グループ 2 ： FC-VI ポート a / c * の QOSH2 FC-VI ゾーン

|===
| FC スイッチ | サイト | スイッチドメイン | スイッチポート |  |  | 接続先 


|  |  |  | 6510 | 6520 | G620 |  


| FC_switch_A_1 を使用します | A | 5. | 24 | 48 | 18 | controller_A_1 のポート FC-VI a 


|  |  |  | 25 | 49 | 19 | controller_A_1 のポート FC-VI c 


|  |  |  | 28 | 52 | 22 | controller_A_2 、 FC-VI a 


|  |  |  | 29 | 53 | 23 | controller_A_1 のポート FC-VI c 


| FC_switch_B_1 | B | 7. | 24 | 48 | 18 | controller_B_2 、ポート FC-VI a 


|  |  |  | 25 | 49 | 19 | controller_B_2 、ポート FC-VI c 


|  |  |  | 28 | 52 | 22 | controller_B_2 、ポート FC-VI a 


|  |  |  | 29 | 53 | 23 | controller_B_2 、ポート FC-VI c 
|===
|===


| Fabric_1 のゾーン | メンバーポート 


| QOSH2_MC2_FAB_1_FCVI （ 6510 ） | 5 、 24 ； 5 、 25 ； 5 、 28 ； 5 、 29 ； 7 、 24 ； 7 、 25 ； 7 、 28 ； 7 、 29 


| QOSH2_MC2_FAB_1_FCVI （ 6520 ） | 5 、 48 ； 5 、 49 ； 5 、 52 ； 5 、 53 ； 7 、 48 ； 7 、 49 ； 7 、 52 ； 7 、 53 
|===
* DR グループ 2 ： FC-VI ポート b / d * の QOSH2 FC-VI ゾーン

|===
| FC スイッチ | サイト | スイッチドメイン | 6510 ポート | 6520 ポート | G620 ポート | 接続先 


| FC_switch_A_2 | A | 6. | 24 | 48 | 18 | controller_A_1 のポート FC-VI b 


| FC_switch_A_2 | A | 6. | 25 | 49 | 19 | controller_A_1 のポート FC-VI d 


| FC_switch_A_2 | A | 6. | 28 | 52 | 22 | controller_A_1 のポート FC-VI b 


| FC_switch_A_2 | A | 6. | 29 | 53 | 23 | controller_A_1 のポート FC-VI d 


| FC_switch_B_2 | B | 8. | 24 | 48 | 18 | controller_B_2 、ポート FC-VI b 


| FC_switch_B_2 | B | 8. | 25 | 49 | 19 | controller_B_2 、ポート FC-VI d 


| FC_switch_B_2 | B | 8. | 28 | 52 | 22 | controller_B_2 、ポート FC-VI b 


| FC_switch_B_2 | B | 8. | 29 | 53 | 23 | controller_B_2 、ポート FC-VI d 
|===
|===


| Fabric_2 のゾーン | メンバーポート 


| QOSH2_MC2_FAB_2_FCVI （ 6510 ） | 6 、 24 、 6 、 25 、 6 、 28 、 6 、 29 、 8 、 24 、 8 、 25 、 8 、 28 、 8 、 29 


| QOSH2_MC2_FAB_2_FCVI （ 6520 ） | 6 、 48 、 6 、 49 、 6 、 52 、 6 、 53 、 8 、 48 、 8 、 49 、 8 、 52 、 8 、 53 
|===
次の表に、 FC-VI ゾーンをまとめます。

|===


| ファブリック | ゾーン名 | メンバーポート 


.3+| FC_switch_A_1 および FC_switch_B_1  a| 
QOSH1_MC1_FAB_1_FCVI
 a| 
5 、 0 ； 5 、 1 ； 5 、 4 ； 5 、 5 ； 7 、 0 ； 7 、 1 ； 7 、 4 ； 7 、 5



 a| 
QOSH2_MC1_FAB_1_FCVI （ 6510 ）
 a| 
5 、 24 ； 5 、 25 ； 5 、 28 ； 5 、 29 ； 7 、 24 ； 7 、 25 ； 7 、 28 ； 7 、 29



 a| 
QOSH2_MC1_FAB_1_FCVI （ 6520 ）
 a| 
5 、 48 ； 5 、 49 ； 5 、 52 ； 5 、 53 ； 7 、 48 ； 7 、 49 ； 7 、 52 ； 7 、 53



.3+| FC_switch_A_2 と FC_switch_B_2  a| 
QOSH1_MC1_FAB_2_FCVI
 a| 
6 、 0 ； 6 、 1 ； 6 、 4 ； 6 、 5 ； 8 、 0 ； 8 、 1 ； 8 、 4 ； 8 、 5



 a| 
QOSH2_MC1_FAB_2_FCVI （ 6510 ）
 a| 
6 、 24 、 6 、 25 、 6 、 28 、 6 、 29 、 8 、 24 、 8 、 25 、 8 、 28 、 8 、 29



 a| 
QOSH2_MC1_FAB_2_FCVI （ 6520 ）
 a| 
6 、 48 、 6 、 49 、 6 、 52 、 6 、 53 、 8 、 48 、 8 、 49 、 8 、 52 、 8 、 53

|===


=== FibreBridge 6500N ブリッジまたは 1 つの FC ポートを使用する FibreBridge 7500N / 7600N ブリッジのゾーニング

FibreBridge 6500N ブリッジまたは一方の FC ポートのみを使用する FibreBridge 7500N / 7600N ブリッジを使用する場合は、ブリッジポート用のストレージゾーンを作成する必要があります。ゾーンを設定する前に、ゾーンおよび関連するポートについて理解しておく必要があります。

ここでは、 DR グループ 1 のゾーニング例のみを示しています。2 つ目の DR グループがある構成の場合は、コントローラとブリッジの対応するポートを使用して、同じ方法で 2 つ目の DR グループのゾーニングを設定します。



==== 必要なゾーン

FC-to-SAS ブリッジの FC ポートごとにゾーンを 1 つ設定し、各コントローラモジュールのイニシエータとその FC-to-SAS ブリッジの間のトラフィックを許可する必要があります。

各ストレージゾーンに 9 つのポートが含まれます。

* HBA イニシエータポート × 8 （コントローラごとに 2 つの接続）
* FC-to-SAS ブリッジの FC ポートに接続するポート × 1


ストレージゾーンでは標準のゾーニングを使用します。

例では、各サイトの 2 つのスタックグループを接続する 2 組のブリッジのペアを示します。各ブリッジが 1 つの FC ポートを使用するため、ファブリックあたりのストレージゾーン数は 4 個（合計 8 個）になります。



==== ブリッジ名

ブリッジでは、次の名前の例を使用します。 bridge_site_B 、スタックグループペア内での指定

|===


| 名前の各部分 | 特定のインターフェイス | 有効な値 


 a| 
サイト
 a| 
ブリッジペアが物理的に配置されているサイト。
 a| 
A または B



 a| 
スタックグループ
 a| 
ブリッジペアが接続されているスタックグループの番号。

* FibreBridge 7600N / 7500N ブリッジでは、スタックグループで最大 4 個のスタックがサポートされます。
+
スタックグループに含めることができるストレージシェルフは 10 個までです。

* FibreBridge 6500N ブリッジでは、スタックグループでサポートされるスタックは 1 つだけです。

 a| 
1 、 2 など



 a| 
ペア内の場所
 a| 
ブリッジペア内のブリッジ。ブリッジのペアは、特定のスタックグループに接続します。
 a| 
a または b

|===
各サイトの 1 つのスタックグループのブリッジ名の例：

* bridge_A_1a
* bridge_A_1b
* bridge_B_1a
* bridge_B_1b




==== DR グループ 1 - Site_A のスタック 1

* drgroup 1 ： MC1_INIT_GRP_1_SITE_A_STK_GRP_1_TOP_FC1 ： *

|===
| FC スイッチ | サイト | スイッチドメイン | Brocade 6505 、 6510 、 6520 、 G620 、または G610 スイッチポート | 接続先 


| FC_switch_A_1 を使用します | A | 5. | 2. | controller_A_1 のポート 0a 


| FC_switch_A_1 を使用します | A | 5. | 3. | controller_A_1 のポート 0c 


| FC_switch_A_1 を使用します | A | 5. | 6. | controller_A_2 、ポート 0a 


| FC_switch_A_1 を使用します | A | 5. | 7. | controller_A_2 、ポート 0c 


| FC_switch_A_1 を使用します | A | 5. | 8. | bridge_A_1a の FC1 


| FC_switch_B_1 | B | 7. | 2. | controller_B_1 、ポート 0a 


| FC_switch_B_1 | B | 7. | 3. | controller_B_1 、ポート 0c 


| FC_switch_B_1 | B | 7. | 6. | controller_B_2 、ポート 0a 


| FC_switch_B_1 | B | 7. | 7. | controller_B_2 、ポート 0c 
|===
|===


| Fabric_1 のゾーン | メンバーポート 


| MC1_INIT_GRP_1_SITE_A_STK_GRP_1_TOP_FC1 | 5 、 2 ； 5 、 3 ； 5 、 6 ； 5 、 7 ； 7 、 2 ； 7 、 3 ； 7 、 7 ； 5 、 8 
|===
* drgroup 1 ： MC1_INIT_GRP_1_SITE_A_STK_GRP_1_BOT_FC1 ： *

|===
| FC スイッチ | サイト | スイッチドメイン | Brocade 6505 、 6510 、 6520 、 G620 、または G610 スイッチポート | 接続先 


| FC_switch_A_1 を使用します | A | 6. | 2. | controller_A_1 のポート 0b 


| FC_switch_A_1 を使用します | A | 6. | 3. | controller_A_1 のポート 0d 


| FC_switch_A_1 を使用します | A | 6. | 6. | controller_A_2 、ポート 0b 


| FC_switch_A_1 を使用します | A | 6. | 7. | controller_A_2 、ポート 0d 


| FC_switch_A_1 を使用します | A | 6. | 8. | bridge_A_1b の FC1 


| FC_switch_B_1 | B | 8. | 2. | controller_B_1 、ポート 0b 


| FC_switch_B_1 | B | 8. | 3. | controller_B_1 、ポート 0d 


| FC_switch_B_1 | B | 8. | 6. | controller_B_2 、ポート 0b 


| FC_switch_B_1 | B | 8. | 7. | controller_B_2 、ポート 0d 
|===
|===


| Fabric_2 のゾーン | メンバーポート 


| MC1_INIT_GRP_1_SITE_A_STK_GRP_1_BOT_FC1 | 6 、 2 ； 6 、 3 ； 6 ； 6 、 7 ； 8 、 2 ； 8 、 3 ； 8 、 6 ； 8 、 7 ； 6 、 8 
|===


==== DR グループ 1 - Site_A のスタック 2

* drgroup 1 ： MC1_INIT_GRP_1_SITE_A_STK_GRP_2_TOP_FC1 ： *

|===
| FC スイッチ | サイト | スイッチドメイン | Brocade 6505 、 6510 、 6520 、 G620 、または G610 スイッチポート | 接続先 


| FC_switch_A_1 を使用します | A | 5. | 2. | controller_A_1 のポート 0a 


| FC_switch_A_1 を使用します | A | 5. | 3. | controller_A_1 のポート 0c 


| FC_switch_A_1 を使用します | A | 5. | 6. | controller_A_2 、ポート 0a 


| FC_switch_A_1 を使用します | A | 5. | 7. | controller_A_2 、ポート 0c 


| FC_switch_A_1 を使用します | A | 5. | 9. | bridge_A_2a の FC1 


| FC_switch_B_1 | B | 7. | 2. | controller_B_1 、ポート 0a 


| FC_switch_B_1 | B | 7. | 3. | controller_B_1 、ポート 0c 


| FC_switch_B_1 | B | 7. | 6. | controller_B_2 、ポート 0a 


| FC_switch_B_1 | B | 7. | 7. | controller_B_2 、ポート 0c 
|===
|===


| Fabric_1 のゾーン | メンバーポート 


| MC1_INIT_GRP_1_SITE_A_STK_GRP_2_TOP_FC1 | 5 、 2 ； 5 、 3 ； 5 、 6 ； 5 、 7 ； 7 、 2 ； 7 、 3 ； 7 、 7 ； 5 、 9 
|===
* drgroup 1 ： MC1_INIT_GRP_1_SITE_A_STK_GRP_2_BOT_FC1 ： *

|===
| FC スイッチ | サイト | スイッチドメイン | Brocade 6505 、 6510 、 6520 、 G620 、または G610 スイッチポート | 接続先 


| FC_switch_A_1 を使用します | A | 6. | 2. | controller_A_1 のポート 0b 


| FC_switch_A_1 を使用します | A | 6. | 3. | controller_A_1 のポート 0d 


| FC_switch_A_1 を使用します | A | 6. | 6. | controller_A_2 、ポート 0b 


| FC_switch_A_1 を使用します | A | 6. | 7. | controller_A_2 、ポート 0d 


| FC_switch_A_1 を使用します | A | 6. | 9. | bridge_A_2b の FC1 


| FC_switch_B_1 | B | 8. | 2. | controller_B_1 、ポート 0b 


| FC_switch_B_1 | B | 8. | 3. | controller_B_1 、ポート 0d 


| FC_switch_B_1 | B | 8. | 6. | controller_B_2 、ポート 0b 


| FC_switch_B_1 | B | 8. | 7. | controller_B_2 、ポート 0d 
|===
|===


| Fabric_2 のゾーン | メンバーポート 


| MC1_INIT_GRP_1_SITE_A_STK_GRP_2_BOT_FC1 | 6 、 2 ； 6 、 3 ； 6 ； 6 、 7 ； 8 、 2 ； 8 、 3 ； 8 、 6 ； 8 、 7 ； 6 、 9 
|===


==== DR グループ 1 - Site_B のスタック 1

* MC1_INIT_GRP_1_SITE_B_STK_GRP_1_TOP_FC1 ： *

|===
| FC スイッチ | サイト | スイッチドメイン | Brocade 6505 、 6510 、 6520 、 G620 、または G610 スイッチ | 接続先 


| FC_switch_A_1 を使用します | A | 5. | 2. | controller_A_1 のポート 0a 


| FC_switch_A_1 を使用します | A | 5. | 3. | controller_A_1 のポート 0c 


| FC_switch_A_1 を使用します | A | 5. | 6. | controller_A_2 、ポート 0a 


| FC_switch_A_1 を使用します | A | 5. | 7. | controller_A_2 、ポート 0c 


| FC_switch_B_1 | B | 7. | 2. | controller_B_1 、ポート 0a 


| FC_switch_B_1 | B | 7. | 3. | controller_B_1 、ポート 0c 


| FC_switch_B_1 | B | 7. | 6. | controller_B_2 、ポート 0a 


| FC_switch_B_1 | B | 7. | 7. | controller_B_2 、ポート 0c 


| FC_switch_B_1 | B | 7. | 8. | bridge_B_1a の FC1 
|===
|===


| Fabric_1 のゾーン | メンバーポート 


| MC1_INIT_GRP_1_SITE_B_STK_GRP_1_TOP_FC1 | 5 、 2 ； 5 、 3 ； 5 、 6 ； 5 、 7 ； 7 、 2 ； 7 、 3 ； 7 、 6 ； 7 、 8 
|===
* drgroup 1 ： MC1_INIT_GRP_1_SITE_B_STK_GRP_1_BOT_FC1 ： *

|===
| FC スイッチ | サイト | スイッチドメイン | Brocade 6505 、 6510 、 6520 、 G620 、または G610 スイッチ | 接続先 


| FC_switch_A_1 を使用します | A | 6. | 2. | controller_A_1 のポート 0b 


| FC_switch_A_1 を使用します | A | 6. | 3. | controller_A_1 のポート 0d 


| FC_switch_A_1 を使用します | A | 6. | 6. | controller_A_2 、ポート 0b 


| FC_switch_A_1 を使用します | A | 6. | 7. | controller_A_2 、ポート 0d 


| FC_switch_B_1 | B | 8. | 2. | controller_B_1 、ポート 0b 


| FC_switch_B_1 | B | 8. | 3. | controller_B_1 、ポート 0d 


| FC_switch_B_1 | B | 8. | 6. | controller_B_2 、ポート 0b 


| FC_switch_B_1 | B | 8. | 7. | controller_B_2 、ポート 0d 


| FC_switch_B_1 | B | 8. | 8. | bridge_B_1b の FC1 
|===
|===


| Fabric_2 のゾーン | メンバーポート 


| MC1_INIT_GRP_1_SITE_B_STK_GRP_1_BOT_FC1 | 5 、 2 ； 5 、 3 ； 5 、 6 ； 5 、 7 ； 7 、 2 ； 7 、 3 ； 7 、 6 ； 7 、 7 ； 8 
|===


==== DR グループ 1 - Site_B のスタック 2

* drgroup 1 ： MC1_INIT_GRP_1_SITE_B_STK_GRP_2_TOP_FC1 ： *

|===
| FC スイッチ | サイト | スイッチドメイン | Brocade 6505 、 6510 、 6520 、 G620 、または G610 スイッチポート | 接続先 


| FC_switch_A_1 を使用します | A | 5. | 2. | controller_A_1 のポート 0a 


| FC_switch_A_1 を使用します | A | 5. | 3. | controller_A_1 のポート 0c 


| FC_switch_A_1 を使用します | A | 5. | 6. | controller_A_2 、ポート 0a 


| FC_switch_A_1 を使用します | A | 5. | 7. | controller_A_2 、ポート 0c 


| FC_switch_B_1 | B | 7. | 2. | controller_B_1 、ポート 0a 


| FC_switch_B_1 | B | 7. | 3. | controller_B_1 、ポート 0c 


| FC_switch_B_1 | B | 7. | 6. | controller_B_2 、ポート 0a 


| FC_switch_B_1 | B | 7. | 7. | controller_B_2 、ポート 0c 


| FC_switch_B_1 | B | 7. | 9. | bridge_B_2a の FC1 
|===
|===


| Fabric_1 のゾーン | メンバーポート 


| MC1_INIT_GRP_1_SITE_b_STK_GRP_2_TOP_FC1 | 5 、 2 ； 5 、 3 ； 5 、 6 ； 5 、 7 ； 7 、 2 ； 7 、 3 ； 7 、 6 ； 7 、 9 
|===
* drgroup 1 ： MC1_INIT_GRP_1_SITE_B_STK_GRP_2_BOT_FC1 ： *

|===
| FC スイッチ | サイト | スイッチドメイン | Brocade 6505 、 6510 、 6520 、 G620 、または G610 スイッチポート | 接続先 


| FC_switch_A_1 を使用します | A | 6. | 2. | controller_A_1 のポート 0b 


| FC_switch_A_1 を使用します | A | 6. | 3. | controller_A_1 のポート 0d 


| FC_switch_A_1 を使用します | A | 6. | 6. | controller_A_2 、ポート 0b 


| FC_switch_A_1 を使用します | A | 6. | 7. | controller_A_2 、ポート 0d 


| FC_switch_B_1 | B | 8. | 2. | controller_B_1 、ポート 0b 


| FC_switch_B_1 | B | 8. | 3. | controller_B_1 、ポート 0d 


| FC_switch_B_1 | B | 8. | 6. | controller_B_2 、ポート 0b 


| FC_switch_B_1 | B | 8. | 7. | controller_B_2 、ポート 0d 


| FC_switch_B_1 | B | 8. | 9. | bridge_B_1b の FC1 
|===
|===


| Fabric_2 のゾーン | メンバーポート 


| MC1_INIT_GRP_1_SITE_B_STK_GRP_2_BOT_FC1 | 6 、 2 、 6 、 6 、 6 、 6 、 7 、 8 、 2 、 8 、 3 、 8 、 6 、 8 、 7 、 8 、 9 
|===


==== ストレージゾーンのサマリ

|===


| ファブリック | ゾーン名 | メンバーポート 


.4+| FC_switch_A_1 および FC_switch_B_1 | MC1_INIT_GRP_1_SITE_A_STK_GRP_1_TOP_FC1 | 5 、 2 ； 5 、 3 ； 5 、 6 ； 5 、 7 ； 7 、 2 ； 7 、 3 ； 7 、 7 ； 5 、 8 


| MC1_INIT_GRP_1_SITE_A_STK_GRP_2_TOP_FC1 | 5 、 2 ； 5 、 3 ； 5 、 6 ； 5 、 7 ； 7 、 2 ； 7 、 3 ； 7 、 7 ； 5 、 9 


| MC1_INIT_GRP_1_SITE_B_STK_GRP_1_TOP_FC1 | 5 、 2 ； 5 、 3 ； 5 、 6 ； 5 、 7 ； 7 、 2 ； 7 、 3 ； 7 、 6 ； 7 、 8 


| MC1_INIT_GRP_1_SITE_B_STK_GRP_2_TOP_FC1 | 5 、 2 ； 5 、 3 ； 5 、 6 ； 5 、 7 ； 7 、 2 ； 7 、 3 ； 7 、 6 ； 7 、 9 


.4+| FC_switch_A_2 と FC_switch_B_2 | MC1_INIT_GRP_1_SITE_A_STK_GRP_1_BOT_FC1 | 6 、 2 ； 6 、 3 ； 6 ； 6 、 7 ； 8 、 2 ； 8 、 3 ； 8 、 6 ； 8 、 7 ； 6 、 8 


| MC1_INIT_GRP_1_SITE_A_STK_GRP_2_BOT_FC1 | 6 、 2 ； 6 、 3 ； 6 ； 6 、 7 ； 8 、 2 ； 8 、 3 ； 8 、 6 ； 8 、 7 ； 6 、 9 


| MC1_INIT_GRP_1_SITE_B_STK_GRP_1_BOT_FC1 | 6 、 2 ； 6 、 3 ； 6 ； 6 、 7 ； 8 、 2 ； 8 、 3 ； 8 、 6 ； 8 、 7 ； 8 、 8 


| MC1_INIT_GRP_1_SITE_B_STK_GRP_2_BOT_FC1 | 6 、 2 、 6 、 6 、 6 、 6 、 7 、 8 、 2 、 8 、 3 、 8 、 6 、 8 、 7 、 8 、 9 
|===


=== 両方の FC ポートを使用する FibreBridge 7500N ブリッジのゾーニング

両方の FC ポートを使用する FibreBridge 7500N ブリッジを使用する場合は、ブリッジポートのストレージゾーンを作成する必要があります。ゾーンを設定する前に、ゾーンおよび関連するポートについて理解しておく必要があります。



==== 必要なゾーン

FC-to-SAS ブリッジの FC ポートごとにゾーンを 1 つ設定し、各コントローラモジュールのイニシエータとその FC-to-SAS ブリッジの間のトラフィックを許可する必要があります。

各ストレージゾーンに 5 つのポートが含まれます。

* HBA イニシエータポート × 4 （コントローラごとに 1 つの接続）
* FC-to-SAS ブリッジの FC ポートに接続するポート × 1


ストレージゾーンでは標準のゾーニングを使用します。

例では、各サイトの 2 つのスタックグループを接続する 2 組のブリッジのペアを示します。各ブリッジが 1 つの FC ポートを使用するため、ファブリックあたりのストレージゾーン数は 8 個（合計 16 個）になります。



==== ブリッジ名

ブリッジでは、次の名前の例を使用します。 bridge_site_B 、スタックグループペア内での指定

|===


| 名前の各部分 | 特定のインターフェイス | 有効な値 


 a| 
サイト
 a| 
ブリッジペアが物理的に配置されているサイト。
 a| 
A または B



 a| 
スタックグループ
 a| 
ブリッジペアが接続されているスタックグループの番号。

* FibreBridge 7600N / 7500N ブリッジでは、スタックグループで最大 4 個のスタックがサポートされます。
+
スタックグループに含めることができるストレージシェルフは 10 個までです。

* FibreBridge 6500N ブリッジでは、スタックグループでサポートされるスタックは 1 つだけです。

 a| 
1 、 2 など



 a| 
ペア内の場所
 a| 
ブリッジペア内のブリッジ。ブリッジのペアは、特定のスタックグループに接続します。
 a| 
a または b

|===
各サイトの 1 つのスタックグループのブリッジ名の例：

* bridge_A_1a
* bridge_A_1b
* bridge_B_1a
* bridge_B_1b




==== DR グループ 1 - Site_A のスタック 1

* drgroup 1 ： MC1_INIT_GRP_1_SITE_A_STK_GRP_1_TOP_FC1 ： *

|===


| FC スイッチ | サイト | スイッチドメイン | 6505 / 6510 / G610 / G620 ポート | 6520 ポート | 接続先 


 a| 
FC_switch_A_1 を使用します
 a| 
A
 a| 
5.
 a| 
2.
 a| 
2.
 a| 
controller_A_1 のポート 0a



 a| 
FC_switch_A_1 を使用します
 a| 
A
 a| 
5.
 a| 
6.
 a| 
6.
 a| 
controller_A_2 、ポート 0a



 a| 
FC_switch_A_1 を使用します
 a| 
A
 a| 
5.
 a| 
8.
 a| 
8.
 a| 
bridge_A_1a の FC1



 a| 
FC_switch_B_1
 a| 
B
 a| 
7.
 a| 
2.
 a| 
2.
 a| 
controller_B_1 、ポート 0a



 a| 
FC_switch_B_1
 a| 
B
 a| 
7.
 a| 
6.
 a| 
6.
 a| 
controller_B_2 、ポート 0a

|===
|===


| Fabric_1 のゾーン | メンバーポート 


 a| 
MC1_INIT_GRP_1_SITE_A_STK_GRP_1_TOP_FC1
 a| 
5 、 2 ； 5 、 6 ； 7 、 2 ； 7 、 6 ； 5 、 8

|===
* drgroup 1 ： MC1_INIT_GRP_2_SITE_A_STK_GRP_1_TOP_FC1 ： *

|===


| FC スイッチ | サイト | スイッチドメイン | 6505 / 6510 / G610 ポート | 6520 ポート | G620 ポート | 接続先 


 a| 
FC_switch_A_1 を使用します
 a| 
A
 a| 
5.
 a| 
3.
 a| 
3.
 a| 
3.
 a| 
controller_A_1 のポート 0c



 a| 
FC_switch_A_1 を使用します
 a| 
A
 a| 
5.
 a| 
7.
 a| 
7.
 a| 
7.
 a| 
controller_A_2 、ポート 0c



 a| 
FC_switch_A_1 を使用します
 a| 
A
 a| 
5.
 a| 
9.
 a| 
9.
 a| 
9.
 a| 
bridge_A_1b の FC1



 a| 
FC_switch_B_1
 a| 
B
 a| 
7.
 a| 
3.
 a| 
3.
 a| 
3.
 a| 
controller_B_1 、ポート 0c



 a| 
FC_switch_B_1
 a| 
B
 a| 
7.
 a| 
7.
 a| 
7.
 a| 
7.
 a| 
controller_B_2 、ポート 0c

|===
|===


| Fabric_2 のゾーン | メンバーポート 


 a| 
MC1_INIT_GRP_2_SITE_A_STK_GRP_1_BOT_FC1
 a| 
5 、 3 ； 5 、 7 ； 7 、 3 ； 7 、 7 ； 5 、 9

|===
* drgroup 1 ： MC1_INIT_GRP_1_SITE_A_STK_GRP_1_BOT_FC1 ： *

|===


| FC スイッチ | サイト | スイッチドメイン | 6505 / 6510 / G610 | 6520 | G620 | 接続先 


 a| 
FC_switch_A_2
 a| 
A
 a| 
6.
 a| 
2.
 a| 
2.
 a| 
2.
 a| 
controller_A_1 のポート 0b



 a| 
FC_switch_A_2
 a| 
A
 a| 
6.
 a| 
6.
 a| 
6.
 a| 
6.
 a| 
controller_A_2 、ポート 0b



 a| 
FC_switch_A_2
 a| 
A
 a| 
6.
 a| 
8.
 a| 
8.
 a| 
8.
 a| 
bridge_A_1a の FC2



 a| 
FC_switch_B_2
 a| 
B
 a| 
8.
 a| 
2.
 a| 
2.
 a| 
2.
 a| 
controller_B_1 、ポート 0b



 a| 
FC_switch_B_2
 a| 
B
 a| 
8.
 a| 
6.
 a| 
6.
 a| 
6.
 a| 
controller_B_2 、ポート 0b

|===
|===


| Fabric_1 のゾーン | メンバーポート 


 a| 
MC1_INIT_GRP_1_SITE_A_STK_GRP_1_TOP_FC2
 a| 
6 、 2 、 6 、 8 、 2 、 8 、 6 、 6 、 8

|===
* drgroup 1 ： MC1_INIT_GRP_2_SITE_A_STK_GRP_1_BOT_FC2 ： *

|===


| FC スイッチ | サイト | スイッチドメイン | 6505 / 6510 / G610 | 6520 | G620 | 接続先 


 a| 
FC_switch_A_2
 a| 
A
 a| 
6.
 a| 
3.
 a| 
3.
 a| 
3.
 a| 
controller_A_1 のポート 0d



 a| 
FC_switch_A_2
 a| 
A
 a| 
6.
 a| 
7.
 a| 
7.
 a| 
7.
 a| 
controller_A_2 、ポート 0d



 a| 
FC_switch_A_2
 a| 
A
 a| 
6.
 a| 
9.
 a| 
9.
 a| 
9.
 a| 
bridge_A_1b の FC2



 a| 
FC_switch_B_2
 a| 
B
 a| 
8.
 a| 
3.
 a| 
3.
 a| 
3.
 a| 
controller_B_1 、ポート 0d



 a| 
FC_switch_B_2
 a| 
B
 a| 
8.
 a| 
7.
 a| 
7.
 a| 
7.
 a| 
controller_B_2 、ポート 0d

|===
|===


| Fabric_2 のゾーン | メンバーポート 


 a| 
MC1_INIT_GRP_2_SITE_A_STK_GRP_1_BOT_FC2
 a| 
6 、 3 、 6 、 7 、 8 、 3 、 8 、 7 、 6 、 9

|===


==== DR グループ 1 - Site_A のスタック 2

* drgroup 1 ： MC1_INIT_GRP_1_SITE_A_STK_GRP_2_TOP_FC1 ： *

|===


| FC スイッチ | サイト | スイッチドメイン | 6505 / 6510 / G610 ポート | 6520 ポート | G620 ポート | 接続先 


 a| 
FC_switch_A_1 を使用します
 a| 
A
 a| 
5.
 a| 
2.
 a| 
2.
 a| 
2.
 a| 
controller_A_1 のポート 0a



 a| 
FC_switch_A_1 を使用します
 a| 
A
 a| 
5.
 a| 
6.
 a| 
6.
 a| 
6.
 a| 
controller_A_2 、ポート 0a



 a| 
FC_switch_A_1 を使用します
 a| 
A
 a| 
5.
 a| 
10.
 a| 
10.
 a| 
10.
 a| 
bridge_A_2a の FC1



 a| 
FC_switch_B_1
 a| 
B
 a| 
7.
 a| 
2.
 a| 
2.
 a| 
2.
 a| 
controller_B_1 、ポート 0a



 a| 
FC_switch_B_1
 a| 
B
 a| 
7.
 a| 
6.
 a| 
6.
 a| 
6.
 a| 
controller_B_2 、ポート 0a

|===
|===


| Fabric_1 hh のゾーン | メンバーポート 


 a| 
MC1_INIT_GRP_1_SITE_A_STK_GRP_2_TOP_FC1
 a| 
5 、 2 ； 5 、 6 ； 7 、 2 ； 7 、 6 ； 5 、 10

|===
* drgroup 1 ： MC1_INIT_GRP_2_SITE_A_STK_GRP_2_TOP_FC1 ： *

|===


| FC スイッチ | サイト | スイッチドメイン | 6505 / 6510 / G610 ポート | 6520 ポート | G620 ポート | 接続先 


 a| 
FC_switch_A_1 を使用します
 a| 
A
 a| 
5.
 a| 
3.
 a| 
3.
 a| 
3.
 a| 
controller_A_1 のポート 0c



| FC_switch_A_1 を使用します  a| 
A
 a| 
5.
 a| 
7.
 a| 
7.
 a| 
7.
 a| 
controller_A_2 、ポート 0c



| FC_switch_A_1 を使用します  a| 
A
 a| 
5.
 a| 
11.
 a| 
11.
 a| 
11.
 a| 
bridge_A_2b の FC1



 a| 
FC_switch_B_1
 a| 
B
 a| 
7.
 a| 
3.
 a| 
3.
 a| 
3.
 a| 
controller_B_1 、ポート 0c



 a| 
FC_switch_B_1
 a| 
B
 a| 
7.
 a| 
7.
 a| 
7.
 a| 
7.
 a| 
controller_B_2 、ポート 0c

|===
|===


| Fabric_2 のゾーン | メンバーポート 


 a| 
MC1_INIT_GRP_2_SITE_A_STK_GRP_2_BOT_FC1
 a| 
5 、 3 ； 5 、 7 ； 7 、 3 ； 7 、 7 ； 5 、 11

|===
* drgroup 1 ： MC1_INIT_GRP_1_SITE_A_STK_GRP_2_BOT_FC2 ： *

|===


| FC スイッチ | サイト | スイッチドメイン | 6505 / 6510 / G610 ポート | 6520 ポート | G620 ポート | 接続先 


 a| 
FC_switch_A_2
 a| 
A
 a| 
6.
 a| 
2.
 a| 
0
 a| 
0
 a| 
controller_A_1 のポート 0b



 a| 
FC_switch_A_2
 a| 
A
 a| 
6.
 a| 
6.
 a| 
4.
 a| 
4.
 a| 
controller_A_2 、ポート 0b



 a| 
FC_switch_A_2
 a| 
A
 a| 
6.
 a| 
10.
 a| 
10.
 a| 
10.
 a| 
bridge_A_2a の FC2



 a| 
FC_switch_B_2
 a| 
B
 a| 
8.
 a| 
2.
 a| 
2.
 a| 
2.
 a| 
controller_B_1 、ポート 0b



 a| 
FC_switch_B_2
 a| 
B
 a| 
8.
 a| 
6.
 a| 
6.
 a| 
6.
 a| 
controller_B_2 、ポート 0b

|===
|===


| Fabric_1 のゾーン | メンバーポート 


 a| 
MC1_INIT_GRP_1_SITE_A_STK_GRP_2_TOP_FC2
 a| 
6 、 2 、 6 、 8 、 2 、 8 、 6 、 6 、 10

|===
* drgroup 1 ： MC1_INIT_GRP_2_SITE_A_STK_GRP_2_BOT_FC2 ： *

|===


| FC スイッチ | サイト | スイッチドメイン | 6505 / 6510 / G610 ポート | 6520 ポート | G620 ポート | 接続先 


 a| 
FC_switch_A_2
 a| 
A
 a| 
6.
 a| 
3.
 a| 
3.
 a| 
3.
 a| 
controller_A_1 のポート 0d



 a| 
FC_switch_A_2
 a| 
A
 a| 
6.
 a| 
7.
 a| 
7.
 a| 
7.
 a| 
controller_A_2 、ポート 0d



 a| 
FC_switch_A_2
 a| 
A
 a| 
6.
 a| 
11.
 a| 
11.
 a| 
11.
 a| 
Bridge_A_2b FC2



 a| 
FC_switch_B_2
 a| 
B
 a| 
8.
 a| 
3.
 a| 
3.
 a| 
3.
 a| 
controller_B_1 、ポート 0d



 a| 
FC_switch_B_2
 a| 
B
 a| 
8.
 a| 
7.
 a| 
7.
 a| 
7.
 a| 
controller_B_2 、ポート 0d

|===
|===


| Fabric_2 のゾーン | メンバーポート 


 a| 
MC1_INIT_GRP_2_SITE_A_STK_GRP_2_BOT_FC2
 a| 
6 、 3 、 6 、 7 、 8 、 3 、 8 、 7 、 6 、 11

|===


==== DR グループ 1 - Site_B のスタック 1

* drgroup 1 ： MC1_INIT_GRP_1_SITE_B_STK_GRP_1_TOP_FC1 ： *

|===


| FC スイッチ | サイト | スイッチドメイン | 6505 / 6510 / G610 ポート | 6520 ポート | G620 ポート | 接続先 


 a| 
FC_switch_A_1 を使用します
 a| 
A
 a| 
5.
 a| 
2.
 a| 
2.
 a| 
2.
 a| 
controller_A_1 のポート 0a



 a| 
FC_switch_A_1 を使用します
 a| 
A
 a| 
5.
 a| 
6.
 a| 
6.
 a| 
6.
 a| 
controller_A_2 、ポート 0a



 a| 
FC_switch_B_1
 a| 
B
 a| 
7.
 a| 
2.
 a| 
2.
 a| 
8.
 a| 
controller_B_1 、ポート 0a



 a| 
FC_switch_B_1
 a| 
B
 a| 
7.
 a| 
6.
 a| 
6.
 a| 
2.
 a| 
controller_B_2 、ポート 0a



 a| 
FC_switch_B_1
 a| 
B
 a| 
7.
 a| 
8.
 a| 
8.
 a| 
6.
 a| 
bridge_B_1a の FC1

|===
|===


| Fabric_1 のゾーン | メンバーポート 


 a| 
MC1_INIT_GRP_1_SITE_B_STK_GRP_1_TOP_FC1
 a| 
5 、 2 ； 5 、 6 ； 7 、 2 ； 7 、 6 ； 7 、 8

|===
* drgroup 1 ： MC1_INIT_GRP_2_SITE_B_STK_GRP_1_TOP_FC1 ： *

|===


| FC スイッチ | サイト | スイッチドメイン | 6505 / 6510 / G610 ポート | 6520 ポート | G620 ポート | 接続先 


 a| 
FC_switch_A_1 を使用します
 a| 
A
 a| 
5.
 a| 
3.
 a| 
3.
 a| 
3.
 a| 
controller_A_1 のポート 0c



 a| 
FC_switch_A_1 を使用します
 a| 
A
 a| 
5.
 a| 
7.
 a| 
7.
 a| 
7.
 a| 
controller_A_2 、ポート 0c



 a| 
FC_switch_B_1
 a| 
B
 a| 
7.
 a| 
3.
 a| 
3.
 a| 
9.
 a| 
controller_B_1 、ポート 0c



 a| 
FC_switch_B_1
 a| 
B
 a| 
7.
 a| 
7.
 a| 
7.
 a| 
3.
 a| 
controller_B_2 、ポート 0c



 a| 
FC_switch_B_1
 a| 
B
 a| 
7.
 a| 
9.
 a| 
9.
 a| 
7.
 a| 
bridge_B_1b の FC1

|===
|===


| Fabric_2 のゾーン | メンバーポート 


 a| 
MC1_INIT_GRP_2_SITE_B_STK_GRP_1_BOT_FC1
 a| 
5 、 3 ； 5 、 7 ； 7 、 3 ； 7 、 7 ； 7 、 9

|===
* drgroup 1 ： MC1_INIT_GRP_1_SITE_B_STK_GRP_1_BOT_FC2 ： *

|===


| FC スイッチ | サイト | スイッチドメイン | 6505 / 6510 / G610 ポート | 6520 ポート | G620 ポート | 接続先 


 a| 
FC_switch_A_2
 a| 
A
 a| 
6.
 a| 
2.
 a| 
2.
 a| 
2.
 a| 
controller_A_1 のポート 0b



 a| 
FC_switch_A_2
 a| 
A
 a| 
6.
 a| 
6.
 a| 
6.
 a| 
6.
 a| 
controller_A_2 、ポート 0b



 a| 
FC_switch_B_2
 a| 
B
 a| 
8.
 a| 
2.
 a| 
2.
 a| 
2.
 a| 
controller_B_1 、ポート 0b



 a| 
FC_switch_B_2
 a| 
B
 a| 
8.
 a| 
6.
 a| 
6.
 a| 
6.
 a| 
controller_B_2 、ポート 0b



 a| 
FC_switch_B_2
 a| 
B
 a| 
8.
 a| 
8.
 a| 
8.
 a| 
8.
 a| 
bridge_B_1a の FC2

|===
|===
| Fabric_1 のゾーン | メンバーポート 


 a| 
MC1_INIT_GRP_1_SITE_B_STK_GRP_1_TOP_FC2
 a| 
6 、 2 、 6 、 8 、 2 、 8 、 6 、 8 、 8

|===
* drgroup 1 ： MC1_INIT_GRP_2_SITE_B_STK_GRP_1_BOT_FC2 ： *

|===


| FC スイッチ | サイト | スイッチドメイン | 6505 / 6510 / G610 ポート | 6520 ポート | G620 ポート | 接続先 


 a| 
FC_switch_A_2
 a| 
A
 a| 
6.
 a| 
3.
 a| 
3.
 a| 
3.
 a| 
controller_A_1 のポート 0d



 a| 
FC_switch_A_2
 a| 
A
 a| 
6.
 a| 
7.
 a| 
7.
 a| 
7.
 a| 
controller_A_2 、ポート 0d



 a| 
FC_switch_B_2
 a| 
B
 a| 
8.
 a| 
3.
 a| 
3.
 a| 
3.
 a| 
controller_B_1 、ポート 0d



 a| 
FC_switch_B_2
 a| 
B
 a| 
8.
 a| 
7.
 a| 
7.
 a| 
7.
 a| 
controller_B_2 、ポート 0d



 a| 
FC_switch_B_2
 a| 
B
 a| 
8.
 a| 
9.
 a| 
9.
 a| 
9.
 a| 
bridge_A_1b の FC2

|===
|===


| Fabric_2 のゾーン | メンバーポート 


 a| 
MC1_INIT_GRP_2_SITE_B_STK_GRP_1_BOT_FC2
 a| 
6 、 3 、 6 、 7 、 8 、 3 、 8 、 7 、 8 、 9

|===


==== DR グループ 1 - Site_B のスタック 2

* drgroup 1 ： MC1_INIT_GRP_1_SITE_B_STK_GRP_2_TOP_FC1 ： *

|===


| FC スイッチ | サイト | スイッチドメイン | 6505 / 6510 / G610 ポート | 6520 ポート | G620 ポート | 接続先 


 a| 
FC_switch_A_1 を使用します
 a| 
A
 a| 
5.
 a| 
2.
 a| 
2.
 a| 
2.
 a| 
controller_A_1 のポート 0a



 a| 
FC_switch_A_1 を使用します
 a| 
A
 a| 
5.
 a| 
6.
 a| 
6.
 a| 
6.
 a| 
controller_A_2 、ポート 0a



 a| 
FC_switch_B_1
 a| 
B
 a| 
7.
 a| 
2.
 a| 
2.
 a| 
2.
 a| 
controller_B_1 、ポート 0a



 a| 
FC_switch_B_1
 a| 
B
 a| 
7.
 a| 
6.
 a| 
6.
 a| 
6.
 a| 
controller_B_2 、ポート 0a



 a| 
FC_switch_B_1
 a| 
B
 a| 
7.
 a| 
10.
 a| 
10.
 a| 
10.
 a| 
bridge_B_2a の FC1

|===
|===


| Fabric_1 のゾーン | メンバーポート 


 a| 
MC1_INIT_GRP_1_SITE_B_STK_GRP_2_TOP_FC1
 a| 
5 、 2 ； 5 、 6 ； 7 、 2 ； 7 、 6 ； 7 、 10

|===
* drgroup 1 ： MC1_INIT_GRP_2_SITE_B_STK_GRP_2_TOP_FC1 ： *

|===


| FC スイッチ | サイト | スイッチドメイン | 6505 / 6510 / G610 ポート | 6520 ポート | G620 ポート | 接続先 


 a| 
FC_switch_A_1 を使用します
 a| 
A
 a| 
5.
 a| 
3.
 a| 
3.
 a| 
3.
 a| 
controller_A_1 のポート 0c



 a| 
FC_switch_A_1 を使用します
 a| 
A
 a| 
5.
 a| 
7.
 a| 
7.
 a| 
7.
 a| 
controller_A_2 、ポート 0c



 a| 
FC_switch_B_1
 a| 
B
 a| 
7.
 a| 
3.
 a| 
3.
 a| 
3.
 a| 
controller_B_1 、ポート 0c



 a| 
FC_switch_B_1
 a| 
B
 a| 
7.
 a| 
7.
 a| 
7.
 a| 
7.
 a| 
controller_B_2 、ポート 0c



 a| 
FC_switch_B_1
 a| 
B
 a| 
7.
 a| 
11.
 a| 
11.
 a| 
11.
 a| 
bridge_B_2b の FC1

|===
|===


| Fabric_2 hh のゾーン | メンバーポート 


 a| 
MC1_INIT_GRP_2_SITE_B_STK_GRP_2_BOT_FC1
 a| 
5 、 3 ； 5 、 7 ； 7 、 3 ； 7 、 7 ； 7 、 11

|===
* drgroup 1 ： MC1_INIT_GRP_1_SITE_B_STK_GRP_2_BOT_FC2 ： *

|===


| FC スイッチ | サイト | スイッチドメイン | 6505 / 6510 / G610 ポート | 6520 ポート | G620 ポート | 接続先 


 a| 
FC_switch_A_2
 a| 
A
 a| 
6.
 a| 
2.
 a| 
2.
 a| 
2.
 a| 
controller_A_1 のポート 0b



 a| 
FC_switch_A_2
 a| 
A
 a| 
6.
 a| 
6.
 a| 
6.
 a| 
6.
 a| 
controller_A_2 、ポート 0b



 a| 
FC_switch_B_2
 a| 
B
 a| 
8.
 a| 
2.
 a| 
2.
 a| 
2.
 a| 
controller_B_1 、ポート 0b



 a| 
FC_switch_B_2
 a| 
B
 a| 
8.
 a| 
6.
 a| 
6.
 a| 
6.
 a| 
controller_B_2 、ポート 0b



 a| 
FC_switch_B_2
 a| 
B
 a| 
8.
 a| 
10.
 a| 
10.
 a| 
10.
 a| 
bridge_B_2a の FC2

|===
|===


| Fabric_1 のゾーン | メンバーポート 


 a| 
MC1_INIT_GRP_1_SITE_B_STK_GRP_2_TOP_FC2
 a| 
6 、 2 、 6 、 8 、 2 、 8 、 6 、 8 、 10

|===
* drgroup 1 ： MC1_INIT_GRP_2_SITE_B_STK_GRP_2_BOT_FC2 ： *

|===


| FC スイッチ | サイト | スイッチドメイン | 6505 / 6510 / G610 ポート | 6520 ポート | G620 ポート | 接続先 


 a| 
FC_switch_A_2
 a| 
A
 a| 
6.
 a| 
3.
 a| 
3.
 a| 
3.
 a| 
controller_A_1 のポート 0d



 a| 
FC_switch_A_2
 a| 
A
 a| 
6.
 a| 
7.
 a| 
7.
 a| 
7.
 a| 
controller_A_2 、ポート 0d



 a| 
FC_switch_B_2
 a| 
B
 a| 
8.
 a| 
3.
 a| 
3.
 a| 
3.
 a| 
controller_B_1 、ポート 0d



 a| 
FC_switch_B_2
 a| 
B
 a| 
8.
 a| 
7.
 a| 
7.
 a| 
7.
 a| 
controller_B_2 、ポート 0d



 a| 
FC_switch_B_2
 a| 
B
 a| 
8.
 a| 
11.
 a| 
11.
 a| 
11.
 a| 
Bridge_B_2b FC2

|===
|===


| Fabric_2 のゾーン | メンバーポート 


 a| 
MC1_INIT_GRP_2_SITE_B_STK_GRP_2_BOT_FC2
 a| 
6 、 3 、 6 、 7 、 8 、 3 、 8 、 7 、 8 、 11

|===


==== ストレージゾーンのサマリ

|===


| ファブリック | ゾーン名 | メンバーポート 


 a| 
FC_switch_A_1 および FC_switch_B_1
 a| 
MC1_INIT_GRP_1_SITE_A_STK_GRP_1_TOP_FC1
 a| 
5 、 2 ； 5 、 6 ； 7 、 2 ； 7 、 6 ； 5 、 8



 a| 
FC_switch_A_1 および FC_switch_B_1
 a| 
MC1_INIT_GRP_2_SITE_A_STK_GRP_1_BOT_FC1
 a| 
5 、 3 ； 5 、 7 ； 7 、 3 ； 7 、 7 ； 5 、 9



 a| 
FC_switch_A_1 および FC_switch_B_1
 a| 
MC1_INIT_GRP_1_SITE_A_STK_GRP_2_TOP_FC1
 a| 
5 、 2 ； 5 、 6 ； 7 、 2 ； 7 、 6 ； 5 、 10



 a| 
FC_switch_A_1 および FC_switch_B_1
 a| 
MC1_INIT_GRP_2_SITE_A_STK_GRP_2_BOT_FC1
 a| 
5 、 3 ； 5 、 7 ； 7 、 3 ； 7 、 7 ； 5 、 11



 a| 
FC_switch_A_1 および FC_switch_B_1
 a| 
MC1_INIT_GRP_1_SITE_B_STK_GRP_1_TOP_FC1
 a| 
5 、 2 ； 5 、 6 ； 7 、 2 ； 7 、 6 ； 7 、 8



 a| 
FC_switch_A_1 および FC_switch_B_1
 a| 
MC1_INIT_GRP_2_SITE_B_STK_GRP_1_BOT_FC1
 a| 
5 、 3 ； 5 、 7 ； 7 、 3 ； 7 、 7 ； 7 、 9



 a| 
FC_switch_A_1 および FC_switch_B_1
 a| 
MC1_INIT_GRP_1_SITE_B_STK_GRP_2_TOP_FC1
 a| 
5 、 2 ； 5 、 6 ； 7 、 2 ； 7 、 6 ； 7 、 10



 a| 
FC_switch_A_1 および FC_switch_B_1
 a| 
MC1_INIT_GRP_2_SITE_B_STK_GRP_2_BOT_FC1
 a| 
5 、 3 ； 5 、 7 ； 7 、 3 ； 7 、 7 ； 7 、 11



 a| 
FC_switch_A_2 と FC_switch_B_2
 a| 
MC1_INIT_GRP_1_SITE_A_STK_GRP_1_TOP_FC2
 a| 
6 、 2 、 6 、 8 、 2 、 8 、 6 、 6 、 8



 a| 
FC_switch_A_2 と FC_switch_B_2
 a| 
MC1_INIT_GRP_2_SITE_A_STK_GRP_1_BOT_FC2
 a| 
6 、 3 、 6 、 7 、 8 、 3 、 8 、 7 、 6 、 9



 a| 
FC_switch_A_2 と FC_switch_B_2
 a| 
MC1_INIT_GRP_1_SITE_A_STK_GRP_2_TOP_FC2
 a| 
6 、 2 、 6 、 8 、 2 、 8 、 6 、 6 、 10



 a| 
FC_switch_A_2 と FC_switch_B_2
 a| 
MC1_INIT_GRP_2_SITE_A_STK_GRP_2_BOT_FC2
 a| 
6 、 3 、 6 、 7 、 8 、 3 、 8 、 7 、 6 、 11



 a| 
FC_switch_A_2 と FC_switch_B_2
 a| 
MC1_INIT_GRP_1_SITE_B_STK_GRP_1_TOP_FC2
 a| 
6 、 2 、 6 、 8 、 2 、 8 、 6 、 8 、 8



 a| 
FC_switch_A_2 と FC_switch_B_2
 a| 
MC1_INIT_GRP_2_SITE_B_STK_GRP_1_BOT_FC2
 a| 
6 、 3 、 6 、 7 、 8 、 3 、 8 、 7 、 8 、 9



 a| 
FC_switch_A_2 と FC_switch_B_2
 a| 
MC1_INIT_GRP_1_SITE_B_STK_GRP_2_TOP_FC2
 a| 
6 、 2 、 6 、 8 、 2 、 8 、 6 、 8 、 10



 a| 
FC_switch_A_2 と FC_switch_B_2
 a| 
MC1_INIT_GRP_2_SITE_B_STK_GRP_2_BOT_FC2
 a| 
6 、 3 、 6 、 7 、 8 、 3 、 8 、 7 、 8 、 11

|===


=== Brocade FC スイッチでゾーニングを設定します

スイッチポートを別々のゾーンに割り当てて、コントローラとストレージのトラフィックを分離する必要があります。また、 FC-VI ポートのゾーンとストレージポートのゾーンも含める必要があります。

.このタスクについて
次の手順では、 MetroCluster 構成の標準的なゾーニングを使用します。

link:task_fcsw_brocade_configure_the_brocade_fc_switches_supertask.html["FC-VI ポートのゾーニング"]

link:task_fcsw_brocade_configure_the_brocade_fc_switches_supertask.html["FibreBridge 6500N ブリッジまたは 1 つの FC ポートを使用する FibreBridge 7500N / 7600N ブリッジのゾーニング"]

link:task_fcsw_brocade_configure_the_brocade_fc_switches_supertask.html["両方の FC ポートを使用する FibreBridge 7500N ブリッジのゾーニング"]

.手順
. 各スイッチに FC-VI ゾーンを作成します。
+
zonecreate "QOSH1_FCVI_1" 、 member ； member … ..

+
この例では、ポート 5 、 0 ； 5 、 1 ； 5 、 4 ； 5 、 5 ； 7 、 0 ； 7 、 1 ； 7 、 4 ； 7 、 5 を含む QOS FCVI ゾーンを作成しています。

+
[listing]
----
Switch_A_1:admin> zonecreate "QOSH1_FCVI_1", "5,0;5,1;5,4;5,5;7,0;7,1;7,4;7,5"
----
. 各スイッチにストレージゾーンを設定します。
+
ファブリックのゾーニングは、ファブリック内の 1 つのスイッチから設定できます。次の例では、 Switch_A_1 でゾーニングを設定します。

+
.. スイッチファブリックの各スイッチドメインのストレージゾーンを作成します。
+
zonecreate name 、 member ； member … ..

+
この例では、両方の FC ポートを使用する FibreBridge 7500N のストレージゾーンを作成します。ゾーンには、ポート 5 、 2 ； 5 、 6 ； 7 、 2 ； 7 、 6 ； 5 、 16 が含まれます。

+
[listing]
----
Switch_A_1:admin> zonecreate "MC1_INIT_GRP_1_SITE_A_STK_GRP_1_TOP_FC1", "5,2;5,6;7,2;7,6;5,16"
----
.. 1 つ目のスイッチファブリックで設定を作成します。
+
cfgcreate config_name 、 zone ； zone... を使用します

+
この例では、 CFG_1 という名前で、 QOSH1_MC1_FAB_1_FCVI および GRP_1_SITE_A_STK_GRP_1_TOP_FC1 の 2 つのゾーンを含む設定を作成します

+
[listing]
----
Switch_A_1:admin> cfgcreate "CFG_1", "QOSH1_MC1_FAB_1_FCVI; MC1_INIT_GRP_1_SITE_A_STK_GRP_1_TOP_FC1"
----
.. 必要に応じて、設定にゾーンを追加します。
+
cfgadd config_name zone ； zone... を使用します

.. 設定を有効にします。
+
cfgenable config_name

+
[listing]
----
Switch_A_1:admin> cfgenable "CFG_1"
----
.. 設定を保存します。
+
cfgsave

+
[listing]
----
Switch_A_1:admin> cfgsave
----
.. ゾーニング設定を検証します。
+
zone -- 妥当性検査

+
[listing]
----
Switch_A_1:admin> zone --validate
Defined configuration:
cfg: CFG_1 QOSH1_MC1_FAB_1_FCVI ; MC1_INIT_GRP_1_SITE_A_STK_GRP_1_TOP_FC1
zone: QOSH1_MC1_FAB_1_FCVI
5,0;5,1;5,4;5,5;7,0;7,1;7,4;7,5
zone: MC1_INIT_GRP_1_SITE_A_STK_GRP_1_TOP_FC1
5,2;5,6;7,2;7,6;5,16
Effective configuration:
cfg: CFG_1
zone: QOSH1_MC1_FAB_1_FCVI
5,0
5,1
5,4
5,5
7,0
7,1
7,4
7,5
zone: MC1_INIT_GRP_1_SITE_A_STK_GRP_1_TOP_FC1
5,2
5,6
7,2
7,6
5,16
------------------------------------
~ - Invalid configuration
* - Member does not exist
# - Invalid usage of broadcast zone
----






== Brocade 6510 または G620 スイッチでの ISL 暗号化の設定

Brocade 6510 または G620 スイッチでは、 ISL 接続に対してオプションで Brocade 暗号化機能を使用できます。暗号化機能を使用する場合は、 MetroCluster 構成の各スイッチで追加の設定手順を実行する必要があります。

.作業を開始する前に
* Brocade 6510 または G620 スイッチが必要です。
+

NOTE: Brocade G620 スイッチでの ISL 暗号化の使用は、 ONTAP 9.4 以降でのみサポートされます。

* 同じファブリックの 2 つのスイッチを選択しておく必要があります。
* スイッチと Fabric Operating System のバージョンに対応する Brocade のドキュメントを参照して、帯域幅とポートの制限を確認しておく必要があります。


.このタスクについて
この手順は、同じファブリック内の両方のスイッチで実行する必要があります。



=== 仮想ファブリックを無効にします

ISL 暗号化を設定するには、 MetroCluster 構成で使用されている 4 つのスイッチすべてで仮想ファブリックを無効にする必要があります。

.手順
. スイッチコンソールで次のコマンドを入力して、仮想ファブリックを無効にします。
+
fosconfig -- VF' を無効にします

. スイッチをリブートします。




=== ペイロードを設定しています

仮想ファブリックを無効にしたら、ファブリック内の両方のスイッチでペイロードまたはデータフィールドサイズを設定する必要があります。

.このタスクについて
データフィールドサイズは 2048 以下にする必要があります。

.手順
. スイッチを無効にします。
+
'witchdisable

. ペイロードを設定します。
+
「 configure 」を実行します

. 次のスイッチパラメータを設定します。
+
.. Fabric パラメータを 'y' のように設定します
.. Domain 、 WWN ベースの persistent PID など、その他のパラメータを設定します。
.. データフィールドのサイズを「 2048 」に設定します






=== 認証ポリシーを設定します

認証ポリシーおよび関連するパラメータを設定する必要があります。

.このタスクについて
コマンドはスイッチコンソールで実行する必要があります。

.手順
. 認証シークレットを設定します。
+
.. セットアッププロセスを開始します。
+
'ecAuthSecret -- セット

+
このコマンドにより、次の手順で応答する一連のプロンプトが開始されます。

.. Enter peer WWN 、 Domain 、 or switch name というプロンプトに対して、ファブリック内のもう一方のスイッチの World Wide Name （ WWN ；ワールドワイド名）を指定します。
.. Enter peer secret というプロンプトに対して、ピアシークレットを指定します。
.. Enter local secret というプロンプトに対して、ローカルシークレットを指定します。
.. 「 Are you done 」パラメータに「 Y 」と入力します。
+
--
認証シークレットの設定例を以下に示します。

[listing]
----
brcd> secAuthSecret --set

This command is used to set up secret keys for the DH-CHAP authentication.
The minimum length of a secret key is 8 characters and maximum 40
characters. Setting up secret keys does not initiate DH-CHAP
authentication. If switch is configured to do DH-CHAP, it is performed
whenever a port or a switch is enabled.

Warning: Please use a secure channel for setting secrets. Using
an insecure channel is not safe and may compromise secrets.

Following inputs should be specified for each entry.

1. WWN for which secret is being set up.
2. Peer secret: The secret of the peer that authenticates to peer.
3. Local secret: The local secret that authenticates peer.

Press enter to start setting up secrets > <cr>

Enter peer WWN, Domain, or switch name (Leave blank when done): 10:00:00:05:33:76:2e:99
Enter peer secret: <hidden>
Re-enter peer secret: <hidden>
Enter local secret: <hidden>
Re-enter local secret: <hidden>

Enter peer WWN, Domain, or switch name (Leave blank when done):
Are you done? (yes, y, no, n): [no] yes
Saving data to key store... Done.
----
--


. 認証グループを 4 に設定します。
+
authUtil -- set-g 4`

. 認証タイプを「 dhchap 」に設定します。
+
authUtil -- set -a dhchap

+
次の出力が表示されます。

+
[listing]
----
Authentication is set to dhchap.
----
. スイッチの認証ポリシーを on に設定します。
+
authUtil -- policy-sw on `

+
次の出力が表示されます。

+
[listing]
----
Warning: Activating the authentication policy requires either DH-CHAP secrets or PKI certificates depending on the protocol selected. Otherwise, ISLs will be segmented during next E-port bring-up.
ARE YOU SURE  (yes, y, no, n): [no] yes
Auth Policy is set to ON
----




=== Brocade スイッチでの ISL 暗号化の有効化

認証ポリシーと認証シークレットを設定したら、ポートで ISL 暗号化を有効にする必要があります。

.このタスクについて
* この手順は、一度に 1 つのスイッチファブリックで実行する必要があります。
* コマンドはスイッチコンソールで実行する必要があります。


.手順
. すべての ISL ポートで暗号化を有効にします。
+
portCfgEncrypt -- ポート番号を有効にします

+
次の例は、ポート 8 とポート 12 で暗号化を有効にします。

+
portCfgEncrypt -- 8 を有効にします

+
portCfgEncrypt -- 12 を有効にします

. スイッチを有効にします。
+
「 witchenable 」

. ISL が稼働していることを確認します。
+
「 islshow` 」

. 暗号化が有効であることを確認します。
+
portenccompshow`

+
次の例は、ポート 8 とポート 12 で暗号化が有効であることを示しています。

+
[listing]
----

User Encryption
Port  configured     Active
----   ----------    ------
 8      yes          yes
 9      No           No
 10     No           No
 11     No           No
 12     yes          yes
----


.次に何をするか
MetroCluster 構成の他のファブリック内のスイッチで、すべての手順を実行します。
