---
permalink: install-fc/task_rack_the_hardware_components_mcc_fabric_and_ip.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, rack, hardware, components 
summary: 納入された機器がキャビネットに設置されていない場合は、コンポーネントをラックに配置する必要があります。 
---
= ラックにハードウェアコンポーネントを配置
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
納入された機器がキャビネットに設置されていない場合は、コンポーネントをラックに配置する必要があります。

.このタスクについて
このタスクは両方の MetroCluster サイトで実行する必要があります。

.手順
. MetroCluster コンポーネントの配置を計画します。
+
ラックスペースは、コントローラモジュールのプラットフォームモデル、スイッチのタイプ、構成内のディスクシェルフスタック数によって異なります。

. 自身の適切な接地対策を行います
. コントローラモジュールをラックまたはキャビネットに設置します。
+
https://docs.netapp.com/platstor/index.jsp["AFF と FAS ドキュメントセンター"]

. FC スイッチをラックまたはキャビネットに設置します。
. ディスクシェルフを設置し、電源を投入して、シェルフ ID を設定します。
+
** 各ディスクシェルフの電源を再投入する必要があります。
** 各 MetroCluster DR グループ（両サイトを含む）で、各 SAS ディスクシェルフのシェルフ ID が一意である必要があります。


. 各 FC-to-SAS ブリッジを設置します。
+
.. 4 本のネジを使用して、ブリッジ前面の「 L 」ブラケットをラックの前面に固定します（フラッシュマウント）。
+
ブリッジ「 L 」ブラケットの開口部は、 19 インチ（ 482.6 mm ）ラックのラック標準 ETA-310-X に準拠しています。

+
設置の詳細および図については、使用しているブリッジモデルに対応した ATTO FibreBridge Installation and Operation Manual を参照してください。

+

NOTE: ポートスペースへのアクセスと FRU の保守性を確保するには、ブリッジペアの下に 1U のスペースを残し、そのスペースを工具が不要なブランクパネルでカバーする必要があります。

.. 各ブリッジを、適切なアースを提供する電源に接続します。
.. 各ブリッジの電源をオンにします。
+

NOTE: 耐障害性を最大限にするために、ディスクシェルフの同じスタックに接続されているブリッジをそれぞれ別々の電源に接続する必要があります。

+
ブリッジの準備完了を示す LED が点灯し、ブリッジの電源投入時自己診断テストが完了したことを示すまで、 30 秒ほどかかる場合があります。




