---
permalink: install-fc/task_reset_the_brocade_fc_switch_to_factory_defaults.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, reset, brocade, fc, switch, factory, defaults 
summary: 新しいソフトウェアバージョンと RCF ファイルをインストールする前に、現在のスイッチの設定を消去し、基本的な設定を完了する必要があります。 
---
= Brocade FC スイッチを工場出荷時のデフォルトにリセット
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
新しいソフトウェアバージョンと RCF ファイルをインストールする前に、現在のスイッチの設定を消去し、基本的な設定を完了する必要があります。

.このタスクについて
この手順は、 MetroCluster ファブリック構成内の各 FC スイッチで実行する必要があります。

.手順
. 管理者としてスイッチにログインします。
. Brocade Virtual Fabric （ VF ）機能を無効にします。
+
「 fosconfig options 」を参照してください

+
[listing]
----
FC_switch_A_1:admin> fosconfig --disable vf
WARNING:  This is a disruptive operation that requires a reboot to take effect.
Would you like to continue  [Y/N]: y
----
. スイッチのポートから ISL ケーブルを外します。
. スイッチを無効にします。
+
'witchcfgpersistentdisable

+
[listing]
----
FC_switch_A_1:admin> switchcfgpersistentdisable
----
. 設定を無効にします。
+
「 cfgDisable 」

+
[listing]
----
FC_switch_A_1:admin> cfgDisable
You are about to disable zoning configuration. This action will disable any previous zoning configuration enabled.
Do you want to disable zoning configuration? (yes, y, no, n): [no] y
Updating flash ...
Effective configuration is empty. "No  Access" default zone mode is ON.
----
. 設定をクリアします。
+
「 cfgClear 」

+
[listing]
----
FC_switch_A_1:admin> cfgClear
The Clear All action will clear all Aliases, Zones, FA Zones
and configurations in the Defined configuration.
Run cfgSave to commit the transaction or cfgTransAbort to
cancel the transaction.
Do you really want to clear all configurations?  (yes, y, no, n): [no] y
----
. 設定を保存します。
+
cfgsave

+
[listing]
----
FC_switch_A_1:admin> cfgSave
You are about to save the Defined zoning configuration. This
action will only save the changes on Defined configuration.
Do you want to save the Defined zoning configuration only?  (yes, y, no, n): [no] y
Updating flash ...
----
. デフォルトの設定を行います。
+
「 configDefault 」

+
[listing]
----
FC_switch_A_1:admin> configDefault
WARNING:  This is a disruptive operation that requires a switch reboot.
Would you like to continue [Y/N]: y
Executing configdefault...Please wait
2020/10/05-08:04:08, [FCR-1069], 1016, FID 128, INFO, FC_switch_A_1, The FC Routing service is enabled.
2020/10/05-08:04:08, [FCR-1068], 1017, FID 128, INFO, FC_switch_A_1, The FC Routing service is disabled.
2020/10/05-08:04:08, [FCR-1070], 1018, FID 128, INFO, FC_switch_A_1, The FC Routing configuration is set to default.
Committing configuration ... done.
2020/10/05-08:04:12, [MAPS-1113], 1019, FID 128, INFO, FC_switch_A_1, Policy dflt_conservative_policy activated.
2020/10/05-08:04:12, [MAPS-1145], 1020, FID 128, INFO, FC_switch_A_1, FPI Profile dflt_fpi_profile is activated for E-Ports.
2020/10/05-08:04:12, [MAPS-1144], 1021, FID 128, INFO, FC_switch_A_1, FPI Profile dflt_fpi_profile is activated for F-Ports.
The switch has to be rebooted to allow the changes to take effect.
2020/10/05-08:04:12, [CONF-1031], 1022, FID 128, INFO, FC_switch_A_1, configDefault completed successfully for switch.
----
. すべてのポートについて、ポートの設定を default に設定します。
+
`portcfgdefault_port-number_`

+
[listing]
----
FC_switch_A_1:admin> portcfgdefault <port number>
----
+
この手順はポートごとに実行する必要があります。

. FOS 9.0 より前のバージョンを実行している場合は、スイッチが動的ポート オン デマンド (POD) 方式を使用していることを確認します。
+

NOTE: Fabric OS 9.0以降では、ライセンス方式はデフォルトで動的です。静的ライセンス方式はサポートされていません。

+
バージョン 8.0 より前の Brocade Fabric OS では、次のコマンドを admin として実行し、バージョン 8.0 以降では root として実行します。

+
.. ライセンスコマンドを実行します。
+
`licenseport --show` 。

+
[listing]
----
FC_switch_A_1:admin> license --show -port
24 ports are available in this switch
Full POD license is installed
Dynamic POD method is in use
----
.. Brocade によって root ユーザが無効にされている場合は、有効にします。
+
[listing]
----
FC_switch_A_1:admin> userconfig --change root -e yes
FC_switch_A_1:admin> rootaccess --set consoleonly
----
.. ライセンスコマンドを実行します。
+
`licenseport --show` 。

+
[listing]
----
FC_switch_A_1:root> license --show -port
24 ports are available in this switch
Full POD license is installed
Dynamic POD method is in use
----
.. Fabric OS 8.2.x以前を実行している場合は、ライセンス方式をdynamicに変更する必要があります。
+
licenseport -- メソッドの動的

+
[listing]
----
FC_switch_A_1:admin> licenseport --method dynamic
The POD method has been changed to dynamic.
Please reboot the switch now for this change to take effect
----


. スイッチをリブートします。
+
「 Fastboot 」を参照してください

+
[listing]
----
FC_switch_A_1:admin> fastboot
Warning: This command would cause the switch to reboot
and result in traffic disruption.
Are you sure you want to reboot the switch [y/n]?y
----
. デフォルト設定が実装されたことを確認します。
+
'witchshow'

. IP アドレスが正しく設定されていることを確認します。
+
ipAddrShow

+
必要に応じて、次のコマンドで IP アドレスを設定できます。

+
ipAddrSet


