---
permalink: install-fc/task_fmc_mcc_transition_configure_the_mcc_hardware_for_share_a_7_mode_brocade_6510_fc_fabric_dure_transition.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, hardware, brocade, fc, transition 
summary: 7-Mode ファブリック MetroCluster 構成で Brocade 6510 スイッチを使用している場合は、既存のスイッチファブリックを新しい clustered MetroCluster 構成と共有できます。スイッチファブリックを共有すれば、新しい MetroCluster 構成用にスイッチファブリックを別途新しく用意する必要がありません。この一時的な構成は、移行を目的として Brocade 6510 スイッチでのみサポートされています。 
---
= 移行中に Brocade 6510 FC ファブリックを共有するためのハードウェアの構成
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
7-Mode ファブリック MetroCluster 構成で Brocade 6510 スイッチを使用している場合は、既存のスイッチファブリックを新しい clustered MetroCluster 構成と共有できます。スイッチファブリックを共有すれば、新しい MetroCluster 構成用にスイッチファブリックを別途新しく用意する必要がありません。この一時的な構成は、移行を目的として Brocade 6510 スイッチでのみサポートされています。

.作業を開始する前に
* 7-Mode ファブリック MetroCluster で Brocade 6510 スイッチを使用している必要があります。
+
MetroCluster 構成で現在 Brocade 6510 スイッチを使用していない場合は、この手順を使用する前に、スイッチを Brocade 6510 にアップグレードする必要があります。

* 7-Mode ファブリックの MetroCluster 構成で SAS ストレージシェルフのみを使用している必要があります。
+
既存の構成に FC ストレージシェルフ（ DS14mk4 FC など）が含まれている場合は、 FC スイッチファブリックの共有はサポートされません。

* 新しい clustered MetroCluster 構成で使用されるスイッチポート上の SFP が、 16Gbps の速度をサポートしている必要があります。
+
既存の 7-Mode ファブリック MetroCluster は、 8Gbps または 16Gbps の SFP を使用するポートに接続したままでかまいません。

* 4 つの Brocade 6510 スイッチそれぞれで、ポート 24~45 が、新しい MetroCluster コンポーネントのポートの接続に使用できる必要があります。
* ポート 46 と 47 に既存のスイッチ間リンク（ ISL ）があることを確認する必要があります。
* Brocade 6510スイッチで、7-ModeファブリックのMetroCluster構成とONTAP MetroCluster構成の両方でサポートされているバージョンのFOSファームウェアが実行されている必要があります。


.完了後
ファブリックを共有して MetroCluster の設定を完了したら、 7-Mode ファブリックの MetroCluster 構成からデータを移行できます。

データを移行したら、7-ModeファブリックのMetroClusterケーブル接続を解除し、必要に応じて、ONTAP MetroClusterのケーブル接続を7-Mode MetroClusterのケーブル接続に使用していた番号の小さいポートに移動できます。ポートについては、「4ノードMetroClusterのFCスイッチのポート割り当ての確認」セクションを参照してください。ポートを再配置した場合は、ゾーニングを調整する必要があります。

link:concept_port_assignments_for_fc_switches_when_using_ontap_9_1_and_later.html["ONTAP 9.1 以降を使用している場合の FC スイッチのポート割り当て"]

.関連情報
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-7mtt-dctg/home.html["コピーベースの移行"]
