---
permalink: install-fc/task_assign_ownership_of_array_luns.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, assigning, ownership, array, luns 
summary: アレイ LUN をアグリゲートに追加してストレージとして使用するには、ノードに所有されていなければなりません。 
---
= アレイ LUN の所有権を割り当てます
:icons: font
:imagesdir: ../media/


[role="lead"]
アレイ LUN をアグリゲートに追加してストレージとして使用するには、ノードに所有されていなければなりません。

.作業を開始する前に
* バックエンド構成のテスト（ ONTAP システムの背後にあるデバイスの接続と構成のテスト）が完了している必要があります。
* 割り当てるアレイ LUN が ONTAP システムに提供されている必要があります。


所有権を割り当てることができるアレイ LUN の条件は次のとおりです。

* 所有権が設定されていない
* ストレージアレイの構成に関して次のようなエラーは発生しません。
+
** アレイ LUN のサイズが ONTAP でサポートされる範囲外である。
** LDEV が 1 つのポートにしかマッピングされていない。
** LDEV に割り当てられている各 LUN ID に一貫性がない。
** LUN のパスが 1 つしかない。




所有権の割り当てを行うアレイ LUN のバックエンド構成に ONTAP システムとストレージアレイの連携に支障をきたす問題があると、 ONTAP でエラーメッセージが表示されます。アレイ LUN の割り当てを続行するには、問題を修正する必要があります。

ONTAP では、アレイ LUN へのパスがすべて同じコントローラに接続されていたり、パスが 1 つしかないなど、割り当てようとしているアレイ LUN に冗長性の問題がある場合に警告が表示されます。冗長性の問題は、 LUN の所有権を割り当てる前に修正しても、割り当てたあとに修正してもかまいません。

.手順
. ノードにまだ割り当てられていないアレイ LUN を表示します。
+
'storage disk show -container-type unassigned （ storage disk show -container-type unassigned

. このノードにアレイ LUN を割り当てます。
+
「 storage disk assign -disk array_LUN_name __ owner_nodename_` 」という名前になります

+
冗長性の問題をディスクの割り当て前ではなく割り当て後に修正する場合は 'storage disk assign コマンドで -force パラメータを使用する必要があります



https://docs.netapp.com/ontap-9/topic/com.netapp.doc.vs-irrg/home.html["FlexArray 仮想化のインストール要件およびリファレンス"]
