---
permalink: install-fc/task_configure_ontap_on_a_system_that_uses_only_array_luns.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, array luns, ontap 
summary: アレイ LUN で使用する ONTAP を設定する場合は、ルートアグリゲートとルートボリュームを設定し、診断およびリカバリ処理用のスペースをリザーブし、クラスタをセットアップする必要があります。 
---
= アレイ LUN のみを使用するシステムでの ONTAP の設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
アレイ LUN で使用する ONTAP を設定する場合は、ルートアグリゲートとルートボリュームを設定し、診断およびリカバリ処理用のスペースをリザーブし、クラスタをセットアップする必要があります。

.作業を開始する前に
* ONTAP システムをストレージアレイに接続する必要があります。
* ストレージアレイ管理者によって LUN が作成され、 ONTAP に提供されている必要があります。
* ストレージアレイ管理者によって LUN セキュリティが設定されている必要があります。


.このタスクについて
アレイ LUN で使用する各ノードを設定する必要があります。HA ペアのノードの場合は、 1 つのノードで設定のプロセスを完了してからパートナーノードの設定に進んでください。

.手順
. プライマリノードの電源をオンにして、コンソールに次のメッセージが表示されたら、 Ctrl+C キーを押してブートプロセスを中断します。
+
特別なブートメニューを表示するには 'CTRL-C を押します

. ブートメニューのオプション * 4 （ Clean configuration and initialize all disks ） * を選択します。
+
ONTAP で使用可能なアレイ LUN のリストが表示されます。また、ルートボリュームの作成に必要なアレイ LUN のサイズも表示されます。ルートボリュームの作成に必要なサイズは、使用する ONTAP システムによって異なります。

+
** アレイ LUN が割り当てられていない場合は、使用可能なアレイ LUN が ONTAP によって検出されて次の例のように表示されます。
+
[listing]
----
mcc8040-ams1::> disk show  NET-1.6 -instance
                  Disk: NET-1.6
        Container Type: aggregate
            Owner/Home: mcc8040-ams1-01 / mcc8040-ams1-01
               DR Home: -
    Stack ID/Shelf/Bay: -  / -  / -
                   LUN: 0
                 Array: NETAPP_INF_1
                Vendor: NETAPP
                 Model: INF-01-00
         Serial Number: 60080E50004317B4000003B158E35974
                   UID: 60080E50:004317B4:000003B1:58E35974:00000000:00000000:00000000:00000000:00000000:00000000
                   BPS: 512
         Physical Size: 87.50GB
              Position: data
Checksum Compatibility: block
             Aggregate: eseries
                  Plex: plex0
Paths:
                                LUN  Initiator Side        Target Side                                                        Link
Controller         Initiator     ID  Switch Port           Switch Port           Acc Use  Target Port                TPGN    Speed      I/O KB/s          IOPS
------------------ ---------  -----  --------------------  --------------------  --- ---  -----------------------  ------  -------  ------------  ------------
mcc8040-ams1-01    2c             0  mccb6505-ams1:16      mccb6505-ams1:18      AO  INU  20330080e54317b4              1   4 Gb/S             0             0
mcc8040-ams1-01    2a             0  mccb6505-ams1:17      mccb6505-ams1:19      ANO RDY  20320080e54317b4              0   4 Gb/S             0             0

Errors:
-
----
** アレイ LUN が以前に割り当てられていた場合、たとえばメンテナンスモードを使用していたときに、 ONTAP をインストールするノードまたはその HA パートナーからアレイ LUN が選択されているかどうかに応じて、使用可能なアレイ LUN のリストでローカルまたはパートナーとしてマークされます。
+
この例では、インデックス番号 3 と 6 のアレイ LUN は以前にこのノードから割り当てられていたため、 local とマークされています。

+
[listing]
----

**********************************************************************
* No disks are owned by this node, but array LUNs are assigned.      *
* You can use the following information to verify connectivity from  *
* HBAs to switch ports.  If the connectivity of HBAs to switch ports *
* does not match your expectations, configure your SAN and rescan.   *
* You can rescan by entering 'r' at the prompt for selecting         *
* array LUNs below.

**********************************************************************
             HBA  HBA WWPN           Switch port      Switch port WWPN
              ---  --------           -----------      ----------------
              0e 500a098001baf8e0  vgbr6510s203:25      20190027f88948dd
              0f 500a098101baf8e0 vgci9710s202:1-17      2011547feeead680
              0g 500a098201baf8e0  vgbr6510s203:27      201b0027f88948dd
              0h 500a098301baf8e0 vgci9710s202:1-18      2012547feeead680


No native disks were detected, but array LUNs were detected.
You will need to select an array LUN to be used to create the root aggregate and root volume.

The array LUNs visible to the system are listed below.  Select one array LUN to be used to
create the root aggregate and root volume.  **The root volume requires 350.0 GB of space.**

 Warning: The contents of the array LUN you select will be erased by ONTAP prior to their use.

Index  Array LUN Name           Model   Vendor    Size    Owner   Checksum  Serial Number
-----  -----------------------  ------  ------  --------  ------  --------  ------------------------
   0   vgci9710s202:2-24.0L19   RAID5   DGC     217.3 GB          Block     6006016083402B0048E576D7
   1   vgbr6510s203:30.126L20   RAID5   DGC     217.3 GB          Block     6006016083402B0049E576D7
   2   vgci9710s202:2-24.0L21   RAID5   DGC     217.3 GB          Block     6006016083402B004AE576D7
   3   vgbr6510s203:30.126L22   RAID5   DGC     405.4 GB  local   Block     6006016083402B004BE576D7
   4   vgci9710s202:2-24.0L23   RAID5   DGC     217.3 GB          Block     6006016083402B004CE576D7
   5   vgbr6510s203:30.126L24   RAID5   DGC     217.3 GB          Block     6006016083402B004DE576D7
   6   vgbr6510s203:30.126L25   RAID5   DGC     423.5 GB  local   Block     6006016083402B003CF93694
   7   vgci9710s202:2-24.0L26   RAID5   DGC     423.5 GB          Block     6006016083402B003DF93694
----


. ルートボリュームとして割り当てるアレイ LUN のインデックス番号を選択します。
+
ルートボリュームを作成するために十分なサイズのアレイ LUN を選択してください。

+
ルートボリュームの作成用に選択したアレイ LUN は「 local （ root ）」とマークされます。

+
次の例では、インデックス番号 3 のアレイ LUN がルートボリュームの作成用にマークされています。

+
[listing]
----

The root volume will be created on switch 0:5.183L33.

**ONTAP requires that 11.0 GB of space be reserved for use in diagnostic and recovery
operations.**  Select one array LUN to be used as spare for diagnostic and recovery operations.

Index Array LUN Name    Model       Vendor    Size   Owner           Checksum  Serial Number
----- ----------------- ----------  ------  -------- --------------  --------  ------------------------
   0  switch0:5.183L1   SYMMETRIX   EMC     266.1 GB                 Block     600604803436313734316631
   1  switch0:5.183L3   SYMMETRIX   EMC     266.1 GB                 Block     600604803436316333353837
   2  switch0:5.183L31  SYMMETRIX   EMC     266.1 GB                 Block     600604803436313237643666
   3  switch0:5.183L33  SYMMETRIX   EMC     658.3 GB local  (root)   Block     600604803436316263613066
   4  switch0:7.183L0   SYMMETRIX   EMC     173.6 GB                 Block     600604803436313261356235
   5  switch0:7.183L2   SYMMETRIX   EMC     173.6 GB                 Block     600604803436313438396431
   6  switch0:7.183L4   SYMMETRIX   EMC     658.3 GB                 Block     600604803436313161663031
   7  switch0:7.183L30  SYMMETRIX   EMC     173.6 GB                 Block     600604803436316538353834
   8  switch0:7.183L32  SYMMETRIX   EMC     266.1 GB                 Block     600604803436313237353738
   9  switch0:7.183L34  SYMMETRIX   EMC     658.3 GB                 Block     600604803436313737333662
----
. 診断とリカバリのオプション用に割り当てるアレイ LUN のインデックス番号を選択します。
+
診断とリカバリのオプションで使用するために十分なサイズのアレイ LUN を選択してください。必要に応じて、合計が必要なサイズ以上になるよう、複数のアレイ LUN を組み合わせて選択することもできます。複数の LUN を選択するには、診断とリカバリのオプション用に選択するアレイ LUN のすべてのインデックス番号をカンマで区切って入力する必要があります。

+
次の例では、ルートボリュームの作成用に選択したアレイ LUN 、および診断とリカバリのオプション用に選択したアレイ LUN のリストが表示されています。

+
[listing]
----

Here is a list of the selected array LUNs
Index Array LUN Name     Model      Vendor    Size    Owner          Checksum  Serial Number
----- -----------------  ---------  ------  --------  -------------  --------  ------------------------
   2  switch0:5.183L31   SYMMETRIX  EMC     266.1 GB  local          Block     600604803436313237643666
   3  switch0:5.183L33   SYMMETRIX  EMC     658.3 GB  local   (root) Block     600604803436316263613066
   4  switch0:7.183L0    SYMMETRIX  EMC     173.6 GB  local          Block     600604803436313261356235
   5  switch0:7.183L2    SYMMETRIX  EMC     173.6 GB  local          Block     600604803436313438396431
Do you want to continue (yes|no)?
----
+

NOTE: 「 no 」を選択すると、 LUN の選択が解除されます。

. インストール処理を続行するかどうかを確認するメッセージが表示されたら '*y*' と入力します
+
ルートアグリゲートとルートボリュームが作成され、残りのインストールプロセスが続行されます。

. ノード管理インターフェイスの作成に必要な詳細を入力します。
+
次の例では、ノード管理インターフェイス画面に、ノード管理インターフェイスの作成に関する確認メッセージが表示されています。

+
[listing]
----
Welcome to node setup.

You can enter the following commands at any time:
  "help" or "?" - if you want to have a question clarified,
  "back" - if you want to change previously answered questions, and
  "exit" or "quit" - if you want to quit the setup wizard.
     Any changes you made before quitting will be saved.

To accept a default or omit a question, do not enter a value.

Enter the node management interface port [e0M]:
Enter the node management interface IP address: 192.0.2.66

Enter the node management interface netmask: 255.255.255.192
Enter the node management interface default gateway: 192.0.2.7
A node management interface on port e0M with IP address 192.0.2.66 has been created.

This node has its management address assigned and is ready for cluster setup.
----


.完了後
アレイ LUN で使用するすべてのノードで ONTAP を設定したら、の作業を完了しますhttps://["クラスタのセットアッププロセス"]

.関連情報
https://["FlexArray 仮想化のインストール要件およびリファレンス"]
