---
permalink: install-fc/task_fmc_mcc_transition_disable_one_of_the_switch_fabrics.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, disable, switch, fabrics 
summary: 一方のスイッチファブリックを無効化して、設定を変更できるようにする必要があります。設定を完了し、スイッチファブリックを再度有効にしたあとに、もう一方のファブリックでも処理を繰り返します。 
---
= 一方のスイッチファブリックを無効にします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
一方のスイッチファブリックを無効化して、設定を変更できるようにする必要があります。設定を完了し、スイッチファブリックを再度有効にしたあとに、もう一方のファブリックでも処理を繰り返します。

.作業を開始する前に
設定プロセスを開始する前に、既存の 7-Mode ファブリックの MetroCluster 設定で fmc_dc ユーティリティを実行し、問題がある場合は解決しておく必要があります。

.このタスクについて
MetroCluster 構成の継続的な運用を確保するために、最初のファブリックが無効になっている間は 2 番目のファブリックを無効にしないでください。

.手順
. ファブリック内の各スイッチを無効にします。
+
'witchcfgpersistentdisable

+
このコマンドが使用できない場合は、「 witchDisable 」コマンドを使用します。

+
** 次の例は、 FC_switch_A_1 で実行するコマンドを示しています。
+
[listing]
----
FC_switch_A_1:admin> switchCfgPersistentDisable
----
** 次の例は、 FC_switch_B_1 で実行するコマンドを示しています。
+
[listing]
----
FC_switch_B_1:admin> switchCfgPersistentDisable
----


. 7-Mode の MetroCluster 構成が、冗長ファブリックを使用して正しく機能していることを確認します。
+
.. コントローラのフェイルオーバーが正常であることを確認します :+'cf status
+
[listing]
----
node_A> cf status
Controller Failover enabled, node_A is up.
VIA Interconnect is up (link 0 down, link 1 up).
----
.. ディスクが表示されていることを確認します。 +'storage show disk – p'
+
[listing]
----
node_A> storage show disk –p

PRIMARY                     PORT  SECONDARY          PORT SHELF BAY
--------------------------- ----  ------------------ ---- ---------
Brocade-6510-2K0GG:5.126L27  B                              1    0
Brocade-6510-2K0GG:5.126L28  B                              1    1
Brocade-6510-2K0GG:5.126L29  B                              1    2
Brocade-6510-2K0GG:5.126L30  B                              1    3
Brocade-6510-2K0GG:5.126L31  B                              1    4

.
.
.
----
.. アグリゲートが正常であることを確認します。 +`aggr status`
+
[listing]
----
node_A> aggr status
           Aggr State           Status              Options
          aggr0 online          raid_dp, aggr       root, nosnap=on
                                mirrored
                                64-bit
----



