---
permalink: install-fc/task_install_the_license_for_us_array_luns_in_a_mcc_configuration.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, license, array, luns, configuration 
summary: アレイ LUN で使用する各 MetroCluster ノードに V_StorageAttach ライセンスをインストールする必要があります。ライセンスをインストールするまで、アグリゲートのアレイ LUN は使用できません。 
---
= MetroCluster 構成でアレイ LUN を使用するためのライセンスをインストールする
:icons: font
:imagesdir: ../media/


[role="lead"]
アレイ LUN で使用する各 MetroCluster ノードに V_StorageAttach ライセンスをインストールする必要があります。ライセンスをインストールするまで、アグリゲートのアレイ LUN は使用できません。

* クラスタがインストールされている必要があります。
* V_StorageAttach ライセンスのライセンスキーを用意しておく必要があります。


V_StorageAttach ライセンスをインストールするノードごとに、個別のライセンスキーを使用する必要があります。

.手順
. 「 system license add 」コマンドを使用して、 V_StorageAttach ライセンスをインストールします。
+
ライセンスをインストールする各クラスタノードについて、この手順を繰り返します。

. 「 system license show 」コマンドを使用して、クラスタ内のすべての必要なノードに V_StorageAttach ライセンスがインストールされていることを確認します。
+
次の出力例では、 cluster_A のノードに V_StorageAttach ライセンスがインストールされています。

+
[listing]
----

cluster_A::> system license show
Serial Number: nnnnnnnn
Owner: controller_A_1
Package           Type    Description           Expiration
----------------- ------- --------------------- --------------------
V_StorageAttach   license Virtual Attached Storage


Serial Number: llllllll
Owner: controller_A_2
Package           Type    Description           Expiration
----------------- ------- --------------------- --------------------
V_StorageAttach   license Virtual Attached Storage
----

