---
permalink: install-fc/task_fmc_mcc_transition_ensure_isls_are_in_the_same_port_group_and_configure_zon.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, ensure, port, group, configure, zoning 
summary: スイッチ間リンク（ ISL ）が同じポートグループに含まれていることを確認し、 MetroCluster 構成でスイッチファブリックを共有するためのゾーニングを設定する必要があります。 
---
= ISL が同じポートグループにあることを確認し、ゾーニングを設定します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
MetroCluster 構成でスイッチファブリックを共有するために、スイッチ間リンク（ ISL ）が同じポートグループに含まれることを確認し、ゾーニングを設定する必要があります。

.手順
. ISL が同じポートグループに含まれていない場合は、一方の ISL ポートをもう一方と同じポートグループに移動します。
+
新しい MetroCluster 構成で使用される 32~45 以外の使用可能なポートを使用できます。推奨される ISL ポートは 46 と 47 です。

. の手順に従います link:task_fcsw_brocade_configure_the_brocade_fc_switches_supertask.html["Brocade FC スイッチでゾーニングを設定します"] トランキングと QoS ゾーンをイネーブルにするには、を参照してください。
+
ファブリックを共有する場合のポート番号は、のセクションに記載されている番号とは異なります。共有する場合は、ポート 46 と 47 を ISL ポートに使用します。ISL ポートを移動した場合は、の手順を使用する必要があります link:task_fcsw_brocade_configure_the_brocade_fc_switches_supertask.html["Brocade FC スイッチでの E ポートの設定"] セクションでポートを設定します。

. [[step3_zones ]] の手順に従います link:task_fcsw_brocade_configure_the_brocade_fc_switches_supertask.html["Brocade スイッチでの非 E ポートの設定"] セクションで非 E ポートを設定します。
. の Traffic Isolation （ TI ）ゾーンを除き、バックエンドスイッチにすでに存在するゾーンまたはゾーンセット（ 7-Mode ファブリック MetroCluster の場合）は削除しないでください ,手順 3。
. の手順に従います link:task_fcsw_brocade_configure_the_brocade_fc_switches_supertask.html["Brocade FC スイッチでの E ポートの設定"] セクションで、新しい MetroCluster で必要なゾーンを既存のゾーンセットに追加します。
+
次の例は、ゾーンを作成するコマンドと出力を示しています。

+
[listing]
----
Brocade-6510-2K0GG:admin> zonecreate "QOSH2_FCVI_1", "2,32; 2,35; 1,32; 1,35"

Brocade-6510-2K0GG:admin> zonecreate "STOR_A_2_47", "2,33; 2,34; 2,36; 2,37; 1,33; 1,34; 1,36; 1,37; 1,47"

Brocade-6510-2K0GG:admin> zonecreate "STOR_B_2_47", "2,33; 2,34; 2,36; 2,37; 1,33; 1,34; 1,36; 1,37; 2,47"


Brocade-6510-2K0GG:admin> cfgadd config_1_FAB2, "QOSH2_FCVI_1; STOR_A_2_47; STOR_B_2_47"

Brocade-6510-2K0GG:admin> cfgenable "config_1_FAB2"
You are about to enable a new zoning configuration.
This action will replace the old zoning configuration with the
current configuration selected. If the update includes changes
to one or more traffic isolation zones, the update may result in
localized disruption to traffic on ports associated with
the traffic isolation zone changes
Do you want to enable 'config_1_FAB2' configuration  (yes, y, no, n): [no] yes

Brocade-6510-2K0GG:admin> cfgsave
You are about to save the Defined zoning configuration. This
action will only save the changes on Defined configuration.
Do you want to save the Defined zoning configuration only?  (yes, y, no, n): [no] yes
Nothing changed: nothing to save, returning ...
Brocade-6510-2K0GG:admin>
----

