= クラスタピアリングの前提条件
:allow-uri-read: 


各 MetroCluster サイトは、パートナーサイトのピアとして設定されます。ピア関係を設定するための前提条件とガイドラインを理解しておく必要があります。これは、それらの関係に共有ポートと専用ポートのどちらを使用するかを決定する際に重要になります。

.関連情報
http://["クラスタと SVM のピアリングの簡単な設定"]



== クラスタピアリングの前提条件

クラスタピアリングを設定する前に、ポート、 IP アドレス、サブネット、ファイアウォール、およびクラスタの命名要件の間の接続が満たされていることを確認する必要があります。



=== 接続要件

ローカルクラスタのすべてのクラスタ間 LIF が、リモートクラスタのすべてのクラスタ間 LIF と通信できる必要があります。

必須ではありませんが、一般に、クラスタ間 LIF には同じサブネットの IP アドレスを使用した方が構成がシンプルになります。IP アドレスは、データ LIF と同じサブネット内や、別のサブネット内に存在できます。各クラスタで使用するサブネットは、次の要件を満たしている必要があります。

* サブネットには、各ノードに 1 つのインタークラスタ LIF が割り当てられる十分な数の IP アドレスが必要です。
+
たとえば、 4 ノードクラスタの場合、クラスタ間通信で使用するサブネットには、使用可能な IP アドレスが 4 つ必要です。



クラスタ間ネットワークでは、各ノードにインタークラスタ LIF と IP アドレスが必要です。

クラスタ間 LIF のアドレスには IPv4 または IPv6 のいずれかを使用できます。


NOTE: ONTAP 9 では、必要に応じて IPv4 プロトコルと IPv6 プロトコルがクラスタ間 LIF に共存することを許可し、 IPv4 から IPv6 にピアリングネットワークを移行できます。以前のリリースでは、クラスタ全体のすべてのクラスタ間関係が IPv4 または IPv6 のどちらかだったため、プロトコルの変更はシステム停止を伴うイベントでした。



=== ポート要件

クラスタ間通信には専用のポートを使用することも、データネットワークで使用されているポートを共有することもできます。ポートは、次の要件を満たしている必要があります。

* あるリモートクラスタとの通信に使用するポートは、すべて同じ IPspace に属している必要があります。
+
複数のクラスタとのピア関係の作成には複数の IPspace を使用できます。ペアワイズのフルメッシュ接続は IPspace 内でのみ必要になります。

* クラスタ間通信で使用されるブロードキャストドメインに、 1 ノードあたり最低 2 つのポートがあり、クラスタ間通信で別のポートへのフェイルオーバーが可能になっている。
+
ブロードキャストドメインに追加できるポートは、物理ネットワークポート、 VLAN 、インターフェイスグループ（ ifgrps ）です。

* すべてのポートが接続されている。
* すべてのポートが正常な状態である必要があります。
* ポートの MTU 設定が一貫している。




=== ファイアウォールの要件

ファイアウォールとクラスタ間ファイアウォールポリシーでは、次のプロトコルを許可する必要があります。

* ICMP サービス
* ポート 10000 、 11104 、および 11105 経由でのすべてのインタークラスタ LIF の IP アドレスへの TCP 接続
* クラスタ間 LIF 間の双方向 HTTPS


デフォルトのクラスタ間ファイアウォールポリシーは、 HTTPS プロトコル経由のアクセス、およびすべての IP アドレス（ 0.0.0.0/0 ）からのアクセスを許可します。ポリシーは必要に応じて変更または置き換えできます。



== 専用のポートを使用する場合の考慮事項

専用のポートを使用することが適切なクラスタ間ネットワーク解決策であるかどうかを判断するには、 LAN のタイプ、利用可能な WAN 帯域幅、レプリケーション間隔、変更率、ポート数などの設定や要件を考慮する必要があります。

専用のポートを使用することがクラスタ間ネットワーク解決策として適切であるかどうかを判断するには、ネットワークについて次の事項を考慮してください。

* 使用できる WAN 帯域幅が LAN ポートの帯域幅とほぼ同じで、レプリケーション間隔の設定により、通常のクライアントアクティビティが実行されている間にレプリケーションが実行される場合は、クラスタ間レプリケーションにイーサネットポートを専用に割り当てて、レプリケーションとデータプロトコルとの競合を回避します。
* データプロトコル（ CIFS 、 NFS 、 iSCSI ）によるネットワーク利用率が 50% を超える場合は、レプリケーションにポートを専用に割り当てて、ノードのフェイルオーバーが発生してもパフォーマンスが低下しないようにします。
* 10GbE 以上の物理ポートがデータとレプリケーションの両方に使用されている場合は、レプリケーション用に VLAN ポートを作成し、論理ポートをクラスタ間レプリケーション専用にすることができます。
+
ポートの帯域幅は、すべての VLAN とベースポートで共有されます。

* データの変更率とレプリケーション間隔について検討し、間隔ごとにレプリケートする必要があるデータの量に十分な帯域幅が必要かどうかを検討します。データポートを共有すると、原因がデータプロトコルと競合する可能性があります。




== データポートを共有する場合の考慮事項

クラスタ間レプリケーションのためにデータポートを共有することが、正しいクラスタ間ネットワーク解決策であるかどうかを判断するには、 LAN のタイプ、利用可能な WAN 帯域幅、レプリケーション間隔、変更率、ポート数などの設定や要件を考慮する必要があります。

データポートを共有することがクラスタ間接続解決策として適切であるかどうかを判断するには、ネットワークについて次の事項を考慮してください。

* 40 ギガビットイーサネット（ 40GbE ）ネットワークのように高速なネットワークの場合は、データアクセスに使用されるのと同じ 40GbE ポート上に、レプリケーションを実行するためのローカル LAN 帯域幅が十分にあると考えられます。
+
多くの場合、使用できる WAN 帯域幅は、 10GbE の LAN 帯域幅よりもはるかに少なくなります。

* クラスタ内のすべてのノードが、データをレプリケートし、使用できる WAN 帯域幅を共有しなければならない場合、データポートを共有する方法は、比較的許容できる選択肢となります。
* データ用とレプリケーション用のポートを共有すると、ポートをレプリケーション専用にする場合の追加のポート数が不要になります。
* レプリケーションネットワークの最大伝送ユニット（ MTU ）サイズは、データネットワークで使用されるサイズと同じになります。
* データの変更率とレプリケーション間隔について検討し、間隔ごとにレプリケートする必要があるデータの量に十分な帯域幅が必要かどうかを検討します。データポートを共有すると、原因がデータプロトコルと競合する可能性があります。
* データポートをクラスタ間レプリケーション用に共有すると、同じノード上にある他の任意のクラスタ間対応ポートにクラスタ間 LIF を移行して、レプリケーションに使用する特定のデータポートを制御できます。

