---
permalink: releasenotes/mcc-new-features.html 
sidebar: sidebar 
keywords: new metrocluster features 
summary:  
---
= MetroClusterの機能の新機能
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[cols="20,65,15"]
|===
| MetroCluster構成でサポートされる機能 | 概要 と詳細情報の入手方法 | 最初から利用可能です 


 a| 
MetroCluster IPおよびイーサネット接続ストレージ用の共有スイッチを使用したMetroCluster FCからMetroCluster IPへの移行
 a| 
共有スイッチを使用して、MetroCluster FCからMetroCluster IP構成（ONTAP 9.8以降）に無停止で移行できます。

https://docs.netapp.com/us-en/ontap-metrocluster/transition/concept_nondisruptively_transitioning_from_a_four_node_mcc_fc_to_a_mcc_ip_configuration.html["MetroCluster FC から MetroCluster IP 構成への無停止での移行（ ONTAP 9.8 以降）"]
 a| 
ONTAP 9.13.1



 a| 
8ノードMetroCluster FC構成からMetroCluster IP構成への無停止での移行
 a| 
既存の8ノードMetroCluster FC構成から新しいMetroCluster IP構成に、ワークロードとデータを無停止で移行できます。

https://docs.netapp.com/us-en/ontap-metrocluster/transition/concept_nondisruptively_transitioning_from_a_four_node_mcc_fc_to_a_mcc_ip_configuration.html["MetroCluster FC構成からMetroCluster IP構成への無停止での移行"]
 a| 
ONTAP 9.13.1



 a| 
スイッチオーバーとスイッチバックを使用した4ノードMetroCluster IP構成のアップグレード
 a| 
スイッチオーバーとスイッチバックを使用して、4ノードMetroCluster IP構成のコントローラをアップグレードできます。 `system controller replace` コマンド

https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_upgrade_controllers_system_control_commands_in_a_four_node_mcc_ip.html["4ノードMetroCluster IP構成でのコントローラのアップグレード"]
 a| 
ONTAP 9.13.1



 a| 
環境のシャットダウン時にメディエーターアシスト自動計画外スイッチオーバー（MAUSO）がトリガーされる
 a| 
環境のシャットダウンにより一方のサイトが正常にシャットダウンすると、MAUSOがトリガーされます。

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_considerations_mediator.html#interoperability-of-ontap-mediator-with-other-applications-and-appliances["ONTAP メディエーターと他のアプリケーションおよびアプライアンスとの相互運用性"]
 a| 
ONTAP 9.13.1



 a| 
8ノードMetroCluster IP構成のサポート
 a| 
8ノードMetroCluster IP構成のコントローラとストレージをアップグレードするには、構成を拡張して一時的な12ノード構成にし、古いDRグループを削除します。

https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_refresh_4n_mcc_ip.html["4 ノード MetroCluster IP 設定の更新"]
 a| 
ONTAP 9.13.1



 a| 
MetroCluster IP構成から共有ストレージMetroClusterスイッチ構成への変換
 a| 
MetroCluster IP構成を共有ストレージMetroClusterスイッチ構成に変換できます。

https://docs.netapp.com/us-en/ontap-metrocluster/maintain/task_replace_an_ip_switch.html["IP スイッチの交換"]
 a| 
ONTAP 9.13.1



 a| 
MetroCluster IP構成でのMetroCluster自動強制スイッチオーバー機能
 a| 
MetroClusterの自動強制スイッチオーバー機能は、MetroCluster IP構成で有効にすることができます。この機能は、Mediator-Assisted Unplanned Switchover（MAUSO；メディエーターアシスト計画外スイッチオーバー）機能の拡張です。

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept-risks-limitations-automatic-switchover.html["自動スイッチオーバーの制限事項"]
 a| 
ONTAP 9.12.1



 a| 
MetroCluster IP構成のミラーされていないアグリゲート上のSVM上のS3
 a| 
MetroCluster IP構成のミラーされていないアグリゲート上のSVMで、ONTAP Simple Storage Service（S3）オブジェクトストレージサーバを有効にすることができます。

https://docs.netapp.com/us-en/ontap/s3-config/index.html#s3-configuration-with-system-manager-and-the-ontap-cli["System ManagerおよびONTAP CLIを使用したS3の設定"]
 a| 
ONTAP 9.12.1



 a| 
MetroCluster FC構成からAFF A250 / FAS500f MetroCluster IP構成への移行
 a| 
MetroCluster FC構成からAFF A250またはFAS500f MetroCluster IP構成に移行できます。

https://docs.netapp.com/us-en/ontap-metrocluster/transition/task_move_cluster_connections.html#which-connections-to-move["ローカルクラスタ接続を移動します"]
 a| 
ONTAP 9.11.1



 a| 
MetroCluster IP構成でのレイヤ3 MetroCluster IPアドレスの設定
 a| 
レイヤ3構成のノードのMetroCluster IPアドレス、ネットマスク、およびゲートウェイを編集できます。

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_modify_ip_netmask_gateway_properties.html["MetroCluster IP のアドレス、ネットマスク、およびゲートウェイを変更する"]
 a| 
ONTAP 9.10.1



 a| 
MetroCluster FC構成でのノードのコントローラアップグレードの簡易化
 a| 
スイッチオーバーとスイッチバックを使用するアップグレードプロセスのアップグレード手順が簡易化されました。

https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_upgrade_controllers_in_a_four_node_fc_mcc_us_switchover_and_switchback_mcc_fc_4n_cu.html["スイッチオーバーとスイッチバックを使用して MetroCluster FC 構成のコントローラをアップグレードする"]
 a| 
ONTAP 9.10.1



 a| 
レイヤ3での共有リンクのIPサポート
 a| 
MetroCluster IP設定は、IPルーテッド（レイヤ3）バックエンド接続で実装できます。

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_considerations_layer_3.html["レイヤ 3 ワイドエリアネットワークに関する考慮事項"]
 a| 
ONTAP 9.9.1



 a| 
8ノードクラスタのサポート
 a| 
永続的な8ノードクラスタは、IPおよびファブリック接続構成でサポートされます。

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_install_and_cable_the_mcc_components.html["MetroCluster コンポーネントの設置とケーブル接続"]
 a| 
ONTAP 9.9.1



 a| 
System ManagerによるIP MetroCluster処理の管理インターフェイスの簡易化
 a| 
System Managerを使用して、IP MetroClusterサイトのセットアップ、サイトのペアリング、クラスタの設定など、IP MetroClusterの処理を管理できます。

https://docs.netapp.com/us-en/ontap/concept_metrocluster_manage_nodes.html["MetroCluster サイトを管理する"]
 a| 
ONTAP 9.8



 a| 
System ManagerでのIP MetroClusterのスイッチオーバーとスイッチバック
 a| 
System Managerを使用して、IP MetroCluster構成に対して計画的または計画外のスイッチオーバーおよびスイッチバックのすべての手順を実行できます。

https://docs.netapp.com/us-en/ontap/task_metrocluster_switchover_switchback.html["MetroCluster のスイッチオーバーとスイッチバック"]
 a| 
ONTAP 9.8



 a| 
MetroCluster FC から MetroCluster IP 構成への移行
 a| 
既存の4ノードMetroCluster FC構成から新しいMetroCluster IP構成へのワークロードとデータの移行がサポートされます。

https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/concept_choosing_an_upgrade_method_mcc.html["MetroCluster 構成をアップグレード、更新、または拡張します"]

https://docs.netapp.com/us-en/ontap-metrocluster/transition/concept_choosing_your_transition_procedure_mcc_transition.html["MetroCluster FC から MetroCluster IP に移行します"]
 a| 
ONTAP 9.8



 a| 
新しいアップグレード手順と更新手順
 a| 
4ノードMetroClusterのFC / IP構成では、ハードウェアのアップグレードまたは更新がサポートされます。

https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/concept_choosing_an_upgrade_method_mcc.html["MetroCluster 構成をアップグレード、更新、または拡張します"]

https://docs.netapp.com/us-en/ontap-metrocluster/transition/concept_choosing_your_transition_procedure_mcc_transition.html["MetroCluster FC から MetroCluster IP に移行します"]
 a| 
ONTAP 9.8



 a| 
ミラーされてないアグリゲート
 a| 
ミラーされていないアグリゲートはMetroCluster IP構成でサポートされます。

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/considerations_unmirrored_aggrs.html["ミラーされていないアグリゲートに関する考慮事項"]
 a| 
ONTAP 9.8



 a| 
MetroCluster準拠スイッチ
 a| 
MetroCluster IP構成では、NetApp仕様に準拠していれば、NetAppで検証されていないスイッチをサポートできます。

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_considerations_mc_compliant_switches.html["MetroCluster 準拠スイッチの使用に関する考慮事項"]
 a| 
ONTAP 9.7



 a| 
プライベートレイヤ2ネットワーク共有
 a| 
サポート対象のCiscoスイッチを使用するMetroCluster IP構成では、専用のMetroCluster ISLを使用するのではなく、既存のネットワークをISLで共有できます。それよりも前のバージョンの ONTAP では専用の ISL が必要

MetroCluster IPスイッチはMetroCluster構成専用であり、共有することはできません。共有スイッチに接続できるのは、 MetroCluster IP スイッチの MetroCluster ISL ポートだけです。

[CAUTION]
====
共有ネットワークを使用する場合は、共有ネットワークの MetroCluster ネットワーク要件を満たす必要があります。

====
https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/index.html["MetroCluster IP のインストールと設定"]
 a| 
ONTAP 9.6



 a| 
MetroCluster のスイッチオーバーとスイッチバック
 a| 
1つのクラスタサイトで別のクラスタサイトのタスクをテイクオーバーすることができます。メンテナンス時や災害からのリカバリ時に便利な機能です。

https://docs.netapp.com/us-en/ontap-metrocluster/manage/index.html["MetroCluster のスイッチオーバーとスイッチバック"]
 a| 
ONTAP 9.6



 a| 
ONTAP System Managerでのクラスタの更新
 a| 
MetroCluster構成のクラスタを更新できます。MetroCluster構成のクラスタの場合、クラスタの更新を除き、それぞれの処理を両方のクラスタで実行する必要があります。

https://docs.netapp.com/us-en/ontap-sm-classic/online-help-96-97/index.html["System Manager を使用したクラスタの管理"]
 a| 
ONTAP 9.5

|===