---
permalink: releasenotes/mcc-mediator-whats-new.html 
sidebar: sidebar 
keywords: metrocluster, mediator, new, release, update, install, 
summary: ONTAP メディエーターには、リリースごとに新しい機能が追加されています。  最新情報をご紹介します。 
---
= MetroCluster向けONTAP Mediator サポートの新機能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP Mediator サポートのMetroCluster の新機能と拡張機能について説明します。

ONTAPメディエーターの各リリースの機能と拡張機能の詳細については、link:https://docs.netapp.com/us-en/ontap/mediator/whats-new-concept.html["ONTAPメディエーターの新機能"^] 。

[cols="4,2"]
|===
| ONTAPメディエーター機能 | 最初から利用可能です 


 a| 
MetroCluster IP 構成では、 ONTAP Mediator 1.11 以降で IPv6 がサポートされます。

link:../install-ip/task_configuring_the_ontap_mediator_service_from_a_metrocluster_ip_configuration.html["MetroCluster IP構成用のONTAPメディエーターを設定する"]
 a| 
ONTAP 9.18.1



 a| 
ONTAP Mediator 1.11 では、単一のONTAP Mediator インスタンスを使用して最大 10 個のMetroCluster IP 構成を管理するためのサポートが追加されました。

link:../install-ip/concept_mediator_requirements.html["MetroCluster IP構成にONTAPメディエーターをインストールする準備"]
 a| 
ONTAP 9.18.1



 a| 
環境がシャットダウンした場合は、Mediator-Assisted Automatic Unplanned Switchover（MAUSO；メディエーターアシスト自動計画外スイッチオーバー）がサポートされます。

環境のシャットダウンにより一方のサイトが正常にシャットダウンすると、MAUSOがトリガーされます。

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept-ontap-mediator-supports-automatic-unplanned-switchover.html["ONTAPメディエーターが計画外の自動スイッチオーバーをサポートする仕組み"]
 a| 
ONTAP 9.13.1



 a| 
MetroCluster IP構成におけるONTAP Mediatorの初期サポート
 a| 
ONTAP 9.7

|===