---
permalink: releasenotes/mcc-config-support-features.html 
sidebar: sidebar 
keywords: metrocluster, configuration, support for ontap features 
summary:  
---
= MetroCluster構成でのONTAP機能のサポートの新機能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9データ管理ソフトウェアの各リリースには、ONTAP MetroCluster構成の機能、管理性、パフォーマンスを向上させる新機能と強化された機能が搭載されています。

ONTAP MetroCluster構成に影響する既知の問題、制限事項、およびアップグレードに関する注意事項の詳細については、『 https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["ONTAP 9 リリースノート"^]。リリースノートにアクセスするには、NetAppアカウントでサインインするか、アカウントを作成する必要があります。

[cols="20,65,15"]
|===
| MetroCluster構成でサポートされる機能 | 説明 | 最初から利用可能です 


 a| 
MetroCluster IPでのNVMeのサポート
 a| 
NVMe/TCPフロントエンドホストプロトコルは、4ノードMetroCluster IP構成でサポートされます。

link:https://docs.netapp.com/us-en/ontap/san-admin/san-config-mcc-concept.html["MetroCluster 環境のSAN構成"^]
 a| 
ONTAP 9.15.1



 a| 
ミラーアグリゲートとミラーされていないアグリゲートでのS3オブジェクトストレージのサポート
 a| 
MetroCluster IPおよびFC構成では、ミラーされたアグリゲートまたはミラーされていないアグリゲート内のSVMでS3オブジェクトストレージサーバを有効にすることができます。

https://docs.netapp.com/us-en/ontap/s3-config/index.html["S3構成の概要"]
 a| 
ONTAP 9.14.1



 a| 
MetroClusterクラスタ内のミラーされたアグリゲートとミラーされていないアグリゲートでのS3バケットのプロビジョニングのサポート
 a| 
MetroCluster構成では、ミラーされたアグリゲートまたはミラーされていないアグリゲートにバケットを作成できます。

https://docs.netapp.com/us-en/ontap/s3-config/create-bucket-mcc-task.html["MetroCluster構成のミラーされたアグリゲートまたはミラーされていないアグリゲートにバケットを作成する"]
 a| 
ONTAP 9.12.1



 a| 
MetroCluster IPでのNVMeのサポート
 a| 
NVMe/FCプロトコルは、4ノードMetroCluster IP構成でサポートされます。

link:https://docs.netapp.com/us-en/ontap/san-admin/san-config-mcc-concept.html["MetroCluster 環境のSAN構成"^]
 a| 
ONTAP 9.12.1



 a| 
MetroCluster IPおよびMetroClusterファブリック接続構成でのフロントエンドホストプロトコルのIPSecサポート
 a| 
フロントエンドホストプロトコル（NFSやiSCSIなど）のIPSecサポートは、MetroCluster IPおよびMetroClusterファブリック接続構成で使用できます。

https://docs.netapp.com/us-en/ontap/networking/configure_ip_security_@ipsec@_over_wire_encryption.html["ワイヤ暗号化を介した IP セキュリティ（ IPsec ）を設定します"]
 a| 
ONTAP 9.11.1



 a| 
整合グループ
 a| 
MetroCluster構成では整合グループがサポートされます。
 a| 
ONTAP 9.7



 a| 
MetroCluster ミラーは FabricPool 構成にあります
 a| 
MetroCluster構成でミラーされたFabricPoolをセットアップして、コールドデータを2つの異なる障害ゾーンに階層化できます。

https://docs.netapp.com/us-en/ontap/fabricpool/setup-object-stores-mcc-task.html["MetroCluster 構成での FabricPool 用オブジェクトストアのセットアップ"]
 a| 
ONTAP 9.7



 a| 
SVM ディザスタリカバリ
 a| 
MetroCluster構成のアクティブなStorage Virtual Machine（SVM）は、SnapMirror SVMディザスタリカバリ機能でソースとして使用できます。
 a| 
ONTAP 9.5

|===