---
permalink: releasenotes/mcc-new-features.html 
sidebar: sidebar 
keywords: new metrocluster features 
summary:  
---
= MetroClusterの機能の新機能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9データ管理ソフトウェアの各リリースには、ONTAP MetroCluster構成の機能、管理性、パフォーマンスを向上させる新機能と強化された機能が搭載されています。

ONTAP MetroCluster構成に影響する既知の問題、制限事項、およびアップグレードに関する注意事項の詳細については、『 https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["ONTAP 9 リリースノート"^]。リリースノートにアクセスするには、NetAppアカウントでサインインするか、アカウントを作成する必要があります。

[cols="20,65,15"]
|===
| MetroCluster構成でサポートされる機能 | 概要 と詳細情報の入手方法 | 最初から利用可能です 


 a| 
エンドツーエンドの暗号化のためのMetroCluster IPサポート
 a| 
次のシステムでは、 MetroCluster IP 構成のサイト間の NVlog やストレージ レプリケーション データなどのバックエンド トラフィックを暗号化するためのエンドツーエンドの暗号化がサポートされています。

* AFF A800、AFF C800
* AFF A20、 AFF A30、 AFF C30、 AFF A50、 AFF C60
* AFF A70、AFF A90、AFF A1K、AFF C80
* FAS50、FAS70、FAS90


link:../maintain/task-configure-encryption.html["MetroCluster IP構成でのエンドツーエンドの暗号化の設定"]
 a| 
ONTAP 9.17.1



 a| 
MetroCluster IP構成の変更を制限する
 a| 
ONTAP 9.17.1 には、4 ノードMetroCluster IP 構成の次の制限の更新が含まれています。

* AFF C800、 AFF A800、 AFF A900、 AFF A90、およびAFF A1Kシステムには、次の更新された制限があります。
+
** ノードあたりのFlexVol volume制限: 1250
** SVM の制限: クラスターあたり 64 SVM
** LIF数: クラスタあたり256個のLIF


* AFF A400、 AFF C400、 ASA A400、 ASA C400、 AFF C80、 AFF A70、およびAFF A50 システムには、次の更新された制限があります。
+
** アグリゲートあたりのFlexVol volume制限（単一または複数）: 625
** ノードあたりのFlexVol volume制限: 1250
** 高可用性（HA）ペアあたりのFlexVol volume制限：2500
** クラスタあたりのFlexVol volume制限: 5000
** SVM の制限: クラスターあたり 64 SVM
** LIF数: クラスタあたり256個のLIF




参照link:https://hwu.netapp.com["Hardware Universe"^]詳細についてはこちらをご覧ください。
 a| 
ONTAP 9.17.1



 a| 
資格情報を使用したFibreBridgeファームウェアのアップデート
 a| 
サーバーがファームウェア パッケージをダウンロードするために資格情報を必要とする場合は、資格情報を使用して FibreBridge ブリッジのファームウェアを更新できます。

link:../maintain/task_update_firmware_on_a_fibrebridge_bridge_parent_topic.html["FibreBridge ブリッジのファームウェアを更新します"]
 a| 
ONTAP 9 .16.1



 a| 
MetroCluster構成の移行におけるSVMデータ移動のサポート
 a| 
ONTAPでサポートされるMetroCluster SVMの移行は次のとおりです。

* MetroCluster以外のHAペアとMetroCluster IP構成間でのSVMの移行
* 2つのMetroCluster IP構成間でのSVMの移行
* MetroCluster FC構成とMetroCluster IP構成間でのSVMの移行


link:https://docs.netapp.com/us-en/ontap/svm-migrate/index.html["SVMのデータ移動"^]
 a| 
ONTAP 9 .16.1



 a| 
BGPピアグループのMD5認証サポート
 a| 
ONTAPはBGPピアグループでMD5認証をサポートして、BGPセッションを保護します。MD5がイネーブルの場合、BGPセッションは許可されたピア間でのみ確立および処理されるため、許可されていないアクターによるセッションの中断を防ぐことができます。

link:https://docs.netapp.com/us-en/ontap/networking/configure_virtual_ip_@vip@_lifs.html["仮想IP（VIP）LIFの設定"^]
 a| 
ONTAP 9 .16.1



 a| 
エンドツーエンドの暗号化のためのMetroCluster IPサポート
 a| 
AFF A400、FAS8300、FAS8700システムでは、MetroCluster IP構成のサイト間のNVLOGやストレージレプリケーションデータなどのバックエンドトラフィックを暗号化するために、エンドツーエンドの暗号化がサポートされています。

link:../maintain/task-configure-encryption.html["MetroCluster IP構成でのエンドツーエンドの暗号化の設定"]
 a| 
ONTAP 9.15.1



 a| 
AFF A800およびAFF C800システムでの4ノードMetroCluster IP構成のボリューム制限の拡張
 a| 
4ノードMetroCluster IP構成では、AFF A800およびAFF C800システムの次のボリューム制限が拡張されました。

* アグリゲートあたりのFlexVolの最大数が200から625に増加しました。
* ノードあたりのFlexVolの最大ボリューム数が800から1250に増加しました。
* HA ペアあたりのFlexVolボリュームの最大数が 1600 から 2500 に増加しました。

 a| 
ONTAP 9.15.1



 a| 
MetroCluster IPでのNVMeのサポート
 a| 
NVMe/TCPフロントエンドホストプロトコルは、4ノードMetroCluster IP構成でサポートされます。

link:https://docs.netapp.com/us-en/ontap/san-admin/san-config-mcc-concept.html["MetroCluster 環境のSAN構成"^]
 a| 
ONTAP 9.15.1



 a| 
AFF A900システムでの4ノードMetroCluster IP構成のボリューム制限の拡張
 a| 
4ノードMetroCluster IP構成では、AFF A900システムの次のボリューム制限が引き上げられました。

* アグリゲートあたりのFlexVolの最大数が200から625に増加しました。
* ノードあたりのFlexVolの最大ボリューム数が800から1250に増加しました。
* HA ペアあたりのFlexVolボリュームの最大数が 1600 から 2500 に増加しました。

 a| 
ONTAP 9.14.1



 a| 
ミラーアグリゲートとミラーされていないアグリゲートでのS3オブジェクトストレージのサポート
 a| 
MetroCluster IPおよびFC構成では、ミラーされたアグリゲートまたはミラーされていないアグリゲート内のSVMでS3オブジェクトストレージサーバを有効にすることができます。

https://docs.netapp.com/us-en/ontap/s3-config/ontap-version-support-s3-concept.html#s3-support-with-metrocluster["MetroClusterによるS3のサポート"^]
 a| 
ONTAP 9.14.1



 a| 
MetroClusterクラスタ内のミラーされたアグリゲートとミラーされていないアグリゲートでのS3バケットのプロビジョニングのサポート
 a| 
MetroCluster構成では、ミラーされたアグリゲートまたはミラーされていないアグリゲートにバケットを作成できます。

link:https://docs.netapp.com/us-en/ontap/s3-config/create-bucket-mcc-task.html#process-to-create-buckets["MetroCluster構成のミラーされたアグリゲートまたはミラーされていないアグリゲートにONTAP S3バケットを作成する"^]
 a| 
ONTAP 9.14.1



 a| 
MetroCluster IPおよびイーサネット接続ストレージ用の共有スイッチを使用したMetroCluster FCからMetroCluster IPへの移行
 a| 
共有ストレージスイッチを使用して、MetroCluster FC構成からMetroCluster IP構成に無停止で移行できます。

https://docs.netapp.com/us-en/ontap-metrocluster/transition/concept_nondisruptively_transitioning_from_a_four_node_mcc_fc_to_a_mcc_ip_configuration.html["MetroCluster FC から MetroCluster IP 構成への無停止での移行（ ONTAP 9.8 以降）"]
 a| 
ONTAP 9.13.1



 a| 
8ノードMetroCluster FC構成からMetroCluster IP構成への無停止での移行
 a| 
既存の8ノードMetroCluster FC構成から新しいMetroCluster IP構成に、ワークロードとデータを無停止で移行できます。

https://docs.netapp.com/us-en/ontap-metrocluster/transition/concept_nondisruptively_transitioning_from_a_four_node_mcc_fc_to_a_mcc_ip_configuration.html["MetroCluster FC構成からMetroCluster IP構成への無停止での移行"]
 a| 
ONTAP 9.13.1



 a| 
スイッチオーバーとスイッチバックを使用した4ノードMetroCluster IP構成のアップグレード
 a| 
スイッチオーバーとスイッチバックを使用して、4ノードMetroCluster IP構成のコントローラをアップグレードできます。 `system controller replace` コマンド

https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_upgrade_controllers_system_control_commands_in_a_four_node_mcc_ip.html["4ノードMetroCluster IP構成でのコントローラのアップグレード"]
 a| 
ONTAP 9.13.1



 a| 
環境のシャットダウン時にメディエーターアシスト自動計画外スイッチオーバー（MAUSO）がトリガーされる
 a| 
環境のシャットダウンにより一方のサイトが正常にシャットダウンすると、MAUSOがトリガーされます。

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept-ontap-mediator-supports-automatic-unplanned-switchover.html["ONTAP メディエーターでの自動計画外スイッチオーバーのサポート"]
 a| 
ONTAP 9.13.1



 a| 
8ノードMetroCluster IP構成のサポート
 a| 
8ノードMetroCluster IP構成のコントローラとストレージをアップグレードするには、構成を拡張して一時的な12ノード構成にし、古いDRグループを削除します。

https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_refresh_4n_mcc_ip.html["4 ノード MetroCluster IP 構成を更新"]
 a| 
ONTAP 9.13.1



 a| 
MetroCluster IP構成から共有ストレージMetroClusterスイッチ構成への変換
 a| 
MetroCluster IP構成を共有ストレージMetroClusterスイッチ構成に変換できます。

https://docs.netapp.com/us-en/ontap-metrocluster/maintain/task_replace_an_ip_switch.html["IP スイッチを交換します"]
 a| 
ONTAP 9.13.1



 a| 
MetroCluster IP構成でのMetroCluster自動強制スイッチオーバー機能
 a| 
MetroClusterの自動強制スイッチオーバー機能は、MetroCluster IP構成で有効にすることができます。この機能は、Mediator-Assisted Unplanned Switchover（MAUSO；メディエーターアシスト計画外スイッチオーバー）機能の拡張です。

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept-risks-limitations-automatic-switchover.html["自動スイッチオーバーの制限事項"]
 a| 
ONTAP 9.12.1



 a| 
MetroCluster IP構成のミラーされていないアグリゲート上のSVM上のS3
 a| 
MetroCluster IP構成のミラーされていないアグリゲート上のSVMで、ONTAP Simple Storage Service（S3）オブジェクトストレージサーバを有効にすることができます。

https://docs.netapp.com/us-en/ontap/s3-config/ontap-version-support-s3-concept.html#s3-support-with-metrocluster["MetroClusterによるS3のサポート"^]
 a| 
ONTAP 9.12.1



 a| 
MetroCluster IPでのNVMeのサポート
 a| 
NVMe/FCプロトコルは、4ノードMetroCluster IP構成でサポートされます。

link:https://docs.netapp.com/us-en/ontap/san-admin/san-config-mcc-concept.html["MetroCluster 環境のSAN構成"^]
 a| 
ONTAP 9.12.1



 a| 
MetroCluster IPおよびMetroClusterファブリック接続構成でのフロントエンドホストプロトコルのIPSecサポート
 a| 
フロントエンドホストプロトコル（NFSやiSCSIなど）のIPSecサポートは、MetroCluster IPおよびMetroClusterファブリック接続構成で使用できます。

https://docs.netapp.com/us-en/ontap/networking/configure_ip_security_@ipsec@_over_wire_encryption.html["ワイヤ暗号化を介した IP セキュリティ（ IPsec ）を設定します"^]
 a| 
ONTAP 9.12.1



 a| 
MetroCluster FC構成からAFF A250またはFAS500f MetroCluster IP構成への移行
 a| 
MetroCluster FC構成からAFF A250またはFAS500f MetroCluster IP構成に移行できます。

https://docs.netapp.com/us-en/ontap-metrocluster/transition/task_move_cluster_connections.html#which-connections-to-move["ローカルクラスタ接続を移動します"]
 a| 
ONTAP 9.11.1



 a| 
整合グループ
 a| 
MetroCluster構成では整合グループがサポートされます。

https://docs.netapp.com/us-en/ontap/consistency-groups/index.html#multi-admin-verification-support-for-consistency-groups["MetroCluster構成の整合グループ"^]
 a| 
ONTAP 9.11.1



 a| 
MetroCluster FC構成でのノードのコントローラアップグレードの簡易化
 a| 
スイッチオーバーとスイッチバックを使用するアップグレードプロセスのアップグレード手順が簡易化されました。

https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_upgrade_controllers_in_a_four_node_fc_mcc_us_switchover_and_switchback_mcc_fc_4n_cu.html["スイッチオーバーとスイッチバックを使用して、 MetroCluster FC 構成のコントローラをアップグレードします"]
 a| 
ONTAP 9.10.1



 a| 
レイヤ3での共有リンクのIPサポート
 a| 
MetroCluster IP設定は、IPルーテッド（レイヤ3）バックエンド接続で実装できます。

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_considerations_layer_3.html["レイヤ 3 ワイドエリアネットワークに関する考慮事項"]
 a| 
ONTAP 9.9.1



 a| 
8ノードMetroCluster構成のサポート
 a| 
永続的な8ノードクラスタは、IPおよびファブリック接続MetroCluster構成でサポートされます。

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_install_and_cable_the_mcc_components.html["MetroCluster コンポーネントを設置してケーブルを配線します"]
 a| 
ONTAP 9.9.1

|===