---
permalink: maintain/concept_using_fibrebridge_7600n_bridges_in_mcc_configurations.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, support, fibrebridge, bridges, configurations 
summary: FibreBridge 7600N ブリッジは、 ONTAP 9.5 以降で、 FibreBridge 7500N / 6500N ブリッジを交換する場合、または MetroCluster 構成に新しいストレージを追加する場合にサポートされます。ゾーニング要件とブリッジの FC ポートの使用に関する制限事項は、 FibreBridge 7500N ブリッジと同じです。 
---
= MetroCluster 構成での FibreBridge 7600N ブリッジのサポート
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FibreBridge 7600N ブリッジは、 ONTAP 9.5 以降で、 FibreBridge 7500N / 6500N ブリッジを交換する場合、または MetroCluster 構成に新しいストレージを追加する場合にサポートされます。ゾーニング要件とブリッジの FC ポートの使用に関する制限事項は、 FibreBridge 7500N ブリッジと同じです。

https://mysupport.netapp.com/matrix["NetApp Interoperability Matrix Tool で確認できます"^]


NOTE: ONTAP 9.8 以降を実行している構成では、 FibreBridge 6500N ブリッジはサポートされません。

[cols="27,19,27,27"]
|===


| ユースケース | ゾーニングの変更が必要か | 制限事項 | 手順 


 a| 
1 つの FibreBridge 7500N ブリッジを 1 つの FibreBridge 7600N ブリッジに交換する
 a| 
いいえ
 a| 
FibreBridge 7600N ブリッジの設定は、 FibreBridge 7500N ブリッジとまったく同じにする必要があります。
 a| 
link:task_replace_a_sle_fc_to_sas_bridge.html#hot-swapping-a-fibrebridge-7500n-with-a-7600n-bridge["FibreBridge 7500N と 7600N ブリッジのホットスワップ"]



 a| 
1 つの FibreBridge 6500N ブリッジを 1 つの FibreBridge 7600N ブリッジに交換する
 a| 
いいえ
 a| 
FibreBridge 7600N ブリッジの設定は、 FibreBridge 6500N ブリッジとまったく同じにする必要があります。
 a| 
link:task_replace_a_sle_fc_to_sas_bridge.html#hot_swap_6500n["FibreBridge 6500N ブリッジと FibreBridge 7600N / 7500N ブリッジのホットスワップ"]



 a| 
新しい FibreBridge 7600N ブリッジペアを追加して、新しいストレージを追加します
 a| 
はい。

新しいブリッジの各 FC ポート用のストレージゾーンを追加する必要があります。
 a| 
FC スイッチファブリック（ファブリック接続 MetroCluster 構成）またはストレージコントローラ（ストレッチ MetroCluster 構成）に使用可能なポートが必要です。 FibreBridge 7500N / 7600N ブリッジペアは、それぞれ最大 4 つのスタックをサポートできます。
 a| 
link:task_fb_hot_add_stack_of_shelves_and_bridges.html["MetroCluster システムへの SAS ディスクシェルフとブリッジのスタックのホットアド"]

|===