---
permalink: maintain/concept_where_to_find_procedures_for_mcc_maintenance_tasks.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, find, procedures, maintenance, tasks 
summary: MetroCluster ハードウェアのメンテナンス作業を行うときは、必ず正しい手順を選択してください。 
---
= MetroClusterメンテナンスの詳細
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
MetroClusterのメンテナンスタスクを準備する方法と、構成に適したメンテナンス手順を選択する方法について説明します。



== メンテナンスタスクの準備

メンテナンス手順を実行する前に、の情報を確認してくださいlink:enable-console-logging-before-maintenance.html["MetroClusterのメンテナンスの準備"]。


NOTE: メンテナンスタスクを実行する前に、コンソールロギングを有効にし、ONTAPメディエーターまたはTiebreakerの監視を削除する必要があります。



== 各種のMetroCluster構成のメンテナンス手順

* MetroCluster IP設定を使用している場合は、の手順を確認してくださいlink:task-modify-ip-netmask-properties.html["MetroCluster IP構成のメンテナンス手順"]。
* MetroCluster FC構成の場合は、の手順を確認してくださいlink:task_modify_switch_or_bridge_ip_address_for_health_monitoring.html["MetroCluster FC構成のメンテナンス手順"]。
* 構成に対応するセクションに記載されている手順が見つからない場合は、の手順を確認してくださいlink:task_replace_a_shelf_nondisruptively_in_a_stretch_mcc_configuration.html["すべてのMetroCluster構成のメンテナンス手順"]。




== その他のすべてのメンテナンス手順

次の表に、上記の3つのセクションに記載されていないMetroClusterのメンテナンス手順へのリンクを示します。

|===


| コンポーネント | MetroCluster タイプ（ FC または IP ） | タスク | 手順 


 a| 
ONTAP ソフトウェア
 a| 
両方
 a| 
ONTAP ソフトウェアのアップグレード
 a| 
https://docs.netapp.com/us-en/ontap/upgrade/index.html["アップグレード、リバート、ダウングレード"^]



 a| 
コントローラモジュール
 a| 
両方
 a| 
FRU の交換（コントローラモジュール、 PCIe カード、 FC-VI カードなど）


NOTE: MetroCluster ストレージシステム間でのストレージコントローラモジュールまたは NVRAM カードの移動はサポートされていません。
 a| 
https://docs.netapp.com/platstor/index.jsp["ONTAPハードウェアシステムのドキュメント"^]



 a| 
アップグレードと拡張
 a| 
link:../upgrade/concept_choosing_an_upgrade_method_mcc.html["MetroCluster のアップグレードと拡張"]



 a| 
FC から IP への接続に移行します
 a| 
link:../transition/concept_choosing_your_transition_procedure_mcc_transition.html["MetroCluster FC から MetroCluster IP に移行します"]



 a| 
ドライブシェルフ
 a| 
FC
 a| 
その他すべてのシェルフのメンテナンス手順。標準の手順を使用できます。
 a| 
https://docs.netapp.com/platstor/topic/com.netapp.doc.hw-ds-sas3-service/home.html["DS460C 、 DS224C 、 DS212C ディスクシェルフを保守します"^]



 a| 
IP
 a| 
すべてのシェルフのメンテナンス手順。標準の手順を使用できます。

ミラーされていないアグリゲートのシェルフを追加する場合は、を参照してください http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-mcc-inst-cnfg-ip/GUID-EA385AF8-7786-4C3C-B5AE-1B4CFD3AD2EE.html["ミラーされていないアグリゲートを使用する場合の"^]
 a| 
https://docs.netapp.com/platstor/topic/com.netapp.doc.hw-ds-sas3-service/home.html["DS460C 、 DS224C 、 DS212C ディスクシェルフを保守します"^]

|===