---
permalink: maintain/concept_in_band_management_of_the_fc_to_sas_bridges.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, in, band, management, fc, sas, bridges 
summary: ONTAP 9.5 以降では、 FibreBridge 7500N / 7600N ブリッジについて、 IP 管理に代わる方法としてインバンド管理がサポートされます。ONTAP 9.8 以降では、アウトオブバンド管理は廃止されています。 
---
= FC-to-SAS ブリッジのインバンド管理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.5 以降では、 FibreBridge 7500N / 7600N ブリッジについて、 IP 管理に代わる方法としてインバンド管理がサポートされます。ONTAP 9.8 以降では、アウトオブバンド管理は廃止されています。

.このタスクについて

NOTE: ONTAP 9.8 以降では 'storage bridge コマンドは 'system bridge コマンドに置き換えられました次の手順は「 storage bridge 」コマンドを示していますが、 ONTAP 9.8 以降を実行している場合は「 system bridge 」コマンドが優先されます。

インバンド管理を使用すると、 ONTAP CLI からブリッジへの FC 接続を介してブリッジを管理および監視できます。ブリッジのイーサネットポートを介してブリッジに物理的にアクセスする必要がないため、ブリッジのセキュリティの脆弱性が軽減されます。

ブリッジのインバンド管理が可能かどうかは、 ONTAP のバージョンによって異なります。

* ONTAP 9.8 以降では、ブリッジはデフォルトでインバンド接続を介して管理され、 SNMP を介したブリッジのアウトオブバンド管理は廃止されています。
* ONTAP 9.5 から 9.7 ：インバンド管理またはアウトオブバンド管理のどちらかで SNMP 管理がサポートされます。
* ONTAP 9.5 よりも前のバージョンでは、アウトオブバンドの SNMP 管理のみがサポートされます。


ブリッジの CLI コマンドは、 ONTAP インターフェイスの ONTAP インターフェイス「 storage bridge run -cli-name_bridge-name_command_bridge-command-name_` コマンド」から実行できます。


NOTE: ブリッジの物理接続を制限することでセキュリティを向上させるために、 IP アクセスを無効にしたインバンド管理の使用を推奨します。

link:task_replace_a_sle_fc_to_sas_bridge.html#hot-swapping-a-bridge-with-a-replacement-bridge-of-the-same-model["同じモデルの交換用ブリッジとのホットスワップ"]

link:task_replace_a_sle_fc_to_sas_bridge.html#hot-swapping-a-fibrebridge-7500n-with-a-7600n-bridge["FibreBridge 7500N と 7600N ブリッジのホットスワップ"]

link:task_replace_a_sle_fc_to_sas_bridge.html#hot-swapping-a-fibrebridge-a-6500n-bridge-with-a-fibrebrdige-7600n-or-7500n-bridge["FibreBridge 6500N ブリッジと FibreBridge 7600N / 7500N ブリッジのホットスワップ"]

link:task_fb_hot_add_stack_of_shelves_and_bridges.html#hot-adding-a-stack-of-sas-disk-shelves-and-bridges["SAS ディスクシェルフとブリッジのスタックのホットアド"]



== ONTAP から FibreBridge ブリッジを管理します

ONTAP 9.5 以降では、 ONTAP CLI を使用して FibreBridge コマンドをブリッジに送信し、コマンドの結果を表示することができます。

.このタスクについて
--

NOTE: ONTAP 9.8 以降では 'storage bridge コマンドは 'system bridge コマンドに置き換えられました次の手順は「 storage bridge 」コマンドを示していますが、 ONTAP 9.8 以降を実行している場合は「 system bridge 」コマンドが優先されます。

--
.手順
. 「 storage bridge run -cli 」コマンドで該当する FibreBridge コマンドを実行します。
+
storage bridge run -cli-name_bridge-name_command_" コマンドテキスト "_`

+
次のコマンドは、 ONTAP プロンプトから FibreBridge 「 S ASPortDisable 」コマンドを実行して、ブリッジの SAS ポート b を無効にします。

+
[listing]
----
cluster_A::> storage bridge run-cli -name "SASPortDisable b"

SAS Port B has been disabled.
Ready
cluster_A::>
----

