---
permalink: maintain/reference_where_to_find_additional_information_mcc_service_guide.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, additional, information 
summary: MetroCluster 構成の設定、運用、監視の詳細については、ネットアップのドキュメントライブラリを参照してください。 
---
= 追加情報の参照先
:icons: font
:imagesdir: ../media/


[role="lead"]
MetroCluster 構成の設定、運用、監視の詳細を、ネットアップのドキュメントライブラリで確認できます。

|===


| ガイド | 内容 


 a| 
link:../index.html["MetroCluster のドキュメント"]
 a| 
* MetroCluster のすべてのガイド




 a| 
https://www.netapp.com/pdf.html?item=/media/13480-tr4705.pdf["NetApp MetroCluster 解決策のアーキテクチャと設計"]
 a| 
* MetroCluster の設定と運用の技術概要
* MetroCluster 構成のベストプラクティス




 a| 
https://docs.netapp.com/us-en/ontap-metrocluster/install-fc/index.html["ファブリック接続 MetroCluster のインストールと設定"]
 a| 
* ファブリック接続 MetroCluster アーキテクチャ
* 構成のケーブル接続
* FC-to-SAS ブリッジの設定
* FC スイッチを設定します
* ONTAP で MetroCluster を設定します




 a| 
https://docs.netapp.com/us-en/ontap-metrocluster/install-stretch/concept_considerations_differences.html["ストレッチ MetroCluster のインストールと設定"]
 a| 
* ストレッチ MetroCluster アーキテクチャ
* 構成のケーブル接続
* FC-to-SAS ブリッジの設定
* ONTAP で MetroCluster を設定します




 a| 
https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_considerations_differences.html["MetroCluster IP のインストールと設定"]
 a| 
* MetroCluster IP アーキテクチャ
* MetroCluster IP 構成のケーブル接続
* ONTAP で MetroCluster を設定します




 a| 
https://www.netapp.com/support-and-training/documentation/["ネットアップのマニュアル：製品ガイドとリソース"]
 a| 
* MetroCluster の設定とパフォーマンスを監視する




 a| 
https://docs.netapp.com/us-en/ontap-metrocluster/tiebreaker/concept_overview_of_the_tiebreaker_software.html["MetroCluster Tiebreaker ソフトウェアのインストールおよび設定"]
 a| 
* MetroCluster Tiebreaker ソフトウェアを使用して MetroCluster 構成を監視する




 a| 
https://docs.netapp.com/us-en/ontap-7mode-transition/copy-based/index.html["コピーベースの移行"]
 a| 
* 7-Mode ストレージシステムから clustered Data ONTAP ストレージシステムへデータを移行する


|===