---
permalink: maintain/reference_mcc_failure_scenarios.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, failure, recovery, scenarios 
summary: さまざまな障害の発生時に MetroCluster 構成でどのように対応できるかを把握しておく必要があります。 
---
= MetroCluster の障害とリカバリのシナリオ
:icons: font
:imagesdir: ../media/


[role="lead"]
さまざまな障害の発生時に MetroCluster 構成でどのように対応できるかを把握しておく必要があります。


NOTE: ノード障害からの追加情報のリカバリについては、の「正しいリカバリ手順の選択」を参照してください link:https://docs.netapp.com/us-en/ontap-metrocluster/disaster-recovery/index.html["『 MetroCluster 管理およびディザスタリカバリガイド』"]。

|===
| イベント | 影響 | リカバリ 


 a| 
単一ノード障害です
 a| 
フェイルオーバーがトリガーされます。
 a| 
ローカルのテイクオーバーによって構成がリカバリされます。RAID には影響はありません。システムメッセージを確認し、障害が発生した FRU を必要に応じて交換します。

https://docs.netapp.com/platstor/index.jsp["AFF と FAS ドキュメントセンター"]



 a| 
一方のサイトの 2 つのノードの障害
 a| 
MetroCluster Tiebreaker ソフトウェアで自動スイッチオーバーが有効になっている場合にのみ、 2 つのノードがスイッチオーバーされます。
 a| 
MetroCluster Tiebreaker ソフトウェアで自動スイッチオーバーが有効になっていない場合は、 USO を手動で実行します。

https://docs.netapp.com/platstor/index.jsp["AFF と FAS ドキュメントセンター"]



 a| 
MetroCluster IP interface -- 1 つのポートの障害
 a| 
システムがデグレード状態になっている。ポート障害がさらに発生すると HA ミラーリングに影響します。
 a| 
2 番目のポートが使用されます。ポートへの物理リンクが切断されると、ヘルスモニタによってアラートが生成されます。システムメッセージを確認し、障害が発生した FRU を必要に応じて交換します。

https://docs.netapp.com/platstor/index.jsp["AFF と FAS ドキュメントセンター"]



 a| 
MetroCluster IP interface -- 両方のポートの障害
 a| 
HA 機能に影響します。ノードの RAID SyncMirror の同期が停止します。
 a| 
HA テイクオーバーは行われないため、すぐに手動でリカバリする必要があります。システムメッセージを確認し、障害が発生した FRU を必要に応じて交換します。

https://docs.netapp.com/platstor/index.jsp["AFF と FAS ドキュメントセンター"]



 a| 
1 つの MetroCluster IP スイッチの障害
 a| 
影響はありません。冗長性は、 2 番目のネットワークを通じて提供されます。
 a| 
障害が発生したスイッチを必要に応じて交換します。

xref:task_replace_an_ip_switch.adoc[IP スイッチの交換]



 a| 
同じネットワーク内にある 2 つの MetroCluster IP スイッチの障害
 a| 
影響はありません。冗長性は、 2 番目のネットワークを通じて提供されます。
 a| 
障害が発生したスイッチを必要に応じて交換します。

xref:task_replace_an_ip_switch.adoc[IP スイッチの交換]



 a| 
1 つのサイトにある 2 つの MetroCluster IP スイッチの障害
 a| 
ノードの RAID SyncMirror の同期が停止します。HA 機能に影響し、クラスタがクォーラムのメンバーでなくなります。
 a| 
障害が発生したスイッチを必要に応じて交換します。

xref:task_replace_an_ip_switch.adoc[IP スイッチの交換]



 a| 
別々のサイトにありネットワークも異なる（対角の関係にある） 2 つの MetroCluster IP スイッチの障害
 a| 
ノードの RAID SyncMirror の同期が停止します。
 a| 
ノードの RAID SyncMirror の同期が停止します。クラスタおよび HA 機能には影響はありません。障害が発生したスイッチを必要に応じて交換します。

xref:task_replace_an_ip_switch.adoc[IP スイッチの交換]

|===