---
permalink: maintain/reference_requirements_for_using_other_interfaces_to_configure_and_manage_fibrebridge_bridges.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, requirements, interfaces, fibrebridge, bridges, manage, configures 
summary: シリアルポート、 Telnet 、および FTP を組み合わせて使用すると、推奨される管理インターフェイスの代わりに FibreBridge ブリッジを管理できます。ブリッジをインストールする前に、システムが適切なインターフェイスの要件を満たしている必要があります。 
---
= 他のインターフェイスを使用して FibreBridge ブリッジを設定および管理するための要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
シリアルポート、 Telnet 、および FTP を組み合わせて使用すると、推奨される管理インターフェイスの代わりに FibreBridge ブリッジを管理できます。ブリッジをインストールする前に、システムが適切なインターフェイスの要件を満たしている必要があります。

シリアルポートまたは Telnet を使用して、ブリッジとイーサネット管理 1 ポートを設定し、ブリッジを管理できます。FTP を使用して、ブリッジファームウェアを更新できます。


NOTE: 管理インターフェイスの詳細については、使用しているモデルブリッジに対応した ATTO FibreBridge Installation and Operation Manual を参照してください。

ATTO FibreBridge の説明ページにあるリンクを使用して、ATTO Web サイトからこのドキュメントにアクセスできます。



== シリアルポート

シリアルポートを使用してブリッジを設定および管理し、イーサネット管理 1 ポートを設定する場合は、システムが次の要件を満たしている必要があります。

* シリアルケーブル（ブリッジのシリアルポートからセットアップに使用するコンピュータのシリアル（ COM ）ポートに接続）
+
ブリッジのシリアルポートは RJ-45 で、ピン配列はコントローラと同じです。

* Hyperterminal 、 TeraTerm 、 PuTTY などの端末エミュレーションプログラム。コンソールにアクセスします
+
ターミナルプログラムは、画面出力をファイルに記録できる必要があります。





== Telnet

Telnet を使用してブリッジを設定および管理する場合は、システムが次の要件を満たしている必要があります。

* シリアルケーブル（ブリッジのシリアルポートからセットアップに使用するコンピュータのシリアル（ COM ）ポートに接続）
+
ブリッジのシリアルポートは RJ-45 で、ピン配列はコントローラと同じです。

* （推奨）デフォルト以外のユーザ名とパスワード（ブリッジへのアクセス用）
* Hyperterminal 、 TeraTerm 、 PuTTY などの端末エミュレーションプログラム。コンソールにアクセスします
+
ターミナルプログラムは、画面出力をファイルに記録できる必要があります。

* 各ブリッジのイーサネット管理 1 ポートの IP アドレス、サブネットマスク、およびゲートウェイ情報




== FTP

FTP を使用してブリッジファームウェアを更新する場合は、システムが次の要件を満たしている必要があります。

* 標準イーサネットケーブル（ブリッジのイーサネット管理 1 ポートからネットワークへの接続用）
* （推奨）デフォルト以外のユーザ名とパスワード（ブリッジへのアクセス用）

