---
permalink: maintain/task_fb_hot_add_a_disk_shelf_install_7500n.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, hot, add, disk, shelf 
summary: パフォーマンスを低下させることなくストレージを拡張するには、ディスクシェルフをホットアドします。 
---
= ディスクシェルフのホットアド
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
パフォーマンスを低下させることなくストレージを拡張するには、ディスクシェルフをホットアドします。

* に記載されたすべての要件をシステムが満たしている必要があります link:task_fb_hot_add_shelf_prepare_7500n.html["SAS ディスクシェルフのホットアドの準備"]。
* シェルフをホットアドするには、次のいずれかのシナリオを満たす環境が必要です。
+
** SAS ディスクシェルフのスタックに FibreBridge 7500N ブリッジが 2 つ接続されている。
** SASディスクシェルフのスタックにFibreBridge 7600Nブリッジが2つ接続されている。
** SASディスクシェルフのスタックにFibreBridge 7500NブリッジとFibreBridge 7600Nブリッジが1つずつ接続されている。


* この手順は、スタック内の最後のディスクシェルフにディスクシェルフをホットアドするためのものです。
+
この手順は、スタック内の最後のディスクシェルフが IOM A からブリッジ A に、 IOM B からブリッジ B に接続されていることを前提としています

* これは無停止の手順です。
* 各サイトで同数のディスクシェルフをホットアドする必要があります。
* 複数のディスクシェルフをホットアドする場合は、ディスクシェルフを 1 つずつホットアドする必要があります。
+

NOTE: FibreBridge 7500N または 7600N ブリッジペアは、それぞれ最大 4 個のスタックをサポートできます。




IMPORTANT: ディスクシェルフをホットアドするには、 advanced モードで「 storage disk firmware update 」コマンドを実行して、ホットアドするディスクシェルフのディスクドライブファームウェアを更新する必要があります。システム内の既存のディスクドライブのファームウェアのバージョンが古い場合は、このコマンドを実行するとシステムが停止する可能性があります。


IMPORTANT: SAS ケーブルを間違ったポートに挿入した場合は、ケーブルを SAS ポートから取り外すときに、 120 秒以上待機してから別の SAS ポートに接続する必要があります。そうしないと、ケーブルが別のポートに移されたことがシステムで認識されません。

.手順
. 自身の適切な接地対策を行います
. いずれかのコントローラのシステムコンソールからディスクシェルフの接続を確認します。
+
「 *sysconfig -v 」を使用します

+
次のような出力が表示されます。

+
** 各 FC ポートの下に、認識されているブリッジがそれぞれ別々の行に表示されます。たとえば、一連の FibreBridge 7500N ブリッジにディスクシェルフをホットアドした場合、出力は次のようになります。
+
[listing]
----
FC-to-SAS Bridge:
cisco_A_1-1:9.126L0: ATTO  FibreBridge7500N 2.10  FB7500N100189
cisco_A_1-2:1.126L0: ATTO  FibreBridge7500N 2.10  FB7500N100162
----
** 各 FC ポートの下に、認識されているディスクシェルフがそれぞれ別々の行に表示されます。
+
[listing]
----
Shelf   0: IOM6  Firmware rev. IOM6 A: 0173 IOM6 B: 0173
Shelf   1: IOM6  Firmware rev. IOM6 A: 0173 IOM6 B: 0173
----
** 各 FC ポートの下に、認識されているディスクドライブがそれぞれ別々の行に表示されます。
+
[listing]
----
cisco_A_1-1:9.126L1   : NETAPP   X421_HCOBD450A10 NA01 418.0GB (879097968 520B/sect)
cisco_A_1-1:9.126L2   : NETAPP   X421_HCOBD450A10 NA01 418.0GB (879097968 520B/sect)
----


. いずれかのコントローラのコンソールで、システムのディスクの自動割り当てが有効になっているかどうかを確認します。
+
「 * storage disk option show * 」を入力します

+
自動割り当てポリシーは Auto Assign 列に表示されます。

+
[listing]
----

Node        BKg. FW. Upd.  Auto Copy   Auto Assign  Auto Assign Policy
----------  -------------  ----------  -----------  ------------------
node_A_1             on           on           on           default
node_A_2             on           on           on           default
2 entries were displayed.
----
. システムでディスクの自動割り当てが有効になっていない場合や、同じスタック内のディスクドライブを両方のコントローラが所有している場合は、ディスクドライブを適切なプールに割り当てます。
+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-psmg/home.html["ディスクおよびアグリゲートの管理"]

+
[NOTE]
====
ディスクシェルフの 1 つのスタックを 2 つのコントローラに分割する場合は、ディスク所有権を割り当てる前にディスクの自動割り当てを無効にする必要があります。そうしないと、 1 本のディスクドライブを割り当てたときに、残りのディスクドライブが同じコントローラおよびプールに自動的に割り当てられる場合があります。

「 storage disk option modify -node node_name -autoassign off 」コマンドは、ディスクの自動割り当てを無効にします。

====
+

NOTE: ディスクドライブとディスクシェルフファームウェアが更新されるまで、アグリゲートまたはボリュームにディスクドライブを追加しないでください。

. ダウンロードしたファームウェアの手順に従って、ディスクシェルフファームウェアを最新バージョンに更新します。
+
手順のコマンドは、どちらのコントローラのシステムコンソールでも実行できます。

+
https://mysupport.netapp.com/site/downloads/firmware/disk-shelf-firmware["ネットアップのダウンロード：ディスクシェルフファームウェア"]

. ディスクシェルフを設置してケーブル接続します。
+

NOTE: コネクタをポートに無理に押し込まないでください。Mini-SAS ケーブルは、誤挿入を防ぐキーイングが施されているため、正しい向きで SAS ポートに取り付けるとカチッとはまり、ディスクシェルフの SAS ポートの LNK LED が緑色に点灯します。ディスクシェルフの場合、プルタブを上（コネクタの上側）にして SAS ケーブルコネクタを挿入します。

+
.. ディスクシェルフを設置して電源をオンにし、シェルフ ID を設定します。
+
ディスクシェルフの設置の詳細については、使用しているディスクシェルフモデルの『 Installation Guide 』を参照してください。

+

NOTE: ディスクシェルフの電源を再投入し、各 SAS ディスクシェルフのシェルフ ID をストレージシステム全体で一意にする必要があります。

.. スタック内の最後のシェルフの IOM B ポートから SAS ケーブルを外し、新しいシェルフの同じポートに再接続します。
+
このケーブルのもう一方の端は、ブリッジ B に接続されたままです

.. 新しいディスクシェルフをデイジーチェーン接続します。そのためには、新しいシェルフの（ IOM A と IOM B の） IOM ポートを最後のシェルフの（ IOM A と IOM B の） IOM ポートにケーブル接続します。


+
ディスクシェルフのデイジーチェーン接続の詳細については、使用しているディスクシェルフモデルの Installation Guide を参照してください。

. システムコンソールからディスクドライブファームウェアを最新バージョンに更新します。
+
https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware["ネットアップのダウンロード：ディスクドライブファームウェア"]

+
.. advanced 権限レベルに切り替えます。 +`*set -privilege advanced *`
+
advanced モードで続けるかどうかを尋ねられたら、「 * y * 」と入力して応答する必要があります。 advanced モードのプロンプトが表示されます（ * > ）。

.. システム・コンソールからディスク・ドライブ・ファームウェアを最新バージョンに更新します： +`* storage disk firmware update *`
.. admin 特権レベルに戻ります :+`*set -privilege admin*`
.. もう一方のコントローラで上記の手順を繰り返します。


. ONTAP で MetroCluster 構成の動作を確認します。
+
.. システムがマルチパスかどうかを確認します。
+
'*node run -node node_name sysconfig -a *

.. 両方のクラスタにヘルス・アラートがないかどうかを確認します +`* system health alert show *`
.. MetroCluster 構成と動作モードが正常であることを確認します :+`* MetroCluster show*`
.. MetroCluster チェック :+`* MetroCluster check run*` を実行します
.. MetroCluster チェックの結果を表示します。
+
「 * MetroCluster check show * 」と表示されます

.. スイッチにヘルスアラートがないかどうかを確認します（ある場合）。
+
「 * storage switch show * 」と表示されます

.. Config Advisor を実行します。
+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["ネットアップのダウンロード： Config Advisor"]

.. Config Advisor の実行後、ツールの出力を確認し、推奨される方法で検出された問題に対処します。


. 複数のディスクシェルフをホットアドする場合は、ホットアドするディスクシェルフごとに前述の手順を繰り返します。

