---
permalink: maintain/task_update_firmware_on_a_fibrebridge_bridge_parent_topic.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, update, firmware, fibrebridge, bridge, update, configuration 
summary: ブリッジファームウェアを更新するための手順は、ブリッジモデルと ONTAP のバージョンによって異なります。 
---
= FibreBridge ブリッジのファームウェアを更新しています
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ブリッジファームウェアを更新するための手順は、ブリッジモデルと ONTAP のバージョンによって異なります。



== ONTAP 9.4 以降を実行している構成での FibreBridge 7600N / 7500N ブリッジのファームウェアの更新

FibreBridge ブリッジのファームウェアを更新して、最新の機能を実装したり、潜在的な問題を解決したりすることが必要になる場合があります。この手順は、 ONTAP 9.4 以降を実行している構成の FibreBridge 7600N / 7500N ブリッジに使用します。

* MetroCluster 構成が正常に動作している必要があります。
* MetroCluster 構成内のすべての FibreBridge ブリッジが稼働している必要があります。
* すべてのストレージパスが使用可能である必要があります。
* 管理者パスワードと、HTTP、FTP、SFTP、またはTrivial File Transfer Protocol（TFTP）サーバへのアクセスが必要です。
* サポートされているファームウェアバージョンを使用している必要があります。
+
https://mysupport.netapp.com/matrix["NetApp Interoperability Matrix Tool で確認できます"^]

+
IMT では、 Storage 解決策フィールドを使用して MetroCluster 解決策を選択できます。検索を絞り込むには、 * 構成部品エクスプローラ * を使用して構成部品と ONTAP バージョンを選択します。[ 結果の表示（ Show Results ） ] をクリックすると、条件に一致するサポートされている構成のリストを表示できます。

* このタスクは、 ONTAP 9.4 以降を実行している構成の FibreBridge 7600N / 7500N ブリッジでのみ使用できます。
* このタスクは、 MetroCluster 構成内の各 FibreBridge ブリッジで実行し、すべてのブリッジで同じファームウェアバージョンが実行されるようにする必要があります。



NOTE: これはシステムの停止を伴わない手順であり、完了までに約 30 分かかります。


NOTE: ONTAP 9.8 以降では 'storage bridge コマンドは 'system bridge コマンドに置き換えられました次の手順は「 storage bridge 」コマンドを示していますが、 ONTAP 9.8 以降を実行している場合は「 system bridge 」コマンドが優先されます。

.手順
. メンテナンスの開始を通知する AutoSupport メッセージを起動します。
+
'system node AutoSupport invoke -node * -type all -message MAINT=_maintenance-window-in-hours_`

+
「 maintenance-window-in-hours 」には、メンテナンス・ウィンドウの長さを 72 時間まで指定します。この時間が経過する前にメンテナンスが完了した場合は、メンテナンス期間が終了したことを通知する AutoSupport メッセージを起動できます。

+
「 system node AutoSupport invoke -node * -type all -message MAINT= end 」というメッセージが表示されます

. ATTO FibreBridge のページに移動し、ブリッジに適したファームウェアを選択します。
+
https://mysupport.netapp.com/site/products/all/details/atto-fibrebridge/downloads-tab["ATTO FibreBridge ファームウェアのダウンロードページ"^]

. 「注意 / 必ずお読みください」と「エンドユーザ契約」を確認し、チェックボックスをクリックして同意してください。
. コントローラモジュールからアクセス可能なネットワーク上の場所にファームウェアファイルを配置します。
+
以降の手順のコマンドは、どちらのコントローラモジュールのコンソールでも入力できます。

. advanced 権限レベルに切り替えます。
+
「 advanced 」の権限が必要です

+
advanced モードで続行するかどうかを尋ねられたら、「 y 」と入力して応答する必要があります。 advanced モードのプロンプトが表示されます（ * > ）。

. ブリッジファームウェアを更新します。
+
storage bridge firmware update -bridge name -uri_url-of-firmware-pACKUE_`

+
[listing]
----
cluster_A> storage bridge firmware update -bridge bridge_A_1a -uri http://192.168.132.97/firmware.ZBD
----
. admin 権限レベルに戻ります。
+
「特権管理者」

. ファームウェアのアップグレードが完了したことを確認します。
+
「 job show -name 」 _job-name_"" 」を参照してください

+
次の例は ' ジョブ storage bridge firmware update ` がまだ実行中であることを示しています

+
[listing]
----
cluster_A> job show -name "storage bridge firmware update"
Owning

Job ID Name                 Vserver    Node           State
------ -------------------- ---------- -------------- ----------
2246   job-name
                            cluster_A
                                       node_A_1
                                                      Running
Description: Storage bridge firmware update job
----
+
約 10 分後に新しいファームウェアが完全にインストールされ、ジョブの状態は「 Success 」になります。

+
[listing]
----
cluster_A> job show -name "storage bridge firmware update"

                            Owning
Job ID Name                 Vserver    Node           State
------ -------------------- ---------- -------------- ----------
2246   Storage bridge firmware update
                            cluster_A
                                       node_A_1
                                                      Success
Description: Storage bridge firmware update job
----
. インバンド管理が有効になっているかどうか、およびシステムで実行されている ONTAP のバージョンに応じて、次の手順を実行します。
+
** ONTAP 9.4 を実行している場合はインバンド管理がサポートされないため、ブリッジコンソールからコマンドを実行する必要があります。
+
... ブリッジのコンソールで「 flashimages 」コマンドを実行し、正しいファームウェアバージョンが表示されることを確認します。
+

NOTE: 次の例では、プライマリフラッシュイメージに新しいファームウェアイメージが表示され、セカンダリフラッシュイメージに古いイメージが表示されています。





+
[listing]
----
flashimages

 ;Type Version
;=====================================================
Primary 3.16 001H
Secondary 3.15 002S
Ready.
----
+
.. ブリッジから「 firmwareerestart 」コマンドを実行して、ブリッジを再起動します。
+
*** ONTAP 9.5 以降を実行している場合はインバンド管理がサポートされるため、クラスタプロンプトからコマンドを実行できます。


.. storage bridge run-cli-name_bridge-name_command FlashImages' コマンドを実行します
+

NOTE: 次の例では、プライマリフラッシュイメージに新しいファームウェアイメージが表示され、セカンダリフラッシュイメージに古いイメージが表示されています。

+
[listing]
----
cluster_A> storage bridge run-cli -name ATTO_7500N_IB_1 -command FlashImages

[Job 2257]

;Type         Version
;=====================================================
Primary 3.16 001H
Secondary 3.15 002S
Ready.


[Job 2257] Job succeeded.
----
.. 必要に応じて、ブリッジを再起動します。
+
「 storage bridge run -cli -name ATTO_7500N _IB_1 - Command FirmwareRestart 」を参照してください

+

NOTE: ATTO ファームウェアバージョン 2.95 以降ではブリッジが自動的に再起動するため、この手順は不要です。



. ブリッジが正常に再起動したことを確認します。
+
「 sysconfig 」を使用できます

+
システムは、マルチパスハイアベイラビリティ（両方のコントローラがブリッジ経由で各スタックのディスクシェルフにアクセス可能）用にケーブル接続されている必要があります。

+
[listing]
----
cluster_A> node run -node cluster_A-01 -command sysconfig
NetApp Release 9.6P8: Sat May 23 16:20:55 EDT 2020
System ID: 1234567890 (cluster_A-01); partner ID: 0123456789 (cluster_A-02)
System Serial Number: 200012345678 (cluster_A-01)
System Rev: A4
System Storage Configuration: Quad-Path HA
----
. FibreBridge ファームウェアが更新されたことを確認します。
+
storage bridge show -fields fw-version 、 symbolic -name

+
[listing]
----
cluster_A> storage bridge show -fields fw-version,symbolic-name
name fw-version symbolic-name
----------------- ----------------- -------------
ATTO_20000010affeaffe 3.10 A06X bridge_A_1a
ATTO_20000010affeffae 3.10 A06X bridge_A_1b
ATTO_20000010affeafff 3.10 A06X bridge_A_2a
ATTO_20000010affeaffa 3.10 A06X bridge_A_2b
4 entries were displayed.
----
. ブリッジのプロンプトからパーティションが更新されたことを確認します。
+
「 flashimages 」と入力します

+
プライマリフラッシュイメージに新しいファームウェアイメージが表示され、セカンダリフラッシュイメージに古いイメージが表示されます。

+
[listing]
----
Ready.
flashimages

;Type         Version
;=====================================================
   Primary    3.16 001H
 Secondary    3.15 002S

 Ready.
----
. 手順 5 ～ 10 を繰り返して、両方のフラッシュイメージが同じバージョンに更新されることを確認します。
. 両方のフラッシュイメージが同じバージョンに更新されていることを確認します。
+
「 flashimages 」と入力します

+
出力には、両方のパーティションで同じバージョンが表示されます。

+
[listing]
----
Ready.
flashimages

;Type         Version
;=====================================================
   Primary    3.16 001H
 Secondary    3.16 001H

 Ready.
----
. 次のブリッジでも手順 5 から 13 を繰り返し、 MetroCluster 構成内のすべてのブリッジを更新します。




== ONTAP 9.3.x 以前を実行している構成での FibreBridge 7500N / 6500N ブリッジのファームウェアの更新

FibreBridge ブリッジのファームウェアを更新して、最新の機能を実装したり、潜在的な問題を解決したりすることが必要になる場合があります。この手順は、 ONTAP 9.3.x を実行している構成の FibreBridge 7500N 、またはサポート対象のすべてのバージョンの ONTAP の FibreBridge 6500N ブリッジに使用します。

.作業を開始する前に
* MetroCluster 構成が正常に動作している必要があります。
* MetroCluster 構成内のすべての FibreBridge ブリッジが稼働している必要があります。
* すべてのストレージパスが使用可能である必要があります。
* 管理パスワードと FTP サーバまたは SCP サーバへのアクセスが必要です。
* サポートされているファームウェアバージョンを使用している必要があります。
+
https://mysupport.netapp.com/matrix["NetApp Interoperability Matrix Tool で確認できます"^]

+
IMT では、 Storage 解決策フィールドを使用して MetroCluster 解決策を選択できます。検索を絞り込むには、 * 構成部品エクスプローラ * を使用して構成部品と ONTAP バージョンを選択します。[ 結果の表示（ Show Results ） ] をクリックすると、条件に一致するサポートされている構成のリストを表示できます。



このタスクは、 FibreBridge 7500N または 6500N ブリッジで使用できます。ONTAP 9.3 以降では、 ONTAP storage bridge firmware update コマンドを使用して、 FibreBridge 7500N ブリッジのブリッジファームウェアを更新できます。

link:task_update_firmware_on_a_fibrebridge_bridge_parent_topic.html["ONTAP 9.4 以降を実行している構成での FibreBridge 7600N / 7500N ブリッジのファームウェアの更新"]

このタスクは、 MetroCluster 構成内の各 FibreBridge ブリッジで実行し、すべてのブリッジで同じファームウェアバージョンが実行されるようにする必要があります。


NOTE: これはシステムの停止を伴わない手順であり、完了までに約 30 分かかります。

.手順
. メンテナンスの開始を通知する AutoSupport メッセージを起動します。
+
'system node AutoSupport invoke -node * -type all -message MAINT=_maintenance-window-in-hours_`

+
"`_maintenance-window-in-hours_`" には、メンテナンス時間の長さを最大 72 時間指定します。この時間が経過する前にメンテナンスが完了した場合は、メンテナンス期間が終了したことを通知する AutoSupport メッセージを起動できます。

+
「 system node AutoSupport invoke -node * -type all -message MAINT= end 」というメッセージが表示されます

. ATTO FibreBridge のページに移動し、ブリッジに適したファームウェアを選択します。
+
https://mysupport.netapp.com/site/products/all/details/atto-fibrebridge/downloads-tab["ATTO FibreBridge ファームウェアのダウンロードページ"^]

. 「注意 / 必ずお読みください」と「エンドユーザ契約」を確認し、チェックボックスをクリックして同意してください。
. ATTO FibreBridge Firmware Download ページで、手順の手順 1~3 を実行してブリッジファームウェアファイルをダウンロードします。
. 各ブリッジでファームウェアを更新するように指示された場合は、 ATTO FibreBridge Firmware のダウンロードページとリリースノートのコピーを作成して参照します。
. ブリッジを更新します。
+
.. FibreBridge ブリッジにファームウェアをインストールします。
+
*** ATTO FibreBridge 7500N ブリッジを使用している場合は、 _ATTO FibreBridge 7500N Installation and Operation Manual _ の「 Update Firmware 」セクションに記載されている手順を参照してください。
*** ATTO FibreBridge 6500N ブリッジを使用している場合は、 _ATTO FibreBridge 6500N Installation and Operation Manual _ の「 Update Firmware 」セクションに記載されている手順を参照してください。
+
* 注意： * ここで個々のブリッジの電源を再投入してください。スタックの両方のブリッジの電源を同時に投入すると、コントローラがドライブにアクセスできなくなり、プレックスや複数のディスクで障害が発生する可能性があります。

+
ブリッジが再起動します。



.. いずれかのコントローラのコンソールで、ブリッジが正常に再起動したことを確認します。
+
「 sysconfig 」を使用できます

+
システムは、マルチパスハイアベイラビリティ（両方のコントローラがブリッジ経由で各スタックのディスクシェルフにアクセス可能）用にケーブル接続されている必要があります。

+
[listing]
----
cluster_A::> node run -node cluster_A-01 -command sysconfig
NetApp Release 9.1P7: Sun Aug 13 22:33:49 PDT 2017
System ID: 1234567890 (cluster_A-01); partner ID: 0123456789 (cluster_A-02)
System Serial Number: 200012345678 (cluster_A-01)
System Rev: A4
System Storage Configuration: Quad-Path HA
----
.. いずれかのコントローラのコンソールで、 FibreBridge ファームウェアが更新されていることを確認します。
+
storage bridge show -fields fw-version 、 symbolic -name

+
[listing]
----
cluster_A::> storage bridge show -fields fw-version,symbolic-name
 name              fw-version        symbolic-name
 ----------------- ----------------- -------------
 ATTO_10.0.0.1     1.63 071C 51.01   bridge_A_1a
 ATTO_10.0.0.2     1.63 071C 51.01   bridge_A_1b
 ATTO_10.0.1.1     1.63 071C 51.01   bridge_B_1a
 ATTO_10.0.1.2     1.63 071C 51.01   bridge_B_1b
 4 entries were displayed.
----
.. 同じブリッジで上記の手順を繰り返して、 2 つ目のパーティションを更新します。
.. 両方のパーティションが更新されたことを確認します。
+
「 flashimages 」と入力します

+
出力には、両方のパーティションで同じバージョンが表示されます。

+
[listing]
----
Ready.
flashimages
4
;Type         Version
;=====================================================
Primary    2.80 003T
Secondary    2.80 003T
Ready.
----


. 次のブリッジでも同じ手順を実行し、 MetroCluster 構成内のすべてのブリッジを更新します。

