---
permalink: maintain/task_hot_add_a_stack_to_exist_7500n_pair.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, hot, add, stack, sas, disk, shelves, existing, pair, fibrebridge, bridge 
summary: 使用可能なポートがある既存の FibreBridge 7500N ブリッジペアに SAS ディスクシェルフのスタックをホットアドできます。 
---
= 既存の FibreBridge 7500N ブリッジペアに SAS ディスクシェルフのスタックをホットアドする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用可能なポートがある既存の FibreBridge 7500N ブリッジペアに SAS ディスクシェルフのスタックをホットアドできます。

.作業を開始する前に
* 最新のディスクファームウェアとディスクシェルフファームウェアをダウンロードしておく必要があります。
* MetroCluster 構成内（既存のシェルフ）のすべてのディスクシェルフで同じファームウェアバージョンを実行する必要があります。1 つ以上のディスクまたはシェルフが最新のファームウェアバージョンを実行していない場合は、新しいディスクまたはシェルフを接続する前にファームウェアを更新します。
+
https://["ネットアップのダウンロード：ディスクドライブファームウェア"^]

+
https://["ネットアップのダウンロード：ディスクシェルフファームウェア"^]

* FibreBridge 7500N ブリッジが接続されており、使用可能な SAS ポートがある必要があります。


.このタスクについて
この手順は、推奨されるブリッジ管理インターフェイスである ATTO ExpressNAV GUI と ATTO QuickNAV ユーティリティを使用していることを前提としています。

ATTO ExpressNAV GUI は、ブリッジの設定および管理、ブリッジファームウェアの更新に使用できます。ATTO QuickNAV ユーティリティは、ブリッジのイーサネット管理 1 ポートの設定に使用できます。

必要に応じて、他の管理インターフェイスを使用できます。オプションには、シリアルポートまたは Telnet を使用したブリッジの設定と管理、イーサネット管理 1 ポートの設定、および FTP を使用したブリッジファームウェアの更新があります。これらの管理インターフェイスのいずれかを選択した場合は、に記載された該当する要件を満たす必要があります link:reference_requirements_for_using_other_interfaces_to_configure_and_manage_fibrebridge_bridges.html["その他のブリッジ管理インターフェイス"]。


IMPORTANT: SAS ケーブルを間違ったポートに挿入した場合は、ケーブルを SAS ポートから取り外すときに、 120 秒以上待機してから別の SAS ポートに接続する必要があります。そうしないと、ケーブルが別のポートに移されたことがシステムで認識されません。

.手順
. 自身の適切な接地対策を行います
. いずれかのコントローラのコンソールで、システムでディスクの自動割り当てが有効になっていることを確認します。
+
「 storage disk option show 」をクリックします

+
Auto Assign 列には、ディスクの自動割り当てが有効になっているかどうかが示されます。

+
[listing]
----

Node        BKg. FW. Upd.  Auto Copy   Auto Assign  Auto Assign Policy
----------  -------------  ----------  -----------  ------------------
node_A_1             on           on           on           default
node_A_2             on           on           on           default
2 entries were displayed.
----
. 新しいスタックのスイッチポートを無効にします。
. 各ブリッジの FibreBridge ファームウェアを更新します。
+
新しいブリッジのタイプがパートナーブリッジと同じ場合は、パートナーブリッジと同じファームウェアにアップグレードします。新しいブリッジのタイプがパートナーブリッジと異なる場合は、ブリッジと ONTAP のバージョンでサポートされている最新のファームウェアにアップグレードします。MetroCluster メンテナンスガイドの「 FibreBridge ブリッジのファームウェアの更新」のセクションを参照してください。

. ペアの各ブリッジで、新しいスタックに接続する SAS ポートを有効にします。
+
'SASortEnable_portlet-letter_

+
両方のブリッジで同じ SAS ポート（ B 、 C 、または D ）を使用する必要があります。

. 設定を保存し、各ブリッジをリブートします。
+
SaveConfiguration Restart を実行します

. ディスクシェルフをブリッジにケーブル接続します。
+
.. 各スタックのディスクシェルフをデイジーチェーン接続します。
+
ディスクシェルフのデイジーチェーン接続の詳細については、使用しているディスクシェルフモデルの Installation and Service Guide を参照してください。

.. ディスクシェルフの各スタックで、最初のシェルフの IOM A を FibreBridge A の SAS ポート A にケーブル接続し、最後のシェルフの IOM B を FibreBridge B の SAS ポート A にケーブル接続します
+
link:../install-fc/index.html["ファブリック接続 MetroCluster のインストールと設定"]

+
link:../install-stretch/concept_considerations_differences.html["ストレッチ MetroCluster のインストールと設定"]

+
各ブリッジには、ディスクシェルフのスタックへのパスが 1 つあります。ブリッジ A は最初のシェルフ経由でスタックの A 側に接続し、ブリッジ B は最後のシェルフ経由でスタックの B 側に接続します。

+

NOTE: ブリッジの SAS ポート B は無効になっています。



. 各ブリッジが、ブリッジの接続先のすべてのディスクドライブとディスクシェルフを検出できることを確認します。
+
[cols="30,70"]
|===


| 使用する手段 | 作業 


 a| 
ATTO ExpressNAV の GUI
 a| 
.. サポートされている Web ブラウザで、ブリッジの IP アドレスをブラウザのアドレスバーに入力します。
+
ATTO FibreBridge のホームページに移動し、リンクが表示されます。

.. リンクをクリックし、ブリッジを設定するときに指定したユーザ名とパスワードを入力します。
+
ATTO FibreBridge のステータスページが開き、左側にメニューが表示されます。

.. メニューの「 * 詳細設定 * 」をクリックします。
.. 接続されているデバイスを表示します。
+
「 astargets 」

.. [Submit （送信） ] をクリックします。




 a| 
シリアルポート接続
 a| 
接続されているデバイスを表示します。

「 astargets 」

|===
+
出力には、ブリッジが接続されているデバイス（ディスクおよびディスクシェルフ）が表示されます。出力行には行番号が振られているため、デバイスの台数を簡単に把握できます。

+

NOTE: 出力の先頭に「 response truncated 」というテキストが表示される場合は、 Telnet を使用してブリッジに接続し、「 sastargets 」コマンドを使用してすべての出力を表示できます。

+
次の出力は、 10 本のディスクが接続されていることを示します。

+
[listing]
----
Tgt VendorID ProductID        Type        SerialNumber
  0 NETAPP   X410_S15K6288A15 DISK        3QP1CLE300009940UHJV
  1 NETAPP   X410_S15K6288A15 DISK        3QP1ELF600009940V1BV
  2 NETAPP   X410_S15K6288A15 DISK        3QP1G3EW00009940U2M0
  3 NETAPP   X410_S15K6288A15 DISK        3QP1EWMP00009940U1X5
  4 NETAPP   X410_S15K6288A15 DISK        3QP1FZLE00009940G8YU
  5 NETAPP   X410_S15K6288A15 DISK        3QP1FZLF00009940TZKZ
  6 NETAPP   X410_S15K6288A15 DISK        3QP1CEB400009939MGXL
  7 NETAPP   X410_S15K6288A15 DISK        3QP1G7A900009939FNTT
  8 NETAPP   X410_S15K6288A15 DISK        3QP1FY0T00009940G8PA
  9 NETAPP   X410_S15K6288A15 DISK        3QP1FXW600009940VERQ
----
. コマンド出力で、スタック内の該当するすべてのディスクおよびディスクシェルフにブリッジが接続されていることを確認します。
+
[cols="30,70"]
|===


| 出力結果 | 作業 


 a| 
正解です
 a| 
残りの各ブリッジについて、同じ手順を繰り返します。



 a| 
不正解です
 a| 
.. SAS ケーブルに緩みがないか確認するか、手順を繰り返してディスクシェルフをブリッジに接続し、 SAS ケーブル接続を修正します。
.. 残りの各ブリッジについて、同じ手順を繰り返します。


|===
. システムコンソールからディスクドライブファームウェアを最新バージョンに更新します。
+
「 disk_fw_update 」

+
このコマンドは両方のコントローラで実行する必要があります。

+
https://["ネットアップのダウンロード：ディスクドライブファームウェア"^]

. ダウンロードしたファームウェアの手順に従って、ディスクシェルフファームウェアを最新バージョンに更新します。
+
手順のコマンドは、どちらのコントローラのシステムコンソールでも実行できます。

+
https://["ネットアップのダウンロード：ディスクシェルフファームウェア"^]

. システムでディスクの自動割り当てが有効になっていない場合は、ディスクドライブの所有権を割り当てます。
+
https://["ディスクおよびアグリゲートの管理"^]

+

NOTE: ディスクシェルフの 1 つのスタックの所有権を複数のコントローラに分割する場合は、ディスク所有権を割り当てる前にディスクの自動割り当てを無効にする必要があります（クラスタ内の両方のノードから「 storage disk option modify -autoassign off * 」）。 そうしないと、いずれかのディスクドライブを割り当てたときに、残りのディスクドライブが同じコントローラおよびプールに自動的に割り当てられる可能性があります。

+

NOTE: ディスクドライブファームウェアとディスクシェルフファームウェアが更新され、このタスクの検証手順が完了するまで、アグリゲートまたはボリュームにディスクドライブを追加しないでください。

. 新しいスタックのスイッチポートを有効にします。
. ONTAP で MetroCluster 構成の動作を確認します。
+
.. システムがマルチパスかどうかを確認します。
+
'node run -node _node-name_sysconfig -a

.. ヘルスアラートがないかどうかを両方のクラスタで確認します。
+
「 system health alert show 」というメッセージが表示されます

.. MetroCluster 構成と運用モードが正常な状態であることを確認します。
+
「 MetroCluster show 」

.. MetroCluster チェックを実行します。
+
「 MetroCluster check run 」のようになります

.. MetroCluster チェックの結果を表示します。
+
MetroCluster チェックショー

.. スイッチにヘルスアラートがないかどうかを確認します（ある場合）。
+
「 storage switch show 」と表示されます

.. Config Advisor を実行します。
+
https://["ネットアップのダウンロード： Config Advisor"^]

.. Config Advisor の実行後、ツールの出力を確認し、推奨される方法で検出された問題に対処します。


. 必要に応じて、パートナーサイトに対してこの手順を繰り返します。

