---
permalink: maintain/task_add_remove_or_change_isl_ports_nondisruptively.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, add, remove, change, isl, ports, nondisruptively 
summary: ISL ポートの追加、削除、または変更が必要になる場合があります。専用の ISL ポートを共有 ISL ポートに変換したり、スイッチの ISL ポートの速度を変更したりできます。ISL の距離が長い場合、品質を向上させるために速度を下げなければならないことがあります。また、ハードウェアを追加またはアップグレードする場合は、システムのアップグレードに合わせて ISL ポートの速度を上げ、 Cisco IP スイッチに ISL を追加することがあります。 
---
= Cisco IPスイッチのISLポートを無停止で追加、削除、変更
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cisco IPスイッチでISLポートの追加、削除、または変更が必要になる場合があります。Cisco IPスイッチでは、専用ISLポートを共有ISLポートに変換したり、ISLポートの速度を変更したりできます。

.このタスクについて
専用の ISL ポートを共有 ISL ポートに変換する場合は、新しいポートがに対応していることを確認してください link:../install-ip/concept_considerations_layer_2.html["共有 ISL ポートの要件"]。

ISL 接続を確保するためには、両方のスイッチですべての手順を実行する必要があります。

次の手順では、スイッチポート Eth1/24/1 に接続されている 10Gb ISL を、スイッチポート 17 と 18 に接続されている 2 つの 100Gb ISL に交換します。


NOTE: NS224シェルフを接続する共有構成でCisco 9336C-FX2スイッチを使用している場合は、ISLを変更するときに新しいRCFファイルが必要になることがあります。現在のISL速度が40Gbpsおよび100Gbpsの場合は、新しいRCFファイルは必要ありません。ISLの速度に対するその他の変更には、新しいRCFファイルが必要です。たとえば、ISLの速度を40Gbpsから100Gbpsに変更しても新しいRCFファイルは必要ありませんが、ISLの速度を10Gbpsから40Gbpsに変更するには新しいRCFファイルが必要です。

.作業を開始する前に
の*スイッチ*セクションを参照してください。 link:https://hwu.netapp.com/["NetApp Hardware Universe の略"^] をクリックして、サポートされているトランシーバを確認します。

.手順
. 変更するファブリック内の両方のスイッチで、 ISL の ISL ポートを無効にします。
+
--

NOTE: 現在の ISL ポートを無効にするのは、ポートを別のポートに移動している場合や ISL の速度が変更されている場合だけです。既存の ISL と同じ速度の ISL ポートを追加する場合は、手順 3 に進みます。

--
+
次の例に示すように、設定コマンドを 1 行に 1 つ入力し、すべてのコマンドを入力したら Ctrl+Z キーを押す必要があります。

+
[listing]
----

switch_A_1# conf t
switch_A_1(config)# int eth1/24/1
switch_A_1(config-if)# shut
switch_A_1(config-if)#
switch_A_1#

switch_B_1# conf t
switch_B_1(config)# int eth1/24/1
switch_B_1(config-if)# shut
switch_B_1(config-if)#
switch_B_1#
----
. 既存のケーブルとトランシーバを取り外します。
. 必要に応じて ISL ポートを変更します。
+

NOTE: NS224シェルフを接続する共有構成でCisco 9336C-FX2スイッチを使用していて、RCFファイルをアップグレードして新しいISLポートに新しい構成を適用する必要がある場合は、次の手順を実行します。 link:task_upgrade_rcf_files_on_mcc_ip_switches.html["MetroCluster IPスイッチでRCFファイルをアップグレードします。"]

+
[cols="30,70"]
|===


| オプション | ステップ 


 a| 
ISL ポートの速度を変更する
 a| 
速度に応じて、新しい ISL を指定のポートにケーブル接続します。使用しているスイッチの ISL ポートが MetroCluster IP インストールおよび設定に表示されていることを確認する必要があります。



 a| 
ISL を追加する
 a| 
ISL ポートとして追加するポートに QFSP を挿入します。MetroCluster IP のインストールと設定に表示されていることを確認し、それに応じてケーブルを接続します。

|===
. ファブリック内の両方のスイッチですべての ISL ポートを有効にします（有効になっていない場合）。最初に次のコマンドを入力します。
+
'switch_A_1# conf t`

+
設定コマンドを 1 行に 1 つ入力し、すべてのコマンドを入力したら Ctrl+Z キーを押す必要があります。

+
[listing]
----
switch_A_1# conf t
switch_A_1(config)# int eth1/17
switch_A_1(config-if)# no shut
switch_A_1(config-if)# int eth1/18
switch_A_1(config-if)# no shut
switch_A_1(config-if)#
switch_A_1#
switch_A_1# copy running-config startup-config

switch_B_1# conf t
switch_B_1(config)# int eth1/17
switch_B_1(config-if)# no shut
switch_B_1(config-if)# int eth1/18
switch_B_1(config-if)# no shut
switch_B_1(config-if)#
switch_B_1#
switch_B_1# copy running-config startup-config
----
. 両方のスイッチ間にISLとポートチャネルが確立されていることを確認します。
+
`switch_A_1# show int brief`

+
次の例に示すように、 ISL インターフェイスがコマンド出力に表示されます。

+
[listing]
----
Switch_A_1# show interface brief
--------------------------------------------------------------------------------
Ethernet        VLAN    Type Mode   Status  Reason                 Speed     Port
Interface                                                                    Ch #
--------------------------------------------------------------------------------
Eth1/17         1       eth  access down    XCVR not inserted        auto(D) --
Eth1/18         1       eth  access down    XCVR not inserted        auto(D) --

------------------------------------------------------------------------------------------
Port-channel VLAN    Type Mode   Status  Reason                              Speed   Protocol
Interface
------------------------------------------------------------------------------------------
Po10         1       eth  trunk  up      none                                a-100G(D)  lacp
Po11         1       eth  trunk  up      none                                a-100G(D)  lacp
----
. ファブリック 2 についても手順を繰り返します。

