---
permalink: maintain/task_online_or_offline_the_mcc_ip_interface.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, online, offline, ip, interface port 
summary: メンテナンスを実施する場合は、MetroCluster IPインターフェイスポートを停止しなければならないことがあります。 
---
= オンラインまたはオフラインのMetroCluster IPインターフェイスポート
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
メンテナンスタスクを実行する際に、MetroCluster IPインターフェイスポートをオフラインまたはオンラインにしなければならない場合があります。

MetroCluster IPインターフェイスポートをオフラインまたはオンラインにするには、次の手順を実行します。

.手順
. 権限レベルを advanced に設定します。
+
[source, cli]
----
set -privilege advanced
----
+
*出力例*

+
[listing]
----
Cluster A_1::> set -privilege advanced
Warning: These advanced commands are potentially dangerous; use them only when
         directed to do so by NetApp personnel.
Do you want to continue? {y|n}: y
----
. MetroCluster IPインターフェイスポートをオフラインにします。
+
[source, cli]
----
system ha interconnect link off -node <node_name> -link <link_num, 0 or 1>
----
+
*出力例*

+
[listing]
----
Cluster_A1::*> system ha interconnect link off -node node-a1 -link 0
----
+
.. MetroCluster IPインターフェイスがオフラインであることを確認します。
+
[source, cli]
----
Cluster_A1::*> system ha interconnect port show
----
+
*出力例*

+
[listing]
----
Cluster_A1::*> system ha interconnect port show
                               Physical  Link
                Link           Layer     Layer      Physical   Physical  Active
Node            Monitor  Port  State     State       Link Up  Link Down  Link
--------------  -------  ----  --------  ---------  --------  ---------  ------
node-a1        off
                            0  disabled  down              4          3  false
                            1  linkup    active            4          2  true
node-a2        off
                            0  linkup    active            4          2  true
                            1  linkup    active            4          2  true
2 entries were displayed.
----


. MetroCluster IPインターフェイスポートをオンラインにします。
+
[source, cli]
----
system ha interconnect link on -node <node_name> -link <link_num, 0 or 1>
----
+
*出力例*

+
[listing]
----
Cluster_A1::*> system ha interconnect link on -node node-a1 -link 0
----
+
.. MetroCluster IPインターフェイスポートがオンラインであることを確認します。
+
[source, cli]
----
Cluster_A1::*> system ha interconnect port show
----
+
*出力例*

+
[listing]
----
Cluster_A1::*> system ha interconnect port show
                               Physical  Link
                Link           Layer     Layer      Physical   Physical  Active
Node            Monitor  Port  State     State       Link Up  Link Down  Link
--------------  -------  ----  --------  ---------  --------  ---------  ------
node-a1        off
                            0  linkup    active            5          3  true
                            1  linkup    active            4          2  true
node-a2        off
                            0  linkup    active            4          2  true
                            1  linkup    active            4          2  true
2 entries were displayed.
----



