---
permalink: maintain/task_upgrade_rcf_files_on_mcc_ip_switches.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, upgrade, rcf, files, ip, switches 
summary: MetroCluster IP スイッチ上の RCF ファイルのアップグレードが必要になる場合があります。たとえば、 ONTAP のアップグレードまたはスイッチファームウェアのアップグレードには、どちらも新しい RCF ファイルが必要です。 
---
= MetroCluster IP スイッチの RCF ファイルをアップグレードします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
MetroCluster IP スイッチ上の RCF ファイルのアップグレードが必要になる場合があります。たとえば、スイッチで実行しているRCFファイルのバージョンが、ONTAPのバージョン、スイッチのファームウェアのバージョン、またはその両方でサポートされていない場合などです。



== RCFファイルがサポートされていることの確認

ONTAPまたはスイッチファームウェアのバージョンを変更する場合は、そのバージョンでサポートされるRCFファイルがあることを確認する必要があります。RCF ジェネレータを使用すると、正しい RCF ファイルが生成されます。

.手順
. RCF ファイルのバージョンを確認するには、スイッチから次のコマンドを使用します。
+
[cols="30,70"]
|===


| スイッチ | 問題コマンド 


 a| 
Broadcomスイッチ
 a| 
`(IP_switch_A_1) # show clibanner`



 a| 
Cisco スイッチ
 a| 
ip_switch _A_1# には、 banner motd が表示されます

|===
+
いずれかのスイッチについて、 RCF ファイルのバージョンを示す行を出力から探します。たとえば、次の出力は Cisco スイッチを使用したもので、 RCF ファイルのバージョンが「 v1.80 」であることを示しています。

+
....
Filename : NX3232_v1.80_Switch-A2.txt
....
. 特定の ONTAP バージョン、スイッチ、およびプラットフォームでサポートされているファイルを確認するには、 RcfFileGenerator を使用します。現在使用している設定またはにアップグレードする設定用の RCF ファイルを生成できる場合は、そのファイルがサポートされます。
. スイッチファームウェアがサポートされていることを確認するには、次のマニュアルを参照してください。
+
** https://hwu.netapp.com["Hardware Universe"]
** https://mysupport.netapp.com/NOW/products/interoperability["ネットアップの相互運用性"]






== RCF ファイルをアップグレードします

新しいスイッチファームウェアをインストールする場合は、 RCF ファイルをアップグレードする前にスイッチファームウェアをインストールする必要があります。

.このタスクについて
この手順では、 RCF ファイルをアップグレードするスイッチ上のトラフィックが中断されます。新しい RCF ファイルが適用されると、トラフィックは再開されます。

.手順
. 構成の健全性を確認
+
.. MetroCluster コンポーネントが正常であることを確認します。
+
「 MetroCluster check run 」のようになります

+
[listing]
----
cluster_A::*> metrocluster check run

----


+
この処理はバックグラウンドで実行されます。

+
.. MetroCluster check run オペレーションが完了したら ' MetroCluster check show を実行して結果を表示します
+
約 5 分後に、次の結果が表示されます。

+
[listing]
----
-----------
::*> metrocluster check show

Last Checked On: 4/7/2019 21:15:05

Component           Result
------------------- ---------
nodes               ok
lifs                ok
config-replication  ok
aggregates          warning
clusters            ok
connections         not-applicable
volumes             ok
7 entries were displayed.
----
.. 実行中の MetroCluster チェック処理のステータスを確認します。
+
MetroCluster オペレーション履歴 show -job-id 38`

.. ヘルスアラートがないことを確認します。
+
「 system health alert show 」というメッセージが表示されます



. 新しい RCF ファイルを適用するための IP スイッチを準備します。
+
スイッチベンダーの手順に従います。

+
** link:../install-ip/task_switch_config_broadcom.html["Broadcom IP スイッチを工場出荷時のデフォルトにリセット"]
** link:../install-ip/task_switch_config_cisco.html["Cisco IP スイッチを工場出荷時のデフォルトにリセットする"]


. スイッチベンダーに応じて、IP RCFファイルをダウンロードしてインストールします。
+

NOTE: スイッチを次の順序で更新します。Switch_A_1、Switch_B_1、Switch_A_1、Switch_B_2

+
** link:../install-ip/task_switch_config_broadcom.html#downloading-and-installing-the-broadcom-rcf-files["Broadcom IP の RCF ファイルをダウンロードしてインストールします"]
** link:../install-ip/task_switch_config_cisco.html#downloading-and-installing-the-cisco-ip-rcf-files["Cisco IP RCF ファイルのダウンロードとインストール"]
+

NOTE: L2共有またはL3ネットワーク構成を使用している場合は、お客様の中間スイッチまたはお客様のスイッチでISLポートの調整が必要になることがあります。スイッチポートモードが「access」モードから「trunk」モードに変わることがあります。スイッチ_A_1とB_1の間のネットワーク接続が完全に機能していて、ネットワークが正常である場合にのみ、2つ目のスイッチペア（A_2、B_2）のアップグレードに進みます。




