---
permalink: maintain/task_upgrade_firmware_on_mcc_ip_switches.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, upgrade, firmware. ip, switches, cisco, broadcom, efos, nxos, nx-os, software, install 
summary: MetroCluster IP スイッチでのファームウェアのアップグレード。 
---
= MetroCluster IP スイッチでのファームウェアのアップグレード
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
MetroCluster IP スイッチのファームウェアのアップグレードが必要になる場合があります。

各スイッチでこのタスクを順に実行する必要があります。

.手順
. 構成の健全性を確認します。
+
.. 各クラスタで MetroCluster が設定されており、通常モードであることを確認します。
+
「 MetroCluster show 」

+
[listing]
----
cluster_A::> metrocluster show
Cluster                   Entry Name          State
------------------------- ------------------- -----------
 Local: cluster_A         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-cluster-disaster
Remote: cluster_B         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-cluster-disaster
----
.. 各ノードでミラーリングが有効であることを確認します。
+
MetroCluster node show

+
[listing]
----
cluster_A::> metrocluster node show
DR                           Configuration  DR
Group Cluster Node           State          Mirroring Mode
----- ------- -------------- -------------- --------- --------------------
1     cluster_A
              node_A_1       configured     enabled   normal
      cluster_B
              node_B_1       configured     enabled   normal
2 entries were displayed.
----
.. MetroCluster コンポーネントが正常であることを確認します。
+
「 MetroCluster check run 」のようになります

+
[listing]
----
cluster_A::> metrocluster check run

Last Checked On: 10/1/2014 16:03:37

Component           Result
------------------- ---------
nodes               ok
lifs                ok
config-replication  ok
aggregates          ok
4 entries were displayed.

Command completed. Use the "metrocluster check show -instance" command or sub-commands in "metrocluster check" directory for detailed results.
To check if the nodes are ready to do a switchover or switchback operation, run "metrocluster switchover -simulate" or "metrocluster switchback -simulate", respectively.
----
.. ヘルスアラートがないことを確認します。
+
「 system health alert show 」というメッセージが表示されます



. 最初のスイッチにソフトウェアをインストールします。
+

NOTE: スイッチには、 switch_A_1 、 switch_B_1 、 switch_B_2 、 switch_B_2 、 switch_B_2 、スイッチ _B_2 を順番にインストールします。

+
スイッチタイプがBroadcom、Cisco、NVIDIAのいずれであるかに応じて、MetroCluster IP Installation and Configuration_informationの関連トピックに記載されているスイッチソフトウェアのインストール手順に従います。

+
** link:../install-ip/task_switch_config_broadcom.html#downloading-and-installing-the-broadcom-switch-efos-software["BroadcomスイッチのEFOSソフトウェアをダウンロードしてインストールする"]
** link:../install-ip/task_switch_config_cisco.html#downloading-and-installing-the-cisco-switch-nx-os-software["CiscoスイッチのNX-OSソフトウェアのダウンロードとインストール"]
** link:../install-ip/task_switch_config_nvidia.html#download-and-install-the-cumulus-software["NVIDIA SN2100スイッチCumulusソフトウェアのダウンロードとインストール"]




. 各スイッチについて、同じ手順を繰り返します。
. 手順 1 を繰り返して構成の健常性を確認します。

