---
permalink: maintain/task_replace_a_shelf_nondisruptively_in_a_stretch_mcc_configuration.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, replace, shelf, nondisruptively, stretch, configuration 
summary: ディスクシェルフまたはディスクシェルフシャーシがフル装備されたストレッチ MetroCluster 構成では、システムを停止することなくディスクシェルフを交換し、取り外すシェルフからコンポーネントを移すことができます。 
---
= ストレッチ MetroCluster 構成のシェルフの無停止での交換
:icons: font
:imagesdir: ../media/


[role="lead"]
ディスクシェルフまたはディスクシェルフシャーシがフル装備されたストレッチ MetroCluster 構成では、システムを停止することなくディスクシェルフを交換し、取り外すシェルフからコンポーネントを移すことができます。

設置するディスクシェルフモデルが、に記載されているストレージシステムの要件を満たしている必要があります link:https://hwu.netapp.com["Hardware Universe"^]サポートされるシェルフモデル、サポートされるディスクドライブタイプ、スタック内のディスクシェルフの最大数、サポートされる ONTAP バージョンなどがあります。

.手順
. 自身の適切な接地対策を行います
. 交換するシェルフが含まれているループのディスクがあるアグリゲートとボリュームをすべて特定し、関係するプレックス名をメモします。
+
いずれかのノードに、関係するシェルフとホストアグリゲートまたはホストボリュームのループのディスクが含まれている場合があります。

. 計画している交換のシナリオに基づいて、次の 2 つのオプションのいずれかを選択します。
+
** シェルフシャーシ、ディスク、および I/O モジュール（ IOM ）を含むディスクシェルフ全体を交換する場合は、次の表の対応する操作を実行します。
+
|===


| シナリオ（ Scenario ） | アクション 


 a| 
関係するプレックスに含まれるディスク数が関係するシェルフよりも少ない。
 a| 
関係するシェルフのディスクを別のシェルフのスペアと 1 本ずつ交換します。


NOTE: ディスク交換の完了後にプレックスをオフラインにすることができます。



 a| 
関係するプレックスに含まれるディスク数が関係するシェルフよりも多い。
 a| 
プレックスをオフラインにして削除します。



 a| 
関係するプレックスに関係するシェルフのいずれかのディスクが含まれる。
 a| 
プレックスをオフラインにしますが削除はしません。

|===
** ディスクシェルフシャーシのみを交換し、他のコンポーネントは交換しない場合は、次の手順を実行します。
+
... 関係するプレックスをホストしているコントローラで、それらのプレックスをオフラインにします。
+
「アグリゲートはオフライン」です

... プレックスがオフラインであることを確認します。
+
アグリゲート・ステータス -r





. 関係するシェルフループが接続されているコントローラ SAS ポートを特定し、両方のサイトコントローラでその SAS ポートを無効にします。
+
storage port disable -node node_name -port_sas_port_

+
関係するシェルフループが両方のサイトに接続されます。

. ディスクが見つからないことが ONTAP で認識されるまで待ちます。
+
.. ディスクがないことを確認します。
+
「 sysconfig -a 」または「 sysconfig -r 」です



. ディスクシェルフの電源スイッチをオフにします。
. ディスクシェルフからすべての電源コードを取り外します。
. 新しいディスクシェルフを同じようにケーブル接続できるように、ケーブルを取り外したポートをメモしておいてください。
. ディスクシェルフを他のディスクシェルフまたはストレージシステムに接続しているケーブルを取り外します。
. ラックからディスクシェルフを取り外します。
+
ディスクシェルフを軽くして扱いやすくするために、電源装置と IOM を取り外します。ディスクシェルフシャーシを設置する場合は、ディスクドライブやキャリアも取り外します。そうでない場合は、過度に動かすと原因の内蔵ドライブが破損する可能性があるため、ディスクドライブやキャリアはできるだけ取り外さないようにしてください。

. 交換用ディスクシェルフをサポートブラケットとラックに設置して固定します。
. ディスクシェルフシャーシを設置した場合は、電源装置と IOM を再度取り付けます。
. 取り外したディスクシェルフとまったく同じように、交換用ディスクシェルフのポートにすべてのケーブルを接続してディスクシェルフのスタックを再構成します。
. 交換用ディスクシェルフの電源をオンにし、ディスクドライブがスピンアップするまで待ちます。
. ディスクシェルフ ID を 0~98 の一意の ID に変更します。
. 無効にした SAS ポートを有効にします。
+
.. ディスクが挿入されたことが ONTAP で認識されるまで待ちます。
.. ディスクが挿入されたことを確認します。
+
「 sysconfig -a 」または「 sysconfig -r 」です



. ディスクシェルフ全体（ディスクシェルフシャーシ、ディスク、 IOM ）を交換する場合は、次の手順を実行します。
+

NOTE: ディスクシェルフシャーシのみを交換し、他のコンポーネントは交換しない場合は、手順 19 に進みます。

+
.. ディスクの自動割り当てが有効になっているかどうかを確認します（ on ）。
+
storage disk option modify -autoassign

+
ディスクの割り当ては自動的に実行されます。

.. ディスクの自動割り当てが有効になっていない場合は、ディスク所有権を手動で割り当てます。


. プレックスをオンラインに戻します。
+
'aggregate online_plex name_`

. アグリゲートをミラーリングして、削除されたプレックスを再作成します。
. プレックスで再同期が開始されるのを監視します。
+
'aggregate status -r < アグリゲート名 >`

. ストレージシステムが想定どおりに機能していることを確認します。
+
「 system health alert show 」というメッセージが表示されます


