---
permalink: maintain/task_upgrade_firmware_on_mcc_ip_switches.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, upgrade, firmware. ip, switches, cisco, broadcom, efos, nxos, nx-os, software, install 
summary: MetroCluster IP スイッチでのファームウェアのアップグレード。 
---
= MetroCluster IP スイッチのファームウェアをアップグレードします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
MetroCluster IP スイッチのファームウェアのアップグレードが必要になる場合があります。



== RCFのサポート状況の確認

ONTAPまたはスイッチファームウェアのバージョンを変更する場合は、そのバージョンでサポートされるリファレンス構成ファイル（RCF）があることを確認する必要があります。このツールを使用するlink:https://mysupport.netapp.com/site/tools/tool-eula/rcffilegenerator["RcfFileGenerator の順にクリックします"^]と、構成に応じた正しいRCFが生成されます。

.手順
. スイッチから次のコマンドを使用して、RCFのバージョンを確認します。
+
[cols="30,70"]
|===


| スイッチ | 問題コマンド 


 a| 
Broadcomスイッチ
 a| 
`(IP_switch_A_1) # show clibanner`



 a| 
Cisco スイッチ
 a| 
ip_switch _A_1# には、 banner motd が表示されます



 a| 
NVIDIA SN2100スイッチ
 a| 
`cumulus@mcc1:mgmt:~$ nv config find message`

|===
+
コマンド出力で、RCFバージョンを示す行を確認します。たとえば、Ciscoスイッチからの次の出力は、RCFバージョンが「v1.80」であることを示しています。

+
....
Filename : NX3232_v1.80_Switch-A2.txt
....
. 特定のONTAPバージョン、スイッチ、およびプラットフォームでサポートされているファイルを確認するには、を使用しlink:https://mysupport.netapp.com/site/tools/tool-eula/rcffilegenerator["MetroCluster IP 用の RcfFileGenerator"^]ます。既存の構成またはにアップグレードする構成に対してRCFを生成できる場合は、そのRCFがサポートされます。
. スイッチファームウェアがサポートされていることを確認するには、次のマニュアルを参照してください。
+
** https://hwu.netapp.com["Hardware Universe"]
** https://imt.netapp.com/matrix/["NetApp Interoperability Matrix を参照してください"^]






== スイッチのファームウェアをアップグレードします。

.このタスクについて
各スイッチでこのタスクを順に実行する必要があります。

link:enable-console-logging-before-maintenance.html["コンソールログを有効にする"] このタスクを実行する前に。

[[step_1_fw_upgrade]]
.手順
. 構成の健全性を確認します。
+
.. 各クラスタで MetroCluster が設定されており、通常モードであることを確認します。
+
「 MetroCluster show 」

+
[listing]
----
cluster_A::> metrocluster show
Cluster                   Entry Name          State
------------------------- ------------------- -----------
 Local: cluster_A         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-cluster-disaster
Remote: cluster_B         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-cluster-disaster
----
.. 各ノードでミラーリングが有効であることを確認します。
+
MetroCluster node show

+
[listing]
----
cluster_A::> metrocluster node show
DR                           Configuration  DR
Group Cluster Node           State          Mirroring Mode
----- ------- -------------- -------------- --------- --------------------
1     cluster_A
              node_A_1       configured     enabled   normal
      cluster_B
              node_B_1       configured     enabled   normal
2 entries were displayed.
----
.. MetroCluster コンポーネントが正常であることを確認します。
+
「 MetroCluster check run 」のようになります

+
[listing]
----
cluster_A::*> metrocluster check run
----
+
この処理はバックグラウンドで実行されます。

.. のあとに入力します `metrocluster check run` 処理が完了しました。run：
+
MetroCluster チェックショー

+
約 5 分後に、次の結果が表示されます。

+
[listing]
----
cluster_A:::*> metrocluster check show

Component           Result
------------------- ---------
nodes               ok
lifs                ok
config-replication  ok
aggregates          ok
clusters            ok
connections         ok
volumes             ok
7 entries were displayed.
----
.. ヘルスアラートがないことを確認します。
+
「 system health alert show 」というメッセージが表示されます



. 最初のスイッチにソフトウェアをインストールします。
+

NOTE: スイッチには、 switch_A_1 、 switch_B_1 、 switch_B_2 、 switch_B_2 、 switch_B_2 、スイッチ _B_2 を順番にインストールします。

+
スイッチタイプがBroadcom、Cisco、NVIDIAのいずれであるかに応じて、該当するトピックのスイッチソフトウェアをインストールする手順に従います。

+
** link:../install-ip/task_switch_config_broadcom.html#downloading-and-installing-the-broadcom-switch-efos-software["BroadcomスイッチのEFOSソフトウェアをダウンロードしてインストールする"]
** link:../install-ip/task_switch_config_cisco.html#downloading-and-installing-the-cisco-switch-nx-os-software["CiscoスイッチのNX-OSソフトウェアのダウンロードとインストール"]
** link:../install-ip/task_switch_config_nvidia.html#download-and-install-the-cumulus-software["NVIDIA SN2100スイッチCumulusソフトウェアのダウンロードとインストール"]


. 各スイッチについて、同じ手順を繰り返します。
. 繰り返します <<step_1_fw_upgrade,手順 1.>> 構成の健全性を確認します。

