---
permalink: maintain/task_replace_a_sle_fc_to_sas_bridge.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, replace, single, fc, sas, bridge 
summary: ブリッジを同じモデルのブリッジまたは新しいモデルのブリッジに無停止で交換することができます。 
---
= 単一の FC-to-SAS ブリッジの交換
:icons: font
:imagesdir: ../media/


[role="lead"]
ブリッジを同じモデルのブリッジまたは新しいモデルのブリッジに無停止で交換することができます。

管理パスワードと FTP サーバまたは SCP サーバへのアクセスが必要です。

これはシステムの停止を伴わない手順であり、完了までに約 60 分かかります。

この手順では、ブリッジ CLI を使用してブリッジを設定および管理し、ブリッジファームウェアと ATTO QuickNAV ユーティリティを更新してブリッジイーサネット管理 1 ポートを設定します。要件を満たしていれば、他のインターフェイスも使用できます。

xref:reference_requirements_for_using_other_interfaces_to_configure_and_manage_fibrebridge_bridges.adoc[他のインターフェイスを使用して FibreBridge ブリッジを設定および管理するための要件]

* 関連情報 *

xref:task_fb_consolidate_replace_a_pair_of_fibrebridge_6500n_bridges_with_7500n_bridges.adoc[FibreBridge 6500N ブリッジのペアを 7600N / 7500N ブリッジに交換する]



== ストレージ接続を確認しています

[role="lead"]
ブリッジを交換する前に、ブリッジとストレージの接続を確認する必要があります。設定を変更したあとに接続を確認できるよう、コマンド出力について理解しておいてください。

これらのコマンドは、メンテナンス中のサイトの MetroCluster 構成にある任意のコントローラモジュールの管理プロンプトから問題できます。

.手順
. いずれかの MetroCluster ノードで次のコマンドを入力して、ディスクへの接続を確認します。
+
'*run local sysconfig -v *

+
出力には、コントローラのイニシエータポートに接続されているディスクが表示され、 FC-to-SAS ブリッジに接続されているシェルフが示されます。

+
[listing]
----

node_A_1> run local sysconfig -v
NetApp Release 9.3.2X18: Sun Dec 13 01:23:24 PST 2017
System ID: 4068741258 (node_A_1); partner ID: 4068741260 (node_B_1)
System Serial Number: 940001025471 (node_A_1)
System Rev: 70
System Storage Configuration: Multi-Path HA**<=== Configuration should be multi-path HA**
.
.
.
slot 0: FC Host Adapter 0g (QLogic 8324 rev. 2, N-port, <UP>)**<=== Initiator port**
		Firmware rev:      7.5.0
		Flash rev:         0.0.0
		Host Port Id:      0x60130
		FC Node Name:      5:00a:098201:bae312
		FC Port Name:      5:00a:098201:bae312
		SFP Vendor:        UTILITIES CORP.
		SFP Part Number:   FTLF8529P3BCVAN1
		SFP Serial Number: URQ0Q9R
		SFP Capabilities:  4, 8 or 16 Gbit
		Link Data Rate:    16 Gbit
		Switch Port:       brcd6505-fcs40:1
  **<List of disks visible to port\>**
		 ID     Vendor   Model            FW    Size
		brcd6505-fcs29:12.126L1527     : NETAPP   X302_HJUPI01TSSM NA04 847.5GB (1953525168 512B/sect)
		brcd6505-fcs29:12.126L1528     : NETAPP   X302_HJUPI01TSSA NA02 847.5GB (1953525168 512B/sect)
		.
		.
		.
		**<List of FC-to-SAS bridges visible to port\>**
		FC-to-SAS Bridge:
		brcd6505-fcs40:12.126L0        : ATTO     FibreBridge6500N 1.61  FB6500N102980
		brcd6505-fcs42:13.126L0        : ATTO     FibreBridge6500N 1.61  FB6500N102980
		brcd6505-fcs42:6.126L0         : ATTO     FibreBridge6500N 1.61  FB6500N101167
		brcd6505-fcs42:7.126L0         : ATTO     FibreBridge6500N 1.61  FB6500N102974
		.
		.
		.
  **<List of storage shelves visible to port\>**
		brcd6505-fcs40:12.shelf6: DS4243  Firmware rev. IOM3 A: 0200  IOM3 B: 0200
		brcd6505-fcs40:12.shelf8: DS4243  Firmware rev. IOM3 A: 0200  IOM3 B: 0200
		.
		.
		.
----




== 同じモデルの交換用ブリッジとのホットスワップ

[role="lead"]
障害が発生したブリッジを同じモデルの別のブリッジとホットスワップすることができます。

IP 管理ではなくブリッジのインバンド管理を使用する場合は、該当する手順に記載されているように、イーサネットポートと IP を設定する手順を省略できます。


NOTE: ONTAP 9.8 以降では '*storage bridge *' コマンドは '*system bridge *' に置き換えられています以下の手順は '*storage bridge *' コマンドを示していますが 'ONTAP 9.8 以降を実行している場合は '*system bridge *' コマンドを使用することをお勧めします

.手順
. 古いブリッジにアクセスできる場合は、設定情報を取得できます。
+
|===
| 状況 | 作業 


 a| 
* IP 管理 * を使用しています
 a| 
Telnet 接続を使用して古いブリッジに接続し、ブリッジ設定の出力をコピーします。



 a| 
* インバンド管理 * を使用しています
 a| 
次のコマンドを使用して、 ONTAP CLI を使用して設定情報を取得します。

「 * storage bridge run -cli-name_bridge-name_command "info" * 」

「 * storage bridge run -cli-name_bridge-name_command "sasportlist" * 」」

|===
+
入力するコマンド

+
`* storage bridge run -cli-name bridge_A1 - コマンド "info"*`

+
[listing]
----
info

Device Status         = Good
Unsaved Changes       = None
Device                = "FibreBridge 7500N"
Serial Number         = FB7500N100000
Device Version        = 3.10
Board Revision        = 7
Build Number          = 007A
Build Type            = Release
Build Date            = "Aug 20 2019" 11:01:24
Flash Revision        = 0.02
Firmware Version      = 3.10
BCE Version (FPGA 1)  = 15
BAU Version (FPGA 2)  = 33
User-defined name     = "bridgeA1"
World Wide Name       = 20 00 00 10 86 A1 C7 00
MB of RAM Installed   = 512
FC1 Node Name         = 20 00 00 10 86 A1 C7 00
FC1 Port Name         = 21 00 00 10 86 A1 C7 00
FC1 Data Rate         = 16Gb
FC1 Connection Mode   = ptp
FC1 FW Revision       = 11.4.337.0
FC2 Node Name         = 20 00 00 10 86 A1 C7 00
FC2 Port Name         = 22 00 00 10 86 A1 C7 00
FC2 Data Rate         = 16Gb
FC2 Connection Mode   = ptp
FC2 FW Revision       = 11.4.337.0
SAS FW Revision       = 3.09.52
MP1 IP Address        = 10.10.10.10
MP1 IP Subnet Mask    = 255.255.255.0
MP1 IP Gateway        = 10.10.10.1
MP1 IP DHCP           = disabled
MP1 MAC Address       = 00-10-86-A1-C7-00
MP2 IP Address        = 0.0.0.0 (disabled)
MP2 IP Subnet Mask    = 0.0.0.0
MP2 IP Gateway        = 0.0.0.0
MP2 IP DHCP           = enabled
MP2 MAC Address       = 00-10-86-A1-C7-01
SNMP                  = enabled
SNMP Community String = public
PS A Status           = Up
PS B Status           = Up
Active Configuration  = NetApp

Ready.
----
+
入力するコマンド

+
「 * storage bridge run -cli-name bridge_A1 - コマンド「 sasportlist 」 *

+
[listing]
----


SASPortList

;Connector      PHY     Link            Speed   SAS Address
;=============================================================
Device  A       1       Up              6Gb     5001086000a1c700
Device  A       2       Up              6Gb     5001086000a1c700
Device  A       3       Up              6Gb     5001086000a1c700
Device  A       4       Up              6Gb     5001086000a1c700
Device  B       1       Disabled        12Gb    5001086000a1c704
Device  B       2       Disabled        12Gb    5001086000a1c704
Device  B       3       Disabled        12Gb    5001086000a1c704
Device  B       4       Disabled        12Gb    5001086000a1c704
Device  C       1       Disabled        12Gb    5001086000a1c708
Device  C       2       Disabled        12Gb    5001086000a1c708
Device  C       3       Disabled        12Gb    5001086000a1c708
Device  C       4       Disabled        12Gb    5001086000a1c708
Device  D       1       Disabled        12Gb    5001086000a1c70c
Device  D       2       Disabled        12Gb    5001086000a1c70c
Device  D       3       Disabled        12Gb    5001086000a1c70c
Device  D       4       Disabled        12Gb    5001086000a1c70c
----
. ブリッジがファブリック接続 MetroCluster 構成に含まれている場合は、ブリッジの FC ポートに接続しているすべてのスイッチポートを無効にします。
. ONTAP クラスタのプロンプトで、メンテナンス中のブリッジをヘルスモニタの対象から削除します。
+
.. ブリッジ +`* storage bridge remove-name_bridge-name_*` を削除します
.. 監視中のブリッジのリストを表示し、削除したブリッジが含まれていないことを確認します。 +`* storage bridge show *`


. 自身の適切な接地対策を行います
. ATTO ブリッジの電源をオフにします。
+
|===
| 使用する方法 | 作業 


 a| 
FibreBridge 7600N または 7500N ブリッジ
 a| 
ブリッジに接続されている電源ケーブルを取り外します。



 a| 
FibreBridge 6500N ブリッジ
 a| 
ブリッジの電源スイッチをオフにします。

|===
. 古いブリッジに接続されているケーブルを外します。
+
各ケーブルが接続されていたポートをメモしておいてください。

. ラックから古いブリッジを取り外します。
. 新しいブリッジをラックに取り付けます。
. 電源コードを再接続します。また、ブリッジへの IP アクセスを設定する場合は、シールド付きイーサネットケーブルを再接続します。
+

IMPORTANT: SAS / FC ケーブルはまだ再接続しないでください。

. ブリッジを電源に接続し、電源をオンにします。
+
ブリッジの準備完了を示す LED が点灯し、ブリッジの電源投入時自己診断テストが完了したことを示すまで、 30 秒ほどかかる場合があります。

. インバンド管理用に設定する場合は、 FibreBridge RS-232 シリアルポートから PC のシリアル（ COM ）ポートにケーブルを接続します。
+
シリアル接続は初期設定と ONTAP によるインバンド管理に使用され、 FC ポートを使用してブリッジの監視と管理を行うことができます。

. IP 管理用に設定する場合は、使用しているブリッジモデルの ATTO FibreBridge Installation and Operation Manual _ のセクション 2.0 の手順に従って、各ブリッジのイーサネット管理 1 ポートを設定します。
+
ONTAP 9.5 以降を実行しているシステムでは、インバンド管理を使用してイーサネットポートではなく FC ポート経由でブリッジにアクセスできます。ONTAP 9.8 以降では、インバンド管理のみがサポートされ、 SNMP 管理は廃止されています。

+
QuickNAV を実行してイーサネット管理ポートを設定すると、イーサネットケーブルで接続されているイーサネット管理ポートのみが設定されます。たとえば、イーサネット管理 2 ポートも設定する場合は、イーサネットケーブルをポート 2 に接続して QuickNAV を実行する必要があります。

. ブリッジを設定します。
+
古いブリッジから設定情報を取得した場合は、その情報を使用して新しいブリッジを設定します。

+
指定するユーザ名とパスワードは必ずメモしてください。

+
使用しているブリッジモデルに対応する _ATTO FibreBridge Installation and Operation Manual _ に、使用可能なコマンドおよびその使用方法に関する最新情報が記載されています。

+

NOTE: ATTO FibreBridge 7600N または 7500N では時刻同期は設定しないでください。ATTO FibreBridge 7600N または 7500N の時刻は、 ONTAP でブリッジが検出されたあとにクラスタ時間に設定されます。また、 1 日に 1 回定期的に同期されます。使用されるタイムゾーンは GMT で、変更することはできません。

+
.. IP 管理用に設定する場合は、ブリッジの IP 設定を行います。
+
Quicknav ユーティリティなしで IP アドレスを設定するには、 FibreBridge に対するシリアル接続が必要です。

+
CLI を使用する場合は、次のコマンドを実行する必要があります。

+
'*set ipaddress mp1_ip-address*'

+
'*set ipsubnetmask mp1_subnet-mask_*

+
*set ipgateway mp1x.x.x.x*

+
*set ipdhcp mp1 disabled*

+
`*set ethernetspeed mp1 1000*`

.. ブリッジ名を設定します。
+
ブリッジ名は、 MetroCluster 構成内でそれぞれ一意である必要があります。

+
各サイトの 1 つのスタックグループのブリッジ名の例：

+
*** bridge_A_1a
*** bridge_A_1b
*** bridge_B_1a
*** bridge_B_1b
+
CLI を使用する場合は、次のコマンドを実行する必要があります。

+
*set bridgename _bridgename _ *`



.. ONTAP 9.4 以前を実行している場合は、ブリッジで SNMP を有効にします。 +`*set snmp enabled*`
+
ONTAP 9.5 以降を実行しているシステムでは、インバンド管理を使用してイーサネットポートではなく FC ポート経由でブリッジにアクセスできます。ONTAP 9.8 以降では、インバンド管理のみがサポートされ、 SNMP 管理は廃止されています。



. ブリッジの FC ポートを設定します。
+
.. ブリッジ FC ポートのデータ速度を設定します。
+
サポートされる FC データ速度は、モデルブリッジによって異なります。

+
*** FibreBridge 7600 ブリッジは、最大 32 、 16 、または 8Gbps をサポートします。
*** FibreBridge 7500 ブリッジは、最大 16 、 8 、または 4Gbps をサポートします。
*** FibreBridge 6500 ブリッジは、最大 8 、 4 、または 2Gbps をサポートします。
+

NOTE: 選択できる FCDataRate の速度は、ブリッジポートを接続するブリッジとスイッチの両方でサポートされる最大速度以下です。ケーブルでの接続距離が SFP およびその他のハードウェアの制限を超えないようにしてください。

+
CLI を使用する場合は、次のコマンドを実行する必要があります。

+
'*set FCDataRate_port-number port-speed_*



.. FibreBridge 7500N / 6500N ブリッジを設定する場合は、ポートが使用する接続モードを ptp に設定します。
+

NOTE: FibreBridge 7600N ブリッジを設定する場合、 FCConnMode の設定は不要です。

+
CLI を使用する場合は、次のコマンドを実行する必要があります。

+
'*set FCConnMode_port-number_ptc*

.. FibreBridge 7600N / 7500N ブリッジを設定する場合は、 FC2 ポートを設定または無効にする必要があります。
+
*** 2 番目のポートを使用する場合は、 FC2 ポートについて同じ手順を繰り返す必要があります。
*** 2 番目のポートを使用しない場合は、ポート +`*FCPortDisable_port-number_*` を無効にする必要があります


.. FibreBridge 7600N / 7500N ブリッジを設定する場合は、未使用の SAS ポートを無効にします： +`*SAPortDisable_SAS-port_*`
+

NOTE: SAS ポート A~D はデフォルトで有効になります。使用していない SAS ポートを無効にする必要があります。SAS ポート A のみを使用している場合は、 SAS ポート B 、 C 、および D を無効にする必要があります。



. ブリッジへのアクセスを保護し、ブリッジの設定を保存します。
+
.. コントローラのプロンプトで ' ブリッジのステータスを確認します *storage bridge show *
+
出力には、保護されていないブリッジが表示されます。

.. セキュリティ保護されていないブリッジのポートのステータスを確認します :`*info*`
+
出力には、イーサネットポート MP1 と MP2 のステータスが表示されます。

.. イーサネットポート MP1 がイネーブルの場合は、 +`*set EthernetPort mp1 disabled*` コマンドを実行します
+

NOTE: イーサネットポート MP2 も有効になっている場合は、ポート MP2 について前の手順を繰り返します。

.. ブリッジの設定を保存します。
+
次のコマンドを実行する必要があります。

+
'*SaveConfiguration*'

+
「 * FirmwareRestart * 」と入力します

+
ブリッジを再起動するように求められます。



. 各ブリッジの FibreBridge ファームウェアを更新します。
+
新しいブリッジのタイプがパートナーブリッジと同じ場合は、パートナーブリッジと同じファームウェアにアップグレードします。新しいブリッジのタイプがパートナーブリッジと異なる場合は、ブリッジと ONTAP のバージョンでサポートされている最新のファームウェアにアップグレードします。MetroCluster メンテナンスガイドの「 FibreBridge ブリッジのファームウェアの更新」のセクションを参照してください。

. SAS ケーブルと FC ケーブルを新しいブリッジの同じポートに再接続します。
+
新しいブリッジが FibreBridge 7600N / 7500N の場合は、ブリッジをシェルフスタックの上部または下部に接続するケーブルを交換する必要があります。FibreBridge 6500N ブリッジでは SAS ケーブルを使用していましたが、 FibreBridge 7600N / 7500N ブリッジの接続には Mini-SAS ケーブルが必要です。

+

NOTE: ポートを接続する前に、 10 秒以上待機します。SAS ケーブルのコネクタは、誤挿入を防ぐキーイングが施されているため、正しい向きで SAS ポートに取り付けるとカチッとはまり、ディスクシェルフの SAS ポートの LNK LED が緑色に点灯します。ディスクシェルフの場合は、 SAS ケーブルのコネクタをプルタブ（コネクタの下側）を下にして挿入します。コントローラの場合は、プラットフォームのモデルによって SAS ポートの向きが異なるため、 SAS ケーブルのコネクタの正しい向きもそれに応じて異なります。

. 各ブリッジが、ブリッジの接続先のすべてのディスクドライブとディスクシェルフを認識できることを確認します。
+
|===
| 使用する手段 | 作業 


 a| 
ATTO ExpressNAV の GUI
 a| 
.. サポートされている Web ブラウザで、ブリッジの IP アドレスをブラウザのアドレスバーに入力します。
+
ATTO FibreBridge のホームページに移動し、リンクが表示されます。

.. リンクをクリックし、ブリッジを設定するときに指定したユーザ名とパスワードを入力します。
+
ATTO FibreBridge のステータスページが開き、左側にメニューが表示されます。

.. メニューの「 * 詳細設定 * 」をクリックします。
.. 接続されているデバイスを表示します :+`*sastargets*`
.. [Submit （送信） ] をクリックします。




 a| 
シリアルポート接続
 a| 
接続されているデバイスを表示します。

'*sastargets*'

|===
+
出力には、ブリッジが接続されているデバイス（ディスクおよびディスクシェルフ）が表示されます。出力行には行番号が振られているため、デバイスの台数を簡単に把握できます。

+

NOTE: 出力の先頭に response truncated というテキストが表示される場合は、 Telnet を使用してブリッジに接続し、 sastargets コマンドを使用して、すべての出力を確認できます。

+
次の出力は、 10 本のディスクが接続されていることを示します。

+
[listing]
----
Tgt VendorID ProductID        Type        SerialNumber
  0 NETAPP   X410_S15K6288A15 DISK        3QP1CLE300009940UHJV
  1 NETAPP   X410_S15K6288A15 DISK        3QP1ELF600009940V1BV
  2 NETAPP   X410_S15K6288A15 DISK        3QP1G3EW00009940U2M0
  3 NETAPP   X410_S15K6288A15 DISK        3QP1EWMP00009940U1X5
  4 NETAPP   X410_S15K6288A15 DISK        3QP1FZLE00009940G8YU
  5 NETAPP   X410_S15K6288A15 DISK        3QP1FZLF00009940TZKZ
  6 NETAPP   X410_S15K6288A15 DISK        3QP1CEB400009939MGXL
  7 NETAPP   X410_S15K6288A15 DISK        3QP1G7A900009939FNTT
  8 NETAPP   X410_S15K6288A15 DISK        3QP1FY0T00009940G8PA
  9 NETAPP   X410_S15K6288A15 DISK        3QP1FXW600009940VERQ
----
. コマンド出力で、スタック内の該当するすべてのディスクおよびディスクシェルフにブリッジが接続されていることを確認します。
+
|===


| 出力結果 | 作業 


 a| 
正解です
 a| 
手順を繰り返します xref:task_replace_a_sle_fc_to_sas_bridge.html[SLE FC を SAS ブリッジに置き換えます] 残りの各ブリッジ。



 a| 
不正解です
 a| 
.. SAS ケーブルに緩みがないか確認するか、手順を繰り返して SAS ケーブル接続を修正します xref:task_replace_a_sle_fc_to_sas_bridge.html[SLE FC を SAS ブリッジに置き換えます]。
.. 手順を繰り返します xref:task_replace_a_sle_fc_to_sas_bridge.html[SLE FC を SAS ブリッジに置き換えます]。


|===
. ブリッジがファブリック接続 MetroCluster 構成に含まれている場合は、この手順の最初で無効にした FC スイッチポートを再度有効にします。
+
このポートはブリッジに接続されている必要があります。

. 両方のコントローラモジュールのシステムコンソールで、すべてのコントローラモジュールが新しいブリッジを介してディスクシェルフにアクセスできる（つまりシステムがマルチパス HA 用に接続されている）ことを確認します。
+
'*run local sysconfig *

+

NOTE: システムで検出が完了するまで、 1 分程度かかる場合があります。

+
出力がマルチパス HA を示していない場合は、新しいブリッジを介してアクセスできないディスクドライブがあるため、 SAS と FC のケーブル接続を修正する必要があります。

+
次の出力は、システムがマルチパス HA 用に接続されていることを示しています。

+
[listing]
----
NetApp Release 8.3.2: Tue Jan 26 01:41:49 PDT 2016
System ID: 1231231231 (node_A_1); partner ID: 4564564564 (node_A_2)
System Serial Number: 700000123123 (node_A_1); partner Serial Number: 700000456456 (node_A_2)
System Rev: B0
System Storage Configuration: Multi-Path HA
System ACP Connectivity: NA
----
+

IMPORTANT: システムがマルチパス HA 構成で接続されていないと、ブリッジを再起動したときに、ディスクドライブへのアクセスが原因で失われて、複数のディスクがパニック状態になることがあります。

. ONTAP 9.4 以前を実行している場合は、ブリッジが SNMP 用に設定されていることを確認します。
+
ブリッジの CLI を使用している場合は、次のコマンドを実行します。

+
[listing]
----
get snmp
----
. ONTAP クラスタのプロンプトで、ブリッジをヘルスモニタの対象に追加します。
+
.. 使用している ONTAP のバージョンに対応したコマンドを使用して、ブリッジを追加します。
+
|===
| ONTAP バージョン | コマンドを実行します 


 a| 
9.5 以降
 a| 
'*storage bridge add -address 0.0.0.0 -managed-by in-band-name_bridge-name_*



 a| 
9.4 以前
 a| 
`* storage bridge add-address_bridge-ip-address_-name_bridge-name_*`

|===
.. ブリッジが追加され、正しく設定されていることを確認します。 +`* storage bridge show *`
+
ポーリング間隔に応じて、すべてのデータが反映されるまで 15 分程度かかる場合があります。ONTAP ヘルスモニタは、「ステータス」列の値が「 OK 」で、ワールドワイド名（ WWN ）などのその他の情報が表示されている場合、ブリッジに接続して監視できます。

+
次の例は、 FC-to-SAS ブリッジが設定されていることを示しています。

+
[listing]
----
controller_A_1::> storage bridge show

Bridge              Symbolic Name Is Monitored  Monitor Status  Vendor Model                Bridge WWN
------------------  ------------- ------------  --------------  ------ -----------------    ----------
ATTO_10.10.20.10  atto01        true          ok              Atto   FibreBridge 7500N   	20000010867038c0
ATTO_10.10.20.11  atto02        true          ok              Atto   FibreBridge 7500N   	20000010867033c0
ATTO_10.10.20.12  atto03        true          ok              Atto   FibreBridge 7500N   	20000010867030c0
ATTO_10.10.20.13  atto04        true          ok              Atto   FibreBridge 7500N   	2000001086703b80

4 entries were displayed

 controller_A_1::>
----


. ONTAP で MetroCluster 構成の動作を確認します。
+
.. システムがマルチパスかどうかを確認します。 +`* node run -node -name_sysconfig -a *`
.. 両方のクラスタにヘルス・アラートがないかどうかを確認します +`* system health alert show *`
.. MetroCluster 構成と動作モードが正常であることを確認します :+`* MetroCluster show*`
.. MetroCluster チェック :+`* MetroCluster check run*` を実行します
.. MetroCluster チェックの結果を表示します :+`* MetroCluster check show*`
.. スイッチにヘルス・アラートがあるかどうかを確認します（ある場合）： +`* storage switch show *`
.. Config Advisor を実行します。
+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["ネットアップのダウンロード： Config Advisor"]

.. Config Advisor の実行後、ツールの出力を確認し、推奨される方法で検出された問題に対処します。




* 関連情報 *

xref:concept_in_band_management_of_the_fc_to_sas_bridges.adoc[FC-to-SAS ブリッジのインバンド管理]



== FibreBridge 7500N と 7600N ブリッジのホットスワップ

[role="lead"]
FibreBridge 7500N ブリッジと 7600N ブリッジをホットスワップできます。

IP 管理ではなくブリッジのインバンド管理を使用する場合は、該当する手順に記載されているように、イーサネットポートと IP を設定する手順を省略できます。


NOTE: ONTAP 9.8 以降では '*storage bridge *' コマンドは '*system bridge *' に置き換えられています以下の手順は '*storage bridge *' コマンドを示していますが 'ONTAP 9.8 以降を実行している場合は '*system bridge *' コマンドを使用することをお勧めします

.手順
. ブリッジがファブリック接続 MetroCluster 構成に含まれている場合は、ブリッジの FC ポートに接続しているすべてのスイッチポートを無効にします。
. ONTAP クラスタのプロンプトで、メンテナンス中のブリッジをヘルスモニタの対象から削除します。
+
.. ブリッジ +`* storage bridge remove-name_bridge-name_*` を削除します
.. 監視中のブリッジのリストを表示し、削除したブリッジが含まれていないことを確認します。 +`* storage bridge show *`


. 自身の適切な接地対策を行います
. ブリッジに接続されている電源ケーブルを外して、ブリッジの電源をオフにします。
. 古いブリッジに接続されているケーブルを外します。
+
各ケーブルが接続されていたポートをメモしておいてください。

. ラックから古いブリッジを取り外します。
. 新しいブリッジをラックに取り付けます。
. 電源コードとシールド付きイーサネットケーブルを再接続します。
+

IMPORTANT: SAS / FC ケーブルはまだ再接続しないでください。

. ブリッジを電源に接続し、電源をオンにします。
+
ブリッジの準備完了を示す LED が点灯し、ブリッジの電源投入時自己診断テストが完了したことを示すまで、 30 秒ほどかかる場合があります。

. インバンド管理用に設定する場合は、 FibreBridge RS-232 シリアルポートから PC のシリアル（ COM ）ポートにケーブルを接続します。
+
シリアル接続は初期設定と ONTAP によるインバンド管理に使用され、 FC ポートを使用してブリッジの監視と管理を行うことができます。

. インバンド管理用に設定する場合は、 FibreBridge RS-232 シリアルポートから PC のシリアル（ COM ）ポートにケーブルを接続します。
+
シリアル接続は初期設定と ONTAP によるインバンド管理に使用され、 FC ポートを使用してブリッジの監視と管理を行うことができます。

. IP 管理用に設定する場合は、使用しているブリッジモデルの ATTO FibreBridge Installation and Operation Manual _ のセクション 2.0 の手順に従って、各ブリッジのイーサネット管理 1 ポートを設定します。
+
ONTAP 9.5 以降を実行しているシステムでは、インバンド管理を使用してイーサネットポートではなく FC ポート経由でブリッジにアクセスできます。ONTAP 9.8 以降では、インバンド管理のみがサポートされ、 SNMP 管理は廃止されています。

+
QuickNAV を実行してイーサネット管理ポートを設定すると、イーサネットケーブルで接続されているイーサネット管理ポートのみが設定されます。たとえば、イーサネット管理 2 ポートも設定する場合は、イーサネットケーブルをポート 2 に接続して QuickNAV を実行する必要があります。

. ブリッジを設定します。
+
指定するユーザ名とパスワードは必ずメモしてください。

+
使用しているブリッジモデルに対応する _ATTO FibreBridge Installation and Operation Manual _ に、使用可能なコマンドおよびその使用方法に関する最新情報が記載されています。

+

NOTE: FibreBridge 7600N では時刻同期は設定しないでください。FibreBridge 7600N の時刻は、 ONTAP でブリッジが検出されたあとにクラスタ時間に設定されます。また、 1 日に 1 回定期的に同期されます。使用されるタイムゾーンは GMT で、変更することはできません。

+
.. IP 管理用に設定する場合は、ブリッジの IP 設定を行います。
+
Quicknav ユーティリティなしで IP アドレスを設定するには、 FibreBridge に対するシリアル接続が必要です。

+
CLI を使用する場合は、次のコマンドを実行する必要があります。

+
'*set ipaddress mp1_ip-address_*

+
'*set ipsubnetmask mp1_subnet-mask_*

+
*set ipgateway mp1x.x.x.x*

+
*set ipdhcp mp1 disabled*

+
`*set ethernetspeed mp1 1000*`

.. ブリッジ名を設定します。
+
ブリッジ名は、 MetroCluster 構成内でそれぞれ一意である必要があります。

+
各サイトの 1 つのスタックグループのブリッジ名の例：

+
*** bridge_A_1a
*** bridge_A_1b
*** bridge_B_1a
*** bridge_B_1b
+
CLI を使用する場合は、次のコマンドを実行する必要があります。

+
`*set bridgename "_bridgename _*`



.. ONTAP 9.4 以前を実行している場合は、ブリッジで SNMP を有効にします。 +`*set snmp enabled*`
+
ONTAP 9.5 以降を実行しているシステムでは、インバンド管理を使用してイーサネットポートではなく FC ポート経由でブリッジにアクセスできます。ONTAP 9.8 以降では、インバンド管理のみがサポートされ、 SNMP 管理は廃止されています。



. ブリッジの FC ポートを設定します。
+
.. ブリッジ FC ポートのデータ速度を設定します。
+
サポートされる FC データ速度は、モデルブリッジによって異なります。

+
*** FibreBridge 7600 ブリッジは、最大 32 、 16 、または 8Gbps をサポートします。
*** FibreBridge 7500 ブリッジは、最大 16 、 8 、または 4Gbps をサポートします。
*** FibreBridge 6500 ブリッジは、最大 8 、 4 、または 2Gbps をサポートします。
+

NOTE: 選択できる FCDataRate の速度は、ブリッジポートを接続するコントローラモジュールまたはスイッチのブリッジ / FC ポートの両方でサポートされる最大速度以下です。ケーブルでの接続距離が SFP およびその他のハードウェアの制限を超えないようにしてください。





+
CLI を使用する場合は、次のコマンドを実行する必要があります。「 * set FCDataRate_port_number port-speed_*

+
.. FC2 ポートを設定または無効にする必要があります。
+
*** 2 番目のポートを使用する場合は、 FC2 ポートについて同じ手順を繰り返す必要があります。
*** 2 番目のポートを使用しない場合は、未使用のポートを無効にする必要があります。 +`*FCPortDisable port-number*` 次の例は、 FC ポート 2 を無効にする方法を示しています。
+
[listing]
----
`FCPortDisable 2`

Fibre Channel Port 2 has been disabled.
----


.. 未使用の SAS ポートを無効にします :+`*SASortDisable_SAS-port_*`
+

NOTE: SAS ポート A~D はデフォルトで有効になります。使用していない SAS ポートを無効にする必要があります。

+
SAS ポート A のみを使用している場合は、 SAS ポート B 、 C 、および D を無効にする必要があります。次の例では、 SAS ポート B を無効にしていますSAS ポート C および D についても、同じように無効にする必要があります。

+
[listing]
----
`SASPortDisable b`

SAS Port B has been disabled.
----


. ブリッジへのアクセスを保護し、ブリッジの設定を保存します。
+
.. コントローラのプロンプトで ' ブリッジのステータスを確認します *storage bridge show *
+
出力には、保護されていないブリッジが表示されます。

.. セキュリティ保護されていないブリッジのポートのステータスを確認します :`*info*`
+
出力には、イーサネットポート MP1 と MP2 のステータスが表示されます。

.. イーサネットポート MP1 がイネーブルの場合は、 +`*set EthernetPort mp1 disabled*` コマンドを実行します
+

NOTE: イーサネットポート MP2 も有効になっている場合は、ポート MP2 について前の手順を繰り返します。

.. ブリッジの設定を保存します。
+
次のコマンドを実行する必要があります： +

+
'*SaveConfiguration*'

+
「 * FirmwareRestart * 」と入力します

+
ブリッジを再起動するように求められます。



. 各ブリッジの FibreBridge ファームウェアを更新します。
+
xref:task_update_firmware_on_a_fibrebridge_bridge_parent_topic.adoc[ONTAP 9.4 以降を実行している構成での FibreBridge 7600N / 7500N ブリッジのファームウェアの更新]

. SAS ケーブルと FC ケーブルを新しいブリッジの同じポートに再接続します。
+

NOTE: ポートを接続する前に、 10 秒以上待機します。SAS ケーブルのコネクタは、誤挿入を防ぐキーイングが施されているため、正しい向きで SAS ポートに取り付けるとカチッとはまり、ディスクシェルフの SAS ポートの LNK LED が緑色に点灯します。ディスクシェルフの場合は、 SAS ケーブルのコネクタをプルタブ（コネクタの下側）を下にして挿入します。コントローラの場合は、プラットフォームのモデルによって SAS ポートの向きが異なるため、 SAS ケーブルのコネクタの正しい向きもそれに応じて異なります。

. 各ブリッジが、ブリッジの接続先のすべてのディスクドライブとディスクシェルフを認識できることを確認します。
+
'*sastargets*'

+
出力には、ブリッジが接続されているデバイス（ディスクおよびディスクシェルフ）が表示されます。出力行には行番号が振られているため、デバイスの台数を簡単に把握できます。

+
次の出力は、 10 本のディスクが接続されていることを示します。

+
[listing]
----
Tgt VendorID ProductID        Type        SerialNumber
  0 NETAPP   X410_S15K6288A15 DISK        3QP1CLE300009940UHJV
  1 NETAPP   X410_S15K6288A15 DISK        3QP1ELF600009940V1BV
  2 NETAPP   X410_S15K6288A15 DISK        3QP1G3EW00009940U2M0
  3 NETAPP   X410_S15K6288A15 DISK        3QP1EWMP00009940U1X5
  4 NETAPP   X410_S15K6288A15 DISK        3QP1FZLE00009940G8YU
  5 NETAPP   X410_S15K6288A15 DISK        3QP1FZLF00009940TZKZ
  6 NETAPP   X410_S15K6288A15 DISK        3QP1CEB400009939MGXL
  7 NETAPP   X410_S15K6288A15 DISK        3QP1G7A900009939FNTT
  8 NETAPP   X410_S15K6288A15 DISK        3QP1FY0T00009940G8PA
  9 NETAPP   X410_S15K6288A15 DISK        3QP1FXW600009940VERQ
----
. コマンド出力で、スタック内の該当するすべてのディスクおよびディスクシェルフにブリッジが接続されていることを確認します。
+
|===
| 出力結果 | 作業 


 a| 
正解です
 a| 
残りの各ブリッジについて、同じ手順を繰り返します。



 a| 
不正解です
 a| 
.. SAS ケーブルに緩みがないか確認するか、手順を繰り返して SAS ケーブル接続を修正します xref:task_replace_a_sle_fc_to_sas_bridge.adocSTEP_CD84065D8F3B43F192919B0CD6FDC1A6[task_replace_a_sle_data_bridge_md#step_CD84065D8F3B43F192919B0CD6FDC1A6]。
.. 前の手順を繰り返します。


|===
. ブリッジがファブリック接続 MetroCluster 構成に含まれている場合は、この手順の最初で無効にした FC スイッチポートを再度有効にします。
+
このポートはブリッジに接続されている必要があります。

. 両方のコントローラモジュールのシステムコンソールで、すべてのコントローラモジュールが新しいブリッジを介してディスクシェルフにアクセスできる（つまりシステムがマルチパス HA 用に接続されている）ことを確認します。
+
'*run local sysconfig *

+

NOTE: システムで検出が完了するまで、 1 分程度かかる場合があります。

+
出力がマルチパス HA を示していない場合は、新しいブリッジを介してアクセスできないディスクドライブがあるため、 SAS と FC のケーブル接続を修正する必要があります。

+
次の出力は、システムがマルチパス HA 用に接続されていることを示しています。

+
[listing]
----
NetApp Release 8.3.2: Tue Jan 26 01:41:49 PDT 2016
System ID: 1231231231 (node_A_1); partner ID: 4564564564 (node_A_2)
System Serial Number: 700000123123 (node_A_1); partner Serial Number: 700000456456 (node_A_2)
System Rev: B0
System Storage Configuration: Multi-Path HA
System ACP Connectivity: NA
----
+

IMPORTANT: システムがマルチパス HA 構成で接続されていないと、ブリッジを再起動したときに、ディスクドライブへのアクセスが原因で失われて、複数のディスクがパニック状態になることがあります。

. ONTAP 9.4 以前を実行している場合は、ブリッジが SNMP 用に設定されていることを確認します。
+
ブリッジの CLI を使用している場合は、次のコマンドを実行します。

+
[listing]
----
get snmp
----
. ONTAP クラスタのプロンプトで、ブリッジをヘルスモニタの対象に追加します。
+
.. 使用している ONTAP のバージョンに対応したコマンドを使用して、ブリッジを追加します。
+
|===
| ONTAP バージョン | コマンドを実行します 


 a| 
9.5 以降
 a| 
'*storage bridge add -address 0.0.0.0 -managed-by in-band-name_bridge-name_*



 a| 
9.4 以前
 a| 
`* storage bridge add-address_bridge-ip-address_-name_bridge-name_*`

|===
.. ブリッジが追加され、正しく設定されていることを確認します。 +`* storage bridge show *`
+
ポーリング間隔に応じて、すべてのデータが反映されるまで 15 分程度かかる場合があります。ONTAP ヘルスモニタは、「ステータス」列の値が「 OK 」で、ワールドワイド名（ WWN ）などのその他の情報が表示されている場合、ブリッジに接続して監視できます。

+
次の例は、 FC-to-SAS ブリッジが設定されていることを示しています。

+
[listing]
----
controller_A_1::> storage bridge show

Bridge              Symbolic Name Is Monitored  Monitor Status  Vendor Model                Bridge WWN
------------------  ------------- ------------  --------------  ------ -----------------    ----------
ATTO_10.10.20.10  atto01        true          ok              Atto   FibreBridge 7500N   	20000010867038c0
ATTO_10.10.20.11  atto02        true          ok              Atto   FibreBridge 7500N   	20000010867033c0
ATTO_10.10.20.12  atto03        true          ok              Atto   FibreBridge 7500N   	20000010867030c0
ATTO_10.10.20.13  atto04        true          ok              Atto   FibreBridge 7500N   	2000001086703b80

4 entries were displayed

 controller_A_1::>
----


. ONTAP で MetroCluster 構成の動作を確認します。
+
.. システムがマルチパスかどうかを確認します。 +`* node run -node -name_sysconfig -a *`
.. 両方のクラスタにヘルス・アラートがないかどうかを確認します +`* system health alert show *`
.. MetroCluster 構成と動作モードが正常であることを確認します :+`* MetroCluster show*`
.. MetroCluster チェック :+`* MetroCluster check run*` を実行します
.. MetroCluster チェックの結果を表示します： +
+
「 * MetroCluster check show * 」と表示されます

.. スイッチにヘルス・アラートがあるかどうかを確認します（ある場合）： +`* storage switch show *`
.. Config Advisor を実行します。
+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["ネットアップのダウンロード： Config Advisor"]

.. Config Advisor の実行後、ツールの出力を確認し、推奨される方法で検出された問題に対処します。




* 関連情報 *

xref:concept_in_band_management_of_the_fc_to_sas_bridges.adoc[FC-to-SAS ブリッジのインバンド管理]



== FibreBridge 6500N ブリッジと FibreBridge 7600N / 7500N ブリッジのホットスワップ

[role="lead"]
FibreBridge 6500N ブリッジと FibreBridge 7600N / 7500N ブリッジをホットスワップして、障害が発生したブリッジを交換したり、ファブリック接続またはブリッジ接続 MetroCluster 構成のブリッジをアップグレードしたりできます。

* この手順は、 1 つの FibreBridge 6500N ブリッジを 1 つの FibreBridge 7600N / 7500N ブリッジとホットスワップするためのものです。
* FibreBridge 6500N ブリッジと FibreBridge 7600N / 7500N ブリッジをホットスワップする場合は、 FibreBridge 7600N / 7500N ブリッジの FC ポートと SAS ポートをそれぞれ 1 つだけ使用する必要があります。
* IP 管理ではなくブリッジのインバンド管理を使用する場合は、該当する手順に記載されているように、イーサネットポートと IP を設定する手順を省略できます。



IMPORTANT: FibreBridge 6500N ブリッジペアの両方をホットスワップする場合は、を使用する必要があります xref:task_fb_consolidate_replace_a_pair_of_fibrebridge_6500n_bridges_with_7500n_bridges.adoc[複数のストレージスタックを統合] ゾーニング手順については手順を参照してください。両方の FibreBridge 6500N ブリッジを交換することで、 FibreBridge 7600N / 7500N ブリッジの追加ポートを活用できます。


NOTE: ONTAP 9.8 以降では '*storage bridge *' コマンドは '*system bridge *' に置き換えられています以下の手順は '*storage bridge *' コマンドを示していますが 'ONTAP 9.8 以降を実行している場合は '*system bridge *' コマンドを使用することをお勧めします

.手順
. 次のいずれかを実行します。
+
** 障害が発生したブリッジがファブリック接続 MetroCluster 構成に含まれている場合は、ブリッジ FC ポートに接続するスイッチポートを無効にします。
** 障害が発生したブリッジがストレッチ MetroCluster 構成である場合は、使用可能ないずれかの FC ポートを使用します。


. ONTAP クラスタのプロンプトで、メンテナンス中のブリッジをヘルスモニタの対象から削除します。
+
.. ブリッジ +`* storage bridge remove-name_bridge-name_*` を削除します
.. 監視中のブリッジのリストを表示し、削除したブリッジが含まれていないことを確認します。 +`* storage bridge show *`


. 自身の適切な接地対策を行います
. ブリッジの電源スイッチをオフにします。
. シェルフから FibreBridge 6500N ブリッジのポートに接続されているケーブルおよび電源ケーブルを外します。
+
各ケーブルが接続されていたポートをメモしておいてください。

. 交換が必要な FibreBridge 6500N ブリッジをラックから取り外します。
. 新しい FibreBridge 7600N / 7500N ブリッジをラックに取り付けます。
. 電源コードを再接続し、必要に応じてシールド付きイーサネットケーブルを再接続します。
+

IMPORTANT: SAS / FC ケーブルはまだ再接続しないでください。

. インバンド管理用に設定する場合は、 FibreBridge RS-232 シリアルポートから PC のシリアル（ COM ）ポートにケーブルを接続します。
+
シリアル接続は初期設定と ONTAP によるインバンド管理に使用され、 FC ポートを使用してブリッジの監視と管理を行うことができます。

. IP 管理用に設定する場合は、イーサネットケーブルを使用して、各ブリッジのイーサネット管理 1 ポートをネットワークに接続します。
+
ONTAP 9.5 以降を実行しているシステムでは、インバンド管理を使用してイーサネットポートではなく FC ポート経由でブリッジにアクセスできます。ONTAP 9.8 以降では、インバンド管理のみがサポートされ、 SNMP 管理は廃止されています。

+
イーサネット管理 1 ポートを使用すると、ブリッジファームウェアを短時間でダウンロードし（ ATTO ExpressNAV または FTP 管理インターフェイスを使用）、コアファイルと抽出ログを取得できます。

. IP 管理用に設定する場合は、使用しているブリッジモデルの ATTO FibreBridge Installation and Operation Manual _ のセクション 2.0 の手順に従って、各ブリッジのイーサネット管理 1 ポートを設定します。
+
ONTAP 9.5 以降を実行しているシステムでは、インバンド管理を使用してイーサネットポートではなく FC ポート経由でブリッジにアクセスできます。ONTAP 9.8 以降では、インバンド管理のみがサポートされ、 SNMP 管理は廃止されています。

+
QuickNAV を実行してイーサネット管理ポートを設定すると、イーサネットケーブルで接続されているイーサネット管理ポートのみが設定されます。たとえば、イーサネット管理 2 ポートも設定する場合は、イーサネットケーブルをポート 2 に接続して QuickNAV を実行する必要があります。

. ブリッジを設定します。
+
古いブリッジから設定情報を取得した場合は、その情報を使用して新しいブリッジを設定します。

+
指定するユーザ名とパスワードは必ずメモしてください。

+
使用しているブリッジモデルに対応する _ATTO FibreBridge Installation and Operation Manual _ に、使用可能なコマンドおよびその使用方法に関する最新情報が記載されています。

+

NOTE: ATTO FibreBridge 7600N または 7500N では時刻同期は設定しないでください。ATTO FibreBridge 7600N または 7500N の時刻は、 ONTAP でブリッジが検出されたあとにクラスタ時間に設定されます。また、 1 日に 1 回定期的に同期されます。使用されるタイムゾーンは GMT で、変更することはできません。

+
.. IP 管理用に設定する場合は、ブリッジの IP 設定を行います。
+
Quicknav ユーティリティなしで IP アドレスを設定するには、 FibreBridge に対するシリアル接続が必要です。

+
CLI を使用する場合は、次のコマンドを実行する必要があります。

+
'*set ipaddress mp1_ip-address_*

+
'*set ipsubnetmask mp1_subnet-mask_*

+
*set ipgateway mp1x.x.x.x*

+
*set ipdhcp mp1 disabled*

+
`*set ethernetspeed mp1 1000*`

.. ブリッジ名を設定します。
+
ブリッジ名は、 MetroCluster 構成内でそれぞれ一意である必要があります。

+
各サイトの 1 つのスタックグループのブリッジ名の例：

+
*** bridge_A_1a
*** bridge_A_1b
*** bridge_B_1a
*** bridge_B_1b
+
CLI を使用する場合は、次のコマンドを実行する必要があります。

+
`*set bridgename _bridgename _ *`



.. ONTAP 9.4 以前を実行している場合は、ブリッジで SNMP を有効にします。 +`*set snmp enabled*`
+
ONTAP 9.5 以降を実行しているシステムでは、インバンド管理を使用してイーサネットポートではなく FC ポート経由でブリッジにアクセスできます。ONTAP 9.8 以降では、インバンド管理のみがサポートされ、 SNMP 管理は廃止されています。



. ブリッジの FC ポートを設定します。
+
.. ブリッジ FC ポートのデータ速度を設定します。
+
サポートされる FC データ速度は、モデルブリッジによって異なります。

+
*** FibreBridge 7600 ブリッジは、最大 32 、 16 、または 8Gbps をサポートします。
*** FibreBridge 7500 ブリッジは、最大 16 、 8 、または 4Gbps をサポートします。
*** FibreBridge 6500 ブリッジは、最大 8 、 4 、または 2Gbps をサポートします。
+

NOTE: 選択できる FCDataRate の速度は、ブリッジポートを接続するブリッジとスイッチの両方でサポートされる最大速度以下です。ケーブルでの接続距離が SFP およびその他のハードウェアの制限を超えないようにしてください。

+
CLI を使用する場合は、次のコマンドを実行する必要があります。

+
'*set FCDataRate_port-number port-speed_*



.. FibreBridge 7500N / 6500N ブリッジを設定する場合は、ポートが使用する接続モードを ptp に設定します。
+

NOTE: FibreBridge 7600N ブリッジを設定する場合、 FCConnMode の設定は不要です。

+
CLI を使用する場合は、次のコマンドを実行する必要があります。

+
'*set FCConnMode_port-number_ptc*

.. FibreBridge 7600N / 7500N ブリッジを設定する場合は、 FC2 ポートを設定または無効にする必要があります。
+
*** 2 番目のポートを使用する場合は、 FC2 ポートについて同じ手順を繰り返す必要があります。
*** 2 番目のポートを使用しない場合は、ポート +`*FCPortDisable_port-number_*` を無効にする必要があります


.. FibreBridge 7600N / 7500N ブリッジを設定する場合は、未使用の SAS ポートを無効にします： +`*SAPortDisable_SAS-port_*`
+

NOTE: SAS ポート A~D はデフォルトで有効になります。使用していない SAS ポートを無効にする必要があります。SAS ポート A のみを使用している場合は、 SAS ポート B 、 C 、および D を無効にする必要があります。



. ブリッジへのアクセスを保護し、ブリッジの設定を保存します。
+
.. コントローラのプロンプトで、ブリッジのステータスを確認します。 +`*storage bridge show*`
+
出力には、保護されていないブリッジが表示されます。

.. セキュリティ保護されていないブリッジのポートのステータスを確認します :`*info*`
+
出力には、イーサネットポート MP1 と MP2 のステータスが表示されます。

.. イーサネットポート MP1 がイネーブルの場合は、 +`*set EthernetPort mp1 disabled*` コマンドを実行します
+

NOTE: イーサネットポート MP2 も有効になっている場合は、ポート MP2 について前の手順を繰り返します。

.. ブリッジの設定を保存します。
+
次のコマンドを実行する必要があります。

+
'*SaveConfiguration*'

+
「 * FirmwareRestart * 」と入力します

+
ブリッジを再起動するように求められます。



. FibreBridge 7600N / 7500N ブリッジの健全性監視を有効にします。
. 各ブリッジの FibreBridge ファームウェアを更新します。
+
新しいブリッジのタイプがパートナーブリッジと同じ場合は、パートナーブリッジと同じファームウェアにアップグレードします。新しいブリッジのタイプがパートナーブリッジと異なる場合は、ブリッジと ONTAP のバージョンでサポートされている最新のファームウェアにアップグレードします。MetroCluster メンテナンスガイドの「 FibreBridge ブリッジのファームウェアの更新」のセクションを参照してください。

. SAS ケーブルと FC ケーブルを新しいブリッジの SAS A ポートと Fibre Channel 1 ポートに再接続します。
+
SAS ポートは、 FibreBridge 6500N ブリッジが接続されていたシェルフポートにケーブル接続する必要があります。

+
FC ポートは、 FibreBridge 6500N ブリッジが接続されていたスイッチポートまたはコントローラポートにケーブル接続する必要があります。

+

NOTE: コネクタをポートに無理に押し込まないでください。Mini-SAS ケーブルは、誤挿入を防ぐキーイングが施されているため、正しい向きで SAS ポートに取り付けるとカチッとはまり、ディスクシェルフの SAS ポートの LNK LED が緑色に点灯します。ディスクシェルフの場合は、 SAS ケーブルのコネクタをプルタブ（コネクタの下側）を下にして挿入します。コントローラの場合、 SAS ポートの向きはプラットフォームのモデルによって異なるため、 SAS ケーブルのコネクタの正しい向きは異なります。

. ブリッジが接続先のすべてのディスクドライブとディスクシェルフを認識できることを確認します。
+
|===
| 使用する手段 | 作業 


 a| 
ATTO ExpressNAV の GUI
 a| 
.. サポートされている Web ブラウザで、ブリッジの IP アドレスをブラウザのアドレスバーに入力します。
+
ATTO FibreBridge のホームページに移動し、リンクが表示されます。

.. リンクをクリックし、ブリッジを設定するときに指定したユーザ名とパスワードを入力します。
+
ATTO FibreBridge のステータスページが開き、左側にメニューが表示されます。

.. メニューの「 * 詳細設定 * 」をクリックします。
.. 次のコマンドを入力し、 *Submit* をクリックして、ブリッジで認識されるディスクのリストを表示します。 +`*sastargets*`




 a| 
シリアルポート接続
 a| 
ブリッジから認識されているディスクのリストを表示します。

'*sastargets*'

|===
+
出力には、ブリッジが接続されているデバイス（ディスクおよびディスクシェルフ）が表示されます。出力行には行番号が振られているため、デバイスの台数を簡単に把握できます。たとえば、次の出力は、 10 本のディスクが接続されていることを示しています。

+
[listing]
----

Tgt VendorID ProductID        Type        SerialNumber
  0 NETAPP   X410_S15K6288A15 DISK        3QP1CLE300009940UHJV
  1 NETAPP   X410_S15K6288A15 DISK        3QP1ELF600009940V1BV
  2 NETAPP   X410_S15K6288A15 DISK        3QP1G3EW00009940U2M0
  3 NETAPP   X410_S15K6288A15 DISK        3QP1EWMP00009940U1X5
  4 NETAPP   X410_S15K6288A15 DISK        3QP1FZLE00009940G8YU
  5 NETAPP   X410_S15K6288A15 DISK        3QP1FZLF00009940TZKZ
  6 NETAPP   X410_S15K6288A15 DISK        3QP1CEB400009939MGXL
  7 NETAPP   X410_S15K6288A15 DISK        3QP1G7A900009939FNTT
  8 NETAPP   X410_S15K6288A15 DISK        3QP1FY0T00009940G8PA
  9 NETAPP   X410_S15K6288A15 DISK        3QP1FXW600009940VERQ
----
+

NOTE: 出力の先頭に「 respondse truncated 」というテキストが表示される場合は、 Telnet を使用してブリッジにアクセスし、同じコマンドを入力すると、すべての出力を確認できます。

. コマンド出力で、スタック内の必要なすべてのディスクおよびディスクシェルフにブリッジが接続されていることを確認します。
+
|===
| 出力結果 | 作業 


 a| 
正解です
 a| 
手順を繰り返します xref:task_replace_a_sle_fc_to_sas_bridge.html[SLE FC を SAS ブリッジに置き換えます] 残りの各ブリッジで使用します。 ]



 a| 
不正解です
 a| 
.. SAS ケーブルに緩みがないか確認するか、手順を繰り返して SAS ケーブル接続を修正します xref:task_replace_a_sle_fc_to_sas_bridge.adocSTEP_CD84065D8F3B43F192919B0CD6FDC1A6[task_replace_a_sle_data_bridge_md#step_CD84065D8F3B43F192919B0CD6FDC1A6]。
.. 手順を繰り返します xref:task_replace_a_sle_fc_to_sas_bridge.html[SLE FC を SAS ブリッジに置き換えます] 残りの各ブリッジ。 ]


|===
. ブリッジに接続する FC スイッチポートを再度有効にします。
. 両方のコントローラのシステムコンソールで、すべてのコントローラが新しいブリッジ経由でディスクシェルフにアクセスできること（システムがマルチパス HA 用にケーブル接続されていること）を確認します。「 run local sysconfig 」
+

NOTE: システムで検出が完了するまで、 1 分程度かかる場合があります。

+
たとえば、次の出力は、システムがマルチパス HA 用に接続されていることを示しています。

+
[listing]
----
NetApp Release 8.3.2: Tue Jan 26 01:23:24 PST 2016
System ID: 1231231231 (node_A_1); partner ID: 4564564564 (node_A_2)
System Serial Number: 700000123123 (node_A_1); partner Serial Number: 700000456456 (node_A_2)
System Rev: B0
System Storage Configuration: Multi-Path HA
System ACP Connectivity: NA
----
+
混在パスまたはシングルパスの HA 構成であることがコマンド出力で示された場合は、新しいブリッジ経由でアクセスできないディスクドライブがあるため、 SAS ケーブルと FC ケーブルの接続を修正する必要があります。

+

IMPORTANT: システムがマルチパス HA 構成で接続されていないと、ブリッジを再起動したときに、ディスクドライブへのアクセスが原因で失われて、複数のディスクがパニック状態になることがあります。

. ONTAP クラスタのプロンプトで、ブリッジをヘルスモニタの対象に追加します。
+
.. 使用している ONTAP のバージョンに対応したコマンドを使用して、ブリッジを追加します。
+
|===


| ONTAP バージョン | コマンドを実行します 


 a| 
9.5 以降
 a| 
'*storage bridge add -address 0.0.0.0 -managed-by in-band-name_bridge-name_*



 a| 
9.4 以前
 a| 
`* storage bridge add-address_bridge-ip-address_-name_bridge-name_*`

|===
.. ブリッジが追加され、正しく設定されていることを確認します。 +`* storage bridge show *`
+
ポーリング間隔に応じて、すべてのデータが反映されるまで 15 分程度かかる場合があります。ONTAP ヘルスモニタは、「ステータス」列の値が「 OK 」で、ワールドワイド名（ WWN ）などのその他の情報が表示されている場合、ブリッジに接続して監視できます。

+
次の例は、 FC-to-SAS ブリッジが設定されていることを示しています。

+
[listing]
----
controller_A_1::> storage bridge show

Bridge              Symbolic Name Is Monitored  Monitor Status  Vendor Model                Bridge WWN
------------------  ------------- ------------  --------------  ------ -----------------    ----------
ATTO_10.10.20.10  atto01        true          ok              Atto   FibreBridge 7500N   	20000010867038c0
ATTO_10.10.20.11  atto02        true          ok              Atto   FibreBridge 7500N   	20000010867033c0
ATTO_10.10.20.12  atto03        true          ok              Atto   FibreBridge 7500N   	20000010867030c0
ATTO_10.10.20.13  atto04        true          ok              Atto   FibreBridge 7500N   	2000001086703b80

4 entries were displayed

 controller_A_1::>
----


. ONTAP で MetroCluster 構成の動作を確認します。
+
.. システムがマルチパスかどうかを確認します。
+
'*node run -node node_name sysconfig -a *

.. 両方のクラスタにヘルス・アラートがないかどうかを確認します +`* system health alert show *`
.. MetroCluster 構成と運用モードが正常な状態であることを確認します。
+
「 * MetroCluster show * 」と入力します

.. MetroCluster チェックを実行します。
+
「 * MetroCluster check run * 」のようになります

.. MetroCluster チェックの結果を表示します。
+
「 * MetroCluster check show * 」と表示されます

.. スイッチにヘルスアラートがないかどうかを確認します（ある場合）。
+
「 * storage switch show * 」と表示されます

.. Config Advisor を実行します。
+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["ネットアップのダウンロード： Config Advisor"]

.. Config Advisor の実行後、ツールの出力を確認し、推奨される方法で検出された問題に対処します。


. 障害のある部品は、キットに付属する RMA 指示書に従ってネットアップに返却してください。
+
テクニカルサポートにお問い合わせください https://mysupport.netapp.com/site/global/dashboard["ネットアップサポート"]RMA 番号を確認する場合や、交換用手順にサポートが必要な場合は、日本国内サポート用電話番号：国内フリーダイヤル 0066-33-123-265 または 0066-33-821-274 （国際フリーフォン 800-800-80-800 も使用可能）までご連絡ください。



* 関連情報 *

xref:concept_in_band_management_of_the_fc_to_sas_bridges.adoc[FC-to-SAS ブリッジのインバンド管理]
