---
permalink: maintain/task_upgrade_rcf_files_on_mcc_ip_switches.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, upgrade, rcf, files, ip, switches 
summary: MetroCluster IP スイッチ上の RCF ファイルのアップグレードが必要になる場合があります。たとえば、 ONTAP のアップグレードまたはスイッチファームウェアのアップグレードには、どちらも新しい RCF ファイルが必要です。 
---
= MetroCluster IP スイッチの RCF ファイルをアップグレードします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
MetroCluster IPスイッチのリファレンス構成ファイル（RCF）のアップグレードが必要になる場合があります。たとえば、スイッチで実行しているRCFのバージョンが、ONTAPのバージョン、スイッチのファームウェアのバージョン、またはその両方でサポートされていない場合などです。

.作業を開始する前に
* 新しいスイッチファームウェアをインストールする場合は、 RCF ファイルをアップグレードする前にスイッチファームウェアをインストールする必要があります。
* RCFをアップグレードする前に、をlink:task_upgrade_firmware_on_mcc_ip_switches.html["RCFのサポート状況の確認"]参照してください。
* link:enable-console-logging-before-maintenance.html["コンソールログを有効にする"] このタスクを実行する前に。


.このタスクについて
* この手順を実行すると、RCFファイルをアップグレードするスイッチでトラフィックが中断されます。トラフィックは、新しいRCFファイルが適用されると再開されます。
* Switch_A_1、Switch_B_1、Switch_A_2、Switch_B_2の手順を一度に1つずつ実行します。


.手順
. 構成の健全性を確認
+
.. MetroCluster コンポーネントが正常であることを確認します。
+
「 MetroCluster check run 」のようになります

+
[listing]
----
cluster_A::*> metrocluster check run

----


+
この処理はバックグラウンドで実行されます。

+
.. MetroCluster check run オペレーションが完了したら ' MetroCluster check show を実行して結果を表示します
+
約 5 分後に、次の結果が表示されます。

+
[listing]
----
-----------
::*> metrocluster check show

Component           Result
------------------- ---------
nodes               ok
lifs                ok
config-replication  ok
aggregates          ok
clusters            ok
connections         ok
volumes             ok
7 entries were displayed.
----
.. 実行中の MetroCluster チェック処理のステータスを確認します。
+
MetroCluster オペレーション履歴 show -job-id 38`

.. ヘルスアラートがないことを確認します。
+
「 system health alert show 」というメッセージが表示されます



. 新しい RCF ファイルを適用するための IP スイッチを準備します。
+
スイッチベンダーの手順に従います。

+
** link:../install-ip/task_switch_config_broadcom.html#resetting-the-broadcom-ip-switch-to-factory-defaults["Broadcom IP スイッチを工場出荷時のデフォルトにリセットします"]
** link:../install-ip/task_switch_config_cisco.html#resetting-the-cisco-ip-switch-to-factory-defaults["Cisco IPスイッチを工場出荷時のデフォルトにリセットする"]
** link:../install-ip/task_switch_config_nvidia.html#reset-the-nvidia-ip-sn2100-switch-to-factory-defaults["NVIDIA IP SN2100スイッチを工場出荷時のデフォルトにリセット"]


. スイッチベンダーに応じて、IP RCFファイルをダウンロードしてインストールします。
+
** link:../install-ip/task_switch_config_broadcom.html#downloading-and-installing-the-broadcom-rcf-files["Broadcom IPのRCFファイルをダウンロードしてインストールする"]
** link:../install-ip/task_switch_config_cisco.html#downloading-and-installing-the-cisco-ip-rcf-files["Cisco IP RCFファイルのダウンロードとインストール"]
** link:../install-ip/task_switch_config_nvidia.html#download-and-install-the-nvidia-rcf-files["NVIDIA IP RCFファイルのダウンロードとインストール"]
+

NOTE: L2共有またはL3ネットワーク構成を使用している場合は、お客様の中間スイッチまたはお客様のスイッチでISLポートの調整が必要になることがあります。スイッチポートモードが「access」モードから「trunk」モードに変わることがあります。スイッチ_A_1とB_1の間のネットワーク接続が完全に機能していて、ネットワークが正常である場合にのみ、2つ目のスイッチペア（A_2、B_2）のアップグレードに進みます。




