---
permalink: maintain/task_hot_add_a_stack_to_exist_7500n_pair.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, hot, add, stack, sas, disk, shelves, existing, pair, fibrebridge, bridge 
summary: 使用可能なポートがある既存の FibreBridge 7500N ブリッジペアに SAS ディスクシェルフのスタックをホットアドできます。 
---
= 既存の FibreBridge 7500N ブリッジペアに SAS ディスクシェルフのスタックをホットアドする
:icons: font
:imagesdir: ../media/


[role="lead"]
使用可能なポートがある既存の FibreBridge 7500N ブリッジペアに SAS ディスクシェルフのスタックをホットアドできます。

* 最新のディスクファームウェアとディスクシェルフファームウェアをダウンロードしておく必要があります。
* MetroCluster 構成内のすべてのディスクシェルフ（新しいシェルフと既存のシェルフの両方）で同じファームウェアバージョンを実行している必要があります。
+
https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware["ネットアップのダウンロード：ディスクドライブファームウェア"]

+
https://mysupport.netapp.com/site/downloads/firmware/disk-shelf-firmware["ネットアップのダウンロード：ディスクシェルフファームウェア"]

* FibreBridge 7500N ブリッジが接続されており、使用可能な SAS ポートがある必要があります。


この手順は、推奨されるブリッジ管理インターフェイスである ATTO ExpressNAV GUI と ATTO QuickNAV ユーティリティを使用していることを前提としています。

ATTO ExpressNAV GUI は、ブリッジの設定および管理、ブリッジファームウェアの更新に使用できます。ATTO QuickNAV ユーティリティは、ブリッジのイーサネット管理 1 ポートの設定に使用できます。

必要に応じて、他の管理インターフェイスを使用できます。オプションには、シリアルポートまたは Telnet を使用したブリッジの設定と管理、イーサネット管理 1 ポートの設定、および FTP を使用したブリッジファームウェアの更新があります。これらの管理インターフェイスのいずれかを選択した場合は、に記載された該当する要件を満たす必要があります xref:reference_requirements_for_using_other_interfaces_to_configure_and_manage_fibrebridge_bridges.adoc[その他のブリッジ管理インターフェイス]。


IMPORTANT: SAS ケーブルを間違ったポートに挿入した場合は、ケーブルを SAS ポートから取り外すときに、 120 秒以上待機してから別の SAS ポートに接続する必要があります。そうしないと、ケーブルが別のポートに移されたことがシステムで認識されません。

.手順
. 自身の適切な接地対策を行います
. いずれかのコントローラのコンソールで、システムでディスクの自動割り当てが有効になっていることを確認します。
+
「 * storage disk option show * 」を入力します

+
Auto Assign 列には、ディスクの自動割り当てが有効になっているかどうかが示されます。

+
[listing]
----

Node        BKg. FW. Upd.  Auto Copy   Auto Assign  Auto Assign Policy
----------  -------------  ----------  -----------  ------------------
node_A_1             on           on           on           default
node_A_2             on           on           on           default
2 entries were displayed.
----
. 新しいスタックのスイッチポートを無効にします。
. 各ブリッジの FibreBridge ファームウェアを更新します。
+
新しいブリッジのタイプがパートナーブリッジと同じ場合は、パートナーブリッジと同じファームウェアにアップグレードします。新しいブリッジのタイプがパートナーブリッジと異なる場合は、ブリッジと ONTAP のバージョンでサポートされている最新のファームウェアにアップグレードします。MetroCluster メンテナンスガイドの「 FibreBridge ブリッジのファームウェアの更新」のセクションを参照してください。

. ペアの各ブリッジで、新しいスタックに接続する SAS ポートを有効にします。
+
'*SAPortEnable_portlet_letter_*

+
両方のブリッジで同じ SAS ポート（ B 、 C 、または D ）を使用する必要があります。

. 設定を保存し、各ブリッジをリブートします。
+
「 * SaveConfiguration Restart * 」と入力します

. ディスクシェルフをブリッジにケーブル接続します。
+
.. 各スタックのディスクシェルフをデイジーチェーン接続します。
+
ディスクシェルフのデイジーチェーン接続の詳細については、使用しているディスクシェルフモデルの Installation and Service Guide を参照してください。

.. ディスクシェルフの各スタックで、最初のシェルフの IOM A を FibreBridge A の SAS ポート A にケーブル接続し、最後のシェルフの IOM B を FibreBridge B の SAS ポート A にケーブル接続します
+
https://docs.netapp.com/us-en/ontap-metrocluster/install-fc/index.html["ファブリック接続 MetroCluster のインストールと設定"]

+
https://docs.netapp.com/us-en/ontap-metrocluster/install-stretch/index.html["ストレッチ MetroCluster のインストールと設定"]

+
各ブリッジには、ディスクシェルフのスタックへのパスが 1 つあります。ブリッジ A は最初のシェルフ経由でスタックの A 側に接続し、ブリッジ B は最後のシェルフ経由でスタックの B 側に接続します。

+

NOTE: ブリッジの SAS ポート B は無効になっています。



. 各ブリッジが、ブリッジの接続先のすべてのディスクドライブとディスクシェルフを検出できることを確認します。
+
|===
| 使用する手段 | 作業 


 a| 
ATTO ExpressNAV の GUI
 a| 
.. サポートされている Web ブラウザで、ブリッジの IP アドレスをブラウザのアドレスバーに入力します。
+
ATTO FibreBridge のホームページに移動し、リンクが表示されます。

.. リンクをクリックし、ブリッジを設定するときに指定したユーザ名とパスワードを入力します。
+
ATTO FibreBridge のステータスページが開き、左側にメニューが表示されます。

.. メニューの「 * 詳細設定 * 」をクリックします。
.. 接続されているデバイスを表示します。
+
'*sastargets*'

.. [Submit （送信） ] をクリックします。




 a| 
シリアルポート接続
 a| 
接続されているデバイスを表示します。

'*sastargets*'

|===
+
出力には、ブリッジが接続されているデバイス（ディスクおよびディスクシェルフ）が表示されます。出力行には行番号が振られているため、デバイスの台数を簡単に把握できます。

+

NOTE: 出力の先頭に「 respondse truncated 」というテキストが表示される場合は、 Telnet を使用してブリッジに接続し、「 astargets 」コマンドを使用してすべての出力を表示できます。

+
次の出力は、 10 本のディスクが接続されていることを示します。

+
[listing]
----
Tgt VendorID ProductID        Type        SerialNumber
  0 NETAPP   X410_S15K6288A15 DISK        3QP1CLE300009940UHJV
  1 NETAPP   X410_S15K6288A15 DISK        3QP1ELF600009940V1BV
  2 NETAPP   X410_S15K6288A15 DISK        3QP1G3EW00009940U2M0
  3 NETAPP   X410_S15K6288A15 DISK        3QP1EWMP00009940U1X5
  4 NETAPP   X410_S15K6288A15 DISK        3QP1FZLE00009940G8YU
  5 NETAPP   X410_S15K6288A15 DISK        3QP1FZLF00009940TZKZ
  6 NETAPP   X410_S15K6288A15 DISK        3QP1CEB400009939MGXL
  7 NETAPP   X410_S15K6288A15 DISK        3QP1G7A900009939FNTT
  8 NETAPP   X410_S15K6288A15 DISK        3QP1FY0T00009940G8PA
  9 NETAPP   X410_S15K6288A15 DISK        3QP1FXW600009940VERQ
----
. コマンド出力で、スタック内の該当するすべてのディスクおよびディスクシェルフにブリッジが接続されていることを確認します。
+
|===
| 出力結果 | 作業 


 a| 
正解です
 a| 
残りの各ブリッジについて、同じ手順を繰り返します。



 a| 
不正解です
 a| 
.. SAS ケーブルに緩みがないか確認するか、手順を繰り返してディスクシェルフをブリッジに接続し、 SAS ケーブル接続を修正します。
.. 残りの各ブリッジについて、同じ手順を繰り返します。


|===
. 使用している構成、スイッチモデル、および FC-to-SAS ブリッジモデルに対応した表に記載されているケーブルを使用して、各ブリッジをローカルの FC スイッチにケーブル接続します。
+
[NOTE]
====
次の表に示すように、 Brocade スイッチと Cisco スイッチでは使用するポート番号が異なります

** Brocade スイッチでは ' 最初のポートに 0 という番号が付けられます
** シスコ製スイッチでは、最初のポートには「 1 」という番号が付けられています。


====
+
|===
13+| 両方の FC ポート（ FC1 または FC2 ）を使用する FibreBridge 7500N または 7600N を使用する構成 


13+| DR グループ 1 


3+|  2+| Brocade 6505 2+| Brocade 6510 、 Brocade DCX 8510-8 2+| Brocade 6520 2+| Brocade G620 、 Brocade G620 -1 、 Brocade G630 、 Brocade G630-1 2+| Brocade G720 


2+| コンポーネント | ポート | スイッチ 1 | スイッチ 2 | スイッチ 1 | スイッチ 2 | スイッチ 1 | スイッチ 2 | スイッチ 1 | スイッチ 2 | スイッチ 1 | スイッチ 2 


 a| 
スタック 1
 a| 
bridge_x_1a
 a| 
fc1
 a| 
8.
 a| 
 a| 
8.
 a| 
 a| 
8.
 a| 
 a| 
8.
 a| 
 a| 
10.
 a| 



 a| 
FC2
 a| 
-
 a| 
8.
 a| 
-
 a| 
8.
 a| 
-
 a| 
8.
 a| 
-
 a| 
8.
 a| 
-
 a| 
10.



 a| 
bridge_x_1B
 a| 
fc1
 a| 
9.
 a| 
-
 a| 
9.
 a| 
-
 a| 
9.
 a| 
-
 a| 
9.
 a| 
-
 a| 
11.
 a| 
-



 a| 
FC2
 a| 
-
 a| 
9.
 a| 
-
 a| 
9.
 a| 
-
 a| 
9.
 a| 
-
 a| 
9.
 a| 
-
 a| 
11.



 a| 
スタック 2
 a| 
bridge_x_2a
 a| 
fc1
 a| 
10.
 a| 
-
 a| 
10.
 a| 
-
 a| 
10.
 a| 
-
 a| 
10.
 a| 
-
 a| 
14
 a| 
-



 a| 
FC2
 a| 
-
 a| 
10.
 a| 
-
 a| 
10.
 a| 
-
 a| 
10.
 a| 
-
 a| 
10.
 a| 
-
 a| 
14



 a| 
bridge_x_2B
 a| 
fc1
 a| 
11.
 a| 
-
 a| 
11.
 a| 
-
 a| 
11.
 a| 
-
 a| 
11.
 a| 
-
 a| 
17
 a| 
-



 a| 
FC2
 a| 
-
 a| 
11.
 a| 
-
 a| 
11.
 a| 
-
 a| 
11.
 a| 
-
 a| 
11.
 a| 
-
 a| 
17



 a| 
スタック 3
 a| 
bridge_x_3a
 a| 
fc1
 a| 
12.
 a| 
-
 a| 
12.
 a| 
-
 a| 
12.
 a| 
-
 a| 
12.
 a| 
-
 a| 
18
 a| 
-



 a| 
FC2
 a| 
-
 a| 
12.
 a| 
-
 a| 
12.
 a| 
-
 a| 
12.
 a| 
-
 a| 
12.
 a| 
-
 a| 
18



 a| 
bridge_x_3B
 a| 
fc1
 a| 
13
 a| 
-
 a| 
13
 a| 
-
 a| 
13
 a| 
-
 a| 
13
 a| 
-
 a| 
19
 a| 
-



 a| 
FC2
 a| 
-
 a| 
13
 a| 
-
 a| 
13
 a| 
-
 a| 
13
 a| 
-
 a| 
13
 a| 
-
 a| 
19



 a| 
スタック y
 a| 
bridge_x_ya
 a| 
fc1
 a| 
14
 a| 
-
 a| 
14
 a| 
-
 a| 
14
 a| 
-
 a| 
14
 a| 
-
 a| 
20
 a| 
-



 a| 
FC2
 a| 
-
 a| 
14
 a| 
-
 a| 
14
 a| 
-
 a| 
14
 a| 
-
 a| 
14
 a| 
-
 a| 
20



 a| 
bridge_x_YB
 a| 
fc1
 a| 
15
 a| 
-
 a| 
15
 a| 
-
 a| 
15
 a| 
-
 a| 
15
 a| 
-
 a| 
21
 a| 
-



 a| 
FC2
 a| 
--

-- a| 
15
 a| 
--

-- a| 
15
 a| 
--

-- a| 
15
 a| 
-
 a| 
15
 a| 
-
 a| 
21



 a| 

NOTE: G620 、 G630 、 G620 -1 、および G630-1 スイッチでは、追加のブリッジをポート 16 、 17 、 20 、および 21 にケーブル接続できます。

|===
+
|===
11+| 両方の FC ポート（ FC1 または FC2 ）を使用する FibreBridge 7500N または 7600N を使用する構成 


11+| DR グループ 2 


3+|  2+| Brocade G620 、 Brocade G620 -1 、 Brocade G630 、 Brocade G630-1 2+| Brocade 6510 、 Brocade DCX 8510-8 2+| Brocade 6520 2+| Brocade G720 


2+| コンポーネント | ポート | スイッチ 1 | スイッチ 2 | スイッチ 1 | スイッチ 2 | スイッチ 1 | スイッチ 2 | スイッチ 1 | スイッチ 2 


 a| 
スタック 1
 a| 
bridge_x_51A
 a| 
fc1
 a| 
26
 a| 
-
 a| 
32
 a| 
-
 a| 
56
 a| 
-
 a| 
32
 a| 
-



 a| 
FC2
 a| 
-
 a| 
26
 a| 
-
 a| 
32
 a| 
-
 a| 
56
 a| 
-
 a| 
32



 a| 
bridge_x_51b
 a| 
fc1
 a| 
27
 a| 
-
 a| 
33
 a| 
-
 a| 
57
 a| 
-
 a| 
33
 a| 
-



 a| 
FC2
 a| 
-
 a| 
27
 a| 
-
 a| 
33
 a| 
-
 a| 
57
 a| 
-
 a| 
33



 a| 
スタック 2
 a| 
bridge_x_52A
 a| 
fc1
 a| 
30
 a| 
-
 a| 
34
 a| 
-
 a| 
58
 a| 
-
 a| 
34
 a| 
-



 a| 
FC2
 a| 
-
 a| 
30
 a| 
-
 a| 
34
 a| 
-
 a| 
58
 a| 
-
 a| 
34



 a| 
bridge_x_52b
 a| 
fc1
 a| 
31.
 a| 
-
 a| 
35
 a| 
-
 a| 
59
 a| 
-
 a| 
35
 a| 
-



 a| 
FC2
 a| 
-
 a| 
31.
 a| 
-
 a| 
35
 a| 
-
 a| 
59
 a| 
-
 a| 
35



 a| 
スタック 3
 a| 
bridge_x_53a
 a| 
fc1
 a| 
32
 a| 
-
 a| 
36
 a| 
-
 a| 
60
 a| 
-
 a| 
36
 a| 
-



 a| 
FC2
 a| 
-
 a| 
32
 a| 
-
 a| 
36
 a| 
-
 a| 
60
 a| 
-
 a| 
36



 a| 
bridge_x_53B
 a| 
fc1
 a| 
33
 a| 
-
 a| 
37
 a| 
-
 a| 
61
 a| 
-
 a| 
37
 a| 
-



 a| 
FC2
 a| 
-
 a| 
33
 a| 
-
 a| 
37
 a| 
-
 a| 
61
 a| 
-
 a| 
37



 a| 
スタック y
 a| 
bridge_x_5ya
 a| 
fc1
 a| 
34
 a| 
-
 a| 
38
 a| 
-
 a| 
62
 a| 
-
 a| 
38
 a| 
-



 a| 
FC2
 a| 
-
 a| 
34
 a| 
-
 a| 
38
 a| 
-
 a| 
62
 a| 
-
 a| 
38



 a| 
bridge_x_5yb
 a| 
fc1
 a| 
35
 a| 
-
 a| 
39
 a| 
-
 a| 
63
 a| 
-
 a| 
39
 a| 
-



 a| 
FC2
 a| 
-
 a| 
35
 a| 
-
 a| 
39
 a| 
-
 a| 
63
 a| 
-
 a| 
39



 a| 

NOTE: G620 、 G630 、 G620 -1 、および G-630-1 スイッチでは、追加のブリッジをポート 36~39 にケーブル接続できます。

|===
+
|===
12+| FibreBridge 6500N ブリッジ、または 1 つの FC ポート（ FC1 または FC2 ）のみを使用する FibreBridge 7500N または 7600N を使用する構成 


12+| DR グループ 1 


2+|  2+| Brocade 6505 2+| Brocade 6510 、 Brocade DCX 8510-8 2+| Brocade 6520 2+| Brocade G620 、 Brocade G620 -1 、 Brocade G630 、 Brocade G630-1 2+| Brocade G720 


| コンポーネント | ポート | スイッチ 1 | スイッチ 2 | スイッチ 1 | スイッチ 2 | スイッチ 1 | スイッチ 2 | スイッチ 1 | スイッチ 2 | スイッチ 1 | スイッチ 2 


 a| 
スタック 1
 a| 
bridge_x_1a
 a| 
8.
 a| 
 a| 
8.
 a| 
 a| 
8.
 a| 
 a| 
8.
 a| 
 a| 
10.
 a| 



 a| 
bridge_x_1b
 a| 
-
 a| 
8.
 a| 
-
 a| 
8.
 a| 
-
 a| 
8.
 a| 
-
 a| 
8.
 a| 
-
 a| 
10.



 a| 
スタック 2
 a| 
bridge_x_2a
 a| 
9.
 a| 
-
 a| 
9.
 a| 
-
 a| 
9.
 a| 
-
 a| 
9.
 a| 
-
 a| 
11.
 a| 
-



 a| 
bridge_x_2b
 a| 
-
 a| 
9.
 a| 
-
 a| 
9.
 a| 
-
 a| 
9.
 a| 
-
 a| 
9.
 a| 
-
 a| 
11.



 a| 
スタック 3
 a| 
bridge_x_3a
 a| 
10.
 a| 
-
 a| 
10.
 a| 
-
 a| 
10.
 a| 
-
 a| 
10.
 a| 
-
 a| 
14
 a| 
-



 a| 
bridge_x_4b
 a| 
-
 a| 
10.
 a| 
-
 a| 
10.
 a| 
-
 a| 
10.
 a| 
-
 a| 
10.
 a| 
-
 a| 
14



 a| 
スタック y
 a| 
bridge_x_ya
 a| 
11.
 a| 
-
 a| 
11.
 a| 
-
 a| 
11.
 a| 
-
 a| 
11.
 a| 
-
 a| 
15
 a| 
-



 a| 
bridge_x_YB
 a| 
-
 a| 
11.
 a| 
-
 a| 
11.
 a| 
-
 a| 
11.
 a| 
-
 a| 
11.
 a| 
-
 a| 
15



 a| 

NOTE: G620 、 G630 、 G620 -1 、および G630-1 スイッチでは、追加のブリッジをポート 12~17 、 20 、および 21 にケーブル接続できます。追加のブリッジは、ポート 16-17 、 20 、および 21 G720 スイッチにケーブル接続できます。

|===
+
|===
10+| FibreBridge 6500N ブリッジ、または 1 つの FC ポート（ FC1 または FC2 ）のみを使用する FibreBridge 7500N または 7600N を使用する構成 


10+| DR グループ 2 


2+|  2+| Brocade G720 2+| Brocade G620 、 Brocade G620 -1 、 Brocade G630 、 Brocade G630-1 2+| Brocade 6510 、 Brocade DCX 8510-8 2+| Brocade 6520 


 a| 
スタック 1
 a| 
bridge_x_51A
 a| 
32
 a| 
-
 a| 
26
 a| 
-
 a| 
32
 a| 
-
 a| 
56
 a| 
-



 a| 
bridge_x_51b
 a| 
-
 a| 
32
 a| 
-
 a| 
26
 a| 
-
 a| 
32
 a| 
-
 a| 
56



 a| 
スタック 2
 a| 
bridge_x_52A
 a| 
33
 a| 
-
 a| 
27
 a| 
-
 a| 
33
 a| 
-
 a| 
57
 a| 
-



 a| 
bridge_x_52b
 a| 
-
 a| 
33
 a| 
-
 a| 
27
 a| 
-
 a| 
33
 a| 
-
 a| 
57



 a| 
スタック 3
 a| 
bridge_x_53a
 a| 
34
 a| 
-
 a| 
30
 a| 
-
 a| 
34
 a| 
-
 a| 
58
 a| 
-



 a| 
bridge_x_54b
 a| 
-
 a| 
34
 a| 
-
 a| 
30
 a| 
-
 a| 
34
 a| 
-
 a| 
58



 a| 
スタック y
 a| 
bridge_x_ya
 a| 
35
 a| 
-
 a| 
31.
 a| 
-
 a| 
35
 a| 
-
 a| 
59
 a| 
-



 a| 
bridge_x_YB
 a| 
-
 a| 
35
 a| 
-
 a| 
31.
 a| 
-
 a| 
35
 a| 
-
 a| 
59



 a| 

NOTE: G620 、 G630 、 G620 -1 、および G630-1 スイッチでは、追加のブリッジをポート 32~39 にケーブル接続できます。G720 スイッチでは、追加のブリッジをポート 36-39 にケーブル接続できます。

|===
. システムコンソールからディスクドライブファームウェアを最新バージョンに更新します。
+
'*disk_fw_updat*

+
このコマンドは両方のコントローラで実行する必要があります。

+
https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware["ネットアップのダウンロード：ディスクドライブファームウェア"]

. ダウンロードしたファームウェアの手順に従って、ディスクシェルフファームウェアを最新バージョンに更新します。
+
手順のコマンドは、どちらのコントローラのシステムコンソールでも実行できます。

+
https://mysupport.netapp.com/site/downloads/firmware/disk-shelf-firmware["ネットアップのダウンロード：ディスクシェルフファームウェア"]

. システムでディスクの自動割り当てが有効になっていない場合は、ディスクドライブの所有権を割り当てます。
+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-psmg/home.html["ディスクおよびアグリゲートの管理"]

+

NOTE: ディスクシェルフの 1 つのスタックの所有権を複数のコントローラに分割する場合は、ディスク所有権を割り当てる前にディスクの自動割り当てを無効にする必要があります（クラスタ内の両方のノードから「 storage disk option modify -autoassign off * 」）。 そうしないと、いずれかのディスクドライブを割り当てたときに、残りのディスクドライブが同じコントローラおよびプールに自動的に割り当てられる可能性があります。

+

NOTE: ディスクドライブファームウェアとディスクシェルフファームウェアが更新され、このタスクの検証手順が完了するまで、アグリゲートまたはボリュームにディスクドライブを追加しないでください。

. 新しいスタックのスイッチポートを有効にします。
. ONTAP で MetroCluster 構成の動作を確認します。
+
.. システムがマルチパスかどうかを確認します。
+
'*node run -node node_name sysconfig -a *

.. ヘルスアラートがないかどうかを両方のクラスタで確認します。
+
「 * system health alert show * 」というメッセージが表示されます

.. MetroCluster 構成と運用モードが正常な状態であることを確認します。
+
「 * MetroCluster show * 」と入力します

.. MetroCluster チェックを実行します。
+
「 * MetroCluster check run * 」のようになります

.. MetroCluster チェックの結果を表示します。
+
「 * MetroCluster check show * 」と表示されます

.. スイッチにヘルスアラートがないかどうかを確認します（ある場合）。
+
「 * storage switch show * 」と表示されます

.. Config Advisor を実行します。
+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["ネットアップのダウンロード： Config Advisor"]

.. Config Advisor の実行後、ツールの出力を確認し、推奨される方法で検出された問題に対処します。


. 必要に応じて、パートナーサイトに対してこの手順を繰り返します。

