---
permalink: maintain/task_do_not_use_for_9_8_and_later_reconfigure_the_fc_switch_layout_for_ontap_9_1_or_later.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, reconfigure, fc, switch, layout, configured 
summary: 既存の FC スイッチレイアウトが ONTAP 9.1 より前に構成されていた場合は、ポートレイアウトを再構成して、最新のリファレンス構成ファイル（ RCF ）を適用する必要があります。この手順は、 MetroCluster FC 構成にのみ適用されます。 
---
= ONTAP 9.x より前に設定された FC スイッチレイアウトの再設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
既存の FC スイッチレイアウトが ONTAP 9.1 より前に構成されていた場合は、ポートレイアウトを再構成して、最新のリファレンス構成ファイル（ RCF ）を適用する必要があります。この手順は、 MetroCluster FC 構成にのみ適用されます。

ファブリックドメイン内の FC スイッチを特定する必要があります。

管理パスワードと FTP サーバまたは SCP サーバへのアクセスが必要です。

既存の FC スイッチレイアウトが ONTAP 9.1 より前に構成されていた場合は、このタスクを実行する必要があります。ONTAP 9.1 以降用に設定された既存のスイッチレイアウトからアップグレードする場合は、 _not_required です。

この手順はシステムを停止せずに実行でき、ディスクが初期化されている場合は約 4 時間で完了します（ラックとスタックは除く）。



== カスタム AutoSupport メッセージの送信 - スイッチの再設定前

スイッチを再設定する前に、 AutoSupport an 問題 message to notify NetApp technical support that maintenance is maintenance.システム停止が発生したとみなしてテクニカルサポートがケースをオープンしないように、メンテナンスが進行中であることを通知する必要があります。

このタスクは MetroCluster サイトごとに実行する必要があります。

.手順
. クラスタにログインします。
. メンテナンスの開始を通知する AutoSupport メッセージを起動します。
+
「 system node AutoSupport invoke -node * -type all -message MAINT=__ maintenance-window-in-hours __ * 」というメッセージが表示されます

+
maintenance-window-in-hours にはメンテナンス時間の長さを指定します。最大値は 72 時間です。この時間が経過する前にメンテナンスが完了した場合は、メンテナンス期間が終了したことを通知する AutoSupport メッセージを起動できます。

+
「 system node AutoSupport invoke -node * -type all -message MAINT= end 」というメッセージが表示されます

. 同じ手順をパートナーサイトでも実行します。




== MetroCluster 構成の健全性の確認

MetroCluster 構成の健全性をチェックして、正常に動作することを確認する必要があります。

.手順
. MetroCluster コンポーネントが正常であることを確認します。
+
「 MetroCluster check run 」のようになります

+
[listing]
----
cluster_A::*> metrocluster check run

----
+
この処理はバックグラウンドで実行されます。

. MetroCluster check run オペレーションが完了したら ' MetroCluster check show を実行して結果を表示します
+
約 5 分後に、次の結果が表示されます。

+
[listing]
----
-----------
cluster_A::*> metrocluster check show

Last Checked On: 4/7/2019 21:15:05

Component           Result
------------------- ---------
nodes               ok
lifs                ok
config-replication  ok
aggregates          warning
clusters            ok
connections         not-applicable
volumes             ok
7 entries were displayed.
----
. 実行中の MetroCluster チェック処理のステータスを確認するには、次のコマンドを使用します。
+
MetroCluster オペレーション履歴 show -job-id 38`

. ヘルスアラートがないことを確認します。
+
「 system health alert show 」というメッセージが表示されます





== MetroCluster の構成エラーを確認しています

ネットアップサポートサイトで入手できる Config Advisor ツールを使用して、代表的な構成エラーがないかどうかを確認できます。

Config Advisor は、構成の検証や健常性のチェックに使用できるツールです。データ収集とシステム分析のために、セキュアなサイトにもセキュアでないサイトにも導入できます。


NOTE: Config Advisor のサポートには制限があり、オンラインでしか使用できません。

. Config Advisor ツールをダウンロードします。
+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["ネットアップのダウンロード： Config Advisor"^]

. Config Advisor を実行し、出力を確認して推奨された方法で問題に対処します。




== スイッチを永続的に無効にします

ファブリックの構成を変更できるように、ファブリック内のスイッチを永続的に無効にする必要があります。

スイッチを無効にするには、スイッチのコマンドラインでコマンドを実行します。使用するのは ONTAP コマンドではありません。

.手順
. スイッチを永続的に無効にします。
+
** Brocade スイッチを永続的に無効にするには、次のコマンドを使用します。
+
'FC_switch_a_1:admin>switchCfgPersistentDisable'

** 次のコマンドを使用して、 Cisco スイッチを永続的に無効にします。
+
「 vsan [vsna#] suspend` 」







== 新しいケーブルレイアウトの決定

新しいコントローラモジュールおよび新しいディスクシェルフと既存の FC スイッチとのケーブル接続を決定する必要があります。

このタスクは MetroCluster サイトごとに実行する必要があります。

.手順
. 使用 https://docs.netapp.com/us-en/ontap-metrocluster/install-fc/index.html["ファブリック接続 MetroCluster のインストールと設定"^] スイッチタイプのケーブルレイアウトを決定するには、 8 ノード MetroCluster 構成のポート用途を使用します。
+
リファレンス構成ファイル（ RCF ）を使用できるようにするために、 FC スイッチポートの用途がこのガイドに記載されている用途と同じである必要があります。

+

NOTE: RCF を使用できないケーブル接続の場合は、この手順を使用しないでください。





== RCF ファイルの適用およびスイッチの再接続

新しいノードに合わせてスイッチを再設定するためには、適切なリファレンス構成ファイル（ RCF ）を適用する必要があります。RCF ファイルを適用したら、スイッチを再接続できます。

使用する FC スイッチポートは、に記載されている用途と一致する必要があります https://docs.netapp.com/us-en/ontap-metrocluster/install-fc/index.html["ファブリック接続 MetroCluster のインストールと設定"^] RCF を使用できるようにするためです。

.手順
. 使用している構成用の RCF ファイルを探します。
+
使用しているスイッチモデルに対応した RCF ファイルを使用する必要があります。

. ダウンロードページの指示に従って RCF ファイルを適用し、必要に応じて ISL 設定を調整します。
. スイッチの設定が保存されたことを確認します。
. 「新しいケーブルレイアウト」セクションで作成したケーブルレイアウトを使用して、両方の FC-to-SAS ブリッジを FC スイッチにケーブル接続します。
. ポートがオンラインであることを確認します。
+
** Brocade スイッチの場合は 'witchshow' コマンドを使用します
** Cisco スイッチの場合は、「 show interface brief 」コマンドを使用します。


. コントローラの FC-VI ポートとスイッチをケーブル接続します。
. 既存のノードから、 FC-VI ポートがオンラインであることを確認します。
+
MetroCluster インターコネクト・アダプタ・ショー

+
MetroCluster interconnect mirror show





== スイッチを永続的に有効にします

ファブリック内のスイッチを永続的に有効にする必要があります。

.手順
. スイッチを永続的に有効にします。
+
** Brocade スイッチの場合は、「 witchCfgPersistentenable 」コマンドを使用します。
** Cisco スイッチの場合は、 no 'uspend' コマンドを使用します。次のコマンドは Brocade スイッチを永続的に有効にします。
+
[listing]
----
FC_switch_A_1:admin> switchCfgPersistentenable
----
+
Cisco スイッチを有効にするコマンドは次のとおりです。

+
[listing]
----
vsan [vsna #]no suspend
----






== スイッチオーバー、修復、スイッチバックを検証しています

MetroCluster 構成のスイッチオーバー、修復、スイッチバックの処理を検証する必要があります。

. の説明に従って、ネゴシエートスイッチオーバー、修復、スイッチバックを実行します https://docs.netapp.com/us-en/ontap-metrocluster/disaster-recovery/concept_dr_workflow.html["MetroCluster の管理とディザスタリカバリ"^]。

