---
permalink: maintain/task_fb_hot_add_stack_of_shelves_and_bridges.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, hot, add, stack, sas, disk, shelves, bridges, system 
summary:  
---
= MetroCluster システムへの SAS ディスクシェルフとブリッジのスタックのホットアド
:icons: font
:imagesdir: ../media/


[role="lead"]
MetroCluster システムにブリッジを含むスタック全体をホットアド（無停止で追加）できます。FC スイッチに使用可能なポートが必要です。変更を反映するには、スイッチゾーニングを更新する必要があります。

* この手順を使用して、 FibreBridge 7500N / 6500N ブリッジを使用してスタックを追加できます。
* この手順は、推奨されるブリッジ管理インターフェイスである ATTO ExpressNAV GUI と ATTO QuickNAV ユーティリティを使用していることを前提としています。
+
** ATTO ExpressNAV GUI は、ブリッジの設定および管理、ブリッジファームウェアの更新に使用します。ATTO QuickNAV ユーティリティは、ブリッジのイーサネット管理 1 ポートの設定に使用します。
** 必要に応じて、他の管理インターフェイスを使用できます。オプションには、シリアルポートまたは Telnet を使用したブリッジの設定と管理、イーサネット管理 1 ポートの設定、および FTP を使用したブリッジファームウェアの更新があります。これらのいずれかの管理インターフェイスを使用する場合は、の該当する要件をシステムが満たしている必要があります xref:reference_requirements_for_using_other_interfaces_to_configure_and_manage_fibrebridge_bridges.adoc[その他のブリッジ管理インターフェイス]






== SAS ディスクシェルフとブリッジのスタックのホットアドの準備

[role="lead"]
SAS ディスクシェルフとブリッジのペアのスタックのホットアドの準備には、ドキュメントおよびディスクドライブとディスクシェルフのファームウェアのダウンロードが含まれます。

* サポートされている構成である必要があり、サポートされているバージョンの ONTAP が実行されている必要があります。
+
https://mysupport.netapp.com/matrix["NetApp Interoperability Matrix Tool で確認できます"]

* システム内のすべてのディスクドライブとディスクシェルフで最新のファームウェアバージョンが実行されている必要があります。
+
シェルフを追加する前に、 MetroCluster 構成全体でディスクとシェルフのファームウェアを更新しなければならない場合があります。

+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-ug-rdg/home.html["アップグレード、リバート、ダウングレード"]

* 各 FC スイッチで、 1 つの FC ポートを 1 つのブリッジに接続できる必要があります。
+

NOTE: FC スイッチの互換性に応じて FC スイッチのアップグレードが必要になる可能性があります。

* ブリッジの設定に使用するコンピュータでは、 ATTO ExpressNAV GUI （ Internet Explorer 8 または 9 、 Mozilla Firefox 3 ）を使用するために、 ATTO でサポートされている Web ブラウザを実行している必要があります。
+
ATTO Product Release Notes に、サポートされている Web ブラウザの最新のリストが掲載されています。このドキュメントには、の手順内の情報を使用してアクセスできます。



.手順
. ネットアップサポートサイトから次のドキュメントをダウンロードまたは表示します。
+
** https://mysupport.netapp.com/matrix["NetApp Interoperability Matrix Tool で確認できます"]
** 使用しているディスクシェルフモデルの Installation and Service Guide を参照してください。


. ATTO の Web サイトおよびネットアップの Web サイトから必要なデータをダウンロードします。
+
.. ATTO FibreBridge 概要のページに移動します。
.. ATTO FibreBridge 概要のページのリンクを使用して、 ATTO の Web サイトにアクセスし、次の項目をダウンロードします。
+
*** 使用しているブリッジモデルに対応した ATTO FibreBridge Installation and Operation Manual
*** ATTO QuickNAV ユーティリティ（セットアップに使用するコンピュータへ）


.. ATTO FibreBridge 概要のページの末尾にある「 * Continue * 」をクリックして、 ATTO FibreBridge ファームウェアのダウンロードページに移動し、次の手順を実行します。
+
*** ダウンロードページの指示に従って、ブリッジファームウェアファイルをダウンロードします。
+
この手順では、リンク先に記載されている手順のダウンロード部分のみを実行します。各ブリッジでのファームウェアの更新は、で指示されたときにあとから実行します xref:task_fb_hot_add_stack_of_shelves_and_bridges.adoc[シェルフのスタックのホットアド] セクション。

*** ATTO FibreBridge ファームウェアのダウンロードページとリリースノートのコピーを作成し、あとで参照できます。




. 最新のディスクファームウェアとディスクシェルフファームウェアをダウンロードし、あとで参照できるよう、手順のインストールに関する部分をコピーします。
+
MetroCluster 構成内のすべてのディスクシェルフ（新しいシェルフと既存のシェルフの両方）で同じファームウェアバージョンを実行する必要があります。

+

NOTE: この手順では、リンク先に記載されている手順のダウンロード部分のみを実行し、インストール手順をコピーします。各ディスクおよびディスクシェルフでのファームウェアの更新は、で指示されたときにあとから実行します xref:task_fb_hot_add_stack_of_shelves_and_bridges.adoc[シェルフのスタックのホットアド] セクション。

+
.. ディスクファームウェアをダウンロードし、あとで参照できるよう、ディスクファームウェアの説明書をコピーします。
+
https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware["ネットアップのダウンロード：ディスクドライブファームウェア"]

.. ディスクシェルフファームウェアをダウンロードし、あとで参照できるよう、ディスクシェルフファームウェアの説明書をコピーします。
+
https://mysupport.netapp.com/site/downloads/firmware/disk-shelf-firmware["ネットアップのダウンロード：ディスクシェルフファームウェア"]



. 推奨されるブリッジ管理インターフェイスを使用するために必要なハードウェアおよび情報を収集する - ATTO ExpressNAV GUI および ATTO QuickNAV ユーティリティ
+
.. 標準のイーサネットケーブルを用意して、ブリッジのイーサネット管理 1 ポートからネットワークに接続します。
.. ブリッジへのアクセスに使用するデフォルト以外のユーザ名とパスワードを決定します。
+
デフォルトのユーザ名とパスワードを変更することを推奨します。

.. 各ブリッジのイーサネット管理 1 ポートの IP アドレス、サブネットマスク、およびゲートウェイ情報を取得します。
.. セットアップに使用するコンピュータで VPN クライアントを無効にします。
+
アクティブな VPN クライアント原因がブリッジの QuickNAV スキャンに失敗しました。



. ブリッジごとに 4 本のネジを用意して、ブリッジの L 字型ブラケットをラックの前面にフラッシュマウントします。
+
ブリッジ「 L 」ブラケットの開口部は、 19 インチ（ 482.6 mm ）ラックのラック標準 ETA-310-X に準拠しています。

. 必要に応じて、構成に追加する新しいブリッジに合わせて FC スイッチゾーニングを更新します。
+
ネットアップが提供するリファレンス構成ファイルを使用している場合は、すべてのポート用のゾーンが作成されているため、ゾーニングを更新する必要はありません。ブリッジの FC ポートに接続するスイッチポートごとにストレージゾーンが必要です。





== SAS ディスクシェルフとブリッジのスタックのホットアド

[role="lead"]
SAS ディスクシェルフとブリッジのスタックをホットアドして、ブリッジの容量を増やすことができます。

SAS ディスクシェルフとブリッジのスタックをホットアドするためのすべての要件をシステムが満たしている必要があります。

xref:task_fb_hot_add_stack_of_shelves_and_bridges.adoc[SAS ディスクシェルフとブリッジのスタックのホットアドの準備]

* 相互運用性の要件をすべて満たしている場合、 SAS ディスクシェルフとブリッジのスタックのホットアドは無停止の手順となります。
+
https://mysupport.netapp.com/matrix["NetApp Interoperability Matrix Tool で確認できます"]

+
xref:concept_using_the_interoperability_matrix_tool_to_find_mcc_information.adoc[Interoperability Matrix Tool を使用した MetroCluster 情報の検索]

* ブリッジを使用する MetroCluster システムでサポートされている構成はマルチパス HA のみです。
+
両方のコントローラモジュールが、各スタックのディスクシェルフにブリッジ経由でアクセスできる必要があります。

* 各サイトで同数のディスクシェルフをホットアドする必要があります。
* IP 管理ではなくブリッジのインバンド管理を使用する場合は、該当する手順に記載されているように、イーサネットポートと IP を設定する手順を省略できます。



NOTE: ONTAP 9.8 以降では '*storage bridge *' コマンドは '*system bridge *' に置き換えられています以下の手順は '*storage bridge *' コマンドを示していますが 'ONTAP 9.8 以降を実行している場合は '*system bridge *' コマンドを使用することをお勧めします


IMPORTANT: SAS ケーブルを間違ったポートに挿入した場合は、ケーブルを SAS ポートから取り外すときに、 120 秒以上待機してから別の SAS ポートに接続する必要があります。そうしないと、ケーブルが別のポートに移されたことがシステムで認識されません。

.手順
. 自身の適切な接地対策を行います
. いずれかのコントローラモジュールのコンソールで、システムでディスクの自動割り当てが有効になっているかどうかを確認します。
+
「 * storage disk option show * 」を入力します

+
Auto Assign 列には、ディスクの自動割り当てが有効になっているかどうかが示されます。

+
[listing]
----

Node        BKg. FW. Upd.  Auto Copy   Auto Assign  Auto Assign Policy
----------  -------------  ----------  -----------  ------------------
node_A_1             on           on           on           default
node_A_2             on           on           on           default
2 entries were displayed.
----
. 新しいスタックのスイッチポートを無効にします。
. インバンド管理用に設定する場合は、 FibreBridge RS-232 シリアルポートから PC のシリアル（ COM ）ポートにケーブルを接続します。
+
シリアル接続は初期設定と ONTAP によるインバンド管理に使用され、 FC ポートを使用してブリッジの監視と管理を行うことができます。

. IP 管理用に設定する場合は、使用しているブリッジモデルの ATTO FibreBridge Installation and Operation Manual _ のセクション 2.0 の手順に従って、各ブリッジのイーサネット管理 1 ポートを設定します。
+
ONTAP 9.5 以降を実行しているシステムでは、インバンド管理を使用してイーサネットポートではなく FC ポート経由でブリッジにアクセスできます。ONTAP 9.8 以降では、インバンド管理のみがサポートされ、 SNMP 管理は廃止されています。

+
QuickNAV を実行してイーサネット管理ポートを設定すると、イーサネットケーブルで接続されているイーサネット管理ポートのみが設定されます。たとえば、イーサネット管理 2 ポートも設定する場合は、イーサネットケーブルをポート 2 に接続して QuickNAV を実行する必要があります。

. ブリッジを設定します。
+
古いブリッジから設定情報を取得した場合は、その情報を使用して新しいブリッジを設定します。

+
指定するユーザ名とパスワードは必ずメモしてください。

+
使用しているブリッジモデルに対応する _ATTO FibreBridge Installation and Operation Manual _ に、使用可能なコマンドおよびその使用方法に関する最新情報が記載されています。

+

NOTE: ATTO FibreBridge 7600N または 7500N では時刻同期は設定しないでください。ATTO FibreBridge 7600N または 7500N の時刻は、 ONTAP でブリッジが検出されたあとにクラスタ時間に設定されます。また、 1 日に 1 回定期的に同期されます。使用されるタイムゾーンは GMT で、変更することはできません。

+
.. IP 管理用に設定する場合は、ブリッジの IP 設定を行います。
+
Quicknav ユーティリティなしで IP アドレスを設定するには、 FibreBridge に対するシリアル接続が必要です。

+
CLI を使用する場合は、次のコマンドを実行する必要があります。

+
'*set ipaddress mp1_ip-address_*

+
'*set ipsubnetmask mp1_subnet-mask_*

+
*set ipgateway mp1x.x.x.x*

+
*set ipdhcp mp1 disabled*

+
`*set ethernetspeed mp1 1000*`

.. ブリッジ名を設定します。
+
ブリッジ名は、 MetroCluster 構成内でそれぞれ一意である必要があります。

+
各サイトの 1 つのスタックグループのブリッジ名の例：

+
*** bridge_A_1a
*** bridge_A_1b
*** bridge_B_1a
*** bridge_B_1b CLI を使用する場合は、次のコマンドを実行する必要があります。
+
`*set bridgename _bridgename _ *`



.. ONTAP 9.4 以前を実行している場合は、ブリッジで SNMP を有効にします。 +`*set snmp enabled*`
+
ONTAP 9.5 以降を実行しているシステムでは、インバンド管理を使用してイーサネットポートではなく FC ポート経由でブリッジにアクセスできます。ONTAP 9.8 以降では、インバンド管理のみがサポートされ、 SNMP 管理は廃止されています。



. ブリッジの FC ポートを設定します。
+
.. ブリッジ FC ポートのデータ速度を設定します。
+
サポートされる FC データ速度は、モデルブリッジによって異なります。

+
*** FibreBridge 7600 ブリッジは、最大 32 、 16 、または 8Gbps をサポートします。
*** FibreBridge 7500 ブリッジは、最大 16 、 8 、または 4Gbps をサポートします。
*** FibreBridge 6500 ブリッジは、最大 8 、 4 、または 2Gbps をサポートします。
+

NOTE: 選択できる FCDataRate の速度は、ブリッジポートを接続するブリッジとスイッチの両方でサポートされる最大速度以下です。ケーブルでの接続距離が SFP およびその他のハードウェアの制限を超えないようにしてください。

+
CLI を使用する場合は、次のコマンドを実行する必要があります。

+
'*set FCDataRate_port-number port-speed_*



.. FibreBridge 7500N / 6500N ブリッジを設定する場合は、ポートが使用する接続モードを ptp に設定します。
+

NOTE: FibreBridge 7600N ブリッジを設定する場合、 FCConnMode の設定は不要です。

+
CLI を使用する場合は、次のコマンドを実行する必要があります。

+
'*set FCConnMode_port-number_ptc*

.. FibreBridge 7600N / 7500N ブリッジを設定する場合は、 FC2 ポートを設定または無効にする必要があります。
+
*** 2 番目のポートを使用する場合は、 FC2 ポートについて同じ手順を繰り返す必要があります。
*** 2 番目のポートを使用しない場合は、ポート +`*FCPortDisable_port-number_*` を無効にする必要があります


.. FibreBridge 7600N / 7500N ブリッジを設定する場合は、未使用の SAS ポートを無効にします： +`*SAPortDisable_SAS-port_*`
+

NOTE: SAS ポート A~D はデフォルトで有効になります。使用していない SAS ポートを無効にする必要があります。SAS ポート A のみを使用している場合は、 SAS ポート B 、 C 、および D を無効にする必要があります。



. ブリッジへのアクセスを保護し、ブリッジの設定を保存します。
+
.. コントローラのプロンプトで、ブリッジのステータスを確認します。
+
「 * storage bridge show * 」

+
出力には、保護されていないブリッジが表示されます。

.. セキュリティ保護されていないブリッジのポートのステータスを確認します :+`*info*`
+
出力には、イーサネットポート MP1 と MP2 のステータスが表示されます。

.. イーサネットポート MP1 がイネーブルの場合は、 +`*set EthernetPort mp1 disabled*` コマンドを実行します
+

NOTE: イーサネットポート MP2 も有効になっている場合は、ポート MP2 について前の手順を繰り返します。

.. ブリッジの設定を保存します。
+
次のコマンドを実行する必要があります。

+
'*SaveConfiguration*'

+
「 * FirmwareRestart * 」と入力します

+
ブリッジを再起動するように求められます。



. 各ブリッジの FibreBridge ファームウェアを更新します。
+
新しいブリッジのタイプがパートナーブリッジと同じ場合は、パートナーブリッジと同じファームウェアにアップグレードします。新しいブリッジのタイプがパートナーブリッジと異なる場合は、ブリッジと ONTAP のバージョンでサポートされている最新のファームウェアにアップグレードします。MetroCluster メンテナンスガイドの「 FibreBridge ブリッジのファームウェアの更新」のセクションを参照してください。

. ディスクシェルフをブリッジにケーブル接続します。
+
.. 各スタックのディスクシェルフをデイジーチェーン接続します。
+
ディスクシェルフのデイジーチェーン接続の詳細については、使用しているディスクシェルフモデルの Installation Guide を参照してください。

.. ディスクシェルフの各スタックで、最初のシェルフの IOM A を FibreBridge A の SAS ポート A にケーブル接続し、最後のシェルフの IOM B を FibreBridge B の SAS ポート A にケーブル接続します
+
https://docs.netapp.com/us-en/ontap-metrocluster/install-fc/index.html["ファブリック接続 MetroCluster のインストールと設定"]

+
https://docs.netapp.com/us-en/ontap-metrocluster/install-stretch/concept_considerations_differences.html["ストレッチ MetroCluster のインストールと設定"]

+
各ブリッジには、ディスクシェルフのスタックへのパスが 1 つあります。ブリッジ A は最初のシェルフ経由でスタックの A 側に接続し、ブリッジ B は最後のシェルフ経由でスタックの B 側に接続します。

+

NOTE: ブリッジの SAS ポート B は無効になっています。



. 各ブリッジが、ブリッジの接続先のすべてのディスクドライブとディスクシェルフを検出できることを確認します。
+
|===
| 使用する手段 | 作業 


 a| 
ATTO ExpressNAV の GUI
 a| 
.. サポートされている Web ブラウザで、ブリッジの IP アドレスをブラウザのアドレスバーに入力します。
+
ATTO FibreBridge のホームページに移動し、リンクが表示されます。

.. リンクをクリックし、ブリッジを設定するときに指定したユーザ名とパスワードを入力します。
+
ATTO FibreBridge のステータスページが開き、左側にメニューが表示されます。

.. メニューの「 * 詳細設定 * 」をクリックします。
.. 接続されているデバイスを表示します :+`*sastargets*`
.. [Submit （送信） ] をクリックします。




 a| 
シリアルポート接続
 a| 
接続されているデバイスを表示します。

'*sastargets*'

|===
+
出力には、ブリッジが接続されているデバイス（ディスクおよびディスクシェルフ）が表示されます。出力行には行番号が振られているため、デバイスの台数を簡単に把握できます。

+

NOTE: 出力の先頭に response truncated というテキストが表示される場合は、 Telnet を使用してブリッジに接続し、 sastargets コマンドを使用して、すべての出力を確認できます。

+
次の出力は、 10 本のディスクが接続されていることを示します。

+
[listing]
----
Tgt VendorID ProductID        Type        SerialNumber
  0 NETAPP   X410_S15K6288A15 DISK        3QP1CLE300009940UHJV
  1 NETAPP   X410_S15K6288A15 DISK        3QP1ELF600009940V1BV
  2 NETAPP   X410_S15K6288A15 DISK        3QP1G3EW00009940U2M0
  3 NETAPP   X410_S15K6288A15 DISK        3QP1EWMP00009940U1X5
  4 NETAPP   X410_S15K6288A15 DISK        3QP1FZLE00009940G8YU
  5 NETAPP   X410_S15K6288A15 DISK        3QP1FZLF00009940TZKZ
  6 NETAPP   X410_S15K6288A15 DISK        3QP1CEB400009939MGXL
  7 NETAPP   X410_S15K6288A15 DISK        3QP1G7A900009939FNTT
  8 NETAPP   X410_S15K6288A15 DISK        3QP1FY0T00009940G8PA
  9 NETAPP   X410_S15K6288A15 DISK        3QP1FXW600009940VERQ
----
. コマンド出力で、スタック内の該当するすべてのディスクおよびディスクシェルフにブリッジが接続されていることを確認します。
+
|===
| 出力結果 | 作業 


 a| 
正解です
 a| 
手順を繰り返します xref:task_fb_hot_add_stack_of_shelves_and_bridges.adocSTEP_524EBC3334F54467B771D9E2FD2B2DDA[11.] 残りの各ブリッジ。



 a| 
不正解です
 a| 
.. SAS ケーブルに緩みがないか確認するか、手順を繰り返して SAS ケーブル接続を修正します xref:task_fb_hot_add_stack_of_shelves_and_bridges.adocSTEP_1F8F7E891D3B4CBD88176B312C6BC5CC[10.]。
.. 手順を繰り返します xref:task_fb_hot_add_stack_of_shelves_and_bridges.adocSTEP_524EBC3334F54467B771D9E2FD2B2DDA[11.]。


|===
. ファブリック接続 MetroCluster 構成を設定する場合は、使用している構成、スイッチモデル、および FC-to-SAS ブリッジモデルに対応した表に記載されているケーブルを使用して、各ブリッジをローカルの FC スイッチにケーブル接続します。
+

NOTE: 次の表に示すように、 Brocade スイッチと Cisco スイッチでは使用するポート番号が異なります。

+
** Brocade スイッチでは ' 最初のポートに 0 という番号が付けられます
** シスコ製スイッチでは、最初のポートには「 1 」という番号が付けられています。
+
|===
13+| 両方の FC ポート（ FC1 または FC2 ）を使用する FibreBridge 7500N または 7600N を使用する構成 


13+| DR グループ 1 


3+|  2+| Brocade 6505 2+| Brocade 6510 、 Brocade DCX 8510-8 2+| Brocade 6520 2+| Brocade G620 、 Brocade G620 -1 、 Brocade G630 、 Brocade G630-1 2+| Brocade G720 


2+| コンポーネント | ポート | スイッチ 1 | スイッチ 2 | スイッチ 1 | スイッチ 2 | スイッチ 1 | スイッチ 2 | スイッチ 1 | スイッチ 2 | スイッチ 1 | スイッチ 2 


 a| 
スタック 1
 a| 
bridge_x_1a
 a| 
fc1
 a| 
8.
 a| 
 a| 
8.
 a| 
 a| 
8.
 a| 
 a| 
8.
 a| 
 a| 
10.
 a| 



 a| 
FC2
 a| 
-
 a| 
8.
 a| 
-
 a| 
8.
 a| 
-
 a| 
8.
 a| 
-
 a| 
8.
 a| 
-
 a| 
10.



 a| 
bridge_x_1B
 a| 
fc1
 a| 
9.
 a| 
-
 a| 
9.
 a| 
-
 a| 
9.
 a| 
-
 a| 
9.
 a| 
-
 a| 
11.
 a| 
-



 a| 
FC2
 a| 
-
 a| 
9.
 a| 
-
 a| 
9.
 a| 
-
 a| 
9.
 a| 
-
 a| 
9.
 a| 
-
 a| 
11.



 a| 
スタック 2
 a| 
bridge_x_2a
 a| 
fc1
 a| 
10.
 a| 
-
 a| 
10.
 a| 
-
 a| 
10.
 a| 
-
 a| 
10.
 a| 
-
 a| 
14
 a| 
-



 a| 
FC2
 a| 
-
 a| 
10.
 a| 
-
 a| 
10.
 a| 
-
 a| 
10.
 a| 
-
 a| 
10.
 a| 
-
 a| 
14



 a| 
bridge_x_2B
 a| 
fc1
 a| 
11.
 a| 
-
 a| 
11.
 a| 
-
 a| 
11.
 a| 
-
 a| 
11.
 a| 
-
 a| 
17
 a| 
-



 a| 
FC2
 a| 
-
 a| 
11.
 a| 
-
 a| 
11.
 a| 
-
 a| 
11.
 a| 
-
 a| 
11.
 a| 
-
 a| 
17



 a| 
スタック 3
 a| 
bridge_x_3a
 a| 
fc1
 a| 
12.
 a| 
-
 a| 
12.
 a| 
-
 a| 
12.
 a| 
-
 a| 
12.
 a| 
-
 a| 
18
 a| 
-



 a| 
FC2
 a| 
-
 a| 
12.
 a| 
-
 a| 
12.
 a| 
-
 a| 
12.
 a| 
-
 a| 
12.
 a| 
-
 a| 
18



 a| 
bridge_x_3B
 a| 
fc1
 a| 
13
 a| 
-
 a| 
13
 a| 
-
 a| 
13
 a| 
-
 a| 
13
 a| 
-
 a| 
19
 a| 
-



 a| 
FC2
 a| 
-
 a| 
13
 a| 
-
 a| 
13
 a| 
-
 a| 
13
 a| 
-
 a| 
13
 a| 
-
 a| 
19



 a| 
スタック y
 a| 
bridge_x_ya
 a| 
fc1
 a| 
14
 a| 
-
 a| 
14
 a| 
-
 a| 
14
 a| 
-
 a| 
14
 a| 
-
 a| 
20
 a| 
-



 a| 
FC2
 a| 
-
 a| 
14
 a| 
-
 a| 
14
 a| 
-
 a| 
14
 a| 
-
 a| 
14
 a| 
-
 a| 
20



 a| 
bridge_x_YB
 a| 
fc1
 a| 
15
 a| 
-
 a| 
15
 a| 
-
 a| 
15
 a| 
-
 a| 
15
 a| 
-
 a| 
21
 a| 
-



 a| 
FC2
 a| 
--

-- a| 
15
 a| 
--

-- a| 
15
 a| 
--

-- a| 
15
 a| 
-
 a| 
15
 a| 
-
 a| 
21



 a| 

NOTE: G620 、 G630 、 G620 -1 、および G630-1 スイッチでは、追加のブリッジをポート 16 、 17 、 20 、および 21 にケーブル接続できます。

|===
+
|===
11+| 両方の FC ポート（ FC1 または FC2 ）を使用する FibreBridge 7500N または 7600N を使用する構成 


11+| DR グループ 2 


3+|  2+| Brocade G620 、 Brocade G620 -1 、 Brocade G630 、 Brocade G630-1 2+| Brocade 6510 、 Brocade DCX 8510-8 2+| Brocade 6520 2+| Brocade G720 


2+| コンポーネント | ポート | スイッチ 1 | スイッチ 2 | スイッチ 1 | スイッチ 2 | スイッチ 1 | スイッチ 2 | スイッチ 1 | スイッチ 2 


 a| 
スタック 1
 a| 
bridge_x_51A
 a| 
fc1
 a| 
26
 a| 
-
 a| 
32
 a| 
-
 a| 
56
 a| 
-
 a| 
32
 a| 
-



 a| 
FC2
 a| 
-
 a| 
26
 a| 
-
 a| 
32
 a| 
-
 a| 
56
 a| 
-
 a| 
32



 a| 
bridge_x_51b
 a| 
fc1
 a| 
27
 a| 
-
 a| 
33
 a| 
-
 a| 
57
 a| 
-
 a| 
33
 a| 
-



 a| 
FC2
 a| 
-
 a| 
27
 a| 
-
 a| 
33
 a| 
-
 a| 
57
 a| 
-
 a| 
33



 a| 
スタック 2
 a| 
bridge_x_52A
 a| 
fc1
 a| 
30
 a| 
-
 a| 
34
 a| 
-
 a| 
58
 a| 
-
 a| 
34
 a| 
-



 a| 
FC2
 a| 
-
 a| 
30
 a| 
-
 a| 
34
 a| 
-
 a| 
58
 a| 
-
 a| 
34



 a| 
bridge_x_52b
 a| 
fc1
 a| 
31.
 a| 
-
 a| 
35
 a| 
-
 a| 
59
 a| 
-
 a| 
35
 a| 
-



 a| 
FC2
 a| 
-
 a| 
31.
 a| 
-
 a| 
35
 a| 
-
 a| 
59
 a| 
-
 a| 
35



 a| 
スタック 3
 a| 
bridge_x_53a
 a| 
fc1
 a| 
32
 a| 
-
 a| 
36
 a| 
-
 a| 
60
 a| 
-
 a| 
36
 a| 
-



 a| 
FC2
 a| 
-
 a| 
32
 a| 
-
 a| 
36
 a| 
-
 a| 
60
 a| 
-
 a| 
36



 a| 
bridge_x_53B
 a| 
fc1
 a| 
33
 a| 
-
 a| 
37
 a| 
-
 a| 
61
 a| 
-
 a| 
37
 a| 
-



 a| 
FC2
 a| 
-
 a| 
33
 a| 
-
 a| 
37
 a| 
-
 a| 
61
 a| 
-
 a| 
37



 a| 
スタック y
 a| 
bridge_x_5ya
 a| 
fc1
 a| 
34
 a| 
-
 a| 
38
 a| 
-
 a| 
62
 a| 
-
 a| 
38
 a| 
-



 a| 
FC2
 a| 
-
 a| 
34
 a| 
-
 a| 
38
 a| 
-
 a| 
62
 a| 
-
 a| 
38



 a| 
bridge_x_5yb
 a| 
fc1
 a| 
35
 a| 
-
 a| 
39
 a| 
-
 a| 
63
 a| 
-
 a| 
39
 a| 
-



 a| 
FC2
 a| 
-
 a| 
35
 a| 
-
 a| 
39
 a| 
-
 a| 
63
 a| 
-
 a| 
39



 a| 

NOTE: G620 、 G630 、 G620 -1 、および G-630-1 スイッチでは、追加のブリッジをポート 36~39 にケーブル接続できます。

|===
+
|===
12+| FibreBridge 6500N ブリッジ、または 1 つの FC ポート（ FC1 または FC2 ）のみを使用する FibreBridge 7500N または 7600N を使用する構成 


12+| DR グループ 1 


2+|  2+| Brocade 6505 2+| Brocade 6510 、 Brocade DCX 8510-8 2+| Brocade 6520 2+| Brocade G620 、 Brocade G620 -1 、 Brocade G630 、 Brocade G630-1 2+| Brocade G720 


| コンポーネント | ポート | スイッチ 1 | スイッチ 2 | スイッチ 1 | スイッチ 2 | スイッチ 1 | スイッチ 2 | スイッチ 1 | スイッチ 2 | スイッチ 1 | スイッチ 2 


 a| 
スタック 1
 a| 
bridge_x_1a
 a| 
8.
 a| 
 a| 
8.
 a| 
 a| 
8.
 a| 
 a| 
8.
 a| 
 a| 
10.
 a| 



 a| 
bridge_x_1b
 a| 
-
 a| 
8.
 a| 
-
 a| 
8.
 a| 
-
 a| 
8.
 a| 
-
 a| 
8.
 a| 
-
 a| 
10.



 a| 
スタック 2
 a| 
bridge_x_2a
 a| 
9.
 a| 
-
 a| 
9.
 a| 
-
 a| 
9.
 a| 
-
 a| 
9.
 a| 
-
 a| 
11.
 a| 
-



 a| 
bridge_x_2b
 a| 
-
 a| 
9.
 a| 
-
 a| 
9.
 a| 
-
 a| 
9.
 a| 
-
 a| 
9.
 a| 
-
 a| 
11.



 a| 
スタック 3
 a| 
bridge_x_3a
 a| 
10.
 a| 
-
 a| 
10.
 a| 
-
 a| 
10.
 a| 
-
 a| 
10.
 a| 
-
 a| 
14
 a| 
-



 a| 
bridge_x_4b
 a| 
-
 a| 
10.
 a| 
-
 a| 
10.
 a| 
-
 a| 
10.
 a| 
-
 a| 
10.
 a| 
-
 a| 
14



 a| 
スタック y
 a| 
bridge_x_ya
 a| 
11.
 a| 
-
 a| 
11.
 a| 
-
 a| 
11.
 a| 
-
 a| 
11.
 a| 
-
 a| 
15
 a| 
-



 a| 
bridge_x_YB
 a| 
-
 a| 
11.
 a| 
-
 a| 
11.
 a| 
-
 a| 
11.
 a| 
-
 a| 
11.
 a| 
-
 a| 
15



 a| 

NOTE: G620 、 G630 、 G620 -1 、および G630-1 スイッチでは、追加のブリッジをポート 12~17 、 20 、および 21 にケーブル接続できます。追加のブリッジは、ポート 16-17 、 20 、および 21 G720 スイッチにケーブル接続できます。

|===
+
|===
10+| FibreBridge 6500N ブリッジ、または 1 つの FC ポート（ FC1 または FC2 ）のみを使用する FibreBridge 7500N または 7600N を使用する構成 


10+| DR グループ 2 


2+|  2+| Brocade G720 2+| Brocade G620 、 Brocade G620 -1 、 Brocade G630 、 Brocade G630-1 2+| Brocade 6510 、 Brocade DCX 8510-8 2+| Brocade 6520 


 a| 
スタック 1
 a| 
bridge_x_51A
 a| 
32
 a| 
-
 a| 
26
 a| 
-
 a| 
32
 a| 
-
 a| 
56
 a| 
-



 a| 
bridge_x_51b
 a| 
-
 a| 
32
 a| 
-
 a| 
26
 a| 
-
 a| 
32
 a| 
-
 a| 
56



 a| 
スタック 2
 a| 
bridge_x_52A
 a| 
33
 a| 
-
 a| 
27
 a| 
-
 a| 
33
 a| 
-
 a| 
57
 a| 
-



 a| 
bridge_x_52b
 a| 
-
 a| 
33
 a| 
-
 a| 
27
 a| 
-
 a| 
33
 a| 
-
 a| 
57



 a| 
スタック 3
 a| 
bridge_x_53a
 a| 
34
 a| 
-
 a| 
30
 a| 
-
 a| 
34
 a| 
-
 a| 
58
 a| 
-



 a| 
bridge_x_54b
 a| 
-
 a| 
34
 a| 
-
 a| 
30
 a| 
-
 a| 
34
 a| 
-
 a| 
58



 a| 
スタック y
 a| 
bridge_x_ya
 a| 
35
 a| 
-
 a| 
31.
 a| 
-
 a| 
35
 a| 
-
 a| 
59
 a| 
-



 a| 
bridge_x_YB
 a| 
-
 a| 
35
 a| 
-
 a| 
31.
 a| 
-
 a| 
35
 a| 
-
 a| 
59



 a| 

NOTE: G620 、 G630 、 G620 -1 、および G630-1 スイッチでは、追加のブリッジをポート 32~39 にケーブル接続できます。G720 スイッチでは、追加のブリッジをポート 36-39 にケーブル接続できます。

|===


. ブリッジ接続型 MetroCluster システムを設定する場合は、各ブリッジをコントローラモジュールにケーブル接続します。
+
.. ブリッジの FC ポート 1 を、 cluster_A のコントローラモジュールの 16Gb または 8Gb の FC ポートにケーブル接続します
.. ブリッジの FC ポート 2 を、 cluster_A のコントローラモジュールの同じ速度の FC ポートにケーブル接続します
.. 他のブリッジでも上記の手順を繰り返し、すべてのブリッジをケーブル接続します。


. システムコンソールからディスクドライブファームウェアを最新バージョンに更新します。
+
'*disk_fw_updat*

+
このコマンドは両方のコントローラモジュールで実行する必要があります。

+
https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware["ネットアップのダウンロード：ディスクドライブファームウェア"]

. ダウンロードしたファームウェアの手順に従って、ディスクシェルフファームウェアを最新バージョンに更新します。
+
手順のコマンドは、どちらのコントローラモジュールのシステムコンソールからも実行できます。

+
https://mysupport.netapp.com/site/downloads/firmware/disk-shelf-firmware["ネットアップのダウンロード：ディスクシェルフファームウェア"]

. システムでディスクの自動割り当てが有効になっていない場合は、ディスクドライブの所有権を割り当てます。
+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-psmg/home.html["ディスクおよびアグリゲートの管理"]

+

NOTE: ディスクシェルフの 1 つのスタックの所有権を複数のコントローラモジュールに分割する場合は、ディスク所有権を割り当てる前に、クラスタ内の両方のノードでディスクの自動割り当てを無効にする必要があります（「 storage disk option modify -autoassign off * 」）。 そうしないと、 1 本のディスクドライブを割り当てたときに、残りのディスクドライブが同じコントローラモジュールおよびプールに自動的に割り当てられる可能性があります。

+

NOTE: ディスクドライブファームウェアとディスクシェルフファームウェアが更新され、このタスクの検証手順が完了するまで、アグリゲートまたはボリュームにディスクドライブを追加しないでください。

. 新しいスタックのスイッチポートを有効にします。
. ONTAP で MetroCluster 構成の動作を確認します。
+
.. システムがマルチパスかどうかを確認します。 +`* node run -node -name_sysconfig -a *`
.. 両方のクラスタにヘルス・アラートがないかどうかを確認します +`* system health alert show *`
.. MetroCluster 構成と動作モードが正常であることを確認します :+`* MetroCluster show*`
.. MetroCluster チェック :+`* MetroCluster check run*` を実行します
.. MetroCluster チェックの結果を表示します :+`* MetroCluster check show*`
.. スイッチにヘルス・アラートがあるかどうかを確認します（ある場合）： +`* storage switch show *`
.. Config Advisor を実行します。
+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["ネットアップのダウンロード： Config Advisor"]

.. Config Advisor の実行後、ツールの出力を確認し、推奨される方法で検出された問題に対処します。


. 必要に応じて、パートナーサイトに対してこの手順を繰り返します。


* 関連情報 *

xref:concept_in_band_management_of_the_fc_to_sas_bridges.adoc[FC-to-SAS ブリッジのインバンド管理]
