---
permalink: install-stretch/concept_in_band_management_of_the_fc_to_sas_bridges.html 
sidebar: sidebar 
keywords: metrocluster, stretch, installation, in, band, management, fc, sas, bridges 
summary: ONTAP 9.5 以降では、 FibreBridge 7500N / 7600N ブリッジについて、 IP 管理に代わる方法としてインバンド管理がサポートされます。ONTAP 9.8 以降では、アウトオブバンド管理は廃止されています。 
---
= FC-to-SAS ブリッジのインバンド管理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.5 以降では、 FibreBridge 7500N / 7600N ブリッジについて、 IP 管理に代わる方法としてインバンド管理 _ がサポートされます。ONTAP 9.8 以降では、アウトオブバンド管理は廃止されています。


NOTE: ONTAP 9.8 以降では '*storage bridge *' コマンドは '*system bridge *' コマンドに置き換えられています以下の手順は '*storage bridge *' コマンドを示していますが 'ONTAP 9.8 以降を実行している場合は '*system bridge *' コマンドを使用することをお勧めします

インバンド管理を使用すると、 ONTAP CLI からブリッジへの FC 接続を介してブリッジを管理および監視できます。ブリッジのイーサネットポートを介してブリッジに物理的にアクセスする必要がないため、ブリッジのセキュリティの脆弱性が軽減されます。

ブリッジのインバンド管理が可能かどうかは、 ONTAP のバージョンによって異なります。

* ONTAP 9.8 以降では、ブリッジはデフォルトでインバンド接続を介して管理され、 SNMP を介したブリッジのアウトオブバンド管理は廃止されています。
* ONTAP 9.5 から 9.7 ：インバンド管理またはアウトオブバンド管理のどちらかで SNMP 管理がサポートされます。
* ONTAP 9.5 よりも前のバージョンでは、アウトオブバンドの SNMP 管理のみがサポートされます。


ブリッジの CLI コマンドは、 ONTAP インターフェイスの ONTAP インターフェイス「 storage bridge run -cli-name_bridge-name_command_bridge-command-name_` コマンド」から実行できます。


NOTE: ブリッジの物理接続を制限することでセキュリティを向上させるために、 IP アクセスを無効にしたインバンド管理の使用を推奨します。
