---
permalink: install-stretch/concept_required_mcc_components_and_naming_conventions_for_two_node_bridge_attached_stretch_configurations_mcc.html 
sidebar: sidebar 
keywords: metrocluster, stretch, installation, required, hardware, components, naming, conventions, two, node, stretch, bridge 
summary: MetroCluster 構成を計画する際には、サポート対象の必要なハードウェアコンポーネントとソフトウェアコンポーネントを把握しておく必要があります。また、内容を正しく理解するためには、このドキュメントで使用しているコンポーネントの命名規則も確認しておく必要があります。たとえば、一方のサイトをサイト A と呼び、もう一方のサイトをサイト B と呼びます 
---
= 2 ノードブリッジ接続ストレッチ構成の MetroCluster に必要なハードウェアコンポーネントと命名規則
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
MetroCluster 構成を計画する際には、サポート対象の必要なハードウェアコンポーネントとソフトウェアコンポーネントを把握しておく必要があります。また、内容を正しく理解するためには、このドキュメントで使用しているコンポーネントの命名規則も確認しておく必要があります。たとえば、一方のサイトをサイト A と呼び、もう一方のサイトをサイト B と呼びます



== サポートされているソフトウェアおよびハードウェア

ハードウェアとソフトウェアは、 MetroCluster FC 構成でサポートされている必要があります。

https://hwu.netapp.com["NetApp Hardware Universe の略"]

AFF システムを使用する場合は、 MetroCluster 構成内のすべてのコントローラモジュールを AFF システムとして構成する必要があります。



== MetroCluster 構成でのハードウェアの冗長性

MetroCluster 構成ではハードウェアの冗長性が確保されるため、サイトには各コンポーネントが 2 つずつあります。コンポーネントの名前には、サイトを表す A または B 、および 2 つあるコンポーネントのうちどちらかを表す番号として 1 または 2 を使用します。



== シングルノード ONTAP クラスタ × 2

ブリッジ接続ストレッチ MetroCluster 構成には、シングルノード ONTAP クラスタが 2 つ必要です。

名前は MetroCluster 構成内で一意である必要があります。

名前の例：

* サイト A ： cluster_A
* サイト B ： cluster_B




== ストレージコントローラモジュール × 2

ブリッジ接続ストレッチ MetroCluster 構成には、ストレージコントローラモジュールが 2 つ必要です。

コントローラの要件は次のとおりです。

* 名前は MetroCluster 構成内で一意である必要があります。
* MetroCluster 構成のすべてのコントローラモジュールで同じバージョンの ONTAP が実行されている必要があります。
* 1 つの DR グループ内のすべてのコントローラモジュールのモデルが同じであることが必要です。
* 1 つの DR グループのすべてのコントローラモジュールで同じ FC-VI 構成を使用する必要があります。
+
一部のコントローラモジュールは、次の 2 つのオプションに対応しています。

+
** オンボードの FC-VI ポート
** スロット 1 の FC-VI カード
+
オンボードの FC-VI ポートを使用するコントローラモジュールとアドオンの FC-VI カードを使用するコントローラモジュールは混在できません。たとえば、あるノードでオンボードの FC-VI 構成を使用する場合は、 DR グループの他のすべてのノードでもオンボードの FC-VI 構成を使用する必要があります。





名前の例：

* サイト A ： controller_A_1
* サイト B ： controller_B_1




== FC-to-SAS ブリッジの要件

ブリッジ接続ストレッチ MetroCluster 構成では、各サイトに FC-to-SAS ブリッジが 2 つ以上必要です。

これらのブリッジで SAS ディスクシェルフをコントローラモジュールに接続します。


NOTE: ONTAP 9.8 以降を実行している構成では、 FibreBridge 6500N ブリッジはサポートされません。

* FibreBridge 7600N / 7500N ブリッジでは、最大 4 つの SAS スタックがサポートされます。
* それぞれのスタックで異なる IOM モデルを使用できますが、スタック内ではすべてのシェルフで同じモデルを使用する必要があります。
+
サポートされる IOM モデルは、実行している ONTAP のバージョンによって異なります。

* 名前は MetroCluster 構成内で一意である必要があります。


この手順で例として使用されている推奨名には、ブリッジの接続先コントローラモジュールとポート番号が含まれています。

名前の例：

* サイト A ：
+
** bridge_A_1_``__ ポート番号 _``
** bridge_A_2_ `__ ポート番号 __``


* サイト B ：
+
** bridge_B_1_``__ ポート番号 _``
** Bridge_B_2_ `__ ポート番号 _``






== SAS シェルフ × 4 台以上（推奨）

ブリッジ接続ストレッチ MetroCluster 構成には、 SAS シェルフが少なくとも 2 台必要です。ただし、シェルフ単位でのディスク割り当てを可能にするために、各サイトにシェルフを 2 台配置し、合計 4 台の SAS シェルフを使用することを推奨します。

各サイトにシェルフ 1 台の最小構成もサポートされます。

名前の例：

* サイト A ：
+
** shelf_A_1_1
** shelf_A_1_2


* サイト B ：
+
** shelf_B_1_1
** shelf_B_1_2






== IOM12 モジュールと IOM 6 モジュールをスタック内に混在させる

使用している ONTAP のバージョンでシェルフの混在がサポートされている必要がお使いのバージョンの ONTAP でシェルフの混在がサポートされているかどうかを確認するには、 Interoperability Matrix Tool （ IMT ）を参照してください。 https://imt.netapp.com/matrix/["IMT"^]

シェルフ混在の詳細については、以下を参照してください。 https://docs.netapp.com/platstor/topic/com.netapp.doc.hw-ds-mix-hotadd/home.html["IOM12 モジュールを搭載したシェルフを IOM6 モジュールを搭載したシェルフのスタックにホットアドします"^]
