---
permalink: install-stretch/reference_information_gathering_worksheet_for_fc_to_sas_bridges_2_node_atto.html 
sidebar: sidebar 
keywords: metrocluster, stretch, installation, worksheet, fc, sas, bridges, information 
summary: MetroCluster サイトの設定を開始する前に、必要な設定情報を収集する必要があります。 
---
= FC-to-SAS ブリッジの情報収集ワークシート
:icons: font
:imagesdir: ../media/


[role="lead"]
MetroCluster サイトの設定を開始する前に、必要な設定情報を収集する必要があります。



== サイト A 、 FC-to-SAS ブリッジ 1 （ FC_bridge_A_1a ）

SAS スタックごとに FC-to-SAS ブリッジが少なくとも 2 つ必要です。

各ブリッジは、 Controller_A_1_````__ ポート番号 ____`` と Controller_B_1_```__ ポート番号 _`` に接続します。

|===


| サイト A | あなたの価値 


 a| 
bridge_A_1a の IP アドレス
 a| 



 a| 
Bridge_A_1a ユーザ名
 a| 



 a| 
Bridge_A_1a のパスワード
 a| 

|===


== サイト A 、 FC-to-SAS ブリッジ 2 （ FC_bridge_A_1b ）

SAS スタックごとに FC-to-SAS ブリッジが少なくとも 2 つ必要です。

各ブリッジは、 Controller_A_1_````__ ポート番号 ____`` と Controller_B_1_```__ ポート番号 _`` に接続します。

|===


| サイト A | あなたの価値 


 a| 
Bridge_A_1b の IP アドレス
 a| 



 a| 
Bridge_A_1b のユーザ名
 a| 



 a| 
Bridge_A_1b のパスワード
 a| 

|===


== サイト B 、 FC-to-SAS ブリッジ 1 （ FC_bridge_B_1a ）

SAS スタックごとに FC-to-SAS ブリッジが少なくとも 2 つ必要です。

各ブリッジは、 Controller_A_1_`__ ポート番号 __ と Controller_B_1_`__ ポート番号 __ に接続します。

|===


| サイト B | あなたの価値 


 a| 
Bridge_B_1a の IP アドレス
 a| 



 a| 
Bridge_B_1a ユーザ名
 a| 



 a| 
Bridge_B_1a のパスワード
 a| 

|===


== サイト B 、 FC-to-SAS ブリッジ 2 （ FC_bridge_B_1b ）

SAS スタックごとに FC-to-SAS ブリッジが少なくとも 2 つ必要です。

各ブリッジは、 Controller_A_1_`__ ポート番号 __ と Controller_B_1_`__ ポート番号 __ に接続します。

|===


| サイト B | あなたの価値 


 a| 
Bridge_B_1b の IP アドレス
 a| 



 a| 
Bridge_B_1b ユーザ名
 a| 



 a| 
Bridge_B_1b のパスワード
 a| 

|===