---
permalink: install-stretch/task_fb_new_install_prepare.html 
sidebar: sidebar 
keywords: metrocluster, stretch, installation, prepare 
summary: 新しい MetroCluster システムで使用するブリッジの設置を準備する際には、システムが一定の要件を満たしている必要があります。これには、ブリッジのセットアップと設定の要件が含まれます。必要なドキュメント、 ATTO QuickNAV ユーティリティ、ブリッジファームウェアのダウンロードなどがあります。 
---
= 設置の準備
:icons: font
:imagesdir: ../media/


[role="lead"]
新しい MetroCluster システムで使用するブリッジの設置を準備する際には、システムが一定の要件を満たしている必要があります。これには、ブリッジのセットアップと設定の要件が含まれます。必要なドキュメント、 ATTO QuickNAV ユーティリティ、ブリッジファームウェアのダウンロードなどがあります。



== 作業を開始する前に

* システムキャビネットに付属していない場合は、システムをラックに設置しておく必要があります。
* サポートされているハードウェアモデルとソフトウェアバージョンを使用している必要があります。
+
https://mysupport.netapp.com/matrix["NetApp Interoperability Matrix Tool で確認できます"]

+
IMT では、 Storage 解決策フィールドを使用して MetroCluster 解決策を選択できます。検索を絞り込むには、 * 構成部品エクスプローラ * を使用して構成部品と ONTAP バージョンを選択します。[ 結果の表示（ Show Results ） ] をクリックすると、条件に一致するサポートされている構成のリストを表示できます。

* 各 FC スイッチで、 1 つの FC ポートを 1 つのブリッジに接続できる必要があります。
* SAS ケーブルの取り扱い方法、およびディスクシェルフの設置とケーブル接続に関する考慮事項とベストプラクティスを確認しておく必要があります。
+
考慮事項とベストプラクティスについては、使用しているディスクシェルフモデルの『 Installation and Service Guide 』を参照してください。

* ブリッジの設定に使用するコンピュータでは、 ATTO ExpressNAV GUI を使用するために、 ATTO でサポートされている Web ブラウザを実行している必要があります。
+
ATTO Product Release Notes に、サポートされている Web ブラウザの最新のリストが掲載されています。このドキュメントには、以下の手順で説明する ATTO の Web サイトからアクセスできます。



.手順
. 使用しているディスクシェルフモデルの Installation and Service Guide をダウンロードします。
. FibreBridge のモデルに対応するリンクを使用して ATTO の Web サイトにアクセスし、マニュアルと QuickNAV ユーティリティをダウンロードします。
+
[NOTE]
====
管理インターフェイスの詳細については、使用しているモデルブリッジに対応した ATTO FibreBridge Installation and Operation Manual を参照してください。

ATTO Fiberbridge の概要ページにあるリンクを使用して、このページおよび ATTO の Web サイトのその他のコンテンツにアクセスできます。

====
. 推奨されるブリッジ管理インターフェイス、 ATTO ExpressNAV GUI および ATTO QuickNAV ユーティリティを使用するために必要なハードウェアおよび情報を収集します。
+
.. デフォルト以外のユーザ名とパスワードを決定します（ブリッジへのアクセス用）。
+
デフォルトのユーザ名とパスワードは変更してください。

.. ブリッジの IP 管理を設定する場合は、ブリッジに付属のシールド付きイーサネットケーブル（ブリッジのイーサネット管理 1 ポートとネットワークの接続に使用）が必要です。
.. ブリッジの IP 管理を設定する場合は、各ブリッジのイーサネット管理 1 ポートの IP アドレス、サブネットマスク、およびゲートウェイの情報が必要です。
.. セットアップに使用するコンピュータで VPN クライアントを無効にします。
+
アクティブな VPN クライアント原因がブリッジの QuickNAV スキャンに失敗しました。




