---
permalink: manage/concept_monitoring_and_protecting_database_validity_by_using_nvfail.html 
sidebar: sidebar 
keywords: monitor, protect, file, system, consistency, nvfail, parameter, volume, modify, enable, detect, nonvolatile, nvram, switchover, recover, impact, access, nfs, volume, lun, command, monitor, data, loss, event, access 
summary: ONTAP では、 volume modify コマンドの -nvfail パラメータによって、システム起動時またはスイッチオーバー処理後の NVRAM （不揮発性 RAM ）の不整合を検出できます。また、警告を表示し、ボリュームを手動でリカバリできるようになるまでデータのアクセスと変更ができないようにシステムを保護します。 
---
= NVFAIL を使用したファイルシステム整合性の監視および保護
:icons: font
:imagesdir: ../media/


[role="lead"]
volume modify コマンドの -nvfail` パラメータを使用すると、 ONTAP は、システムの起動時またはスイッチオーバー操作後に NVRAM （不揮発性 RAM ）の不整合を検出できます。また、警告を表示し、ボリュームを手動でリカバリできるようになるまでデータのアクセスと変更ができないようにシステムを保護します。

ONTAP が何らかの問題を検出すると、データベースインスタンスまたはファイルシステムインスタンスは応答を停止するか、シャットダウンされます。ONTAP はコンソールにエラーメッセージを送信して、データベースまたはファイルシステムの状態をチェックするようユーザに警告します。NVFAIL を有効にすると、データベースの有効性を侵害する可能性のある、クラスタ化されたノード間での NVRAM の不整合をデータベース管理者に警告できます。

フェイルオーバーまたはブートリカバリのあとは、 NVFAIL 状態が解消されるまで NFS クライアントはどのノードからもデータにアクセスできません。CIFS クライアントには影響はありません。



== NFS ボリュームまたは LUN へのアクセスに対する NVFAIL の影響

[role="lead"]
NVFAIL 状態は、起動時に ONTAP が NVRAM エラーを検出した場合、 MetroCluster スイッチオーバー処理が実行された場合、または NVFAIL オプションが設定されたボリュームの HA テイクオーバー処理中に発生します。起動時にエラーが検出されなければ、ファイルサービスは正常に開始されます。ただし、 NVRAM エラーが検出された場合、またはディザスタスイッチオーバーで NVFAIL の処理が実行された場合、 ONTAP はデータベースインスタンスの応答を停止します。

NVFAIL オプションを有効にすると、起動時に次の表に示すいずれかのプロセスが開始されます。

|===
| 状況 | 作業 


 a| 
ONTAP は NVRAM エラーを検出しませんでした
 a| 
ファイルサービスが正常に開始されます。



 a| 
ONTAP が NVRAM エラーを検出した場合
 a| 
* ONTAP がデータベースにアクセスしようとする NFS クライアントに古いファイルハンドル（ ESTALE ）エラーを返します。これにより、アプリケーションは、応答を中断するか、クラッシュまたは停止します。
+
ONTAP からシステムコンソールおよびログファイルにエラーメッセージが送信されます。

* アプリケーションが再起動されると、データベースの妥当性が確認されていなくても、 CIFS クライアントからのアクセスが可能になります。
+
NFS クライアントの場合は、影響を受けたボリューム上の in-nvfailed-state オプションをリセットするまでファイルにアクセスできません。





 a| 
次のいずれかのパラメータを使用する場合：

* 「 dr-force-nvfail 」ボリュームオプションが設定されている
* force-nvfail-all 'switchover コマンド・オプションが設定されている

 a| 
管理者が将来のディザスタスイッチオーバーで NVFAIL 処理を強制的に実行する予定がない場合は、スイッチオーバー後に「 dr-force-nvfail 」オプションを解除できます。NFS クライアントの場合は、影響を受けたボリューム上の in-nvfailed-state オプションをリセットするまでファイルにアクセスできません。


NOTE: 「 force-nvfail-all 」オプションを使用すると、ディザスタスイッチオーバー時に処理されるすべての DR ボリュームで「 dr -force-nvfail 」オプションが設定されます。



 a| 
ONTAP は、 LUN を含むボリューム上で NVRAM エラーを検出します
 a| 
そのボリュームの LUN がオフラインになります。ボリュームの in-nvfailed-state オプションをクリアし、さらに影響を受けたボリュームの各 LUN をオンラインにして LUN 上の NVFAIL 属性をクリアする必要があります。LUN の整合性をチェックする手順を実行し、必要に応じて Snapshot コピーまたはバックアップから LUN をリカバリすることができます。ボリューム内のすべての LUN がリカバリされると、影響を受けたボリュームの in-nvfailed-state オプションがクリアされます。

|===


== データ損失イベントを監視するコマンド

[role="lead"]
NVFAIL オプションを有効にすると、 NVRAM の不整合によってシステムクラッシュが発生した場合、または MetroCluster スイッチオーバーが発生した場合に、通知を受け取ることができます。

デフォルトでは、 NVFAIL パラメータは無効になっています。

[cols="2*"]
|===
| 状況 | 使用するコマンド 


 a| 
NVFAIL を有効にして新しいボリュームを作成します
 a| 
'volume create-nvfail on `



 a| 
既存のボリュームで NVFAIL を有効にする
 a| 
'volume modify'

* 注： * 作成されたボリュームで NVFAIL を有効にするには、 -nvfail オプションを on に設定します。



 a| 
指定したボリュームで NVFAIL が有効になっているかどうかを表示します
 a| 
volume show

* 注： * 指定したボリュームの NVFAIL 属性を表示するには、「 -fields 」パラメータを「 nvfail 」に設定します。

|===
詳細については、各コマンドのマニュアルページを参照してください。



== スイッチオーバー後に NVFAIL 状態のボリュームにアクセスする場合

[role="lead"]
スイッチオーバー後に 'volume modify コマンドの -in-nvfailed-state パラメータをリセットし ' クライアントがデータにアクセスする制限を解除することにより 'NVFAIL 状態をクリアする必要があります

データベースまたはファイルシステムが実行されていない、または影響を受けたボリュームにアクセスしようとしていないことが必要です。

in-nvfailed-state パラメータを設定するには、 advanced 権限が必要です。

.ステップ
. in-nvfailed-state パラメータを false に設定して volume modify コマンドを実行し、ボリュームをリカバリします。


データベースファイルの有効性を調べる方法については、ご使用のデータベースソフトウェアのマニュアルを参照してください。

データベースで LUN が使用されている場合は、 NVRAM 障害後にホストから LUN にアクセスできるようにする手順を確認してください。

link:../manage/concept_monitoring_and_protecting_database_validity_by_using_nvfail.html["NVFAIL を使用したファイルシステム整合性の監視および保護"]



== スイッチオーバー後の NVFAIL 状態にある LUN のリカバリ

[role="lead"]
スイッチオーバーが発生すると、 NVFAIL 状態にある LUN 上のデータにホストがアクセスできなくなります。データベースが LUN にアクセスできるようにするには、いくつかの作業が必要です。

データベースが実行されていないことを確認します。

.手順
. volume modify コマンドの -in-nvfailed-state パラメータをリセットし、 LUN をホストする、影響を受けたボリュームの NVFAIL 状態をクリアします。
. 影響を受けた LUN をオンラインにします。
. LUN でデータの不整合の有無を確認し、これを解決します。
+
これには、ホストベースのリカバリか、 SnapRestore を使用してストレージコントローラ上で実行するリカバリが含まれる場合があります。

. LUN をリカバリしたあと、データベースアプリケーションをオンラインにします。

