---
permalink: manage/reference_where_to_find_additional_information_dr_guide.html 
sidebar: sidebar 
keywords: learn, metrocluster, configuration, operation, netapp, extensive, documentation, additional, information, miscellaneous, guide 
summary: MetroCluster の構成と運用の詳細については、ネットアップの広範なドキュメントを参照してください。 
---
= 追加情報の参照先
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
MetroCluster の設定と処理の詳細については、を参照してください。



== MetroCluster およびその他の情報

|===


| 情報 | 件名 


 a| 
link:../index.html["MetroCluster のドキュメント"]
 a| 
* すべての MetroCluster 情報




 a| 
https://www.netapp.com/pdf.html?item=/media/13482-tr4375pdf.pdf["ネットアップテクニカルレポート 4375 ：『 NetApp MetroCluster for ONTAP 9.3 』"^]
 a| 
* MetroCluster の設定と運用の技術概要
* MetroCluster 構成のベストプラクティス




 a| 
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-mcc-inst-cnfg-fabric/home.html["ファブリック接続 MetroCluster のインストールと設定"]
 a| 
* ファブリック接続 MetroCluster アーキテクチャ
* 構成のケーブル接続
* FC-to-SAS ブリッジの設定
* FC スイッチを設定します
* ONTAP で MetroCluster を設定します




 a| 
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-mcc-inst-cnfg-stretch/home.html["ストレッチ MetroCluster のインストールと設定"]
 a| 
* ストレッチ MetroCluster アーキテクチャ
* 構成のケーブル接続
* FC-to-SAS ブリッジの設定
* ONTAP で MetroCluster を設定します




 a| 
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-mcc-inst-cnfg-ip/home.html["MetroCluster IP のインストールと設定"]
 a| 
* MetroCluster IP アーキテクチャ
* 構成のケーブル接続
* ONTAP で MetroCluster を設定します




 a| 
link:../tiebreaker/concept_overview_of_the_tiebreaker_software.html["MetroCluster Tiebreaker 1.21 ソフトウェアのインストールと設定"]
 a| 
* MetroCluster Tiebreaker ソフトウェアを使用して MetroCluster 構成を監視する




 a| 
Active IQ Unified Manager のドキュメント https://www.netapp.com/support-and-training/documentation/["ネットアップのマニュアル：製品ガイドとリソース"^]
 a| 
* MetroCluster の設定とパフォーマンスを監視する




 a| 
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-7mtt-dctg/home.html["コピーベースの移行"]
 a| 
* 7-Mode ストレージシステムから clustered Data ONTAP ストレージシステムへデータを移行する


|===