---
permalink: manage/task_verify_SVMs are_running_and_aggregates_are_online.html 
sidebar: sidebar 
keywords: switchover, dr, partner, ownership, disk, svm, online, confirm 
summary: スイッチオーバーが完了したら、 DR パートナーがディスクの所有権を取得し、パートナー SVM がオンラインになったことを確認する必要があります。 
---
= SVMが実行されていて、アグリゲートがオンラインになっていることを確認してください
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
スイッチオーバーが完了したら、 DR パートナーがディスクの所有権を取得し、パートナー SVM がオンラインになったことを確認する必要があります。

MetroCluster のスイッチオーバー後に storage aggregate plex show コマンドを実行すると、スイッチオーバーされたルートアグリゲートの plex0 のステータスが確定していないため、失敗と表示されます。この間、スイッチオーバーされたルートは更新されません。このプレックスの実際のステータスは、 MetroCluster 修復フェーズ後に確定します。

.手順
. storage aggregate show コマンドを使用して、アグリゲートがスイッチオーバーされたことを確認します。
+
この例では、アグリゲートがスイッチオーバーされています。ルートアグリゲート（ aggr0_b2 ）はデグレード状態、データアグリゲート（ b2_aggr2 ）はミラーされた正常な状態になっています。

+
[listing]
----
cluster_A::*> storage aggregate show

.
.
.
mcc1-b Switched Over Aggregates:
Aggregate     Size Available Used% State   #Vols  Nodes            RAID Status
--------- -------- --------- ----- ------- ------ ---------------- ------------
aggr0_b2    227.1GB   45.1GB    80% online       0 node_A_1        raid_dp,
                                                                   mirror
                                                                   degraded
b2_aggr1    227.1GB   200.3GB    20% online       0 node_A_1       raid_dp,
                                                                   mirrored
                                                                   normal
----
. vserver show コマンドを使用して、セカンダリ SVM がオンラインになったことを確認します。
+
この例では、これまで休止状態だったセカンダリサイトの同期先 SVM がアクティブで、 Admin State は running になっています。

+
[listing]
----
cluster_A::*> vserver show
                                          Admin      Operational  Root                 Name    Name
Vserver           Type  Subtype           State      State        Volume    Aggregate  Service Mapping
-----------       ----- ----------        ---------- -----------  --------- ---------- ------- -------
...
cluster_B-vs1b-mc data   sync-destination  running   running      vs1b_vol   aggr_b1   file    file
----

