---
permalink: manage/task_perform_a_negotiated_switchover.html 
sidebar: sidebar 
keywords: negotiate, switchover, clean, shut, down, partner, site, operation, metrocluster, perform 
summary: ネゴシエートスイッチオーバーは、パートナーサイトのプロセスをクリーンシャットダウンしてから、パートナーサイトの処理をスイッチオーバーします。ネゴシエートスイッチオーバーは、 MetroCluster サイトでのメンテナンスの実施、またはスイッチオーバー機能のテストに使用できます。 
---
= ネゴシエートスイッチオーバーの実行
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ネゴシエートスイッチオーバーは、パートナーサイトのプロセスをクリーンシャットダウンしてから、パートナーサイトの処理をスイッチオーバーします。ネゴシエートスイッチオーバーは、 MetroCluster サイトでのメンテナンスの実施、またはスイッチオーバー機能のテストに使用できます。

* スイッチバック処理を実行する前に、設定の変更がすべて完了している必要があります。
+
これにより、ネゴシエートスイッチオーバーまたはスイッチバックの処理との競合が回避されます。

* 停止していたノードがブートし、クラスタクォーラムに参加している必要があります。
+
クラスタ・クォーラムの詳細については ' 定足数と Epsilon についての項を参照してください

+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-sag/home.html["システム管理"]

* 両方のサイトからクラスタピアリングネットワークにアクセスできる必要があります。
* MetroCluster 構成のすべてのノードで、同じバージョンの ONTAP ソフトウェアが実行されている必要があります。
* 新しい SnapMirror 関係を作成する前に、 MetroCluster 構成の両方のサイトで replication.create_data_protection_rels.enable オプションを ON に設定しておく必要があります。
* 2 ノード MetroCluster 構成の場合、サイト間で ONTAP のバージョンが一致していないときは、アップグレード時に新しい SnapMirror 関係を作成しないようにする必要があります。
* 4 ノード MetroCluster 構成の場合、サイト間で ONTAP のバージョンが一致している必要があります。


リカバリサイトがスイッチバック処理を実行できるようになるまでに数時間かかることがあります。

MetroCluster switchover コマンドは、 MetroCluster 構成のすべての DR グループで、ノードをスイッチオーバーします。たとえば、 8 ノードの MetroCluster 構成では、両方の DR グループでノードがスイッチオーバーされます。

ネゴシエートスイッチオーバーの準備中および実行中は、クラスタの設定を変更したり、テイクオーバーまたはギブバック処理を実行したりしないでください。

MetroCluster FC 構成の場合：

* リモートストレージがアクセス可能である場合、ミラーされたアグリゲートは通常の状態のままになります。
* リモートストレージへのアクセスが失われると、ネゴシエートスイッチオーバー後にミラーアグリゲートがデグレード状態になります。
* リモートストレージへのアクセスが失われると、ディザスタサイトにあるミラーされていないアグリゲートは使用できなくなります。これにより、コントローラが停止する可能性があります。


MetroCluster IP 構成の場合：


NOTE: メンテナンスタスクを実行する前に、 Tiebreaker またはメディエーターユーティリティで MetroCluster 設定を監視している場合は、監視を解除する必要があります。link:../maintain/concept_remove_mediator_or_tiebreaker_when_performing_maintenance_tasks.html["メンテナンス作業を実行する前に、 ONTAP メディエーターまたは Tiebreaker の監視を削除します"]

* ONTAP 9.4 以前：
+
** ミラーアグリゲートはネゴシエートスイッチオーバー後にデグレード状態になります。


* ONTAP 9.5 以降：
+
** リモートストレージがアクセス可能である場合、ミラーされたアグリゲートは通常の状態のままになります。
** リモートストレージへのアクセスが失われると、ネゴシエートスイッチオーバー後にミラーアグリゲートがデグレード状態になります。


* ONTAP 9.8 以降の場合：
+
** リモートストレージへのアクセスが失われると、ディザスタサイトにあるミラーされていないアグリゲートは使用できなくなります。これにより、コントローラが停止する可能性があります。
+
... MetroCluster check run 、 MetroCluster check show 、および MetroCluster check config-replication show の各コマンドを使用して、進行中または保留中の設定更新がないことを確認します。問題：稼働したままにするサイトからのコマンドです。
... 稼働したままにするサイトから ' スイッチオーバーを実行します MetroCluster switchover
+
この処理が完了するまでに数分かかることがあります。

... スイッチオーバーの完了を監視します MetroCluster operation show
+
[listing]
----
cluster_A::*> metrocluster operation show
  Operation: Switchover
 Start time: 10/4/2012 19:04:13
      State: in-progress
   End time: -
     Errors:

cluster_A::*> metrocluster operation show
  Operation: Switchover
 Start time: 10/4/2012 19:04:13
      State: successful
   End time: 10/4/2012 19:04:22
     Errors: -
----
... SnapMirror 構成または SnapVault 構成があれば、再確立します。





