---
permalink: manage/task_verify_a_successful_switchback.html 
sidebar: sidebar 
keywords: perform, switchback, aggregate, storage, virtual, machine, svm, switch, back, online, verify, successful 
summary: スイッチバックを実行したあとに、すべてのアグリゲートと Storage Virtual Machine （ SVM ）がスイッチバックされてオンラインになっていることを確認します。 
---
= スイッチバックが成功したことを確認する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
スイッチバックの実行後に、すべてのアグリゲートと Storage Virtual Machine （ SVM ）がスイッチバックされてオンラインになっていることを確認します。

. スイッチオーバーされたデータアグリゲートがスイッチバックされたことを確認します。
+
「 storage aggregate show

+
次の例では、ノード B2 の aggr_b2 がスイッチバックされています。

+
[listing]
----
node_B_1::> storage aggregate show
Aggregate     Size Available Used% State   #Vols  Nodes            RAID Status
--------- -------- --------- ----- ------- ------ ---------------- ------------
...
aggr_b2    227.1GB   227.1GB    0% online       0 node_B_2   raid_dp,
                                                                   mirrored,
                                                                   normal
----
. サバイバークラスタの同期先のすべてのSVMが休止状態であることを確認します（動作状態が「`stopped`」と表示されています）。
+
`vserver show -subtype sync-destination`

+
[listing]
----
node_B_1::> vserver show -subtype sync-destination
                                 Admin    Operational  Root
Vserver       Type    Subtype    State    State        Volume    Aggregate
-----------   ------- ---------- -------- ----------   --------  ----------
...
cluster_A-vs1a-mc data sync-destination
                               running    stopped    vs1a_vol   aggr_b2

----
+
MetroCluster 構成の同期先アグリゲートの名前には、識別しやすいように「 -mc 」というサフィックスが自動的に付加されます。

. ディザスタクラスタの同期元SVMが稼働していることを確認します。
+
「 vserver show -subtype sync-source 」のようになります

+
[listing]
----
node_A_1::> vserver show -subtype sync-source
                                  Admin    Operational  Root
Vserver        Type    Subtype    State    State        Volume     Aggregate
-----------    ------- ---------- -------- ----------   --------   ----------
...
vs1a           data    sync-source
                                  running  running    vs1a_vol  aggr_b2

----
. MetroCluster operation show コマンドを使用して、スイッチバック操作が成功したことを確認します。
+
|===


| 出力内容 | 作業 


 a| 
スイッチバック処理の状態が「 successful 」である
 a| 
スイッチバックプロセスは完了しており、システムの処理を続行できます。



 a| 
スイッチバック処理またはスイッチバック継続エージェントの処理が「 partially successful 」である
 a| 
MetroCluster operation show コマンドの出力に記載されている推奨修正を実行します

|===


上記の手順を繰り返して、逆方向へのスイッチバックを実行する必要があります。site_A が site_B のスイッチオーバーを行った場合は、 site_B で site_A のスイッチオーバーを行います
