---
permalink: manage/task_send_a_custom_autosupport_message_prior_to_negotiated_switchover.html 
sidebar: sidebar 
keywords: perform, negotiate, switchover, autosupport, message, netapp, technical, support, maintenance, underway, failure, trigger, support, prevent, disruption, custom, prior 
summary: ネゴシエートスイッチオーバーを実行する前に、 AutoSupport メッセージを問題で送信して、メンテナンスが進行中であることをネットアップテクニカルサポートに通知する必要があります。ネゴシエートスイッチオーバーでは、プレックスや MetroCluster の処理が失敗して AutoSupport メッセージがトリガーされることがあります。システム停止が発生したとみなしてテクニカルサポートがケースをオープンしないように、メンテナンスが進行中であることを通知する必要があります。 
---
= カスタム AutoSupport メッセージの送信 - ネゴシエートスイッチオーバー前
:icons: font
:imagesdir: ../media/


[role="lead"]
ネゴシエートスイッチオーバーを実行する前に、 AutoSupport メッセージを問題で送信して、メンテナンスが進行中であることをネットアップテクニカルサポートに通知する必要があります。ネゴシエートスイッチオーバーでは、プレックスや MetroCluster の処理が失敗して AutoSupport メッセージがトリガーされることがあります。システム停止が発生したとみなしてテクニカルサポートがケースをオープンしないように、メンテナンスが進行中であることを通知する必要があります。

このタスクは MetroCluster サイトごとに実行する必要があります。

.手順
. Site_A のクラスタにログインします
. メンテナンスの開始を示す AutoSupport メッセージを起動します。「 system node AutoSupport invoke -node * -type all -message MAINT= maintenance-window-in-hours
+
maintenance-window-in-hours にはメンテナンス時間の長さを指定します。最大値は 72 時間です。この時間が経過する前にメンテナンスが完了した場合は、メンテナンス期間が終了したことを示すコマンドを問題に送信できます。「 system node AutoSupport invoke -node * -type all -message MAINT=end 」

. 同じ手順をパートナーサイトでも実行します。

