---
permalink: manage/task_heal_the_configuration_in_a_mcc_ip_configuration_ontap_9_4_and_earlier.html 
sidebar: sidebar 
keywords: heal, aggregate, preparation, switchback, operation, configuration, metrocluster, ip, ontap 
summary: スイッチバック処理の準備として、アグリゲートを修復する必要があります。 
---
= MetroCluster IP 構成での構成の修復（ ONTAP 9.4 以前）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
スイッチバック処理の準備として、アグリゲートを修復する必要があります。


NOTE: ONTAP 9.5 を実行している MetroCluster IP システムでは、自動的に修復が実行されるため、これらのタスクを省略できます。

修復手順を実行するには、次の条件を満たしている必要があります。

* スイッチオーバーを実行済みで、サバイバーサイトがデータを提供している必要があります。
* ディザスタサイトのストレージシェルフの電源がオンで稼働しており、アクセス可能である必要があります。
* ISL が稼働中である必要があります。
* サバイバーサイトのノードが HA フェイルオーバー状態でない（両方のノードが稼働中である）必要があります。


このタスクでは、 ONTAP 9.5 より前のバージョンを実行している環境 MetroCluster IP 構成のみを行います。

この手順は、 MetroCluster FC 構成の修復手順とは異なります。

.手順
. スイッチオーバーされたサイトの各コントローラモジュールの電源をオンにして、完全にブートします。
+
システムに LOADER プロンプトが表示されたら、「 boot_ontap 」コマンドを実行します。

. ルートアグリゲートの修復フェーズ「 MetroCluster heal root-aggregates 」を実行します
+
[listing]
----
cluster_A::> metrocluster heal root-aggregates
[Job 137] Job succeeded: Heal Root-Aggregates is successful
----
+
修復が拒否された場合は、 MetroCluster heal-rootaggregates コマンドを --override-vetoes パラメータで再実行できます。このオプションパラメータを使用すると、修復処理を妨げるソフトな拒否はすべて無視されます。

. アグリゲートを再同期します。「 MetroCluster heal aggregates 」
+
[listing]
----
cluster_A::> metrocluster heal aggregates
[Job 137] Job succeeded: Heal Aggregates is successful
----
+
修復が拒否された場合は、 -override-vetoes パラメータを指定して MetroCluster heal コマンドを再実行できます。このオプションパラメータを使用すると、修復処理を妨げるソフトな拒否はすべて無視されます。

. 正常なクラスタで MetroCluster operation show コマンドを実行して、修復処理が完了したことを確認します。
+
[listing]
----

cluster_A::> metrocluster operation show
  Operation: heal-aggregates
      State: successful
 Start Time: 7/29/2017 20:54:41
   End Time: 7/29/2017 20:54:42
     Errors: -
----

